"""SEN0401 chapter 6, corpus text part G (version 1.0.0): the branch 'Lock time and the coinbase' - the last four bytes of a
transaction and the three ways they are read (any block, a block height, an epoch time compared with the median time past), and the
first transaction of every block with its null outpoint, its coinbase field, the subsidy schedule, the block reward and the maturity
rule. Markers become author-year strings."""
from sen0401_ch06_common_v1_0_0 import *

NODES_G = [
 ("LockTimeAndCoinbase", "Lock time and the coinbase", 1, None, None, P(
  (W, "This branch covers the last field of every transaction and the first transaction of every block. The book says the final field in a serialized transaction is its lock time, which was part of the original format but initially only enforced by Bitcoin's policy for choosing which transactions to mine, until Bitcoin's earliest known soft fork made it a rule from block 31,000; and that the first transaction in each block is a special case, called a generation transaction in older documentation and a coinbase transaction in newer [AH]."),
  (Y, "The two subjects share a theme, time and height as conditions on validity. The lock time says the earliest block or time at which a transaction may be included; the coinbase's maturity rule says how long its outputs must wait before they can be spent; and both rely on the median time past and the block height that the outpoint group said a node records for every output. The coinbase is also where new bitcoins enter, under a schedule this branch computes [AH] [BCL]."),
  (E, "The reader meets the lock time as the four zero bytes that end most transactions, and as the field a wallet sets to the current height to discourage fee sniping, which is what the transaction that paid Alice did with a lock time of 774,957 [MP]. The coinbase is met at the top of every block an explorer shows, with its subsidy and its fees, and in the news every four years when the subsidy halves."),
  (H, "The branch has two groups. The lock time group reads the field and its three readings - zero for any block, a value below 500,000,000 as a block height, and a larger value as an epoch time compared with the median time past of eleven blocks. The coinbase group reads the special rules: one input with a null outpoint, a coinbase field of 2 to 100 bytes, outputs that may not exceed the fees plus the subsidy, the subsidy schedule of halvings, the block reward, and the maturity rule of 100 confirmations [AH] [BCT] [BCL].")), None),

 ("LockTime", "Lock time", 2, "LockTimeAndCoinbase", None, P(
  (W, "The lock time is the four-byte field that ends every transaction. The book says it was part of Bitcoin's original serialization format but was initially only enforced by policy, and that the earliest known soft fork added a rule that, starting at block height 31,000, forbids the inclusion of a transaction in a block unless its lock time is zero, or is a height the block has reached, or is a time the block's median time past has passed [AH]. This group reads the field and each of its three cases."),
  (Y, "The lock time matters because it is the oldest timelock in Bitcoin and the one the opcode of BIP65 later built on: a transaction can be made unusable until a date, which is what makes a presigned refund safe to hand over, since it cannot be broadcast early [AH] [B65]. It is also an example of the chapter's recurring pattern of a feature first enforced by policy and then by consensus, and of a field whose encoding packs two meanings into one number by a threshold."),
  (H, "The four sections take the field, then its two non-zero readings, then the clock those readings compare against. The lock-time field section states the rule and its history; the height lock section computes the book's example of 123,456; the time lock section explains epoch time and the 500,000,000 threshold; and the median time past section computes the median of eleven block times, the quantity BIP113 made the reference for time locks, and explains why it runs an hour or two behind [AH] [B113] [BCH].")), None),

 ("LockTimeField", "The lock time field", 3, "LockTime", ("zero: eligible for any block", "The lock time is the last 4 bytes of a transaction; zero makes it eligible for any block, and since block 31,000 a non-zero value is a consensus rule restricting which blocks may include it.", ("int.from_bytes(bytes.fromhex('00000000'), 'little')", "0")), P(
  (W, "The lock time field is the final field in a serialized transaction. The book says it was part of Bitcoin's original serialization format but initially only enforced by Bitcoin's policy for choosing which transactions to mine, and that Bitcoin's earliest known soft fork added a rule that, starting at block height 31,000, forbids the inclusion of a transaction in a block unless it satisfies one of three rules, the first being that a lock time of zero makes it eligible for inclusion in any block [AH]. Alice's transaction ends with four zero bytes."),
  (Y, "The field matters as the simplest way to say not before. A transaction with a lock time in the future is valid in form but cannot be confirmed yet, so it can be signed and handed over without the holder being able to use it early; and because the rule is consensus, no miner can include it ahead of time. Bitcoin Core's IsFinalTx implements the check, with one exception the sequence branch mentioned: if every input's sequence is the final value, the lock time is ignored, a remnant of the original replacement scheme in which a final transaction needed no further waiting [BCV]."),
  (H, "The worked example reads the four bytes of Alice's lock time as the little-endian integer zero. For a non-zero value the node compares it with the block: the next section's height reading if it is below 500,000,000, the time reading otherwise, and the transaction is final when the lock time is strictly less than the block's height or the block's median time past, which is why a lock time of 123,456 is first satisfied by block 123,456 - the comparison is against the height after it, as the book's example and Bitcoin Core's comparison agree [AH] [BCV]."),
  (K, "The caution is the interaction with the sequence field: a lock time is honoured only if at least one input's sequence is below the final value, so a wallet that wants a lock time must also lower a sequence, which is why many wallets use 0xfffffffe. A second caution is the word earliest: a lock time cannot expire a transaction, only delay it, and the book's note on coinbase maturity makes the same point from the other side [AH].")), None),

 ("HeightLock", "Lock time as a block height", 3, "LockTime", ("123,456 means block 123,456 or later", "A lock time below 500,000,000 is a block height: the transaction can only be included in a block whose height is equal to the lock time or higher, so 123,456 allows block 123,456 and any later one.", ("(lambda lt, h: lt < 500_000_000 and h >= lt)(123456, 123456)", "True")), P(
  (W, "A lock time below 500,000,000 is read as a block height. The book's second rule: the transaction indicates that it wants to restrict which blocks it can be included in by setting its lock time to a value less than 500,000,000, and in this case the transaction can only be included in a block that has a height equal to the lock time or higher; a transaction with a lock time of 123,456 can be included in block 123,456 or any later block [AH]."),
  (Y, "The height reading is the precise one, since the chain's height advances by exactly one per block, and it is the one wallets use most. The transaction that paid Alice, confirmed in block 774,958, carries a lock time of 774,957, the height of the chain when it was built; setting the lock time to the current height is a common wallet practice that prevents the transaction from being included in a reorganised earlier block, a defence against what is called fee sniping [MP] [BCV]. The worked example checks the book's example at the boundary."),
  (H, "Bitcoin Core's IsFinalTx compares the lock time with the height of the block being validated, which is one more than the height of the chain tip when the transaction was built: a lock time of 774,957 is satisfied by block 774,958, because 774,957 is less than 774,958 [BCV]. The threshold itself is the constant LOCKTIME_THRESHOLD, 500,000,000, which Bitcoin Core's script header annotates with the date it corresponds to as a time, 5 November 1985 [BCS]. Heights will not reach it for thousands of years, which is what makes the two readings separable."),
  (K, "The caution is the off-by-one that the book's example settles: a lock time of n allows block n, not block n plus one, because the comparison is strict against the block's own height. A second caution is that the height reading has no notion of time at all, so a transaction locked to a height may become valid earlier or later than expected if blocks arrive faster or slower than ten minutes apart.")), None),

 ("TimeLock", "Lock time as an epoch time", 3, "LockTime", ("500,000,000 or more is a timestamp", "A lock time of 500,000,000 or more is an epoch time, seconds since 1970-01-01T00:00 UTC; the transaction can only be included in a block whose median time past is greater than the lock time.", ("(lambda lt: 'epoch time' if lt >= 500_000_000 else 'block height')(1675559245)", "'epoch time'")), P(
  (W, "A lock time of 500,000,000 or more is read as a time. The book's third rule: the transaction indicates that it wants to restrict when it can be included in the blockchain by setting its lock time to a value of 500,000,000 or greater, in which case the field is parsed as epoch time, the number of seconds since 1970-01-01T00:00 UTC, and the transaction can only be included in a block with a median time past greater than the lock time [AH]."),
  (Y, "The time reading matters for agreements made in human terms, a refund valid from a date rather than from a height. Epoch time is the convention of counting seconds from the start of 1970 that most computers use; the block time of Alice's transaction's block, 1,675,559,245, is such a number and the worked example classifies it as a time. The reading is enforced against the median time past, not against the block's own timestamp, a change BIP113 made so that a miner cannot satisfy a lock by writing a later time in a block header [B113]."),
  (H, "The threshold 500,000,000 separates the two readings because, as a time, it is 5 November 1985, before Bitcoin existed, and as a height it is thousands of years away, so no value is ambiguous [BCS]. Bitcoin Core's IsFinalTx chooses the comparison by the threshold and tests that the lock time is less than the block's time or height, with the block's time taken as its median time past when the BIP113 rule is active, which it has been since the same activation as BIP68 [BCV] [BCD]."),
  (K, "The caution is that the median time past is normally an hour or two behind the current time, as the book says, so a time lock set for noon is usually satisfiable only in the early afternoon; a protocol that needs precision must allow for it [AH]. A second caution is that the two readings cannot be mixed in one transaction, and BIP65's opcode fails when the lock-time type of its argument differs from that of the transaction's field [B65].")), None),

 ("MedianTimePast", "Median time past", 3, "LockTime", ("the middle of eleven block times", "The median time past (MTP) of a block is the median of the timestamps of the last eleven blocks; time locks are compared with it, and it is normally an hour or two behind the clock.", ("sorted([1675558000, 1675558600, 1675557000, 1675559245, 1675558900, 1675556500, 1675559100, 1675558300, 1675557700, 1675558800, 1675559000])[5]", "1675558600")), P(
  (W, "The median time past is the quantity a time lock is compared against. The book introduces it in the third lock-time rule - a transaction with a time lock can only be included in a block with a median time past greater than the lock time - and says MTP is normally about an hour or two behind the current time, deferring the rules to its chapter on the blockchain [AH]. Bitcoin Core computes it in GetMedianTimePast as the median of the timestamps of the last eleven blocks [BCH]."),
  (Y, "The median matters because block timestamps are chosen by miners and are only loosely constrained. A single block's time can be early or late, so a lock compared against it could be satisfied early by a miner who writes a later time; the median of eleven is much harder to move, since a miner would need to control six of the last eleven blocks. BIP113 made the median the endpoint of lock-time calculations for exactly this reason, and BIP68 uses the same median for time-based relative locks [B113] [B68]."),
  (H, "The worked example sorts eleven timestamps and takes the sixth, the median; Bitcoin Core walks back eleven blocks from the tip, sorts their times and returns the middle element [BCH]. Because a block's time must exceed the median of the eleven before it, the median is monotonic even when individual timestamps are not, which is why it is a safe clock for consensus. The hour-or-two lag follows from the arithmetic: the median of eleven blocks is about six blocks old, which at ten minutes a block is about an hour."),
  (K, "The caution is that the median time past is a property of the chain, not of the world: it can be well behind real time when blocks come slowly and can never run ahead of the latest block times. A second caution is that the lag means a time lock expressed in wall-clock time is honoured conservatively, later rather than earlier, which is the right direction for a lock but a surprise to someone expecting the clock on the wall.")), None),

 ("CoinbaseTransaction", "Coinbase transactions", 2, "LockTimeAndCoinbase", None, P(
  (W, "The coinbase transaction is the first transaction in each block. The book says it is a special case, that most older documentation calls it a generation transaction and most newer documentation a coinbase transaction, not to be confused with the company of that name, and that it is created by the miner of the block that includes it, giving the miner the option to claim any fees paid by transactions in that block and, up until block 6,720,000, a subsidy of bitcoins that have never been circulated [AH]."),
  (Y, "The group matters because the coinbase is the only transaction that creates bitcoins, and every rule that limits creation is a rule about it: the subsidy schedule, the sum of its outputs, and the maturity that keeps freshly created coins from being spent until the block is secure. It also uses the fields of this chapter in a special way, which the book lists: one input, a null outpoint, a coinbase field in place of an input script, and since segwit an output that commits to the block's witnesses [AH]."),
  (H, "The six sections follow the book's list of special rules. The coinbase transaction section states the role and the names; the null outpoint section reads the all-zero txid and maximal index; the coinbase field section explains the 2-to-100-byte field that gives the transaction its name and the BIP34 height it must begin with; the block subsidy section computes the halving schedule; the block reward section adds the fees; and the maturity rule section explains the 100 confirmations [AH] [BCT] [BCL] [BCC].")), None),

 ("Coinbase", "Coinbase transaction", 3, "CoinbaseTransaction", ("first in the block, made by the miner", "The coinbase transaction is the first transaction of a block, created by its miner to claim the block's fees and, until the subsidy runs out, newly created bitcoins; older documents call it a generation transaction.", ("['the first transaction in the block', 'created by the miner', 'claims the fees and the subsidy']", "['the first transaction in the block', 'created by the miner', 'claims the fees and the subsidy']")), P(
  (W, "The coinbase transaction is the first transaction in each block, a special case that the book says most older documentation calls a generation transaction and most newer documentation a coinbase transaction, not to be confused with transactions created by the company named Coinbase. It is created by the miner of the block that includes it and gives the miner the option to claim any fees paid by transactions in that block, and additionally, up until block 6,720,000, a subsidy of bitcoins that have never previously been circulated [AH]."),
  (Y, "The coinbase matters as the source of every bitcoin: every output that any transaction has ever spent traces back, through chains of outpoints, to a coinbase output, which is why the book says the maturity rule and the subsidy schedule are enforced on it. It is also the one transaction a node cannot check against previous outputs, since it spends none, so its validity is a matter of the block it sits in - its fees and its height - rather than of the UTXO database [AH] [BCL]."),
  (H, "The book lists the special rules: a coinbase may only have one input; that input's outpoint must have a null txid and the maximal index; the field that would hold an input script is the coinbase field, between 2 and 100 bytes, not executed but subject to the legacy limits on signature-checking operations, and since BIP34 beginning with the block height; the sum of the outputs must not exceed the fees plus the subsidy; and since the 2017 segwit soft fork a block that contains a segwit spend must have a coinbase output committing to all the transactions including their witnesses [AH]. The worked example lists its three defining properties."),
  (K, "The caution is the book's closing remark: most Bitcoin software does not need to deal with coinbase transactions, but their special nature means they can occasionally cause unusual problems in software not designed to expect them - a parser that assumes every outpoint names a real output, or a wallet that counts an immature output as spendable [AH]. A second caution is that Bitcoin Core refuses a coinbase outside a block entirely: as a loose transaction it is invalid with the single word coinbase as its reason [BCL].")), None),

 ("NullOutpoint", "The null outpoint", 3, "CoinbaseTransaction", ("32 zero bytes and index 0xffffffff", "A coinbase transaction's single input must have an outpoint with a null txid of all zeros and the maximal output index 0xffffffff, so that it cannot reference a previous output.", ("(bytes(32).hex() == '00' * 32, int.from_bytes(bytes.fromhex('ffffffff'), 'little') == 0xffffffff, 0xffffffff)", "(True, True, 4294967295)")), P(
  (W, "The null outpoint is the outpoint of a coinbase transaction's only input. The book says the single input must have an outpoint with a null txid, consisting entirely of zeros, and a maximal output index, 0xffffffff, and that this prevents the coinbase transaction from referencing a previous transaction output, which would at the very least be confusing given that the coinbase pays out fees and subsidy [AH]. Bitcoin Core's IsCoinBase test is exactly this: one input whose previous outpoint is null [BCX]."),
  (Y, "The null outpoint matters because it is how the format marks the one transaction that creates rather than transfers. Every other transaction's inputs name outputs that exist; the coinbase's input names nothing, and a node recognises the coinbase by that. Bitcoin Core's CheckTransaction enforces the converse too: for a transaction that is not a coinbase, any input with a null outpoint is refused with bad-txns-prevout-null, so a null outpoint can appear nowhere else [BCT]."),
  (H, "The worked example states the two parts, 32 zero bytes and the maximal four-byte index, and the index as a number. The chapter's library's is_coinbase test reads a parsed transaction and checks all three conditions - one input, a zero txid, a maximal index - and an executed claim confirms that neither Alice's transaction nor the first bitcoin transaction is a coinbase, while a transaction constructed with the null outpoint is. The maximal index is also the value an outpoint can never legitimately hold, since no transaction has four billion outputs."),
  (K, "The caution is that the null outpoint's 36 bytes are still serialized and still weigh: a coinbase input is the same shape as any other, which is why the book lists the rule as a constraint on the outpoint rather than as its absence. A second caution is that the input's sequence field exists too and is exempt from BIP68, as the sequence branch noted; miners use it, together with the coinbase field, as extra space for the numbers they vary while searching for a valid block [B68].")), None),

 ("CoinbaseField", "The coinbase field", 3, "CoinbaseTransaction", ("2 to 100 bytes, beginning with the height", "The coinbase field is the coinbase transaction's input-script field, 2 to 100 bytes long, not executed, and since BIP34 beginning with a push of the block height; it gives the transaction its name.", ("(lambda field: (len(field), 2 <= len(field) <= 100, field[0], int.from_bytes(field[1:1 + field[0]], 'little')))(bytes.fromhex('03e0e60b') + b'/example miner/')", "(19, True, 3, 780000)")), P(
  (W, "The coinbase field is the field that would contain an input script in a normal transaction. The book says it is called a coinbase, that it is this field that gives the coinbase transaction its name, that it must be at least two bytes and not longer than 100, that it is not executed but legacy limits on the number of signature-checking operations apply to it so arbitrary data should be prefixed by a data-pushing opcode, and that since a 2013 soft fork defined in BIP34 its first few bytes must follow additional rules [AH] [B34]."),
  (Y, "The field matters as the only free space in a block that a miner may fill: it carries the block height, extra nonce values the miner varies, and often a text tag naming the mining pool, which is how explorers know who mined a block. BIP34 requires the height so that no two coinbase transactions can be identical, which closes the duplicate-transaction problem that BIP30 addressed after two early coinbases were found to be byte-for-byte the same [B34] [B30]. Bitcoin Core enforces the length with bad-cb-length [BCT]."),
  (H, "The worked example builds a field of a three-byte push of the height 780,000 followed by a tag, and checks its length, its bounds, the push length and the height. BIP34 specifies the height as a script number pushed by the usual push opcode, which is the 03 followed by the three little-endian bytes e0 e6 0b in the example [B34]. Bitcoin Core's chain parameters record that the BIP34 rule became mandatory on the main network at block 227,931, which its documentation dates to March 2013 [BCK] [BCD]."),
  (K, "The caution is in the book's phrase not executed: the field is never run as a script, so it can contain anything, but the sigop counting of the legacy rules still scans it for opcodes, which is why data should sit behind a push opcode that the scanner skips. A second caution is that the field's 100-byte limit is for the field alone; the extra nonce and the tag share it with the height.")), None),

 ("BlockSubsidy", "Block subsidy", 3, "CoinbaseTransaction", ("50 BTC, halved every 210,000 blocks", "The block subsidy is the newly created bitcoin a coinbase may claim: 50 BTC at first, halved every 210,000 blocks and rounded down to the satoshi, so that the total issued is just under 21 million.", (PROG("subsidy = lambda h: (50 * 100_000_000) >> (h // 210_000) if h // 210_000 < 64 else 0\nresult = (subsidy(0) / 1e8, subsidy(840_000) / 1e8, subsidy(6_720_000), subsidy(6_929_999), subsidy(6_930_000))"), "(50.0, 3.125, 1, 1, 0)")), P(
  (W, "The block subsidy is the part of a coinbase's claim that consists of bitcoins that have never previously been circulated. The book says the subsidy started at 50 BTC per block and halves every 210,000 blocks, approximately every four years, with values rounded down to the nearest satoshi, and it dates the subsidy to block 6,720,000 [AH]. Bitcoin Core's GetBlockSubsidy computes it as 50 times COIN shifted right once per 210,000 blocks, and zero once the shift would be undefined after 64 halvings [BCL] [BCK]."),
  (Y, "The subsidy matters because it is the only source of new bitcoins and the reason the total is bounded. Halving a quantity repeatedly sums to twice its first value, so 210,000 blocks of 50 bitcoins, halved for ever, approach 21 million; the rounding down to a satoshi at each halving makes the actual total slightly less, and the chapter's library sums the whole schedule to 20,999,999.9769 bitcoins, which an executed claim records. Chapter 1 gave the 21 million figure; this is the arithmetic behind it."),
  (H, "The worked example writes the formula in one line and evaluates it at five heights: 50 at the start, 3.125 after the fourth halving at block 840,000, and one satoshi at block 6,720,000, where the 32nd halving leaves 5,000,000,000 shifted right 32 places. The subsidy is still one satoshi at block 6,929,999 and becomes zero at block 6,930,000, the 33rd halving, so the last block with any subsidy is 6,929,999; the book's figure of 6,720,000 is the height from which the subsidy is a single satoshi, not the height at which it ends, a difference an executed claim measures [AH] [BCL]."),
  (K, "The caution is that the schedule is enforced on the coinbase's outputs rather than written in them: a miner may claim less than the subsidy, and some have, by mistake, leaving satoshis uncreated for ever, which is a second reason the total will be below 21 million. A second caution is the word approximately in every four years: the halving is a count of blocks, and blocks arrive faster or slower than ten minutes apart, so the dates drift.")), None),

 ("BlockReward", "Block reward", 3, "CoinbaseTransaction", ("fees plus subsidy, as a ceiling", "The block reward is the total a miner can claim for a block, the fees of its transactions plus the subsidy; the coinbase's outputs may sum to no more than it.", ("(lambda fees, subsidy, claimed: (fees + subsidy, claimed <= fees + subsidy))(5000 + 12000 + 3000, 312_500_000, 312_520_000)", "(312520000, True)")), P(
  (W, "The block reward is the total amount a miner can claim for a block, which the book defines as the combination of fees and subsidy, and the rule on it is one of the coinbase's special rules: the sum of the outputs must not exceed the value of the fees collected from all the transactions in that block plus the subsidy [AH]. Bitcoin Core computes the reward as the fees plus GetBlockSubsidy and refuses a block whose coinbase pays more with bad-cb-amount, the message saying coinbase pays too much [BCL]."),
  (Y, "The reward matters because it is where the fees of this chapter's transactions go. Alice's transaction left 5,000 satoshis unassigned; that difference is not lost but is claimable by the miner of block 775,072 in that block's coinbase, together with the fees of every other transaction in the block and the subsidy of the time, 6.25 bitcoins at that height [MP] [BCL]. The reward is a ceiling, not a floor: a miner may claim less, and the book's chapter on mining explains why a miner would never want to."),
  (H, "The worked example adds three fees to a subsidy of 3.125 bitcoins and checks a claim against the sum. A node computes the fees as the sum over the block's transactions of inputs minus outputs, which requires the UTXO database for every input, so the reward check is the last step of validating a block rather than the first. The reward is also why the coinbase has the maximal output index and null txid: its value comes from the block, not from an outpoint [AH]."),
  (K, "The caution is that the reward is a property of a block, not of a transaction: the same coinbase transaction would be invalid in a block with fewer fees. A second caution is that the subsidy and the fees are not separated in the coinbase's outputs; the outputs simply sum to at most the reward, and an explorer that shows them separately is computing the fees itself.")), None),

 ("MaturityRule", "Maturity rule", 3, "CoinbaseTransaction", ("100 confirmations before spending", "The maturity rule says a transaction spending a coinbase output cannot be included in any block until the coinbase has 100 confirmations; outputs with fewer are called immature.", ("(lambda coinbase_height, spend_height: (spend_height - coinbase_height, spend_height - coinbase_height >= 100))(170 - 161, 170)", "(161, True)")), P(
  (W, "The maturity rule is the rule that a transaction spending one of a coinbase's outputs cannot be included in any block until after the coinbase transaction has received 100 confirmations. The book says a coinbase may have any other outputs that would be valid in a normal transaction, but that this restriction applies to spending them, and that coinbase outputs that do not yet have 100 confirmations are called immature [AH]. Bitcoin Core names the constant COINBASE_MATURITY, 100, and checks it in its input verification [BCC] [BCV]."),
  (Y, "The rule matters because a coinbase's value depends on its block staying in the chain. If a block is reorganised away, every transaction in it can be mined again in a later block - except the coinbase, which belongs to that block alone and vanishes with it; anything that had spent its outputs would vanish too. Making the outputs wait 100 blocks makes a reorganisation deep enough to remove them practically impossible, which the book's chapter on consensus develops [AH]."),
  (H, "The worked example applies the rule to the first bitcoin transaction of this chapter's stories: it spent the coinbase output of block 9 in block 170, 161 blocks later, which satisfies the rule. Bitcoin Core's check is that the spending height minus the coinbase's height must be at least 100, and the coinbase flag and height of every output are the metadata the UTXO database keeps for this purpose, as the outpoint group noted [BCV] [AH]. The first bitcoin transaction's input is therefore an outpoint to a coinbase, one the chapter's library parses."),
  (K, "The caution is that maturity is counted in confirmations of the coinbase, not of the spending transaction, and that the spend is invalid rather than merely delayed if included early; a miner who pays itself from a recent coinbase makes an invalid block. A second caution is that explorers and wallets must track the immature state, which the book's remark about software not designed to expect coinbases alludes to [AH].")), None),
]

CHECKS_G = [
 Qb("ch06_transactions.adoc", "starting at block height 31,000, forbid the inclusion of a", "transaction in a block unless it satisfies one of the following rules"),
 Qb("ch06_transactions.adoc", "a transaction with a lock time of 123,456 can be included in", "block 123,456 or any later block"),
 Qb("ch06_transactions.adoc", "epoch", "time (the number of seconds since 1970-01-01T00:00 UTC)", "MTP is normally about an hour or", "two behind the current time"),
 Qb("ch06_transactions.adoc", "Most older", "documentation calls this a _generation transaction_", "up until block 6,720,000,", "called", "the _block subsidy_", "is called the _block reward_"),
 Qb("ch06_transactions.adoc", "The single input must have an outpoint with a null txid (consisting entirely", "of zeros) and a maximal output index (0xffffffff)"),
 Qb("ch06_transactions.adoc", "The coinbase field must be at least two bytes", "and not longer than 100 bytes"),
 Qb("ch06_transactions.adoc", "The subsidy", "started at 50 BTC per block and halves every 210,000 blocks", "Subsidy values are rounded down to the", "nearest satoshi"),
 Qb("ch06_transactions.adoc", "This is called the", "_maturity rule_", "100 confirmations are called _immature_"),
 Qe("bip-0113.mediawiki", "Median time-past as endpoint for lock-time calculations"),
 Qe("bip-0034.mediawiki", "Height in Coinbase"),
 Qe("bip-0065.mediawiki", "the lock-time type (height vs. timestamp) of the top stack item and the nLockTime field are not the same"),
 Qc("src/script/script.h", "LOCKTIME_THRESHOLD{500'000'000}; // Tue Nov  5 00:53:20 1985 UTC"),
 Qc("src/chain.h", "static constexpr int nMedianTimeSpan = 11;"),
 Qc("src/consensus/consensus.h", "inline constexpr int COINBASE_MATURITY = 100;"),
 Qc("src/consensus/tx_check.cpp", "bad-cb-length", "bad-txns-prevout-null"),
 Qc("src/validation.cpp", "if (halvings >= 64)", "nSubsidy >>= halvings;", "bad-cb-amount", "coinbase pays too much"),
 Qc("src/kernel/chainparams.cpp", "consensus.nSubsidyHalvingInterval = 210000;", "consensus.BIP34Height = 227931;"),
 Qe("core_doc_bips.md", "version 1 blocks are no longer allowed since *block 227931* (March 25th 2013)"),
 X("T.parse_tx(%r)['locktime']" % ALICE, 0),
 X("(T.parse_tx(C.ev_hex('tx_alice_prev_4ac54180_v1_0_0.hex'))['locktime'], C.ev_json('mempool_tx_4ac5418026798669_v1_0_0.json')['status']['block_height'])", (774957, 774958)),
 X("[T.locktime_decode(v) for v in (0, 123456, 774957, 500000000, 1675559245)]", [('any block', 0), ('block height', 123456), ('block height', 774957), ('epoch time', 500000000), ('epoch time', 1675559245)]),
 X("(T.locktime_satisfied(123456, 123456, 0, [0]), T.locktime_satisfied(123456, 123455, 0, [0]), T.locktime_satisfied(123456, 123455, 0, [T.SEQUENCE_FINAL]))", (False, False, True)),
 X("T.locktime_satisfied(123456, 123457, 0, [0])", True),
 X("T.median_time_past([1675558000, 1675558600, 1675557000, 1675559245, 1675558900, 1675556500, 1675559100, 1675558300, 1675557700, 1675558800, 1675559000])", 1675558600),
 X("C.ev_json('mempool_tx_466200308696215b_v1_0_0.json')['status']['block_time']", 1675559245),
 X("(T.block_subsidy(0), T.block_subsidy(210000), T.block_subsidy(840000), T.block_subsidy(6720000), T.block_subsidy(6929999), T.block_subsidy(6930000))", (5000000000, 2500000000, 312500000, 1, 1, 0)),
 X("(T.last_subsidy_height(), T.total_subsidy(), T.total_subsidy() / T.COIN)", (6929999, 2099999997690000, 20999999.9769)),
 X("T.block_subsidy(775072)", 625000000),
 X("T.is_coinbase({'inputs': [{'txid': '00' * 32, 'vout': 0xffffffff}]})", True),
 X("(T.is_coinbase(T.parse_tx(%r)), T.is_coinbase(T.parse_tx(C.ev_hex('tx_first_f4184fc5_v1_0_0.hex'))))" % ALICE, (False, False)),
 X("(T.coinbase_field_ok('00'), T.coinbase_field_ok('0000'), T.coinbase_field_ok('00' * 100), T.coinbase_field_ok('00' * 101))", (False, True, True, False)),
 X("(T.coinbase_mature(9, 170), T.coinbase_mature(9, 108), T.coinbase_mature(9, 109), T.COINBASE_MATURITY)", (True, False, True, 100)),
 # the first bitcoin transaction spends the coinbase of block 9 (the explorer's record), 161 blocks later
 X("(C.ev_json('mempool_tx_f4184fc596403b9d_v1_0_0.json')['status']['block_height'], C.ev_json('mempool_tx_f4184fc596403b9d_v1_0_0.json')['vin'][0]['txid'][:16])", (170, '0437cd7f8525ceed')),
 ("(500_000_000 < 2 ** 32, 2 ** 32 - 1)", "(True, 4294967295)"),
 ("(5000000000 >> 32, 5000000000 >> 33, 210000 * 32, 210000 * 33)", "(1, 0, 6720000, 6930000)"),
 ("sum((5000000000 >> h) * 210000 for h in range(64)) / 1e8", "20999999.9769"),
 ("(11 // 2, sorted([3, 1, 2])[1])", "(5, 2)"),
]
