"""SEN0401 chapter 7, corpus text part D (version 1.0.0): the branch 'Pay to script hash' - what the 2012 output type is, the
redeem script that is revealed when the output is spent, the address of version byte 5, the benefits and the validation rules.
Markers such as [AH] become author-year strings (sen0401_ch07_common). Every number is computed by the chapter's library in CHECKS_D."""
from sen0401_ch07_common_v1_0_0 import *

BK = "ch07_authorization-authentication.adoc"
H_MOH = "54c557e07dde5bb6cb791c7a540e0a4796f5e97e"                    # the book's hash of Mohammed's redeem script
SS_P2SH = "00483045022100ba4c78ddef0abe9dcf336a60712045f8594c5c474d60639af56e3b992ec35989022045935caa747ea9ffc534e963af0d575a03aa4a8bec37494ad8e792a70929398b0147512103774ae7f858a9411e5ef4246b70c65aac5649980be5c17891bbec17895da008cb2103d01115d548e7561b15c38f004d734633687cf4419620095bc5b0f47070afe85a52ae"
SIGOPS = '''def sigops(words):
    n, prev = 0, None
    for w in words:
        if w in ('CHECKSIG', 'CHECKSIGVERIFY'): n += 1
        elif w in ('CHECKMULTISIG', 'CHECKMULTISIGVERIFY'): n += int(prev) if prev in [str(i) for i in range(1, 17)] else 20
        prev = w
    return n
'''

NODES_D = [
 ("PayToScriptHash", "Pay to script hash", 1, None, None, P(
  (W, "This branch is about the output type that lets a payer lock coins to the fingerprint of a script instead of to the script itself. The book says that pay to script hash, P2SH, was introduced in 2012 as a powerful new type of operation that greatly simplifies the use of complex scripts [AH]. The script is revealed only when the coins are spent, together with the data that satisfies it, and the network checks both that the script matches the fingerprint and that it succeeds."),
  (Y, "The branch matters because almost everything that came after it uses the same idea. A script hash output is the first example of a commitment: the payer commits to something without knowing it, the owner reveals it later, and everyone can check the match. The segregated witness outputs of a later branch, and the merkle trees of the taproot branch, repeat the pattern. BIP16 states its aim in one sentence: to move the responsibility for supplying the conditions to redeem a transaction from the sender of the funds to the redeemer [B16]."),
  (E, "A reader meets it as a legacy address that begins with a 3. In the saved block of 775,072 there are 139 inputs that spend such outputs, about 14 percent of the 1,022 inputs of its first 599 transactions: 10 reveal a 2-of-3 multisignature script, 95 reveal a nested witness key hash and 34 a nested witness script hash, so that the form is today mostly a wrapper for the upgrades of the next branches [MP]."),
  (H, "The branch has two groups. The first, the mechanism, explains the output script that holds the hash, the redeem script that is presented at spending time, and the address that lets any wallet pay to it. The second, the consequences, lists what P2SH gives its users and the rules that nodes apply to it. All the scripts in it are run by the chapter's library on real signatures, and the hash-and-address steps are checked against the values in the book."),
 ), None),

 ("P2shMechanism", "Hashing the script", 2, "PayToScriptHash", None, P(
  (W, "This group describes how a script becomes a hash and how the hash becomes an address and then a script again. The output script is OP_HASH160, the 20-byte hash of the script, and OP_EQUAL; the input script ends with the script itself, the redeem script, and the data it needs; the address is the Base58Check encoding of the hash with a version byte of 5 [AH] [B13]."),
  (Y, "The three parts divide the work between the people involved. The payer needs only the address and a standard output script; the receiver keeps the redeem script and its keys; the node checks the two together. Because each party sees only what it needs, a payer with an ordinary wallet can fund an arbitrarily complicated script."),
  (H, "The first section shows the shape of the output script and the two-stage check of the spend, the second the redeem script and what it must satisfy, and the third the address and its first character. The examples reuse the book's own numbers, the hash 54c557e0... of Mohammed's script and the address 39RF6JqA... that the book derives from it, and recompute them."),
  (K, "The hash does not tell anyone what the script is. A wallet that has lost the redeem script cannot spend a script hash output even if it still has every key, because the script is the thing the hash commits to. Backups of such wallets must keep the script, not only the keys."),
 ), None),


 ("PayToScriptHashOutput", "Pay to script hash output", 3, "P2shMechanism", ("OP_HASH160 <20-byte script hash> OP_EQUAL", "A pay to script hash output script holds only the 20-byte HASH160 of a script, so that whoever spends it must present a script that hashes to the same value and then satisfy that script.",
   (PROG("h = '" + H_MOH + "'                  # the hash the book gives for Mohammed's redeem script\nspk = 'a914' + h + '87'                       # OP_HASH160, push of 20 bytes, the hash, OP_EQUAL\nresult = (spk, len(spk) // 2)"), "('a91454c557e07dde5bb6cb791c7a540e0a4796f5e97e87', 23)")), P(
  (W, "A pay to script hash output replaces a long script with a commitment, the digest of a cryptographic hash. The book states the idea in simple terms: P2SH means pay to a script matching this hash, a script that will be presented later when this output is spent. The hash is made by applying SHA-256 and then RIPEMD-160 to the script, exactly as for a public key, so that it is 20 bytes however long the script is [AH]. BIP16 defines the output script as OP_HASH160, then the push-20-bytes opcode with exactly 20 bytes, then OP_EQUAL [B16]."),
  (Y, "The output exists to solve the problem the book illustrates with an importer in Dubai. Mohammed's company wants every customer payment locked by a 2-of-5 multisignature of himself, his three partners and their attorney. Without P2SH every customer would have to be given the long script and would need wallet software that builds custom scripts, the resulting transaction would be much bigger and its fee would be paid by the customer, and every full node would keep the long script in the set of unspent outputs until it was spent [AH]. With P2SH the customer pays to a short hash."),
  (E, "The output is 23 bytes on the chain: a byte 169 for OP_HASH160, a byte 20 to push the hash, the hash and a byte 135 for OP_EQUAL. The example builds the output script of Mohammed's company from the book's hash and shows that it is 23 bytes whatever the script behind it; Bitcoin Core's function IsPayToScriptHash recognises exactly this shape of 23 bytes, and its solver lists it as the type scripthash [BCS] [BCV]."),
  (H, "The spend is checked in two stages. First the input script is run and the redeem script, which is the last item it pushes, is checked against the output script, that is, its hash must equal the hash in the output. Then, if the match holds, the redeem script is taken off the stack and run on what remains, which is the data it needs, such as signatures. The book writes the first stage as the redeem script followed by OP_HASH160, the hash and OP_EQUAL, and the second as the signatures followed by the contents of the redeem script. The library runs both stages on a real 2-of-3 spend, and also with a one-byte redeem script."),
  (K, "The second stage does not exist for old software. A node from before 2012 sees only OP_HASH160, a hash and OP_EQUAL, and accepts any input script that pushes a script with the right hash, whether or not the script then succeeds. The library shows the same thing by running the spend of a redeem script that is always false with the P2SH rule switched off, which is accepted, and with the rule on, which fails. That is why the rule had to be activated by a majority of miners, a story the page tells later."),
 ), None),

 ("RedeemScript", "Redeem script", 3, "P2shMechanism", ("<sig> ... <redeem script>", "The redeem script is the script whose hash is committed to in a pay to script hash output; it is revealed as the last item of the input script when the output is spent and is then executed with the items that precede it.",
   (PROG("ss = bytes.fromhex('" + SS_P2SH + "')\nitems, pos = [], 0\nwhile pos < len(ss):\n    op = ss[pos]; pos += 1\n    n = op if op < 76 else ss[pos]               # a direct push, or OP_PUSHDATA1 and a length byte\n    if op == 76: pos += 1\n    items.append(ss[pos:pos + n]); pos += n\nresult = ([len(i) for i in items], items[-1][-1])"), "([0, 72, 71], 174)")), P(
  (W, "The redeem script is the script that a pay to script hash output stands for. The book says it is called that because it is presented to the system at redemption time rather than as an output script. In the book's tables the output script is the hash form, the redeem script is the long multisignature, and the input script is the signatures followed by the redeem script [AH]."),
  (Y, "The redeem script moves cost and complexity from the payer to the owner. The book lists the effects: the burden of storage moves from the output, which is kept by every node in the set of unspent outputs, to the input, which is only stored in the chain; it moves from the present, when the payment is made, to the future, when the output is spent; and the fees of the long script move from the sender to the recipient, who must include the redeem script to spend [AH]."),
  (E, "A reader meets a redeem script as the last push of a legacy input script of an output that starts with a 3. The example parses the input script of a 1-of-2 multisignature spend produced by the library: it starts with an empty push, the dummy of the previous branch, then a signature, and the last push is a redeem script of 71 bytes that ends with the byte 174, OP_CHECKMULTISIG. Bitcoin Core's function that recognises the spend reads the last pushed item as the redeem script in the same way when it counts signature operations [BCP]."),
  (H, "Because the redeem script is a push, the engine needs no new opcode to read it: after the first stage it takes the last item of the saved stack, turns it into a script and runs it on the remaining stack. BIP16 says exactly this: the serialized script is popped off the initial stack, and the transaction is validated again using the popped stack and the deserialized script as the scriptPubKey [B16]. In Bitcoin Core the code that does it is in VerifyScript, directly after the first run [BCI]."),
  (K, "The redeem script must be kept. Whoever pays to a script hash output cannot tell whether the script behind the hash is valid or can ever be satisfied, so the book warns that a P2SH output is accepted even if the redeem script is invalid, and that an output can be created that cannot be spent later [AH]. The 520-byte limit on a pushed item also applies to the redeem script, which is the reason a legacy multisignature stops at 15 keys."),
 ), None),

 ("P2shAddress", "P2SH address", 3, "P2shMechanism", ("version byte 5 gives an address that starts with 3", "A P2SH address is the Base58Check encoding of the 20-byte script hash with a version byte of 5, which makes it begin with the character 3.",
   (PROG(B58 + "h = bytes.fromhex('" + H_MOH + "')\nresult = b58check(5, h)"), "'39RF6JqABiHdYHkfChV6USGMe6Nsr66Gzw'")), P(
  (W, "A P2SH address is a way to write a script hash so that a person can copy it and a wallet can pay to it. The book says that P2SH addresses are Base58Check encodings of the 20-byte hash of a script, just like ordinary addresses are Base58Check encodings of the 20-byte hash of a public key, and that they use the version prefix 5, which results in addresses that start with a 3. The format was defined in BIP13 [AH] [B13]."),
  (Y, "The address is what makes P2SH usable. The book's example turns Mohammed's script into the address 39RF6JqABiHdYHkfChV6USGMe6Nsr66Gzw and observes that he can now give it to customers, who can use almost any wallet for a simple payment as to any other address; the 3 hints that it is special but otherwise it works in the same way. BIP16 gives the same reason: a fixed-length hash that is short enough to scan from a QR code or to copy and paste [B16]."),
  (E, "The example recomputes the book's address from its hash. It writes the version byte 5, the 20 bytes and the first four bytes of a double SHA-256 as a checksum, and encodes all 25 bytes in base 58, which gives 39RF6JqABiHdYHkfChV6USGMe6Nsr66Gzw, the address printed in the book. The library recomputes it in the checks and decodes two other addresses of the book, which belong to the nested forms of a later branch. The testnet version of the address uses a version byte of 196 and begins with a 2 [B13]."),
  (H, "The Base58Check steps are those of chapter 4 of the book: a version byte, the payload, a four-byte checksum taken from the double SHA-256 of both, and base 58. BIP13 writes it as the one-byte version, the 20-byte hash and the 4-byte checksum, and chose the version byte so that, after encoding, the leading character is consistent [B13] [AH4]. The address of a script hash and the address of a key hash differ only in the version byte, and so a typing error is caught by the checksum in the same way."),
  (K, "The address does not say what the script is, and a wallet cannot tell from the address whether the owner can spend it. The BIP13 text also admits that its address is not backward compatible: an old implementation reports the address as invalid and refuses to create a transaction, which is a failure that is safe. Segregated witness later changed the encoding to bech32 for its native outputs, but the nested forms keep the 3 form [B173] [AH]."),
 ), None),

 ("P2shConsequences", "What the hash changes", 2, "PayToScriptHash", None, P(
  (W, "This group draws together what P2SH changes for the people and the nodes that use it. For people, it is the four benefits the book lists; for nodes, it is a short set of rules about what an input script may contain, how a redeem script is judged and how many signature checks it may hide [AH] [B16]."),
  (Y, "The two sections belong together because each rule is the other face of a benefit. Moving the script to the spender makes it necessary to count the work it hides, and making the output opaque makes it possible to lock coins to a script that cannot be satisfied. A reader who knows both can say not only why P2SH was added but also what it costs."),
  (H, "The first section gives the benefits with the sizes recomputed for Mohammed's script; the second sets out the rules, runs each of them with the library and reports the policy limit of Bitcoin Core on the signature checks of a redeem script. The sections use BIP16 for the rules of 2012 and the source of Bitcoin Core at the pinned commit for the rules of today."),
  (K, "The rules were added to a live system with a soft fork, which means that an old node still accepts what the new rules reject. The BIP spends several paragraphs on the one-confirmation attack that this opens, and on the way miners were asked to signal support, which is why a part of this history appears in the stories of this chapter."),
 ), None),

 ("P2shBenefits", "Benefits of P2SH", 3, "P2shConsequences", ("the long script moves from the payer to the spender", "P2SH makes a complex payment as easy as an ordinary one for the payer and shifts the storage and the fee of the long script to the later spender.",
   (PROG("redeem = 3 + 34 * 5                 # a 2-of-5 script with compressed keys: OP_2, five pushes of 33 bytes, OP_5, OP_CHECKMULTISIG\nspk = 23                                # the P2SH output script\nresult = (redeem, spk, redeem - spk)"), "(173, 23, 150)")), P(
  (W, "The benefits of P2SH are four, in the words of the book. The similarity to the original legacy addresses means that the sender and the sender's wallet need no complex engineering; the burden of storing the long script moves from the output, which is on the chain and in the set of unspent outputs, to the input, which is only on the chain; it moves from the present to a future time; and the transaction fee of a long script moves from the sender to the recipient [AH]."),
  (Y, "The first benefit made the second possible. Because the payer saw only an address, exchanges, shops and wallets that already knew how to pay an address could pay a multisignature without being changed, and BIP16 names that as its reason: it would minimize the changes needed to all of the supporting infrastructure and allow merchants and exchanges to support multisignature transactions sooner [B16]. The storage benefit is a benefit to every node, since the long script does not sit in the set of unspent outputs."),
  (E, "The example counts the bytes for Mohammed's script with compressed keys: the 2-of-5 script is 173 bytes, the P2SH output script is 23 bytes, and the output of the payer is therefore 150 bytes shorter. The library recomputes the script size and also the size of the real spend, in which the spender adds the redeem script and two signatures; the spending input is the larger one, which is the shifting of the burden that the book describes."),
  (H, "The shifted cost is paid in the future. When the owners spend, their input script contains the empty dummy, the signatures and the full redeem script, so the transaction they pay a fee for is bigger than a spend of a single key. The fee is proportional to size, so the owner pays about the cost of the script that the payer did not. A group that wants to be paid in this way is choosing to carry the cost of its own security."),
  (K, "The fee shift is a shift, not a saving: in total the chain carries the same bytes. The book's remark that the payment is about five times larger without P2SH is a rough comparison with a simple payment which this page does not re-derive; the sizes of the script and the output are what it computes. And the opacity of the hash has a price, covered in the next section."),
 ), None),

 ("P2shRules", "P2SH validation rules", 3, "P2shConsequences", ("push-only input, no recursion, counted signature operations", "The validation rules of P2SH say that the input script may only push data, that the redeem script is run exactly once, with no further P2SH inside, and that the signature checks it hides are counted.",
   (PROG(SIGOPS + "result = (sigops('2 K1 K2 K3 3 CHECKMULTISIG'.split()), sigops('CHECKSIG IF CHECKSIGVERIFY ELSE CHECKMULTISIGVERIFY ENDIF'.split()))"), "(3, 22)")), P(
  (W, "The validation rules of pay to script hash come from BIP16 and from the code of Bitcoin Core. BIP16 lists them: validation fails if there are any operations other than push data operations in the input script; normal validation is done, and fails at once if the hash of the script does not match the output; and then the script is popped off the stack and validated again with the rest of the stack. The book adds that a P2SH cannot be put inside a P2SH redeem script because the specification is not recursive, and that OP_RETURN in a redeem script would make the transaction invalid [B16] [AH]."),
  (Y, "The rules matter because they make an opaque output safe to validate. The push-only rule prevents an input script from changing what the redeem script means, and the single evaluation keeps the cost of a spend bounded. The counting rule exists because Bitcoin limits the signature checks per block to protect miners; BIP16 explains that without a limit a rogue miner might broadcast a block that requires hundreds of thousands of signature operations to validate and gain a head start on the next block [B16]."),
  (E, "In Bitcoin Core the rules are in VerifyScript: a failure of the push-only rule is the error SIG_PUSHONLY, and a hash mismatch simply makes the first stage false. The counting rule has two forms. BIP16 counts a CHECKMULTISIG that follows a small number as that many operations and any other as 20, and the example applies it to the BIP's two examples to get 3 and 22. Bitcoin Core's relay policy also refuses an input if its redeem script contains more than 15 such operations, the constant MAX_P2SH_SIGOPS [BCI] [BCQ] [BCP]."),
  (H, "The library runs each rule. A redeem script that is OP_1 succeeds; the redeem script OP_0 fails with EVAL_FALSE; an input script that has an extra no-operation before the push fails with SIG_PUSHONLY; a redeem script whose hash does not match fails with EVAL_FALSE; and a redeem script that is itself a P2SH output script is not run as a P2SH again, it only has its hash compared, so that an inner script that would be false is never executed. With the P2SH flag switched off, as in the rules before 2012, even the always-false redeem script is accepted."),
  (K, "Not recursive is a surprise in one direction: the nested output is not evaluated, so a script hash inside a script hash does not protect the funds in the way a reader might expect. And invalid is a surprise in the other: the network accepts the creation of an output whose redeem script can never succeed, so a mistake is only discovered at the time of spending, when nothing can be changed. The book makes this a warning, and so does this page."),
 ), None),
]

CHECKS_D = [
 Qb(BK, "Pay to script hash (P2SH) was", "introduced in 2012 as a powerful new type of operation that greatly", "simplifies the use of complex scripts."),
 Qb(BK, "Mohammed is an electronics importer based in Dubai.", "Mohammed, his three partners, and their attorney can each provide one signature.", "2 <Mohammed's Public Key> <Partner1 Public Key> <Partner2 Public Key>", "<Partner3 Public Key> <Attorney Public Key> 5 OP_CHECKMULTISIG"),
 Qb(BK, "Given the preceding script, Mohammed would have to", "communicate this script to every customer prior to payment.", "special Bitcoin wallet software with the", "ability to create custom transaction scripts.", "the resulting transaction would be about five times larger", "than a simple payment transaction", "carried in the UTXO set in every full node, until it was spent."),
 Qb(BK, "the complex script is replaced with a", "commitment, the digest of a cryptographic hash.", "it must contain the script that", "matches the commitment in addition to the data that satisfies the script.", "P2SH", "means \"pay to a script matching this hash, a script that will be", "presented later when this output is spent.\""),
 Qb(BK, "the script that is replaced by a hash is", "referred", "to as the _redeem script_ because it is presented to the system at", "redemption time rather than as an output script."),
 Qb(BK, "Output script", "OP_HASH160 &lt;20-byte hash of redeem script&gt; OP_EQUAL", "Sig1 Sig2 &lt;redeem script&gt;", "This shifts the burden", "in fees and complexity from the spender to the receiver of the", "transaction."),
 Qb(BK, "first applying the SHA256 hashing algorithm and then applying", "the RIPEMD-160 algorithm on the result.", "54c557e07dde5bb6cb791c7a540e0a4796f5e97e", "OP_HASH160 54c557e07dde5bb6cb791c7a540e0a4796f5e97e OP_EQUAL", "<Sig1> <Sig2> <2 PK1 PK2 PK3 PK4 PK5 5 OP_CHECKMULTISIG>", "<2 PK1 PK2 PK3 PK4 PK5 5 OP_CHECKMULTISIG> OP_HASH160 <script hash> OP_EQUAL", "<Sig1> <Sig2> 2 <PK1> <PK2> <PK3> <PK4> <PK5> 5 OP_CHECKMULTISIG"),
 Qb(BK, "P2SH addresses are base58check", "encodings of the 20-byte hash of a script, just like Bitcoin addresses", "are base58check encodings of the 20-byte hash of a public key.", "P2SH", "addresses use the version prefix \"5,\" which results in", "base58check-encoded addresses that start with a \"3.\"", "+39RF6JqABiHdYHkfChV6USGMe6Nsr66Gzw+", "The 3 prefix gives them a hint that this is a special", "type of address", "P2SH addresses hide all of the complexity so the person making a", "payment does not see the script."),
 Qb(BK, "The similarity to original legacy addresses means the sender and the sender's", "wallet don't need complex engineering to implement P2SH.", "P2SH shifts the burden in data storage for the long script from the", "output (which additionally to being stored on the blockchain is in the", "UTXO set) to the input (only stored on the blockchain).", "from the present time (payment) to a future time (when it is spent).", "shifts the transaction fee cost of a long script from the sender", "to the recipient, who has to include the long redeem script to spend", "it."),
 Qb(BK, "You are", "not able to put a P2SH inside a P2SH redeem script because the", "P2SH specification is not recursive.", "executing +OP_RETURN+ during validation will cause the", "transaction to be marked invalid.", "if you create an output with the", "hash of an invalid redeem script, you will not be able to spend", "it.", "The P2SH output will be", "considered valid and accepted even if the redeem script is invalid."),
 Qb("ch04_keys.adoc", "base58check"),
 Qe("bip-0173.mediawiki", "Base32 address format for native v0-16 witness outputs"),
 X("(L.b58check_decode('37Lx99uaGn5avKBxiW26HjedQE3LrDCZru')[0], L.b58check_decode('3Dwz1MXhM6EfFoJChHCxh1jWHb8GQqRenG')[0])", (5, 5)),
 X("len(bytes.fromhex(C.ms_scriptsig(2, 5, [3, 4]))) > 173", True),
 Qe("bip-0016.mediawiki", "The purpose of pay-to-script-hash is to move the responsibility for supplying the conditions to redeem a transaction from the sender of the funds to the redeemer.", "using a fixed-length 20-byte hash that is short enough to scan from a QR code or easily copied and pasted.", "OP_HASH160 [20-byte-hash-value] OP_EQUAL", "[20-byte-hash-value] shall be the push-20-bytes-onto-the-stack opcode (0x14) followed by exactly 20 bytes.", "...signatures... {serialized script}", "Validation fails if there are any operations other than \"push data\" operations in the scriptSig.", "validation fails immediately if it does not match the hash in the outpoint.", "{serialized script} is popped off the initial stack, and the transaction is validated again using the popped stack and the deserialized script as the scriptPubKey.", "timestamps >= 1333238400 (Apr 1 2012)", "OP_CHECKSIG and OP_CHECKSIGVERIFY count as 1 signature operation, whether or not they are evaluated.", "All other OP_CHECKMULTISIG and OP_CHECKMULTISIGVERIFY are counted as 20 signature operations.", "+3 signature operations:", "+22 signature operations:", "If there was no limit, a rogue miner might broadcast a block that required hundreds of thousands of ECDSA signature operations to validate", "minimize the changes needed to all of the supporting infrastructure that has already been created", "allowing merchants and exchanges and other software to start supporting multisignature transactions sooner", "it is only possible to spend a P2SH output requiring a maximum of 15 pubkeys to redeem: 3 bytes + 15 pubkeys * 34 bytes/pubkey = 513 byte"),
 Qe("bip-0013.mediawiki", "base58-encode: [one-byte version][20-byte hash][4-byte checksum]", "Version byte is 5 for a main-network address, 196 for a testnet address.", "byte 5 becomes the character '3'", "byte 196 is encoded into '2'", "if an older implementation is given one of these new bitcoin addresses, it will report the address as invalid and will refuse to create a transaction"),
 Qc("src/script/interpreter.cpp", "// scriptSig must be literals-only or validation fails", "if (!scriptSig.IsPushOnly())", "return set_error(serror, SCRIPT_ERR_SIG_PUSHONLY);", "const valtype& pubKeySerialized = stack.back();", "CScript pubKey2(pubKeySerialized.begin(), pubKeySerialized.end());", "if (!EvalScript(stack, pubKey2, flags, checker, SigVersion::BASE, serror))"),
 Qc("src/script/script.cpp", "bool CScript::IsPayToScriptHash() const", "(*this)[0] == OP_HASH160 &&", "(*this)[1] == 0x14 &&", "(*this)[22] == OP_EQUAL);"),
 Qc("src/script/solver.cpp", "TxoutType::SCRIPTHASH"),
 Qc("src/policy/policy.h", "inline constexpr unsigned int MAX_P2SH_SIGOPS{15};"),
 Qc("src/policy/policy.cpp", "unsigned int sigop_count = subscript.GetSigOpCount(true);", "if (sigop_count > MAX_P2SH_SIGOPS) {", "\"p2sh redeemscript sigops exceed limit (input %u: %u > %u)\""),
 Qc("src/script/script.h", "bool IsPayToScriptHash() const;"),
 # executed: hashes and addresses of the book
 X("L.b58check_encode(5, bytes.fromhex(" + repr(H_MOH) + "))", "39RF6JqABiHdYHkfChV6USGMe6Nsr66Gzw"),
 X("(lambda v, h: (v, h.hex()))(*L.b58check_decode('39RF6JqABiHdYHkfChV6USGMe6Nsr66Gzw'))", (5, H_MOH)),
 X("L.script_to_address(bytes.fromhex('a914' + " + repr(H_MOH) + " + '87'))", "39RF6JqABiHdYHkfChV6USGMe6Nsr66Gzw"),
 X("L.address_to_script('39RF6JqABiHdYHkfChV6USGMe6Nsr66Gzw').hex()", "a914" + H_MOH + "87"),
 X("(L.classify(bytes.fromhex('a914' + " + repr(H_MOH) + " + '87')), len(bytes.fromhex('a914' + " + repr(H_MOH) + " + '87')))", (("scripthash", "OP_HASH160 <20 bytes> OP_EQUAL"), 23)),
 X("[L.b58check_encode(v, bytes(20))[0] for v in (0, 5, 196)]", ["1", "3", "2"]),
 X("L.b58check_encode(5, bytes.fromhex('3e054726' + '0' * 32))[:1]", "3"),
 X("L.b58check_decode(L.b58check_encode(5, bytes.fromhex(" + repr(H_MOH) + "))) == (5, bytes.fromhex(" + repr(H_MOH) + "))", True),
 X("__import__('datetime').datetime.fromtimestamp(1333238400, __import__('datetime').UTC).strftime('%Y-%m-%d %H:%M')", "2012-04-01 00:00"),
 # executed: the sizes
 X("(len(L.multisig_script(2, [C.pub(i) for i in range(5)])), len(L.p2sh_script(bytes(20))))", (173, 23)),
 X("(len(L.multisig_script(15, [C.pub(i % 8) for i in range(15)])), len(L.multisig_script(16, [C.pub(i % 8) for i in range(16)])))", (513, 547)),
 X("[len(i) for i in [o[2] if o[2] is not None else b'' for o in L.get_ops(bytes.fromhex(C.ms_scriptsig(1, 2, [1])))]]", [0, 72, 71]),
 X("C.ms_scriptsig(1, 2, [1]) == " + repr(SS_P2SH), True),
 X("bytes.fromhex(" + repr(SS_P2SH) + ")[-1]", 174),
 X("(lambda ss: L.get_ops(ss)[-1][2][-1])(bytes.fromhex(" + repr(SS_P2SH) + "))", 174),
 # executed: the rules
 X("(C.p2sh_spend(b'\\x51'), C.p2sh_spend(b'\\x00'), C.p2sh_spend(b'\\x51', hashed=b'\\x52'))", ("OK", "EVAL_FALSE", "EVAL_FALSE")),
 X("C.p2sh_spend(b'\\x51', script_sig=b'\\x61' + L.push_data(b'\\x51'))", "SIG_PUSHONLY"),
 X("(lambda inner: C.p2sh_spend(L.p2sh_script(L.hash160(inner)), pushes=[inner]))(b'\\x00')", "OK"),
 X("(C.p2sh_spend(b'\\x00', flags=frozenset()), C.p2sh_spend(b'\\x00', flags=frozenset({'P2SH'})))", ("OK", "EVAL_FALSE")),
 X("C.p2sh_spend(b'\\x6a')", "OP_RETURN"),
 X("(C.sigops(L.multisig_script(2, [C.pub(i) for i in range(3)])), C.sigops(bytes([0xac, 0x63, 0xad, 0x67, 0xaf, 0x68])))", (3, 22)),
 X("(C.sigops(bytes([0xae]), True), C.sigops(L.multisig_script(1, [C.pub(0)]), False))", (20, 20)),
 X("C.ms_spend(2, 3, [1, 2], wrap='p2sh')", "OK"),
 X("(lambda tx: [o[2] is not None for o in L.get_ops(tx.vin[0][2])])(L.parse_tx(C.tx_record('a1075db55d41')[0]))", [True, True]),
 # executed: the real chain
 X("(C.census(L)['p2sh-multisig 2-of-3'], C.census(L)['p2sh-p2wpkh'], C.census(L)['p2sh-p2wsh'], sum(v for k, v in C.census(L).items() if k.startswith('p2sh')))", (10, 95, 34, 139)),
 X("[k for k in C.census(L) if k == 'p2sh-other']", []),
 X("round(139 / sum(C.census(L).values()) * 100)", 14),
 X("sum(1 for r in C.block_records() for i in range(len(L.parse_tx(r['hex']).vin)) if L.is_p2sh(bytes.fromhex(r['spent'][i][1])) and L.verify_input(L.parse_tx(r['hex']), i, [(a, bytes.fromhex(s)) for a, s in r['spent']], L.MAINNET_FLAGS) == 'OK')", 139),
 X("sum(1 for r in C.block_records() for i in range(len(L.parse_tx(r['hex']).vin)) if L.is_p2sh(bytes.fromhex(r['spent'][i][1])) and L.verify_input(L.parse_tx(r['hex']), i, [(a, bytes.fromhex(s)) for a, s in r['spent']], frozenset()) == 'OK')", 139),
]
