"""SEN0401 chapter 4, corpus text part E (version 1.1.0): the segregated witness addresses (bech32 and bech32m) and the witness output kinds.
Markers such as [BK] are replaced by author-year strings in sen0401_ch04_corpus_v1_1_0.py. The first element of every paragraph tuple is
only the author's writing guide and is not printed."""
from sen0401_ch04_text_a_v1_1_0 import W, Y, E, H, K, KHEX, NHEX, YHEX
WPKH = "2b626ed108ad00a944bb2922a309844611d25468"
WSH = "648a32e50b6fb7c5233b228f60a6a2ca4158400268844c4bc295ed5e8c3d626f"
TR = "2ceefa5fa770ff24f87c5475d76eab519eda6176b11dbe1618fcf755bfac5311"
A_WPKH = "bc1q9d3xa5gg45q2j39m9y32xzvygcgay4rgc6aaee"
A_WSH = "bc1qvj9r9egtd7mu2gemy28kpf4zefq4ssqzdzzycj7zjhk4arpavfhsct5a3p"
A_TR = "bc1p9nh05ha8wrljf7ru236awm4t2x0d5ctkkywmu9sclnm4t0av2vgs4k3au7"
A_TYPO = "bc1p9nh05ha8wrljf7ru236awn4t2x0d5ctkkywmv9sclnm4t0av2vgs4k3au7"

NODES_E = [
 ("Segwit", "Segwit addresses", 2, "Address", None, [
  (W, "Segwit addresses are the addresses written for segregated witness outputs. They are the answer of the Bitcoin developers to a practical question that the legacy addresses could not answer: how can a payer be given a short, easily typed string that works for the new kinds of output of a protocol upgrade and for kinds that have not yet been invented. The book presents two closely related formats, bech32 for the first version of the upgrade and bech32m for later versions, and says that bech32m is the current recommended address format for Bitcoin wallets [BK]."),
  (Y, "The upgrade in question, called segregated witness or segwit, was introduced in 2017 according to the book, and, when it is used, it prevents transaction identifiers from being changed without the consent of the spender; it also provided additional capacity for transaction data in blocks and several other benefits [BK]. Users who wanted direct access to its benefits had to accept payments to new output scripts, and that demanded a new way of telling payers what to pay. The book lists four problems of the older base58check addresses that the designers wanted to solve at the same time, among them the difficulty of reading them aloud and the need to upgrade every payer's wallet whenever a new protocol feature appeared [BK]."),
  (E, "A segwit address is what a current wallet shows by default. Bitcoin Core 31.1, for instance, gives out a bech32 address for a new wallet unless it is asked for another kind, and the addresses begin with bc1 on the main network [CORE]. Because the formats include their own version number, a wallet that can pay a bech32m address can in principle pay outputs of future versions that nobody has defined yet, which is one of the aims of the design."),
  (H, "The level has three groups of concepts. The upgrade itself and its nested form inside a P2SH address come first. The format is described next, piece by piece: the bech32 address, the witness version, the witness program, the human-readable part, the BCH checksum and the way errors are detected, the weakness of bech32 that was found in practice, and bech32m which repairs it. The three witness output kinds, the public key hash, the script hash and taproot, close the level, because each is a different use of the witness program."),
  (K, "A new address format does not make old ones invalid, and a valid segwit address does not prove that the receiver can spend what arrives. The wallet that pays also needs to be able to recognise the kind: a payer that is not upgraded cannot pay a bech32 address, and the book explains that this need for upgrades was one of the problems the designers wanted to reduce [BK]. The remaining danger lies in implementation errors, which is why the book asks implementers to use the published test vectors."),
 ], None),
 ("SegwitUpgrade", "Segregated witness upgrade", 3, "Segwit", ('a new place for signatures', 'Segregated witness moves the signatures and scripts of a transaction into a separate witness structure, so that the transaction identifier no longer depends on them and a spender, not a third party, controls it.', ("(lambda sha: (lambda nowit, wit: (sha(sha(nowit).digest()).hexdigest()[:8], sha(sha(nowit + wit).digest()).hexdigest()[:8]))(b'the bytes of a transaction without its witness', b' and the witness bytes'))(__import__('hashlib').sha256)", "('3116f499', 'd97ceb07')")), [
  (W, "Segregated witness, shortened to segwit, is an upgrade of the Bitcoin protocol that defines a new structure called the witness, committed to blocks separately from the tree of transactions. The structure contains the data required to check that a transaction is valid, but not the data that determines what the transaction does; in particular, scripts and signatures are moved into it [B141]. The book dates the upgrade to 2017 [BK], and the specification, BIP141, has the status Deployed [B141]. Chapter 3 introduced the same upgrade from the side of the node, listing segregated witness and the transaction identifiers among the data that a node handles."),
  (Y, "The first motivation that the specification gives is the end of unintentional malleability. Because signature data is no longer part of the transaction hash, changes to how the transaction was signed are no longer relevant to transaction identification [B141]. The book describes the same benefit: when the upgrade is used, the transaction identifier cannot be changed without the consent of the spending user, or of the quorum of signers when several signatures are required [BK]. Transaction identifiers that are stable are a prerequisite for chains of unconfirmed transactions, and the specification mentions that this is important for off-chain protocols such as the Lightning Network [B141]."),
  (E, "Segwit is met whenever an address begins with bc1, and it is the reason why a transaction has two identifiers. The txid remains the double SHA256 of the traditional serialisation, while a new identifier, the wtxid, is the double SHA256 of the serialisation that includes the witness [B141]. The worked example shows the consequence on two short byte strings: hashing the bytes of a transaction without its witness and hashing the same bytes with the witness appended give two completely different identifiers, which is why the witness had to be left out of the first of them. The upgrade was designed to be a soft fork, compatible with nodes that did not upgrade, and it did not make older address kinds invalid; it also gave blocks additional capacity for transaction data, as the book says [BK]."),
  (H, "The specification sets out the mechanism. Each transaction input is associated with a witness field, a list of stack items, and for an input that does not spend a witness program the field is empty, a single zero byte. The witnesses of a block are committed in a second tree whose root is recorded in an output of the coinbase transaction, the first transaction of a block, so that the commitment is nested in the block's existing structure, which is what makes the change compatible with a soft fork [B141]. The chapter's checks read the specification and confirm that it defines the two identifiers and the empty witness field in these words."),
  (K, "A frequent error is to think that segwit hides signatures or removes them. They are transmitted and verified as before; they are only stored in a different place and not counted in the identifier. The specification states that transmission of signature data becomes optional for a peer that merely wants to check that a transaction exists [B141], and that is a saving, not a removal of verification. A second error is to think that using a segwit address makes a transaction private: the structure of the transaction remains visible."),
 ]),
 ("NestedSegwit", "Segwit inside P2SH", 3, "Segwit", ('3FyC6EYuxW22uj4CaEGjNCjxeg7gHyFeVv', 'A P2SH address can wrap a witness program: the redeem script is the witness output script (OP_0 and the 20-byte key hash), so an older payer that only knows P2SH can pay a segwit receiver.', ("(lambda h: (bytes([0, 20]).hex() + h, len(bytes.fromhex('0014' + h))))('bbc1e42a39d05a4cc61752d6963b7f69d09bb27b')", "('0014bbc1e42a39d05a4cc61752d6963b7f69d09bb27b', 22)")), [
  (W, "Segwit inside P2SH, often called nested segwit, is the way in which a receiver can use segregated witness through an ordinary P2SH address. The redeem script that the address commits to is the segwit output script itself: the byte for version 0 followed by a push of the 20-byte hash of the public key. The book explains the idea: as the P2SH output type had the advantage that a spender does not need to know the details of the script the receiver uses, the segwit upgrade was designed to use that mechanism, allowing users to begin accessing many of its benefits immediately through a P2SH address [BK]."),
  (Y, "Nested segwit was a bridge. A receiver wanting segwit did not have to wait for all payers to upgrade, because every wallet that could pay a P2SH address could pay this one. The book adds the limit of the bridge: to gain access to all the benefits, Bob would need Alice's wallet to pay him with a different type of script, and that would require Alice's wallet to upgrade to support the new scripts [BK]. The bech32 address was the way out of the dilemma."),
  (E, "The nested form is still visible in Bitcoin Core, whose address type options are legacy, p2sh-segwit, bech32 and bech32m [CORE]. The documentation of descriptors calls the corresponding output a P2SH-P2WPKH output and writes it sh(wpkh(KEY)) [CORE]. Such an address begins with 3 like every P2SH address, so it cannot be told from a multisignature P2SH address by looking at it."),
  (H, "The chapter's checks build one. The compressed public key of the example gives the 20-byte hash bbc1e42a39d05a4cc61752d6963b7f69d09bb27b; the redeem script is the two bytes 00 and 14 followed by that hash; the P2SH address of this script is 3FyC6EYuxW22uj4CaEGjNCjxeg7gHyFeVv. Bitcoin Core 31.1 returns the same address for the descriptor sh(wpkh(KEY)) [CORE]. The payer sees only a P2SH output and nothing of the witness."),
  (K, "Compared with a native segwit address, the nested one costs more space: the specification gives the figures for the nested form of P2WPKH, an output script one byte bigger and an input script 23 bytes bigger than those of the native form [B141]. It is also more roundabout, and the book's reasoning for the bech32 format is that it should lead directly to the new scripts [BK]. The nested kind also carries the weaker 160-bit commitment of P2SH, a point discussed under the collision attack. It is a compatibility measure and should not be mistaken for a separate kind of key."),
 ]),
 ("Bech32Address", "Bech32 address", 3, "Segwit", (A_WPKH, "A bech32 address is a human-readable part, the separator 1, a witness version, a witness program and a six-character checksum, in one case of a 32-character alphabet.", ("len('" + A_WPKH + "')", "42")), [
  (W, "A bech32 address is a segwit address written in the bech32 format, which is a checksummed base 32 format. The book gives its pronunciation, a soft ch as in besh thirty-two, and explains the name: bech stands for BCH, the initials of the three individuals who discovered the cyclic code in 1959 and 1960 on which the checksum is based, and 32 for the number of characters of the alphabet, as the 58 in base58check [BK]. The designers' own explanation of the name is shorter: Bech contains the characters BCH, the error detection algorithm used, and sounds a bit like base [B173]."),
  (Y, "The format answers the defects of base58check that the designers identified. It uses only numbers and a single case of letters, which makes it easier to read aloud and to copy; it can detect, and help to locate, errors; it can be written in capital letters, which takes less space in a QR code; and it has a mechanism that lets today's wallets pay outputs of future versions [BK]. The book adds that despite its alphabet being almost half the size of the base58check alphabet, a bech32 address for P2WPKH is only slightly longer than the legacy address for an equivalent P2PKH script [BK]."),
  (E, "The book's example, for a P2WPKH output, is bc1q9d3xa5gg45q2j39m9y32xzvygcgay4rgc6aaee, 42 characters long, and the book shows further examples for the other output kinds [BK]. Bitcoin Core 31.1 reports the address as valid, as a witness address of version 0 whose program is 2b626ed108ad00a944bb2922a309844611d25468 [CORE]. Version 0 addresses are always 42 or 62 characters long, as the specification says [B173]."),
  (H, "An address is built in three steps. The witness version and the witness program are rearranged from groups of 8 bits into groups of 5, each group is replaced by one of the 32 characters of the alphabet qpzry9x8gf2tvdw0s3jn54khce6mua7l, and the checksum, six more characters, is computed over the human-readable part and the data and appended [B173]. The chapter's checks do it with the toolkit, which reproduces the book's address from the 20 bytes of the program, and also with the reference implementation that the book itself uses; both give the same four addresses of the book. Decoding reverses the steps and fails if the checksum is wrong."),
  (K, "The format has a weakness that appeared only in practice, described in the concept on length extension. The alphabet omits the characters 1, b, i and o because they resemble others [B173], but the string is still easy to mistype in the middle of a long address. A last caution concerns case: a bech32 address must be written entirely in lowercase or entirely in uppercase, and a decoder must not accept a string that mixes the two [B173]."),
 ]),
 ("WitnessVersion", "Witness version", 3, "Segwit", ("q is 0 and p is 1", "The witness version is the first character after the separator of a segwit address; it is a number from 0 to 16, and the character q stands for 0 and p for 1.", ("('qpzry9x8gf2tvdw0s3jn54khce6mua7l'.index('q'), 'qpzry9x8gf2tvdw0s3jn54khce6mua7l'.index('p'))", "(0, 1)")), [
  (W, "The witness version is a number between 0 and 16 that tells which set of rules governs a witness output. In a bech32m address it is a single byte that is encoded as a single character immediately following the separator. The book says that the letter q is the encoding of 0 for segwit version 0, the initial version, where bech32 addresses were introduced, and the letter p is the encoding of 1 for segwit version 1, also called taproot, where bech32m began to be used [BK]. There are seventeen possible versions, and Bitcoin requires that the first byte of the data part decode to a number from 0 to 16 inclusive [BK]."),
  (Y, "The version is the means by which the protocol can grow. A new kind of output receives a new version number, and wallets that can pay any version can pay it without a new address format. The designers' stated hope was that developers could build a wallet today that allows spending to a bech32 address and have that wallet remain able to pay bech32 addresses for users of new features added in future protocol upgrades [BK]. That is why the book asks implementers to pass the test vectors concerning the versions that are not yet defined."),
  (E, "The characters follow from the alphabet: q is the character at position 0 and p at position 1, and the book's last example, an address for the highest version, begins with bc1s because s is at position 16 [BK]. The chapter's checks look the positions up in the alphabet of the specification. In the output script the version is stored as an opcode: version 0 is OP_0, which uses the byte 0x00, but version 1 uses OP_1, which is the byte 0x51, and the versions 2 to 16 use 0x52 to 0x60 [BK]."),
  (H, "A decoder takes the first value after the separator, checks that it is between 0 and 16, and uses it to decide which checksum constant and which program lengths are allowed: for version 0 the bech32 constant and a program of 20 or 32 bytes, for versions 1 to 16 the bech32m constant [B350]. The chapter's checks compute the opcode bytes from the versions, 0x00 for 0 and 0x50 plus the version for 1 to 16, and obtain the book's values 0x51 and 0x60 for the first and last of them, with the value 0x60 matching the opcode OP_16 in the source of Bitcoin Core [CORE]."),
  (K, "The book's warning is the most important thing to remember here: a witness version of 0 is OP_0, which uses the byte 0x00, but a witness version of 1 uses OP_1, the byte 0x51, and not 0x01 [BK]. A wallet that converts an address to an output script with the wrong byte creates an output that is likely to be unspendable or insecure, as the specification warns [B173]. Another mistake is to think that the version is part of the program: it is a separate field."),
 ]),
 ("WitnessProgram", "Witness program", 3, "Segwit", ("20 or 32 bytes for version 0", "The witness program is 2 to 40 bytes and, for witness version 0, exactly 20 or 32; for version 1, taproot, it is a 32-byte point.", ("(lambda p20, p32: (len(bytes.fromhex(p20)), len(bytes.fromhex(p32))))('2b626ed108ad00a944bb2922a309844611d25468', '648a32e50b6fb7c5233b228f60a6a2ca4158400268844c4bc295ed5e8c3d626f')", '(20, 32)')), [
  (W, "The witness program is the data part of a segwit output: the bytes that follow the witness version in the output script and in the address. It is between 2 and 40 bytes long. For segwit version 0 it must be either 20 or 32 bytes, and no other length is valid; for version 1 the only length defined at the time of the book is 32 bytes, though others may be defined later [BK]."),
  (Y, "The program is the commitment on which the receiver and the payer agree. In version 0 the 20-byte program commits to a public key and the 32-byte program to a script, which means that the decoder can tell what kind of output is meant from the length alone. The specification of the address format requires decoders to enforce the known-length restrictions for the versions that have them, and quotes BIP141: if the version byte is 0 but the witness program is neither 20 nor 32 bytes, the script must fail [B173]."),
  (E, "The book's table shows the three kinds in use at the time of publication, together with a fourth for a future version: OP_0 and the 20-byte hash for P2WPKH, OP_0 and the 32-byte hash for P2WSH, OP_1 and the 32-byte point for P2TR, and OP_16 followed by two bytes of zero for a future example [BK]. Bitcoin Core reports the scripts for these addresses as 0014 and the program, 0020 and the program, 5120 and the program, and 60020000 [CORE]."),
  (H, "From the length rules the address lengths follow. A program of 20 bytes gives an address of 42 characters, and one of 32 bytes gives an address of 62; the book says that these are the two lengths of version 0 [BK]. In general an address is between 14 and 74 characters long, and its length modulo 8 cannot be 0, 3 or 5, as the specification derives from the rules [B173]. The chapter's checks compute the lengths from the bit counts and the smallest and largest case."),
  (K, "The program is not the address, nor is it the script: it is only the data that a template wraps. The same bytes are a public key hash in one kind and the start of a script hash in another only by their length and version. A decoder that accepts a program of an invalid length for its version produces an address that cannot be spent."),
 ]),
 ("HumanReadablePart", "Human-readable part", 3, "Segwit", ("bc for mainnet, tb for testnet", "The human-readable part opens a bech32 address and names its network or purpose, for Bitcoin bc for the main network and tb for testnet; it is followed by the separator 1.", ("'" + A_WPKH + "'.rsplit('1', 1)[0]", "'bc'")), [
  (W, "The human-readable part, abbreviated HRP, is the beginning of a bech32 string: a short prefix of printable characters that conveys the type of data or anything else relevant to the reader. The book says that bech32m addresses start with it, and that for Bitcoin it needs to know only about the two already chosen: bc for Bitcoin mainnet and tb for Bitcoin testnet [BK]. The specification allows 1 to 83 characters in general and leaves applications to restrict them further [B173]."),
  (Y, "The prefix makes an address self-describing, and it keeps networks apart: an address written for one cannot be mistaken for the other, because the prefix is mixed into the checksum as well [B173]. The specification explains why the shorter bc was chosen and not btc: it is shorter; and tb has the same length as bc, which simplifies implementations' assumptions about lengths, yet is visually distinct [B173]."),
  (E, "The human-readable part is followed by the separator, the number 1. The book explains the choice: earlier proposals used a colon, but some operating systems and applications that allow a user to double-click a word to highlight it for copy and paste do not extend the highlighting past a colon, whereas a number does work, and 1 was chosen because bech32 strings do not otherwise use it, which prevents accidental transliteration between the number 1 and the lowercase letter l [BK]. The specification adds that if the prefix itself contains a 1, the last one in the string is the separator [B173]."),
  (H, "To split an address, a decoder finds the last 1 in the string: everything before it is the prefix and everything after it is the data part, whose characters never include 1. The chapter's checks do so for the book's mainnet address and for the specification's testnet address for the same kind of output, and obtain bc and tb. In the checksum computation the high bits of each prefix character are processed first, then a zero, then the low bits, so that an error that changes a letter into another letter remains within the range for which the error-detection guarantee holds [B173]."),
  (K, "Changing the prefix of a valid address does not give a valid address on the other network, because the checksum would no longer match; a tool that merely replaces bc by tb produces an invalid string. Nor should the prefix be confused with the version: the prefix names the network, while the character after the separator names the witness version."),
 ]),
 ("BchCode", "BCH code", 3, "Segwit", ("six characters, 30 bits", "A BCH code is an error-correcting code; bech32's checksum is a BCH code of six 5-bit characters, 30 bits, which is why errors beyond the guaranteed ones slip through less than once in a billion.", ("(6 * 5, 2 ** 30, 1 / 2 ** 30 < 1e-9)", "(30, 1073741824, True)")), [
  (W, "A BCH code is an error-correcting code, named after the initials of the discoverers of the cyclic code on which it is based, and it is the mathematical heart of the bech32 checksum. The book says that the checksum is exactly six characters long and is created using a BCH code, a type of error correction code, although for Bitcoin addresses it is essential to use the checksum only for error detection and not for correction [BK]. The specification of the format describes the code as implementing a BCH code that guarantees the detection of any error affecting at most four characters [B173]."),
  (Y, "The code gives bech32 a stronger guarantee than the checksum of base58check, which is only a truncated hash. A hash gives a probabilistic check; a BCH code can be designed so that a specific class of errors is detected with certainty. The specification states the proposition: any error affecting at most 4 characters is guaranteed to be detected, and there is less than a 1 in 10 to the 9 chance of failing to detect more errors [B173]."),
  (E, "The six characters of a bech32 address carry 30 bits, since each character holds 5 bits, and 2 to the 30 is just over a billion, which is the origin of the one-in-a-billion figure for errors beyond the guarantee. The checksum contains no information of its own [B173]. The specification includes the code that checks it, a short function that computes a polynomial remainder over the numbers of the characters with five constants, and states that valid strings must pass it [B173]."),
  (H, "The verification feeds the expanded prefix and the data characters through the function polymod, which combines each value into a running 30-bit state, and accepts the string if the final state equals a constant: 1 for bech32 and 0x2bc830a3 for bech32m [B350]. The chapter's checks run the function on the book's address and accept it, then test the guarantee on that address. All 1,209 changes of one data character and all 712,101 changes of two data characters are detected, and so are all 100,000 random changes of three or four characters that the checks try."),
  (K, "Correction has a danger that detection does not. The specification warns that error correction erodes error detection, because correction changes invalid inputs into valid inputs, and if more than a few errors were made the valid input may not be the correct input; it therefore asks implementations not to correct beyond suggesting where in the string an error might be [B173]. Bitcoin Core follows the advice by pointing to the positions of the errors and nothing more [CORE]."),
 ]),
 ("ErrorDetection", "Error detection", 3, "Segwit", ("detects, and locates, typing errors", "Bech32 is guaranteed to detect any error affecting four characters or fewer, and Bitcoin Core points to where a typing error is, while bech32's original constant let a q be added before a final p without detection, which bech32m fixes.", ("[i for i, (a, b) in enumerate(zip('" + A_TR + "', '" + A_TYPO + "')) if a != b]", "[25, 40]")), [
  (W, "Error detection is the property of a format that lets software notice that a string has been altered by an accident, such as a mistyped character. The book states what bech32 gives: in an address of the expected length, it is mathematically guaranteed to detect any error affecting four characters or fewer, which is more reliable than base58check; for longer errors it fails to detect them less than one time in a billion, roughly the same reliability as base58check [BK]. Beyond detection, for an address typed with just a few errors, it can tell the user where those errors occurred [BK]."),
  (Y, "A wallet that can say where the mistake is makes the correction quick. The book describes the experience with base58check: if you accidentally transpose two characters your wallet will almost certainly warn that a mistake exists but will not help you find it, and it might take several frustrating minutes to discover the mistake [BK]. For bech32 the decoder can mark the positions of the characters in error, which turns a rejection into a repair."),
  (E, "The book shows an address with two errors, whose wrong characters are underlined in its figure. Bitcoin Core 31.1 rejects the address with the message Invalid Bech32m checksum and reports the error locations 25 and 40, and the chapter's checks confirm that these are exactly the two positions in which the typed string differs from the correct address [CORE]. The book obtained its figure from a decoder demonstration that localises errors [BK]."),
  (H, "The mechanism rests on the BCH code: the checksum is a remainder that equals a fixed constant for valid strings, so a few wrong characters change the remainder. One of the properties of these BCH codes is that they can be used for error correction, which is what lets a decoder suggest where an error is [B173]. The guarantee holds only if the length of the string entered equals the length of the original address [BK]. The chapter's checks confirm the guarantee on the book's address by trying every single-character and every two-character substitution."),
  (K, "The guarantee has a condition that the book spells out: it applies only if the length of the address entered is the same as the length of the original. If characters are added or removed in transcription the guarantee does not apply and the wallet may spend funds to a wrong address [BK]. This is the root of the weakness explained in the next concept. Detection is also not correction: the specification asks software never to apply a suggested correction without the user's confirmation [B173]."),
 ]),
 ("LengthExtension", "Bech32 length extension weakness", 3, "Segwit", ("a q before a final p", "In bech32, adding or removing the letter q just before a final p leaves the checksum valid; the book's six extended strings are valid under bech32 and invalid under bech32m.", ("[len(a) for a in ('bc1pqqqsq9txsqp', 'bc1pqqqsq9txsqqqqp', 'bc1pqqqsq9txsqqqqqqp')]", "[15, 18, 20]")), [
  (W, "The length extension weakness is a flaw found in the bech32 checksum after the format had been designed: the guarantees about detecting errors apply only if the length of the entered address is the same as that of the original. The book explains that one of the constants of the algorithm happened to make it very easy to add or remove the letter q in the penultimate position of an address that ends with the letter p, and to do so more than once [BK]. The specification of the repair says that whenever the final character is a p, inserting or deleting any number of q characters immediately preceding it does not invalidate the checksum [B350]."),
  (Y, "In version 0 the flaw is harmless in practice, because only two lengths of witness program are valid. The book works out the figures: the valid program lengths of 22 and 34 bytes of script correspond to addresses of 42 and 62 characters, so one would have to add or remove the letter q twenty times to send money to an invalid address without the wallet being able to detect it [BK]. For later versions it would become a problem, because developers did not want to constrain output sizes: without a constraint, adding or removing a single q could send money to an output that is unspendable or spendable by anyone [BK]."),
  (E, "The book prints an intended address, bc1pqqqsq9txsqp, and five longer strings with a valid checksum. The chapter's checks verify the book's statement, by applying the checksum algorithm of bech32: all six strings carry a valid bech32 checksum, and none of them carries a valid bech32m checksum. Bitcoin Core 31.1 refuses all six when they are given as version 1 addresses [CORE]. The note in the specification of bech32m, that the flaw was reported in an issue of the repository of the reference implementation, shows how it was found [B350]."),
  (H, "The lengths of the book's six strings show what has been inserted: the intended address has 15 characters and the five others have 18, 20, 22, 23 and 25, which means that three, five, seven, eight and ten letters q have been put in front of the final p. Because the string ends in that p, the checksum of bech32 stays valid after each of these insertions, and a decoder of that format cannot tell the six strings apart; the chapter's checks confirm the six lengths and that every one of the six passes the bech32 test. The repair, explained in the next concept, changes one constant of the algorithm and removes the flaw for insertions and deletions of up to five characters, as the book states [BK]."),
  (K, "The flaw does not affect segwit version 0 addresses or the funds that were sent to them, and it was fixed before it could harm users. The lesson for implementers is that a checksum has a design range, and that a property such as detecting any change of up to four characters says nothing about lengths. A further consequence is that wallets must reject addresses whose length is not valid for their version, which the specification's decoder does."),
 ]),
 ("Bech32mAddress", "Bech32m address", 3, "Segwit", (A_TR, "Bech32m differs from bech32 only in the constant merged into the checksum, 0x2bc830a3 instead of 1, and is required for witness version 1 and later.", ("(lambda b32, b32m: (b32[:-6] == b32m[:-6], b32[-6:], b32m[-6:]))('bc1p9nh05ha8wrljf7ru236awm4t2x0d5ctkkywmu9sclnm4t0av2vgsq2p3eu', 'bc1p9nh05ha8wrljf7ru236awm4t2x0d5ctkkywmu9sclnm4t0av2vgs4k3au7')", "(True, 'q2p3eu', '4k3au7')")), [
  (W, "Bech32m, short for bech32 modified, is the version of bech32 with a single different constant. The checksum algorithm is the same, and in its final step the constant 0x2bc830a3 is combined by an exclusive-or operation with the value in place of the constant 1 of the original [BK][B350]. Bech32m is used for segwit outputs of version 1 and later, while version 0 keeps bech32 [B350]. The book recommends it as the current address format for Bitcoin wallets [BK]."),
  (Y, "The aim was to remove the length extension weakness without constraining future output sizes. The book reports that developers analysed the bech32 problem exhaustively and found that changing a single constant would eliminate it, so that any insertion or deletion of up to five characters is missed less often than one time in a billion [BK]. The specification explains why version 0 was not given the choice of both encodings: permitting both would reduce the error detection capabilities, making it equivalent to having only 29 bits of checksum [B350]."),
  (E, "All the characters of a bech32 and a bech32m address for the same underlying data are identical except for the last six, the checksum [BK]. The book's taproot example, bc1p9nh05ha8wrljf7ru236awm4t2x0d5ctkkywmu9sclnm4t0av2vgs4k3au7, is a bech32m address, and Bitcoin Core 31.1 validates it as a witness address of version 1 [CORE]. A wallet needs to know which of the two versions is in use to validate the checksum, but the version inside the address makes that easy to find out [BK]."),
  (H, "To decode, a program computes the polynomial remainder once and compares it with both constants: 1 means bech32, 0x2bc830a3 means bech32m, anything else is an error. It then checks that the encoding matches the witness version, bech32 for version 0 and bech32m for the others [B350]. The chapter's checks encode the same 20-byte program once with each constant and find that the two strings share all characters except the last six, and the worked example shows the same for the book's taproot program, where the two encodings differ only in their last six characters, q2p3eu against 4k3au7. They also encode the program of the book's taproot address with the bech32 constant and see that a decoder that applies the rule rejects the result."),
  (K, "A bech32m address with a version 0 program is not valid, and a bech32 address with a version 1 program is not valid either; software that accepts both for either version loses part of the error detection. The BIP350 document states that a string can never be valid in both encodings, because two valid strings of equal length differ in at least three characters [B350]. Implementers should use the test vectors of the specification, including those for versions that are not yet defined [BK]."),
 ]),
 ("P2wpkh", "Pay to witness public key hash (P2WPKH)", 3, "Segwit", ("OP_0 and a 20-byte key hash", "A P2WPKH output script is OP_0 followed by the 20-byte HASH160 of a public key, the same commitment as P2PKH, 22 bytes in all; its address is bech32.", ("len(bytes.fromhex('0014" + WPKH + "'))", "22")), [
  (W, "Pay to witness public key hash, abbreviated P2WPKH, is the segwit counterpart of P2PKH. The output script is the witness version 0 followed by a 20-byte witness program, and for the book's example the script is OP_0 2b626ed108ad00a944bb2922a309844611d25468 [BK]. The witness program contains a commitment constructed in exactly the same way as the commitment for a P2PKH output: the public key is passed into SHA256, the 32-byte digest into RIPEMD-160, and the result is placed in the witness program [BK]."),
  (Y, "The kind combines the short commitment of P2PKH with the benefits of the segwit upgrade, and it yields a bech32 address only slightly longer than the legacy one. Since the signature and the public key move into the witness, the transaction identifier no longer depends on them, which is the point of the upgrade [B141]. A P2WPKH output is the form that Bitcoin Core hands out by default [CORE], and the specification notes that it occupies 3 bytes less in the output script than the equivalent P2PKH output [B141]."),
  (E, "For the book's example key the chapter's checks compute the program from the compressed public key, bbc1e42a39d05a4cc61752d6963b7f69d09bb27b, and obtain the address bc1qh0q7g23e6pdye3sh2ttfvwmld8gfhvnmmfxuck, the same as the descriptor wpkh(KEY) gives in Bitcoin Core 31.1 [CORE]. The specification of the address format shows the standard example: the public key of the generator point gives the program 751e76e8199196d454941c45d1b3a323f1433bd6 and the address bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4 [B173]."),
  (H, "The script is 22 bytes: one byte for the version 0, one for the length 20, and the 20 bytes of the commitment. A node that sees such an output recognises the pattern, and when the output is spent the spender supplies the signature and the public key in the witness, not in the input script; the witness must consist of exactly two items, a signature and a public key, and the HASH160 of the key must match the program [B141]. The chapter's checks recompute the hash of the generator point's public key and confirm the specification's address."),
  (K, "The word hash in the name should not be read as an extra layer of secrecy: the commitment is only 160 bits and is subject to the collision attack of the legacy discussion, but for a key created by one party alone it is as strong as P2PKH. The kind carries one key only, and only compressed public keys are accepted in P2WPKH and P2WSH, so a key that was used in its uncompressed form with a legacy address cannot be used with this kind [B141]; scripts with several keys need the next kind."),
 ]),
 ("P2wsh", "Pay to witness script hash (P2WSH)", 3, "Segwit", ("OP_0 and a 32-byte script hash", "A P2WSH output script is OP_0 followed by the 32-byte SHA256 of a script, without the RIPEMD-160 step of P2SH, 34 bytes in all.", ("len(bytes.fromhex('0020" + WSH + "'))", "34")), [
  (W, "Pay to witness script hash, abbreviated P2WSH, is the segwit counterpart of P2SH. The output script is the version 0 followed by a 32-byte witness program, which is the SHA256 digest of the script that will be revealed when the output is spent [BK]. The book stresses that the algorithm of P2SH is not used here: the script is passed into a SHA256 function and the 32-byte digest is used in the witness program, whereas P2SH hashed the SHA256 digest again with RIPEMD-160 [BK]."),
  (Y, "The longer commitment is the answer to the collision attack. The book notes that for P2SH the RIPEMD-160 step may not be secure in some cases, as the collision discussion explains, and that a consequence of using SHA256 alone is that the commitments are 32 bytes (256 bits) instead of 20 bytes (160 bits) [BK]. The newer addresses thereby provide at least 128 bits of collision resistance, as the book says [BK]."),
  (E, "The book's example is bc1qvj9r9egtd7mu2gemy28kpf4zefq4ssqzdzzycj7zjhk4arpavfhsct5a3p, 62 characters long, with the program 648a32e50b6fb7c5233b228f60a6a2ca4158400268844c4bc295ed5e8c3d626f. The specification of bech32 gives a worked example too: for the script formed of a public key and OP_CHECKSIG the SHA256 digest is 1863143c14c5166804bd19203356da136c985678cd4d27a1b8c6329604903262 [B173]. Bitcoin Core 31.1 validates the book's address as a witness address of version 0 and reports its script as a 34-byte one [CORE]."),
  (H, "To pay to a script the receiver computes the SHA256 of the serialised script and gives the digest to the payer in a bech32 address. To spend, the receiver provides the script in the witness, together with the data it needs, and nodes check that the script hashes to the program before running it [B141]. The chapter's checks reproduce the specification's digest from its public key and the opcode OP_CHECKSIG, and the matching address."),
  (K, "The 32-byte program tells the node that it must be a script hash, but the script itself is not visible until the output is spent. As with P2SH, the payer cannot verify that the script can be satisfied. The stronger commitment protects against an attacker who helps to create the script, but it does not make a poorly designed script safe."),
 ]),
 ("P2tr", "Pay to taproot (P2TR)", 3, "Segwit", ("OP_1 and a 32-byte point", "A P2TR output script is OP_1 followed by a 32-byte witness program that is a point on the secp256k1 curve, which may be a public key or a key that commits to more data; its address is bech32m.", ("len(bytes.fromhex('" + TR + "'))", "32")), [
  (W, "Pay to taproot, abbreviated P2TR, is the output kind of segwit version 1. For a P2TR output the witness program is a point on the secp256k1 curve. The book says that it may be a simple public key, but that in most cases it should be a public key that commits to some additional data, a commitment explained in a later chapter [BK]. The output script is OP_1 followed by the 32-byte program, and the address uses bech32m [BK]."),
  (Y, "Taproot gives a single output the flexibility to be spent either by a signature from one key or by revealing conditions that were committed to in the key. The program is only 32 bytes because the signature standard that goes with it, the Schnorr signatures of BIP340, encodes public keys as 32 bytes, instead of the 33-byte compressed encodings that are common in Bitcoin today [B340]. Signatures take a fixed 64 bytes in this scheme [B340]."),
  (E, "The book's example program is 2ceefa5fa770ff24f87c5475d76eab519eda6176b11dbe1618fcf755bfac5311 and its address is bc1p9nh05ha8wrljf7ru236awm4t2x0d5ctkkywmu9sclnm4t0av2vgs4k3au7. Bitcoin Core 31.1 reports the address as valid, of witness version 1 with that program [CORE]. When the same key is given to Core as the internal key of a tr descriptor, the address differs, because the descriptor language defines the argument of tr as the internal key from which the output key is made, while a descriptor called rawtr takes the key as it is [CORE]."),
  (H, "A 32-byte x coordinate stands for a point because the curve equation determines y up to its sign, and the Schnorr standard settles the sign by convention: the point with an even y coordinate is taken [B340]. The chapter's checks confirm that the book's program is a valid x coordinate, by computing a square root of x cubed plus 7 and testing that it satisfies the equation, and that the toolkit's bech32m encoding of the program gives the book's address."),
  (K, "A taproot address commits to a key, not to a hash of a key, so the key is visible in the output from the start; the benefit of a hash hiding the key until spending is traded for flexibility and smaller signatures. The book returns to the topic in a later chapter, and this chapter treats it only as an output kind that needs a bech32m address."),
 ]),
]
