"""SEN0401 chapter 7, corpus text part F (version 1.0.0): the branch 'Flow control and complex scripts' - conditional clauses,
the VERIFY guard, scripts with several ways to be spent, the book's capital-account script with timelocks, and Miniscript.
Markers such as [AH] become author-year strings (sen0401_ch07_common). The scripts are executed with real signatures in CHECKS_F."""
from sen0401_ch07_common_v1_0_0 import *

BK = "ch07_authorization-authentication.adoc"
H_ABC = "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"        # SHA-256 of b'abc'
MSB = "('or_i', ('pk', 'M'), ('and_v', ('v', ('pk', 'S')), ('older', 144)))"

NODES_F = [
 ("FlowControl", "Flow control and complex scripts", 1, None, None, P(
  (W, "This branch is about scripts that have more than one way of being spent, and the tools for writing them. Flow control, also called conditional clauses, lets a script choose between code paths according to a true or false value that the spender supplies; the VERIFY opcodes attach preconditions; and nesting the conditionals produces scripts with many execution paths. The book ends the topic with a company's capital account that uses all these ideas together [AH]."),
  (Y, "The branch is where Script becomes a language of contracts rather than of single keys. A script with several paths can express who may spend, when, and with whose help: partners who can act together at once, a lawyer who can help after a month, and the same lawyer who can act alone after three months. Every such rule is enforced by every node without a trusted party, which is what the book calls the power of the language."),
  (E, "The reader meets the pattern in the inheritance and recovery schemes of wallets, in escrow, in payment channels, and in the miniscript policies that tools produce. In the saved block of 775,072 none of the 91 witness scripts that were revealed contains a conditional, since all of them are multisignatures; the only conditional is in the one taproot spend that reveals a script, where the branch that follows OP_FALSE OP_IF is never executed and holds the bytes of an image [MP]. The sections run each script with real signatures, so that a reader sees which inputs reach which path."),
  (H, "The branch has two groups. The first, conditionals, covers the opcodes IF, NOTIF, ELSE and ENDIF, the guard clause made with a VERIFY opcode, and the selection of a path by the input script. The second, complex scripts, runs the capital-account script of the book on its three paths and then presents Miniscript, a structured language for the same kind of script that the tools of today use and that can be analysed by a program."),
 ), None),

 ("Conditionals", "Conditionals and guards", 2, "FlowControl", None, P(
  (W, "This group covers the three ways a script decides what to do. A conditional clause chooses between two code paths; a VERIFY guard continues only if a condition holds; and a nest of conditionals offers many paths, one of which the spender selects in the input script [AH]."),
  (Y, "The group matters because the condition is not part of the script. The output script contains the rules, and the input script contains the choice. This is how a single output can be spent in several different ways without anyone revealing, when the output is created, which way will be used."),
  (H, "The first section explains the IF construct and its reversed order, the second the guard clause and the reason it is preferred when there is a single path, and the third the maze of paths that nesting produces. The examples are run by the page's small stack machine and by the chapter's library on real signatures."),
  (K, "Reading the order is the hard part, because the condition comes before the IF, and the value at the top of the stack is the one the first IF takes. A beginner who reads a script as if it were a program in a common language often chooses the wrong path, which is why the book advises running small scripts on paper."),
 ), None),

 ("ConditionalClauses", "Conditional clauses", 3, "Conditionals", ("<condition> OP_IF <A> OP_ELSE <B> OP_ENDIF", "A conditional clause is a group of opcodes between OP_IF or OP_NOTIF and OP_ENDIF, with an optional OP_ELSE, that runs one of two code paths according to the value on top of the stack when the OP_IF is reached.",
   (PROG(MINI + "script = 'IF 10 ELSE 20 ENDIF'\nresult = (dec(run(script, [enc(1)])[-1]), dec(run(script, [enc(0)])[-1]), dec(run('NOTIF 10 ELSE 20 ENDIF', [enc(1)])[-1]))"), "(10, 20, 20)")), P(
  (W, "A conditional clause is the flow control of Script. The book says that Bitcoin's conditional opcodes allow a script that has two ways of being unlocked, depending on a true or false outcome of a logical condition: if the condition is true, one path is executed and otherwise the ELSE path. They are implemented with the opcodes OP_IF, OP_ELSE, OP_ENDIF and OP_NOTIF, together with boolean operators such as OP_BOOLAND, OP_BOOLOR and OP_NOT [AH]."),
  (Y, "Conditionals turn a script into a decision with alternatives. The book adds that the clauses can be nested indefinitely, that scripts with hundreds of possible paths can be built, and that there is no limit to the nesting except the consensus limit on the size of a script in bytes. Without them a script could only be a single chain of checks, all of which would have to pass."),
  (E, "The reader meets conditionals in every script with alternatives; the example runs the book's construct on the page. The same three words of script are run with a true and a false condition on the stack: with 1 the first arm leaves 10, with 0 the second arm leaves 20, and the opposite opcode OP_NOTIF, which takes the first arm when the condition is false, leaves 20 for the value 1. Bitcoin Core's interpreter holds a list of flags, one for each open IF, which says whether the code now being read is executed [BCI]."),
  (H, "The book points out that the form looks backward, like 1 1 OP_ADD does: in a stack language the condition comes before the IF. The opcode takes the top item off the stack, treats any nonzero value as true, and starts an arm; OP_ELSE switches to the other arm; OP_ENDIF closes the clause. In the inactive arm the opcodes are read but not run, which is why a script with an unbalanced IF fails with its own error. Bitcoin Core's comment gives the pattern in the usual order, the expression, then if, the statements, else and endif [BCI] [AH]."),
  (K, "The value that the IF takes can be any bytes, and the three kinds of script treat it differently. In the original rules every nonzero value is true. A policy rule for witness scripts, MINIMALIF, requires exactly an empty value or the single byte 1, and tapscript makes the same rule a consensus rule, with its own error. A wallet that wants its spends to be relayed as well as valid should therefore use OP_TRUE and OP_FALSE, as the book does, and not an arbitrary nonzero number."),
 ), None),

 ("VerifyGuard", "VERIFY guard clause", 3, "Conditionals", ("OP_HASH160 <hash> OP_EQUALVERIFY <pk> OP_CHECKSIG", "An opcode with the suffix VERIFY ends the script with failure unless its result is true, and otherwise continues; it acts as a guard clause that attaches one precondition without offering a second path.",
   (PROG(MINI + "import hashlib\nh = hashlib.sha256(b'abc').hexdigest()\nscript = 'SHA256 0x' + h + ' EQUALVERIFY 1'     # a guard: the secret must hash to h, then the script is true\nresult = (run(script, [b'abc']), run(script, [b'abd']), len('HASH160 h EQUALVERIFY pk CHECKSIG'.split()), len('HASH160 h EQUAL IF pk CHECKSIG ENDIF'.split()))"), "([b'\\x01'], 'FAIL: EQUALVERIFY', 5, 7)")), P(
  (W, "A VERIFY guard is the second form of conditional in Script: any opcode that ends in VERIFY. The book explains that the suffix means that if the evaluated condition is not true, execution of the script terminates at once and the transaction is deemed invalid. Unlike an IF clause, which offers alternative paths, the suffix acts as a guard clause, continuing only if a precondition is met [AH]."),
  (Y, "The guard is the cheaper way to say that two things must both hold. The book's example requires Bob's signature and a preimage, a secret that produces a specific hash: the script hashes the first item, compares it with the expected hash and stops if they differ, and only then checks the signature; without the preimage, Bob cannot get to the part of the script that checks his signature. The same script can be written with OP_IF, but the VERIFY form uses two fewer opcodes [AH]."),
  (E, "The reader meets VERIFY in OP_EQUALVERIFY, which every pay to public key hash script uses, and in OP_CHECKSIGVERIFY, OP_CHECKMULTISIGVERIFY and OP_NUMEQUALVERIFY. The page runs a guard with the hash function that the stack machine has: the script hashes the top item with SHA-256, compares it with a given digest and then leaves 1 on the stack. The secret abc passes, the secret abd stops with the failure of the guard, and the word counts of the two forms in the book's example are 5 and 7."),
  (H, "The engine implements the plain opcode OP_VERIFY as follows: it takes the top item, and if it is true removes it and goes on; if it is false it returns the error SCRIPT_ERR_VERIFY. The other opcodes with the suffix do the same after their own operation, as OP_EQUALVERIFY does after comparing two items [BCI]. The book's rule of thumb: if all you want is to attach a precondition, VERIFY is better; if you want more than one execution path, you need IF and ELSE [AH]."),
  (K, "Two opcodes do not behave like the others with the suffix. OP_CHECKLOCKTIMEVERIFY and OP_CHECKSEQUENCEVERIFY leave their operand on the stack, because the soft forks that added them redefined opcodes that did not drop items and the old behaviour had to be kept, so a script that uses them is followed by OP_DROP if the operand is in the way. The guard also does not choose: a script made only of guards has exactly one way of being spent."),
 ), None),

 ("MultiPathScript", "Scripts with several paths", 3, "Conditionals", ("<signature> OP_1 OP_0 selects path B", "A script with several paths nests conditional clauses so that each path is a different way to redeem the output, and the input script selects the path by pushing a true or false value for each clause.",
   (PROG(MINI + "script = 'IF 10 ELSE IF 20 ELSE 30 ENDIF ENDIF'     # three paths: A, B and C\nchoices = {'A': [1], 'B': [1, 0], 'C': [0, 0]}      # the last value pushed is the first IF to read it\nresult = {k: dec(run(script, [enc(v) for v in c])[-1]) for k, c in choices.items()}"), "{'A': 10, 'B': 20, 'C': 30}")), P(
  (W, "A script with several paths is one in which the output offers more than one way to be redeemed. The book's first example has two signers, Alice and Bob, either of whom can redeem, written with an IF instead of a 1-of-2 multisignature: OP_IF with Alice's key, OP_ELSE with Bob's key, OP_ENDIF and OP_CHECKSIG. It then asks where the condition is, and answers that the condition is not part of the script; it is offered at spending time, so that Alice and Bob can choose which path they want [AH]."),
  (Y, "The choice is made by the spender and not by the script, and that is a form of privacy and flexibility: the paths not taken are invisible until they are used, in a script hash output. The book generalizes: since OP_IF clauses can be nested, one can create a maze of execution paths, and the input script provides a map that selects which path is executed; with this construct, redeem scripts with tens or hundreds of paths can be built [AH]."),
  (E, "The book's three-path script has subscripts A, B and C. To choose B the input script ends with OP_1 OP_0, true and false: the values are pushed so that the false is on top, the outer IF pops it and runs the first ELSE, and then the true moves to the top and is read by the inner IF, which selects B. The example runs the script for the three choices on the page and gets 10, 20 and 30 for A, B and C. The page's library does the same with Alice's and Bob's keys and real signatures: either path succeeds with its own signature, and a signature given to the wrong path fails."),
  (H, "The engine keeps a list of flags for the open clauses, and it pops one value for each IF that it reaches in an executed arm; the inner IF is only reached if the outer arm that contains it runs. That is why the choices appear in the reverse order of the clauses, the innermost first in the sense of being read last and pushed first. The order of the input script is the opposite of the order of reading, which is the reason the book's tip asks whether FALSE then TRUE is not backward, and answers that TRUE is pushed on top and therefore popped first [BCI] [AH]."),
  (K, "A path that is never chosen is still part of the script. Its keys and its timelocks are all committed to by the hash of the script, and the script is revealed in full when any path is used, at least in a script hash output, so the existence of the other paths is made public by the spend. Taproot, in a later branch, was designed to avoid that. Also, a script with many paths takes space: every unused path is paid for in the fee of the transaction that uses the script."),
 ), None),

 ("ComplexScripts", "Script with timelocks and signers", 2, "FlowControl", None, P(
  (W, "This group puts the previous branches together. The book's complex script example is a company capital account that has different rules depending on the time that has passed, with three partners who decide by majority and a lawyer who can help or replace them. Miniscript is the language that tools use today to write and analyse such scripts [AH] [B379]."),
  (Y, "The two sections show two stages of the same work. The first reads a script as a person would write it by hand, with the IF structure, the timelocks and the CHECKMULTISIG, and runs it with real signatures on all three paths. The second shows the rules by which a script like that can be built from small parts whose behaviour is known, so that the whole can be checked by a program and not only by a reader."),
  (H, "The first section executes the redeem script of the book's listing with the library; the days of the listing are written as blocks, 4,320 for 30 days and 12,960 for 90, as a block is a tenth of an hour. The second section reads the translation table of BIP379 and compiles two small examples by its rules, and then runs them."),
  (K, "A script that works on paper may not be spendable in practice. It may mix a timelock of heights with one of times, it may exceed a size limit, or it may need a signature order that the wallet does not produce. The group is meant to show both the power of the language and the reason why tools were built to check scripts."),
 ), None),

 ("MohammedScript", "Capital account script", 3, "ComplexScripts", ("2-of-3 partners, or lawyer plus one after 30 days, or lawyer after 90", "The capital-account script of the book has three execution paths: two of three partners at any time, the lawyer with one partner after 30 days, and the lawyer alone after 90 days, selected by two true or false values in the input script.",
   (PROG("def spendable(path, age_blocks, signers):    # a model of the three paths with sets of signers; the page's library runs the real script\n    partners = {'M', 'S', 'Z'}\n    if path == 1: return len(signers & partners) >= 2\n    if path == 2: return age_blocks >= 4320 and 'L' in signers and len(signers & partners) >= 1\n    return age_blocks >= 12960 and 'L' in signers\nresult = [spendable(1, 0, {'M', 'Z'}), spendable(2, 4319, {'S', 'L'}), spendable(2, 4320, {'S', 'L'}), spendable(3, 12960, {'L'})]"), "[True, False, True, True]")), P(
  (W, "The capital-account script is the book's combined example. Mohammed, a company owner in Dubai, wants a capital account with flexible rules: the participants are Mohammed, his two partners Saeed and Zaira, and the company lawyer; two of the three partners decide by majority; if there is a problem with their keys, the lawyer can recover the funds with one of the three partner signatures; and if all partners are unavailable or incapacitated for a while, the lawyer can manage the account directly. The redeem script nests two IF clauses and has three paths [AH]."),
  (Y, "The script shows how rules about people become rules about keys and time. The first path is an ordinary 2-of-3 multisignature that can be used at any time. The second can be used only after 30 days have passed since the output was confirmed, and requires the lawyer and one of the three partners, a 1-of-3 combined with a signature check. The third lets the lawyer spend alone but only after 90 days. The time conditions are relative, so the clock starts when the funds are confirmed, as the escrow of BIP112 does [AH] [B112]."),
  (E, "The library builds the script with four demonstration keys, 30 days written as 4,320 blocks and 90 days as 12,960 blocks. The script is 192 bytes. It is spent on all three paths as a witness script hash and as a script hash. Path 1 with the signatures of the first and the third partner succeeds at once. Path 2 with the second partner and the lawyer succeeds with a sequence of 4,320 and fails with 4,319. Path 3 with the lawyer succeeds with a sequence of 12,960 and fails with 12,959. The signature of a partner on the third path does not help."),
  (H, "The inputs of the book are, for the first path, OP_0 then two partner signatures and OP_TRUE OP_TRUE; for the second, OP_0, a partner's signature, the lawyer's signature, OP_FALSE and OP_TRUE; and for the third the lawyer's signature and OP_FALSE. The leading OP_0 is the dummy element of the multisignature oddity. In the second path the lawyer's signature is checked first, by OP_CHECKSIGVERIFY with the lawyer's key, and the rest is a multisignature of one among three. The timelock comparisons are performed by OP_CHECKSEQUENCEVERIFY against the sequence of the spending input, and the transaction must have version 2 [AH] [BCI]."),
  (K, "The book writes the delays as 30 days and 90 days; in the script they must be numbers, of blocks or of units of 512 seconds, and the two paths must use the same kind or the script becomes impossible to use for some inputs. Signatures must also be in the order of the keys: the library shows that the first and third partner succeed in that order and fail when the order is reversed. And the timelock is checked per input, so the script depends on the transaction version: with version 1 the third path never succeeds."),
 ), None),

 ("Miniscript", "Miniscript", 3, "ComplexScripts", ("or_i(pk(A),and_v(v:pk(B),older(144)))", "Miniscript is a structured way of writing a subset of Bitcoin Script, in which small fragments with known behaviour are composed by rules, so that a program can analyse the result, find the spending conditions and construct witnesses.",
   (PROG("def script(m):\n    k = m[0]\n    if k == 'pk': return [m[1], 'CHECKSIG']\n    if k == 'older': return [str(m[1]), 'CHECKSEQUENCEVERIFY']\n    if k == 'v':\n        s = script(m[1]); ver = {'CHECKSIG': 'CHECKSIGVERIFY', 'EQUAL': 'EQUALVERIFY'}.get(s[-1])\n        return s[:-1] + [ver] if ver else s + ['VERIFY']\n    if k == 'and_v': return script(m[1]) + script(m[2])\n    if k == 'or_i': return ['IF'] + script(m[1]) + ['ELSE'] + script(m[2]) + ['ENDIF']\nresult = ' '.join(script(('or_i', ('pk', 'A'), ('and_v', ('v', ('pk', 'B')), ('older', 144)))))"), "'IF A CHECKSIG ELSE B CHECKSIGVERIFY 144 CHECKSEQUENCEVERIFY ENDIF'")), P(
  (W, "Miniscript is a language for writing a subset of Bitcoin Scripts in a structured way, enabling analysis, composition, generic signing and more, in the words of BIP379. The BIP says that Script is an unusual stack-based language with many edge cases, and that it is highly nontrivial to find the most economical script for a combination of spending conditions, to compose two scripts, to find out what spending conditions a script permits, or to know whether a limit such as the operation count might be hit. Miniscript gives a representation in which these operations are possible [B379]."),
  (Y, "The language answers the problem that the book's own example has. A hand-written script can contain a mistake, such as a height timelock mixed with a time timelock in one path, that makes the output unspendable. The book warns of this and advises thorough tests on a test network or a tool designed to prevent the issue, like a Miniscript compiler. BIP379 has a type system with a property for exactly this, named k, which means that no timelock of the same type is mixed height and time, and other properties for signatures and malleability [AH] [B379]."),
  (E, "BIP379 has the status Draft, and Bitcoin Core's documentation records that it was partially implemented in release 24.0 and fully as of 26.0, which is the release that added tapscript. The fragments are used in output script descriptors, wsh() for witness script hash outputs and tr() for taproot. The page's example follows the translation table: pk(A) is the key followed by CHECKSIG, older(144) is 144 followed by CHECKSEQUENCEVERIFY, the wrapper v: replaces the last opcode with its VERIFY form, and and_v and or_i give the concatenation and the IF form. The result is the script of the line above [B379] [BCD]."),
  (H, "The chapter's library applies the same table to bytes and runs the result with real signatures: the first key can spend at once with the signature and a true value, and the second key can spend only after 144 blocks, with a false value, version 2 and a sequence of at least 144. The same code compiles a multi() fragment, the 2-of-3 multisignature, and the test that the compiled bytes equal those of the library's own multisignature builder passes. The check is of the table as printed in the BIP and not of Bitcoin Core's compiler, which was not available in this environment."),
  (K, "The BIP says that its specification applies to P2WSH and tapscript scripts, and that P2SH and bare scripts are excluded. It also lists the limits that a static analysis should check: in P2WSH, scripts larger than 3,600 bytes are invalid by standardness, an operation count above 201 is invalid by consensus, and a stack above 1,000 elements is invalid in both. Miniscript is not a different way of spending; the output on the chain is an ordinary script, and what changes is the confidence with which it was made."),
 ), None),
]

CHECKS_F = [
 Qb(BK, "One of", "the more", "powerful features of Bitcoin Script is flow control, also known as", "conditional clauses.", "Bitcoin conditional opcodes allow us to construct a", "script that has two ways of being unlocked, depending on a", "+TRUE+/+FALSE+ outcome of evaluating a logical condition.", "Bitcoin Script flow control can", "be used to construct very complex scripts with hundreds", "of possible execution paths. There is no limit to nesting, but", "consensus rules impose a limit on the maximum size of a", "script in bytes."),
 Qb(BK, "Bitcoin implements flow control using the +OP_IF+, +OP_ELSE+, +OP_ENDIF+, and", "+OP_NOTIF+ opcodes.", "conditional expressions can contain", "boolean operators such as +OP_BOOLAND+, +OP_BOOLOR+, and +OP_NOT+.", "flow", "control clauses in Bitcoin also look \"backward.\"", "the condition being evaluated", "comes _before_ the +IF+ opcode."),
 Qb(BK, "any opcode that ends in", "+VERIFY+. The +VERIFY+ suffix means that if the condition evaluated is", "not +TRUE+, execution of the script terminates immediately and the", "transaction is deemed invalid.", "the +VERIFY+ suffix acts as a _guard clause_,", "continuing only if a precondition is met.", "OP_HASH160 <expected hash> OP_EQUALVERIFY <Bob's Pubkey> OP_CHECKSIG", "Without presenting the preimage, Bob can't get to the part of the", "script that checks for his signature.", "OP_HASH160 <expected hash> OP_EQUAL", "However, the", "+VERIFY+ construction is more efficient, using two fewer opcodes.", "If all we are", "trying to do is to attach a precondition (guard clause), then +VERIFY+", "is better.", "we want to have more than one execution path", "(flow control), then we need an +OP_IF...OP_ELSE+ flow control clause."),
 Qb(BK, "A very common use for flow control in Bitcoin Script is to construct a", "script that offers multiple execution paths, each a different way", "of redeeming the UTXO.", "The condition is not part of the script. Instead, the condition", "will be offered at spending time, allowing Alice and Bob to", "\"choose\" which execution path they want:", "<Alice's Sig> OP_TRUE", "<Bob's Sig> OP_FALSE", "we can create a \"maze\" of execution", "paths. The input script can provide a \"map\" selecting which", "execution path is actually executed:", "To select path +subscript B+, for", "example, the input script must end in +OP_1 OP_0+ (+TRUE+, +FALSE+).", "tens or hundreds", "of execution paths"),
 Qb(BK, "Mohammed, a company owner in Dubai, operates an import/export", "The participants in the multisig scheme are Mohammed, his", "two partners Saeed and Zaira, and their company lawyer.", "so two of the three", "must agree.", "they want", "their lawyer to be able to recover the funds with one of the three", "partner signatures.", "they want the lawyer to be able to manage the", "account directly after he gains access to the capital account's", "transaction records."),
 Qb(BK, "01  OP_IF", "02    OP_IF", "05      <30 days> OP_CHECKSEQUENCEVERIFY OP_DROP", "06      <Lawyer's Pubkey> OP_CHECKSIGVERIFY", "09    <Mohammed's Pubkey> <Saeed's Pubkey> <Zaira's Pubkey> 3 OP_CHECKMULTISIG", "11    <90 days> OP_CHECKSEQUENCEVERIFY OP_DROP", "12    <Lawyer's Pubkey> OP_CHECKSIG", "OP_0 <Mohammed's Sig> <Zaira's Sig> OP_TRUE OP_TRUE", "OP_0 <Saeed's Sig> <Lawer's Sig> OP_FALSE OP_TRUE", "<Lawyer's Sig> OP_FALSE", "The second execution path can only be used after 30 days have elapsed", "from the creation of the UTXO.", "Finally, the third execution path allows the lawyer to spend the", "funds alone, but only after 90 days.", "+TRUE+ is therefore popped _first_ by the first +OP_IF+ opcode."),
 Qe("bip-0379.md", "This document specifies Miniscript, a language for writing (a subset of) Bitcoin Scripts in a", "structured way, enabling analysis, composition, generic signing and more.", "Bitcoin Script is an unusual stack-based language with many edge cases", "Given a combination of spending conditions, finding the most economical script to implement it.", "Given two scripts, construct a script that implements a composition of their spending conditions", "These specifications apply to P2WSH", "P2SH and bare scripts are excluded from this specification.", "| nSequence ≥ n (and compatible)                           | `older(n)`                    | `<n> CHECKSEQUENCEVERIFY`", "| `pk(key)` = `c:pk_k(key)`     | `<key> CHECKSIG`", "| X and Y                                                  | `and_v(X,Y)`                  | `[X] [Y]`", "| `or_i(X,Z)`                   | `IF [X] ELSE [Z] ENDIF`", "| `v:X`                         | `[X] VERIFY (or VERIFY version of last opcode in [X])`", "| check(key_1) + ... + check(key_n) = k *(P2WSH only)*     | `multi(k,key_1,...,key_n)`    | `<k> <key_1> ... <key_n> <n> CHECKMULTISIG`", "\"**k**\" No timelock mixing.", "In P2WSH, scripts larger than 3600 bytes are invalid by standardness.", "script satisfactions where the total number of non-push opcodes plus the number of keys participating in all executed `CHECKMULTISIG` is above 201 are invalid by consensus.", "script satisfactions which make the stack exceed 1000 elements before or during execution are invalid.", "Status: Draft"),
 Qe("core_doc_bips.md", "Miniscript was partially implemented in **v24.0**", "fully implemented as of **v26.0**"),
 Qc("src/script/interpreter.cpp", "// <expression> if [statements] [else [statements]] endif", "// Tapscript requires minimal IF/NOTIF inputs as a consensus rule.", "// Under witness v0 rules it is only a policy rule, enabled through SCRIPT_VERIFY_MINIMALIF.", "return set_error(serror, SCRIPT_ERR_UNBALANCED_CONDITIONAL);", "// (true -- ) or", "// (false -- false) and return", "return set_error(serror, SCRIPT_ERR_VERIFY);"),
 Qc("src/script/interpreter.h", "SCRIPT_VERIFY_MINIMALIF,"),
 # executed: conditionals
 X("[L.run('1', 'IF 2 ELSE 3 ENDIF 2 EQUAL', flags=L.MAINNET_FLAGS), L.run('0', 'IF 2 ELSE 3 ENDIF 3 EQUAL', flags=L.MAINNET_FLAGS), L.run('1', 'NOTIF 2 ELSE 3 ENDIF 3 EQUAL', flags=L.MAINNET_FLAGS)]", ["OK", "OK", "OK"]),
 X("[L.run('', 'IF 2 ELSE 3 ENDIF', flags=L.MAINNET_FLAGS), L.run('1', 'IF 2 ELSE 3', flags=L.MAINNET_FLAGS), L.run('1', 'ENDIF 1', flags=L.MAINNET_FLAGS), L.run('0', 'IF 1 ENDIF', flags=L.MAINNET_FLAGS)]", ["INVALID_STACK_OPERATION", "UNBALANCED_CONDITIONAL", "UNBALANCED_CONDITIONAL", "EVAL_FALSE"]),
 X("[C.wsh_run(bytes([0x63, 0x51, 0x67, 0x00, 0x68]), [b'\\x05']), C.wsh_run(bytes([0x63, 0x51, 0x67, 0x00, 0x68]), [b'\\x05'], L.MAINNET_FLAGS | {'MINIMALIF'}), C.wsh_run(bytes([0x63, 0x51, 0x67, 0x00, 0x68]), [b'\\x01'], L.MAINNET_FLAGS | {'MINIMALIF'})]", ["OK", "MINIMALIF", "OK"]),
 X("C.key_spend(L.push_data(C.pub(1)) + b'\\xac', 1, wrap='p2wsh')", "OK"),
 # executed: guards
 X("L.sha256(b'abc').hex()", H_ABC),
 X("[L.run(\"'abc'\", 'OP_SHA256 0x20 0x" + H_ABC + " OP_EQUALVERIFY 1', flags=L.MAINNET_FLAGS), L.run(\"'abd'\", 'OP_SHA256 0x20 0x" + H_ABC + " OP_EQUALVERIFY 1', flags=L.MAINNET_FLAGS)]", ["OK", "EQUALVERIFY"]),
 X("[L.run('', '1 OP_VERIFY 1', flags=L.MAINNET_FLAGS), L.run('', '0 OP_VERIFY 1', flags=L.MAINNET_FLAGS), L.run('', 'OP_VERIFY 1', flags=L.MAINNET_FLAGS)]", ["OK", "VERIFY", "INVALID_STACK_OPERATION"]),
 X("(len('HASH160 h EQUALVERIFY pk CHECKSIG'.split()), len('HASH160 h EQUAL IF pk CHECKSIG ENDIF'.split()))", (5, 7)),
 X("[L.run('', '500 OP_CHECKSEQUENCEVERIFY 1', flags=L.MAINNET_FLAGS, sequence=500, version=2), L.run('', '500 OP_CHECKSEQUENCEVERIFY', flags=L.MAINNET_FLAGS, sequence=500, version=2), L.run('', '500 OP_CHECKSEQUENCEVERIFY OP_DROP', flags=L.MAINNET_FLAGS, sequence=500, version=2)]", ["OK", "OK", "EVAL_FALSE"]),
 # executed: Alice or Bob, and the maze

 X("(lambda sc: (C.key_spend(sc, 1, wrap='p2wsh', tail=[b'\\x01']), C.key_spend(sc, 2, wrap='p2wsh', tail=[b'']), C.key_spend(sc, 1, wrap='p2wsh', tail=[b'']), C.key_spend(sc, 2, wrap='p2wsh', tail=[b'\\x01'])))(b'\\x63' + L.push_data(C.pub(1)) + b'\\x67' + L.push_data(C.pub(2)) + b'\\x68\\xac')", ("OK", "OK", "EVAL_FALSE", "EVAL_FALSE")),
 X("[L.run('1', 'IF 10 ELSE 20 ENDIF 10 EQUAL', flags=L.MAINNET_FLAGS)]", ["OK"]),
 X("[L.run(c, 'IF 10 ELSE IF 20 ELSE 30 ENDIF ENDIF %d EQUAL' % v, flags=L.MAINNET_FLAGS) for c, v in (('1', 10), ('1 0', 20), ('0 0', 30))]", ["OK", "OK", "OK"]),
 # executed: Mohammed
 X("(len(C.moh_script()), len(C.moh_script(4320, 12960)), 30 * 144, 90 * 144)", (192, 192, 4320, 12960)),
 X("[C.moh_spend(1, wrap=w) for w in ('p2wsh', 'p2sh')]", ["OK", "OK"]),
 X("[C.moh_spend(2, sequence=sq, wrap=w) for w in ('p2wsh', 'p2sh') for sq in (4320, 4319)]", ["OK", "UNSATISFIED_LOCKTIME", "OK", "UNSATISFIED_LOCKTIME"]),
 X("[C.moh_spend(3, sequence=sq, wrap=w) for w in ('p2wsh', 'p2sh') for sq in (12960, 12959)]", ["OK", "UNSATISFIED_LOCKTIME", "OK", "UNSATISFIED_LOCKTIME"]),
 X("C.moh_spend(3, sequence=12960, signers=['M'])", "EVAL_FALSE"),
 X("(C.moh_spend(1, signers=['Z', 'M']), C.moh_spend(1, signers=['M', 'S']), C.moh_spend(1, signers=['S', 'Z']), C.moh_spend(1, signers=['M']))", ("EVAL_FALSE", "OK", "OK", "INVALID_STACK_OPERATION")),
 X("(C.moh_spend(2, sequence=4320, signers=['L', 'S']), C.moh_spend(2, sequence=4320, signers=['S', 'Z']), C.moh_spend(2, sequence=4320, signers=['M', 'L']), C.moh_spend(2, sequence=4320, signers=['Z', 'L']))", ("CHECKSIGVERIFY", "CHECKSIGVERIFY", "OK", "OK")),
 X("(C.moh_spend(3, sequence=12960, version=1), C.moh_spend(2, sequence=4320, version=1), C.moh_spend(1, version=1))", ("UNSATISFIED_LOCKTIME", "UNSATISFIED_LOCKTIME", "OK")),
 X("(C.moh_spend(2, sequence=4320, count=True), C.moh_spend(1, count=True), C.moh_spend(3, sequence=12960, count=True))", (("OK", 3), ("OK", 3), ("OK", 1))),
 X("(C.moh_spend(2, sequence=4320 | (1 << 22)), C.moh_spend(2, sequence=0x80000000 | 4320))", ("UNSATISFIED_LOCKTIME", "UNSATISFIED_LOCKTIME")),
 X("L.classify(C.moh_script())", ("nonstandard", "")),
 # executed: miniscript
 X("(lambda sc: L.disassemble(sc).split()[0::1][:1] + [L.disassemble(sc).split()[-1]])(C.ms_compile(" + MSB + "))", ["OP_IF", "OP_ENDIF"]),
 X("(lambda sc: [C.key_spend(sc, 0, wrap='p2wsh', tail=[b'\\x01'], sequence=0, version=2), C.key_spend(sc, 1, wrap='p2wsh', tail=[b''], sequence=144, version=2), C.key_spend(sc, 1, wrap='p2wsh', tail=[b''], sequence=143, version=2), C.key_spend(sc, 1, wrap='p2wsh', tail=[b'\\x01'], sequence=144, version=2)])(C.ms_compile(" + MSB + "))", ["OK", "OK", "UNSATISFIED_LOCKTIME", "EVAL_FALSE"]),
 X("C.ms_compile(('multi', 2, 'M', 'S', 'Z')) == L.multisig_script(2, [C.pub(0), C.pub(1), C.pub(2)])", True),
 X("C.ms_compile(('v', ('pk', 'M'))) == L.push_data(C.pub(0)) + b'\\xad'", True),
 X("C.ms_compile(('v', ('older', 144))) == L.push_int(144) + b'\\xb2\\x69'", True),
 X("L.disassemble(C.ms_compile(('and_v', ('v', ('pk', 'M')), ('after', 500000)))).split()[-3:]", ["OP_CHECKSIGVERIFY", "20a107", "OP_CHECKLOCKTIMEVERIFY"]),
 X("len(C.ms_compile(('multi', 15, *'MSZLMSZLMSZLMSZ')))", 3 + 34 * 15),
 X("sum(1 for s in C.witness_scripts(L) if any(op[1] in (0x63, 0x64) for op in L.get_ops(s)))", 0),
 X("(lambda w: (any(op[1] == 0x63 for op in L.get_ops(w[-2])), b'image/png' in w[-2]))(L.parse_tx(C.tx_record('4e0e703251bb')[0]).witness[0])", (True, True)),
]
