"""SEN0401 chapter 6, corpus text part H (version 1.0.0): the branch 'Weight and foundations' - the weight and vbyte units, the
4,000,000 limit, the factors of 4 and 1 recomputed for every field of Alice's transaction, and the terms the chapter leans on
without defining in place: the hash function and double SHA-256, the txid and wtxid, and the difference between relay policy and
consensus. Markers become author-year strings."""
from sen0401_ch06_common_v1_0_0 import *

NODES_H = [
 ("WeightAndFoundations", "Weight and foundations", 1, None, None, P(
  (W, "This last branch has two jobs. The first is the book's section on weight and vbytes: each Bitcoin block is limited in the amount of transaction data it can contain, so most Bitcoin software needs to be able to measure the transactions it creates or processes, and the modern unit of measurement is called weight, with vbytes as an alternative in which four units of weight equal one vbyte [AH]. The second is to explain the terms the chapter uses throughout without a section of their own: the hash function, double SHA-256, the txid and wtxid, relay policy and consensus."),
  (Y, "Weight matters because it is what a transaction pays for. Fees are quoted per vbyte, blocks are filled by weight, and the factors that make a witness byte cost a quarter of any other byte are what makes segwit cheaper and what the book says was chosen to reduce the weight used when spending a UTXO, discouraging uneconomical outputs [AH]. The foundations matter because the chapter's arguments rest on them: malleability is about what a hash covers, and half the rules in the chapter are policy rather than consensus."),
  (E, "The reader meets weight in every fee estimate a wallet shows and in the figure 569 that Bitcoin Core reports for Alice's transaction, which this course recomputes from the bytes field by field. The reader meets the foundations wherever the chapter says txid, hashes, standard or valid; the two kinds of rule are met in the version branch's version 3 proposal, the outputs branch's dust limit and the sequence branch's replacement policy, each a policy, against the consensus rules of lock time, maturity and the subsidy [AH]."),
  (H, "The branch has two groups. The weight units group explains weight, vbytes, the block limit with its header and transaction-count overhead, and the per-field factors, with the book's table recomputed and summed to 569. The foundations group explains the hash function and its double application, the transaction identifier and the witness transaction identifier as two hashes over two serializations, and the distinction between the relay policy a node chooses and the consensus rules every node must apply [AH] [B141] [BCW].")), None),

 ("WeightUnits", "Weight and vbytes", 2, "WeightAndFoundations", None, P(
  (W, "Weight is the modern unit in which the size of a transaction or a block is measured, and vbytes are weight divided by four. The book says blocks are limited to 4 million weight, that the block header takes up 240 weight and the transaction count 4 or 12, that all the remaining weight may be used for transaction data, and that to calculate the weight of a field its serialized size in bytes is multiplied by a factor, with the weight of a transaction the sum over its fields [AH]."),
  (Y, "The unit matters because it replaced the byte as the measure of block capacity when segwit activated, and because the replacement is uneven on purpose: a byte of witness data weighs one unit and any other byte weighs four, so the same transaction is cheaper in the segwit format than it would be with its signatures in the input script. The book says the factors and the fields they apply to were chosen to reduce the weight used when spending a UTXO, which helps discourage the creation of uneconomical outputs [AH] [B141]."),
  (H, "The four sections cover the unit, its quarter, the limit and the factors. Weight is defined by BIP141's formula and recomputed for Alice's transaction; vbytes are the rounded-up quarter, 143 for her; the block weight limit is Bitcoin Core's constant with the header and count overheads the book lists; and the weight factors section recomputes the book's table of every field of Alice's transaction and sums it to 569, the number Bitcoin Core returns [AH] [BCW] [BCC].")), None),

 ("Weight", "Weight", 3, "WeightUnits", ("3 times the legacy size plus the full size", "Weight is BIP141's measure of a transaction: the legacy serialization's size times 3 plus the full serialization's size, which is 569 for Alice's transaction, the figure Bitcoin Core reports.", (PROG("tx = bytes.fromhex('01000000000101eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a0100000000ffffffff02204e0000000000002251203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068f8240100000000001600147752c165ea7be772b2c0acb7f4d6047ae6f4768e0141cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e817130100000000')\nlegacy = tx[:4] + tx[6:-71] + tx[-4:]\nresult = (len(legacy), len(tx), len(legacy) * 3 + len(tx))"), "(125, 194, 569)")), P(
  (W, "Weight is the modern unit of measurement for the size of Bitcoin transactions and blocks. The book says each block is limited in the amount of transaction data it can contain, so most software needs to measure the transactions it creates or processes, and that the unit is called weight [AH]. BIP141 defines a transaction's weight as its base size, the serialization without witness data, times three, plus its total size with the witness, and Bitcoin Core's GetTransactionWeight computes exactly that [B141] [BCW]."),
  (Y, "Weight matters because it is the number a fee is paid for and the number a block is filled by. The book verifies its own table by asking Bitcoin Core for the weight of Alice's transaction and receiving 569; this course cannot run a node, but it recomputes the number from the bytes and finds the same, and the explorer that this course consulted reports 569 as well [AH] [MP]. Every fee-rate figure a wallet shows is a fee divided by this number or by its quarter."),
  (H, "The worked example computes both sizes and the formula: the legacy serialization of Alice's transaction, without the marker, the flag and the 67-byte witness structure, is 125 bytes; the full serialization is 194; and three times 125 plus 194 is 569. The same result follows from the per-field factors of the later section, since multiplying the legacy bytes by three and adding every byte once is the same as charging four for a legacy byte and one for a witness byte. A legacy transaction's weight is simply four times its size [B141]."),
  (K, "The caution is that weight is not bytes and is not what the network transmits: Alice's transaction is 194 bytes on the wire and 569 in weight, and a fee rate in satoshis per byte and one in satoshis per vbyte differ by the discount. A second caution is that weight counts the serialized bytes only; the cost of validating a transaction, in signature checks, is bounded by a separate limit that the book's chapter on mining discusses [BCC].")), None),

 ("Vbyte", "Vbytes", 3, "WeightUnits", ("weight divided by four, rounded up", "A vbyte is a quarter of a weight unit, rounded up, so that a legacy transaction's vbytes equal its bytes; Alice's transaction is 143 vbytes.", ("(-(-569 // 4), 569 / 4, 194 * 4 // 4)", "(143, 142.25, 194)")), P(
  (W, "A vbyte, a virtual byte, is an alternative version of weight in which four units of weight equal one vbyte. The book says it provides an easy comparison to the original byte measurement unit used in legacy Bitcoin blocks [AH]. BIP141 defines the virtual transaction size as the weight divided by four, rounded up to the next integer, so a transaction with no witness has as many vbytes as bytes and a segwit transaction has fewer [B141]."),
  (Y, "The unit matters because it is what most wallets and fee estimators quote: a fee of 10 satoshis per vbyte, not per weight unit, and the old intuition that a block holds a million bytes becomes a million vbytes. The worked example computes Alice's 143 vbytes from 569 weight, shows the unrounded quarter of 142.25, and shows that a legacy transaction's vbytes equal its bytes, which is the comparison the book means."),
  (H, "The rounding is always up, so that fractional weight cannot be hidden: 569 divided by four is 142.25 and the vbyte count is 143. The chapter's library computes it with a negative floor division, the standard way to round up in integer arithmetic. Because a block's limit of 4 million weight is a million vbytes, a fee rate per vbyte and a block's capacity in vbytes are the two numbers a miner uses to fill a block, which the book's chapter on fees develops [B141]."),
  (K, "The caution is that two transactions of the same byte size can have different vbyte sizes, because their witness shares differ: a taproot spend's 65-byte signature is cheap and a legacy spend's 107-byte input script is not. A second caution is the name: a vbyte is a unit of weight, not a kind of byte, and the serialized transaction does not change size when measured in it.")), None),

 ("BlockWeightLimit", "The block weight limit", 3, "WeightUnits", ("4 million weight a block", "Blocks are limited to 4,000,000 weight, Bitcoin Core's MAX_BLOCK_WEIGHT; the header and the transaction count take a small fixed share and the rest is for transactions.", ("(4_000_000, 4_000_000 // 4, 4_000_000 // 569)", "(4000000, 1000000, 7029)")), P(
  (W, "The block weight limit is the consensus rule that blocks are limited to 4 million weight. The book says so and adds the overheads: the block header takes up 240 weight, an additional field, the transaction count, uses either 4 or 12 weight, and all of the remaining weight may be used for transaction data [AH]. Bitcoin Core names the limit MAX_BLOCK_WEIGHT with the value 4,000,000 and cites BIP141 for it, and BIP141's rule is that block weight is at most 4,000,000 [BCC] [B141]."),
  (Y, "The limit matters because it is the scarce resource every fee competes for. Four million weight is a million vbytes, and the worked example shows that if every transaction were Alice's, a block would hold about 7,029 of them; the book's chapter on fees treats the market this creates. The limit replaced the earlier one-megabyte limit on the block's size at the segwit soft fork, which is why the book speaks of legacy blocks and the original byte unit [AH] [B141]."),
  (H, "The weight of a block is computed by the same formula as a transaction's, over the whole serialized block: BIP141 defines block weight as base size times three plus total size, and Bitcoin Core's GetBlockWeight applies it to the block, header included [B141] [BCW]. The transaction count is a compactSize integer, one byte for up to 252 transactions and three bytes beyond, which at a factor of four gives the book's 4 or 12 weight; a block with thousands of transactions uses the three-byte form."),
  (K, "The caution is the header figure. An 80-byte header counted by BIP141's formula weighs 80 times three plus 80, which is 320, not 240; 240 is 80 times three, the base-size part alone, so the book's figure appears to omit the header's contribution to the total size, a discrepancy an executed claim of this chapter records [AH] [B141]. The difference is 80 units out of four million and changes no conclusion, but a reader computing capacity to the byte should use 320.")), None),

 ("WeightFactor", "Weight factors", 3, "WeightUnits", ("4 for most fields, 1 for marker, flag and witness", "Each field's weight is its serialized size times a factor: 4 for the version, inputs, outputs and lock time, 1 for the marker, the flag and the witness structure; summed over Alice's transaction the factors give 569.", (PROG("rows = [('Version', 4, 4), ('Marker & Flag', 2, 1), ('Inputs Count', 1, 4), ('Outpoint', 36, 4), ('Input script', 1, 4), ('Sequence', 4, 4), ('Outputs Count', 1, 4), ('Amount', 16, 4), ('Output script', 58, 4), ('Witness Count', 1, 1), ('Witness items', 66, 1), ('Lock time', 4, 4)]\nresult = ([(n, b * f) for n, b, f in rows], sum(b * f for n, b, f in rows))"), "([('Version', 16), ('Marker & Flag', 2), ('Inputs Count', 4), ('Outpoint', 144), ('Input script', 4), ('Sequence', 16), ('Outputs Count', 4), ('Amount', 64), ('Output script', 232), ('Witness Count', 1), ('Witness items', 66), ('Lock time', 16)], 569)")), P(
  (W, "The weight factors are the multipliers applied to each field's size. The book says that to calculate the weight of a particular field the size of that serialized field in bytes is multiplied by a factor, and that the weight of a transaction is the sum of the weights of all its fields; its table gives a factor of 4 for the version, the counts, the outpoint, the input script, the sequence, the amount, the output script and the lock time, and a factor of 1 for the marker and flag, the witness count and the witness items, and totals Alice's transaction at 569 [AH]."),
  (Y, "The factors matter because they are where the discount lives. The book says they were chosen to reduce the weight used when spending a UTXO, which discourages uneconomical outputs: the signature that spends an output is witness data at a factor of 1, while the output script that creates one is at 4, so creating outputs is relatively dear and spending them relatively cheap [AH]. In Alice's transaction the 66 bytes of witness items weigh 66, while the 58 bytes of her two output scripts weigh 232."),
  (H, "The worked example rebuilds the book's table from the byte counts of each field and the two factors: 16 for the version, 2 for the marker and flag, 4 for the input count, 144 for the 36-byte outpoint, 4 for the one-byte prefix of the empty input script, 16 for the sequence, 4 for the output count, 64 for two 8-byte amounts, 232 for the two output scripts with their length prefixes, 1 for the witness count, 66 for the witness item with its length, and 16 for the lock time, which sum to 569. The chapter's library derives the same rows from its byte spans rather than from a typed table, and an executed claim compares the two [AH]."),
  (K, "The caution is that the book's rows group bytes in a way a parser does not: the outpoint row is the 32-byte identifier and the 4-byte index together, the output script row includes each script's length prefix, and the witness items row includes the item's length byte. A second caution is that only three rows carry the factor of 1, so a transaction's discount depends entirely on how much of it is witness, which is why a taproot spend with a 65-byte witness is among the lightest transactions there are.")), None),

 ("Foundations", "Foundations", 2, "WeightAndFoundations", None, P(
  (W, "This group explains the terms the chapter uses on every page without a section of its own. The hash function and its double application are what every identifier and commitment in the chapter is made of; the txid and the wtxid are the two identifiers BIP141 defines over the two serializations; and relay policy and consensus rules are the two kinds of rule the chapter keeps distinguishing, from the dust limit to the standard templates to the version 3 proposal [AH] [B141]."),
  (Y, "The group matters because the chapter's hardest ideas are precise statements about these terms. Malleability is the statement that a txid covers the input script; segregated witness is the statement that it covers the legacy serialization only; the book's remark that there is more to replacement than fee rates is a statement about policy; and the maturity rule is a statement about consensus. A reader who has the terms straight can follow each argument as a line of a proof."),
  (H, "The six sections are two triples. The first triple is cryptographic: the hash function, the double SHA-256 that Bitcoin applies to it, and the two identifiers that result. The second is institutional: the relay policy that a node chooses and may change, the consensus rule that every node must apply identically, and the memory pool in which policy is applied, which the book's later chapters treat at length and this chapter needs only as a name [AH].")), None),

 ("HashFunction", "Hash function", 3, "Foundations", ("any input, a fixed 32-byte digest", "A hash function maps input of any length to a fixed-length digest, one-way and unpredictable, so that a digest can identify data and commit to it; Bitcoin's is SHA-256, with a 32-byte output.", ("(len(__import__('hashlib').sha256(b'').digest()), len(__import__('hashlib').sha256(b'x' * 10000).digest()))", "(32, 32)")), P(
  (W, "A hash function is a function that maps data of any length to a digest of fixed length, in a way that cannot be run backwards and that changes the digest unpredictably when the input changes. Chapter 4 introduced it for addresses; this chapter relies on it for identifiers and commitments, and the book's sidebar lists the uses: unique identifiers for blocks and transactions, commitments for addresses, blocks, transactions and signatures, and the iteration of proof of work [AH]. Bitcoin's function is SHA-256, whose digest is 32 bytes."),
  (Y, "The function matters here for two properties. Fixed length is why a 32-byte txid can stand for a transaction of any size and sit in a 36-byte outpoint. Sensitivity to the input is why a transaction's identifier changes completely when a single byte of its serialization changes - the property that makes identifiers trustworthy and that makes malleability a problem, since any mutation of the hashed bytes, however meaningless to the script interpreter, produces a new identifier [AH]."),
  (H, "The worked example hashes an empty input and a ten-thousand-byte input and finds 32 bytes both times. Python's hashlib provides the function, and every worked example in this chapter that computes an identifier uses it twice in succession, which the next section explains. A commitment uses the function in the order the book describes: the digest is published first, the data later, and anyone can check that the data hashes to the digest, which is how a block commits to its transactions and an outpoint to a previous transaction."),
  (K, "The caution is that a hash function identifies bytes, not meaning: two serializations of the same transaction, one with witness and one without, hash to different values, and two byte strings that push the same number hash differently, which is the whole of the malleability group. A second caution is that the one-way and collision-free properties are the current state of cryptanalysis rather than theorems, as chapter 4 noted.")), None),

 ("DoubleSha256", "Double SHA-256", 3, "Foundations", ("SHA-256 of SHA-256", "Bitcoin's identifiers are double SHA-256: the hash function applied to its own output, so a txid is SHA-256 of SHA-256 of the legacy serialization, shown reversed.", ("__import__('hashlib').sha256(__import__('hashlib').sha256(b'hello').digest()).digest()[::-1].hex()[:16]", "'503d8319a48348cd'")), P(
  (W, "Double SHA-256 is the hash construction Bitcoin uses for transaction and block identifiers: SHA-256 applied to the output of SHA-256. Chapter 4 met it in base58check, where the first four bytes of a double hash are a checksum; here it is the whole of the identifier. The chapter's library writes it as hash256, the name Bitcoin Core uses, and every identifier the book prints - Alice's 46620030..., the previous transaction's 4ac54180... - is such a double hash reversed into display order [AH]."),
  (Y, "The construction matters because it is exactly what the word txid means in every sentence of the chapter. When the book says every field of a legacy transaction is used to derive the txid, it means every field is in the bytes that are hashed twice; when BIP141 says the witness is excluded from the txid, it means the bytes hashed are the legacy serialization. Knowing the construction lets a reader recompute any identifier in the chapter, which the worked examples of the witness branch do [B141]."),
  (H, "The worked example double-hashes a short string and shows the reversed digest's first sixteen characters; the same two lines, applied to the 125 legacy bytes of Alice's transaction, give her identifier, as the segregated witness section's example shows. The reversal is the byte-order convention of the inputs branch. Why the function is applied twice is a historical design choice; the book does not explain it, and the practical consequence is only that every identifier costs two hash computations."),
  (K, "The caution is that the double hash is over the serialization, so any program that serializes a transaction differently - a different compactSize encoding, a witness included where it should not be - computes a different identifier and will not find the transaction it is looking for. A second caution is that the chapter's examples compute identifiers from saved bytes, and a saved copy that was edited by hand would hash to something else; the executed claims compare against the explorer's and the book's identifiers for that reason [MP].")), None),

 ("Txid", "Transaction identifier", 3, "Foundations", ("double SHA-256 of the legacy bytes, reversed", "The txid is the double SHA-256 of a transaction's legacy serialization, displayed in reversed byte order; for a segwit transaction it therefore excludes the witness.", ("len('466200308696215bbc949d5141a49a4138ecdfdfaa2a8029c1f9bcecd1f96177')", "64")), P(
  (W, "The transaction identifier, txid, is the double SHA-256 of a transaction's serialization in display byte order. The book uses the term from the chapter's first listing, where it asks Bitcoin Core for the transaction by its identifier, and makes its definition explicit in the witness branch: in the legacy format every field, including the input script that contains signatures, is used to derive a transaction's identifier [AH]. BIP141 keeps the identifier as the hash of the serialization without the witness, so that it is unchanged for legacy transactions and witness-independent for segwit ones [B141]."),
  (Y, "The identifier matters because it is how everything refers to a transaction: an outpoint, an explorer, a wallet's history, a block's merkle tree. Its exact scope is the subject of the witness branch - a malleable identifier breaks every outpoint that names it, and segwit fixes the scope so that nothing a third or second party can change is in it [AH]. The worked example confirms the identifier's display length, 64 hexadecimal characters for 32 bytes, the count the book gave at the start of the chapter."),
  (H, "A node computes the identifier by serializing the transaction in the legacy format, hashing twice and storing the result; it displays it reversed. The chapter's library's txid function does these steps and an executed claim shows it reproducing the identifiers of all four saved transactions, including the two legacy ones from 2009 and 2010, which have no witness and whose legacy serialization is their whole serialization [MP]. A block's merkle tree, which the book's chapter on the blockchain explains, is built from these identifiers in internal order."),
  (K, "The caution is the one the witness branch exists for: before segwit, the identifier of an unconfirmed transaction was not reliable, and a protocol that stored one could find it changed; after segwit, it is reliable only for inputs that spend segwit outputs. A second caution is that the identifier does not commit to the witness, so two valid transactions with the same identifier and different witnesses are possible, which is why BIP141 adds the next section's identifier [B141].")), None),

 ("Wtxid", "Witness transaction identifier", 3, "Foundations", ("the hash of everything, witness included", "The wtxid is the double SHA-256 of the whole extended serialization, witness included; it changes when the witness changes, and blocks commit to it separately from the txid.", ("(lambda a, b: a != b)('466200308696215bbc949d5141a49a4138ecdfdfaa2a8029c1f9bcecd1f96177', 'f7cdbc7cf8b910d35cc69962e791138624e4eae7901010a6da4c02e7d238cdac')", "True")), P(
  (W, "The witness transaction identifier, wtxid, is the double SHA-256 of a transaction's full extended serialization, witness included, in display byte order. BIP141 defines it beside the txid: a new data structure, the witness, is committed to by a new identifier, and a block that contains segwit transactions commits to the wtxids of all its transactions through an output of its coinbase [B141]. The book mentions this commitment among the coinbase's special rules and defers its details to the chapter on mining [AH]."),
  (Y, "The wtxid matters because something must commit to witnesses. Leaving the witness out of the txid is what removes malleability, but a block that committed only to txids would let anyone substitute a different valid witness for a transaction after the fact; the wtxid closes that gap, and the coinbase commitment ties every wtxid to the block. For a legacy transaction, whose serialization has no witness, BIP141 says the wtxid equals the txid [B141]."),
  (H, "The worked example compares Alice's two identifiers, her txid 46620030... and her wtxid f7cdbc7c..., and finds them different, as they must be for a transaction with a witness. The chapter's library computes the wtxid over the 194 extended bytes and the txid over the 125 legacy bytes, and an executed claim shows that replacing the witness item changes the first and not the second. The commitment in the coinbase is a merkle root of wtxids with the coinbase's own entry set to zero, which the book's chapter on mining describes [B141]."),
  (K, "The caution is that the wtxid is not what outpoints use: an input names a previous output by txid, never by wtxid, which is why the txid's stability is what matters for presigned transactions. A second caution is that explorers rarely show the wtxid, so a reader who wants to check one must compute it, which is one reason this chapter's library exists.")), None),

 ("RelayPolicy", "Relay policy", 3, "Foundations", ("what a node chooses to relay and keep", "Relay policy is the set of rules a full node applies to unconfirmed transactions it relays and keeps in its memory pool; it is chosen by the node, can change, and includes dust, standardness, version 3 and replacement rules.", ("sorted(['dust limit', 'standard outputs', 'version 3 restrictions', 'replace-by-fee', 'reserved features'])", "['dust limit', 'replace-by-fee', 'reserved features', 'standard outputs', 'version 3 restrictions']")), P(
  (W, "Relay policy is the set of rules a full node applies when deciding which unconfirmed transactions to relay to its peers and to keep in its memory pool, the store of transactions waiting for a block. The book names such rules throughout the chapter: Bitcoin Core's default transaction relay policy that refuses reserved features, the dust policies that affect the relay and mining of unconfirmed transactions, the policy that limits output scripts to standard templates, and the policy of replacement [AH]. Bitcoin Core's policy sources hold the constants [BCP]."),
  (Y, "The distinction matters because policy is not validity. A transaction that violates policy can still be included in a block by a miner who chooses to, and the block is valid; a transaction that violates consensus can never be. The book's version 3 proposal is the clearest case, a change that does not seek to change the consensus rules but only the policy that nodes use to relay transactions, and the book's advice to test a transaction with testmempoolaccept is advice about policy [AH]. The worked example lists the policies this chapter has met."),
  (H, "A node applies policy in its memory pool: a received transaction is checked against consensus first and then against policy, and one that fails policy is dropped without being relayed, which is why non-standard transactions rarely reach miners. Policy is set by the software's defaults and the operator's options, so it can differ between nodes and change between releases; Bitcoin Core's documentation lists which proposals its policy implements and since which release [BCD]. The book's phrase as of this writing recurs in this chapter because policy moves."),
  (K, "The caution is to never rely on policy as a guarantee: a presigned transaction that is standard today may be non-standard later, and a dust limit that protects a protocol today may be lowered. A second caution is the reverse: policy is also a protection, as the version 3 and reserved-features rules show, so a developer who routes around it by using a non-default node forfeits that protection [AH].")), None),

 ("ConsensusRule", "Consensus rule", 3, "Foundations", ("what every node must enforce identically", "A consensus rule is a rule every full node enforces identically to decide which blocks and transactions are valid; this chapter's examples are the input and output bounds, the amount range, BIP68, the lock time, the subsidy and the maturity rule.", ("sorted(['at least one input and one output', 'amount range', 'no double spend', 'BIP68 sequence locks', 'lock time since block 31,000', 'subsidy and reward', 'coinbase maturity', 'block weight'])", "['BIP68 sequence locks', 'amount range', 'at least one input and one output', 'block weight', 'coinbase maturity', 'lock time since block 31,000', 'no double spend', 'subsidy and reward']")), P(
  (W, "A consensus rule is a rule that every full node enforces identically to decide whether a block, and each transaction in it, is valid. Chapter 2 introduced the term; this chapter is full of its instances, which the worked example lists: a transaction has at least one input and one output, amounts lie in range, no output is spent twice, the sequence locks of BIP68, the lock time rule since block 31,000, the subsidy and the reward, the maturity of coinbase outputs, and the block weight limit [AH] [BCT] [BCV] [BCC]."),
  (Y, "Consensus rules matter because they are what the ownership record of the first branch is made of: a full node's database is the result of applying them to every block, and two nodes that apply the same rules to the same blocks hold the same record. They can be changed only by the soft forks and hard forks of the witness branch, and the book's care about presigned transactions and reserved features is care about how those changes are made safely [AH]."),
  (H, "Bitcoin Core keeps its context-free consensus checks in CheckTransaction, which refuses with named reasons - bad-txns-vin-empty, bad-txns-vout-negative, bad-cb-length and the rest - and its context-dependent ones, which need the UTXO database and the chain, in its input verification and block connection, where the lock time, the sequence locks, the maturity and the reward are checked [BCT] [BCV] [BCL]. Every executed claim of this chapter that names such a reason reads it from the saved source at the pinned commit."),
  (K, "The caution is that consensus is defined by what the nodes run, not by any document: a proposal describes a rule, but the rule binds only once the economic majority enforces it, which the book says in its soft-fork definition. A second caution is that the boundary moves in one direction in practice - policy rules sometimes become consensus rules, as the lock time did at block 31,000 - and a developer should read a policy rule as a possible future consensus rule [AH].")), None),
]

CHECKS_H = [
 Qb("ch06_transactions.adoc", "The modern unit of measurement", "for Bitcoin is called _weight_", "four units of weight equal one vbyte"),
 Qb("ch06_transactions.adoc", "Blocks are limited to 4 million weight.", "The block header takes up 240", "weight.", "uses either 4 or", "12 weight."),
 Qb("ch06_transactions.adoc", "chosen to", "reduce the weight used when spending a UTXO"),
 Qb("ch06_transactions.adoc", "2 | jq .weight", "569"),
 Qe("bip-0141.mediawiki", "''Transaction weight'' is defined as ''Base transaction size'' * 3 + ''Total transaction size''", "''Virtual transaction size'' is defined as ''Transaction weight'' / 4 (rounded up to the next integer).", "The new rule is ''block weight'' ≤ 4,000,000."),
 Qc("src/consensus/consensus.h", "MAX_BLOCK_WEIGHT{4'000'000}", "WITNESS_SCALE_FACTOR = 4"),
 Qc("src/consensus/validation.h", "return ::GetSerializeSize(TX_NO_WITNESS(tx)) * (WITNESS_SCALE_FACTOR - 1) + ::GetSerializeSize(TX_WITH_WITNESS(tx));"),
 # the weight, recomputed and compared with the book's figure and the explorer's
 X("(T.weight(%r), T.vbytes(%r))" % (ALICE, ALICE), (569, 143)),
 X("C.ev_json('mempool_tx_466200308696215b_v1_0_0.json')['weight']", 569),
 X("sum(w for n, b, f, w in T.field_weights(%r))" % ALICE, 569),
 X("[(n, b, f, w) for n, b, f, w in T.field_weights(%r) if f == 1]" % ALICE, [('marker', 1, 1, 1), ('flag', 1, 1, 1), ('witness 0 count', 1, 1, 1), ('witness 0 item 0 length', 1, 1, 1), ('witness 0 item 0', 65, 1, 65)]),
 X("(T.weight(C.ev_hex('tx_first_f4184fc5_v1_0_0.hex')), 4 * T.parse_tx(C.ev_hex('tx_first_f4184fc5_v1_0_0.hex'))['size'], C.ev_json('mempool_tx_f4184fc596403b9d_v1_0_0.json')['weight'])", (1100, 1100, 1100)),
 X("(T.weight(C.ev_hex('tx_pizza_a1075db5_v1_0_0.hex')), C.ev_json('mempool_tx_a1075db55d416d3c_v1_0_0.json')['weight'], T.vbytes(C.ev_hex('tx_pizza_a1075db5_v1_0_0.hex')))", (94480, 94480, 23620)),
 X("(T.weight(C.ev_hex('tx_alice_prev_4ac54180_v1_0_0.hex')), C.ev_json('mempool_tx_4ac5418026798669_v1_0_0.json')['weight'])", (609, 609)),
 # the header: 80 bytes by BIP141's formula
 X("(80 * 3 + 80, 80 * 3, T.WITNESS_SCALE_FACTOR * 80)", (320, 240, 320)),
 # the four identifiers reproduce from the saved bytes
 X("[T.txid(C.ev_hex(f)) == C.ev_json(j)['txid'] for f, j in (('tx_alice_46620030_v1_0_0.hex', 'mempool_tx_466200308696215b_v1_0_0.json'), ('tx_alice_prev_4ac54180_v1_0_0.hex', 'mempool_tx_4ac5418026798669_v1_0_0.json'), ('tx_first_f4184fc5_v1_0_0.hex', 'mempool_tx_f4184fc596403b9d_v1_0_0.json'), ('tx_pizza_a1075db5_v1_0_0.hex', 'mempool_tx_a1075db55d416d3c_v1_0_0.json'))]", [True] * 4),
 X("T.wtxid(C.ev_hex('tx_first_f4184fc5_v1_0_0.hex')) == T.txid(C.ev_hex('tx_first_f4184fc5_v1_0_0.hex'))", True),
 X("T.hash256(b'hello')[::-1].hex()[:16]", "'503d8319a48348cd'"),
 ("(125 * 3 + 194, -(-569 // 4), 4000000 // 4)", "(569, 143, 1000000)"),
 ("(16 + 2 + 4 + 144 + 4 + 16 + 4 + 64 + 232 + 1 + 66 + 16, 1 + 1 + 65, 36 * 4, 58 * 4)", "(569, 67, 144, 232)"),
 ("(1 * 4, 3 * 4)", "(4, 12)"),
 # the owner's 2021 course notes on this chapter, written after the 2nd edition: read from the file
 Pp("Chapter_6_Transactions_v1_0_0.pptx", "Transactions are Data Structures", "Incompleteness of Transactions", "Indivisible Units of Value", "Table 6-1. Transaction output serialization"),
]
