"""SEN0401 chapter 4, corpus text part A (version 1.1.0): the branch 'Keys' down to the key pair and randomness.
Markers such as [BK] are replaced by author-year strings in sen0401_ch04_corpus_v1_1_0.py. The first element of every paragraph tuple is
only the author's writing guide and is not printed."""
W, Y, E, H, K = "What it is", "Why it matters", "Where you meet it", "How it works", "Watch out"
KHEX = "1E99423A4ED27608A15A2616A2B0E9E52CED330AC530EDCC32C8FFC6A526AEDD"
NHEX = "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141"
YHEX = "0x07CF33DA18BD734C600B96A72BBC4749D5141C90EC8AC328AE52DDFE2E505BDB"

NODES_A = [
 ("Keys", None, 1, None, None, [
  (W, "This branch of the chapter starts from a payment. Alice wants to pay Bob, but the thousands of full nodes that will verify her transaction do not know who Alice or Bob are, and the design is meant to keep it that way, to protect their privacy [BK]. Alice therefore has to tell the network that Bob should receive some of her bitcoins without tying any part of the transaction to Bob's real-world identity, and without linking it to the other payments Bob receives. The method must also guarantee that only Bob can spend what he receives afterwards. Keys are the answer to both demands, and the rest of the chapter is the story of how a key becomes something that one person can hand to another."),
  (Y, "Without keys there would be no way to decide who may spend a coin. A bank answers that question by looking up an account holder in its own records, but a network of nodes that do not trust one another has no such record and no such authority. Bitcoin replaces the account holder with a pair of numbers: whoever can produce a valid signature with the right private number may spend, and anyone can check the signature with the matching public number. The original Bitcoin paper describes this in its simplest form, in which a receiver like Bob accepts bitcoins to a public key in a transaction that the spender signs, and in which full nodes verify that the spender's signature commits to the output of a hash function that itself commits to Bob's public key and the other transaction details [BK]."),
  (E, "You meet keys every time you use a wallet. Chapter 1 described the wallet as the software through which people use Bitcoin and explained that in a noncustodial wallet only the user holds the keys. Chapter 2 showed that a transaction input carries a digital signature and an output receives funds. This chapter opens those two ideas up: it shows what the signature is made from, how the number that stands behind a payment is generated, and why the strings that people actually copy, such as an address, look the way they do."),
  (H, "The branch is arranged as the book arranges its argument. The key pair section introduces public key cryptography, the digital signature, the private key and the public key. The randomness section explains where a private key must come from. The curve section describes the mathematics that turns a private key into a public key, and the hash function section describes the second tool, which lets a long public key be replaced by a short commitment. Later branches of the chapter combine these ingredients into the addresses that modern Bitcoin software uses [BK]."),
  (K, "Two warnings run through everything that follows. The private key must stay secret at all times, because revealing it to a third party is equivalent to giving that party control over the bitcoins it secures. It must also be backed up and protected from accidental loss, because a lost private key cannot be recovered and the funds it secured are lost for good [BK]. Secrecy and survival are the whole of key management."),
 ], None),
 ("KeyPair", "Key pair", 2, "Keys", None, [
  (W, "A key pair is the combination of a private key and a public key that belongs to it. In Bitcoin the key pair is what controls access to bitcoins: the public key is used to receive funds, and the private key is used to sign transactions that spend them [BK]. The two keys are not independent. The public key is calculated from the private key, and the mathematical relationship between them is what allows the private key to produce signatures that anyone can validate against the public key without learning the private key."),
  (Y, "The pair is the smallest unit of ownership that Bitcoin knows. A wallet, in the words of the book, contains a collection of key pairs, each consisting of a private key and a public key [BK]. Every question about who may spend a given output reduces to the question of who holds the private key of the pair that the output was paid to, which is why this second level of the branch deserves careful reading."),
  (H, "The sections below follow the order in which the pieces are needed. Public key cryptography names the family of techniques and says what Bitcoin uses it for. The digital signature is the thing that the private key produces. The private key and the public key are then described one after the other, in the direction in which the calculation runs, from the private key to the public key. A tip in the book adds that some wallets store both keys together as a pair for convenience, whereas storing only the private key is also possible, because the public key can always be recalculated from it [BK]."),
 ], None),
 ("PublicKeyCryptography", "Public key cryptography", 3, "KeyPair", ("signatures, not secrecy", "Public key cryptography lets a private key produce a signature that anyone can check against the public key, which is what Bitcoin uses it for, not for encrypting transactions.", None), [
  (W, "Public key cryptography, also called asymmetric cryptography, is a branch of cryptography in which every participant has two different but mathematically related keys. The book dates its invention to the 1970s and calls it a mathematical foundation for modern computer and information security [BK]. Several suitable mathematical functions have been found since, among them the exponentiation of prime numbers and the multiplication of points on an elliptic curve. What they share is that they are easy to calculate in one direction and infeasible to calculate in the opposite direction with the computers and algorithms available today, and Bitcoin uses elliptic curve addition and multiplication as the basis of its cryptography [BK]."),
  (Y, "The reason Bitcoin needs the technique is easy to misjudge. It is not used to encrypt, that is to make secret, the transactions: everything on the blockchain is public. Its useful property is the ability to generate digital signatures. A private key applied to a transaction produces a numerical signature that only someone who knows the private key can produce, yet anyone who has the public key and the transaction can verify it [BK]. That is precisely what a network of strangers needs, because it makes it possible for everyone to verify every signature on every transaction while only the owners of private keys can create valid ones."),
  (E, "The technique is met wherever people need to prove something to others who do not trust them, and Chapter 3 has already shown one case: the signatures on the release files that a Bitcoin Core user checks before running the software. In Bitcoin itself the technique appears in two places. The spender's signature in a transaction input is checked against a public key, and the public key itself is hidden behind an address until the moment it is spent, as later sections of this chapter explain."),
  (H, "The mechanism has three steps. A private key, which is only a number, is chosen at random. A one-way function, elliptic curve multiplication in Bitcoin, turns it into the public key. When a transaction must be authorised, the private key is used to compute a signature over the transaction, and a verifier combines the signature, the transaction and the public key to decide whether the signature is genuine. The private key itself never leaves the signer's hands and is not revealed by the signature [BK]. Bitcoin has traditionally used the ECDSA signature scheme over the secp256k1 curve with SHA256 hashes, and a newer scheme, Schnorr signatures, is standardised for the same curve [B340]."),
  (K, "Three misunderstandings are common. The first is that signing hides the transaction, which it does not. The second is that the public key could be used to recover the private key, which the one-way property rules out for the computers and algorithms of today [BK]. The third is that the one-way property has been proved: the book says only that the reverse calculation is infeasible with today's computers and algorithms [BK], which is a statement about the present state of knowledge and not a mathematical theorem."),
 ]),
 ("DigitalSignature", "Digital signature", 3, "KeyPair", ("a number only the key holder can produce", "A digital signature is a number computed from a message and a private key that anyone holding the public key can verify, and that cannot be produced without the private key.", None), [
  (W, "A digital signature is a number that a signer computes from a message and from a private key. Anyone who has the message, the signature and the matching public key can verify the signature, that is, can check that it was produced by the holder of the private key and that the message has not been altered since. The book describes this as the central benefit of asymmetric cryptography for Bitcoin: the signature can only be produced by someone with knowledge of the private key, yet it can be verified by anyone with the public key and the transaction [BK]."),
  (Y, "The signature is how Bitcoin answers the question of who may spend. A transaction input does not carry a name or a password; it carries a signature that proves that the spender controls the key to which the earlier output was paid, as Chapter 2 already noted. Because verification needs only public information, every full node can check every signature independently, which is what lets thousands of nodes that do not know each other agree on which spends are valid."),
  (E, "In Bitcoin the signature is used in every spend of an output that is locked to a key. In the earliest form of payment, which later sections describe, the output script asks for a signature that matches a public key, and the check is carried out by a single operation of the script language. Outside Bitcoin, the same mechanism signs documents, software and web certificates."),
  (H, "The scheme that Bitcoin has traditionally used is the Elliptic Curve Digital Signature Algorithm, ECDSA, over the secp256k1 curve with SHA256 hashes, and a signature is encoded in a variable-size format of up to 72 bytes [B340]. The chapter's toolkit contains a teaching sketch of the algorithm: given a private key, a message hash and a nonce, which is a one-time secret number, it produces a pair of numbers, and a verifier that knows only the public key accepts the pair for that message hash. The same pair is rejected for a message hash that differs in a single unit, which is the property that ties a signature to one particular transaction. Bitcoin's newer Schnorr signatures use a fixed 64-byte format and a 32-byte public key [B340]."),
  (K, "A signature scheme is only as good as its handling of the one-time number that goes into every signature. The sketch in the toolkit takes the nonce as an argument so that its output is reproducible; a real signer must derive it deterministically or draw it from a secure random source, and the toolkit says plainly that it is not for use with real funds. ECDSA signatures are also malleable: if a pair of numbers is a valid signature, then the pair with the second number replaced by the group order minus that number is also valid for the same key and message, which Bitcoin handles with a policy rule on the network [B340]. One of the stated motivations of the segregated witness upgrade, described in its own section, is that signature data no longer takes part in the transaction identifier, so that changes to how a transaction was signed no longer change its identity [B141]."),
 ]),
 ("PrivateKey", "Private key", 3, "KeyPair", ("a random number below n", "A private key is a number picked at random between 1 and n minus 1, where n, about 1.1579 times 10 to the 77, is the order of the curve and slightly less than 2 to the 256.", ("2**256 - " + NHEX, "432420386565659656852420866394968145599")), [
  (W, "A private key is simply a number, picked at random. Control over the private key is the root of user control over all funds associated with the corresponding public key: the key is used to create the signatures that spend bitcoins by proving control of the funds used in a transaction [BK]. The book's example private key, written in hexadecimal, is 1E99423A4ED27608A15A2616A2B0E9E52CED330AC530EDCC32C8FFC6A526AEDD, which is 256 bits shown as 64 hexadecimal digits of 4 bits each [BK]."),
  (Y, "Everything else in the system is derived from this one number. The public key, the addresses and the signatures follow from it, while it cannot be recovered from them. That asymmetry makes the private key both the most valuable and the most dangerous secret a Bitcoin user has: whoever learns it can spend the funds, and whoever loses it cannot get them back. The book states both consequences directly, that revealing the key is equivalent to giving control to a third party and that a lost key cannot be recovered [BK]."),
  (E, "The private key is met in wallet software, usually out of sight. Chapter 1 explained that a wallet may derive its keys from a recovery code, and later sections of this chapter show the private key written in other formats, such as the wallet import format used to move a key between wallets. A simple tip in the book makes the nature of the key tangible: tossing a coin 256 times gives the binary digits of a random private key that could be used in a Bitcoin wallet [BK]."),
  (H, "Not every 256-bit number is a valid key. The private key can be any number between 0 and n minus 1, where n is a constant slightly less than 2 to the 256, defined as the order of the elliptic curve that Bitcoin uses [BK]. The constant is FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141 in hexadecimal [SEC2]. Software therefore picks a random 256-bit number and checks that it is less than n, and tries again otherwise. The chance of having to retry is the share of 256-bit numbers that are not below n, about 3.7 times 10 to the minus 39. A key of zero would be useless, because zero times the generator point is the point at infinity and not a public key, so a usable key lies between 1 and n minus 1."),
  (K, "Two details deserve attention. The book prints n as 1.1578 times 10 to the 77, but computing the constant from the standard gives 1.1579 to five significant figures; the difference is a slip in the book's rounding and has no practical consequence. The second detail matters a great deal: any process that is less than completely random can significantly reduce the security of the key and of the bitcoins it controls [BK]. The key space is enormous, about 10 to the 77 numbers, compared with the roughly 10 to the 80 atoms that the book mentions for the visible universe, but that size protects only a key that was chosen without bias."),
 ]),
 ("PublicKey", "Public key", 3, "KeyPair", ("K = k x G", "A public key is the point K = k x G obtained by multiplying the generator point by the private key, which is easy in one direction and infeasible to reverse.", ("'03' if " + YHEX + " % 2 else '02'", "'03'")), [
  (W, "A public key is the number, in fact a point on an elliptic curve, that is calculated from a private key and can be shared with anyone. In the book's notation the private key is k, the public key is K, and the relation is K = k times G, where G is a constant point called the generator point [BK]. For the book's example private key the public key is the point whose two coordinates are x = F028892BAD7ED57D2FB57BF33081D5CFCF6F9ED3D3D7F159C2E2FFF579DC341A and y = 07CF33DA18BD734C600B96A72BBC4749D5141C90EC8AC328AE52DDFE2E505BDB [BK]."),
  (Y, "The public key is what lets the rest of the world check a signature without being able to forge one. Because the generator point is the same for every Bitcoin user, a given private key always produces the same public key, and because the calculation cannot be run backwards, the public key does not reveal the private key [BK]. The book summarises this in a tip: a private key can be converted into a public key, but a public key cannot be converted back into a private key, because the math only works one way."),
  (E, "In the earliest design a public key was placed directly in an output script, and Bob would hand his public key to Alice. The book points out that this is impractical, since the key is long: imagine Bob reading the two 64-digit coordinates to Alice over the phone [BK]. Most of the later sections of this chapter, compressed keys, hashed commitments and addresses, exist to solve exactly that practical problem."),
  (H, "The calculation is an elliptic curve multiplication, described in its own section. Software computes K from k by repeated doubling and adding of points, and many Bitcoin implementations delegate the work to the libsecp256k1 library [BK]. The result is a pair of 256-bit coordinates, which can be written in several encodings. The chapter's toolkit reproduces the book's coordinates from the book's private key, and it confirms that the point satisfies the curve equation. The parity of y, odd for the example key, decides whether the compressed encoding starts with 02 or 03, as the compressed key section explains."),
  (K, "A public key is public only in the sense that it can be shared, not in the sense that it must be published early. Bitcoin addresses hide the public key behind a hash until the key is used to spend, and the book's later sections explain what is gained by that. Do not confuse the public key with the address: they are related, but the address is derived from the public key by further steps and has its own formats."),
 ]),
 ("RandomSource", "Randomness", 2, "Keys", None, [
  (W, "Randomness is the property of a number or a sequence of numbers that nobody can predict or repeat. The first and most important step in generating keys is to find a secure source of it, which computer scientists call entropy [BK]. The word describes both the quality that is needed and, loosely, the material from which random numbers are made."),
  (Y, "A private key protects funds only to the extent that an attacker cannot guess it. A key chosen from a source that is predictable, repeatable or biased may be guessed in far fewer attempts than the size of the key space suggests, even though the key itself looks like an arbitrary 64-digit number. For that reason the source of the number matters more than the number."),
  (H, "The two sections below separate the quantity from the machine. Entropy is the amount of unpredictability that goes into a key, measured in bits. Secure randomness is the kind of generator that turns a seed of real entropy into the 256 bits that a key needs, and the book's rule is blunt: use a cryptographically secure generator and do not write your own [BK]."),
 ], None),
 ("Entropy", "Entropy", 3, "RandomSource", ("a coin tossed 256 times", "Entropy is unpredictability measured in bits; a private key needs 256 bits of it, as many as 256 fair coin tosses supply.", ("round(__import__('math').log10(2**256), 2)", "77.06")), [
  (W, "Entropy, in the sense the book uses the word, is the unpredictability of the material from which a random number is made, and it is counted in bits. Each fair coin toss that nobody can foresee contributes one bit, so the book's tip that 256 tosses give the binary digits of a random private key is a statement about 256 bits of entropy [BK]. The phrase 'cryptographically secure random number generators to produce 256 bits of entropy' describes the practice of Bitcoin software [BK]."),
  (Y, "The count of bits is the count of equally likely possibilities an attacker would have to try. A source with 256 bits of entropy offers 2 to the 256 possibilities, a number with 78 decimal digits and about 10 to the 77 in size, as the book puts it [BK]. If a program claims to produce a 256-bit key but draws it from a source with only 32 bits of entropy, an attacker faces about four billion possibilities and not 10 to the 77, and the key is weak whatever it looks like."),
  (E, "Entropy is met under several names. Chapter 1 explained that a wallet's recovery code is the basis of its keys and gave the initial entropy of the standard recovery words as 128 to 256 bits, and the Python documentation points to the same idea when it says that the secrets module provides access to the most secure source of randomness that the operating system provides [PSF]."),
  (H, "Entropy is not generated by a clever formula. A formula can only stretch entropy that already exists, which is what a pseudorandom number generator does when it expands a short seed into a long stream. Therefore the question for any key generator is where its seed comes from. The book's recipe collects a larger string of random bits from a cryptographically secure source and feeds it to SHA256, which conveniently produces a 256-bit value that can be read as a number; if the number is below n it is a suitable private key, and otherwise the process repeats with fresh randomness [BK]."),
  (K, "High-quality-looking output does not prove high entropy. A number that passes casual inspection can come from a seed as small as the current time, and such a key can be found by an attacker who simply tries all plausible seeds, a search of a few million tries rather than the 10 to the 77 that the size of the key space suggests. Nor can the amount of entropy in a number be measured by looking at the number: two keys that look equally arbitrary may have been drawn from sources that differ by seventy orders of magnitude. Treat entropy as a property of the source and never of the printed result, and ask of any key generator where its seed came from."),
 ]),
 ("SecureRandomness", "Secure randomness", 3, "RandomSource", ("secrets rather than random", "A private key must come from a cryptographically secure random generator; Python's secrets module is documented for that use and its random module for modelling and simulation.", ("0 < __import__('secrets').randbelow(" + NHEX + " - 1) + 1 < " + NHEX, "True")), [
  (W, "Secure randomness is what a cryptographically secure pseudorandom number generator, abbreviated CSPRNG, delivers: numbers that cannot be predicted by an attacker even when the attacker has seen earlier output. The book's warning on the subject is categorical. Do not write your own code to create a random number and do not use a simple random number generator offered by your programming language; use a CSPRNG with a seed from a source of sufficient entropy, and study the documentation of the library you choose to make sure that it is cryptographically secure, because correct implementation of the CSPRNG is critical to the security of the keys [BK]."),
  (Y, "The warning exists because ordinary generators are designed for a different job. The Python documentation says that the default generator of its random module is designed for modelling and simulation, not for security or cryptography [PSF]. Such a generator is a fixed procedure that starts from a seed, so anyone who learns or guesses the seed can reproduce every number that follows. For a private key that is fatal: a key is only as secret as its generator is unpredictable."),
  (E, "Every serious programming environment offers both kinds of generator, and the difference is visible in their documentation. The documentation of Python's secrets module says that the module is used for generating cryptographically strong random numbers suitable for managing data such as passwords, account authentication and security tokens, and that it should be used in preference to the default generator of the random module, which is designed for modelling and simulation, not security or cryptography [PSF]."),
  (H, "A CSPRNG gathers entropy from the operating system, mixes it and expands it into as many unpredictable bits as are asked for. In Python the call secrets.randbelow(m) returns a random integer from 0 up to but not including m, drawn from the most secure source the operating system provides [PSF]. Choosing a key with it takes one line: ask for a number below n minus 1 and add 1, which yields a number from 1 to n minus 1. The default generator of the random module, by contrast, is repeatable on purpose: two generators started from the same seed give the same number, a property that the chapter's checks confirm and that is useful for experiments and disastrous for keys."),
  (K, "Following the rule requires attention to details that are easy to overlook. A generator that is secure in principle can be misused by seeding it with a poor value, by calling it before the system has gathered enough entropy, or by running it on a machine whose random source is compromised. Keys should be generated on a device that you control, and the quality of the software should not be taken on trust. The book names generating code that is compromised with a back door as one of the pitfalls of paper wallets, a subject that a later section returns to [BK]."),
 ]),
]
