"""SEN0401 chapter 6, corpus text part B (version 1.0.0): the branch 'Version, marker and flag' - the first four bytes and what each
version number permits (BIP68 and BIP112 for version 2, the policy proposal for version 3), the presigned transactions that version
numbers protect, and the two bytes that announce the extended format. Markers such as [AH] become author-year strings."""
from sen0401_ch06_common_v1_0_0 import *

NODES_B = [
 ("VersionMarkerFlag", "Version, marker and flag", 1, None, None, P(
  (W, "This branch reads the first six bytes of Alice's transaction: the four-byte version and, because her transaction carries a witness, the marker and the flag that announce the extended format. The book says the first four bytes of a serialized Bitcoin transaction are its version, that the original version was 1, written 01000000, and that all transactions in Bitcoin must follow the rules of version 1 transactions, with many of those rules described throughout the book [AH]."),
  (Y, "Six bytes seem too few for a branch, but they decide which rules apply to everything after them. Version 2 transactions were introduced by the BIP68 soft fork, which places additional constraints on the sequence field that apply only to transactions with version 2 or higher, and BIP112 upgraded an opcode that fails when evaluated in a transaction with a version below 2 [AH]. The marker and the flag decide whether the bytes that follow are read as the legacy layout or as the extended one, so a parser that misreads them misreads the whole transaction [AH] [B144]."),
  (E, "The reader meets the version wherever a transaction is decoded - every explorer and every node reports it - and meets it as a decision in any wallet that uses relative timelocks, which must set version 2. The marker and the flag are met in every segwit transaction's hexadecimal as the 0001 after the version, and in the policy of Bitcoin Core, whose source declares version 2 as the current version a new transaction is built with and 3 as the highest version its relay policy treats as standard [BCX] [BCP]."),
  (H, "The branch has two groups. The version field group follows the numbers: version 1 and its rules, version 2 and the sequence constraints that came with it, the version 3 proposal that changes relay policy rather than consensus, and the presigned transactions whose safety is the reason version numbers are reserved for upgrades. The marker and flag group explains the two bytes of the extended format, why the marker is a zero that a legacy parser would misread as a count of inputs, and why the flag is a separate byte rather than part of the marker [AH] [B144].")), None),

 ("VersionField", "The version field", 2, "VersionMarkerFlag", None, P(
  (W, "The version field is the four-byte little-endian integer at the start of every transaction. This group covers the three values it has taken or may take and the problem that explains why new values are introduced carefully: version 1, the original; version 2, which the BIP68 soft fork introduced to carry the new meaning of the sequence field; the version 3 proposal that the book says was being widely considered as it was written; and presigned transactions, which can be invalidated by a rule that applies to a version they already use [AH]."),
  (Y, "The group matters because a version number is a promise. Bitcoin's consensus rules can only be tightened by soft fork, and a tightening that applied to every existing transaction could invalidate transactions that were signed long ago and cannot be signed again. Reserving a new version number for the new constraint keeps the old transactions valid under the old number; the book's sidebar on protecting presigned transactions states the problem and this solution, and the sequence branch shows the constraint that BIP68 actually added [AH] [B68]."),
  (H, "The four sections are in historical order. Version 1 is the baseline every transaction must satisfy; version 2 adds BIP68's reading of the sequence field and BIP112's opcode; version 3 is a relay-policy regime under which a transaction accepts topological limits in exchange for protection from a kind of attack the book defers to a later chapter; and the presigned transaction section explains why anyone building a protocol on Bitcoin must avoid features reserved for upgrades and can test a transaction with Bitcoin Core's testmempoolaccept command [AH].")), None),

 ("VersionOne", "Version 1", 3, "VersionField", ("01000000 in the first four bytes", "Version 1 is the original transaction version, written 01000000 in little-endian order; every transaction must follow its rules, and Alice's transaction uses it.", ("int.from_bytes(bytes.fromhex('01000000'), 'little')", "1")), P(
  (W, "Version 1 is the original version of Bitcoin transactions. The book says the first four bytes of a serialized transaction are its version, that the original version was 1, written 0x01000000, and that all transactions in Bitcoin must follow the rules of version 1 transactions, with many of those rules described throughout the book [AH]. Alice's transaction begins with exactly these four bytes, and the worked example reads them as the little-endian integer 1."),
  (Y, "Version 1 matters as the floor. Later versions do not replace its rules but add to them: a version 2 transaction obeys everything a version 1 transaction obeys and in addition the sequence constraints of BIP68, and the book says that beyond those changes version 2 transactions are identical to version 1 transactions [AH]. Most of what this chapter describes - inputs, outpoints, outputs, amounts, scripts, lock time - are version 1 rules, so a reader who understands version 1 understands the format, and the later versions are a short list of differences."),
  (H, "The number is stored least significant byte first, which is why 1 appears as 01 followed by three zero bytes. Bitcoin Core reads it as a signed 32-bit integer; its CheckTransaction function, the context-free check of a transaction, does not look at the version at all, and the version only matters where a rule names it, in the sequence-lock calculation for version 2 and in the relay policy for version 3 [BCT] [BCV] [BCP]. Alice's transaction is version 1 even though it spends a segwit output and carries a witness, because segwit changed the serialization and not the version [AH]."),
  (K, "The caution is that version 1 is not the version a modern node creates by default. Bitcoin Core's transaction class names 2 as its current version, so a transaction built by a current wallet is usually version 2 even when it uses no relative timelock, and the previous transaction in Alice's chain, the one that paid her, is version 2 as the explorer records it [BCX] [MP]. Version 1 is therefore what old software and some deliberately conservative wallets produce, not what the reader should expect to see most often.")), None),

 ("VersionTwo", "Version 2 and BIP68", 3, "VersionField", ("the version that turns sequence into a timelock", "Version 2 transactions were introduced by the BIP68 soft fork; only in a transaction of version 2 or higher is a sequence value below 2 to the 31 a relative timelock, and BIP112's opcode fails below version 2.", ("(lambda version, seq: 'relative timelock' if version >= 2 and seq < 2 ** 31 else 'no timelock')(2, 30)", "'relative timelock'")), P(
  (W, "Version 2 is the transaction version introduced by the BIP68 soft fork change to Bitcoin's consensus rules. The book says BIP68 places additional constraints on the sequence field that apply only to transactions with version 2 or higher, that version 1 transactions are unaffected, and that BIP112, part of the same soft fork, upgraded the opcode OP_CHECKSEQUENCEVERIFY, which now fails if evaluated as part of a transaction with a version less than 2; beyond those two changes, version 2 transactions are identical to version 1 transactions [AH]."),
  (Y, "The version gate is what makes the soft fork safe. Before BIP68, the sequence field of a version 1 transaction could hold any value with no consensus meaning, so a transaction signed years earlier with a low sequence number remained valid. Applying the new reading only from version 2 means that no presigned version 1 transaction was invalidated, which is the book's own example of protecting presigned transactions [AH] [B68]. BIP68 states the rule in its own words: the specification defines the meaning of sequence numbers for transactions with a version greater than or equal to 2 [B68]."),
  (H, "A node implements the gate in one comparison. Bitcoin Core's CalculateSequenceLocks computes a relative lock only when the transaction's version is at least 2 and the input's disable flag is clear; otherwise the sequence is ignored for timelock purposes [BCV]. The worked example states the same decision as a small function: version 2 with a sequence of 30 means a relative timelock, and the sequence branch explains what a lock of 30 blocks means. The activation height of these rules on the main network, 419,328, is recorded in Bitcoin Core's chain parameters as CSVHeight, the height at which BIP68, BIP112 and BIP113 took effect together [BCK] [BCD]."),
  (K, "The caution is that the gate is on the transaction, not on the input. All inputs of a version 2 transaction are read under BIP68, so a wallet cannot opt one input into a relative timelock and leave another with an unrestricted low sequence; it must set the disable flag on the inputs it wants excluded, which is a distinct bit the sequence branch describes [AH] [B68]. A second caution is that version 2 does not by itself impose any timelock: with every sequence at its final value the transaction behaves exactly like a version 1 one.")), None),

 ("VersionThree", "The version 3 proposal", 3, "VersionField", ("a policy, not a consensus change", "The version 3 proposal, BIP431, changes only the relay policy of full nodes: a version 3 transaction accepts topological restrictions in exchange for protection against pinning attacks; Bitcoin Core treats it as standard since release 28.0.", ("(lambda current, max_standard: (current, max_standard, max_standard - current))(2, 3)", "(2, 3, 1)")), P(
  (W, "The version 3 proposal is the one the book says was being widely considered as it was written: a proposal to begin using version 3 transactions that does not seek to change the consensus rules but only the policy that Bitcoin full nodes use to relay transactions. Under it, version 3 transactions would be subject to additional constraints in order to prevent certain denial of service attacks that the book discusses under transaction pinning in a later chapter [AH]. The proposal became BIP431, whose title is topology restrictions for pinning [B431]."),
  (Y, "The proposal matters as an example of the difference between policy and consensus, a distinction the whole chapter leans on. A consensus rule decides which blocks are valid and binds every node; a policy decides which unconfirmed transactions a node will relay and store, and a node may choose it. Version 3 adds no validity rule - a version 3 transaction in a block is valid under exactly the rules of version 2 - but a node that follows BIP431 refuses to relay a version 3 transaction with more than a small number of unconfirmed relatives, which is what denies an attacker the ability to pin a payment-channel transaction in the memory pool with a large low-fee descendant [B431]."),
  (H, "BIP431 says a sender signals that a transaction is to be topologically restricted until confirmation by setting its version to 3, and a node applying the policy requires, among other rules, that a version 3 transaction signals replaceability even without the BIP125 signal and that all of its unconfirmed ancestors and descendants are also version 3 [B431]. Bitcoin Core's documentation records that transactions with version 3 are standard and treated this way as of release 28.0, and its policy source sets the highest standard version to 3 while its transaction class still builds version 2 by default, which is the pair the worked example states [BCD] [BCP] [BCX]."),
  (K, "The caution is that the book's tense is already out of date in one respect and not in another. The proposal was under consideration when the book was written and has since been implemented as policy in Bitcoin Core, so the reader will meet version 3 transactions on the network; but the consensus rules are exactly as the book says, unchanged. A reader should also not expect version 3 from an ordinary wallet, since the restrictions are designed for contract protocols such as payment channels rather than for simple payments [B431].")), None),

 ("PresignedTransaction", "Presigned transactions", 3, "VersionField", ("signed now, broadcast years later", "A presigned transaction is signed but not broadcast, perhaps for years; a later rule that applies to its version could make it permanently invalid, so new constraints are reserved for new version numbers.", ("(lambda presigned_version, rule_applies_from: 'still valid' if presigned_version < rule_applies_from else 'at risk')(1, 2)", "'still valid'")), P(
  (W, "A presigned transaction is a transaction that has been signed but not broadcast. The book's sidebar explains that the last step before broadcasting a transaction for inclusion in the blockchain is to sign it, but that it is possible to sign a transaction without broadcasting it immediately and to save it for months or years in the belief that it can be added to the blockchain later; in the interim the holder may even lose access to the private keys needed to sign an alternative. This is not hypothetical: several protocols built on Bitcoin, including the Lightning Network, depend on presigned transactions [AH]."),
  (Y, "Presigned transactions are why consensus upgrades must be careful. Adding a new constraint, as BIP68 did to the sequence field, may invalidate some presigned transactions, and if there is no way to create a new signature for an equivalent transaction, the money being spent in the presigned transaction is permanently lost [AH]. The solution is to reserve some transaction features for upgrades, such as version numbers: anyone creating presigned transactions before BIP68 should have used version 1, so applying BIP68's constraints only to version 2 or higher invalidates none of them [AH]."),
  (H, "The protection works as a contract between protocol developers and consensus developers. A protocol that uses presigned transactions must not use any feature reserved for future upgrades - unusual version numbers, unused sequence bits, unknown witness versions - and the consensus developers in turn only attach new rules to those reserved features. The book notes that Bitcoin Core's default transaction relay policy does not allow the use of reserved features, and that a developer can test whether a transaction complies with that policy by using Bitcoin Core's testmempoolaccept RPC on the main network [AH]. The worked example states the rule as a comparison: a version 1 transaction is untouched by a rule that applies from version 2."),
  (K, "The caution is that relay policy is a weaker guarantee than consensus. A transaction that passes testmempoolaccept today uses no reserved feature today, but policy is a moving target, and what is non-standard now could become a consensus rule later only if it was reserved, which is the reason to test. The second caution is practical: a presigned transaction depends on the previous output it spends staying unspent, so the protocol must also prevent the counterparty from spending that output another way, which is the malleability problem of the witness branch [AH].")), None),

 ("MarkerAndFlag", "The marker and the flag", 2, "VersionMarkerFlag", None, P(
  (W, "The marker and the flag are the two bytes that follow the version in the extended serialization format. The book says that if the transaction includes a witness structure, the marker must be zero and the flag must be nonzero; that in the current peer-to-peer protocol the flag should always be one, with alternative flags reserved for later protocol upgrades; and that if the transaction does not need a witness stack, the marker and flag must not be present [AH]."),
  (Y, "Two bytes carry the whole backward compatibility of segwit's serialization. A legacy parser reads the byte after the version as the count of inputs; a count of zero is impossible, so the zero marker makes an extended transaction unparseable as a legacy one rather than wrongly parseable, and a new parser reads the zero as a signal. The book says the marker signals to modern programs that extended serialization is being used and that the flag provides a similar signal and also simplifies the process of updating the serialization format in the future [AH] [B144]."),
  (H, "The two sections take one byte each. The marker byte section explains the choice of zero and its collision with the input count; the flag byte section explains why a second byte follows the marker, with BIP144's own rationale that a single zero byte would have made an empty test transaction look like new serialized data, and that the flag can be interpreted as a bit vector for adding more non-committed data later [B144].")), None),

 ("MarkerByte", "Marker byte", 3, "MarkerAndFlag", ("a zero where a count cannot be zero", "The marker is the byte 0x00 after the version of an extended-format transaction; a legacy parser would read it as a count of zero inputs, which no transaction can have, so it signals the extended format.", ("(lambda b: 'extended format' if b[4] == 0 and b[5] != 0 else 'legacy format')(bytes.fromhex('01000000000101eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a0100000000ffffffff02204e0000000000002251203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068f8240100000000001600147752c165ea7be772b2c0acb7f4d6047ae6f4768e0141cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e817130100000000'))", "'extended format'")), P(
  (W, "The marker is the single byte, always 0x00, that follows the version in a transaction serialized in the extended format. The book explains the choice: in legacy serialization, the marker byte would have been interpreted as the number of inputs, zero; a transaction cannot have zero inputs, so the marker signals to modern programs that extended serialization is being used [AH]. BIP144 names the field marker and fixes its value at zero [B144]."),
  (Y, "The marker matters because it lets one byte stream serve two generations of software without ambiguity. A format change that could be confused with the old format would be dangerous: an old node might accept a mis-parsed transaction, or two nodes might disagree about what a transaction says. Choosing a value that is impossible in the old format removes the ambiguity entirely, and BIP144 states the goal directly: the marker is set to zero so that the structure will never parse as a valid transaction in a parser that does not support the proposal [B144]."),
  (H, "A parser reads the marker with a lookahead. After the four version bytes it inspects the next byte; if that byte is zero and the byte after it is nonzero, the transaction is in the extended format and the parser consumes both bytes before reading the real input count; otherwise the byte is the input count itself and the legacy layout follows. The worked example applies exactly this test to Alice's transaction, whose fifth byte is 00 and sixth 01, and reports the extended format. The chapter's library does the same and records the marker and the flag as fields of one byte each in the byte map [AH]."),
  (K, "The caution is that the marker is not part of what the transaction identifier commits to. The identifier is computed over the legacy serialization, which has no marker, so two serializations of the same transaction, one with and one without the witness, share a txid while differing in these bytes; the witness branch returns to this. A reader should also note that the rule is strict in both directions: a transaction with a witness must carry the marker and one without a witness must not [AH].")), None),

 ("FlagByte", "Flag byte", 3, "MarkerAndFlag", ("one, with other values reserved", "The flag is the byte after the marker; it is 0x01 in the current protocol, other values are reserved for upgrades, and BIP144 reads it as a bit vector for adding non-committed data later.", ("(lambda flag: [bit for bit in range(8) if flag >> bit & 1])(0x01)", "[0]")), P(
  (W, "The flag is the byte that follows the marker in the extended format. The book says the flag must be nonzero, that in the current peer-to-peer protocol it should always be one, and that alternative flags are reserved for later protocol upgrades [AH]. BIP144 lists it after the marker in its table of the format and gives its value as 0x01 [B144]."),
  (Y, "The flag matters as the room left for the future. BIP144 gives two reasons for having it at all: a single zero byte as marker would lead empty transactions, with no inputs and no outputs and used in some tests, to be interpreted as new serialized data, and the flag byte in between will allow more extra non-committed data to be added to transactions later, such as the outputs being spent, because it can be interpreted as a bit vector [B144]. The book summarises the same point: the flag simplifies the process of updating the serialization format in the future [AH]."),
  (H, "Read as a bit vector, the flag's lowest bit says that a witness structure follows, and the other seven bits are unassigned; the worked example lists the set bits of 0x01 and finds only bit 0. A future extension could set a second bit to announce a further block of data after the witness, and a parser that recognises only bit 0 would know, from the unknown bit, that it cannot parse the rest, rather than silently misreading it. Non-committed data means data that is not part of what the transaction identifier commits to, which is exactly what a witness is [B144] [B141]."),
  (K, "The caution is that reserved does not mean usable. A transaction with a flag other than 1 is not relayed under current rules, so an application cannot set a bit for its own purposes; this is one of the reserved features the presigned-transaction section says a protocol must avoid [AH]. A second caution: the flag's value is checked only in the extended format, and the whole two-byte pair is absent from the legacy format, so there is no flag of zero anywhere.")), None),
]

CHECKS_B = [
 Qb("ch06_transactions.adoc", "The original version of Bitcoin transactions was version 1", "(0x01000000)"),
 Qb("ch06_transactions.adoc", "Version 2 Bitcoin transactions were introduced in the BIP68 soft fork", "which will now fail if it is", "evaluated as part of a transaction with a version less than 2"),
 Qb("ch06_transactions.adoc", "a proposal to begin using version 3 transactions is", "being widely considered", "only the policy that Bitcoin full nodes use to relay", "transactions"),
 Qb("ch06_transactions.adoc", "several protocols built on Bitcoin, including Lightning", "Network, depend on presigned", "testmempoolaccept"),
 Qb("ch06_transactions.adoc", "the flag should always be one", "(0x01); alternative flags are reserved for later protocol upgrades"),
 Qb("ch06_transactions.adoc", "the marker byte would have been interpreted as", "the number of inputs (zero)"),
 Qe("bip-0068.mediawiki", "This specification defines the meaning of sequence numbers for transactions with an nVersion greater than or equal to 2"),
 Qe("bip-0431.mediawiki", "Topology Restrictions for Pinning", "set <code>nVersion=3</code>", "A TRUC transaction signals replaceability, even if it does not signal BIP125 replaceability."),
 Qe("bip-0144.mediawiki", "Rationale for not using just a single 0x00 byte as marker", "It can be interpreted as a bitvector."),
 Qe("core_doc_bips.md", "transactions with nVersion=3 are standard and treated as Topologically Restricted Until Confirmation as of **v28.0**"),
 Qe("core_doc_bips.md", "Sequence locks have been implemented as of **v0.12.1**"),
 Qc("src/primitives/transaction.h", "static constexpr uint32_t CURRENT_VERSION{2};"),
 Qc("src/policy/policy.h", "TX_MAX_STANDARD_VERSION{3}"),
 Qc("src/kernel/chainparams.cpp", "consensus.CSVHeight = 419328;"),
 Qc("src/consensus/tx_verify.cpp", "if (txin.nSequence & CTxIn::SEQUENCE_LOCKTIME_DISABLE_FLAG) {"),
 X("T.parse_tx(%r)['version']" % ALICE, 1),
 X("T.parse_tx(C.ev_hex('tx_alice_prev_4ac54180_v1_0_0.hex'))['version']", 2),
 X("C.ev_json('mempool_tx_4ac5418026798669_v1_0_0.json')['version']", 2),
 X("T.sequence_decode(30, version=1)['relative_timelock'] is None and T.sequence_decode(30, version=2)['relative_timelock'] == ('blocks', 30)", True),
 ("int.from_bytes(bytes.fromhex('01000000'), 'little')", "1"),
 ("(0x01000000).to_bytes(4, 'big').hex() == (1).to_bytes(4, 'little').hex()", "True"),
]
