"""SEN0401 chapter 7, corpus text part C (version 1.0.0): the branch 'Scripted multisignatures' - the t-of-k script, its limits,
the extra stack element that OP_CHECKMULTISIG consumes and the number of signature checks it makes. Markers such as [AH] become
author-year strings (sen0401_ch07_common). Every number is computed by the chapter's library in CHECKS_C."""
from sen0401_ch07_common_v1_0_0 import *

BK = "ch07_authorization-authentication.adoc"
Z2OF3 = "3b21c61230fc5b234fef6a894f008ad633c55138a46f415b10d39622858e4560"                       # SHA-256 of b'two of three'
KA = "03774ae7f858a9411e5ef4246b70c65aac5649980be5c17891bbec17895da008cb"                         # demonstration keys 11, 12, 13
KB = "03d01115d548e7561b15c38f004d734633687cf4419620095bc5b0f47070afe85a"
KC = "03f28773c2d975288bc7d1d205c3748651b075fbc6610e58cddeeddf8f19405aa8"
SB = (0x7e7e66cd29902c4ba2bb06d0c2b8d3dda0e6d0f0329c386225ae3a333ef4796e, 0x06e33926f2dc02a6ad04f28769865fd9fe25caa5c446c247d22517bf1cbd54c2)
SC = (0x1f4a142c40ea17b00bbf9abae877025e1e4b4d5151b74dbb74466f7236c7b8a4, 0x2204972b18bc9eb7a25b3e00f5025bbfe620cb1bb67d3a83633f422ee8600fa1)
MSIG = '''
def checkmultisig(sigs, keys, z):
    sigs, keys = list(sigs), list(keys)      # the engine starts from the top of the stack: the last key and the last signature
    while sigs:
        if verify(keys[-1], z, *sigs[-1]): sigs.pop()
        keys.pop()
        if len(sigs) > len(keys): return False
    return True
z = int('%s', 16)
A, B, C = (bytes.fromhex(k) for k in ('%s', '%s', '%s'))
sB, sC = (%s, %s), (%s, %s)
''' % (Z2OF3, KA, KB, KC, hex(SB[0]), hex(SB[1]), hex(SC[0]), hex(SC[1]))

NODES_C = [
 ("ScriptedMultisig", "Scripted multisignatures", 1, None, None, P(
  (W, "This branch is about the first way Bitcoin lets several people share control of one output. A multisignature script lists k public keys and states how many of them, t, must sign before the output can be spent; the book calls this a t-of-k multisignature and gives a 2-of-3 as its example, three listed keys of which at least two must be used to sign [AH]. The branch has two groups: the form of the script with its limits, and an oddity in the way the opcode that checks the signatures reads the stack."),
  (Y, "Shared control is the reason the pattern exists and the reason it is the model for several later chapters of the story. A business can require two of three officers to approve a payment, a person can keep one key at home and one in a safe and a third with a trusted service, and two parties who do not trust each other can ask a third to judge a dispute; the author of the proposal that standardized the pattern, BIP11, gave exactly this last case, a three-party escrow with a buyer, a seller and an agent, as its example [B11]."),
  (E, "A reader meets multisignatures in wallets that take several signers and in services that keep coins for others. The block of 775,072 used for this chapter's census holds 67 inputs of this kind among its 1,022 inputs: 10 spend a legacy script hash output and 57 spend a witness script hash output, all of them hidden behind the hash forms of the next branches [MP]. Almost nobody locks coins directly with a bare multisignature script any more, but the script inside the hash is the same."),
  (H, "The branch follows a single script from its general form to the details of the machine that runs it. The form is t, then the k public keys, then k, then the opcode OP_CHECKMULTISIG; the input script supplies the signatures; the limits say how large k may be under policy and under consensus; and the oddity and the signature count describe what the engine does when it runs. Every example in the branch is run by the chapter's library, which accepts the same scripts that Bitcoin Core's own script tests accept [BCJ]."),
 ), None),

 ("MultisigForm", "The t-of-k script and its limits", 2, "ScriptedMultisig", None, P(
  (W, "This group states what a multisignature output script looks like and how large it may be. The script is written t, the keys, k, OP_CHECKMULTISIG, where t is the threshold of signatures that must be valid and k is the number of keys listed; the input script that satisfies it holds the signatures, in the same order as the keys they belong to [AH]."),
  (Y, "The two sections matter together because a script that is valid in form can still be too large or not standard. A person who builds a 16-key script discovers that it cannot be put in a script hash output, and a person who builds a bare 4-key script discovers that nodes will not relay it; the limits are what turn the general idea into what a wallet may really create."),
  (H, "The first section gives the form and runs a 2-of-3 example with real signatures; the second collects the limits, which are three different numbers for three different places: three keys for a bare script under relay policy, fifteen for a script hash by the size of a script element, and twenty by consensus for every other script. Each number is read from the book and from the source code of Bitcoin Core and then recomputed."),
  (K, "Policy and consensus differ throughout the group. A rule of the relay policy decides which transactions a node passes on, and a miner may still include a transaction that breaks it; a consensus rule decides whether a block is valid at all. The group says each time which of the two a limit is."),
 ), None),

 ("ScriptedMultisignature", "Scripted multisignature", 3, "MultisigForm", ("2 <sig B> <sig C> ... OP_CHECKMULTISIG", "A scripted multisignature output lists k public keys and requires at least t valid signatures from them, given in the same order as the keys, before it can be spent.",
   (PROG(SECP + MSIG + "result = (checkmultisig([sB, sC], [A, B, C], z), checkmultisig([sC, sB], [A, B, C], z))"), "(True, False)")), P(
  (W, "A scripted multisignature is an output script that sets a condition where k public keys are recorded in the script and at least t of them must provide signatures to spend the funds. The book calls this t-of-k and notes that earlier editions, and much other documentation, write m-of-n, which is hard to say aloud because m and n sound alike [AH]. The general output script is t, then the k keys, then k, then OP_CHECKMULTISIG, and a 2-of-3 looks like 2 followed by three public keys, then 3 and the opcode; the input script is two signatures, or any other combination of two signatures from the three keys."),
  (Y, "The pattern turns one key into a group decision. The signatures are independent proofs that two different holders agreed to one transaction, so no single holder can spend alone and the loss of a single key does not lose the funds. BIP11 made the form a standard transaction in 2011 and described the use that motivated it, a three-party escrow in which the buyer sends coins into a 2-of-3 output, the seller fulfils the deal and the agent decides only if the other two disagree [B11]."),
  (E, "On the real chain the bare form is rare; in block 775,072 not one of the 1,022 inputs spends a bare multisignature output, while 10 inputs reveal a 2-of-3 script inside a script hash and 41 reveal one inside a witness script hash, as do 5 2-of-2 scripts and a few others [MP]. Bitcoin Core's script solver still treats the bare form as one of its standard templates and reads t and k from it [BCV]. The example in this section builds the 2-of-3 with the chapter's library, signs with the second and third keys and runs the engine."),
  (H, "The engine reads the combined script from left to right: it pushes the signatures, the number 2, the three keys and the number 3, and then OP_CHECKMULTISIG pops k, the keys, t and the signatures and tests them. It takes the key and the signature that are on top of the stack, tries them together, and moves to the next key whatever happens; a signature that fits is used up, and the opcode succeeds when all t signatures have been used [BCI]. Because the signatures are used up in order, they must appear in the input script in the same order as their keys appear in the output script. The example in the page checks signatures by the second and third key against the list in order and then in the reverse order, and the second attempt fails."),
  (K, "The order of the signatures is the trap. Two valid signatures given in the wrong order fail with the engine's EVAL_FALSE error even though each is valid on its own, because the engine never goes back to an earlier key. The input script of a real multisignature spend also needs the extra first element described in the next section; without it the script fails, and the signatures alone are not an input script."),
 ), None),

 ("MultisigLimits", "Multisignature limits", 3, "MultisigForm", ("15 keys fit a script hash, 20 keys fit a witness script", "The number of keys a multisignature may list is limited in three different ways: three for a bare script by relay policy, fifteen for a script hash because of the 520-byte limit on a script element, and twenty for every script by consensus.",
   (PROG("def size(k): return 3 + 34 * k          # OP_t, k pushes of 33 bytes plus the length byte, OP_k, OP_CHECKMULTISIG\nresult = (size(15), size(16), size(15) <= 520, size(16) <= 520)"), "(513, 547, True, False)")), P(
  (W, "The limits on the number of keys come from three different places. The book says that Bitcoin Core's relay policy limits multisignature output scripts to at most three listed keys, from 1-of-1 to 3-of-3; that this applies only to bare multisignature scripts and not to scripts wrapped in a P2SH, P2WSH or P2TR structure; that a P2SH multisignature is limited by both policy and consensus to 15 keys; and that all other scripts are limited by consensus to 20 keys per OP_CHECKMULTISIG or OP_CHECKMULTISIGVERIFY, although one script may contain several such opcodes [AH]."),
  (Y, "The limits explain choices that look arbitrary. A 15-of-15 is the biggest standard script hash multisignature, and the reason is a size, not a design choice: the script is redeemed by pushing it as one element, and a script element may be at most 520 bytes [BCS]. Fifteen compressed keys with their length bytes and the three other bytes make 513 bytes; sixteen make 547 and no longer fit. A comment in Bitcoin Core's policy code does the same arithmetic and rounds the largest signature script of a standard input to 1,650 bytes [BCP]."),
  (E, "The three-key rule is in Bitcoin Core's function IsStandard, which refuses a bare multisignature output whose n is less than one or more than three, and the twenty-key rule is the constant MAX_PUBKEYS_PER_MULTISIG in the script header; the 3,600-byte limit of a standard witness script is in the policy header [BCP] [BCS] [BCQ]. In tapscript, the script language of taproot, OP_CHECKMULTISIG does not exist at all: the engine fails a script that uses it, and the threshold is built with a counting opcode instead, the subject of a later branch [BCI]."),
  (H, "The example computes the size of a multisignature script from its parts: one byte for the threshold, 34 bytes per compressed key (a length byte and 33 bytes of key), one byte for k and one for the opcode, which is 34 times k plus 3. For 15 keys this is 513 bytes and for 16 it is 547, so the second is more than the 520-byte limit. The library confirms the sums with real scripts and also builds a 15-of-15 script hash and spends it, so that the largest standard case is not only computed but run."),
  (K, "The word limit hides three different rules. Policy numbers can change from release to release, and the book itself says to check IsStandard to see what is accepted; the 520-byte element size and the 20-key count are consensus rules that cannot be changed without a soft fork. A multisignature that is large because it uses 20 keys has to be placed in a witness script hash, where the element limit of 520 bytes does not apply to the witness script."),
 ), None),

 ("MultisigOddity", "The multisig extra-element bug", 2, "ScriptedMultisig", None, P(
  (W, "This group covers two consequences of the way OP_CHECKMULTISIG is implemented. The first is an extra stack item that the opcode pops and ignores, which every multisignature input script must therefore provide; the second is the number of signature checks the opcode makes, which can be much larger than the number of signatures [AH]."),
  (Y, "Both matter to people who build scripts and wallets. The extra item is the reason every multisignature input starts with an empty push, and a script that leaves it out fails; the signature count matters because a node's work and a block's allowance are measured in signature checks. A wallet developer who knew neither would build transactions that nodes reject or that cost more than needed."),
  (H, "The first section describes the extra element and how it became a consensus rule, BIP147; the second counts the checks with the real engine for a 1-of-5 spend and shows the book's explanation of why the extra element might have been put there. The book does not decide whether it was a bug or a plan, and neither does this group."),
  (K, "A rule that exists to repair an old oddity cannot be removed afterwards: the book says that the extra element must now be replicated forever. New designs avoid the issue altogether, which is the reason the taproot script language replaced the opcode with a different one."),
 ), None),

 ("CheckmultisigDummy", "The CHECKMULTISIG dummy element", 3, "MultisigOddity", ("OP_0 <sig B> <sig C> 2 <A> <B> <C> 3 OP_CHECKMULTISIG", "The dummy element is the extra stack item that OP_CHECKMULTISIG pops after its signatures; its content is ignored by the opcode itself, but since BIP147 it must be an empty byte array.",
   (PROG("stack = ['', 'sigB', 'sigC', '2', 'pkA', 'pkB', 'pkC', '3']       # the combined script of the book, after all its pushes\nk = int(stack.pop())\nkeys = [stack.pop() for _ in range(k)]\nt = int(stack.pop())\nsigs = [stack.pop() for _ in range(t)]\nresult = (t + k + 2, 8 - len(stack))        # the items the opcode should take, the items it took before the dummy"), "(7, 7)")), P(
  (W, "The dummy stack element is the extra item that OP_CHECKMULTISIG removes from the stack. The book explains that the opcode should consume t plus k plus 2 items, namely k, the k keys, t and the t signatures, but because of an oddity in the implementation it pops one more, which it ignores when it checks the signatures and which therefore can be anything. It must exist, because an empty stack at that point causes a stack error and the script fails [AH]."),
  (Y, "The element matters because it is the first thing every multisignature input script contains and because it was once a malleability problem. The book says it became custom to use OP_0, which later became a relay policy rule and eventually a consensus rule through BIP147. The BIP explains the danger: a relay node could change the ignored value without invalidating the script, and for a transaction without witness data this changes the transaction identifier and invalidates children that spend the unconfirmed output [B147]."),
  (E, "The rule is in the engine itself. Bitcoin Core's comment in the opcode says that a bug causes OP_CHECKMULTISIG to consume one extra argument whose contents were not checked in any way, and that the flag NULLDUMMY verifies it to be of zero length before it is removed; the same flag is in the standard flags of the relay policy [BCI] [BCH] [BCQ]. In block 775,072 every one of the 91 inputs whose witness script is a multisignature, 57 direct and 34 inside a nested script hash, begins with an empty element [MP]. BIP11 already mentioned the bug in 2011, and BIP147 was deployed together with segregated witness, which activated at block 481,824 [B11] [B147] [BCL]."),
  (H, "The engine pops k first, then the k keys, then t, and then the t signatures; the extra element is the next item on the stack. The example in the page pops the items of the book's script in that order and shows that the opcode has taken 7 items and not yet reached the dummy at the bottom of the stack, so that there is exactly one item left for it to pop. The library runs the real thing: a 2-of-3 spend with an empty first element succeeds, one whose first element is the byte 1 fails with the engine's error SIG_NULLDUMMY, and the same spend without the NULLDUMMY flag succeeds, which is how it was before the rule."),
  (K, "The book's formulation that the dummy is something to put in front of the signatures is true but not the whole truth: it is an empty byte array that is pushed by OP_0, and since BIP147 any other value makes the script fail at once. In a segregated witness input, the dummy is the first item of the witness stack and the rule applies there too."),
 ), None),

 ("SignatureCheckCount", "Signature check count", 3, "MultisigOddity", ("a 1-of-5 spend by the first key costs five checks", "The opcode compares signatures with keys one by one, and a signature that matches a key that is far from the top of the stack is found only after many failed attempts, so that the number of checks can be as large as the number of keys.",
   (PROG("keys = ['k0', 'k1', 'k2', 'k3', 'k4']\ndef checks(signer):                           # the engine tries the key on top of the stack first, then the next one\n    n = 0\n    for key in reversed(keys):\n        n += 1\n        if key == signer: return n\nresult = (checks('k4'), checks('k0'))"), "(1, 5)")), P(
  (W, "The signature check count is the number of signature verifications an OP_CHECKMULTISIG performs. The book explains that verifying t-of-k signatures can require many more than t or k checks, and gives a 1-of-5 as its example: one signature is compared with the keys one after another until it meets its own, so five checks are done for one signature. The opcode does not know which signature belongs to which key and has to try [AH]."),
  (Y, "The count is a cost, and it is limited because signature checks are the expensive part of validating a transaction. Bitcoin Core counts them in the function GetSigOpCount, in which an OP_CHECKMULTISIG counts as the number of keys when it directly follows a small number and as 20, the maximum, when the count is not known, and the consensus limit of a block is a sigop cost of 80,000 [BCC] [BCK]. BIP11 recalled the older limit of 20,000 signature operations a block and the consequence that old software counted each multisignature as 20, so that at most 1,000 multisignature transactions fitted in one [B11]."),
  (E, "The book offers a theory about the origin of the oddity in the previous section: the original developer might have added the extra element so that a later soft fork could pass a map telling the opcode which signature belongs to which key, which would reduce the work to exactly t checks. That feature was never implemented, and the book says that BIP147 makes it impossible to add in the future [AH]. The same count is the reason why tapscript replaced the opcode, in a later branch."),
  (H, "The example uses a model: keys are labels, and the opcode takes the key on top of the stack first, the last key listed, then the next one below. The signature of the last key, k4, is found at the first try, and that of the first key, k0, only at the fifth. The library runs the real engine with a counter around the ECDSA verification: a 1-of-5 spend signed by the last key makes 1 check, one signed by the first key makes 5, and a 3-of-3 makes 3."),
  (K, "The book describes the search as starting with the first key listed; in Bitcoin Core's code the engine starts with the key at the top of the stack, which is the last one listed, and the number of checks in the worst case is the same. A signature that does not match any remaining key makes the whole operation fail early, as soon as more signatures are left than keys, so a wrong signature is not paid for with all the checks."),
 ), None),
]

CHECKS_C = [
 Qb(BK, "Multisignature scripts", "set a condition where _k_ public keys", "are recorded in the script and at least _t_ of those must provide", "signatures to spend the funds, called _t_-of-_k_.", "a 2-of-3 multisignature is one", "where three public keys are listed as potential signers and at least two", "of those must be used to create signatures for a valid transaction to", "spend the funds."),
 Qb(BK, "uses the term \"m-of-n\" for a traditional multisignature.", "it's hard", "to tell \"m\" and \"n\" apart when they're spoken, so we use the alternative", "_t_-of-_k_."),
 Qb(BK, "t <Public Key 1> <Public Key 2> ... <Public Key k> k OP_CHECKMULTISIG", "2 <Public Key A> <Public Key B> <Public Key C> 3 OP_CHECKMULTISIG", "<Signature B> <Signature C>", "or any combination of two signatures from the private keys corresponding", "to the three listed public keys.", "<Sig B> <Sig C> 2 <Pubkey A> <Pubkey B> <Pubkey C> 3 OP_CHECKMULTISIG"),
 Qb(BK, "Bitcoin Core's transaction relay policy limits multisignature output scripts to, at most, three", "listed public keys, meaning you can do anything from a 1-of-1 to a", "3-of-3 multisignature or any combination within that range.", "the limit of three keys applies only to", "standard (also known as \"bare\") multisignature scripts, not to", "scripts wrapped in another structure like P2SH, P2WSH, or P2TR.", "P2SH multisignature scripts are limited by both policy and consensus to", "15 keys, allowing for up to a 15-of-15 multisignature.", "All other scripts are consensus limited to 20 keys", "per +OP_CHECKMULTISIG+ or +OP_CHECKMULTISIGVERIFY+ opcode, although one", "script may include multiple of those opcodes."),
 Qb(BK, "When", "+OP_CHECKMULTISIG+ executes, it should consume _t_ + _k_ + 2 items on the stack as", "parameters.", "due to the oddity, +OP_CHECKMULTISIG+ will pop an extra", "value or one value more than expected."),
 Qb(BK, "First, +OP_CHECKMULTISIG+ pops the top item, which is _k_", "Then it pops _k_ items, which are the public keys that can sign;", "Then, it pops one item, which", "is _t_, the quorum (how many signatures are needed).", "an oddity in the implementation causes +OP_CHECKMULTISIG+ to pop one more item (_t_ + 1", "total) than it should.", "The extra item is called", "the _dummy stack", "element_", "and it is disregarded when checking the", "signatures so it has no direct effect on +OP_CHECKMULTISIG+ itself.", "the dummy element must be present because, if it isn't present", "when +OP_CHECKMULTISIG+ attempts to pop on an empty stack, it will cause a", "stack error and script failure"),
 Qb(BK, "It became the custom early on to use +OP_0+, which later became a", "relay policy rule and eventually a consensus rule (with the enforcement of BIP147).", "Because popping the dummy element is part of the consensus rules, it must now be", "replicated forever.", "OP_0 <Sig B> <Sig C> 2 <Pubkey A> <Pubkey B> <Pubkey C> 3 OP_CHECKMULTISIG", "OP_0 <Sig B> <Sig C>"),
 Qb(BK, "Some people believe this oddity was a bug in the original code for", "Bitcoin, but a plausible alternative explanation exists.", "Verifying", "_t_-of-_k_ signatures can require many more than _t_ or _k_ signature checking", "operations.", "<dummy> <Sig4> 1 <key0> <key1> <key2> <key3> <key4> 5 OP_CHECKMULTISIG", "The signature is checked first against +key0+, then +key1+, and then", "the other keys before it is finally compared to its corresponding", "+key4+.", "That means five signature checking operations need to be", "performed even though there's only one signature.", "so they could add the", "feature for allowing a map to be passed in a later soft fork.", "that feature was never implemented, and the BIP147 update to the", "consensus rules in 2017 makes it impossible to add that feature in the", "future.", "Only Bitcoin's original", "developer could tell us whether the dummy stack", "element was the result of a bug or a plan for a future upgrade."),
 Qe("bip-0011.mediawiki", "Three-party escrow (buyer, seller, and trusted dispute agent). 2-of-3 signatures required transactions will be used.", "m {pubkey}...{pubkey} n OP_CHECKMULTISIG", "OP_0 is required because of a bug in OP_CHECKMULTISIG; it pops one too many items off the execution stack, so a dummy value must be placed on the stack", "old clients and miners count it as \"20 sigops\"", "there is a hard limit of 20,000 sigops per block-- meaning a maximum of 1,000 multisig transactions per block"),
 Qe("bip-0147.mediawiki", "A design flaw in <code>OP_CHECKMULTISIG</code> and <code>OP_CHECKMULTISIGVERIFY</code> causes them to consume an extra stack element (\"dummy element\") after signature validation.", "The dummy element is not inspected in any manner, and could be replaced by any value without invalidating the script.", "the dummy element MUST be the empty byte array.", "Anything else makes the script evaluate to false immediately.", "the <code>NULLDUMMY</code> rule has been enforced as relay policy by the reference client since v0.10.0", "using the same parameters for BIP141 and BIP143", "bit 1", "will change the <code>txid</code> and invalidate any unconfirmed child transactions"),
 Qc("src/script/interpreter.cpp", "// ([sig ...] num_of_signatures [pubkey ...] num_of_pubkeys -- bool)", "if (nKeysCount < 0 || nKeysCount > MAX_PUBKEYS_PER_MULTISIG)", "if (nSigsCount < 0 || nSigsCount > nKeysCount)", "// A bug causes CHECKMULTISIG to consume one extra argument", "// whose contents were not checked in any way.", "if ((flags & SCRIPT_VERIFY_NULLDUMMY) && stacktop(-1).size())", "return set_error(serror, SCRIPT_ERR_SIG_NULLDUMMY);", "if (sigversion == SigVersion::TAPSCRIPT) return set_error(serror, SCRIPT_ERR_TAPSCRIPT_CHECKMULTISIG);", "valtype& vchSig = stacktop(-isig);", "valtype& vchPubKey = stacktop(-ikey);", "if (nSigsCount > nKeysCount) fSuccess = false;"),
 Qc("src/script/interpreter.h", "// verify dummy stack item consumed by CHECKMULTISIG is of zero-length (BIP62 rule 7).", "SCRIPT_VERIFY_NULLDUMMY,"),
 Qc("src/script/script.h", "inline constexpr int MAX_PUBKEYS_PER_MULTISIG = 20;", "inline constexpr unsigned int MAX_SCRIPT_ELEMENT_SIZE = 520;", "inline constexpr int MAX_OPS_PER_SCRIPT = 201;"),
 Qc("src/script/script.cpp", "n += DecodeOP_N(lastOpcode);", "n += MAX_PUBKEYS_PER_MULTISIG;"),
 Qc("src/consensus/consensus.h", "inline constexpr int64_t MAX_BLOCK_SIGOPS_COST{80'000};"),
 Qc("src/policy/policy.cpp", "// Support up to x-of-3 multisig txns as standard", "if (n < 1 || n > 3)", "// Biggest 'standard' txin involving only keys is a 15-of-15 P2SH", "// multisig with compressed keys (remember the MAX_SCRIPT_ELEMENT_SIZE byte limit on", "// redeemScript size). That works out to a (15*(33+1))+3=513 byte", "// redeemScript, 513+1+15*(73+1)+3=1627 bytes of scriptSig, which", "// we round off to 1650(MAX_STANDARD_SCRIPTSIG_SIZE) bytes for"),
 Qc("src/policy/policy.h", "inline constexpr unsigned int MAX_STANDARD_P2WSH_SCRIPT_SIZE{3600};", "SCRIPT_VERIFY_NULLDUMMY |"),
 Qc("src/script/solver.cpp", "if (script.size() < 1 || script.back() != OP_CHECKMULTISIG) return false;", "TxoutType::MULTISIG"),
 Qc("src/kernel/chainparams.cpp", "consensus.SegwitHeight = 481824;"),
 # executed: the pattern with real signatures
 X("L.multisig_script(2, [C.pub(0), C.pub(1), C.pub(2)]).hex()[:4] + '...' + L.multisig_script(2, [C.pub(0), C.pub(1), C.pub(2)]).hex()[-4:]", "5221...53ae"),
 X("L.classify(L.multisig_script(2, [C.pub(0), C.pub(1), C.pub(2)]))", ("multisig", "2-of-3")),
 X("(C.ms_spend(2, 3, [1, 2]), C.ms_spend(2, 3, [0, 2]), C.ms_spend(2, 3, [0, 1]))", ("OK", "OK", "OK")),
 X("(C.ms_spend(2, 3, [1]), C.ms_spend(1, 3, [1]), C.ms_spend(3, 3, [0, 1, 2]))", ("INVALID_STACK_OPERATION", "OK", "OK")),
 X("(C.ms_spend(2, 3, [2, 1]), C.ms_spend(2, 3, [1, 1]))", ("EVAL_FALSE", "EVAL_FALSE")),
 X("L.classify(L.multisig_script(1, [C.pub(0)]))", ("multisig", "1-of-1")),
  X("(C.ms_spend(2, 3, [1, 2], wrap='p2sh'), C.ms_spend(2, 3, [1, 2], wrap='p2wsh'))", ("OK", "OK")),
 # executed: the sample public keys and signatures of the browser example
 X("(L.pubkey_create(11).hex(), L.pubkey_create(12).hex(), L.pubkey_create(13).hex()) == (" + repr(KA) + ", " + repr(KB) + ", " + repr(KC) + ")", True),
 X("L.sha256(b'two of three').hex()", Z2OF3),
 X("[L.der_parse_lax(L.ecdsa_sign(s, L.sha256(b'two of three'))) for s in (12, 13)] == [" + repr(SB) + ", " + repr(SC) + "]", True),
 X("(lambda z: [L.ecdsa_verify(C.pub(i), z, L.ecdsa_sign(11 + j, z)) for i, j in ((1, 1), (2, 2), (2, 1), (0, 1))])(L.sha256(b'two of three'))", [True, True, False, False]),
 # executed: the limits
 X("[len(L.multisig_script(1, [C.pub(i % 8) for i in range(k)])) for k in (3, 15, 16, 20)]", [105, 513, 547, 684]),
 X("(3 + 34 * 15, 3 + 34 * 16, 15 * (33 + 1) + 3)", (513, 547, 513)),
 X("(C.ms_spend(15, 15, list(range(15)), wrap='p2sh'), C.ms_spend(20, 20, list(range(20)), wrap='p2wsh'))", ("OK", "OK")),
 X("(L.get_ops(L.multisig_script(1, [C.pub(0), C.pub(1)]))[0][1], L.get_ops(L.multisig_script(1, [C.pub(0), C.pub(1)]))[-1][1])", (81, 174)),
 X("(lambda spk: L.classify(spk))(L.multisig_script(2, [C.pub(i) for i in range(4)]))", ("multisig", "2-of-4")),
 X("1650 - 1627", 23),
 X("513 + 1 + 15 * (73 + 1) + 3", 1627),
 X("(C.census(L)['p2sh-multisig 2-of-3'], sum(v for k, v in C.census(L).items() if k.startswith('p2wsh-multisig')), C.census(L)['p2wsh-multisig 2-of-3'], C.census(L)['p2wsh-multisig 2-of-2'])", (10, 57, 41, 5)),
 X("sum(v for k, v in C.census(L).items() if 'multisig' in k)", 67),
 X("[k for k in C.census(L) if k == 'multisig' or k.startswith('multisig')]", []),
 X("sum(1 for r in C.block_records() for w in L.parse_tx(r['hex']).witness if len(w) > 2 and w[-1][-1:] == b'\\xae' and 81 <= w[-1][0] <= 96 and 81 <= w[-1][-2] <= 96 and w[0] == b'')", 91),
 X("C.census(L)['p2sh-p2wsh']", 34),
 X("sum(1 for r in C.block_records() for i, x in enumerate(L.parse_tx(r['hex']).vin) if L.is_p2sh(bytes.fromhex(r['spent'][i][1])) and L.get_ops(x[2]) and L.get_ops(x[2])[0][1] == 0 and L.get_ops(x[2])[-1][2] is not None and L.get_ops(x[2])[-1][2][-1:] == b'\\xae')", 10),
 # executed: the dummy element
 X("(C.ms_spend(2, 3, [1, 2]), C.ms_spend(2, 3, [1, 2], dummy=b'\\x01'))", ("OK", "SIG_NULLDUMMY")),
 X("C.ms_spend(2, 3, [1, 2], dummy=b'\\x01', flags=frozenset({'P2SH'}))", "OK"),
 X("C.ms_spend(2, 3, [1, 2], dummy=b'\\x01', wrap='p2wsh')", "SIG_NULLDUMMY"),
 X("(L.disassemble(L.multisig_script(2, [C.pub(0), C.pub(1), C.pub(2)])).split()[0], L.disassemble(L.multisig_script(2, [C.pub(0), C.pub(1), C.pub(2)])).split()[-2:])", ("OP_2", ["OP_3", "OP_CHECKMULTISIG"])),
 X("'NULLDUMMY' in L.MAINNET_FLAGS and 'NULLDUMMY' in L.STANDARD_FLAGS", True),
 # executed: the signature check count
 X("(C.ms_spend(1, 5, [4], count=True), C.ms_spend(1, 5, [0], count=True), C.ms_spend(3, 3, [0, 1, 2], count=True))", (("OK", 1), ("OK", 5), ("OK", 3))),
 X("[C.ms_spend(1, 5, [i], count=True)[1] for i in range(5)]", [5, 4, 3, 2, 1]),
 X("C.ms_spend(2, 3, [1, 2], count=True)", ("OK", 2)),
 X("C.ms_spend(2, 3, [0, 2], count=True)[1]", 3),
]
