"""SEN0401 chapter 1, text part E (version 1.2.0): the Nature branch (what kind of thing Bitcoin is) and the further concepts added to the Transfer, Address and Standards
sections. See sen0401_ch01_corpus_v1_2_0.py."""
from sen0401_ch01_common_v1_2_0 import W, Y, E, H, K, js, prog
_RULE = prog('''def accept(claim, height, fees):
    subsidy = (50 * 10**8) >> (height // 210000)
    return claim <= subsidy + fees
result = [accept(312_500_000, 840000, 0), accept(312_500_001, 840000, 0), accept(325_000_000, 840000, 12_500_000)]''')
_P2P = prog('''links = {'A': ['B', 'C'], 'B': ['A', 'D'], 'C': ['A', 'E'], 'D': ['B', 'F'], 'E': ['C', 'F'], 'F': ['D', 'E', 'G'], 'G': ['F']}
seen, frontier, rounds = {'A'}, {'A'}, 0
while len(seen) < len(links):
    frontier = {n for f in frontier for n in links[f]} - seen
    seen |= frontier; rounds += 1
result = rounds''')
_VIRT = prog('''txs = [('Joe', 'Alice', 100_000), ('Alice', 'Eve', 30_000), ('Joe', 'Eve', 5_000)]
def balance(who): return sum(a for f, t, a in txs if t == who) - sum(a for f, t, a in txs if f == who)
result = (balance('Alice'), balance('Eve'))''')
_CHAN = prog('''onchain, a, b = 2, 60_000, 40_000
for _ in range(100):
    a, b = a - 10, b + 10
result = (a, b, a + b, onchain)''')
_LN = prog('''channels = {('Alice', 'Bob'), ('Bob', 'Carol'), ('Carol', 'Dave')}
nbr = {}
for x, y in channels: nbr.setdefault(x, []).append(y); nbr.setdefault(y, []).append(x)
path, frontier = {'Alice': ['Alice']}, ['Alice']
while 'Dave' not in path:
    nxt = []
    for x in frontier:
        for y in nbr[x]:
            if y not in path: path[y] = path[x] + [y]; nxt.append(y)
    frontier = nxt
result = (path['Dave'], len(path['Dave']) - 1, ('Alice', 'Dave') in channels)''')
NODES_E = [
 # ------------------------------------------------------------------ NATURE
 ("Nature", None, 1, None, None, [
  (W, "The Nature branch answers a question that precedes all the others: what kind of thing is Bitcoin? Chapter 1 gives two complementary answers. The first describes the characteristics of the currency, which is virtual, borderless, decentralized and robust. The second describes the architecture, which the chapter lists as four innovations brought together: a decentralized peer-to-peer network, a public transaction journal, a set of rules for validation and issuance, and a mechanism for reaching consensus [AH]."),
  (Y, "A student who knows only how to use a wallet knows what Bitcoin does and not why it is built as it is. The characteristics explain the goals, and the architecture explains how the goals are met. The sidebar on digital currencies before Bitcoin makes the link: earlier systems were centralized and easy to attack, so a decentralized digital currency was needed to be robust against intervention by antagonists, whether legitimate governments or criminal elements [AH]."),
  (E, "The characteristics appear in the opening paragraphs of the chapter, where Bitcoin is called arguably the perfect form of money for the internet because it is fast, secure and borderless, and where the currency is described as entirely virtual [AH]. The architecture appears in the list of what Bitcoin consists of, and each item of that list is then explained in the Network branch and the Foundations branch."),
  (H, "The branch has two sections. The Characteristic section contains four concepts, virtual, borderless, decentralized and robust, each of which names a property that the chapter attributes to the currency. The Architecture section contains three concepts that correspond to three of the four innovations in the chapter's list: the peer-to-peer protocol, the public journal and the consensus rule set. The fourth innovation, the proof-of-work mechanism, has its own concept in the Network branch."),
  (K, "A list of attractive adjectives is not an argument. Each characteristic is a claim that can be examined, and each depends on conditions: a currency is borderless only where people can reach the network, decentralized only while control stays spread out, and robust only against the threats it was designed for. The branch should be read as an account of design goals, with the evidence supplied by the other branches."),
 ], None),
 ("Characteristic", None, 2, "Nature", None, [
  (W, "The Characteristic section collects four properties that the chapter attributes to the bitcoin currency: it is virtual, it is borderless, it is decentralized, and it is robust. The first two come from the opening description of the currency, where Bitcoin is called arguably the perfect form of money for the internet because it is fast, secure and borderless, and the last two from the sidebar that explains why a decentralized digital currency was needed at all [AH]. The four are properties of the thing itself and not of any program that uses it, which is why they sit in their own branch rather than among the wallets."),
  (Y, "These properties distinguish Bitcoin from conventional money and from the earlier digital currencies that the chapter's sidebar describes. Conventional money exists in a physical and an electronic form at once and is controlled by central institutions; the earlier digital currencies were electronic but centralized, and the sidebar records that they were therefore easy to attack and that most were litigated out of existence or collapsed with the company behind them [AH]. Bitcoin combines a purely virtual existence with the absence of any central authority, and the chapter presents that combination, rather than either half of it, as the reason the currency suits the internet."),
  (H, "Each concept in the section is defined by the sentence of the chapter that introduces it and is then connected to the mechanism that makes it true, because a property without a mechanism is only a slogan. Virtual is shown by computing a balance from a list of transfers, which demonstrates that the coins need not exist anywhere as objects. Borderless, decentralized and robust are referred to the mechanisms of the other branches: the peer-to-peer protocol carries a payment without asking where its parties live, the consensus rules let every participant check issuance for himself, and proof of work makes the rewriting of history expensive. A learner who can name the mechanism for each property has understood the section."),
 ], None),
 ("Virtual", "Virtual", 3, "Characteristic", ("balances computed from transactions", "The bitcoin currency is entirely virtual: there are no physical coins or even individual digital coins, only transactions that imply the coins.", (_VIRT, "(70000, 35000)")), [
  (W, "To say that the bitcoin currency is virtual is to say that it has no physical or object form. The chapter states this precisely: unlike traditional currencies, the bitcoin currency is entirely virtual, there are no physical coins or even individual digital coins, and the coins are implied in transactions that transfer value from spender to receiver [AH]."),
  (Y, "The statement removes a common picture. Many people imagine a bitcoin as a file or a token that moves from one wallet to another, but nothing moves; the record of transfers is all there is. This is why the central question of the system is who may create a valid transfer, which the chapter answers by the control of keys: users control keys that allow them to prove ownership, and with these keys they sign transactions to unlock the value and spend it by transferring it to a new owner [AH]."),
  (E, "The property shows in every wallet. The balance that Alice sees is not a number stored somewhere as a coin; it is a figure that her wallet calculates from the transactions that involve her addresses. Alice's wallet shows 0.001 BTC as incoming as soon as it sees Joe's transaction, even though no coin has been delivered in the physical sense [AH]."),
  (H, "The example represents a tiny history as a list of transfers, Joe pays Alice 100000 satoshis, Alice pays Eve 30000, and Joe pays Eve 5000. The program computes each person's balance by adding what they received and subtracting what they sent: Alice has 70000 and Eve has 35000. No coin exists in the program, only the list. Bitcoin works on the same principle, with the list made public and validated by the nodes."),
  (K, "Virtual does not mean unreal. The value is real because people accept it, in the same way that the value of a bank balance is real. It also does not mean that nothing can be lost, since a lost key makes the funds unspendable. Finally, the word does not describe the system as a whole: the network, the miners and the wallets are physical machines that use real electricity and real hardware."),
 ]),
 ("Borderless", "Borderless", 3, "Characteristic", ("money for the internet", "Bitcoin is fast, secure and borderless, which the chapter gives as the reason that it is arguably the perfect form of money for the internet.", None), [
  (W, "Borderless means that the currency is not tied to any country or to its financial institutions. The chapter says that Bitcoin is arguably the perfect form of money for the internet because it is fast, secure and borderless [AH]. A payment is sent to an address and does not depend on the nationality of the recipient."),
  (Y, "Conventional payments between countries pass through banks and clearing systems that apply different rules and take time. The internet itself has no such borders, which is why a money that behaves like an internet service fits it so well. The chapter's list of what users can do is long: Bitcoin can be used to buy and sell goods, send money to people or organisations, or extend credit, just as with conventional currencies [AH]."),
  (E, "The property is met in remittances sent home across a border, in online purchases from a foreign seller, and in the global markets where bitcoin is exchanged for other currencies; the chapter notes that bitcoin can be purchased, sold and exchanged for other currencies at specialised currency exchanges [AH]. It is also met in the reach of the software itself, since the protocol stack is open source and runs on a wide range of devices, including laptops and smartphones, which the chapter gives as the reason the technology is easily accessible [AH]. A payment to an address therefore looks the same to the network whether the payee is in the next street or on another continent."),
  (H, "Bitcoin is borderless because the network is a peer-to-peer system on top of the internet and the rules are the same everywhere. Anyone can run the software on a laptop or a smartphone, as the chapter notes, and any participant can send to any address [AH]. Where bitcoin touches the traditional system, at exchanges for example, national and international regulations often apply."),
  (K, "Borderless does not mean that law does not apply. The chapter states that national and international regulations often apply where bitcoin touches traditional systems, and that exchanging bitcoin for national currency will often require proof of identity and banking information [AH]. The word also says nothing about prices, which float and can differ from market to market."),
 ]),
 ("Decentralized", "Decentralized", 3, "Characteristic", ("no single point of control", "Bitcoin is decentralized by design and free of any central authority or point of control that can be attacked or corrupted.", None), [
  (W, "A decentralized system is one that has no central authority or point of control. The chapter says that Bitcoin is decentralized by design, and free of any central authority or point of control that can be attacked or corrupted [AH]. Its ordinary statement of the same idea is that there is no central server or point of control in the system."),
  (Y, "Centralization is a weakness of the systems that came before. The sidebar explains that earlier digital currencies worked but were centralized and, as a result, were easy to attack by governments and hackers; they used a central clearinghouse to settle all transactions, and most were litigated out of existence or collapsed when their parent company liquidated abruptly [AH]. Decentralization removes the single party whose failure or coercion would end the system."),
  (E, "The property appears in the way that Bitcoin is run. No one owns the network; the chapter states that neither Satoshi Nakamoto nor anyone else exerts individual control over the Bitcoin system, which operates based on fully transparent mathematical principles, open source code and consensus among participants [AH]. Miners, nodes and wallet developers are separate parties."),
  (H, "Decentralization is achieved by spreading each function across many participants. Validation is done by every full node, issuance and clearing are done by miners competing for blocks, and the rules are written in software that everyone can read. The result is that no participant can unilaterally change a rule or block a payment; changing a rule requires nearly everyone to run new software."),
  (K, "Decentralization is a matter of degree and it can erode. If most of the mining were done by a few pools, or most users relied on a few custodians, the practical control would be concentrated, even though the design allows otherwise. The word also does not mean absence of rules: Bitcoin has strict rules, enforced by software instead of by a person."),
 ]),
 ("Robust", "Robust", 3, "Characteristic", ("resisting intervention", "A robust digital currency is built to withstand intervention by antagonists, whether legitimate governments or criminal elements, which a decentralized design makes possible.", None), [
  (W, "Robust means able to withstand attack and interference and to keep working while under them. The chapter's sidebar states the requirement in one sentence: to be robust against intervention by antagonists, whether legitimate governments or criminal elements, a decentralized digital currency was needed to avoid a single point of attack [AH]. The two words of that sentence that a student should notice are antagonists, which covers both lawful and unlawful opponents, and single point of attack, which names what the design removes rather than what it adds."),
  (Y, "The history of digital money supplies the motive. The earlier projects were targeted by worried governments and were eventually litigated out of existence, or failed in spectacular crashes when the parent company liquidated abruptly [AH]. A currency intended to last must not depend on a company or an institution that can be pressured, sued or closed."),
  (E, "Robustness is a property of the whole design. The chapter points to mining as a security mechanism, noting that the number and power of the machines running the proof-of-work algorithm have increased exponentially, and that their combined computational power now exceeds the combined computing operations of the world's top supercomputers [AH]. The more work that protects the record, the harder it is to attack."),
  (H, "Robustness follows from decentralization plus cost. Because there is no central point, an attacker must act against many independent participants. Because the record is protected by proof of work, rewriting it would require repeating the work. The whitepaper expresses the resulting guarantee: as long as honest nodes control the majority of the computing power, the honest chain will grow the fastest and outpace any competing chains [NK]."),
  (K, "Robust is not the same as invulnerable. The guarantee depends on the honest majority assumption, on the correctness of the software, and on users protecting their keys; the chapter itself lists dangers such as malware and phishing. A robust network can contain fragile wallets, and the weakest link is often the user's own device."),
 ]),
 ("Architecture", None, 2, "Nature", None, [
  (W, "The Architecture section describes how the Bitcoin system is put together. After the opening pages, the chapter lists what Bitcoin consists of: a decentralized peer-to-peer network, a public transaction journal, a set of rules for independent transaction validation and currency issuance, and a mechanism for reaching global decentralized consensus on the valid blockchain [AH]. It adds that Bitcoin builds on decades of research in cryptography and distributed systems and includes at least four key innovations brought together in a unique and powerful combination."),
  (Y, "The combination, rather than any single part, is the invention. Digital signatures, hash functions and peer-to-peer networks existed before. What was new was the arrangement in which they support each other, so that a money system works without a central party. A student who can name the four parts and say what each contributes understands the structure of the whole subject."),
  (H, "Three of the four parts are concepts of this section. The peer-to-peer protocol describes the network. The public journal describes the record. The consensus rule set describes the rules every participant applies. The fourth part, the proof-of-work mechanism, is explained in the Consensus section of the Network branch, because it is the means by which the other three are brought to agreement."),
 ], None),
 ("PeerToPeerProtocol", "Peer-to-peer protocol", 3, "Architecture", ("a decentralized peer-to-peer network", "The Bitcoin protocol defines a decentralized peer-to-peer network in which every full node is a peer that both provides and consumes services.", (_P2P, "4")), [
  (W, "The peer-to-peer protocol is the first of the four parts of Bitcoin that the chapter lists: a decentralized peer-to-peer network, which it identifies as the Bitcoin protocol [AH]. The textbook's chapter on the network explains that the term peer-to-peer means that the full nodes that participate are peers to each other, that they can all perform the same functions, and that there are no special nodes [AH]."),
  (Y, "A peer-to-peer design removes the server. With no central machine to run, pay for, defend or shut down, the network has no single point of failure or control. The network chapter observes that peer-to-peer networks are inherently resilient, decentralized and open, and that decentralization of control is a core design principle of Bitcoin that can only be achieved and maintained by a flat and decentralized network [AH]."),
  (E, "The network chapter describes the arrangement as a mesh with a flat topology, with no server, no centralized service and no hierarchy; nodes both provide and consume services at the same time. It also names file sharing as another large application of peer-to-peer technology [AH]. In the chapter's story, Joe's transaction reaches the whole network by being passed from peer to peer."),
  (H, "Each node connects to several others, and each message is passed on from node to node until it has reached everyone. The example models seven peers with a few links between them and floods a message from peer A; the program counts the rounds until every peer has it, and the answer is 4. The real network is far larger, but the principle is the same: reach grows with each round of forwarding."),
  (K, "Peer-to-peer does not mean that all participants are equal in practice. Many users run clients and not peers, as the chapter explains, and the network also contains gateway servers that extend it to other protocols [AH]. A message passed from peer to peer is also not instantly delivered everywhere: it takes a few seconds for a transaction to reach most well-connected nodes."),
 ]),
 ("PublicJournal", "Public journal", 3, "Architecture", ("the blockchain as a public transaction journal", "The second part of Bitcoin is a public transaction journal, the blockchain, in which every confirmed transaction is recorded for anyone to read.", None), [
  (W, "The public journal is the second part of Bitcoin in the chapter's list: a public transaction journal, the blockchain [AH]. A journal is a chronological record, and public means that anyone can read it. The chapter uses the same phrase when it explains confirmation, as the Bitcoin transaction journal known as the blockchain."),
  (Y, "A shared record is what lets strangers agree about who owns what without trusting one another. In a bank, only the bank sees the full ledger and the customers trust its statements. In Bitcoin the ledger is open, and every participant can check it, so trust is replaced by verification. The whitepaper makes the same argument: the only way to confirm the absence of a transaction is to be aware of all transactions, so the transactions must be publicly announced [NK]."),
  (E, "The journal is met in block explorers, in the data that nodes download, and in the way wallets compute balances. The chapter tells us that Alice's address first shows Joe's payment as unconfirmed and that it is confirmed when it is recorded in the journal [AH]. The privacy consequence is also public: the chapter notes that once a Bitcoin address is attached to an identity, associated transactions may become easy to identify and track."),
  (H, "The journal is stored as a chain of blocks, each of which commits to its predecessor, and every full node keeps a copy. New entries are added by miners, in blocks, about every ten minutes, and each node checks them before appending them to its copy. The Chain section of the Foundations branch explains the structure in detail."),
  (K, "Public does not mean that the entries carry names. They carry addresses and amounts, which is pseudonymous and not anonymous, as the privacy concept of the Usage branch explains, and the whitepaper describes the same arrangement as keeping the public keys anonymous so that an amount can be seen moving without anything linking it to a person [NK]. Nor does public mean complete: the journal holds only what was recorded on the chain, so payments made by the offchain methods of the Transfer group do not appear in it at all. A student should therefore read the journal as a record of onchain transfers between addresses and not as a list of who paid whom."),
 ]),
 ("ConsensusRuleSet", "Consensus rule set", 3, "Architecture", ("the rules every node applies", "The consensus rules are the set of rules for independent transaction validation and currency issuance that every participant applies in the same way.", (_RULE, "[True, False, True]")), [
  (W, "The consensus rule set is the third part of Bitcoin in the chapter's list: a set of rules for independent transaction validation and currency issuance, which the chapter calls consensus rules [AH]. They define what makes a transaction valid, what makes a block valid, and how many new bitcoins a block may create."),
  (Y, "Because Bitcoin has no referee, each participant must be able to decide for himself whether a transaction or a block is acceptable, and all of them must reach the same decision. The rules are the means of this. The chapter says that nobody can force you to accept any bitcoins that were created beyond the expected issuance rate [AH]; the rules make that statement true, because a block that breaks them is rejected."),
  (E, "The rules are written into the software of the nodes. Bitcoin Core's validation code, for instance, compares the amount that the first transaction of a block claims with the sum of the fees and the subsidy for the block height, and rejects the block if it claims more [BC]. The difficulty and subsidy rules are in the same code."),
  (H, "Each node checks every block and every transaction against the rules before it accepts it. The example is a miniature of the reward rule: a block at height 840000 may claim at most the subsidy of 312,500,000 satoshis plus the fees. A claim of exactly the subsidy is accepted, a claim one satoshi higher is rejected, and a claim that includes 12,500,000 satoshis of fees is accepted."),
  (K, "The rules are valid only as long as the participants run them. Changing a rule means persuading nearly everyone to run new software, and a minority that runs different rules ends up on a chain of its own. A rule is also different from a policy that a single node applies for convenience, such as the fee below which it will not relay a transaction."),
 ]),
 # ------------------------------------------------------------------ ADDED CONCEPTS (further nodes for the existing sections)
 ("PaymentChannel", "Payment channel", 3, "Transfer", ("many payments with two transactions on the chain", "A payment channel is a class of techniques that lets users make many Bitcoin transactions without committing all of them to the blockchain; typically only two transactions are recorded.", (_CHAN, "(59000, 41000, 100000, 2)")), [
  (W, "A payment channel is a technique that lets two parties make many payments between themselves while recording only a few transactions on the blockchain. The glossary of the textbook defines a micropayment channel or payment channel as a class of techniques designed to allow users to make multiple Bitcoin transactions without committing all of the transactions to the Bitcoin blockchain, and says that in a typical payment channel only two transactions are added to the blockchain but an unlimited or nearly unlimited number of payments can be made between the participants [AH]."),
  (Y, "Every transaction on the chain pays a fee and competes for limited room in blocks, so small and frequent payments are costly there. A channel moves the frequent payments elsewhere. The chapter lists the benefits of offchain technology as reduced costs and improved privacy, among other things [AH]."),
  (E, "Payment channels are the building blocks of the Lightning Network, the next concept, which connects many of them so that a payment can pass through a chain of channels. A reader meets them today in wallets that offer both ordinary onchain payments and fast payments over such channels, and in services that settle many small amounts between the same two parties. In this chapter they appear in one place only, the discussion of backups, because a channel changes what a backup has to contain: the balance inside a channel is the result of payments that were never written into the public record, so it cannot be recovered from that record [AH]."),
  (H, "Two parties open a channel with a transaction on the chain that commits funds to it, then exchange signed updates that shift the balance between them, and close the channel with a final transaction that settles the last balance. The example models a channel opened with 60,000 and 40,000 satoshis; after 100 payments of 10 satoshis from the first party to the second, the balances are 59,000 and 41,000 satoshis, the total is unchanged at 100,000, and only the two transactions of opening and closing are counted on the chain."),
  (K, "The payments in a channel are not recorded in the public blockchain, so a recovery code, which rebuilds the wallet from onchain data, cannot restore them; the chapter tells users of applications with offchain support to make frequent backups of the wallet database [AH]. The toy model here also leaves out the safeguards that make real channels secure against a party that tries to cheat."),
 ]),
 ("LightningNetwork", "Lightning Network", 3, "Transfer", ("a route through several channels", "The Lightning Network connects payment channels so that a payment can be routed through several of them, and any peer can pay any other even without a direct channel.", (_LN, "(['Alice', 'Bob', 'Carol', 'Dave'], 3, False)")), [
  (W, "The Lightning Network is a network of payment channels. The glossary of the textbook describes it as a proposed implementation of Hashed Timelock Contracts with bi-directional payment channels, which allows payments to be securely routed across multiple peer-to-peer payment channels, so that any peer on the network can pay any other even if they do not directly have a channel open between each other [AH]. Its authors' paper presents the idea as a way to scale Bitcoin by moving most payments off the chain [LN]."),
  (Y, "A single channel only helps two parties who deal with each other often. By linking channels into a network, the system lets a payer reach people with whom he has no channel, in the way that the internet lets any computer reach any other through intermediate machines. This extends the benefits of offchain payment, lower cost and better privacy, to ordinary payments between strangers [AH]."),
  (E, "The chapter mentions the Lightning Network only twice, in the glossary entry and in the discussion of offchain payments, and the later chapters of the book return to it in detail; this course therefore treats it here as a named example of offchain technology and not as a subject of its own. It is met today in wallets that offer fast payments with low fees beside ordinary onchain ones, and in the payment pages of merchants who accept both. Its own authors present it as a way of carrying a large volume of payments without writing each of them into the chain [LN]."),
  (H, "A payer finds a path of channels from himself to the recipient, and each intermediate party forwards the payment over its own channel. The example has channels Alice-Bob, Bob-Carol and Carol-Dave. There is no direct channel between Alice and Dave, but the program finds the route Alice, Bob, Carol, Dave, of three hops."),
  (K, "A routed payment depends on the intermediaries having enough funds in the right channels, and it is a different system from the chain: it has its own failures and its own privacy and backup considerations. Funds held in channels are not visible in the blockchain, so a wallet that supports the network needs its database backed up as well as its recovery code [AH]."),
 ]),
 ("ElectronicPayment", "Electronic payment", 3, "Transfer", ("cards, PayPal and bank transfers", "An electronic payment is a payment made over an electronic network; credit cards, debit cards, PayPal and bank transfers are reversible, unlike Bitcoin transactions.", None), [
  (W, "An electronic payment is a payment made through an electronic network instead of with cash. The chapter names the common forms: most electronic payment networks, such as credit cards, debit cards, PayPal and bank account transfers, are reversible [AH]. Conventional money is also often stored and transmitted digitally, and in those cases the counterfeiting and double-spend issues are handled by clearing all electronic transactions through central authorities that have a global view of the currency in circulation."),
  (Y, "The comparison with electronic payments explains two features of Bitcoin. First, reversibility is a service that central institutions can provide because they can see and change the record, and Bitcoin has no such institution. Second, the difference creates a risk that is central to buying bitcoin: for someone selling bitcoin, a reversible payment introduces a very high risk that the buyer will reverse the electronic payment after receiving the bitcoin [AH]."),
  (E, "Electronic payments are what a new user uses to acquire a first bitcoin, at an exchange or through another company. The chapter notes that companies accepting traditional electronic payments in return for bitcoin usually require identity verification and credit-worthiness checks, which may take several days or weeks, so that a new user cannot buy bitcoin instantly with a credit card [AH]."),
  (H, "A card or bank payment passes through intermediaries that record and can reverse it. The seller of bitcoin can protect himself only by checking the buyer and by waiting, because once the bitcoin has been sent it cannot be taken back. The whitepaper explains the underlying economics: the possibility of reversal makes merchants wary of customers and increases the cost of transactions [NK]."),
  (K, "Reversible does not mean better or worse; it means that the risk sits with a different party. Reversibility protects a buyer who has been cheated and exposes a seller to the fraud of a reversed payment, while irreversibility does the opposite, and the whitepaper proposes to balance the second case by a routine escrow arrangement in which a third party holds the money until both sides agree [NK]. The chapter's lesson for a student is therefore practical rather than moral: before acting, establish which kind of payment is involved, because the party who can be hurt by a mistake is not the same in the two cases. It is also the reason that the chapter's four ways of acquiring bitcoin differ so much in how long they take."),
 ]),
 ("Privacy", "Privacy", 3, "Address", ("addresses without names", "Privacy in Bitcoin is pseudonymous: payments are public and attached to addresses, not names, until an address is linked to an identity.", None), [
  (W, "Privacy is the ability to keep information about oneself from being known by others. In Bitcoin the chapter describes it as an advantage over other payment systems: when used correctly, Bitcoin affords users much more privacy, since acquiring, holding and spending bitcoin does not require them to divulge sensitive and personally identifiable information to third parties [AH]."),
  (Y, "Financial information reveals much about a person: where he shops, whom he pays and how much he has. The whitepaper explains the approach of Bitcoin: the traditional banking model achieves privacy by limiting access to information to the parties involved and to the trusted third party, whereas Bitcoin can keep privacy by keeping public keys anonymous, so that the public can see that someone is sending an amount to someone else, but without information linking the transaction to anyone [NK]."),
  (E, "Privacy questions arise whenever a payment touches the traditional system. The chapter warns that once a Bitcoin address is attached to an identity, other associated Bitcoin transactions may also become easy to identify and track, including transactions made earlier, which is one reason many users keep dedicated exchange accounts independent from their wallets [AH]. The same issue arises with address reuse and with wallets that query remote servers."),
  (H, "Bitcoin offers pseudonymity, not anonymity. A pseudonym is a fictitious name that a person assumes for a particular purpose [WP], and a Bitcoin address plays that part: it is a name for a payee that has no link to the person's real name. As long as the link is not made, the record shows only addresses. The measures that protect the link are a new address for each payment, separate accounts, and care about the services that learn the user's identity."),
  (K, "Pseudonymous is not private. Everything on the chain is permanent and public, so a single mistake, such as a payment to an exchange that knows the customer, can identify an address and with it a history that stretches back in time. Anonymity is the condition of an identity being unknown or concealed [SH], and Bitcoin does not promise it."),
 ]),
 ("W3cStandard", "W3C standard", 3, "Standards", ("a W3C Recommendation", "The World Wide Web Consortium (W3C) is an international organization that develops web standards; its finished standards are called Recommendations.", None), [
  (W, "The World Wide Web Consortium, abbreviated W3C, is an international public-interest non-profit organisation where member organisations, a full-time staff and the public work together to develop web standards [WC]. It was founded by Tim Berners-Lee in 1994. A finished standard of the consortium is called a Recommendation."),
  (Y, "Open standards are what let software from different makers work together on the web, and W3C is where many of them are agreed. This chapter uses two of its Recommendations as a bridge to identity: the Decentralized Identifiers v1.0 of 19 July 2022 and the Verifiable Credentials Data Model v2.0 of 15 May 2025 [DID][VC]. Both express, in a standard form, the idea that control belongs to whoever holds the keys."),
  (E, "Besides identity, the consortium is known for the standards behind web pages and for those behind the semantic web, which is the theme of this course, so a student of SEN0401 meets its documents in both halves of the syllabus. Its Recommendations are public documents that anyone may read without a fee or a licence, which is why this chapter can cite them in the same way that it cites a Bitcoin Improvement Proposal. The two that are cited here, the Decentralized Identifiers and the Verifiable Credentials Data Model, each publish a dated version at a fixed address: the identifier document is the Recommendation of 19 July 2022 and the credentials document the Recommendation of 15 May 2025 [DID] [VC]. The consortium's own pages state its purpose in one line, that its mission is to make the web work for everyone, and record that Tim Berners-Lee founded it in 1994 to ensure the long-term growth of the web [WC]."),
  (H, "A standard moves through drafts and review by the member organisations and by the public before it becomes a Recommendation, and the finished document is the one that implementers are expected to follow. Each document records its status and its date at the top of its first page, and it gives two addresses: one for this particular version, which never changes, and one for the latest published version, which moves on when a new Recommendation appears [DID] [VC]. A reader can therefore always say which text he is reading, which matters in a course that quotes it. Programs that implement the standard can then be tested against that fixed text, and two independent implementations that both follow it should be able to work together, which is the practical purpose of the whole process."),
  (K, "A Recommendation is a standard and not a law: it binds only those who choose to implement it, and its authority comes from the number of programs that do so rather than from any power to compel. A document that exists is therefore not evidence that the technology it describes is in wide use, and a student should say that a standard specifies a thing rather than that it establishes it. The Recommendations of this consortium should also be told apart from the Bitcoin Improvement Proposals of the earlier section, which are produced by a different community with its own numbering and its own process, even though both are public, numbered documents that specify how something is to be done."),
 ]),
]
