"""SEN0401 chapter 4, corpus text part D (version 1.1.0): the branch 'Address' down to the legacy addresses (scripts, pay to public key, P2PKH, P2SH and the attacks on short hashes).
Markers such as [BK] are replaced by author-year strings in sen0401_ch04_corpus_v1_1_0.py. The first element of every paragraph tuple is
only the author's writing guide and is not printed."""
from sen0401_ch04_text_a_v1_1_0 import W, Y, E, H, K, KHEX, NHEX, YHEX
H160C = "bbc1e42a39d05a4cc61752d6963b7f69d09bb27b"
H160U = "211b74ca4686f81efda5641767fc84ef16dafe0b"

NODES_D = [
 ("Address", None, 1, None, None, [
  (W, "This branch turns the keys of the first branch into something one person can hand to another. An address is a short string that a receiver gives to a payer so that the payer's wallet can build a transaction output that only the receiver can spend. In the book's story Alice wants to pay Bob, and the method she uses has to make sure that only Bob can later spend what he receives [BK]. The branch follows the history of the answer, from the first and simplest scheme of the original Bitcoin paper, in which Alice pays a public key directly, to the addresses that wallets display today."),
  (Y, "The public key itself is a poor thing to hand over. The book points out how long it is: imagine Bob reading the two 64-digit coordinates of his key to Alice over the telephone [BK]. Even the shortest form known to the first developers took 65 bytes, equivalent to 130 characters in hexadecimal, and any mistake made in copying a value of that kind would send the bitcoins to an unspendable output and lose them for ever [BK]. Every step in the history of addresses is an attempt to give the receiver a shorter, safer and more flexible thing to communicate."),
  (E, "Addresses are what a user sees in a wallet. Chapter 1 introduced the Bitcoin address as the string by which a payment is directed, and Chapter 2 showed that a transaction output is the place where funds wait for their next spender. An address is a convenient way of writing down what an output script contains, and the same wallet can show several kinds of address, which differ in the script they stand for, in the alphabet in which they are written and in the checks they carry."),
  (H, "The branch has three parts. The first explains output scripts, input scripts and the stack machine that evaluates them, because every address kind is a name for one script template. The second covers the legacy kinds, the pay to public key output, the public key hash commitment of the P2PKH address and the script hash commitment of the P2SH address, together with the attacks that limit how short a hash can safely be. The third covers the segregated witness addresses, whose design answers the problems that the legacy kinds had [BK]."),
  (K, "An address is not an account and it is not a key. It contains no private information, it can be recomputed from a public key or a script, and it says nothing about who owns the funds. It is also not a promise: a valid address of the right kind is accepted by the wallet even if its owner has lost the key, so that the funds sent to it can never be spent. The remaining sections show how the checks built into each address kind reduce, but never remove, the chance of paying a wrong string."),
 ], None),
 ("Scripts", "Locking and unlocking scripts", 2, "Address", None, [
  (W, "A script, in Bitcoin, is a short program that decides whether a spend of an output is allowed. Every output carries one, called its output script, and every input that spends it carries another, called its input script. The two are run together by every full node that checks the transaction. This level of the chapter introduces both scripts and the small machine that runs them, because each address kind of the following levels is only a name for a particular output script."),
  (Y, "The scripts are what turn the simple scheme of the original paper, a public key and a signature, into something that can express other conditions. The book explains that the first version of Bitcoin did not send payments directly to public keys but to a field called the output script, and authorised spends with a field called the input script, so that additional operations could be performed in addition to, or instead of, verifying that a signature corresponds to a public key [BK]. An output script can, for example, contain two public keys and require two corresponding signatures in the spending input script."),
  (H, "The three concepts below follow the life of a payment. The output script is written by the payer and locks the funds. The input script is written by the spender and unlocks them. The stack machine is the mechanism by which a node combines the two and decides whether the unlocking succeeds. Chapter 3 introduced the full node that does the checking, and the book promises a complete treatment of scripts in a later chapter, so this level confines itself to what is needed to read the address kinds [BK]."),
 ], None),
 ("OutputScript", "Output script", 3, "Scripts", ("the lock on an output", "An output script is the condition that a transaction output places on its spender; the script of a P2PKH output for the book's key is the 25 bytes 76a914, the 20-byte HASH160 of the key, and 88ac.", ("len(bytes.fromhex('76a914" + H160C + "88ac'))", "25")), [
  (W, "An output script is the field of a transaction output that states the conditions under which the funds of that output may be spent. The book describes the arrangement as follows: bitcoins are received to an output script that acts like a public key, and bitcoin spending is authorised by an input script that acts like a signature [BK]. The output script is therefore the lock, and the input script the key that opens it. In the specification of pay to script hash the same field is called by its internal name, the scriptPubKey [B16]."),
  (Y, "Because the lock is a program and not a fixed public key, the receiver can choose what must be shown to spend. The simplest lock asks for a signature that matches one public key. A richer lock can require a public key whose hash matches a stored value, several signatures, or a script that is revealed only when the funds are spent. All the address kinds of this chapter exist so that the receiver can choose among these locks and the payer can build the right one without understanding it."),
  (E, "Output scripts are met whenever a wallet or a block explorer displays an output. Bitcoin Core reports the script of an address when it is asked to validate it, and for the legacy address 1J7mdg5rbQyUHENYdx39WVWK7fsLpEoXZy it gives the hexadecimal string 76a914bbc1e42a39d05a4cc61752d6963b7f69d09bb27b88ac [CORE]. Reading it byte by byte, 76 stands for the operation that duplicates the top item, a9 for the operation that hashes it, 14 says that twenty bytes of data follow, the twenty bytes are the commitment to the public key, and 88 and ac stand for the verification of equality and the check of the signature [BK]."),
  (H, "The payer's wallet builds the output script from the receiver's address. It decodes the address, finds the kind and the data inside it, and writes the matching template with the data in place; that is the whole of the work a payer has to do. The chapter's checks rebuild the script above from the hash of the example key and find the same 25 bytes that Bitcoin Core reported. The opcode values used here are read from the source code of Bitcoin Core, which defines them as numbers, for instance OP_DUP as 0x76 and OP_CHECKSIG as 0xac [CORE]."),
  (K, "An output script is data, not a promise of safety. A payer who builds a script that does not follow one of the accepted templates may create an output that nobody can spend, or one that anyone can spend. The book gives a specific warning for pay to script hash, saying that the output script must be exactly the template with no extra data or conditions, otherwise the bitcoins may be unspendable or spendable by anyone [BK]. For the same reason payers should always use the address of the receiver and never assemble scripts by hand."),
 ]),
 ("InputScript", "Input script", 3, "Scripts", ('the key that opens the lock', 'An input script supplies the data that satisfies the output script of the output being spent; for a P2PKH output it consists of a signature and the public key, with the public key on top of the stack.', ("(lambda stack: (stack[-1], stack[0], len(stack)))(['<Bob signature>', '<Bob public key>'])", "('<Bob public key>', '<Bob signature>', 2)")), [
  (W, "An input script is the field of a transaction input that provides what the output script being spent demands. Where the output script says what must be shown, the input script shows it. In the earliest scheme the input script consisted entirely of the spender's signature, and for a pay to public key hash output it consists of a signature followed by the public key [BK]. In the language of the specification of pay to script hash, the input script is the scriptSig [B16]."),
  (Y, "The separation of the two scripts is what allows the receiver to keep information private until the moment of spending. An output that commits to a hash of a key does not reveal the key; the key appears for the first time in the input script of the spend, where a node checks it against the commitment. The same separation lets a payer create an output without knowing the details of the data that will later be needed to spend it."),
  (E, "Input scripts are met in every spending transaction. The three examples of the chapter show the pattern: the input script of a pay to public key output is the signature alone, that of a pay to public key hash output is the signature and the public key, and that of a pay to script hash output is the signatures followed by the whole redeem script [BK]. The specification of pay to script hash adds a restriction: validation fails if there are any operations other than pushing data in the input script [B16]."),
  (H, "When a node validates a spend, it takes the input script and the output script and runs them as one program. The book explains that you can combine them together, input script first, and then note that each piece of data, shown in angle brackets, is placed at the top of a list of items called a stack [BK]. The data items of the input script are therefore pushed first, and the operations of the output script act on them afterwards. In the pay to public key hash example the signature is pushed first and the public key is placed on top of it."),
  (K, "The input script is the only part of a spend that the spender controls entirely, and it is public once it is broadcast. Everything in it, including a public key that was hidden behind a hash until now, is visible to everybody. A signature, once published, proves nothing further about the key but also reveals nothing that helps an attacker, provided the key was produced and used correctly; a key that is revealed and then reused, by contrast, loses the protection of the hash, a point on which the discussion of address reuse returns."),
 ]),
 ("StackExecution", "Stack, opcodes and script evaluation", 3, "Scripts", ("push, operate, check the top", "Scripts run on a stack: data is pushed on top of a list, each opcode consumes the topmost items and pushes its result, and the script passes if a nonzero item is on top at the end; OP_DUP copies the top item.", ("(lambda s: (s.append(s[-1]), s)[1])(['sig', 'pub'])", "['sig', 'pub', 'pub']")), [
  (W, "A stack is a list of items to which items are added and from which items are removed at one end only, which is called the top. The script machine of Bitcoin evaluates a script on a stack. Data is placed on top of the stack; an operation code, abbreviated opcode, is a one-byte instruction that, when it is encountered, uses items from the stack, starting with the topmost items [BK]. Evaluation of the combined input and output script ends with a result: the script passes if there is a nonzero item on top of the stack at the end of evaluation [BK]."),
  (Y, "The design is simple on purpose. A machine with one stack and a short list of operations is easy to specify exactly, which a consensus system requires, because every node must reach the same verdict for every transaction. If all the scripts of a transaction pass, and all the other details of the transaction are valid, then full nodes consider the transaction valid [BK]. Anything that a node cannot evaluate in the same way as all others would split the network."),
  (E, "Every spend of every output is checked in this manner. The book walks through the two scripts of this chapter. In the pay to public key example, the signature is put on the stack and the public key on top of it; the opcode OP_CHECKSIG consumes two elements, starting with the public key and followed by the signature, verifies that the signature corresponds to the public key and commits to various fields of the transaction, and replaces itself on the stack with 1 if the signature is correct and with 0 if it is not [BK]."),
  (H, "The pay to public key hash example uses four more opcodes. OP_DUP duplicates the top item, so that the public key is on the stack twice. OP_HASH160 replaces the top item with its HASH160. The commitment that was stored in the output script is pushed. OP_EQUALVERIFY consumes the top two items and checks that they are equal, and if they are not, the whole script fails. What remains is the signature and the public key, which OP_CHECKSIG consumes as before [BK]. The chapter's checks run exactly this sequence on a list used as a stack, with the real HASH160 of the example key: with the right commitment the signature and the key remain, with a wrong one the script fails; and they confirm that an ECDSA signature made by the toolkit's sketch verifies against the key and fails for a different message."),
  (K, "The book's text prints the output script of the public key hash scheme with the opcode OP_EQUAL, but the combined script printed a few lines later and the script that Bitcoin Core reports for such an address both use OP_EQUALVERIFY, whose value is 0x88 in the source code of Bitcoin Core while that of OP_EQUAL is 0x87 [CORE]. The difference matters: OP_EQUAL leaves a truth value on the stack while OP_EQUALVERIFY stops the script if the items differ. The stack is also an abstraction of the machine, not a picture of the signature check: the book says only that the signature commits to various fields of the transaction, and this chapter does not reconstruct what is signed [BK]."),
 ]),
 ("Legacy", "Legacy addresses", 2, "Address", None, [
  (W, "Legacy addresses are the address kinds that Bitcoin used before the introduction of segregated witness, and the book still calls them legacy: pay to public key hash (P2PKH) and pay to script hash (P2SH), both written with the base58check encoding [BK]. This level also describes the two forms of payment that came before them, the payment by IP address and the output that pays a public key directly, because they explain what the legacy kinds were designed to improve."),
  (Y, "The legacy kinds solve the problem of communicating a public key by replacing it with a short commitment, a hash of the key, that a receiver can pass on safely. They also introduced a general principle, which later address kinds keep: the receiver chooses the script, the payer needs to know only a short fingerprint of it, and the script is revealed when the funds are spent. The book states that P2PKH and P2SH are the only two script templates used with base58check encoding, that they have become less common over time, and that they were supplanted by the bech32 family of addresses [BK]."),
  (E, "Legacy addresses remain in use and remain valid. They begin with the digit 1 or 3, they are accepted by current wallets such as Bitcoin Core, and a wallet that supports older addresses must continue to recognise them. A new wallet can generate them on request, though it uses a newer kind by default, a point that the section on the default address type returns to."),
  (H, "The concepts of the level follow history. The payment by IP address and the pay to public key output show the first scheme and its limits. The hash commitment, then the P2PKH address, show how a short fingerprint solved the problem. The redeem script, the multisignature script and the P2SH address show how the same idea was extended to arbitrary scripts. The three attacks on short hashes close the level, because they explain why the commitments of the next level are longer."),
  (K, "Legacy does not mean unsafe, and it does not mean obsolete in the same sense as a paper wallet. The book recommends that all new wallets use newer types of address, but it says plainly that there is no immediate threat to anyone creating new P2SH addresses [BK]. The reason for the recommendation is cost and convenience, together with a theoretical risk, and a reader should learn to separate these three."),
 ], None),
 ("IpAddressPayment", "Payment to an IP address", 3, "Legacy", ("Bitcoin 0.1's send screen", "The earliest Bitcoin software let a spender type the receiver's IP address; the spender's node contacted the receiver's node and obtained a new public key, but the receiver had to be online and reachable.", ('(lambda octets: (octets * 8, 2 ** (octets * 8)))(4)', '(32, 4294967296)')), [
  (W, "An IP address is the number that identifies a host on the Internet: the Internet Protocol moves blocks of data called datagrams from sources to destinations, where sources and destinations are hosts identified by fixed-length addresses, and the address is four octets, that is 32 bits, long [R791]. The earliest version of the Bitcoin software allowed a spender to enter the receiver's IP address instead of a public key, as the book's picture of an early send screen shows [BK]. This was the first form of address, and it was removed later."),
  (Y, "The scheme answered the problem of the long public key in the simplest possible way: the receiver does not hand over a key, only an address that is short enough to type. The book explains the mechanism. If Alice entered Bob's IP address in Bitcoin 0.1, her full node would establish a connection with his full node and receive a new public key from Bob's wallet that his node had never previously given anyone. That the key was new was important, because it ensured that different transactions paying Bob could not be connected together by someone looking at the blockchain and noticing that all of them paid the same public key [BK]."),
  (E, "The scheme is of historical interest only. The book says that the feature was later removed, because there are many problems with using IP addresses, and that no widely used program has supported IP address payments for almost a decade [BK]. It is nonetheless useful to know, because later features of the Bitcoin protocol can be understood as answers to its defects."),
  (H, "The first defect is that the receiver needs the wallet to be online at its IP address, and to be accessible from the outside world. The book lists the ordinary reasons for which that is not the case: the computer is turned off at night, the laptop goes to sleep, there is a firewall in the way, or the receiver uses Network Address Translation (NAT) [BK]. Network Address Translation is a method by which IP addresses are mapped from one group to another, so that a network's internal addresses, which cannot be used outside the network, need not be [R3022]. A receiver behind such a translation is not directly reachable by a stranger."),
  (K, "The lesson is not that the scheme was foolish but that its good idea, a fresh public key for every payment, survived while its means of delivery did not. Fresh keys reduce the linking of payments, and the later address kinds, together with wallets that derive many keys from one seed, achieve the same effect without requiring the receiver to be online. A reader should not conclude that Bitcoin addresses are IP addresses: no address of the later kinds contains one."),
 ]),
 ("P2pk", "Pay to public key (P2PK)", 3, "Legacy", ("<public key> OP_CHECKSIG", "A pay to public key output locks funds with the receiver's public key and the opcode OP_CHECKSIG, and is spent with the signature alone; it was never widely used for payments.", ("(lambda s: (s.pop(), s.pop(), s.append(1), s)[3])(['<Bob signature>', '<Bob public key>'])", "[1]")), [
  (W, "Pay to public key, abbreviated P2PK, is the output type in which the output script consists of the receiver's public key followed by the opcode OP_CHECKSIG, and the spender's input script consists of nothing but the signature. The book writes the two scripts as <Bob's public key> OP_CHECKSIG and <Bob's signature> [BK]. This is the form of the original paper's payment, with a script around it."),
  (Y, "P2PK is the baseline against which the later kinds are measured. It places the whole public key in the output, so that the output is as large as the key, and the key is visible to everyone as soon as the output exists. The book remarks that the script uses the same public key and signature described in the original paper but adds the complexity of two script fields and an opcode, and promises that the benefits will become visible in the next sections [BK]."),
  (E, "The book states that this type of output is known today as pay to public key, that it was never widely used for payments, and that the payment by IP address that went with it has not been supported by any widely used program for almost a decade [BK]. In practice a modern reader meets P2PK mainly in discussions of the early blockchain."),
  (H, "The evaluation is the one explained in the concept on the stack machine. The signature is put on the stack, then the public key is placed on top of it, and OP_CHECKSIG consumes the two and replaces them with 1 if the signature is correct, which leaves a nonzero item on top and lets the script pass. The chapter's checks apply the same stack operations to a list and obtain the single value 1, and they check with the toolkit's sketch of a signature that a signature made with the private key verifies against the public key."),
  (K, "In P2PK the public key sits in the output for ever, long before it is spent. That gives up the protection that a hash provides, and it makes the output as long as a public key, 65 bytes in the early encoding, against the 20 bytes of the commitment that the next concept introduces [BK]. The size is also the reason why the receiver of a P2PK payment cannot easily communicate where to pay: the public key is a long string that people cannot dictate."),
 ]),
 ("Commitment", "Hash commitment (HASH160)", 3, "Legacy", ("a hash of the public key", "A hash function output is a commitment to its input; Bitcoin commits to a public key with HASH160, the RIPEMD-160 of the SHA-256 of it, 20 bytes instead of 65.", ("__import__('hashlib').sha256(b'2007.  He said about a year and a half before Oct 2008\\n').hexdigest()", "'94d7a772612c8f2f2ec609d41f5bd3d04a5aa1dfe3582f04af517d396a302e4e'")), [
  (W, "A commitment is a value that a person publishes now in order to be bound to a hidden value that will be revealed later. A cryptographic hash function gives a simple commitment: its output is always the same for the same input, and a secure function also makes it impractical to find a different input that gives a previously seen output, so the output is a promise that, in practice, only input x will produce output X [BK]. In the legacy addresses the hidden value is the receiver's public key, and the commitment is its HASH160."),
  (Y, "The commitment is the idea at the centre of the legacy addresses. The book explains it with a game. The question is in what year Satoshi Nakamoto started working on Bitcoin; the answerer gives a commitment to the answer in the form of the SHA256 hash 94d7a772612c8f2f2ec609d41f5bd3d04a5aa1dfe3582f04af517d396a302e4e, and later reveals the sentence and shows that hashing it gives the same output [BK]. In the same way Bob can give us a cryptographically secure commitment to his public key, and if he later reveals the key and we verify that it produces the same commitment, we can be sure that it was exactly the key used for the earlier commitment [BK]."),
  (E, "Commitments are met throughout this chapter. The 20 bytes inside a P2PKH address commit to a public key, the 20 bytes inside a P2SH address commit to a redeem script, the 20 or 32 bytes of a witness program commit to a key or a script, and the 32-byte witness program of a taproot output is a point that may commit to additional data [BK]. In every case the output holds only the short commitment, and the long object appears in the spending transaction, where nodes check it against the commitment."),
  (H, "The chapter's checks reproduce the book's example: the SHA256 of the sentence, with the line break that the shell command echo adds, is exactly the value that the book prints. For a public key the commitment is computed by HASH160, A = RIPEMD160(SHA256(K)), a 20-byte value, against the 65 bytes of the uncompressed public key of the early software [BK]. The compressed key of the book's example commits to bbc1e42a39d05a4cc61752d6963b7f69d09bb27b, and the same key in the uncompressed form to 211b74ca4686f81efda5641767fc84ef16dafe0b, two different commitments to two encodings of one key."),
  (K, "A commitment binds but does not necessarily hide. If the number of possible hidden values is small, anyone can compute the commitment of every candidate and compare, which is why the book's game would be broken if the answer could only be one of a few years. A public key is one of an enormous number of values, so a commitment to it does hide it until it is revealed; but after the key has been revealed in a spend, the commitment no longer protects it. The commitment is also only as strong as the hash: the following concepts on attacks explain what a 160-bit output can and cannot guarantee."),
 ]),
 ("P2pkhAddress", "P2PKH address", 3, "Legacy", ('1J7mdg5rbQyUHENYdx39WVWK7fsLpEoXZy', 'A P2PKH address is the base58check encoding of version 0x00 and the HASH160 of the public key, and a compressed and an uncompressed key give two different addresses.', ("(lambda B58, a: (lambda n: (n.to_bytes(25, 'big')[0], len(n.to_bytes(25, 'big'))))(sum(B58.index(c) * 58 ** i for i, c in enumerate(a[::-1]))))('123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz', '1J7mdg5rbQyUHENYdx39WVWK7fsLpEoXZy')", '(0, 25)')), [
  (W, "A pay to public key hash address, abbreviated P2PKH, is the legacy address in which the output script commits to the HASH160 of the receiver's public key. The output script is OP_DUP OP_HASH160 <commitment> OP_EQUALVERIFY OP_CHECKSIG and the spender's input script is the signature followed by the public key [BK]. The address is the base58check encoding of the version byte 0x00 followed by the 20-byte commitment, and it therefore begins with the digit 1 [BK]."),
  (Y, "The scheme is convoluted compared with a bare public key, as the book admits, but it allows Alice's payment to Bob to contain only a 20-byte commitment to his public key instead of the key itself, which would have been 65 bytes in the original version of Bitcoin. That is a lot less data for Bob to communicate to Alice [BK]. The commitment must still be copied without error, and the book introduces base58check encoding as the answer to that problem."),
  (E, "For the book's example private key the compressed public key gives the address 1J7mdg5rbQyUHENYdx39WVWK7fsLpEoXZy and the uncompressed public key gives 1424C2F4bC9JidNjjTUZCbUxv6Sa1Mt62x. The book does not print these two strings; the chapter's checks compute them from its key, and Bitcoin Core 31.1, given the two public keys in descriptors, returns the same two addresses and reports both as valid [CORE]. A single private key therefore stands behind two different legacy addresses, a fact that the book stresses [BK]."),
  (H, "The construction takes four steps. Compute the SHA256 of the public key, compute the RIPEMD-160 of that, put the version byte 0x00 in front, and append the first four bytes of the double SHA256 of the result before writing it in base58. The leading zero byte becomes the character 1. When the address is decoded, the checksum is verified first, the version byte tells the kind, and the 20 bytes are inserted into the script template. The chapter's toolkit performs exactly these steps and its decoder returns the version 0 and the 20-byte commitment for the address."),
  (K, "An address is derived from a public key; it does not contain it, so it cannot be turned back into the key. The public key is revealed for the first time when the output is spent, and from that moment the protection of the hash is gone, which is one reason not to reuse an address. Another is that the two encodings of the key give two addresses, so a wallet that was told about only one of them will not find funds paid to the other [BK]. An address that fails its checksum is not an address at all; the wallet must refuse it."),
 ]),
 ("RedeemScript", "Redeem script", 3, "Legacy", ("a script revealed when spending", "A redeem script is the script that a P2SH output commits to by its HASH160; it is revealed in the input script when the output is spent, and nodes check its hash before running it.", ("[0x14, 0x76, 0xa9, 0x87, 0x88, 0xac]", "[20, 118, 169, 135, 136, 172]")), [
  (W, "A redeem script, also called a redemption script, is a script that an output commits to by means of its hash instead of containing it. The book describes the BIP16 upgrade of 2012, which allows an output script to commit to a redeem script; when Bob spends his bitcoins, his input script has to provide a redeem script that matches the commitment, and any data necessary to satisfy the redeem script, such as signatures [BK]. The specification of the upgrade calls the same thing the redeemScript or the serialised script [B16]."),
  (Y, "The receiver, not the payer, ought to decide what conditions govern the spending of funds. The specification states the purpose in these words: to move the responsibility for supplying the conditions to redeem a transaction from the sender of the funds to the redeemer [B16]. A script with several keys can be thousands of bytes long, and the book points out that this is not only thousands of bytes to communicate to Alice but thousands of bytes for which she would pay transaction fees each time she sends money to Bob; a short commitment avoids both [BK]."),
  (E, "Redeem scripts are met inside P2SH outputs. The book's example is a script with two conditions, one signature from Bob's desktop wallet and one from a hardware signing device: <public key 1> OP_CHECKSIGVERIFY <public key 2> OP_CHECKSIG [BK]. A hardware signing device, the book says elsewhere, is a device that securely stores private keys and signs transactions that a less secure program prepares and broadcasts; it only needs to hold keys and use them to generate signatures [BK]."),
  (H, "The commitment is made with the same mechanism as for a public key: RIPEMD160(SHA256(script)). When Bob spends, his input script contains the signatures followed by the redeem script as a single data element, in the order in which the opcodes will consume them. Full nodes verify that the serialised redeem script hashes to the same value as the commitment, replace it on the stack by its deserialised value, and execute the result [BK]. The specification adds a limit: the redeem script is an ordinary data push, so it cannot be longer than 520 bytes, which allows at most 15 compressed public keys in a multisignature script (3 bytes plus 15 keys of 34 bytes make 513) [B16]."),
  (K, "The redeem script is revealed only when the funds are spent, and in the meantime no one can tell what conditions the output carries. That is a privacy advantage and also a risk: a payer cannot check that the receiver chose a script that can in fact be satisfied. The hash must also be computed over the exact serialised bytes, since a script that differs in any byte has a different commitment."),
 ]),
 ("MultisigScript", "Multisignature script", 3, "Legacy", ('2 of 3 keys', "A multisignature script requires signatures from several keys; the opcode OP_CHECKMULTISIG checks m signatures against n public keys, as in BIP16's example of 2 of 3.", ('(lambda n: (3 + n * 34, 3 + (n + 1) * 34 > 520))(15)', '(513, True)')), [
  (W, "A multisignature script is a script that requires signatures made with more than one key before funds can be spent. The book's example requires two signatures, one from Bob's desktop wallet and one from a hardware signing device [BK]. The usual way to describe such a rule is m of n: m signatures are needed out of n public keys that are named in the script. The specification of pay to script hash gives a script of this kind with the opcode OP_CHECKMULTISIG in its example, {2 [pubkey1] [pubkey2] [pubkey3] 3 OP_CHECKMULTISIG}, which needs two of three keys [B16]."),
  (Y, "Splitting authority among keys protects against the loss or theft of any single one of them. In the book's example a thief who steals the desktop wallet still cannot spend without the hardware signing device, and with two out of three keys, as in the specification's example, the loss of any one key does not by itself lose the funds. The pay to script hash upgrade was designed so that the receiver can choose such a script without the payer having to know it [B16]."),
  (E, "The book notes that pay to script hash is not necessarily the same as a multisignature transaction: a P2SH address most often represents a multisignature script, but it might also represent a script encoding other types of transaction [BK]. In the specification the opcode OP_CHECKMULTISIG can itself accept up to 20 public keys, and when it is not immediately preceded by a small number it counts as 20 signature operations towards a block limit of 20,000 [B16]."),
  (H, "The script lists the keys, and the spender's input script supplies the signatures in the order in which the opcodes consume them. A node executes the script by checking each supplied signature against the keys. In the book's two-key example the first opcode, OP_CHECKSIGVERIFY, is a check that makes the whole script fail if its signature is wrong: the script interpreter of Bitcoin Core performs the ordinary signature check, pushes the result and then, for this opcode only, removes the result if it is true and returns the error SCRIPT_ERR_CHECKSIGVERIFY if it is false, whereas the second opcode, OP_CHECKSIG, simply leaves its result on the stack [BK] [CORE]. The chapter's checks compute the size limit that the specification states for a P2SH multisignature script of compressed keys, 15 keys and 513 bytes."),
  (K, "Multisignature is a rule about keys, not about people: if one person holds all the keys on one computer, nothing at all is gained, and if the keys are spread over devices that fail together, little is gained. It also enlarges the transaction, since each signature and each public key has to be shown when the output is spent, and the spender pays for those bytes. The limit on the size of a data push, which the previous paragraph computes, is the reason why such a script cannot name an unlimited number of keys. A last point concerns the collision attack of a following concept, which applies precisely to scripts that several parties create together, and which is the reason the newer address kinds commit to 32 bytes rather than 20."),
 ]),
 ("P2shAddress", "P2SH address", 3, "Legacy", ("3F6i6kwkevjR7AsAd4te2YB2zZyASEm1HM", "A P2SH address commits with HASH160 to a redeem script instead of a key, uses version byte 0x05 and starts with 3.", ("(lambda a: (lambda n: n.to_bytes(25, 'big')[0])(sum('123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'.index(c) * 58 ** i for i, c in enumerate(a[::-1]))))('3F6i6kwkevjR7AsAd4te2YB2zZyASEm1HM')", "5")), [
  (W, "A pay to script hash address, abbreviated P2SH, is the legacy address in which the output script commits to the HASH160 of a redeem script. The output script has a fixed template, OP_HASH160 <commitment> OP_EQUAL, and the address is the base58check encoding of the version byte 5 followed by the 20-byte commitment, which makes it begin with the digit 3 [BK]. The book's example is 3F6i6kwkevjR7AsAd4te2YB2zZyASEm1HM."),
  (Y, "P2SH gave the receiver the freedom to choose any script without troubling the payer. The payer's wallet needs only to recognise the one template and to put the commitment into it, so a wallet that has never heard of multisignature scripts can still pay one [BK]. The specification describes the benefit as allowing a sender to fund any arbitrary transaction, no matter how complicated, using a fixed-length 20-byte hash that is short enough to scan from a QR code or easily copied and pasted [B16]."),
  (E, "The book dates the upgrade to 2012, and the specification gives the details: it was a soft fork, it applied to blocks with timestamps from 1 April 2012 (1333238400 in Unix time), and miners signalled their support by putting the string /P2SH/ in the coinbase transaction of their blocks, that is in the first transaction of a block, the one that pays the block subsidy of Chapter 1 [B16]. P2SH addresses are still in use, notably for multisignature scripts and for the nested form of segregated witness that the next branch describes. Bitcoin Core 31.1 validates the book's example address and reports it as a script address [CORE]."),
  (H, "To spend, Bob's input script supplies the signatures and the serialised redeem script. Nodes first run the ordinary check, hashing the redeem script and comparing it with the commitment, and then run the redeem script on the remaining stack as if it were the output script [B16]. The chapter's checks decode the book's address and obtain the version 5 and a 20-byte hash, and they find that Bitcoin Core's script for the address begins with a9 and ends with 87, the codes of OP_HASH160 and OP_EQUAL."),
  (K, "The template must be followed exactly. The book's warning is that when using P2SH one must use the specific template with no extra data or conditions, because if the output script is not exactly OP_HASH160 followed by 20 bytes and OP_EQUAL the redeem script will not be used, and any bitcoins may be unspendable or spendable by anyone [BK]. Finally, P2PKH and P2SH are the only two script templates used with base58check encoding, and the book recommends newer address types for new wallets [BK]."),
 ]),
 ("PreimageAttack", "Preimage attack", 3, "Legacy", ("1 in 2 to the 160", "A preimage attack is finding an input for a given hash output; for a secure 160-bit function such as HASH160 an attacker that tries inputs succeeds with probability 1 in 2 to the 160 per try.", ("2 ** 160", "1461501637330902918203684832716283019655932542976")), [
  (W, "A preimage attack is an attempt to find an input that produces a given output of a hash function, that is, to open a commitment whose hidden value is unknown to the attacker. In Bitcoin terms, it means finding a public key or a script whose hash equals the commitment in an existing output. The book explains the danger: if the attacker finds the input in the same way as the original user did, they will know the user's private key and be able to spend the user's bitcoins [BK]."),
  (Y, "The attack gives a way to measure the safety of a short commitment. For a secure hash function of 160 bits such as HASH160 the book states the probability as 1 in 2 to the 160 [BK], which is a number with 49 digits. An attacker's chance of finding an input by trying is proportional to the number of attempts divided by that number, so the only way to make the attack practical would be a weakness in the function itself."),
  (E, "The attack is the one that people usually have in mind when they ask whether somebody can guess their address's key. The commitments of the address kinds of this chapter are protected against it by the size of the hash output: the legacy kinds and the witness public key hash kind by 160 bits, the witness script hash kind by 256 bits [BK], and a taproot output holds a point and no hash at all. It is also what the commitment game of the book relies on: the answerer cannot change the answer after the hash is published, nor can the questioner reconstruct the answer from the hash unless the set of possible answers is small [BK]."),
  (H, "The cost grows by a factor of two for every added bit. The chapter's checks print 2 to the 160 in decimal, with its 49 digits, and compare it with the 2 to the 80 hashes per hour that the book attributes to all Bitcoin miners combined in early 2023: even the whole network would need 2 to the 80 hours at that rate, which is more than 10 to the 20 years. The comparison uses the book's figure; the miners run a different hash function, so their hardware cannot be turned to this task [BK]."),
  (K, "Resistance to a preimage attack is the strongest of the three hash properties that this chapter uses, and it is not the one in danger. The attacks that justify the book's recommendation to use newer addresses are the second preimage attack and the collision attack, in which the attacker has more freedom. A reader should not take the safety of a preimage attack as a statement about the safety of the whole scheme."),
 ]),
 ("SecondPreimageAttack", "Second preimage attack", 3, "Legacy", ("a different input, same hash", "A second preimage attack is finding a different input that gives the same hash as a given input; for addresses created entirely by one party the chance is again about 1 in 2 to the 160 for HASH160.", ("float(1 / 2 ** 160)", "6.842277657836021e-49")), [
  (W, "A second preimage attack is an attempt to find, for a given input, a different input that produces the same hash output. The book considers the attacker who tries to generate two different inputs, for example two redeem scripts, that produce the same commitment, and states that for addresses created entirely by a single party the chance of generating a different input for an existing commitment is also about 1 in 2 to the 160 for the HASH160 algorithm [BK]."),
  (Y, "The attack matters because a commitment is supposed to bind its author to one value. If a second input with the same hash could be found for a given first one, then the author of the commitment would not be bound by it, and an output committing to a script could be spent with another script. For addresses made by one honest party the attack is as hard as the preimage attack, which is why P2SH is considered safe in that case."),
  (E, "The distinction between the cases is the one made in the book's box about P2SH collision attacks. When all the inputs are produced by a single party that acts honestly, the attack is a second preimage attack, with a probability of 1 in 2 to the 160. When the attacker takes part in producing the input, the situation is different, as the next concept explains [BK]."),
  (H, "The estimate can be reasoned in one line. A hash output has 2 to the 160 possible values; for one fixed input, a random different input hits the same value with probability one in that number. The chapter's checks show that the figure equals that of the preimage attack. The case is exactly like the preimage attack for an attacker who sees only the commitment, and the main difference is the starting knowledge: the attacker has the original input, but has no more help in finding a second one."),
  (K, "The two attacks are often confused. In a preimage attack the attacker knows only the output; in a second preimage attack the attacker also knows one input; and in a collision attack, described next, the attacker may choose both inputs. The first two cost about 2 to the 160 hash computations for HASH160; the third costs about the square root of that, and that is the whole reason why attention is paid to who creates the inputs."),
 ]),
 ("CollisionAttack", "Collision attack", 3, "Legacy", ("1 in 2 to the 80", "A collision attack is finding any two inputs with the same hash; because the attacker chooses both, the work is only about the square root of the output space, 2 to the 80 for HASH160, which is why newer addresses use 256-bit commitments.", ("(2 ** 160) ** 0.5 == 2 ** 80", "True")), [
  (W, "A collision attack is an attempt to find two different inputs that produce the same hash output, with no requirement that either of them be fixed in advance. The book applies it to P2SH: all addresses based on hash functions are theoretically vulnerable, but the position changes when an attacker is able to influence the original input value, for example when the attacker takes part in the creation of a multisignature script and does not need to submit their public key until after they have learned all the others [BK]. In that case the strength of the hash algorithm is reduced to its square root, and for HASH160 the probability becomes 1 in 2 to the 80 [BK]."),
  (Y, "The attack matters because the freedom to choose both inputs makes the work far smaller. The attacker prepares two scripts, one honest-looking and one that sends the money to the attacker, such that both have the same hash. The honest partners commit to the first; later the attacker spends with the second. The book explains why the case is realistic: there are organisations that expect to receive billions of dollars in bitcoins to addresses generated by processes involving multiple parties, and that could make the attack profitable [BK]."),
  (E, "The book gives a sense of scale. As of early 2023, it says, all Bitcoin miners combined execute about 2 to the 80 hash functions every hour; they run a different hash function than HASH160, so their existing hardware cannot mount a collision attack on it, but the existence of the network proves that collision attacks against 160-bit functions are practical [BK]. The chapter's checks recompute the book's comparison and find that 2 to the 128 hash operations, the strength of the newer commitments, would take that network about 32 billion years."),
  (H, "The square-root effect comes from the birthday problem: among a number of random values, a match between two of them appears far sooner than one would think, once about the square root of the number of possible values has been generated. The chapter's checks show it on a hash cut down to its first 32 bits, which has 2 to the 32 possible values: hashing the numbers 0, 1, 2 and so on, the first repeated value appears at the number 95303, close to the 2 to the 16, that is 65536, that the square root predicts, and not near the four billion that a search for a given value would need. A secure 256-bit hash therefore offers 128 bits of collision resistance, and a 160-bit hash only 80. The book states the remedy plainly: there are well-established cryptographic protocols for preventing collision attacks, but a simple solution that requires no special knowledge on the part of wallet developers is to use a stronger hash function, and later upgrades to Bitcoin made that possible, so that newer addresses provide at least 128 bits of collision resistance [BK]."),
  (K, "The book's figures date from early 2023. A third party's estimate of how many hash computations the whole network performs, read on 28 September 2026 for this chapter, gives about 2.8 times the book's figure for an hour, and with that number 2 to the 128 operations would take about 11 billion years instead of 32 billion [HR]. The conclusion does not change: the book shows that 2 to the 80 operations are within reach of an operation the size of the Bitcoin network, and 2 to the 128 are not. The book adds that it does not believe there is an immediate threat to anyone creating new P2SH addresses, and recommends newer address types so that collision attacks need not be a concern [BK]."),
 ]),
]
