"""SEN0401 chapter 4, corpus text part F (version 1.1.0): practice today (address types, key export, passphrase protection, deterministic wallets, address reuse,
vanity addresses, paper wallets, hardware signing devices), assurance (test vectors, cross-checking) and the semantic link to identifiers.
Markers such as [BK] are replaced by author-year strings in sen0401_ch04_corpus_v1_1_0.py. The first element of every paragraph tuple is
only the author's writing guide and is not printed."""
from sen0401_ch04_text_a_v1_1_0 import W, Y, E, H, K, KHEX, NHEX, YHEX
B58LIT = "'123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'"
def B58C(payload_expr):
    """an expression: the base58check text of the bytes payload_expr (no leading zero byte)"""
    return ("(lambda h, d: (lambda n: ''.join(" + B58LIT + "[n // 58 ** i % 58] for i in range(70)[::-1]).lstrip('1'))(int.from_bytes(d + h(h(d).digest()).digest()[:4], 'big')))(__import__('hashlib').sha256, " + payload_expr + ")")
BIP38_MIN = "6PRHv1jg1ytiE4kT2QtrUz8gEjMQghZDWg1FuxjdYDzjUkcJeGdFj9q9Vi"

NODES_F = [
 ("Practice", None, 1, None, None, [
  (W, "This branch asks what a user or a developer should do with the material of the earlier branches today. The chapter ends with advanced keys and addresses, vanity addresses and paper wallets, and it surrounds them with remarks about how practice has changed since the first Bitcoin software. The branch collects those remarks together with the current behaviour of Bitcoin Core, which was run for this chapter, and with the way in which implementers can convince themselves that their address code is correct."),
  (Y, "A chapter of a book is a snapshot, and software moves on. The book says of private key formats that the information is mainly of interest to anyone needing compatibility with early Bitcoin wallets, because modern wallets generate all their keys from one seed [BK]. A student who learns only the formats of the early years may look for features that current software has removed. The branch therefore compares what the book says with what a recent release of Bitcoin Core does, and where they differ it says so."),
  (E, "The material is met by anyone who installs a wallet, restores a backup, imports an old key or writes software that pays addresses. Chapter 3 described how to obtain, verify and run Bitcoin Core and its interface; this chapter used a release of it, version 31.1, as an independent authority on addresses, by asking it to derive and to validate every address that the book prints."),
  (H, "Two levels organise the branch. The first, practice now, covers the default address type of a current wallet, the export of single keys, the protection of a key with a passphrase, the deterministic wallet that has replaced single keys, the privacy cost of reusing an address, the vanity address, the paper wallet and the hardware device that has replaced it. The second level, assurance, covers the test vectors of the standards and the habit of checking an implementation against independent software."),
  (K, "Practice is not static. A statement of the form wallets do X is true of some wallets at some date; the dates attached to the sources in this chapter, a book of 2023 and software of 2026, are part of the information. Where a source and the software disagree, the software of the date is the better witness to what happens now, and the source the better witness to what its authors intended."),
 ], None),
 ("Modern", "Practice now", 2, "Practice", None, [
  (W, "Practice now means the behaviour of current wallets and the advice of the book's third edition. It covers which address a wallet gives out, whether a wallet still lets a user take a single key out of it, how keys are protected, and which of the curiosities of the early years, vanity addresses and paper wallets, are still sensible. The book is blunt about several of them, calling paper wallets obsolete and dangerous and observing that vanity addresses have almost entirely disappeared [BK]."),
  (Y, "Learning the current practice protects against mistakes that came from earlier habits. The old way of keeping bitcoins, one key per address, each backed up on paper or in a file, led to lost keys and to leaked keys. The modern way derives all the keys of a wallet from a single seed, which can be backed up once, and this changes what exporting a key, protecting a key and printing a key mean."),
  (H, "The eight concepts of the level move from the wallet outward. The default address type and the export of a single key say what current software offers. Passphrase protection, the deterministic wallet and address reuse explain the surrounding security and privacy ideas. The vanity address, the paper wallet and the hardware signing device are three ways of obtaining or keeping a key, one of them fashionable in the early years and abandoned, one obsolete, and one recommended."),
  (K, "A recommendation in this level is the authors' judgement at a date, and the book frames them so: the paper wallet section is a warning rather than a procedure, and the section on key formats says in its own words that it is mainly of interest to anyone needing compatibility with early wallets. The reader should keep the facts apart from the opinions and should check the date of any advice before acting on it. The facts of this level are of two kinds, and they age differently: what a document says, which stays true of that document for ever, and what a program does, which is true of one release on one day."),
 ], None),
 ("DefaultAddressType", "Default address type", 3, "Modern", ("bech32 by default, bech32m on request", "Bitcoin Core's addresstype option defaults to bech32, a P2WPKH address, and the four types are legacy, p2sh-segwit, bech32 and bech32m, the last a taproot address.", ("['legacy', 'p2sh-segwit', 'bech32', 'bech32m'].index('bech32')", "2")), [
  (W, "The default address type is the kind of address that a wallet gives out when the user does not ask for another. In Bitcoin Core it is controlled by the option addresstype, whose help text lists the possible values as legacy, p2sh-segwit, bech32 and bech32m, with the default bech32 [CORE]. The command getnewaddress accepts the same four values as its address type argument, and its default is whatever the option sets [CORE]."),
  (Y, "A default shapes what most users do. The default of the reference implementation tells the whole ecosystem which address format is regarded as current, and the book supports the choice when it calls bech32m the current recommended address format for wallets [BK]. Defaults also matter for compatibility: a payer's wallet must be able to pay whatever kind the receiver's wallet hands out."),
  (E, "The chapter's evidence is a run of Bitcoin Core 31.1 as an offline node with a new wallet. The default address was a bech32 address, a P2WPKH output of witness version 0; asking for the types legacy, p2sh-segwit, bech32 and bech32m produced a P2PKH address, a P2SH address of a P2WPKH script, a P2WPKH address, and a P2TR address of witness version 1 [CORE]. The first three names correspond to the kinds of this chapter that carry a single key, and the fourth, as the name says, uses bech32m."),
  (H, "The wallet reports the kind of each address through its descriptor, the output descriptor of Chapter 3: wpkh for the default and the bech32 type, pkh for the legacy type, sh for the nested type, and tr for the bech32m type [CORE]. The chapter's checks read these facts from the saved output of the run and also test the book's claim about the version numbers, finding witness version 0 for the first two segwit kinds and 1 for the taproot kind."),
  (K, "A default is not a rule. Another wallet may default to another kind, and the choice of the kind of address for a payment belongs to the receiver, who makes it known by the address itself; a payer never chooses it. A default also says nothing about which kinds a wallet can pay, which is a separate question and the one that decided the design of bech32. Note finally that the evidence here concerns one release on one date, release 31.1 as it was run for this chapter, while the book was printed in 2023 and describes the practice of that year."),
 ]),
 ("KeyExport", "Exporting a single key", 3, "Modern", ("no dumpprivkey any more", "Deterministic descriptor wallets no longer export single keys, and Bitcoin Core removed dumpprivkey and importprivkey in 30.0, while a WIF key can still be used inside a descriptor.", ("(lambda present, removed: sorted(set(present) - set(removed)))(['getnewaddress', 'dumpprivkey', 'importdescriptors', 'importprivkey'], ['dumpprivkey', 'importprivkey'])", "['getnewaddress', 'importdescriptors']")), [
  (W, "Exporting a single key means taking one private key out of a wallet, usually as a wallet import format string, so that it can be put into another wallet. It was an everyday operation of the early wallets, which held independent keys, and Bitcoin Core offered the commands dumpprivkey to export a key and importprivkey to import one. The book says that almost no modern wallets support the ability to export or import an individual key [BK]."),
  (Y, "The reason is the deterministic wallet. The book explains that if a user exports a single private key from such a wallet and an attacker obtains that key together with some nonprivate data about the wallet, the attacker can potentially derive any private key in the wallet, which allows the theft of all the funds; and that keys cannot be imported into deterministic wallets at all [BK]. The operation that was routine for independent keys is dangerous and often impossible for derived ones."),
  (E, "Bitcoin Core followed the change. The release notes of version 30.0 state that BDB legacy wallets, that is the ones kept in a Berkeley DB file, can no longer be created or loaded and list among the removed legacy-only commands dumpprivkey, importprivkey, dumpwallet and importmulti [CORE]. In the chapter's run of release 31.1 the help for both dumpprivkey and importprivkey answered unknown command [CORE]."),
  (H, "A key can still be brought in through the descriptor interface. The command importdescriptors imports descriptors, and the help text warns that it triggers a rescan of the blockchain and requires a new wallet backup [CORE]. A descriptor can contain a wallet import format string: given the descriptors pkh and wpkh with the book's WIF strings, Bitcoin Core returned the P2PKH addresses 1424C2F4bC9JidNjjTUZCbUxv6Sa1Mt62x for the uncompressed string and 1J7mdg5rbQyUHENYdx39WVWK7fsLpEoXZy for the compressed one, and the P2WPKH address bc1qh0q7g23e6pdye3sh2ttfvwmld8gfhvnmmfxuck, the addresses that the chapter computes by hand [CORE]."),
  (K, "The course material that accompanies this chapter describes the earlier workflow: to ask the node to expose a private key one used the dumpprivkey command, and its example prints the address 1J7mdg5rbQyUHENYdx39WVWK7fsLpEoXZy from getnewaddress and then the compressed wallet import format string of that address from dumpprivkey [AL]. That workflow no longer works in a current Bitcoin Core, though the first command is still present [CORE]. A key that has been exported, even by a legacy wallet that still allows it, is a copy of the secret and must be treated like the secret itself; the loss of control of the copy is the loss of control of the funds."),
 ]),
 ("PassphraseProtection", "Passphrase-protected key", 3, "Modern", ("BIP38 and the prefix 6P", "BIP38 encrypts a private key under a passphrase into a 58-character base58check string starting with 6P; the BIPs repository lists it as Deployed with the comment summary Unanimously Discourage for implementation, and the 3rd edition does not cover it.", ("(lambda s: (len(s), s[:2]))('6PRHv1jg1ytiE4kT2QtrUz8gEjMQghZDWg1FuxjdYDzjUkcJeGdFj9q9Vi')", "(58, '6P')")), [
  (W, "Passphrase protection is the encryption of a private key under a passphrase, a secret phrase chosen by the owner, so that the key can be stored or printed without being usable by whoever finds it. BIP38 specifies how: it proposes a method of encrypting and encoding a passphrase-protected private key record as a 58-character base58check string [B38]. The record contains everything needed to reconstitute the private key except the passphrase."),
  (Y, "The proposal was written for paper wallets and physical bitcoins. Its motivation is a two-factor arrangement, something you have plus something you know: a person holding the printed record cannot spend without the passphrase, and the passphrase can be sent through another channel, for instance the telephone, while the record goes by post [B38]. The third edition of the book does not cover the format at all, whereas the course material that accompanies this chapter, written on the second edition, presents it: there BIP38 is described as a common standard for encrypting private keys with a passphrase and encoding them with base58check, so that they can be stored on backup media or transported between wallets, with the Advanced Encryption Standard named as the cipher [AL]."),
  (E, "The BIPs repository gives BIP38 the status Deployed, yet the summary of the comments on it reads Unanimously Discourage for implementation [B38]. The two statements are compatible: the format exists and is in use, and those who commented advise against building it into new software. The format is therefore of interest for old paper wallets and encrypted keys that someone may still hold."),
  (H, "The encryption uses three tools. The passphrase is stretched into a key by scrypt, a key derivation function that is deliberately slow and memory-hungry in order to resist brute-force attacks. The 32-byte private key is then encrypted with AES, a widely used block cipher, in two halves of 16 bytes. The first four bytes of the double SHA256 of the Bitcoin address serve as a salt for scrypt and as a check that the passphrase was right [B38]. The result is encoded in base58check with the 2-byte prefix 0x0142 for a record without EC multiplication, followed by 37 further bytes; the specification publishes the first and the last of the 2 to the 296 possible strings of each kind, and the chapter's checks reproduce the first, 6PRHv1jg1ytiE4kT2QtrUz8gEjMQghZDWg1FuxjdYDzjUkcJeGdFj9q9Vi, from the bytes 01 42 C0 and thirty-six zeros with the base58check procedure of the toolkit."),
  (K, "A passphrase adds protection only if it is not guessable, and the scrypt step only slows a guesser down; it does not stop one. The extra factor also adds a new way to lose funds: forget the passphrase, and the key is gone. As the book asks readers to use a recovery code and a hardware signing device instead of printed keys, the format is mainly a matter of compatibility [BK]."),
 ]),
 ("DeterministicWallet", "Deterministic wallet and seed", 3, "Modern", ("one seed, all the keys", "A deterministic wallet derives all its private keys from a single seed, a random value, by a repeatable procedure, so one backup covers every key; the book's example derives three keys by hashing the seed with 0, 1 and 2.", ("__import__('hashlib').sha256(b'f1cc3bc03ef51cb43ee7844460fa5049e779e7425a6349c8e89dfbb0fd97bb73 + 0\\n').hexdigest()[:8]", "'50b18e0b'")), [
  (W, "A deterministic wallet is a wallet whose private keys are all derived from a single random value, called the seed, by a procedure that always gives the same results for the same seed. The book of this course shows the idea with a hash function: if the seed is hashed together with the numbers 0, 1 and 2, three seemingly random values come out, and using the same hash function with the same seed always gives the same values [BK]. The book says that a user of deterministic key generation can back up every key in the wallet by simply recording the seed and a reference to the algorithm used [BK]."),
  (Y, "The earlier arrangement, in which a wallet generated independent keys, needed a new backup every time a new key was generated or imported. The fourth chapter's section on key formats says that later wallets began to use deterministic wallets, which only ever need to be backed up once for typical use on the blockchain [BK]. This is also why Chapter 1's recovery code can be a short list of words: it encodes the seed from which everything else follows."),
  (E, "Almost all current wallets are of this type. The consequences for this chapter are the ones that the book draws: a single exported key can endanger the others, keys cannot be imported, and a vanity address, which comes from a separate search, does not fit into the scheme unless the user backs up additional data for it [BK]. The more elaborate hierarchical form, with a tree of keys derived from one seed, is the subject of the next chapter."),
  (H, "The book's own demonstration reproduces exactly. The seed is the hexadecimal text f1cc3bc0 and so on, the derived values are the SHA256 of the text 'seed + i' with a line break, and the three results begin 50b18e0b, a965dbcd and 19580c97. The chapter's checks recompute them with the hash function of the standard library. Real wallets use a stronger and more structured derivation than a bare hash, but the principle is the same: the keys are a function of the seed, so protecting the seed protects the keys, and losing the seed loses them [BK]."),
  (K, "The seed is a single point of failure in both directions: whoever obtains it can generate every private key and steal all the funds, and whoever loses it loses them all. The book says exactly that of the seed and its recovery code: someone else who gets the seed can generate all of the private keys [BK]. A reader should therefore keep the idea of the deterministic wallet apart from the idea of backup: derivation makes the backup short, but it does not make it safe."),
 ]),
 ("AddressReuse", "Address reuse and privacy", 3, "Modern", ("one address, many payments", "Receiving several payments to the same address links them all together for anyone looking at the blockchain, which reduces the privacy of everyone who pays or is paid by that address.", ("(lambda reused, fresh: (len(set(reused)), len(set(fresh))))(['bc1qh0q7g23e6pdye3sh2ttfvwmld8gfhvnmmfxuck'] * 3, ['bc1qaaa', 'bc1qbbb', 'bc1qccc'])", '(1, 3)')), [
  (W, "Address reuse is the practice of receiving more than one payment to the same address. Because all the transactions are public, every payment to an address is visible together with every other payment to it. The book makes the point about vanity addresses: using a vanity address to receive multiple payments to the same address creates a link between all of those payments [BK]."),
  (Y, "The link matters for people other than the receiver. The book gives two small stories: Alice may want to donate anonymously, and Bob may not want his other customers to know that he gives discount pricing to the charity [BK]. The same reasoning stands behind the first design of Bitcoin, in which the receiver's node supplied a new public key that it had never previously given anyone, so that different payments to Bob could not be connected by someone looking at the blockchain [BK]."),
  (E, "Wallets avoid the problem by giving a new address for every payment, which is cheap when all the keys derive from one seed. The default behaviour of Bitcoin Core's command getnewaddress is exactly that: a new address on every call [CORE]. Reuse is still met when a person publishes one address on a website or a poster, and with the vanity address, whose point is to be recognised."),
  (H, "The link is created by the observer, not by the protocol. Anyone can scan the blockchain for outputs to the same address and list the payments, the amounts and the dates. A fresh address splits the history into pieces that have nothing visible in common. The chapter's checks illustrate the principle with a set: three payments to one address give one distinct address, three payments to three addresses give three."),
  (K, "A fresh address for each payment does not give anonymity by itself, and the book is careful in its claims: it says that the reuse of a vanity address reduces privacy, not that avoiding reuse guarantees it. Reuse may be acceptable when a link is wanted anyway, as the book remarks for a non-profit that reports its income and expenditure to a tax authority [BK]. The public key behind an address is also exposed when the address is first spent from, which gives one more reason to treat each address as single-use."),
 ]),
 ("VanityAddress", "Vanity address", 3, "Modern", ("1Kids and 58 to the fourth", "A vanity address starts with a chosen string found by trying keys one after another, and each further character multiplies the work by 58, so four characters take 58 to the fourth, about 11 million keys.", ("58**4", "11316496")), [
  (W, "A vanity address is a valid Bitcoin address that contains a human-readable message, such as the address 1LoveBPzzD72PUXLzCkYAtGFYmK5vYNR33 of the book, whose first four base58 letters after the digit 1 spell Love [BK]. Such addresses are not designed but searched for: the process picks a private key at random, derives the public key and the address, checks whether it matches the wanted pattern, and repeats billions of times until a match is found [BK]."),
  (Y, "The attraction is recognition; the book's example is a children's charity that wants an address beginning 1Kids to publicise a fundraising drive. The cost is computing time. The book is clear that the result is no less and no more secure than any other address: the key that was found spends the funds like any key, it depends on the same elliptic curve cryptography and the same secure hash algorithm, and one cannot find the private key of a vanity address more easily than that of another [BK]."),
  (E, "The book reports that vanity addresses were popular in the early years of Bitcoin but have almost entirely disappeared from use as of 2023, and it names two likely causes. Deterministic wallets make it impossible to use a vanity address unless the user backs up additional data for each one, and most such wallets do not allow the import of a key from a vanity generator. And address reuse, which a vanity address invites, reduces privacy [BK]. A vanity pool is a service that lets those with fast hardware earn bitcoin searching for vanity addresses for others [BK]."),
  (H, "The book counts the work. An address with the prefix 1Kids lies in a range of about 58 to the 29, that is 1.4 times 10 to the 51, addresses; each further character of the pattern makes the pattern 58 times rarer, so that the frequencies run 1 in 58, 1 in 3,364 and 1 in 195,000 for patterns of one, two and three characters after the 1, and 1 in 11 million for four [BK]. The chapter's checks recompute these powers of 58 for one to eleven characters. They also run a real, small search, counting private keys upwards from 1: the first key whose compressed P2PKH address begins with 1Ki is the number 1666, and the first that begins with 1Kid is the number 8810. The number of tries depends on luck, and these are far below the averages."),
  (K, "The search is a brute-force one and it multiplies its cost by 58 for every character, so long patterns are out of reach: the book says that a pattern such as 1KidsCharity would take 2.5 million years on a desktop computer. Its table of times follows its own rule, half the frequency divided by 100,000 keys a second, up to patterns of seven characters, but for eight and more characters the book's times are about a third shorter than the rule gives, and its frequency for eleven characters, 23 quintillion, should be 25 quintillion according to the powers of 58, as the chapter's checks show. The examples that this chapter found, with keys 1666 and 8810, also give a warning: a key found by counting upwards from 1 is not secret at all, and a real search must draw its candidate keys at random."),
 ]),
 ("PaperWallet", "Paper wallet", 3, "Modern", ("a private key on paper", "A paper wallet is a private key printed on paper, which the 3rd edition calls an obsolete technology and dangerous for most users.", ("(lambda k: (len(k), len(bytes.fromhex(k))))('1E99423A4ED27608A15A2616A2B0E9E52CED330AC530EDCC32C8FFC6A526AEDD')", '(64, 32)')), [
  (W, "A paper wallet is a private key printed on paper, often together with the corresponding Bitcoin address for convenience, though this is not necessary, because the address can be derived from the private key [BK]. The book shows a sample and describes many designs: some for gifts, with seasonal themes; some for storage in a bank vault with the key hidden by a scratch-off sticker or by tamper-proof foil; some with detachable stubs that allow several copies to be kept against fire or flood [BK]."),
  (Y, "A wallet on paper was an answer to the question of how to keep a key away from computers that can be attacked. The book now declares the answer wrong. Paper wallets are an obsolete technology and dangerous for most users, there are many subtle pitfalls in generating them, not least that the generating code might be compromised with a back door, and many bitcoins have been stolen in this way; they are shown for informational purposes only and should not be used for storing bitcoin [BK]."),
  (E, "The book recommends the alternative in the same warning: use a recovery code to back up the keys, possibly with a hardware signing device to store keys and sign transactions [BK]. A paper wallet is met mainly in old gifts and old backups, and the reader who finds one should treat the printed key like any other private key, in the format described by the wallet import format."),
  (H, "A paper wallet has to be generated by software, which chooses the random number and prints the key; the worked example counts what then has to be printed and kept safe, namely 64 hexadecimal digits, which are the 32 bytes of the private key. The security of the paper therefore depends first on that software and on the randomness it used, the issue of the earlier concepts on randomness, and only afterwards on where the paper is kept. Two risks follow: the software is not trusted, and the paper, once read or photographed, is a complete copy of the secret."),
  (K, "The recommendation against paper wallets is a statement about generation and about the format of a single static key, and not about writing things on paper: the recovery code of a modern wallet is routinely written on paper, and the book proposes exactly this. The difference is that a recovery code can regenerate a whole wallet from a trustworthy device, and a paper wallet is one key produced by a program whose trustworthiness the owner cannot check."),
 ]),
 ("HardwareSigningDevice", "Hardware signing device", 3, "Modern", ("keys that never leave the device", "A hardware signing device holds private keys and uses them only to sign; a less secure program prepares the transaction and broadcasts it, so the keys never meet general-purpose software.", ("(lambda steps: (steps.index('sign'), 'private key' in steps))(['prepare', 'sign', 'broadcast'])", '(1, False)')), [
  (W, "A hardware signing device is a small device whose only job is to hold private keys and to use them to generate signatures. The book of this course describes it in the chapter on wallets: Alice gives a hardware signing device, sometimes confusingly called a hardware wallet, the key tweaks she needs, the device derives the child private keys and signs the transaction, and it returns the signed transaction to the less secure frontend for broadcast to the network [BK]."),
  (Y, "A computer or phone runs a great deal of software of unknown quality, and a key that is held there can be stolen by it. Another chapter of the book states the idea in general terms: unlike a smartphone or desktop computer, a hardware signing device only needs to hold keys and use them to generate signatures, and without general-purpose software to compromise and with limited interfaces such devices can deliver strong security to nonexpert users [BK]. It adds that they may become the predominant method of storing bitcoins [BK]."),
  (E, "This chapter meets the device twice. The multisignature example of P2SH, a signature from Bob's desktop wallet and one from a hardware signing device, shows it as one of the keys of a script, and the warning against paper wallets recommends it, with a recovery code, as the replacement [BK]. The device is therefore a place where keys are kept, and not a new kind of address."),
  (H, "The division of labour is the point. The frontend, which can be an ordinary program, builds the transaction and shows it; the device checks it, signs it with the key it keeps inside and sends back only the signature. The worked example names the three steps in order and asks whether the private key is among them, and it is not: preparing and broadcasting happen outside the device, signing inside it, and the key never appears in the list of things that cross the boundary. Since a signature does not reveal the private key, the key is never exposed to the frontend, however compromised the frontend is [BK]. The device still needs the secret to be backed up, so a recovery code, as the book says, goes with it."),
  (K, "A hardware signing device is not magic. It protects keys from software on the computer, not from loss, so the recovery code must still be kept, and not from the owner's own mistakes, such as signing a transaction that pays the wrong address. The name hardware wallet is called confusing by the book because the device does not hold coins; it holds keys [BK]."),
 ]),
 ("Assurance", "Assurance", 2, "Practice", None, [
  (W, "Assurance is the confidence that an implementation does what the standard says. In a payment system an implementation error is not a minor bug: an address decoder that accepts a string it should reject, or encodes a program wrongly, sends money to a place from which it cannot be recovered. This level of the chapter covers the two means that the chapter itself uses to obtain assurance, the published test vectors of the address standards and the comparison of independent implementations."),
  (Y, "The book asks directly for such assurance. When implementing bech32m encoding or decoding, it says, use the test vectors provided in BIP350, and make sure the code passes the vectors for paying future segwit versions that have not yet been defined, so that the software remains usable for many years [BK]. The specification itself explains why: experiments on implementations of the earlier format found that many wallets and services did not support sending to higher-version outputs [B350]."),
  (H, "Two concepts follow. The test vectors are examples with known right answers, published with the specification. The cross-check is the comparison of the results of several implementations written by different people, with each other and with the numbers printed in the book. Both rest on the same idea: a claim about software is worth what the evidence for it is worth, and evidence from independent sources is worth more than evidence from one."),
 ], None),
 ("TestVectors", "BIP350 test vectors", 3, "Assurance", ("BIP350's list of valid and invalid addresses", "The BIP350 test vectors give valid and invalid segwit addresses and bech32m strings against which any bech32m implementation should be run, including those for future witness versions.", ("(lambda b32m, valid, invalid: (len(b32m), len(valid), len(invalid)))(['A1LQFN3A', 'a1lqfn3a', 'an83characterlonghumanreadablepartthatcontainsthetheexcludedcharactersbioandnumber11sg7hg6', 'abcdef1l7aum6echk45nj3s0wdvt2fg8x9yrzpqzd3ryx', '11llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllludsr8', 'split1checkupstagehandshakeupstreamerranterredcaperredlc445v', '?1v759aa'], ['BC1QW508D6QEJXTDG4Y5R3ZARVARY0C5XW7KV8F3T4', 'tb1qrp33g0q5c5txsp9arysrx4k6zdkfs4nce4xj0gdcccefvpysxf3q0sl5k7', 'bc1pw508d6qejxtdg4y5r3zarvary0c5xw7kw508d6qejxtdg4y5r3zarvary0c5xw7kt5nd6y', 'BC1SW50QGDZ25J', 'bc1zw508d6qejxtdg4y5r3zarvaryvaxxpcs', 'tb1qqqqqp399et2xygdj5xreqhjjvcmzhxw4aywxecjdzew6hylgvsesrxh6hy', 'tb1pqqqqp399et2xygdj5xreqhjjvcmzhxw4aywxecjdzew6hylgvsesf3hn0c', 'bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqzk5jj0'], ['Invalid human-readable part', 'Invalid checksum: bech32 for v1', 'Invalid checksum: bech32 for v1 again', 'Invalid checksum: bech32 for v16', 'Invalid checksum: bech32m for v0', 'Invalid checksum: bech32m for v0 again', 'Invalid character in checksum', 'Invalid witness version', 'Invalid program length (1 byte)', 'Invalid program length (41 bytes)', 'Invalid program length for witness version 0', 'Mixed case', 'Zero padding of more than 4 bits', 'Non-zero padding in the 8-to-5 conversion', 'Empty data section'])", '(7, 8, 15)')), [
  (W, "A test vector is an input together with the output that a correct implementation must give, published so that implementers can check their work. BIP350 publishes three groups: valid bech32m strings, invalid bech32m strings with the reason for the invalidity, and valid and invalid segwit addresses of versions 0 to 16, the valid ones with the output script that they translate to [B350]. The chapter's checks count seven valid bech32m strings, eight valid segwit addresses and fifteen invalid ones."),
  (Y, "Vectors capture the cases that implementers forget. The invalid list contains an address with the wrong human-readable part, a checksum of the wrong kind for the version, a version out of range, a program that is too short or too long, mixed case, and padding errors, each with the reason. The valid list contains addresses of the versions that did not yet exist, so that wallets are forward-compatible. The specification says that all higher versions of native segwit outputs should be recognised as valid recipients, while no wallet should ever create them [B350]."),
  (E, "The book recommends the vectors twice, once for the encoding rules and once for the future versions [BK]. The chapter's own toolkit was run against them, and it accepted all eight valid addresses with the right scripts and rejected all fifteen invalid ones, as did the reference implementation that the book uses. This is the kind of evidence the book asks implementers to produce."),
  (H, "A vector test is a loop. For each valid address the decoder must return the stated witness version and program, and re-encoding must give the same address in lowercase; for each invalid address it must refuse. The checks of this chapter read the vectors from the saved text of the specification, parse the groups and run the toolkit's decoder on each; they also confirm that none of the bech32m strings is accepted when read as bech32 [B350]."),
  (K, "Passing the vectors is necessary but not sufficient: they sample the space of inputs and do not cover it. A decoder that passes can still contain a bug for a case that none of the vectors tries, so vectors should be combined with the other checks of the next concept, and with careful reading of the specification."),
 ]),
 ("IndependentCheck", "Cross-checking with independent software", 3, "Assurance", ("three sources, one answer", "Cross-checking compares the results of independent implementations on the same input; this chapter compares its own toolkit with Bitcoin Core 31.1 and with the book's reference code, and finds the same addresses.", ("(lambda answers: (len(set(answers)), len(set(answers)) == 1))(['1J7mdg5rbQyUHENYdx39WVWK7fsLpEoXZy', '1J7mdg5rbQyUHENYdx39WVWK7fsLpEoXZy', '1J7mdg5rbQyUHENYdx39WVWK7fsLpEoXZy'])", '(1, True)')), [
  (W, "Cross-checking is the comparison of the results of independent implementations on the same inputs. If a toolkit written by one person and a program written by others, without sharing code, give the same answer for many inputs, the chance that both have the same error is much smaller than the chance that one has an error. The chapter applies the method to its main example: the private key of the book, with its public key, its two P2PKH addresses and its two WIF strings."),
  (Y, "The method is the way in which trust is built in this field, by checking that several independent implementations agree and not by believing one. The book itself relies on it when it advises readers not to write their own code for random numbers, and the specifications publish reference implementations, so that others can compare. Where an implementation is for teaching, as the toolkit of this chapter is, the comparison is the only reason to believe its output."),
  (E, "Three sources were compared. The toolkit of the chapter, written for reading in plain Python, computed the public key, the two addresses and the two WIF strings of the book's key. Bitcoin Core 31.1, given the public keys and the WIF strings in descriptors, returned the same two P2PKH addresses and a P2WPKH address, and validated every address that the chapter prints [CORE]. The reference implementation of bech32 that the book itself uses produced the same four segwit addresses as the toolkit."),
  (H, "The procedure is simple. Fix the inputs, in this case the 64 hexadecimal digits of the key; run each implementation; compare outputs exactly, character by character. Disagreement points to an error in at least one of them. The chapter's checks recompute the toolkit's outputs and compare them with the saved output of Bitcoin Core, and they check the error positions that Core reports against the positions at which the typed string differs from the correct address."),
  (K, "Agreement shows that the results are the same, not that they are right: two programs can agree on a mistake if they share a source of error, such as a misreading of the same specification. The comparison also covers only the inputs tried. The chapter's differences from the book, such as the statement about the origin of secp256k1 and the figures of the vanity table, were found by comparing the book with primary sources, which is a cross-check of another kind."),
 ]),
 ("Semantics", None, 1, None, None, [
  (W, "This branch links the chapter to the theme of the course on identity and semantics. A key pair, as the chapter has described it, is more than a means of paying: it is an identifier whose holder can prove control without asking anyone. That is the property around which the W3C's Decentralized Identifiers are designed, and the branch explains the connection and uses it to name the ideas of the chapter in terms that are used outside Bitcoin."),
  (Y, "Bitcoin's keys are often discussed as money. Seen as identifiers, they raise questions about how a name for something can be created, recognised and proved without a central registry. Chapter 1 introduced the idea of decentralized identity in connection with Bitcoin addresses, and this branch says what precisely makes a key pair suitable for it: the holder of the private key can sign, anyone can verify, and nobody has to grant permission."),
  (H, "The branch has one level, identifiers, with three concepts. The first is the proof of control by a key, the cryptographic property from which the rest follows. The second is the uniform resource identifier, the kind of name that web standards use. The third is the decentralized identifier, a specific standard that combines a name of that kind with public keys."),
  (K, "A resemblance is not an identity. Bitcoin addresses and decentralized identifiers share a design idea, but they are different things with different specifications, and no part of Bitcoin is a decentralized identifier method simply by being a key pair. There are methods that do use a blockchain, and there are methods that use none, and whether any of them uses Bitcoin is a question about that method and not about Bitcoin. The branch therefore states only what the two sets of sources say, keeps the two vocabularies apart, and leaves the comparison as a comparison."),
 ], None),
 ("Identifiers", "Identifiers", 2, "Semantics", None, [
  (W, "An identifier is a name that refers to a thing, so that statements about the thing can be made, stored and found. A public key can be used as such a name, because a key pair lets its holder show, by a signature, that a statement comes from the one who holds the matching private key. This level of the chapter gathers the concepts that connect key pairs to the identifier standards of the web."),
  (Y, "Identifiers matter wherever data from different sources must be linked. In the semantic web, a thing is named by an identifier that is unique and that others can use. Most identifiers depend on a central authority, which assigns names and can withdraw them. A name that its holder controls by a key does not need such an authority, and the question that the standards pose is how to describe and discover the keys behind a name."),
  (H, "The three concepts form a ladder, and each step needs the one below it. Proof of control states what a key makes possible: a signature that anybody can check and nobody can forge. The uniform resource identifier is the general form of the names that web standards use, so that the same string refers to the same thing wherever it appears and whatever program reads it. The decentralized identifier is a particular form of such a name, with a document attached that may list public keys as its verification methods. A reader who follows the ladder from the bottom can say exactly which part of a decentralized identifier a Bitcoin key pair corresponds to, and which parts it does not provide at all."),
 ], None),
 ("KeyControlProof", "Proof of control by a key", 3, "Identifiers", ("signing to prove control", "Whoever holds a private key can prove control of the matching public key by signing, without a central registry or anyone's permission.", None), [
  (W, "Proof of control by a key is the act of showing that one holds a private key without revealing it, by producing a signature that others can verify with the public key. The book describes the property: a signature can only be produced by someone with knowledge of the private key, yet anyone with the public key and the transaction can verify it [BK]. Nothing in the procedure requires the verifier to ask a third party."),
  (Y, "This is what makes a key suitable as the basis of an identity that nobody grants. Ownership of bitcoins is exactly proof of control: a node accepts a spend because the signature verifies against the public key to which the funds were paid, not because anybody vouches for the spender. The identity of the spender is not needed; control is enough, which is the privacy aim with which the chapter began [BK]."),
  (E, "The property is met in every Bitcoin transaction, and outside Bitcoin in the login procedures and certificates that rest on public key cryptography. In the Decentralized Identifiers specification the same idea appears as the ability of the controller of an identifier to prove control over it without requiring permission from any other party [W3C]."),
  (H, "To prove control the holder signs a challenge: a message that the verifier chooses, so that an old signature cannot be replayed. The verifier checks the signature against the public key. The chapter's checks apply the toolkit's ECDSA sketch to the book's key: a signature of a message verifies against the public key, and the same signature does not verify against a different message or a different key. The sketch signs a message hash with a nonce that the caller supplies, which a real signer must not do."),
  (K, "Proof of control is not proof of identity. It shows that the prover holds the key, not who the prover is, and not that the key is the one the verifier meant: the binding of a key to a person or an organisation needs something further, such as a document from a trusted source. A key whose private part has been stolen proves control for the thief."),
 ]),
 ("Uri", "Uniform resource identifier (URI)", 3, "Identifiers", ("did:example:123456789abcdefghi", "A URI is a compact sequence of characters that identifies an abstract or physical resource; the identifiers of the DID standard are URIs of the form did, a colon, a method name, a colon and a method-specific identifier.", ("'did:example:123456789abcdefghi'.split(':')", "['did', 'example', '123456789abcdefghi']")), [
  (W, "A Uniform Resource Identifier, abbreviated URI, is a compact sequence of characters that identifies an abstract or physical resource. The specification of URIs, RFC 3986, defines the generic syntax and a process for resolving URI references, and its grammar allows an implementation to parse the common components of a URI without knowing the requirements of every particular kind of identifier [R3986]. A web address is a URI, and so is the payment request address of Chapter 2, whose scheme is bitcoin."),
  (Y, "A URI gives a thing a name that machines can handle, store, compare and send: the same string refers to the same resource wherever it appears. The semantic technologies of the course rest on this property, since statements are made about resources named by identifiers, and the DID standard chose to be a URI in order to fit into that world. Chapter 3 introduced the IRI, the variant of the URI that allows international characters."),
  (E, "The identifiers of the DID standard are URIs. The example of the specification is did:example:123456789abcdefghi: the scheme did, the name of a DID method, here example, and an identifier that is specific to the method [DID]. In a DID URL, which is such an identifier followed by further parts written in the generic syntax, a path, a query and a fragment may follow, as RFC 3986 allows: for instance did:example:123456/path or did:example:123456?versionId=1 [DID]."),
  (H, "Splitting the example at the colons gives three parts, which the chapter's checks print: did, example and the method-specific identifier. The scheme says which specification governs the rest of the string, the method says how to find the document that belongs to it, and the last part is what the method uses to look it up. Software that knows nothing about the method can still parse the string into these pieces because of the generic syntax [R3986]."),
  (K, "A URI names a resource; it does not say that the resource exists or that anybody controls it. Two different strings may name the same resource, and a name that looks like a web address need not lead to a page. For a decentralized identifier the question of who controls the name is answered by the method and by the keys in the document, as the next concept explains."),
 ]),
 ("DecentralizedIdentifier", "Decentralized identifier (DID)", 3, "Identifiers", ("a DID and its DID document", "A decentralized identifier is a URI that associates a subject with a DID document that can carry verification methods such as public keys, so its controller can prove control without permission from another party.", None), [
  (W, "A decentralized identifier, abbreviated DID, is a new type of identifier defined by a recommendation of the World Wide Web Consortium that enables verifiable, decentralised digital identity. A DID refers to any subject, such as a person, an organisation or a thing, as determined by the controller of the DID. DIDs are URIs that associate a DID subject with a DID document, which allows trustable interactions with that subject [DID]."),
  (Y, "The standard was designed so that its identifiers may be decoupled from centralised registries, identity providers and certificate authorities. While other parties might help in the discovery of information about a DID, the design enables the controller of a DID to prove control over it without requiring permission from any other party [DID]. This is the property that a Bitcoin key pair also has, and it is why the course treats the two together."),
  (E, "A DID document contains information associated with a DID. Each document can express cryptographic material, verification methods or services, which provide a set of mechanisms by which a DID controller can prove control of the DID [DID]. A verification method is typically a public key that can authenticate or authorise interactions, and a cryptographic public key can be used with a digital signature to verify that the signer could use the associated private key [DID]."),
  (H, "The specification defines the syntax of a DID, a data model, the core properties, serialised representations and operations, and the process of resolving a DID to the document that it represents; the steps of resolution are defined by the specification of each DID method [DID]. The chapter's checks read the abstract and the terminology of the saved specification and confirm the sentences quoted here. A Bitcoin key pair maps to the idea in a simple way: the public key is the verification method, and a signature is the proof of control."),
  (K, "A DID is not a Bitcoin address, and a Bitcoin address is not a DID; they only share the design idea. A DID is meaningful only together with a DID method that says how documents are created, resolved, updated and deactivated, and the method may use a blockchain or may not. The specification speaks of a controller who can prove control, and, as for any key-based scheme, a controller who loses the key loses the ability to prove it."),
 ]),
]
