#!/usr/bin/env python3
"""Writes a chapter deck's `examples_vX_Y_Z.py` from that chapter's corpus.

Every worked example of the corpus (a leaf concept's `io` pair) becomes either a short list of console
rows or, when its program needs an indented block, a program the deck shows verbatim. The module written
here carries, for each example: the rows (or the program), and `EXPECT`, the output the corpus itself
records. The runner re-executes everything and refuses to write its JSON if a recast example stops
producing the corpus's own answer, so a slide can never show a number the chapter does not have.

Usage: sen0401_deck_examples_gen_v1_0_0.py <NN> <corpus module> <out .py> <version>
"""
__version__ = "1.0.0"

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from sen0401_deck_lib_v1_0_0 import recast  # noqa: E402

HEADER = '''"""Every computation the SEN0401 chapter {nn} lecture deck shows, and the answer the chapter records for it.

Generated by sen0401_deck_examples_gen_v1_0_0.py from {corpus}.py: each entry is one worked example of that
corpus, recast into the console rows a slide can show (or, where the program needs an indented block, into
the program itself). The outputs are never typed here - examples_run_v{ver}.py executes every row and
writes them, and refuses to write anything if a recast example stops producing the answer in EXPECT, which
is the corpus's own recorded output.
"""
__version__ = "{dotted}"

PRELUDE = {prelude!r}

# concept id -> the console rows the deck shows; the value of the last row is the output
EX = {{
'''


def build(nn, corpus_mod, out_path, ver):
    mod = __import__(corpus_mod)
    prelude_data, groups, blocks, expect, imports = {}, {}, {}, {}, set()
    for node in mod.NODES:
        nid, _label, _lvl, _parent, leaf, _paras = node
        if not leaf or not leaf[2]:
            continue
        code, out = leaf[2]
        got = recast(code, nid.upper(), prelude_data)
        imports.update(got["imports"])
        if got["kind"] == "rows":
            groups[nid] = got["rows"]
        else:
            blocks[nid] = got["text"]
        expect[nid] = out
    prelude = ""
    if imports:
        prelude += "".join("import %s\n" % m for m in sorted(imports))
    for name in sorted(prelude_data):
        prelude += "%s = %s\n" % (name, prelude_data[name])
    dotted = ver.replace("_", ".")
    text = HEADER.format(nn=nn, corpus=corpus_mod, ver=ver, dotted=dotted, prelude=prelude)
    for nid in groups:
        text += " %r: [\n" % nid
        for row in groups[nid]:
            text += "  %r,\n" % row
        text += " ],\n"
    text += "}\n\n# concept id -> a program the deck shows verbatim; the value of `result` is the output\nBLOCKS = {\n"
    for nid, body in blocks.items():
        text += " %r: %r,\n" % (nid, body)
    text += "}\n\n# concept id -> the output the chapter corpus records for this example\nEXPECT = {\n"
    for nid, out in expect.items():
        text += " %r: %r,\n" % (nid, out)
    text += "}\n"
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("written %s: %d row examples, %d block examples, %d prelude names"
          % (os.path.basename(out_path), len(groups), len(blocks), len(prelude_data)))


if __name__ == "__main__":
    build(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
