"""SEN0401 chapter 7, corpus text part H (version 1.0.0): the branch 'Trees and key tweaks' - Merklized alternative script trees,
the difference between the two meanings of MAST, pay to contract, scriptless multisignatures and threshold signatures. These are the
ideas that taproot combines. Markers such as [AH] become author-year strings (sen0401_ch07_common). Numbers are computed in CHECKS_H."""
from sen0401_ch07_common_v1_0_0 import *

BK = "ch07_authorization-authentication.adoc"
TREE = '''import hashlib
def tagged(tag, data):                                  # BIP340's tagged hash: SHA-256(SHA-256(tag) + SHA-256(tag) + data)
    t = hashlib.sha256(tag.encode()).digest()
    return hashlib.sha256(t + t + data).digest()
def leaf(script): return tagged('TapLeaf', bytes([0xc0, len(script)]) + script)
def branch(a, b): return tagged('TapBranch', min(a, b) + max(a, b))
def check(leaf_hash, proof, root):                      # fold the sibling hashes upward and compare with the root
    h = leaf_hash
    for sibling in proof: h = branch(h, sibling)
    return h == root
'''

NODES_H = [
 ("TreesAndTweaks", "Script trees and key tweaks", 1, None, None, P(
  (W, "This branch presents the three ideas that taproot, the last upgrade of the chapter, combines. The first is a tree of alternative scripts, in which only the script that is used is revealed. The second is key tweaking, in which a public key is changed by a value that commits to some data, so that paying to the changed key is also a commitment. The third is the scriptless multisignature, in which several signers make together one signature that looks like the signature of a single key [AH]."),
  (Y, "The ideas answer the weaknesses of the script of the previous branches. A script with several paths pays for all of them in every spend, is limited in size and makes every condition public when any one is used; a multisignature script puts a key and a signature on the chain for every signer. The branch shows how a hash tree, an addition of points and a sum of signatures remove these costs, and each idea is recomputed with the library."),
  (E, "The reader meets the results in every taproot address. In the 6 taproot inputs of block 775,072, 5 spend with a single signature, which can be that of one person or of many, and 1 reveals a script from a tree; the data shows how a tree hides everything but the leaf that is used [MP]. Bitcoin Core's documentation records support for the aggregation of keys in descriptors since release 30.0 and for signing since release 31.0 [BCD]."),
  (H, "The branch has two groups. The first, script trees, explains the Merklized alternative script tree and why the name has two meanings. The second, key tweaks, explains pay to contract, the scriptless multisignature, and the threshold signature, which is the subject where the book's text and the BIPs differ most in strictness. The browser examples use only SHA-256 and the elliptic curve arithmetic that the page provides."),
 ), None),

 ("ScriptTrees", "Trees of alternative scripts", 2, "TreesAndTweaks", None, P(
  (W, "This group is about committing to many scripts with one hash. A Merklized alternative script tree is a set of scripts, each complete by itself, of which only one is used; the output commits to the root of a Merkle tree over them, and a spend reveals the used script and the hashes that connect it to the root [AH]."),
  (Y, "The tree takes the three costs of an IF script away: the weight, since only the executed script is in the transaction; the limit on size, since the number of scripts can grow with only one more hash for each doubling; and the loss of privacy, since the other scripts, and even their number, stay hidden. The earlier proposals BIP114 and BIP116 had the same aim, and taproot reached it by another way."),
  (H, "The first section describes the tree, the membership proof and the arithmetic of the commitments, with a real tree built from the hashes that taproot uses. The second section separates the two meanings of the name MAST, which the book keeps apart because one of them is wasteful. The examples run in the browser with SHA-256 alone."),
  (K, "The sizes the book quotes for its three-script example depend on key, signature and script sizes that the text does not give, so the page does not reproduce them; the structure of the saving, which grows with the logarithm of the number of scripts, is the part that is explained and computed."),
 ), None),

 ("Mast", "Merklized alternative script tree", 3, "ScriptTrees", ("a spend reveals one script and one hash per level of the tree", "A Merklized alternative script tree commits to a set of alternative scripts with the root of a Merkle tree; a spender shows the script that is used and the hashes that connect it to the root, which costs one 32-byte hash for each level between the script and the root.",
   (PROG(TREE + "scripts = [bytes([0x51]), bytes([0x52]), bytes([0x53])]       # three alternative scripts, one byte each, for the example\nla, lb, lc = [leaf(s) for s in scripts]\nroot = branch(branch(la, lb), lc)\nresult = (check(la, [lb, lc], root), check(lc, [branch(la, lb)], root), check(la, [lc, lb], root))"), "(True, True, False)")), P(
  (W, "A Merklized alternative script tree, MAST for short, is the way to use a merkle tree to authorize many different spending conditions. The book describes it step by step: each member of the set of conditions is passed through a hash function to create a short commitment called a leaf; each leaf is paired with another and hashed again, giving a commitment to the leaves called a branch; the step is repeated until one identifier remains, the merkle root. A spend then carries a compact membership proof, which proves that one condition is a member without disclosing the others [AH]."),
  (Y, "The tree removes the three drawbacks that the book finds in OP_IF scripts. Every condition adds weight and fee, because the script grows; legacy script is limited to 10,000 bytes, which allows only a few hundred branches, or about 20,000 useful branches even in a script as large as a block; and every condition becomes public when the output is spent, so that Mohammed's lawyer would see the whole script of the previous branch even when he does not sign. With the tree, only the used script is public, and the number of scripts stays hidden, from a single one to a trillion [AH]."),
  (E, "The cost of a tree grows slowly. The book computes it in commitments of 32 bytes: three conditions need three commitments, one of them the root; a fourth condition costs nothing more; an eighth needs one more; sixteen commitments, 512 bytes, serve over 32,000 conditions; and 128 commitments, 4,096 bytes, more than all computers could create. The page's example builds a three-leaf tree and checks two membership proofs, a long one of two hashes for the first script and a short one of one hash for the third, and rejects a proof whose hashes are in the wrong order [AH]."),
  (H, "The check folds the hashes upward: starting from the hash of the script, it combines the running value with each supplied hash, and compares the final value with the committed root. In the form that taproot uses, a leaf hash is a tagged hash of the leaf version and the script, a branch hash is a tagged hash of the two children sorted so that the smaller comes first, and the sorting means that a proof does not need to say whether a sibling is left or right. BIP341 gives the reason for that choice, which was suggested by one of its acknowledged contributors [B341]."),
  (K, "The tree does not make all scripts equal. A script near the root is cheap to use and one far from it is dear, so the book restructures its example to place the most expected script in the best position, saving one commitment of 32 bytes for the common case, and notes that a Huffman tree gives the best arrangement when the probabilities are known. BIP341 adds a privacy point: the depth of a script in the tree leaks the minimum depth of the tree, which can suggest the wallet software that made it [AH] [B341]."),
 ), None),

 ("MastVersusAst", "Two meanings of MAST", 3, "ScriptTrees", ("commitments needed: 3 scripts need 3, 32,768 scripts need 16", "The name MAST first meant a Merklized abstract syntax tree, which commits to every part of a program, and now means a Merklized alternative script tree, which commits to a set of complete scripts of which one is used; the second needs only one hash for each level of depth.",
   (PROG("def commitments(n):                    # the siblings on the path, one per level, plus the root\n    return (n - 1).bit_length() + 1\nresult = [(n, commitments(n), 32 * commitments(n)) for n in (3, 4, 8, 32768)]"), "[(3, 3, 96), (4, 3, 96), (8, 4, 128), (32768, 16, 512)]")), P(
  (W, "The name MAST has two meanings, and the book keeps them apart in a box. The earliest idea for what is now called MAST was the Merklized abstract syntax tree: in an abstract syntax tree every condition in a script creates a new branch, and such trees are widely used by compilers. A Merklized AST would commit to every part of a program. What people mostly call MAST in Bitcoin today is the Merklized alternative script tree, a backronym coined by the developer Anthony Towns [AH]."),
  (Y, "The distinction matters because it decides how much is revealed. A Merklized AST would require revealing at least one 32-byte digest for every separate part of the program, which, the book says, would not be very space efficient on the blockchain for most programs. An alternative script tree is a set of scripts, each complete by itself, of which only one is selected, so they are alternatives for each other, and it requires one 32-byte digest for each level of depth between the chosen script and the root [AH]."),
  (E, "BIP114 is the 1 proposal that used the earlier name: its title is Merkelized Abstract Syntax Tree, its status is Closed, and it defines a new witness program type that uses a Merkle tree to encode mutually exclusive branches in a script. BIP116, MERKLEBRANCHVERIFY, is a Draft that proposes an opcode for proving that a data element is a member of a committed set. The book says that there were two solid proposals before an improved approach was discovered, which became taproot [B114] [B116] [AH]."),
  (H, "The cost of the alternative tree can be computed from the number of scripts. The number of 32-byte commitments is the depth of the tree plus the root: the example computes 3 for three scripts and for four, 4 for eight and 16 for 32,768, which is 96, 96, 128 and 512 bytes, the figures of the book. A balanced tree is right when all scripts are equally likely; when they are not, BIP341 advises building the tree by the known probabilities, and the book names Huffman's algorithm for it [AH] [B341]."),
  (K, "The book's paragraph on the cost says that with three conditions it needs three commitments and that it could also have four commitments for the same cost; the second figure must mean four conditions, which the arithmetic above confirms. There is also a limit in taproot on the depth of the tree, 128 levels, which BIP341 explains as the depth of the most space-efficient tree that could be built [B341]."),
 ), None),

 ("KeyTweaks", "Tweaking keys", 2, "TreesAndTweaks", None, P(
  (W, "This group is about changing a public key by adding to it a value that is made from other data. Pay to contract uses the tweak as a commitment to a description; the scriptless multisignature uses the sum of keys as a way to make one key from many; and the threshold signature adds the question of who signed [AH]."),
  (Y, "Each idea uses the same property of the curve: points can be added, and the sum of two keys is the key of the sum of the two private keys. The tweak means that a key can carry a commitment without any extra data on the chain, and the sum means that several parties can look like one. Both are what taproot builds on, since a taproot output is a tweaked key."),
  (H, "The first section explains pay to contract with the book's example of a podcast episode and checks that the tweaked private key matches the tweaked public key; the second shows the aggregation of keys and signatures and a signature made by three signers that verifies as an ordinary one; the third gives the arithmetic of sharing a secret so that any two of three can use it, and sets it against the n-of-n signature of BIP327."),
  (K, "The demonstrations of the group are teaching sketches, not secure protocols. The naive sum of keys is open to a rogue-key attack, which the standard protocol prevents with a coefficient for each key, and a threshold scheme needs more care than the secret sharing shown here. The page says so each time and cites the standard where there is one."),
 ), None),

 ("PayToContract", "Pay to contract", 3, "KeyTweaks", ("pay to the key P + t*G, where t is a hash of the contract", "Pay to contract is a key tweak that commits to an agreed description: the payer adds the hash of the description, as a number, to the public key of the payee, and the payee spends with the private key plus the same number.",
   (PROG(SECP + "t = int.from_bytes(hashlib.sha256(b\"Alice's podcast episode #123\").digest(), 'big') % N      # the tweak\nalice = mul(11, G)                                   # Alice's public key, from the private key 11\npaid = add(alice, mul(t, G))                         # the key Bob pays to\nresult = mul((11 + t) % N, G) == paid                  # Alice's tweaked private key opens it"), "True")), P(
  (W, "Pay to contract, P2C, is the use of a key tweak as a commitment. The book builds on the property of elliptic curves that Alice can derive a public key from her private key and give it to Bob; Bob can add an arbitrary value to it to create a derived public key, and if he gives the value to Alice, she can add it to her private key to get the key of the derived public key. In the example, Bob buys a podcast episode from Alice, and they agree on a description, which is turned into a number by hashing it. Bob adds the number to Alice's public key and pays it. The process is called key tweaking, and the number is the tweak [AH]."),
  (Y, "The payment can later be shown to be a payment for that thing. Bob can reveal Alice's underlying key and the description, and anyone can check that the paid key equals the underlying key plus the hash commitment of the description; if Alice admits that the key is hers, she received the payment, and if she spent the funds she knew the description when she signed, as she could only sign for the tweaked key if she knew the tweak. If neither of them reveals the description, the payment looks like any other, so there is no loss of privacy [AH]."),
  (E, "The book notes that because P2C is private by default we cannot know how often it is used for its original purpose, but that it is widely used today in another form, which is taproot. BIP341 describes this: the output of a taproot is a point Q computed as P plus the hash of P and m, times G, for a public key P and the root m of a Merkle tree, so that every taproot output is a pay to contract commitment to a tree of scripts, even when the tree is empty [AH] [B341]."),
  (H, "The example computes the tweak as the SHA-256 of the description taken as a number modulo the curve order, adds the tweak times the generator point to Alice's public key, and checks that the point of the sum of Alice's private key and the tweak is the same point. The library does the same with the taproot tweak: the tagged hash of the key and the tree root gives the number, and the secret that signs for the output is the secret plus that number, adjusted for the parity of the point [B341]."),
  (K, "The proof only works if the payee's underlying key is revealed together with the description, and then the payee's other uses of that key become public; fresh keys for each payment avoid this. The tweak must also be a commitment in the full sense: a hash that cannot be made to match two different descriptions. And the sum of the two is a key like any other, so an observer cannot tell a tweaked key from an ordinary one, which is both the privacy of the scheme and the reason why the proof must be given on purpose."),
 ), None),

 ("ScriptlessMultisignature", "Scriptless multisignature", 3, "KeyTweaks", ("many partial keys and signatures sum to one key and one signature", "A scriptless multisignature is a way for several participants to produce one public key and one signature that look exactly like those of a single signer; the script that would count the keys and signatures disappears.",
   (PROG(SECP + "partial_private_keys = [11, 12, 13]                          # one secret per participant\npartial_public_keys = [mul(k, G) for k in partial_private_keys]\ncombined = None\nfor p in partial_public_keys: combined = add(combined, p)       # the combined key is the sum of the partial keys\nresult = (combined == mul(sum(partial_private_keys) % N, G), len(partial_public_keys))"), "(True, 3)")), P(
  (W, "A scriptless multisignature is the other way to require cooperation from several keys. The book distinguishes script multisignatures, which use the OP_CHECKSIG-style opcodes, from scriptless ones. Each participant creates a secret like a private key, called a partial private key, and derives a partial public key from it; the partial public keys are shared and combined into the scriptless multisignature public key. To spend, each participant makes a partial signature, and the partial signatures are combined into a regular full signature [AH]."),
  (Y, "The result is smaller and more private. The combined key looks the same as any other Bitcoin public key, and the combined signature looks the same as any other signature, so a third party cannot tell whether a signature was made by one person or by a million people. For scripted multisignatures the number of bytes grows with every key and signature, and the number of keys is disclosed; for scriptless ones the size is constant. The book names two costs: the known secure algorithms need more rounds of interaction or more careful management of state, which is hard for nearly stateless hardware signing devices, and a threshold signature does not reveal who signed [AH]."),
  (E, "BIP327 standardizes the scheme, MuSig2, for BIP340 keys and signatures: signers create one aggregate public key and cooperatively create ordinary Schnorr signatures valid under it, in two communication rounds, and signing requires all signers. The on-chain footprint is essentially a single public key and one signature, which BIP327 says is more compact and has lower verification cost than a key and a signature for each signer with the counting opcode of tapscript, and the number of signers is not limited by any consensus rule [B327]."),
  (H, "The sum of keys is the base of the scheme: the point of the sum of private keys is the sum of the points of the private keys, which the example checks for three participants. A signature is added in the same way, if the participants add their random nonces too: each makes a partial signature from its nonce, key and a common challenge, and the sum of the partial signatures is a signature that the standard verification accepts. The library does this for two, three and five signers, each time producing 64 bytes that verify under the sum of the keys [B340]."),
  (K, "The simple sum is not secure. A participant who sees the others' keys before choosing its own can choose a key that cancels theirs and so control the combined key alone; the standard prevents this by multiplying each key by a coefficient that depends on all the keys, and by nonces of two points. The library's sketch is labelled as a sketch for that reason. The standard is also an n-of-n scheme and not a threshold scheme, as BIP327 says in its motivation [B327]."),
 ), None),

 ("ThresholdSignature", "Threshold signature", 3, "KeyTweaks", ("any 2 of 3 shares reconstruct the key", "A threshold signature lets any t of k participants sign; because the result is an ordinary signature, it does not show which of them signed, which is good for privacy and bad for accountability.",
   (PROG("N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141\nsecret, a1 = 12345, 67890                          # a line f(x) = secret + a1 * x, so that two points fix it\nshares = {x: (secret + a1 * x) % N for x in (1, 2, 3)}\ndef combine(i, j):                                 # Lagrange interpolation at x = 0 from the shares i and j\n    return (j * pow(j - i, -1, N) * shares[i] + (-i) * pow(j - i, -1, N) * shares[j]) % N\nresult = [combine(1, 2) == secret, combine(1, 3) == secret, combine(2, 3) == secret]"), "[True, True, True]")), P(
  (W, "A threshold signature is the t-of-k version of the scriptless multisignature. The book explains the difference with a script: in scripted threshold signing, Alice, Bob and Carol agree that any two of them signing is enough, and if Alice and Bob sign, their signatures are on the chain and prove to anyone who knows their keys that they signed and Carol did not. In scriptless threshold signing a signature from Alice and Bob cannot be told from one by Alice and Carol or by Bob and Carol [AH]."),
  (Y, "That property is a benefit and a cost at the same time. It is beneficial for privacy, since the chain says nothing about who took part; but even if Carol claims that she did not sign, she cannot prove it, which the book says may be bad for accountability and auditability. The book's conclusion for many users and uses is that the reduced size and increased privacy outweigh the occasional difficulties of creating and auditing these signatures [AH]."),
  (E, "The mathematics of sharing a secret is old and simple, and the page shows its smallest case: a secret is the constant term of a line, the three shares are the values of the line at the points 1, 2 and 3, and any two shares determine the line and therefore the secret, by Lagrange interpolation at zero. The example checks all three pairs. A threshold signature scheme applies this idea to a signing key so that the key itself is never assembled in one place, which this page does not demonstrate."),
  (H, "The reader should not confuse the sketch with a protocol. BIP327, the standard that the chapter cites, is n-of-n and not a t-of-n threshold scheme, as its own motivation states; so there is no deployed standard of the course's sources for the threshold case. What the library shows is the part that is pure arithmetic: shares of 12345 at 1, 2 and 3 reconstruct it from any two, and one share alone gives no information about the secret, since for every possible secret there is a line through that share [B327]."),
  (K, "The book names the second cost directly: scriptless threshold signing does not reveal who signed. A business that needs an audit trail has to keep it outside the chain, or use a script multisignature, in which the signatures are the audit trail. The first cost, interaction, matters most for a signing device in a safe deposit box, which with a scripted multisignature is visited once and with a scriptless one possibly two or three times [AH]."),
 ), None),
]

CHECKS_H = [
 Qb(BK, "Using +OP_IF+, you", "can authorize multiple different spending conditions,", "but this approach has several undesirable aspects:", "Every condition you add increases the size of the", "script, increasing the weight of the transaction and the amount of fee", "legacy script is limited to 10,000 bytes, practically", "limiting you to a few hundred conditional branches at most.", "it could still", "only contain about 20,000 useful branches.", "Every condition you add to your script becomes", "public knowledge when you spend bitcoins protected by that script.", "will be able to track all of their transactions."),
 Qb(BK, "Bitcoin already uses a data structure known as a merkle tree", "that allows verifying an element is a member of a set without", "needing to identify every other member of the set.", "(called a _leaf_ of the merkle", "tree)", "called a", "_branch_ commitment.", "called the _merkle root_.", "compact membership proof that proves a particular", "authorization condition is a member of the merkle tree without", "disclosing any details about the other members of the merkle tree.", "The hash digests used to create the commitments are each 32 bytes", "uses 383", "bytes.", "uses 412 bytes.", "Saving 29 bytes (7%)"),
 Qb(BK, "you only need an additional 32-byte commitment every time", "you double the number of members in the set", "we need to use three", "commitments (one of them being the merkle root, which will need to be", "included in the authorization data); we could also have four", "commitments for the same cost.", "An extra commitment would give us up to", "eight conditions.", "With just 16 commitments--512 bytes of commitments--we could have", "over 32,000 authorization conditions", "With 128 commitments", "(4,096 bytes)"),
 Qb(BK, "Now we only need to provide two commitments for the common case (saving 32", "bytes), although we still need three commitments for the less common cases.", "you can use the Huffman", "algorithm to place them into a maximally efficient tree; see BIP341 for", "details.", "we're only revealing the actual authorization conditions", "that get used.  The other conditions remain private.", "a tree could have a single condition", "or a trillion conditions", "there were two solid", "proposals for it, BIP114 and BIP116"),
 Qb(BK, "The earliest", "idea for what we now know as _MAST_ in Bitcoin was", "_merklized abstract syntax trees_.", "every condition in a script creates a new branch", "ASTs are widely used by programs that parse and optimize code", "A merklized AST would commit to every part", "of a program", "it would require revealing at least one 32-byte digest for", "every separate part of the program, which would not be very space", "efficient on the blockchain for most programs.", "_merklized alternative script trees_, a backronym coined by developer", "Anthony Towns.", "An alternative script tree is a set of scripts, each", "one of them complete by itself, where only one can be selected--making", "them alternatives for each other", "Alternative script trees only require revealing one 32-byte digest for", "each level of depth between the spender's chosen script and the root of", "the tree."),
 Qb(BK, "Bob can create child public keys for which only", "Alice can create the corresponding private keys.", "transform that description into a", "number by hashing it and interpreting the hash digest as a number.", "Bob", "adds that number to Alice's public key and pays it.", "The process is", "called _key tweaking_, and the number is known as a _tweak_.", "Alice can spend the funds by tweaking her private key using the same", "number (tweak).", "Later, Bob can prove to anyone what he paid Alice by revealing her", "underlying key and the description they used.", "If neither Alice nor Bob decided to publicly reveal the description they", "use, the payment between them looks like any other payment.  There's no", "privacy loss.", "Because P2C is private by default, we can't know how often it is used", "P2C is widely used today", "in a slightly different form, which we'll"),
 Qb(BK, "we'll call the", "version involving `OP_CHECKSIG`-style opcodes _script multisignatures_", "and the other version _scriptless multisignatures_.", "_partial private key_", "derives a partial public key", "This combined public key looks the same as any other Bitcoin public key.", "each participant generates a", "partial signature.  The partial signatures", "are then combined to create a regular full signature.", "Third parties", "can't determine whether a signature was created by a single person or a", "million people cooperating with each other.", "Scriptless multisignatures are smaller and more private than scripted", "multisignatures.", "the size is constant--a million", "participants each providing their own partial key and partial signature", "puts exactly the same amount of data in a transaction as an individual", "using a single key and signature."),
 Qb(BK, "all known secure algorithms for creating them for Bitcoin require more", "rounds of interaction or more careful management of state than", "scripted multisignatures.", "you", "would need to visit that box once to create a scripted multisignature but", "possibly two or three times for a scriptless multisignature.", "threshold signing doesn't reveal who signed.", "Alice, Bob, and Carol agree (for example)", "that any two of them signing will be sufficient to spend the funds.", "a signature from", "Alice and Bob is indistinguishable from a signature between Alice and", "Carol or Bob and Carol.", "This is beneficial for privacy, but it means", "that, even if Carol claims she didn't sign, she can't", "prove that she didn't, which may be bad for accountability and", "auditability.", "the always reduced size and increased", "privacy of multisignatures outweighs its occasional challenges for"),
 Qe("bip-0114.mediawiki", "Title: Merkelized Abstract Syntax Tree", "Status: Closed", "This BIP defines a new witness program type that uses a Merkle tree to encode mutually exclusive branches in a script.", "Any unexecuted branches and non-consensus enforced data in the script are visible to the public, consuming block space while damaging privacy."),
 Qe("bip-0116.mediawiki", "Title: MERKLEBRANCHVERIFY", "Status: Draft", "which allows script writers to commit to a set of data elements and have one or more of these elements be provided at redemption without having to reveal the entire set."),
 Qe("bip-0341.mediawiki", "Merkle branches (\"MAST\", [[bip-0114.mediawiki|BIP114]]", "''Q'' is computed as ''P + hash(P||m)G'' for a public key ''P'', and the root ''m'' of a Merkle tree", "must have length ''33 + 32m'', for a value of ''m'' that is an integer between 0 and 128", "Why are child elements sorted before hashing in the Merkle tree?", "By doing so, it is not necessary to reveal the left/right directions along with the", "the depth of a script in the Merkle root leaks information including the minimum depth of the tree, which suggests specific wallet software that created the output and helps clustering.", "Arik Sosman for suggesting to sort Merkle node children before hashes", "If probabilities for each condition are known, consider constructing the tree"),
 Qe("bip-0327.mediawiki", "MuSig2 is a multi-signature scheme that allows multiple signers to create a single aggregate public key and cooperatively create ordinary Schnorr signatures valid under the aggregate public key.", "Signing requires interaction between ''all'' signers involved in key aggregation.", "(MuSig2 is a ''n-of-n'' multi-signature scheme and not a ''t-of-n'' threshold-signature scheme.)", "The on-chain footprint of a MuSig2 Taproot output is essentially a single BIP340 public key, and a transaction spending the output only requires a single signature cooperatively produced by all signers.", "This is '''more compact''' and has '''lower verification cost'''", "the number ''n'' of signers is not limited by any consensus rules when using MuSig2.", "MuSig2 Taproot outputs are indistinguishable for a blockchain observer from regular, single-signer Taproot outputs", "Two Communication Rounds", "each signer's nonce consists of two elliptic curve points", "Status: Deployed"),
 Qe("bip-0340.mediawiki", "BIP0340/challenge"),
 Qe("core_doc_bips.md", "Key aggregation via `musig()` descriptors is supported as of **v30.0**", "Signing is supported as of **v31.0**"),
 # executed: the tree
 X("(lambda g: (exec(" + repr(TREE) + ", g), (g['leaf'](b'\\x51') == L.tap_leaf_hash(0xc0, b'\\x51'), g['branch'](g['leaf'](b'\\x51'), g['leaf'](b'\\x52')) == L.tap_branch_hash(L.tap_leaf_hash(0xc0, b'\\x51'), L.tap_leaf_hash(0xc0, b'\\x52')), g['branch'](g['leaf'](b'\\x52'), g['leaf'](b'\\x51')) == g['branch'](g['leaf'](b'\\x51'), g['leaf'](b'\\x52'))))[1])({})", (True, True, True)),
 X("L.tap_leaf_hash(0xc0, b'\\x51').hex()", "a85b2107f791b26a84e7586c28cec7cb61202ed3d01944d832500f363782d675"),
 X("(lambda g: (exec(" + repr(TREE) + ", g), (lambda la, lb, lc: (lambda root: (g['check'](la, [lb, lc], root), g['check'](lc, [g['branch'](la, lb)], root), g['check'](la, [lc, lb], root), g['check'](lb, [la, lc], root)))(g['branch'](g['branch'](la, lb), lc)))(g['leaf'](b'\\x51'), g['leaf'](b'\\x52'), g['leaf'](b'\\x53')))[1])({})", (True, True, False, True)),
 X("[(n - 1).bit_length() + 1 for n in (1, 2, 3, 4, 5, 8, 32768, 2 ** 127)]", [1, 2, 3, 3, 4, 4, 16, 128]),
 X("[32 * ((n - 1).bit_length() + 1) for n in (32768, 2 ** 127)]", [512, 4096]),
 X("(lambda a: (a[0] > 32000, 2 ** 127 > 10 ** 38))((2 ** 15, 0))", (True, True)),
 X("(10000 // 34, 1000000 // 34)", (294, 29411)),
 X("[C.census(L)['p2tr-keypath'], C.census(L)['p2tr-scriptpath']]", [5, 1]),
 X("L.tap_branch_hash(b'\\x01' * 32, b'\\x00' * 32) == L.tap_branch_hash(b'\\x00' * 32, b'\\x01' * 32)", True),
 X("(lambda w: (len(w), len(w[-1]), (len(w[-1]) - 33) // 32))(L.parse_tx(C.tx_record('4e0e703251bb')[0]).witness[0])", (3, 33, 0)),
 # executed: pay to contract
 X("(lambda t, P, secret: (L.point_mul((secret + t) % L.N) == L.point_add(P, L.point_mul(t)), L.point_mul((secret + t) % L.N)[0] == L.point_add(P, L.point_mul(t))[0]))(int.from_bytes(L.sha256(b\"Alice's podcast episode #123\"), 'big') % L.N, L.point_mul(11), 11)", (True, True)),
 X("(lambda t, P: L.point_add(P, L.point_mul(t)) != P)(int.from_bytes(L.sha256(b'a different description'), 'big') % L.N, L.point_mul(11))", True),
 X("(lambda g: (exec(" + repr(SECP) + ", g), (lambda t: g['mul']((11 + t) % g['N'], g['G']) == g['add'](g['mul'](11, g['G']), g['mul'](t, g['G'])))(int.from_bytes(__import__('hashlib').sha256(b\"Alice's podcast episode #123\").digest(), 'big') % g['N']))[1])({})", True),
 X("(lambda m: (lambda parity, x: (len(x), parity in (0, 1)))(*L.taproot_tweak_pubkey(L.schnorr_pubkey(1), m)))(L.tap_leaf_hash(0xc0, b'\\x51'))", (32, True)),
 X("(lambda d, m: (lambda tweaked_secret: L.schnorr_pubkey(tweaked_secret) == L.taproot_tweak_pubkey(L.schnorr_pubkey(d), m)[1])(L.taproot_tweak_seckey(d, m)))(7, L.tap_leaf_hash(0xc0, b'\\x51'))", True),
 X("(lambda d, m: (lambda t: L.point_add(L.lift_x(int.from_bytes(L.schnorr_pubkey(d), 'big')), L.point_mul(t))[0].to_bytes(32, 'big') == L.taproot_tweak_pubkey(L.schnorr_pubkey(d), m)[1])(int.from_bytes(L.tagged_hash('TapTweak', L.schnorr_pubkey(d) + m), 'big') % L.N))(7, L.tap_leaf_hash(0xc0, b'\\x51'))", True),
 # executed: scriptless multisignatures
 X("(lambda ks: (lambda ps: (lambda c: (c == L.point_mul(sum(ks) % L.N), len(ps)))(__import__('functools').reduce(L.point_add, ps)))([L.point_mul(k) for k in ks]))([11, 12, 13])", (True, 3)),
 X("[(lambda m: (lambda p, s: (len(s), L.schnorr_verify(p, m, s)))(*C.naive_agg_sign(ss, m)))(L.sha256(b'two of three')) for ss in ([11, 12], [11, 12, 13], [5, 6, 7, 8, 9])]", [(64, True)] * 3),
 X("(lambda m: (lambda p, s: L.schnorr_verify(p, L.sha256(b'another message'), s))(*C.naive_agg_sign([11, 12, 13], m)))(L.sha256(b'two of three'))", False),
 X("(lambda m, ks: [len(p) for p in [C.naive_agg_sign(ks[:i], m)[0] for i in (2, 3, 5)]])(L.sha256(b'm'), [11, 12, 13, 14, 15])", [32, 32, 32]),
 X("(lambda m: (lambda p, s: (L.taproot_tweak_pubkey(p)[1] != p, L.schnorr_verify(p, m, s)))(*C.naive_agg_sign([11, 12, 13], m)))(L.sha256(b'm'))", (True, True)),
 X("[len(L.multisig_script(k, [C.pub(i % 8) for i in range(k)])) for k in (3, 5, 15)]", [105, 173, 513]),
 # executed: shares of a secret
 X("(lambda N, secret, a1: (lambda sh: (lambda comb: [comb(1, 2) == secret, comb(1, 3) == secret, comb(2, 3) == secret])(lambda i, j: (j * pow(j - i, -1, N) * sh[i] + (-i) * pow(j - i, -1, N) * sh[j]) % N))({x: (secret + a1 * x) % N for x in (1, 2, 3)}))(L.N, 12345, 67890)", [True, True, True]),
 X("(lambda N, a1: len({(12345 + a1 * 1) % N, (999 + a1 * 1) % N}))(L.N, 67890)", 2),
 X("(lambda N: [(s + a * 2) % N for s, a in ((12345, 67890),)][0] != (12345 + 67890) % N)(L.N)", True),
]
