"""SEN0401 chapter 7, corpus text part B (version 1.0.0): the branch 'Locking to a key' - the original payment to a public key, the hash of
a public key and the pay to public key hash script, and what the signature operator actually checks (the signature hash, the hash types
and the encoding of an ECDSA signature). Real bytes of the first payment between people (block 170) and of the pizza payment are used.
Markers such as [AH] become author-year strings (sen0401_ch07_common). The facet names are only the author's writing guide."""
from sen0401_ch07_common_v1_0_0 import *
from sen0401_ch07_common_v1_0_0 import SS_PIZZA

BK = "ch07_authorization-authentication.adoc"
NODES_B = [
 ("KeyLocking", "Locking to a key", 1, None, None, P(
  (W, "This branch follows the oldest and still the commonest way of controlling an output: locking it to a key. The original description of Bitcoin put the public key itself in the output, and the authentication came from the receiver in the form of a signature that committed to the spending transaction; the released software made the mechanism more flexible, and the book then describes the form that dominated legacy transactions, the pay to public key hash script, whose output holds only a hash of the key [AH]. The branch also explains what the signature operator checks, because every later branch ends in it."),
  (Y, "The branch matters because a signature is the proof that ends almost every script in the chapter. A reader who knows exactly what a signature covers - which bytes of the spending transaction are hashed, which hash type was chosen, how the signature is encoded - can read multisignatures, timelocked contracts, witness programs and taproot spends as variations on one act of authentication, and can see why each later upgrade changed the way the hash is computed."),
  (H, "The branch has two groups. The first, from a public key to its hash, follows the output script from the bare key of 2009, through the 20-byte hash that a legacy address encodes, to the script that checks both the hash and the signature. The second, checking a signature, opens the signature operator: the message that is signed, the choices a signer has about what to commit to, and the byte format of the signature itself. The worked examples verify, in the browser, the signature of the first payment between people."),
  (K, "The chapter on signatures that follows this one explains the mathematics of ECDSA and schnorr signatures; this branch stays at the level of the script that calls them, and where it needs a number from the mathematics - the order of the curve, the size of a signature - it states the number and says where it comes from [AH8].")), None),

 ("PayToKey", "From a public key to its hash", 2, "KeyLocking", None, P(
  (W, "This group covers the three ways an output has been locked to a single key. The earliest is the pay to public key script, in which the output holds the key. The second ingredient is the public key hash, the short digest of a key that a legacy address encodes. The third is the pay to public key hash script, which puts the digest in the output and asks the spender to reveal the key and sign with it [AH]."),
  (Y, "The sequence is a history of trade-offs between size, privacy and convenience. The bare key is the simplest script but the output is as long as the key and the key is public from the moment the output exists; the hash is shorter and hides the key until the output is spent, and it lets an address be a short string that a person can copy; and the script that checks the hash and then the signature gives the receiver the same proof of ownership the bare key gave."),
  (H, "The three sections each end in a worked example on real bytes: the 67-byte script of the first payment between people, the address that the 20-byte hash of the generator point encodes, and the input of the pizza payment of 2010, which is run step by step through the script. The census of block 775,072 gives the proportions in today's traffic [MP]."),
  (K, "The word address names the Base58Check or bech32 string that encodes a hash, not a script; a wallet turns the address back into the script before it builds the output. A reader who sees the script in an explorer is therefore looking one step closer to what the nodes actually check than a reader who sees the address.")), None),

 ("PayToPublicKey", "Pay to public key", 3, "PayToKey", ("<public key> OP_CHECKSIG", "A pay to public key output holds the public key itself followed by the signature operator, so that it is spent by a signature that the key can verify; it is the form in which Bitcoin was first described and used.",
   (PROG("spk = bytes.fromhex('" + SPK170 + "')\nresult = (len(spk), spk[0], spk[-1])"), "(67, 65, 172)")), P(
  (W, "A pay to public key output, written P2PK, is the form the first description of Bitcoin used. The book says the original description used a public key for authorization: Alice paid Bob by putting his public key in the output of a transaction, and Bob authenticated himself with a signature that committed to a spending transaction, such as one from Bob to Carol [AH]. The script is the public key followed by the signature operator, and it is spent by an input script consisting of a single signature."),
  (Y, "P2PK matters as the base case: it shows authorization and authentication in their purest form, one key and one signature, with no hash in between. The first payment between people, in block 170 on 12 January 2009, spent an output of this kind and created two more: its input is a 71-byte signature, and its outputs of 10 and 40 bitcoins are locked with 67-byte scripts [ML]. Every other single-key script in the chapter is this one with some indirection."),
  (E, "The reader meets P2PK in the oldest blocks, in the coinbase outputs of the first years, and wherever a script is built by hand; Bitcoin Core's script solver still recognises it as one of its standard templates, the pay to public key type, and the book names it in the introduction of the chapter [BCV] [AH]. The example reads the locking script of the output that the block 170 transaction spends: 67 bytes, beginning with the byte 65 that pushes a 65-byte uncompressed public key and ending with byte 172, the signature operator."),
  (K, "The public key sits in the output from the moment the output is created, so it is visible in every full node's set of unspent outputs and in the blockchain for as long as the output is unspent. The hash form described next keeps the key out of view until the spender reveals it. The 65 bytes of an uncompressed key are also longer than the 33 bytes of a compressed one, which is why later outputs use compressed keys [AH4]."),
 ), None),

 ("PublicKeyHash", "Public key hash", 3, "PayToKey", ("HASH160 of the public key: RIPEMD-160(SHA-256(key))", "A public key hash is the 20-byte digest obtained by applying SHA-256 and then RIPEMD-160 to a public key; the legacy address that begins with a 1 is its Base58Check encoding.",
   (PROG(B58 + "h = bytes.fromhex('751e76e8199196d454941c45d1b3a323f1433bd6')       # HASH160 of the compressed generator point\nresult = b58check(0, h)"), "'1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH'")), P(
  (W, "A public key hash is a short commitment to a public key. The book describes the construction in its P2SH section for a script and the same two hash functions are used for a key: the data is hashed first with SHA256 and then with RIPEMD-160, producing a 20-byte hash [AH]. The book states what the hash is used for in a P2PKH script: the Key Hash is the data that would be encoded into a legacy base58check address, and most applications show it in hexadecimal rather than as an address that begins with a 1 [AH]. The example encodes the hash of the compressed generator point of the curve, 751e76e8..., with a version byte of 0 and obtains the address 1BgGZ9tc..."),
  (Y, "The hash makes the output shorter and the key private for a while. A compressed key takes 33 bytes and a hash 20; more importantly, an output that holds only the hash reveals nothing about the key until it is spent, and a person can share an address that is a short string of characters with a checksum rather than a long hexadecimal key. The book's chapter on keys describes the address and the compression of keys in detail [AH4]."),
  (H, "The operator OP_HASH160 performs the two steps in one: it pops an item, applies SHA-256 and then RIPEMD-160, and pushes the 20-byte result. Bitcoin Core's own function for it is named Hash160 and does the same [BCI]. RIPEMD-160 is not available in the Python of a web browser, so the example is given the hash rather than computing it; the chapter's library, which includes a RIPEMD-160 written in pure Python that was checked against the C implementation on 131 inputs, computes it in the checks."),
  (K, "A key has two serializations, compressed and uncompressed, and the two have different hashes and therefore different addresses; funds sent to the hash of the uncompressed form can be spent only by presenting the uncompressed key. The book makes the point for segregated witness: a P2WPKH output must be built from the hash of a compressed key, and an output built from an uncompressed key may be unspendable [AH]."),
 ), None),

 ("PayToPublicKeyHash", "Pay to public key hash", 3, "PayToKey", ("OP_DUP OP_HASH160 <key hash> OP_EQUALVERIFY OP_CHECKSIG", "A pay to public key hash output script contains a hash that commits to a public key, and it is spent by presenting a public key that matches the hash together with a signature made by the corresponding private key.",
   (PROG("script = bytes.fromhex('76a914ab68025513c3dbd2f7b92a94e0581f5d50f654e788ac')\nnames = {0x76: 'DUP', 0xa9: 'HASH160', 0x88: 'EQUALVERIFY', 0xac: 'CHECKSIG'}\nresult = [names.get(script[0]), names.get(script[1]), 'PUSH %d' % script[2], names.get(script[23]), names.get(script[24])]"), "['DUP', 'HASH160', 'PUSH 20', 'EQUALVERIFY', 'CHECKSIG']")), P(
  (W, "A pay to public key hash output, P2PKH, is the legacy output that most transactions used. The book defines it as a script that uses an output script containing a hash that commits to a public key, best known as the basis for a legacy Bitcoin address, spent by presenting a public key that matches the hash commitment and a digital signature created by the corresponding private key [AH]. The output script is OP_DUP OP_HASH160 <Key Hash> OP_EQUALVERIFY OP_CHECKSIG, which is 25 bytes: three operators, a 20-byte push, and two more operators."),
  (Y, "P2PKH is the pattern behind the first decade of Bitcoin payments, and it still appears: in the first 599 transactions of block 775,072 there are 194 inputs that spend a P2PKH output out of 1,022 inputs in all, against 626 that spend the segwit equivalent [MP]. It combines two proofs in one output - that the spender has the key the sender had in mind, by the hash, and that the spender controls it, by the signature - and it does so with an output that is 25 bytes, not the 67 of the bare key."),
  (E, "The book gives the input script as <Signature> <Public Key>, and the combined script as <Sig> <Pubkey> OP_DUP OP_HASH160 <Hash> OP_EQUALVERIFY OP_CHECKSIG, and walks through the execution in its figures 7-3 and 7-4 [AH]. The pizza payment of 22 May 2010 is a real example: its first input spends a P2PKH output with a 73-byte signature and a 65-byte public key [ML]."),
  (H, "The trace has seven steps. The two pushes of the input script leave the signature and the key on the stack; DUP copies the key; HASH160 replaces the copy with its 20-byte hash; the output script pushes the committed hash; EQUALVERIFY compares the two hashes and stops the script with a failure if they differ; and CHECKSIG consumes the signature and the remaining key and leaves true if the signature is valid for the spending transaction. The stack holds 1, 2, 3, 3, 4, 2 and 1 items after the seven steps, and the library confirms that the real input is accepted and that the hash of the key in it equals the hash in the output."),
  (K, "The result is true only if both halves hold. A correct key with a forged signature fails at CHECKSIG, and a valid signature made with a different key fails at EQUALVERIFY, because the hash does not match. The most common wallet error with this script is the compressed or uncompressed choice: the script commits to the hash of exactly one serialization of the key [AH]."),
 ), None),

 ("SignatureChecking", "Checking a signature", 2, "KeyLocking", None, P(
  (W, "This group opens the signature operator. Three questions come in order: what the operator does when it runs, what exactly the signature is a signature of, and how the signature is written down as bytes. The first is the subject of OP_CHECKSIG, the second of the signature hash and its hash types, the third of the DER encoding of an ECDSA signature [AH8]."),
  (Y, "The questions matter because everything a transaction promises is only as strong as the commitment inside its signatures. The book frames the point: in Bitcoin's use of digital signatures the message being signed is the transaction, or more accurately a hash of a specific subset of the data in the transaction, called the commitment hash, so the choice of subset decides what a signer can later be held to, and what a third party may still change [AH8]."),
  (H, "The three sections are in the order the engine meets them. OP_CHECKSIG pops a public key and a signature, strips the hash type from the end of the signature, builds the commitment hash for the transaction and the script being run, and verifies. The signature hash section describes how the hash depends on the hash type, and the encoding section describes the bytes. The first payment between people is verified end to end by a standard-library program in the page."),
  (K, "The mathematics of the signature, and the signing algorithms of ECDSA and schnorr, belong to the next chapter; the group quotes it only for the numbers a script reader needs. The commitment hash is computed in three different ways in Bitcoin - the legacy algorithm, the version 0 witness algorithm of BIP143 and the taproot algorithm of BIP341 - and this group describes the legacy one, leaving the others to the witness and taproot branches [B143] [B341].")), None),

 ("OpChecksig", "OP_CHECKSIG", 3, "SignatureChecking", ("<signature> <public key> OP_CHECKSIG", "OP_CHECKSIG pops a public key and a signature, checks the signature against a hash of the spending transaction, and pushes true if it is valid and false otherwise.",
   (PROG(SECP + "tx = bytes.fromhex('" + TX170 + "')\nspk = bytes.fromhex('" + SPK170 + "')\nn = tx[41]; sig = tx[42:42 + n][1:-1]                     # the input script is one push: the DER signature and one hash-type byte\nrl = sig[3]; r = int.from_bytes(sig[4:4 + rl], 'big'); sl = sig[5 + rl]; s = int.from_bytes(sig[6 + rl:6 + rl + sl], 'big')\npreimage = tx[:41] + bytes([len(spk)]) + spk + tx[42 + n:] + (1).to_bytes(4, 'little')    # the transaction with the locking script in place of the input script, then SIGHASH_ALL\nz = int.from_bytes(hashlib.sha256(hashlib.sha256(preimage).digest()).digest(), 'big')\nresult = (verify(spk[1:66], z, r, s), verify(spk[1:66], z + 1, r, s))"), "(True, False)")), P(
  (W, "OP_CHECKSIG is the operator that turns a signature into an answer. The book describes the verification algorithm it relies on: it takes the message, a hash of parts of the transaction and related data, the signer's public key and the signature, and returns true if the signature is valid for this message and public key; verification means that only the controller of the private key that generated this public key could have produced this signature on this transaction [AH8]. As a script operator it pops the public key from the top of the stack, then the signature, and pushes 1 or 0."),
  (Y, "OP_CHECKSIG is the authentication step of almost every pattern in the chapter: the P2PKH script, the pay to public key script, the witness program for a key hash, the keys inside a multisignature, the single key of a taproot spend. It is also the expensive operator, which is why the consensus rules count signature operations and why tapscript replaces the operation count with a budget that is spent on each signature [B342]."),
  (H, "The last byte of the signature is the hash type; the engine removes it, builds the commitment hash for the transaction, the input being checked and the script being run, and verifies the remaining DER signature with the public key. The example does this for the block 170 payment in standard-library Python: it takes the transaction, replaces the input script with the locking script of the output being spent, appends the hash type as four bytes, hashes the result twice with SHA-256, and verifies the signature against the 65-byte key in the locking script. It prints True for the real message and False for a message that differs by one, and runs in about 0.04 seconds."),
  (K, "A failing signature does not by itself stop the script; the operator pushes false and the script continues, which is why the standard relay policy added the NULLFAIL rule that a failing signature must be empty, so that nobody can change a failing signature without invalidating the transaction. Bitcoin Core reports the error SIG_NULLFAIL for it. In tapscript the rule is part of consensus: a non-empty signature that does not verify fails the script at once [BCH] [B342]."),
 ), None),

 ("SignatureHash", "The signature hash and its hash types", 3, "SignatureChecking", ("SIGHASH_ALL = 0x01 commits to all inputs and all outputs", "The signature hash, or commitment hash, is the digest of a modified copy of the transaction plus the hash type, and the hash type, one byte appended to the signature, says which parts of the transaction the signature commits to.",
   (PROG("types = {'ALL': 1, 'NONE': 2, 'SINGLE': 3}\nANYONECANPAY = 0x80\nresult = [(name + ('|ANYONECANPAY' if flag else ''), hex(v | flag)) for flag in (0, ANYONECANPAY) for name, v in types.items()]"), "[('ALL', '0x1'), ('NONE', '0x2'), ('SINGLE', '0x3'), ('ALL|ANYONECANPAY', '0x81'), ('NONE|ANYONECANPAY', '0x82'), ('SINGLE|ANYONECANPAY', '0x83')]")), P(
  (W, "The signature hash is the message that a Bitcoin signature actually signs. The book explains that a signature proves a commitment by the signer to specific transaction data, in the simplest form to almost the entire transaction, and that a SIGHASH flag, a single byte appended to the signature, says which part of a transaction's data is included in the hash signed by the private key [AH8]. There are three flags - ALL (0x01), NONE (0x02) and SINGLE (0x03) - and a modifier ANYONECANPAY (0x80) that combines with each by bitwise OR, giving six values."),
  (Y, "The hash types are what make partially built transactions possible. ALL, the default, commits to every input and output and is what simple wallets use. With ALL|ANYONECANPAY several people can each add an input to a transaction whose outputs are fixed, the book's crowdfunding construction; NONE gives a blank check, since anyone may write the outputs; NONE|ANYONECANPAY gives a dust collector. Because the flag itself is part of the hashed data, a miner cannot change it [AH8]."),
  (H, "To compute the legacy signature hash the signer makes a copy of the transaction, blanks the input scripts of the other inputs, puts the locking script of the output being spent in the input being signed, omits or truncates fields according to the flag, serializes the result, appends the flag as four bytes and hashes the whole with SHA-256 twice. The book describes the same steps in words; Bitcoin Core's 500 test vectors for it all reproduce with the chapter's library [AH8] [BCJ]."),
  (K, "The legacy algorithm has a flaw that its successors repair: with SINGLE, if the input has no output with the same index, Bitcoin Core's code returns the constant 1 as the hash, so the signature signs nothing about the transaction. BIP143 keeps the behaviour but commits zero instead of one in the equivalent case, and BIP341 refuses to sign at all. The book also lists the BIP118 proposal for new flags, which is not part of Bitcoin's rules [AH8] [B143].")), None),

 ("SignatureEncoding", "Signature encoding (DER)", 3, "SignatureChecking", ("30 <len> 02 <len r> r 02 <len s> s <hash type>", "An ECDSA signature is the pair of integers r and s written in DER, the Distinguished Encoding Rules, followed by one hash-type byte; Bitcoin requires the strict form of DER and policy requires the lower of the two possible values of s.",
   (PROG("tx = bytes.fromhex('" + TX170 + "')\nn = tx[41]; push = tx[42:42 + n]; sig = push[1:]\nresult = (hex(sig[0]), sig[1], sig[3], sig[5 + sig[3]], sig[-1])"), "('0x30', 68, 32, 32, 1)")), P(
  (W, "An ECDSA signature is two numbers, r and s, and the way they are written as bytes is a rule of the protocol. The book says that for ECDSA the encoding uses an international standard called the Distinguished Encoding Rules, DER, while for schnorr signatures a simpler serialization is used [AH8]. The bytes are: 0x30, the length of what follows, 0x02, the length of r, r, 0x02, the length of s and s; Bitcoin appends one more byte, the hash type. The input script of the block 170 payment holds exactly such a push: 70 bytes of DER and the hash type 1."),
  (Y, "The encoding matters because a signature that can be written in more than one way is a malleable signature. Before BIP66, the OpenSSL library that Bitcoin used accepted some encodings that were not strict DER, and a third party could rewrite a valid signature into another valid form and change the transaction identifier. BIP66 made strict DER a consensus rule; Bitcoin Core's chain parameters record that it applies from height 363,725, and the repair is also visible in the standard relay policy, which adds the rule that the number s be at most half the order of the curve [B66] [BCL] [B146]."),
  (H, "A parser reads the sequence in order and rejects anything unexpected. The example prints the first byte 0x30, the length 68 of the content, the length 32 of r, the length 32 of s and the hash-type byte 1 for the real signature. The low-S rule rests on a property of ECDSA stated by BIP146: taking the negative of s modulo the curve order gives another valid signature, so a signature with the larger of the two values can be trivially replaced by one with the smaller [B146]."),
  (K, "BIP146, which proposed LOW_S and NULLFAIL as consensus rules, has the status Closed; the rules are nevertheless in force as standardness rules, because Bitcoin Core's standard verification flags include LOW_S and NULLFAIL, so a transaction that breaks them is valid in a block but is not relayed. Taproot signatures are not DER: a BIP340 signature is 64 bytes with an optional 65th byte for the hash type [BCQ] [B340]."),
 ), None),
]

CHECKS_B = [
 Qb(BK, "The original description of Bitcoin used a public key for authorization.", "Alice paid Bob by putting his public key in the output of a transaction.", "Authentication came from Bob in the form of a signature that committed to a", "spending transaction"),
 Qb(BK, "pay to public key hash (P2PKH) script uses an output script that", "contains a hash that commits to a public key.", "P2PKH is best known as", "the basis for a legacy Bitcoin address", "A P2PKH output can be spent by", "presenting a public key that matches the hash commitment and a digital", "signature created by the corresponding private key"),
 Qb(BK, "OP_DUP OP_HASH160 <Key Hash> OP_EQUALVERIFY OP_CHECKSIG", "The +Key Hash+ is the data that would be encoded into a legacy base58check", "address.", "begins with [.keep-together]#a \"1.\"#"),
 Qb(BK, "<Signature> <Public Key>", "<Sig> <Pubkey> OP_DUP OP_HASH160 <Hash> OP_EQUALVERIFY OP_CHECKSIG"),
 Qb(BK, "first applying the SHA256 hashing algorithm and then applying", "the RIPEMD-160 algorithm on the result"),
 Qb(BK, "P2WPKH outputs must be constructed from the hash of a", "_compressed_ public key. Uncompressed public keys are nonstandard in", "segwit", "it may be", "unspendable and you may lose funds."),
 Qb("ch08_signatures.adoc", "the \"message\" being", "signed is the transaction, or more accurately a hash of a specific", "subset of the data in the transaction, called the _commitment hash_"),
 Qb("ch08_signatures.adoc", "returns ++TRUE++ if the signature is valid for this message and public key", "Only the controller of", "the private key that generated this public key could have produced this", "signature on this transaction."),
 Qb("ch08_signatures.adoc", "For ECDSA", "signatures, the encoding uses an international standard encoding scheme", "_Distinguished Encoding Rules_, or _DER_.  For schnorr signatures, a", "simpler serialization format is used."),
 Qb("ch08_signatures.adoc", "The +SIGHASH+ flag is a single byte", "that is appended to the signature.", "There are three +SIGHASH+ flags: +ALL+, +NONE+, and +SINGLE+", "+SIGHASH_ANYONECANPAY+", "has the value +0x80+", "applied by bitwise OR"),
 Qb("ch08_signatures.adoc", "By including the", "+SIGHASH+ flag itself, the signature commits the", "+SIGHASH+ type as well, so it can't be changed (e.g., by a miner)."),
 Qb("ch08_signatures.adoc", "a copy of the transaction is made and certain fields within are", "either omitted or truncated", "The +SIGHASH+ flag is included in the serialized", "transaction data and the result is hashed."),
 Qb("ch08_signatures.adoc", "construction can be used to make a", "funds can construct a transaction with a single output", "\"bearer check\" or", "\"blank check\"", "\"dust", "collector.\"", "BIP118"),
 Qb("ch08_signatures.adoc", "Simple wallet applications", "sign with [.keep-together]#+SIGHASH_ALL+# flags."),
 Qe("bip-0066.mediawiki", "strict DER"),
 Qe("bip-0146.mediawiki", "Inherent ECDSA signature malleability", "taking the negative of the number S inside (modulo the curve order) does not invalidate it", "We require that the S value inside ECDSA signatures is at most the curve order divided by 2", "If an <code>OP_CHECKSIG</code> is trying to return a <code>FALSE</code> value to the stack, we require that the relevant signature must be an empty byte array.", "Status: Closed"),
 Qe("bip-0143.mediawiki", "In the original algorithm, a <code>uint256</code> of <code>0x0000......0001</code> is committed if the input index for a <code>SINGLE</code> signature is greater than or equal to the number of outputs. In this BIP a <code>0x0000......0000</code> is committed"),
 Qe("bip-0342.mediawiki", "If the signature is not the empty vector, the opcode is counted towards the sigops budget"),
 Qc("src/script/interpreter.cpp", "if (nIn >= txTo.vout.size()) {", "//  nOut out of range", "return uint256::ONE;"),
 Qc("src/script/interpreter.h", "// Signature(s) must be empty vector if a CHECK(MULTI)SIG operation failed", "SCRIPT_VERIFY_NULLFAIL,", "// Passing a non-strict-DER signature or one with S > order/2 to a checksig operation causes script failure", "SCRIPT_VERIFY_LOW_S,"),
 Qc("src/policy/policy.h", "SCRIPT_VERIFY_NULLFAIL |", "SCRIPT_VERIFY_LOW_S |", "SCRIPT_VERIFY_CLEANSTACK |"),
 Qc("src/kernel/chainparams.cpp", "consensus.BIP66Height = 363725;"),
 Qc("src/script/solver.cpp", "TxoutType::PUBKEY", "TxoutType::PUBKEYHASH"),
 Qc("src/script/interpreter.cpp", "case OP_HASH160:", "CHash160().Write(vch).Finalize(vchHash);"),
 Qc("src/script/interpreter.cpp", "case OP_CHECKSIG:", "case OP_CHECKSIGVERIFY:", "fSuccess = checker.CheckECDSASignature(vchSig, vchPubKey, scriptCode, sigversion);"),
 # the real bytes
 X("L.parse_tx(C.tx_record('f4184fc59640')[0]).txid()", "f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16"),
 X("C.tx_record('f4184fc59640')[0] == " + repr(TX170), True),
 X("(lambda r: (r['block_height'], __import__('datetime').datetime.fromtimestamp(r['block_time'], __import__('datetime').UTC).strftime('%Y-%m-%d')))(C.ev_json('mainnet_landmarks_v1_0_0.json')['transactions'][0])", (170, "2009-01-12")),
 X("(lambda t: ([v for v, s in t.vout], len(t.vin[0][2]), [len(s) for v, s in t.vout]))(L.parse_tx(C.tx_record('f4184fc59640')[0]))", ([1000000000, 4000000000], 72, [67, 67])),
 X("C.tx_record('f4184fc59640')[1]", [(5000000000, SPK170)]),
 X("(lambda t, sp: L.verify_input(t, 0, [(a, bytes.fromhex(s)) for a, s in sp], L.MAINNET_FLAGS))(L.parse_tx(C.tx_record('f4184fc59640')[0]), C.tx_record('f4184fc59640')[1])", "OK"),
 X("L.classify(bytes.fromhex(" + repr(SPK170) + "))[0]", "pubkey"),
 X("(lambda sig: (L.is_valid_der(sig), L.is_low_s(sig), len(sig), sig[-1]))([o[2] for o in L.get_ops(L.parse_tx(C.tx_record('f4184fc59640')[0]).vin[0][2])][0])", (True, True, 71, 1)),
 X("L.hash160(L.pubkey_serialize(L.G)).hex()", "751e76e8199196d454941c45d1b3a323f1433bd6"),
 X("L.b58check_encode(0, L.hash160(L.pubkey_serialize(L.G)))", "1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH"),
 X("L.hash160(L.pubkey_serialize(L.G, False)).hex() != L.hash160(L.pubkey_serialize(L.G)).hex()", True),
 X("(len(L.pubkey_serialize(L.G)), len(L.pubkey_serialize(L.G, False)))", (33, 65)),
 X("L.ripemd160_pure(b'abc') == __import__('hashlib').new('ripemd160', b'abc').digest()", True),
 X("L.hash160(b'abc').hex()", "bb1be98c142444d7a56aa3981c3942a978e4dc33"),
 X("(lambda t, sp: (L.hash160([o[2] for o in L.get_ops(t.vin[0][2])][1]).hex(), sp[0][1][6:46]))(L.parse_tx(C.tx_record('a1075db55d41')[0]), C.tx_record('a1075db55d41')[1])", ("05bf3a3aea6335a3949c0a351ff3afcba884e125", "05bf3a3aea6335a3949c0a351ff3afcba884e125")),
 X("(lambda t, sp: [len(s[2]) if len(s) > 2 else 0 for s in [(0, 0, o[2]) for o in L.get_ops(t.vin[0][2])]])(L.parse_tx(C.tx_record('a1075db55d41')[0]), C.tx_record('a1075db55d41')[1])", [73, 65]),
 X("(lambda tr: [len(t[2]) for t in tr])(__import__('functools').reduce(lambda a, f: f(a), [lambda tr: tr], (lambda tx, sp: (lambda tr: (L.verify_input(tx, 0, [(a, bytes.fromhex(s)) for a, s in sp], L.MAINNET_FLAGS, trace=tr), tr)[1])([]))(L.parse_tx(C.tx_record('a1075db55d41')[0]), C.tx_record('a1075db55d41')[1])))", [1, 2, 3, 3, 4, 2, 1]),
X("L.classify(bytes.fromhex('76a914' + '00' * 20 + '88ac'))[0]", "pubkeyhash"),
X("(C.census(L)['pubkeyhash'], C.census(L)['witness_v0_keyhash'], sum(C.census(L).values()))", (194, 626, 1022)),
 # signature behaviour, with the real rules
 X("(lambda tx, sp: (lambda t2: (L.verify_input(t2, 0, sp, L.MAINNET_FLAGS), L.verify_input(t2, 0, sp, L.MAINNET_FLAGS | {'NULLFAIL'})))(__import__('copy').deepcopy(tx)))(*(lambda t, s: (t, [(a, bytes.fromhex(x)) for a, x in s]))(L.parse_tx(C.tx_record('a1075db55d41')[0]), C.tx_record('a1075db55d41')[1])) == ('OK', 'OK')", True),
 X("(lambda tx, sp: (lambda ss: (setattr(tx, 'vin', [(tx.vin[0][0], tx.vin[0][1], bytes(ss), tx.vin[0][3])] + tx.vin[1:]), (L.verify_input(tx, 0, sp, L.MAINNET_FLAGS), L.verify_input(tx, 0, sp, L.MAINNET_FLAGS | {'NULLFAIL'})))[1])(bytearray(tx.vin[0][2][:8] + bytes([tx.vin[0][2][8] ^ 1]) + tx.vin[0][2][9:])))(*(lambda t, s: (t, [(a, bytes.fromhex(x)) for a, x in s]))(L.parse_tx(C.tx_record('a1075db55d41')[0]), C.tx_record('a1075db55d41')[1]))", ("EVAL_FALSE", "SIG_NULLFAIL")),
 X("(lambda sig: (L.is_valid_der(sig), L.is_low_s(sig)))(L.ecdsa_sign(1, L.sha256(b'Satoshi Nakamoto')) + b'\\x01')", (True, True)),
 X("(L.N // 2) - 1 < L.N // 2 and hex(L.N)[-7:] == '0364141'", True),
 X("(lambda d: (len(d), sum(1 for e in d if len(e) == 5)))(C.core_json('src/test/data/sighash.json'))", (501, 500)),
 X("(lambda d: all(L.sighash_legacy(bytes.fromhex(e[1]), L.parse_tx(e[0]), e[2], e[3] & 0xffffffff)[::-1].hex() == e[4] for e in d[1:51]))(C.core_json('src/test/data/sighash.json'))", True),
 X("[hex(v | f) for f in (0, 0x80) for v in (1, 2, 3)]", ['0x1', '0x2', '0x3', '0x81', '0x82', '0x83']),
]
