"""SEN0401 chapter 5, corpus text part D (version 1.0.0): the branch 'Hierarchical deterministic wallet', first half - the master keys made from
the seed (HMAC-SHA512, master private key, master chain code) and the child key derivation functions (chain code, index, normal and hardened
private derivation, public derivation, what a child key alone can do). Markers such as [AH] become author-year strings."""
from sen0401_ch05_common_v1_0_0 import *

SEED1 = "000102030405060708090a0b0c0d0e0f"            # BIP32 test vector 1
_HM = "__import__('hmac').new(b'Bitcoin seed', bytes.fromhex('%s'), __import__('hashlib').sha512).hexdigest()" % SEED1
# the left half of the HMAC of the parent chain code for the normal child m/0H/1 of BIP32 test vector 1, as data
IL_0H1 = "4eb9d78157bae7a24115001621c4d91e3a3110e11e143c5259eaa4e55c5ec4bf"
K_0H = "edb2e14f9ee77d26dd93b4ecede8d16ed408ce149b6cd80b0715a2d911a0afea"
NORD = "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141"
# a small elliptic curve, written out so that the program runs in the reader's browser as well
SMALL = ("p = 97\n"
         "def add(P, Q):\n"
         "    if P is None: return Q\n"
         "    if Q is None: return P\n"
         "    if P[0] == Q[0] and (P[1] + Q[1]) % p == 0: return None\n"
         "    m = (3 * P[0] * P[0] * pow(2 * P[1], -1, p) if P == Q else (Q[1] - P[1]) * pow(Q[0] - P[0], -1, p)) % p\n"
         "    x = (m * m - P[0] - Q[0]) % p\n"
         "    return (x, (m * (P[0] - x) - P[1]) % p)\n"
         "def mul(n, P):\n"
         "    R = None\n"
         "    while n:\n"
         "        if n & 1: R = add(R, P)\n"
         "        P = add(P, P); n >>= 1\n"
         "    return R\n"
         "G = (1, 28)\n"
         "k, t = 7, 13\n"
         "result = (add(mul(t, G), mul(k, G)) == mul(k + t, G), mul(k, G))")
HARD_IO = ("import hashlib, hmac\n"
           "N = %s\n"
           "I = hmac.new(b'Bitcoin seed', bytes.fromhex('%s'), hashlib.sha512).digest()\n"
           "k, c = int.from_bytes(I[:32], 'big'), I[32:]\n"
           "J = hmac.new(c, b'\\x00' + k.to_bytes(32, 'big') + (2 ** 31).to_bytes(4, 'big'), hashlib.sha512).digest()\n"
           "result = hex((int.from_bytes(J[:32], 'big') + k) %% N)[:18]" % (NORD, SEED1))

NODES_D = [
 ("HdWallet", "Hierarchical deterministic wallet", 1, None, None, P(
  (W, "A hierarchical deterministic wallet, which the chapter and the standards abbreviate to HD wallet, is a wallet whose keys form a tree, every node of which is computed from the seed. The book's glossary calls the hierarchical deterministic protocol the key creation and transfer protocol of BIP32, which allows creating child keys from parent keys in a hierarchy, and an HD wallet a wallet using that protocol [AHG]. This branch is the detailed treatment the chapter promised when it first mentioned the idea: how the master keys are made from the seed, and how any key can produce children."),
  (Y, "The branch matters because the tree is what the whole chapter is for. A single seed is a good backup only if everything else can be recomputed from it, and BIP32 is the rule by which it is recomputed. BIP32's own motivation gives the two reasons it exists: deterministic wallets do not require frequent backups, and elliptic curve mathematics permits schemes in which public keys can be calculated without revealing private keys, which lets, for example, a web shop's server generate fresh addresses for each order without having access to the keys needed for spending [B32]. The second reason is also why the tree has to be a tree and not a single chain: sharing one chain is all or nothing, whereas a hierarchy allows selective sharing [B32]."),
  (E, "The reader has met the tree twice already: in the overview of key generation methods in the first branch, and in the key paths of the wallet that Bitcoin Core 31.1 created for this chapter, whose first address was reported at the path m/84h/0h/0h/0/0 [B31]. Bitcoin Core's documentation lists BIP32 as implemented since version 0.13.0 [BC]. The chapter says that every modern Bitcoin wallet of which its authors are aware uses this scheme by default [AH]."),
  (H, "The branch has four groups. The master keys group turns the seed into the root of the tree with one keyed hash. The child derivation group gives the functions that make a child from a parent, in the two private forms, normal and hardened, and in the public form, and explains what a child key can and cannot be used for on its own. The extended keys group explains the pair of key and chain code that is passed around as one object, and how it is written as the xprv and xpub strings a reader will have seen. The tree navigation group gives the path notation and the two standards, BIP43 and BIP44, that fix what the levels of the tree mean."),
  (K, "One warning applies to the whole branch. The tree is enormous and nothing marks which parts of it a wallet used: the chapter points out that in a BIP32 tree there are approximately four billion first-level keys, each with its own four billion children, and so on, so it is not possible for a wallet application to generate even a small fraction of every possible key, which means that recovering from data loss requires knowing more than the recovery code and the algorithms, it also requires knowing which paths were used [AH]. That problem is the subject of the next branch, and a reader should keep it in mind while reading this one.")), None),

 ("MasterKeys", "Master keys from the seed", 2, "HdWallet", None, P(
  (W, "This group covers the one step that turns a seed into the root of a key tree. The chapter states it in three short sentences: the root seed is input into the HMAC-SHA512 algorithm and the resulting hash is used to create a master private key and a master chain code; the master private key then generates a corresponding master public key using the normal elliptic curve multiplication that chapter 4 introduced; and the master chain code is used to introduce entropy in the function that creates child keys from parent keys [AH]."),
  (Y, "The step deserves its own group because it is where two objects appear that the rest of the branch keeps together. Everything below the root is derived, so if the master private key and the master chain code are right, the whole tree is right; if either is wrong, nothing below it is recoverable. The group also introduces the keyed hash that does all the work, which is used again at every level of the tree, so understanding it once is enough for the entire standard."),
  (H, "The three sections take the parts in order. The keyed hash function HMAC-SHA512 is explained first, with the fixed key BIP32 uses; then the left half of its output, which becomes the master private key; then the right half, which becomes the master chain code. Each section recomputes its part from the seed of BIP32's first test vector, so a reader can follow the arithmetic and compare it with the standard's own published values.")), None),

 ("HmacSha512", "HMAC-SHA512", 3, "MasterKeys", ("the keyed hash of the test vector's seed",
   "HMAC-SHA512 is a keyed hash: it combines a key and a message into 64 bytes that cannot be produced without the key, and BIP32 uses it both to make the master keys and to derive every child.",
   (_HM + "[:16]", "'e8f32e723decf405'")), P(
  (W, "HMAC is a way of using an ordinary hash function with a key, so that the output depends on both. Its specification defines the construction exactly: to compute HMAC over the data, one computes the hash of the key combined with an outer pad together with the hash of the key combined with an inner pad and the text, with the key padded with zeros to the hash's block length [R2104]. HMAC-SHA512 is that construction with SHA-512 as the hash, so its output is 64 bytes. BIP32 names it as the function used at every derivation and notes that it is specified in an RFC [B32]."),
  (Y, "A keyed hash is needed because a plain hash would not keep the tree private. If children were derived by hashing the parent key alone, anyone who learned a child's position could derive it; by mixing in a second 32-byte value, the chain code, the standard makes the derivation depend on a secret that is not the key itself. BIP32 says this in its own words when it explains why extended keys exist: in order to prevent the derived keys from depending solely on the key itself, both private and public keys are first extended with an extra 256 bits of entropy [B32]."),
  (E, "The reader meets this function three times in the chapter: making the master keys, deriving a normal child and deriving a hardened child, where the chapter says the parent public key, chain code and index number are combined and hashed with the HMAC-SHA512 algorithm to produce a 512-bit hash [AH]. It is also the function inside PBKDF2 in the previous branch, and the function Electrum uses with the key 'Seed version' to derive its version number [B39] [EL]. The worked example applies it as BIP32's master key generation does: the fixed key is the twelve characters of the text Bitcoin seed, the message is the seed, and the first eight bytes of the result are e8f32e723decf405, which agree with the standard's own first test vector."),
  (H, "The mechanism to remember is the shape of the output and how it is split. HMAC-SHA512 returns 64 bytes, which BIP32 always divides into two 32-byte halves that it calls I-left and I-right; the left half is used as key material and the right half becomes a chain code [B32]. Because SHA-512 is a hash function, neither half reveals anything about the inputs, and because the two halves come from one computation, knowing one does not give the other. The key of the HMAC is the chain code at every derivation except the first, where it is the constant 'Bitcoin seed'."),
  (K, "Two confusions arise here. The first is between the two arguments: the chain code is the key and the key material is part of the message, which is the reverse of what the names suggest, and swapping them yields a plausible but incompatible wallet. The second is to treat HMAC as encryption: nothing is recoverable from its output, which is exactly why the derivation is one-way and why a child key cannot be used to find its parent, as the chapter states when it says the derivation function is a one-way function [AH].")), None),

 ("MasterPrivateKey", "Master private key", 3, "MasterKeys", ("the left half of the hash, as a number",
   "The master private key is the left 32 bytes of HMAC-SHA512 over the seed, read as a 256-bit number; it is the root of the tree and is written m.",
   (_HM + "[:64]", "'e8f32e723decf4051aefac8e2c93c9c5b214313817cdb01a1494b917c8436b35'")), P(
  (W, "The master private key is the private key at the root of the tree. The chapter calls it m and says that the root seed is input into HMAC-SHA512 and the resulting hash is used to create a master private key and a master chain code, and that the master private key then generates a corresponding master public key, written M, by the ordinary multiplication by the generator point [AH]. BIP32 states the same as a procedure: split the HMAC output into two 32-byte sequences and use the left one, read as a 256-bit number, as the master secret key [B32]."),
  (Y, "This key matters because it is the one key from which every other can be reached, and therefore the one key whose loss or leak is total. BIP32 draws the consequence when it discusses what care extended keys need: knowing an extended private key allows reconstruction of all descendant private keys and public keys [B32]. The chapter's advice about hardened derivation at the first level follows from the same fact: as a best practice, the level-1 children of the master keys are always derived through hardened derivation to prevent compromise of the master keys [AH]."),
  (E, "A reader meets the master private key as the string that begins xprv, which the extended keys group explains, and as the letter m at the head of every path. The worked example computes it from the standard's own first test vector: the left 32 bytes of the keyed hash of the seed 000102030405060708090a0b0c0d0e0f are e8f32e72...c8436b35, and the claims of this chapter check that serialising this number with its chain code gives exactly the xprv string the standard prints for chain m [B32]."),
  (H, "The mechanism is a reading of bytes as a number, with one validity test. BIP32 says that if the left half, read as a number, is zero or greater than or equal to the order of the curve, the master key is invalid [B32]; the order is the count of points the generator reaches, a number just below 2 to the 256, so the test fails only with vanishing probability. From the master private key the master public key follows by the multiplication of chapter 4, and the pair of key and chain code is what the next sections treat as a single object."),
  (K, "The master private key is not the seed, and the distinction is practical. The seed can be shorter and is what a recovery code encodes; the master key is derived from it and cannot be turned back into it. A wallet that exports an xprv is therefore exporting something that cannot be written as words, and a user who holds only an xprv has a complete wallet but no recovery code. BIP32 also notes that a serialised extended key that mixes up the private and public version bytes is invalid, and its fifth test vector exists to make implementations reject exactly such strings [B32].")), None),

 ("MasterChainCode", "Master chain code", 3, "MasterKeys", ("the right half of the hash",
   "The master chain code is the right 32 bytes of HMAC-SHA512 over the seed: 256 bits of extra entropy that make every derivation depend on more than the key.",
   (_HM + "[64:]", "'873dff81c02f525623fd1fe5167eac3a55a049de3d314bb42ee227ffed37d508'")), P(
  (W, "The master chain code is the second half of the same hash. The chapter writes it c and says that it is used to introduce entropy in the function that creates child keys from parent keys [AH]. BIP32 says to use the right 32-byte sequence as the master chain code, and explains what a chain code is for: both private and public keys are extended with an extra 256 bits of entropy, an extension called the chain code, which is identical for corresponding private and public keys and consists of 32 bytes [B32]."),
  (Y, "Without it, a public key would be enough to enumerate a family. The chapter makes the point when it introduces chain codes generally: the chain code introduces deterministic random data so that knowing the index and a child key is not sufficient to derive other child keys, and knowing a child key does not make it possible to find its siblings unless the chain code is also known [AH]. The chain code is therefore a secret in its own right, even though it is not a key and cannot sign anything."),
  (E, "A reader meets the chain code inside every extended key: an xprv or xpub string contains 32 bytes of chain code beside the key, which is why such strings are so much longer than an address [B32]. The worked example computes the master chain code of the standard's first test vector, 873dff81...ed37d508, the right half of the hash whose left half was the master private key. The same value is what the claims of this chapter feed into the derivations that reproduce the standard's published keys."),
  (H, "Mechanically the chain code is the HMAC key at the next level. Each derivation calls HMAC-SHA512 with the parent's chain code as the key, and the right half of the result becomes the child's chain code, so each node of the tree has its own [B32]. Because the chain code of a private key and of its public counterpart are the same, a holder of the extended public key can carry out the same hash for a normal child, which is what makes public derivation possible; the hardened variant breaks that symmetry deliberately."),
  (K, "The chain code is the part users forget, and forgetting it is fatal to recovery in two ways. A key without its chain code cannot derive anything, which the chapter states for the child case: without the child chain code, the child key cannot be used to derive any grandchildren [AH]. And a chain code that leaks turns a single leaked child private key into a disaster, which is the risk BIP32 calls the weakness that may not be immediately obvious: knowledge of a parent extended public key plus any non-hardened private key descending from it is equivalent to knowing the parent extended private key [B32].")), None),

 ("ChildDerivation", "Deriving child keys", 2, "HdWallet", None, P(
  (W, "This group covers the functions that make a child key from a parent. The chapter introduces them as the child key derivation functions, abbreviated CKD, and says that they are based on a one-way hash function that combines three things: a parent private or public key, a seed called a chain code of 256 bits, and an index number of 32 bits [AH]. BIP32 defines three of them: from a private parent to a private child, from a public parent to a public child, and from a private parent to a public child, and states plainly that the fourth, from a public parent to a private child, is not possible [B32]."),
  (Y, "The group is the mathematical centre of the chapter. Everything that makes an HD wallet useful, the ability to hand a server an extended public key, the ability to keep private keys on a device that never sees the internet, the ability to restore a whole wallet from one code, is a consequence of how these three functions relate. The group is also where the one serious hazard of the design lives, the leak that hardened derivation exists to prevent, so a reader who skips it will not understand why paths contain apostrophes."),
  (H, "The sections begin with what all the functions share: the combination of key, chain code and index, and the splitting of the hash. The chain code and the index each then get a section, because each carries a rule of its own. Private derivation follows, in its normal and hardened forms, then public derivation, which exists only for normal children. The group closes with what a child key on its own is good for, which the chapter asks and answers in one short section, and which explains why a leaf of the tree is indistinguishable from a randomly generated key.")), None),

 ("ChildKeyDerivation", "Child key derivation", 3, "ChildDerivation", ("512 bits split into two halves of 32 bytes",
   "A child is derived by hashing the parent key, the parent chain code and an index with HMAC-SHA512 and splitting the 512-bit result: the left half makes the child key, the right half is the child chain code.",
   ("(512 // 2, 512 // 2 // 8)", "(256, 32)")), P(
  (W, "Child key derivation is the operation that produces one child of one parent. The chapter describes the inputs and the split in two sentences: the parent public key, chain code and index number are combined and hashed with HMAC-SHA512 to produce a 512-bit hash, and this hash is split into two 256-bit halves, of which the right half becomes the chain code for the child while the left half is added to the parent private key to produce the child private key [AH]. BIP32 gives the same in its notation, splitting the output into I-left and I-right [B32]."),
  (Y, "The uniformity is the point. One function, differing only in what is fed to it, generates the whole tree, so an implementation that is correct once is correct everywhere, and a reader who follows it once can follow every path. The split is what makes the recursion work: because each derivation produces a new chain code as well as a new key, the child is itself a complete parent and the tree can be extended to any depth, which the chapter states when it says that each child can in turn become a parent and create its own children, in an infinite number of generations [AH]."),
  (E, "A reader meets the operation in every path they read: each slash in m/84h/0h/0h/0/0 is one call of this function. The worked example records the arithmetic of the split that every call performs: the 512 bits of the hash divided in two give 256 bits for each half, which is 32 bytes. The claims of this chapter carry out the full derivations of BIP32's first and second test vectors and compare the results with the strings the standard publishes, so the description above is checked at six depths for two different seeds [B32]."),
  (H, "The left half is not used directly as the key: it is added to the parent key. BIP32 says that the returned child key is the left half, read as a number, plus the parent key, taken modulo the order of the curve, and that the returned chain code is the right half; it adds the validity rule that if the left half is greater than or equal to the order, or the child key is zero, the result is invalid and the next index should be used, with a probability lower than one in 2 to the 127 [B32]. Addition rather than multiplication was a deliberate change made in 2013, which the standard's own change log records as faster and easier to implement [B32]."),
  (K, "Two properties of the function should be read carefully. It is one-way, so the chapter can say that because the derivation function is a one-way function the child key cannot be used to find the parent key, nor any siblings [AH]; but that statement holds for the child key alone, not for a child key together with the parent's extended public key, which is the leak discussed under hardened derivation [B32]. And the index is an input, not a property of the key: the same parent gives a completely different child for every index, and nothing in a child shows which index produced it.")), None),

 ("ChainCode", "Chain code", 3, "ChildDerivation", ("256 bits beside every key",
   "A chain code is the 32 bytes of extra entropy carried beside a key so that derivation depends on more than the key; a key's children cannot be found without it.",
   ("len(bytes.fromhex('873dff81c02f525623fd1fe5167eac3a55a049de3d314bb42ee227ffed37d508')) * 8", "256")), P(
  (W, "A chain code is 32 bytes that travel with a key and take part in deriving its children. The chapter lists it among the three inputs of the derivation function as a seed called a chain code of 256 bits, and explains the name's logic: the initial chain code at the root of the tree is made from the seed, while subsequent child chain codes are derived from each parent chain code [AH]. The worked example counts the bytes of the master chain code of BIP32's first test vector and confirms the 256 bits."),
  (Y, "The chain code is what separates an HD wallet from a mere sequence of hashes. The chapter states the property it provides twice: the chain code is used to introduce deterministic random data to the process, so that knowing the index and a child key is not sufficient to derive other child keys; and knowing a child key does not make it possible to find its siblings unless you also have the chain code [AH]. Because the same chain code belongs to a private key and to its public counterpart, it is also the reason an extended public key can derive a branch of public keys."),
  (E, "A reader meets the chain code in three forms. It is 32 of the 78 bytes of a serialised extended key [B32]; it is the key argument of every HMAC in the derivation; and it is the thing a wallet must store or recompute for every node it uses. The chapter notes the consequence for a child key handled on its own: you need both the child private key and the child chain code to start a new branch and derive grandchildren [AH]."),
  (H, "Mechanically a chain code is produced and consumed in the same way at every level: the right half of the derivation's hash becomes the child's chain code, and that chain code is the HMAC key for the child's own children [B32]. The root is the only exception, where the chain code comes from the right half of the hash of the seed under the fixed key 'Bitcoin seed'. Nothing else is done to a chain code: it is never hashed on its own, never published, and never used to sign."),
  (K, "The chain code is secret even though it is not a key, and that is the mistake to avoid. BIP32's implications section says that leaking a private key means access to coins while leaking a public key can mean loss of privacy, and that somewhat more care must be taken with extended keys because they correspond to an entire subtree [B32]. The chapter adds the sharpest consequence: because an extended public key contains the chain code, a single leaked child private key together with a parent chain code reveals all the private keys of all the children, and can even be used to deduce the parent private key [AH].")), None),

 ("IndexNumber", "Index number", 3, "ChildDerivation", ("two ranges in 32 bits",
   "The index is the 32-bit number that selects which child is derived; indices below 2 to the 31 are normal children and those at or above it are hardened, displayed with an apostrophe or an h.",
   ("(2 ** 31 - 1, 2 ** 31, 2 ** 32 - 1)", "(2147483647, 2147483648, 4294967295)")), P(
  (W, "The index number is the third input of the derivation function and the one that says which child is wanted. The chapter devotes a section to it: the index number used in the derivation function is a 32-bit integer, and to distinguish keys created through the normal function from those derived through hardened derivation the number is split into two ranges; indices between 0 and 2 to the 31 minus 1, that is 0x0 to 0x7FFFFFFF, are used only for normal derivation, and indices between 2 to the 31 and 2 to the 32 minus 1, that is 0x80000000 to 0xFFFFFFFF, only for hardened derivation [AH]. The worked example prints the three boundary values of those ranges."),
  (Y, "The split is a piece of engineering that makes a security property visible in a path. Because the range decides the derivation, a reader can tell from an index alone whether the parent's private key was needed, and therefore whether the branch above can be shared as an extended public key. BIP32 states the counts the split produces: each extended key has 2 to the 31 normal child keys and 2 to the 31 hardened child keys, the normal ones using indices 0 through 2 to the 31 minus 1 [B32]."),
  (E, "A reader meets indices in the displayed form rather than the numeric one. The chapter explains the convention: to make the number easier to read, the index for hardened children is displayed starting from zero but with a prime symbol, so the first normal child is 0 and the first hardened child, index 0x80000000, is displayed as 0 followed by a prime; in a sequence the second hardened key has index 0x80000001 and is displayed as 1 with a prime; and when you see an index i with a prime it means 2 to the 31 plus i [AH]. In plain text the prime is written as an apostrophe or as the letter h, and the chapter recommends h where an apostrophe would have a special meaning, as in output script descriptors used in a shell [AH]."),
  (H, "The mechanism is a comparison and a serialisation. BIP32's derivation first checks whether the index is at least 2 to the 31 and takes the hardened branch if so; the index is then serialised as four bytes, most significant first, and appended to the key material before hashing [B32]. The two notations are therefore the same number: 0h is 2147483648 and 1h is 2147483649, which is why the evidence files of this chapter show Bitcoin Core writing paths such as m/84h/0h/0h/0/0 with the letter h where the book writes a prime [B31]."),
  (K, "Three slips are common. The first is to read 2147483647 as the number of children of a key: the chapter prints that figure, saying that each parent key can have 2,147,483,647 children and giving 2 to the 31 as the value, but 2 to the 31 is 2147483648, and BIP32 counts 2 to the 31 normal children with indices 0 to 2 to the 31 minus 1 [AH] [B32]. The second is to read the prime as part of the number; it is a notation for adding 2 to the 31. The third is to assume the two notations are interchangeable everywhere: a descriptor in a shell should use h, because an apostrophe would be consumed by the shell [AH].")), None),

 ("PrivateChildDerivation", "Private child key derivation", 3, "ChildDerivation", ("the left half added to the parent key",
   "A private child is the sum, modulo the order of the curve, of the parent private key and the left half of the derivation hash; the right half is the child's chain code.",
   ("hex((int('%s', 16) + int('%s', 16)) %% %s)[:18]" % (IL_0H1, K_0H, NORD), "'0x3c6cb8d0f6a264c9'")), P(
  (W, "Private child key derivation is the function that takes a parent private key with its chain code and an index and returns a child private key with its own chain code. The chapter describes the normal case: the parent public key, the chain code and the index number are combined and hashed with HMAC-SHA512 to produce a 512-bit hash, whose right half becomes the child's chain code and whose left half is added to the parent private key to produce the child private key, illustrated with the index set to zero to produce the first child of the parent [AH]."),
  (Y, "This is the function a signing device runs. A wallet that knows a path and holds the master private key with its chain code can reproduce any private key it ever used, which is the whole promise of a seed backup; and because the arithmetic is addition modulo a number, it is cheap enough for a small device to do many times. The chapter adds the organisational gain in the same section: changing the index extends the parent and creates the other children in the sequence, so one parent organises a whole chain of keys [AH]."),
  (E, "The worked example is one step of BIP32's first test vector, done as arithmetic. For the normal child of index 1 below m/0h, the left half of the derivation hash is 4eb9d781...5c5ec4bf and the parent private key is edb2e14f...11a0afea; their sum modulo the order of the curve begins 0x3c6cb8d0f6a264c9, which is the private key the standard publishes for chain m/0h/1 inside its xprv string [B32]. The claims of this chapter check the full key and the complete serialised strings for every chain of test vectors 1 and 2."),
  (H, "Two details of the mechanism are worth stating precisely. The first is what goes into the hash: for a normal child it is the compressed serialisation of the parent public key followed by the four bytes of the index, which is why the parent public key can be computed from the parent private key and nothing else is needed; for a hardened child it is a zero byte, the 32 bytes of the parent private key and the index [B32]. The second is the arithmetic: the addition is modulo the order of the curve, so the result stays a valid private key, and BIP32 notes that the earlier version of the standard multiplied by the left half instead and was changed to addition in 2013 for speed and ease of implementation [B32]."),
  (K, "The chapter's description of the inputs contains a slip a careful reader will notice. In the list of the three combined items it writes a parent private or public key, with the parenthesis uncompressed key, while BIP32 serialises the parent public key in compressed form, the 33 bytes beginning 02 or 03 [AH] [B32]. The claims of this chapter show that using the 65-byte uncompressed form gives a different child key, so the parenthesis has to be read as a slip rather than as an option. The second caution is the same as everywhere in this group: the function needs the chain code, and a private key alone derives nothing.")), None),

 ("HardenedDerivation", "Hardened child key derivation", 3, "ChildDerivation", ("the first hardened child of a test vector's master key",
   "Hardened derivation feeds the parent private key, not the parent public key, into the hash, so the resulting chain code cannot be used with a leaked child key to recover the parent.",
   (PROG(HARD_IO), "'0xedb2e14f9ee77d26'")), P(
  (W, "Hardened derivation is the alternative derivation function that breaks the relationship between the parent public key and the child chain code. The chapter introduces it as a counter to a risk and describes the change in one sentence: the hardened derivation function uses the parent private key to derive the child chain code instead of the parent public key, which creates a firewall in the parent-child sequence, with a chain code that cannot be used to compromise a parent or sibling private key; it adds that the function looks almost identical to normal private derivation except for that substitution [AH]."),
  (Y, "The risk it answers is the chapter's clearest security argument. Access to an extended public key does not give access to child private keys, but because the extended public key contains the chain code, a child private key that is known or somehow leaked can be used with the chain code to derive all the other child private keys, and worse, together with the parent chain code it can be used to deduce the parent private key [AH]. BIP32 states the same as a property its design deliberately does not have, and says that this is the reason for the existence of hardened keys and why they are used at the account level, so that a leak of account-level or lower private keys never risks compromising the master or other accounts [B32]."),
  (E, "A reader meets hardened derivation as the apostrophes and letters h in every standard path: m/44h/0h/0h, m/84h/0h/0h and the rest are hardened at their first three levels [B44] [B84]. The worked example performs one hardened derivation in full, from BIP32's own first test vector: with the master private key and chain code obtained from the seed, hashing a zero byte, the parent private key and the index 2 to the 31, then adding the left half to the parent key, gives a child private key beginning 0xedb2e14f9ee77d26, which is the key inside the xprv the standard publishes for chain m/0h [B32]. The claims of this chapter check that the whole serialised string matches."),
  (H, "The mechanism is the change of one input, with a padding byte to keep the length. BIP32 says that for a hardened child the message is a zero byte, the 32-byte parent private key and the four-byte index, and notes that the zero byte pads the private key to make it 33 bytes long, the same length as a compressed public key [B32]. Everything else is identical: the chain code is still the HMAC key, the left half is still added to the parent key and the right half still becomes the child's chain code. Because the message now contains a secret, a holder of the extended public key cannot compute it, and BIP32's public derivation function simply returns failure for such an index [B32]."),
  (K, "Hardening is not a stronger kind of key and it does not protect the child. The chapter's own summary of when to use it is the practical rule: if you want the convenience of an extended public key to derive branches of public keys without exposing yourself to the risk of a leaked chain code, derive it from a hardened parent rather than a normal one, and as a best practice the level-1 children of the master keys are always derived through hardened derivation [AH]. The cost is that nothing above a hardened step can be shared as an extended public key, which is why standard paths harden the first three levels and leave the last two normal.")), None),

 ("PublicChildDerivation", "Public child key derivation", 3, "ChildDerivation", ("the tweak added on a small curve",
   "A public child can be derived from a parent public key and chain code alone, because adding a value to a public key gives the public key of the sum, so a server can make addresses without the power to spend.",
   (PROG(SMALL), "(True, (12, 38))")), P(
  (W, "Public child key derivation is the function that produces a child public key from a parent public key and chain code, without any private key. The chapter calls it a very useful characteristic of HD wallets and says it gives two ways to derive a child public key, either from the child private key or directly from the parent public key, so that an extended public key can be used to derive all of the public keys, and only the public keys, in that branch [AH]. BIP32 defines it as CKDpub and says it is only defined for non-hardened child keys [B32]."),
  (Y, "This function is the reason the standard exists in the form it has. BIP32's motivation gives the use case: elliptic curve mathematics permits schemes where public keys can be calculated without revealing private keys, which lets a web shop let its web server generate fresh addresses for each order or each customer without giving the server access to the keys required for spending [B32]. The chapter develops the same example at length in its web store section, and lists the other case, cold storage, where the extended private key stays on paper or on a device while the extended public key is kept online [AH]."),
  (E, "The reader has already met the arithmetic in the first branch, where the chapter adds 123 to a public key and to its private key and gets a matching pair [AH]. The worked example repeats the property on a curve small enough to print: on the curve with the equation y squared equals x cubed plus 7 over the field of 97 elements, with the point (1, 28) as generator, the sum of the points for 13 and 7 equals the point for 20, and the point for 7 is (12, 38). The same identity on Bitcoin's own curve is checked by the claims of this chapter, as are the complete public derivations of BIP32's test vectors."),
  (H, "The mechanism mirrors the private function exactly. BIP32 says that for a normal child the hash is taken over the compressed parent public key and the index, the right half becomes the child chain code, and the child public key is the point for the left half added to the parent public key [B32]. Because the point for a sum of numbers is the sum of their points, this gives the same key as deriving the child private key and then multiplying, which BIP32 states as an identity and calls the fact that makes non-hardened keys useful [B32]. For a hardened index the message would need the parent private key, so the function returns failure, and the standard adds that from a public parent key to a private child key is not possible at all [B32]."),
  (K, "The convenience has the cost that the whole group has been circling. An extended public key lets its holder compute every address of a branch, so BIP32 warns that it must be treated more carefully than a regular public key, both because leaking a public key can mean loss of privacy and because of the leak that a non-hardened child private key makes possible [B32]. The chapter's account of the web store notes the benefit that remains even so: a hack of the website can only steal the funds the owner would have received in the future, not those received in the past [AH].")), None),

 ("ChildKeyIndependence", "Using a derived child key", 3, "ChildDerivation", ("2,147,483,647 siblings it cannot reach",
   "A child key on its own behaves exactly like a randomly generated key: it can make a public key, an address and signatures, but it cannot find its parent, its siblings or its own children.",
   ("2 ** 31 - 1", "2147483647")), P(
  (W, "This section answers the question the chapter asks about a child key taken out of the tree: what can it be used for on its own? The chapter's answer is short: it can be used to make a public key and a Bitcoin address, and then to sign transactions to spend anything paid to that address [AH]. Everything else it might seem to offer is excluded by the surrounding sentences, which say that the child key cannot be used to find the parent key, cannot be used to find any siblings, such as the key before or after it, and without the child chain code cannot derive any grandchildren either [AH]."),
  (Y, "The property matters for privacy and for operational safety. The chapter puts it in a tip: a child private key, the corresponding public key and the Bitcoin address are all indistinguishable from keys and addresses created randomly, and the fact that they are part of a sequence is not visible outside the wallet function that created them, so once created they operate exactly as normal keys [AH]. A payer therefore learns nothing about the receiver's wallet from an address, and a wallet can hand out a key without handing out a position in a tree."),
  (E, "A reader meets this independence whenever a single key is exported or imported. A signing device that is given a key and a path returns a signature and nothing else; a descriptor that names a single public key, as in the Bitcoin Core evidence of this chapter where one address is described by a descriptor over one 33-byte key with its origin recorded, works without any chain code [B31] [B380]. The worked example is the number of siblings a normal child cannot reach: 2 to the 31 minus 1, that is 2147483647 other normal children of the same parent."),
  (H, "The mechanism behind each prohibition is one of the facts already established. The parent cannot be recovered because the derivation runs through a one-way hash and because the subtraction that would undo it needs the left half of the hash, which needs the chain code [AH] [B32]. Siblings cannot be reached because each index gives an unrelated hash, and grandchildren cannot be derived because the child chain code is missing. BIP32 confirms the first of these as an intended security property: given a child extended private key and the index, an attacker cannot find the parent private key more efficiently than a brute force of 2 to the 256 over HMAC-SHA512 [B32]."),
  (K, "The independence holds for the child key alone, and the exception is the one this group has repeated: a non-hardened child private key together with the parent extended public key does reveal the parent extended private key, which BIP32 lists among the properties its scheme does not have [B32]. A second caution concerns what independence does not buy: because the chain of a wallet's addresses can often be linked on the blockchain by how outputs are spent, the indistinguishability of a single key is not privacy for the wallet as a whole, which is why chapter 2 of the book treats address reuse and change outputs as privacy questions.")), None),
]

CHECKS_D = [
 Qb("glossary.asciidoc", "The Hierarchical Deterministic (HD) key creation and transfer protocol (BIP32), which allows creating child keys from parent keys in a hierarchy",
    "Wallets using the Hierarchical Deterministic (HD Protocol) key creation and transfer protocol (BIP32)"),
 Qe("bip-0032.mediawiki", "Deterministic wallets do not require such frequent backups, and elliptic curve mathematics permit schemes where one can calculate the public keys without revealing the private keys",
    "This permits for example a webshop business to let its webserver generate fresh addresses (public key hashes) for each order or for each customer, without giving the webserver access to the corresponding private keys",
    "The fact that there is only one chain means that sharing a wallet happens on an all-or-nothing basis",
    "Hierarchical deterministic wallets allow such selective sharing by supporting multiple keypair chains, derived from a single root"),
 Qb("ch05_wallets.adoc", "The root seed is input into the HMAC-SHA512 algorithm and the resulting\nhash is used to create a _master private key_ (_m_) and a _master chain\ncode_ (_c_)",
    "The master private key (_m_) then generates a corresponding master public\nkey (_M_) using the normal elliptic curve multiplication process _m_ \u00d7 _G_",
    "The master chain code (_c_) is used to introduce entropy in the function that\ncreates child keys from parent keys"),
 # HMAC-SHA512 and the master keys, against BIP32 test vector 1
 (_HM + "[:16]", "'e8f32e723decf405'"),
 (_HM + "[:64]", "'e8f32e723decf4051aefac8e2c93c9c5b214313817cdb01a1494b917c8436b35'"),
 (_HM + "[64:]", "'873dff81c02f525623fd1fe5167eac3a55a049de3d314bb42ee227ffed37d508'"),
 ("len(bytes.fromhex(%s))" % _HM, "64"),
 ("len('Bitcoin seed')", "12"),
 X("W.master(bytes.fromhex('%s'))[0] == int('e8f32e723decf4051aefac8e2c93c9c5b214313817cdb01a1494b917c8436b35', 16)" % SEED1, "True"),
 X("W.serialize_xprv(*W.master(bytes.fromhex('%s')))" % SEED1,
   "'xprv9s21ZrQH143K3QTDL4LXw2F7HEK3wJUD2nW2nRk4stbPy6cq3jPPqjiChkVvvNKmPGJxWUtg6LnF5kejMRNNU3TGtRBeJgk33yuGBxrMPHi'"),
 X("W.derive_serialized(bytes.fromhex('%s'), 'm')" % SEED1,
   "('xprv9s21ZrQH143K3QTDL4LXw2F7HEK3wJUD2nW2nRk4stbPy6cq3jPPqjiChkVvvNKmPGJxWUtg6LnF5kejMRNNU3TGtRBeJgk33yuGBxrMPHi', 'xpub661MyMwAqRbcFtXgS5sYJABqqG9YLmC4Q1Rdap9gSE8NqtwybGhePY2gZ29ESFjqJoCu1Rupje8YtGqsefD265TMg7usUDFdp6W1EGMcet8')"),
 Qe("bip-0032.mediawiki", "Calculate I = HMAC-SHA512(Key = \"Bitcoin seed\", Data = S)", "Use parse<sub>256</sub>(I<sub>L</sub>) as master secret key, and I<sub>R</sub> as master chain code",
    "In case parse<sub>256</sub>(I<sub>L</sub>) is 0 or parse<sub>256</sub>(I<sub>L</sub>) ≥ n, the master key is invalid",
    "we extend both private and public keys first with an extra 256 bits of entropy. This extension, called the chain code, is identical for corresponding private and public keys, and consists of 32 bytes",
    "The HMAC-SHA512 function is specified in [http://tools.ietf.org/html/rfc4231 RFC 4231]",
    "xprv9s21ZrQH143K3QTDL4LXw2F7HEK3wJUD2nW2nRk4stbPy6cq3jPPqjiChkVvvNKmPGJxWUtg6LnF5kejMRNNU3TGtRBeJgk33yuGBxrMPHi"),
 ("len(bytes.fromhex('873dff81c02f525623fd1fe5167eac3a55a049de3d314bb42ee227ffed37d508')) * 8", "256"),
 # the derivation function, chain code, index
 Qb("ch05_wallets.adoc", "HD wallets use a _child key derivation_ (CKD)\nfunction to derive child keys from parent keys",
    "* A parent private or public key (uncompressed key)", "* A seed called a chain code (256 bits)", "* An index number (32 bits)",
    "The chain code is used to introduce deterministic random data to the\nprocess, so that knowing the index and a child key is not sufficient to\nderive other child keys",
    "Knowing a child key does not make it possible\nto find its siblings unless you also have the chain code",
    "The parent public key, chain code, and the index number are combined and\nhashed with the HMAC-SHA512 algorithm to produce a 512-bit hash. This\n512-bit hash is split into two 256-bit halves. The right-half 256 bits\nof the hash output become the chain code for the child. The left-half\n256 bits of the hash are added to the parent private key to produce the\nchild private key"),
 Qb("ch05_wallets.adoc", "Each\nparent key can have 2,147,483,647 (2^31^) children", "the other half is reserved for a\nspecial type of derivation"),
 ("(512 // 2, 512 // 2 // 8)", "(256, 32)"), ("(2 ** 31 - 1, 2 ** 31, 2 ** 32 - 1)", "(2147483647, 2147483648, 4294967295)"),
 ("2 ** 31 != 2147483647", "True"),      # the chapter prints 2,147,483,647 for 2 to the 31
 ("2 ** 31 + 2 ** 31 == 2 ** 32", "True"),
 Qb("ch05_wallets.adoc", "Index numbers between 0 and\n2^31^ &#x2013; 1 (0x0 to 0x7FFFFFFF) are used _only_ for normal\nderivation",
    "Index numbers between 2^31^ and 2^32^ &#x2013; 1 (0x80000000\nto 0xFFFFFFFF) are used _only_ for hardened derivation",
    "the first hardened child (index 0x80000000) is displayed as 0", "that means 2^31^+i",
    "the prime symbol is substituted with either a single apostrophe or the\nletter _h_"),
 Qe("bip-0032.mediawiki", "Each extended key has 2<sup>31</sup> normal child keys, and 2<sup>31</sup> hardened child keys",
    "The normal child keys use indices 0 through 2<sup>31</sup>-1. The hardened child keys use indices 2<sup>31</sup> through 2<sup>32</sup>-1",
    "a number i<sub>H</sub> represents i+2<sup>31</sup>"),
 ("hex(2 ** 31)", "'0x80000000'"), ("hex(2 ** 32 - 1)", "'0xffffffff'"), ("hex(2 ** 31 - 1)", "'0x7fffffff'"),
 Qe("core_fresh_wallet_31_1_v1_0_0.json", '"hdkeypath": "m/84h/0h/0h/0/0"'),
 # private, hardened and public derivation
 Qe("bip-0032.mediawiki", "let I = HMAC-SHA512(Key = c<sub>par</sub>, Data = 0x00 || ser<sub>256</sub>(k<sub>par</sub>) || ser<sub>32</sub>(i))",
    "(Note: The 0x00 pads the private key to make it 33 bytes long.)",
    "let I = HMAC-SHA512(Key = c<sub>par</sub>, Data = ser<sub>P</sub>(point(k<sub>par</sub>)) || ser<sub>32</sub>(i))",
    "The returned child key k<sub>i</sub> is parse<sub>256</sub>(I<sub>L</sub>) + k<sub>par</sub> (mod n)",
    "In case parse<sub>256</sub>(I<sub>L</sub>) ≥ n or k<sub>i</sub> = 0, the resulting key is invalid",
    "(Note: this has probability lower than 1 in 2<sup>127</sup>.)",
    "Switched from multiplication by I<sub>L</sub> to addition of I<sub>L</sub> (faster, easier implementation)",
    "It is only defined for non-hardened child keys", "The returned child key K<sub>i</sub> is point(parse<sub>256</sub>(I<sub>L</sub>)) + K<sub>par</sub>",
    "====Public parent key &rarr; private child key==== This is not possible",
    "The fact that they are equivalent is what makes non-hardened keys useful",
    "an attacker cannot find the parent private key k<sub>par</sub> more efficiently than a 2<sup>256</sup> brute force of HMAC-SHA512",
    "Given a parent extended public key (K<sub>par</sub>,c<sub>par</sub>) and a non-hardened child private key (k<sub>i</sub>), it is hard to find k<sub>par</sub>",
    "knowledge of a parent extended public key plus any non-hardened private key descending from it is equivalent to knowing the parent extended private key",
    "It is also the reason for the existence of hardened keys, and why they are used for the account level in the tree",
    "Leaking a private key means access to coins - leaking a public key can mean loss of privacy"),
 Qb("ch05_wallets.adoc", "if a child\nprivate key is known, or somehow leaked, it can be used with the chain\ncode to derive all the other child private keys",
    "the child private key together with a\nparent chain code can be used to deduce the parent private key",
    "The hardened derivation function\nuses the parent private key to derive the child chain code, instead of\nthe parent public key",
    "This creates a \"firewall\" in the parent/child\nsequence", "the level-1 children of the master keys are always derived through the hardened derivation to\nprevent compromise of the master keys"),
 Qb("ch05_wallets.adoc", "the ability to derive public child keys from public parent keys _without_\nhaving the private keys",
    "That kind of deployment can\nproduce an infinite number of public keys and Bitcoin addresses but\ncannot spend any of the money sent to those addresses"),
 # the arithmetic of one normal and one hardened step of test vector 1
 ("hex((int('%s', 16) + int('%s', 16)) %% %s)[:18]" % (IL_0H1, K_0H, NORD), "'0x3c6cb8d0f6a264c9'"),
 X("hex(W.ckd_priv(int('%s', 16), bytes.fromhex('47fdacbd0f1097043b78c63c20c34ef4ed9a111d980047ad16282c7ae6236141'), 1)[0])[:18]" % K_0H, "'0x3c6cb8d0f6a264c9'"),
 X("hex(W.ckd_priv(*W.master(bytes.fromhex('%s')), 2 ** 31)[0])[:18]" % SEED1, "'0xedb2e14f9ee77d26'"),
 X("W.derive_serialized(bytes.fromhex('%s'), \"m/0'\")[0]" % SEED1,
   "'xprv9uHRZZhk6KAJC1avXpDAp4MDc3sQKNxDiPvvkX8Br5ngLNv1TxvUxt4cV1rGL5hj6KCesnDYUhd7oWgT11eZG7XnxHrnYeSvkzY7d2bhkJ7'"),
 X("W.derive_serialized(bytes.fromhex('%s'), \"m/0'/1\")[1]" % SEED1,
   "'xpub6ASuArnXKPbfEwhqN6e3mwBcDTgzisQN1wXN9BJcM47sSikHjJf3UFHKkNAWbWMiGj7Wf5uMash7SyYq527Hqck2AxYysAA7xmALppuCkwQ'"),
 X("W.derive_serialized(bytes.fromhex('%s'), \"m/0'/1/2'/2/1000000000\")[0]" % SEED1,
   "'xprvA41z7zogVVwxVSgdKUHDy1SKmdb533PjDz7J6N6mV6uS3ze1ai8FHa8kmHScGpWmj4WggLyQjgPie1rFSruoUihUZREPSL39UNdE3BBDu76'"),
 X("all(x in %s for p in ['m', \"m/0'\", \"m/0'/1\", \"m/0'/1/2'\", \"m/0'/1/2'/2\", \"m/0'/1/2'/2/1000000000\"] for x in W.derive_serialized(bytes.fromhex('%s'), p))"
   % (CL() + ".ev_raw('bip-0032.mediawiki')", SEED1), "True"),
 X("all(x in %s for p in ['m', 'm/0', \"m/0/2147483647'\", \"m/0/2147483647'/1\", \"m/0/2147483647'/1/2147483646'\", \"m/0/2147483647'/1/2147483646'/2\"] for x in W.derive_serialized(bytes.fromhex('fffcf9f6f3f0edeae7e4e1dedbd8d5d2cfccc9c6c3c0bdbab7b4b1aeaba8a5a29f9c999693908d8a8784817e7b7875726f6c696663605d5a5754514e4b484542'), p))"
   % (CL() + ".ev_raw('bip-0032.mediawiki')",), "True"),
 # public derivation agrees with private derivation, and the uncompressed form does not
 X("(lambda k, c: W.ckd_pub(W.ec_mul(k), c, 5) == (W.ec_mul(W.ckd_priv(k, c, 5)[0]), W.ckd_priv(k, c, 5)[1]))(*W.master(bytes.fromhex('%s')))" % SEED1, "True"),
 X("(lambda k, c: W.ckd_priv_uncompressed_input(k, c, 5)[0] == W.ckd_priv(k, c, 5)[0])(*W.master(bytes.fromhex('%s')))" % SEED1, "False"),
 X("(lambda k, c: W.leak_parent_private_key(W.ec_mul(k), c, 5, W.ckd_priv(k, c, 5)[0]) == k)(*W.master(bytes.fromhex('%s')))" % SEED1, "True"),
 X("W.ec_add(W.ec_mul(13), W.ec_mul(7)) == W.ec_mul(20)", "True"),
 # the small curve of the worked example
 (PROG(SMALL), "(True, (12, 38))"),
 ("sum(1 for x in range(97) for y in range(97) if (y * y - x ** 3 - 7) % 97 == 0)", "78"),
 # a child key on its own
 Qb("ch05_wallets.adoc", "Child private keys are indistinguishable from nondeterministic (random)\nkeys",
    "Because the derivation function is a one-way function, the child\nkey cannot be used to find the parent key",
    "If you have the n^th^ child, you cannot find\nits siblings", "You\nneed both the child private key and the child chain code to start a new\nbranch and derive grandchildren",
    "It can be used\nto make a public key and a Bitcoin address",
    "A child private key, the corresponding public key, and the Bitcoin\naddress are all indistinguishable from keys and addresses created\nrandomly",
    "each child can in turn\nbecome a parent and create its own children, in an infinite number of\ngenerations"),
 Qb("ch05_wallets.adoc", "there are approximately four billion first-level\nkeys", "It's not possible for a wallet application to generate\neven a small fraction of every possible key in a BIP32 tree"),
 Qc("doc/bips.md", "BIP 32`](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki): Hierarchical Deterministic Wallets has been implemented since **v0.13.0**"),
 Pp("Chapter_5_Wallets_v1_0_0.pptx", "Private child key derivation", "Chain Code", "Hardened child key derivation", "Index numbers for normal and hardened derivation"),
]
