"""SEN0401 chapter 6, corpus text part E (version 1.0.0): the branch 'Outputs' - the count, the 8-byte amount in satoshis and its
consensus range, uneconomical outputs and the dust policy with its data-carrier exception, and the output script with its size
limits, the anyone-can-spend scripts and the standard templates. Markers become author-year strings."""
from sen0401_ch06_common_v1_0_0 import *

NODES_E = [
 ("Outputs", "Outputs", 1, None, None, P(
  (W, "This branch reads the outputs field, the 75 bytes of Alice's transaction that assign her bitcoins to new conditions. The book says the outputs field contains several fields related to specific outputs and, as with the inputs, starts from a byte map; the field begins with a count, and each output has an amount followed by a length-prefixed output script, the script that contains the conditions that will need to be fulfilled in order to spend the bitcoins [AH]. Alice's transaction has two outputs: 20,000 satoshis to Bob and 75,000 back to herself as change."),
  (Y, "Outputs are where value and conditions are written down. The amount is the only place a transaction states a number of satoshis, and the output script is the only place it states who may spend them, so the whole of what chapter 2 called the UTXO is created here. The branch also carries a public cost: every output a node must remember until it is spent burdens every full node, which is why the book spends a section on outputs that are not worth spending and on the dust policy that discourages them [AH]."),
  (E, "The reader meets outputs as the lines of a payment an explorer shows, with an amount and an address; the address is the human form of the output script, which chapter 4 explained, and the amount is the satoshi count the book defines here. The dust limit of 546 satoshis is met as the smallest payment most wallets will make, and the standard templates are met as the handful of address types a wallet offers [AH] [BCP]."),
  (H, "The branch has three groups. The output list explains the count, the amount field, the satoshi as a unit and the consensus range of an amount. The dust group explains uneconomical outputs, the policy against creating them and the one exception, the data-carrier output. The output script group explains the script field, its minimum and maximum sizes, the anyone-can-spend scripts on which upgrades are built, and the standard templates that relay policy limits outputs to [AH].")), None),

 ("OutputList", "The output list", 2, "Outputs", None, P(
  (W, "The output list is the outputs field as a whole: a compactSize count greater than zero, then that many outputs, each an 8-byte amount and a length-prefixed script. The book says the count is identical in form to the start of the inputs section, that it must be greater than zero, and that the example transaction has two outputs; the amount is an 8-byte signed integer of satoshis, and there are 100 million satoshis in a bitcoin [AH]."),
  (Y, "The list matters because it is where arithmetic is checked. The sum of the outputs may not exceed the sum of the inputs' previous outputs, the difference being the fee that a miner may claim, and each amount must lie within the range consensus allows; Bitcoin Core refuses negative values, values above the maximum and a sum that overflows the range, naming each refusal [BCT]. The amount of a single output is bounded above by the total that can ever exist, 21 million bitcoins, which the book gives as 2.1 quadrillion satoshis [AH]."),
  (H, "The four sections take the field in order: the count and its lower bound, the amount field and its 8-byte little-endian encoding, the satoshi as the unit the amount counts, and the range from zero to 21 million bitcoins that consensus permits, with Bitcoin Core's constants COIN and MAX_MONEY and the history of why a check against overflow exists [AH] [BCA] [BCT].")), None),

 ("OutputCount", "Output count", 3, "OutputList", ("two outputs: a payment and change", "The output count is the compactSize integer that opens the outputs field; it must be greater than zero, and Alice's transaction has two outputs.", ("int.from_bytes(bytes.fromhex('01000000000101eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a0100000000ffffffff02204e0000000000002251203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068f8240100000000001600147752c165ea7be772b2c0acb7f4d6047ae6f4768e0141cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e817130100000000')[48:49], 'little')", "2")), P(
  (W, "The output count is the integer that opens the outputs field and says how many outputs follow. The book says it is identical to the start of the inputs section: a count indicating the number of outputs, a compactSize integer that must be greater than zero, and the example transaction has two outputs [AH]. The worked example reads the byte at offset 48 of Alice's transaction, immediately after her single input, and finds 02."),
  (Y, "The lower bound is a consensus rule: Bitcoin Core's CheckTransaction refuses a transaction with no outputs with the error bad-txns-vout-empty, just as it refuses one with no inputs [BCT]. A transaction must assign its value somewhere, even if only to a fee, and in practice almost every payment has two outputs, the payment and the change, because an input is spent whole and the remainder has to return to the sender; the book's chapter 2 explained change in exactly these terms [AH2]."),
  (H, "Like the input count, the output count is compactSize, so it is one byte for up to 252 outputs and grows only for larger transactions; some transactions that pay many recipients at once, such as exchange withdrawals, exceed that and use the three-byte form. The count is read before the outputs because the outputs have no terminator, and the number is used again nowhere else - unlike the input count, which also fixes the number of witness stacks."),
  (K, "The caution is that two outputs do not mean two recipients: Alice's second output is her own change, and nothing in the transaction marks it as such, which is a privacy property the book's later chapters discuss. A second caution is that a count of one is common and legal, for a transaction that spends an output exactly or deliberately leaves the remainder as fee, as the pizza transaction of 2010 did with its single output and its fee of 0.99 bitcoins [MP].")), None),

 ("AmountField", "Amount", 3, "OutputList", ("8 bytes, little-endian, in satoshis", "The amount is the first field of an output: an 8-byte signed little-endian integer of satoshis, called value in Bitcoin Core; Alice's first output carries 20,000.", ("int.from_bytes(bytes.fromhex('204e000000000000'), 'little')", "20000")), P(
  (W, "The amount is the first field of a specific output. The book says it is also called value in Bitcoin Core, that it is an 8-byte signed integer indicating the number of satoshis to transfer, that a satoshi is the smallest unit of bitcoin that can be represented in an on-chain transaction, and that there are 100 million satoshis in a bitcoin [AH]. The first output of Alice's transaction begins with the bytes 204e000000000000, which the worked example reads as 20,000 satoshis, the payment to Bob."),
  (Y, "The amount is the only place a transaction states value, and it is stated once per output. The inputs carry no amounts, so a node computes the fee as the sum of the referenced outputs' amounts minus the sum of these; a transaction whose outputs total more than its inputs is invalid, and one whose outputs total less has given the difference to the miner. Chapter 2 followed Alice's payment with this arithmetic: she spent 100,000, paid 20,000, took 75,000 back, and left 5,000 as fee, which the explorer records as the fee of her transaction [AH2] [MP]."),
  (H, "Eight little-endian bytes read as a signed integer give the value; the second output of Alice's transaction, f824010000000000, reads as 75,000. Bitcoin Core's type for the field is CAmount, a 64-bit signed integer, and its CheckTransaction refuses an output whose value is negative with bad-txns-vout-negative and one above the maximum with bad-txns-vout-toolarge, and keeps a running total that it refuses if the sum leaves the money range [BCT] [BCA]. The signed type is why the consensus range starts at zero rather than at the smallest representable number."),
  (K, "The caution is in the word signed. A naive reader of eight bytes could obtain a negative number, and an early version of the software did not check the sum of outputs for overflow, which produced the value overflow incident of August 2010, one of this chapter's stories; Bitcoin Core's source cites the identifier of that bug beside its check [BCT]. A second caution is units: an explorer may show 0.0002 BTC while the field holds 20,000, and the conversion by 100 million is the only arithmetic between them.")), None),

 ("Satoshi", "Satoshi", 3, "OutputList", ("100 million to a bitcoin", "A satoshi is the smallest unit of bitcoin an on-chain transaction can represent; there are 100 million satoshis in a bitcoin, so 20,000 satoshis are 0.0002 bitcoin.", ("(100_000_000, 20000 / 100_000_000, 75000 / 100_000_000)", "(100000000, 0.0002, 0.00075)")), P(
  (W, "A satoshi is the smallest unit of bitcoin that can be represented in an on-chain Bitcoin transaction. The book defines it in the amount section and gives the ratio: there are 100 million satoshis in a bitcoin [AH]. Chapter 1 introduced the unit by name as the one bitcoin's amounts are counted in; this chapter shows the field that counts it. Bitcoin Core names the ratio COIN, with the value 100,000,000 [BCA]."),
  (Y, "The unit matters because the amount field is an integer, never a fraction. A transaction does not say 0.0002 bitcoins; it says 20,000, and every wallet, explorer and exchange that shows a decimal is dividing by 100 million for display. That makes the arithmetic of fees and change exact - no rounding can occur on the chain - and it fixes a floor: a payment smaller than one satoshi cannot be made on the chain, which is one reason the book's chapter on second-layer applications exists."),
  (H, "The worked example states the ratio and converts Alice's two amounts: 20,000 satoshis are 0.0002 bitcoin and 75,000 are 0.00075. The ratio also sets the scale of the consensus maximum: 21 million bitcoins times 100 million satoshis is 2.1 quadrillion satoshis, which is the number the book gives for the largest amount an output may carry, and which the next section computes [AH]."),
  (K, "The caution is that the satoshi is the smallest unit on the chain but not in every Bitcoin system: the Lightning Network, which the book's chapter on second-layer applications describes, accounts in thousandths of a satoshi off the chain and rounds when it settles. A second caution is naming: some software shows sat or sats, and a figure given without a unit may be either satoshis or bitcoins, a difference of eight decimal places.")), None),

 ("AmountRange", "The consensus range of an amount", 3, "OutputList", ("from 0 to 2.1 quadrillion", "Consensus allows an output amount from zero to 21 million bitcoins, 2.1 quadrillion satoshis; Bitcoin Core names the maximum MAX_MONEY and refuses negative, oversized and overflowing totals.", ("(21_000_000 * 100_000_000, 21_000_000 * 100_000_000 == 2_100_000_000_000_000, 0 <= 20000 <= 21_000_000 * 100_000_000)", "(2100000000000000, True, True)")), P(
  (W, "The consensus range of an amount is the set of values an output may carry. The book says Bitcoin's consensus rules allow an output to have a value as small as zero and as large as 21 million bitcoins, which is 2.1 quadrillion satoshis [AH]. Bitcoin Core states the upper bound as the constant MAX_MONEY, 21 million times COIN, and the function MoneyRange that checks a value is between zero and that bound inclusive [BCA]."),
  (Y, "The range matters because an amount is a 64-bit signed integer, which can hold values far outside it. Without the check, an output could claim a negative amount, which would make a transaction's outputs sum to less than they are, or two outputs could sum past the top of the integer and wrap around to a small negative number, so that the outputs appear to total less than the inputs; the second is exactly what happened in August 2010, when a transaction created two outputs of over 92 billion bitcoins each whose sum overflowed to a small negative value and passed the check of the time [BCT]. The source comment on the check cites that incident's identifier."),
  (H, "The worked example computes the maximum, confirms it equals 2.1 quadrillion, and checks Alice's payment of 20,000 against the range. Bitcoin Core applies three refusals in CheckTransaction: bad-txns-vout-negative for a value below zero, bad-txns-vout-toolarge for a value above MAX_MONEY, and bad-txns-txouttotal-toolarge when the running sum of the outputs leaves the range, which is the check that stops a wraparound [BCT]. The maximum is deliberately the total supply, since no output can hold more than everything."),
  (K, "The caution is that the range is a consensus bound, not a policy one: a zero-value output is valid under consensus but is the book's first example of an uneconomical output, and the dust policy of the next group refuses to relay it unless it is a data-carrier output [AH]. A second caution is that MAX_MONEY is slightly above the amount that will ever exist, since the subsidy schedule issues a little under 21 million, as the coinbase group computes; the source says the exact value of the constant is consensus-critical only as an upper bound [BCA].")), None),

 ("DustPolicy", "Uneconomical outputs and dust", 2, "Outputs", None, P(
  (W, "This group explains the outputs that are not worth spending and the relay policy against creating them. The book says a zero-value output can be spent under the same rules as any other, but spending an output increases the size of a transaction and so the fee that must be paid; if the value of the output is less than the cost of the additional fee, it does not make economic sense to spend it, and such outputs are known as uneconomical outputs [AH]. The policies against relaying or mining transactions that create them are called dust policies."),
  (Y, "The group matters because an unspent output is a cost to everyone. The need for full nodes to keep track of all UTXOs means that every UTXO makes it slightly harder to run a full node; outputs of significant value will eventually be spent, but there is no incentive for the person controlling an uneconomical UTXO ever to spend it, potentially making it a perpetual burden on operators of full nodes, and since Bitcoin's decentralisation depends on many people running full nodes, several implementations discourage uneconomical outputs by policy [AH]."),
  (H, "The three sections are the problem, the policy and the exception. Uneconomical outputs explains the arithmetic and why an output that is economical today may not be tomorrow; the dust limit gives Bitcoin Core's threshold and the 546-satoshi figure many programs assume, recomputed from the source; and the data-carrier output explains why a script beginning with OP_RETURN is allowed a value of zero, because it can never be spent and so never burdens the UTXO set [AH] [BCP].")), None),

 ("UneconomicalOutput", "Uneconomical output", 3, "DustPolicy", ("worth less than the fee to spend it", "An uneconomical output is one whose value is less than the extra fee that spending it would add to a transaction; a zero-value output is always uneconomical, and others become so when fee rates rise.", ("(lambda value, input_vbytes, rate: (input_vbytes * rate, value < input_vbytes * rate))(500, 68, 10)", "(680, True)")), P(
  (W, "An uneconomical output is one that does not make economic sense to spend. The book explains the mechanism: despite having no value, a zero-value output can be spent under the same rules as any other output, but spending an output, using it as an input, increases the size of a transaction, which increases the fee that needs to be paid, and if the value of the output is less than the cost of the additional fee it does not make economic sense to spend it [AH]."),
  (Y, "The concept matters because it is relative to fee rates and therefore unstable. The book says a zero-value output is always uneconomical, since it would contribute nothing even at a fee rate of zero, but that many other low-value outputs can be uneconomical as well, even unintentionally: at a typical fee rate today an output might add more value than it costs to spend, but tomorrow fee rates might rise and make it uneconomical [AH]. A wallet that creates small change outputs is creating future dust for its own user."),
  (H, "The worked example runs the arithmetic for a segwit input of about 68 virtual bytes at 10 satoshis per vbyte: spending costs 680 satoshis, so an output of 500 is uneconomical at that rate. The book's chapter on fees develops the fee rate; here it is enough that the cost of an input is its size times the rate, and that the output's value must exceed it to be worth including. Bitcoin Core's dust threshold, the next section, is this calculation made at a fixed, low rate so that a single number can be a policy [BCP]."),
  (K, "The caution is that uneconomical is not invalid: consensus accepts a zero-value output and a transaction that spends one, and the refusal is a relay policy of some nodes. A second caution is the cost the book names: the owner of an uneconomical output has no reason ever to spend it, so the entry stays in every full node's UTXO database for ever, and that is a cost paid by everyone rather than by the owner [AH].")), None),

 ("DustLimit", "Dust limit", 3, "DustPolicy", ("546 satoshis, from 182 bytes at 3,000 sat/kvB", "Bitcoin Core's dust threshold is the size of an output plus the smallest input that could spend it, times the dust relay rate of 3,000 satoshis per kilo-vbyte: 546 satoshis for a legacy P2PKH output, 294 for a P2WPKH output.", ("((34 + 148) * 3000 // 1000, (31 + 67) * 3000 // 1000)", "(546, 294)")), P(
  (W, "The dust limit is the value below which a relaying node treats an output as dust and refuses to relay or mine the transaction that creates it. The book says the policies against relaying or mining transactions creating new uneconomical outputs are called dust policies, based on a comparison between outputs with very small values and particles with very small size, that Bitcoin Core's dust policy is complicated and contains several arbitrary numbers, and that many programs simply assume outputs with less than 546 satoshis are dust [AH]."),
  (Y, "The limit matters because it is the smallest payment most software will make and because it is not a consensus rule but a convention that can change. The book notes that there are occasionally proposals to lower dust limits and counterproposals to raise them, and encourages developers using presigned transactions or multiparty protocols to check whether the policy has changed since publication [AH]. Bitcoin Core's source explains the figure: if you would pay more in fees than the value of the output to spend it, the output is dust [BCP]."),
  (H, "The worked example recomputes both figures Bitcoin Core's comment gives. A typical non-segwit output is 34 bytes and needs an input of at least 148 bytes to spend, so dust is anything below 182 times the dust relay fee of 3,000 satoshis per kilobyte, which is 546 satoshis; a P2WPKH output is 31 bytes and needs an input of at least 67 bytes, so its threshold is 98 times the rate, 294 satoshis [BCP]. The policy header names the rate DUST_RELAY_TX_FEE, and the chapter's library computes the threshold from any output script; for a taproot output, 43 plus 67 bytes, it gives 330 satoshis."),
  (K, "The caution is that 546 is a legacy figure that many programs apply to every output type, although Bitcoin Core's own threshold for segwit outputs is lower; the book's phrase simply assume is exact. A second caution is that the threshold is in satoshis at a fixed rate, so a 600-satoshi output passes the dust policy and may still be uneconomical to spend at the fee rates of a busy day; dust and uneconomical overlap but are not the same set [AH].")), None),

 ("DataCarrierOutput", "Data-carrier output", 3, "DustPolicy", ("OP_RETURN: unspendable, so not dust", "A data-carrier output is one whose script begins with OP_RETURN; it can never be spent, so nodes need not keep it, and Bitcoin Core's dust policy allows it a value of zero.", ("(bytes.fromhex('6a')[0] == 0x6a, 'OP_RETURN', 0)", "(True, 'OP_RETURN', 0)")), P(
  (W, "A data-carrier output is an output whose script starts with OP_RETURN. The book says Bitcoin Core's dust policy has one exception: such outputs can have a value of zero, because the OP_RETURN opcode causes the script to immediately fail no matter what comes after it, so these outputs can never be spent; full nodes do not need to keep track of them, which Bitcoin Core uses to let users store small amounts of arbitrary data in the blockchain without increasing the size of its UTXO database [AH]."),
  (Y, "The exception matters because it turns the logic of dust on its head. Dust is bad because it stays in the UTXO set for ever; an OP_RETURN output never enters the set at all, since it is provably unspendable, so it costs nodes nothing after the block that contains it. The book adds the second half of the reasoning: since the outputs are unspendable they are not uneconomical, any satoshis assigned to them become permanently unspendable, so allowing the amount to be zero ensures satoshis are not being destroyed [AH]."),
  (H, "An opcode is a one-byte instruction of Bitcoin's script language, which the next chapter of the book explains; OP_RETURN is the byte 0x6a, and the worked example checks the byte and the policy's threshold of zero. Bitcoin Core's GetDustThreshold returns zero for any script its IsUnspendable test accepts, which is a script beginning with OP_RETURN or one longer than the maximum script size [BCP] [BCS]. The chapter's library does the same, and the data after the opcode is simply ignored by every node, which is why it can be anything."),
  (K, "The caution is that the data is stored by every archival node even though it is not in the UTXO set: a data-carrier output costs block space once, not database space for ever, and relay policy limits its size for that reason. A second caution is the one the book makes elsewhere: assigning a positive value to an OP_RETURN output destroys the satoshis, since nothing can ever spend them, and a wallet that does so by mistake has no remedy.")), None),

 ("OutputScriptField", "The output script", 2, "Outputs", None, P(
  (W, "The output script is the last field of an output: the book says the amount is followed by a compactSize integer indicating the length of the output script, the script that contains the conditions that will need to be fulfilled in order to spend the bitcoins, and that according to consensus the minimum size of an output script is zero [AH]. The group covers the field, its size limits, the empty and other anyone-can-spend scripts, and the standard templates."),
  (Y, "The output script is where authorization is written, which the book says it only briefly looks at here and makes the subject of the next chapter. For this chapter the field matters as a byte field with rules: its length is prefixed, its maximum depends on when it is checked, a script that anyone can satisfy is valid and is the raw material of soft forks, and relay policy limits outputs to a few templates that wallets recognise as address types [AH]."),
  (H, "The four sections take the field, its sizes, its degenerate cases and its usual cases. The output script section reads Alice's two scripts, a 34-byte taproot script and a 22-byte pay-to-witness-public-key-hash script; the size limit section gives the zero minimum and the 10,000-byte spending maximum; the anyone-can-spend section explains the empty script and why upgrades are built on such scripts; and the standard outputs section explains the templates and why Bitcoin Core keeps the restriction [AH].")), None),

 ("OutputScript", "Output script", 3, "OutputScriptField", ("34 bytes to Bob, 22 bytes of change", "The output script holds the conditions for spending an output; Alice's first is a 34-byte segwit version 1 script for Bob, her second a 22-byte segwit version 0 script for her change.", (PROG("tx = bytes.fromhex('01000000000101eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a0100000000ffffffff02204e0000000000002251203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068f8240100000000001600147752c165ea7be772b2c0acb7f4d6047ae6f4768e0141cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e817130100000000')\nlen0 = tx[57]; s0 = tx[58:58 + len0]            # after the count at 48 and the 8-byte amount\nlen1 = tx[58 + len0 + 8]; s1 = tx[58 + len0 + 9:58 + len0 + 9 + len1]\nresult = (len0, s0[:2].hex(), len1, s1[:2].hex())"), "(34, '5120', 22, '0014')")), P(
  (W, "The output script is the script that contains the conditions that will need to be fulfilled in order to spend the bitcoins of an output. The book says the output amount is followed by a compactSize integer indicating the length of the output script, and that parsing and using scripts is the subject of the next chapter; this chapter reads the field as bytes [AH]. Alice's transaction has two: a 34-byte script beginning 51 20 for Bob and a 22-byte script beginning 00 14 for her change."),
  (Y, "The script is the modern form of what the whitepaper called a public key, the thing that says who is authorised to spend. Chapter 4 showed how an address encodes a script of this kind - a bech32m address for a taproot script, a bech32 address for a version 0 witness script - so the two scripts of Alice's transaction are the two addresses the payment was made to, decoded [AH]. Which conditions a script imposes is for the next chapter; which bytes it occupies and what they cost is for this one."),
  (H, "The worked example cuts both scripts out of the bytes: the first output's length byte at offset 57 says 34, and its script begins 5120, which is the opcode for the number 1 followed by a push of 32 bytes, a segwit version 1 script, the taproot template; the second output's length byte says 22, and its script begins 0014, the number 0 followed by a push of 20 bytes, a segwit version 0 script paying a public key hash. Both are witness programs in the sense of the witness branch: a version number from 0 to 16 followed by 2 to 40 bytes of data [AH] [B141]. The explorer labels them v1_p2tr and v0_p2wpkh [MP]."),
  (K, "The caution is that a script is not an address: the address is a human encoding of the script with a checksum, and the transaction carries only the script. A second caution is that the two outputs look different only because they pay different script types; the taproot output to Bob costs 136 weight units for its script and the change output 88, as the weight branch's table shows, which is one of the ways a script type affects the fee [AH].")), None),

 ("ScriptSizeLimit", "Script size limits", 3, "OutputScriptField", ("zero at minimum, 10,000 bytes to spend", "Consensus sets the minimum size of an output script at zero and no explicit maximum when it is created, but a later transaction can only spend an output whose script is 10,000 bytes or smaller.", ("(0, 10000, 10000 * 4 <= 4000000)", "(0, 10000, True)")), P(
  (W, "The script size limits are the bounds on how long an output script may be. The book says that according to consensus the minimum size is zero, that the maximum varies depending on when it is being checked - there is no explicit limit on the size of an output script in the output of a transaction, but a later transaction can only spend a previous output with a script of 10,000 bytes or smaller - and that implicitly an output script can be almost as large as the transaction containing it, and a transaction almost as large as the block [AH]."),
  (Y, "The asymmetry matters because it is a property of where the rule is checked. Creating an output costs block space, which the block weight limit prices; spending it executes the script, which the 10,000-byte limit bounds so that no script can take unbounded work to run. An output with a script above the limit can therefore be created and can never be spent, which makes it a strange kind of data-carrier output. Bitcoin Core names the limit MAX_SCRIPT_SIZE and treats a script above it as unspendable in the same test that catches OP_RETURN [BCS]."),
  (H, "The worked example states the two bounds and checks that a 10,000-byte script would fit a block by weight. The 10,000-byte limit lives in the script interpreter, which refuses to execute a longer script, so the check happens when the spending transaction is validated; the creating transaction's output passes CheckTransaction regardless of its script's length, as long as the whole transaction fits the block weight limit [BCS] [BCT] [BCC]. A zero-length script is valid at creation too, and the next section explains what spends it."),
  (K, "The caution is that consensus limits and policy limits differ again here: Bitcoin Core's relay policy will not relay an output whose script is not a standard template, so a 9,000-byte script is valid but will not be relayed by default. A second caution is that these are byte limits on the script as data; the number of operations a script may execute and the size of the elements it pushes are separate limits, which the next chapter of the book treats [BCS].")), None),

 ("AnyoneCanSpend", "Anyone-can-spend scripts", 3, "OutputScriptField", ("an empty script that OP_TRUE satisfies", "An anyone-can-spend script is one anyone can satisfy, such as the empty output script spent by an input script of OP_TRUE; upgrades take such a script and add constraints to it.", ("(len(b''), bytes.fromhex('51')[0] == 0x51, 'OP_TRUE')", "(0, True, 'OP_TRUE')")), P(
  (W, "An anyone-can-spend script is an output script that anyone can satisfy. The book's example is the empty one: an output script with zero length can be spent by an input script containing OP_TRUE, and anyone can create that input script, so anyone can spend an empty output script; there are an essentially unlimited number of such scripts, and Bitcoin protocol developers know them as anyone can spends [AH]. OP_TRUE is the opcode 0x51, the same byte that the taproot script of Alice's first output begins with."),
  (Y, "The category matters because it is how Bitcoin upgrades its script language without a hard fork. The book says upgrades often take an existing anyone-can-spend script and add new constraints to it, making it spendable only under the new conditions; the witness branch shows segwit doing exactly this, since to an old node a segwit output script is a number followed by data that anyone could spend, while new nodes require a witness [AH] [B141]. That is why Alice's taproot output begins with 0x51: to a pre-taproot node it is an anyone-can-spend output."),
  (H, "The worked example states the three facts: the empty script has length zero, 0x51 is OP_TRUE, and the name. The mechanism is that a script's conditions are whatever its opcodes impose, and an empty script imposes none, so the stack left by the input script decides; OP_TRUE leaves a true value, and the spend succeeds. An upgrade that redefines what a particular anyone-can-spend pattern means tightens the rules, which old nodes accept because they would have accepted any spend, which is the definition of a soft fork the witness branch gives [AH]."),
  (K, "The caution is the book's own, in strong words: application developers should never need to use an anyone-can-spend script, and anyone who does should loudly announce their plans to Bitcoin users and developers so that future upgrades do not accidentally interfere with their system, since an upgrade may give the pattern a new meaning [AH]. A second caution is that funds sent to such a script are, in practice, a gift to the first miner who notices.")), None),

 ("StandardOutput", "Standard transaction outputs", 3, "OutputScriptField", ("a few templates relay policy allows", "Standard transaction outputs are the few output script templates that Bitcoin Core's policy for relaying and mining transactions allows, kept to support upgrades and to encourage putting conditions in redeem, witness and leaf scripts.", ("sorted(['P2PKH', 'P2SH', 'P2WPKH', 'P2WSH', 'P2TR', 'bare multisig', 'OP_RETURN'])", "['OP_RETURN', 'P2PKH', 'P2SH', 'P2TR', 'P2WPKH', 'P2WSH', 'bare multisig']")), P(
  (W, "Standard transaction outputs are the output script templates that Bitcoin Core's policy for relaying and mining transactions allows. The book says the policy effectively limits output scripts to just a few templates, that this was originally implemented after the discovery of several early bugs in Bitcoin related to the script language, and that it is retained to support anyone-can-spend upgrades and to encourage the best practice of placing script conditions in P2SH redeem scripts, segwit version 0 witness scripts and segwit version 1 leaf scripts [AH]."),
  (Y, "The templates matter because they are what wallets, explorers and addresses understand. Each template corresponds to an address type that chapter 4 introduced - pay to public key hash, pay to script hash, the two segwit version 0 forms and taproot - and a transaction whose output matches none of them is valid under consensus but will not be relayed by default nodes, so in practice it cannot be sent [AH] [BCP]. The restriction is also what keeps the anyone-can-spend patterns of future upgrades out of ordinary use."),
  (H, "The worked example lists the templates Bitcoin Core's policy recognises as standard: the five address templates, the bare multisignature template that the source limits to at most three keys, and the data-carrier OP_RETURN template [BCP]. Bitcoin Core's IsStandard function classifies a script with its Solver and refuses anything it cannot classify, which is the mechanism; the book defers the templates themselves to the next chapter, where each is parsed [AH]. Both of Alice's outputs are standard, one taproot and one version 0 witness public key hash [MP]."),
  (K, "The caution is that standard is a policy word: a non-standard output can be mined if a miner chooses to include it, and standardness has changed as templates were added, so a list is dated. A second caution is that the templates constrain the output script only; what a redeem script, witness script or leaf script inside them may do is far less restricted, which is exactly the point of the best practice the book names [AH].")), None),
]

CHECKS_E = [
 Qb("ch06_transactions.adoc", "It's a compactSize integer and must be greater than zero.", "The example transaction has two outputs."),
 Qb("ch06_transactions.adoc", "This is an 8-byte signed integer indicating", "the number of satoshis to transfer", "There are 100 million satoshis in a bitcoin."),
 Qb("ch06_transactions.adoc", "as small as", "zero and as large as 21 million bitcoins (2.1 quadrillion satoshis)"),
 Qb("ch06_transactions.adoc", "Such outputs are known as", "_uneconomical outputs_", "A zero-value output is always an uneconomical output"),
 Qb("ch06_transactions.adoc", "assume outputs with less than 546 satoshis are dust"),
 Qb("ch06_transactions.adoc", "scripts starting with +OP_RETURN+, called _data carrier outputs_,", "can have a value of zero"),
 Qb("ch06_transactions.adoc", "the minimum size of an output script is zero", "only spend a previous output with a script of 10,000 bytes or", "smaller"),
 Qb("ch06_transactions.adoc", "An output script with zero length can be spent by an input script containing", "++OP_TRUE++", "known to Bitcoin", "protocol developers as _anyone can spends_"),
 Qb("ch06_transactions.adoc", "limits output scripts to just a few templates,", "called _standard", "transaction outputs_"),
 Qc("src/consensus/amount.h", "inline constexpr CAmount COIN{100'000'000};", "inline constexpr CAmount MAX_MONEY{21'000'000 * COIN};"),
 Qc("src/consensus/tx_check.cpp", "bad-txns-vout-empty", "bad-txns-vout-negative", "bad-txns-vout-toolarge", "bad-txns-txouttotal-toolarge", "see CVE-2010-5139"),
 Qc("src/policy/policy.cpp", "546 satoshis at the default rate of 3000 sat/kvB.", "294 satoshis at the default rate of 3000 sat/kvB.", "A typical spendable non-segwit txout is 34 bytes big, and will", "need a CTxIn of at least 148 bytes to spend"),
 Qc("src/policy/policy.h", "DUST_RELAY_TX_FEE{3000}"),
 Qc("src/script/script.h", "return (size() > 0 && *begin() == OP_RETURN) || (size() > MAX_SCRIPT_SIZE);"),
 Qc("src/policy/policy.cpp", "// Support up to x-of-3 multisig txns as standard"),
 X("[(o['value'], len(bytes.fromhex(o['script'])), o['script'][:4]) for o in T.parse_tx(%r)['outputs']]" % ALICE, [(20000, 34, '5120'), (75000, 22, '0014')]),
 X("[(o['value'], o['scriptpubkey_type']) for o in C.ev_json('mempool_tx_466200308696215b_v1_0_0.json')['vout']]", [(20000, 'v1_p2tr'), (75000, 'v0_p2wpkh')]),
 X("C.ev_json('mempool_tx_466200308696215b_v1_0_0.json')['fee']", 5000),
 X("(100000 - 20000 - 75000, T.COIN, T.MAX_MONEY, T.money_range(T.MAX_MONEY), T.money_range(T.MAX_MONEY + 1), T.money_range(-1))", (5000, 100000000, 2100000000000000, True, False, False)),
 X("[T.dust_threshold(s) for s in ('76a914' + '00' * 20 + '88ac', '0014' + '00' * 20, '5120' + '00' * 32, '6a04deadbeef')]", [546, 294, 330, 0]),
 X("[T.segwit_output_version(o['script']) for o in T.parse_tx(%r)['outputs']]" % ALICE, [(1, '3b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068'), (0, '7752c165ea7be772b2c0acb7f4d6047ae6f4768e')]),
 # the pizza transaction: one output of 10,000 BTC, a fee of 0.99 BTC (the explorer's figure)
 X("(T.parse_tx(C.ev_hex('tx_pizza_a1075db5_v1_0_0.hex'))['outputs'][0]['value'] // T.COIN, C.ev_json('mempool_tx_a1075db55d416d3c_v1_0_0.json')['fee'] / T.COIN)", (10000, 0.99)),
 ("int.from_bytes(bytes.fromhex('f824010000000000'), 'little')", "75000"),
 ("(2 ** 63 - 1 > 21_000_000 * 100_000_000, 2 ** 63 - 1)", "(True, 9223372036854775807)"),
 # the 2010 overflow: two outputs of 92,233,720,368.54277039 BTC sum, as a signed 64-bit integer, to a small negative number
 ("(lambda w: w - 2 ** 64 if w >= 2 ** 63 else w)((2 * 92_233_720_368_54277039) & 0xffffffffffffffff)", "-997538"),
 ("(34 + 148, 31 + 67, 43 + 67, 182 * 3, 98 * 3, 110 * 3)", "(182, 98, 110, 546, 294, 330)"),
 ("(0x51, 0x6a)", "(81, 106)"),
 ("(136 + 88, (34 + 22) * 4)", "(224, 224)"),
]
