"""SEN0401 chapter 6, corpus text part F (version 1.0.0): the branch 'Witnesses' - the witness as data that solves a math problem,
the three problems of putting witnesses in the input script (circular dependencies, third-party and second-party malleability),
segregated witness as a soft fork built on anyone-can-spend scripts, and the serialization of the witness structure. Markers become
author-year strings."""
from sen0401_ch06_common_v1_0_0 import *

NODES_F = [
 ("Witnesses", "Witnesses", 1, None, None, P(
  (W, "This branch explains the witness structure, the 67 bytes near the end of Alice's transaction that prove she was allowed to spend. The book starts from the word: in court a witness is someone who testifies that they saw something important happen; for a math problem such as x plus 2 equals 4, the witness can simply be the value 2, which anyone can check; and when spending bitcoins the important problem is whether the spend was authorised by the people who control them, which full nodes decide by accepting witnesses that consist entirely of data for solving math problems [AH]."),
  (Y, "The branch matters because where a witness is stored turned out to decide what contracts Bitcoin can support. In the legacy format signatures and other witness data go in the input script, which is hashed into the transaction identifier; the book shows three problems that follow - a circular dependency between two unsigned transactions, a third party's ability to change the identifier by re-encoding a push, and a counterparty's ability to do the same by re-signing - and explains how segregated witness removes all three by leaving the witness out of the identifier [AH] [B141]."),
  (E, "The reader meets witnesses in every segwit transaction's hexadecimal, after the outputs and before the lock time; in the empty input script of such transactions; in the names of address types, where witness program and witness version are the terms chapter 4 used; and in the history of the Mt. Gox exchange, whose February 2014 claim that malleability explained its missing withdrawals is one of this chapter's stories. The 2017 activation of segwit at block 481,824 is recorded in Bitcoin Core's chain parameters [BCK]."),
  (H, "The branch has four groups. The idea of a witness: the court analogy, the public key and signature as the real problem and its solution, and the contract protocols that need transactions signed out of order. The malleability problems: the circular dependency, third-party malleability through alternative push encodings, second-party malleability through alternative signatures, and the wanted kind that signature hashes allow. Segregated witness: the idea, the hard-fork and soft-fork paths, the witness program and the witness structure. And the serialization of the witness structure, with its stacks and items [AH].")), None),

 ("WitnessIdea", "The idea of a witness", 2, "Witnesses", None, P(
  (W, "This group explains what a witness is before any byte of it is read. The book's sequence is an analogy, a toy and the real case: a human witness in court, whose testimony must be interrogated; a value that witnesses the solution of a math problem, which can be checked rather than believed; and the public key and signature of a digital signature scheme, where the equation can only be solved by someone holding a secret [AH]."),
  (Y, "The idea matters because it names the role that signatures play without tying it to any one place in the transaction. A signature in an input script, a signature in a witness item and a solution to the toy script 2 OP_ADD 4 OP_EQUAL are all witnesses in this sense: data that lets a node verify an authorisation without trusting anyone. Giving the role a name is what lets the book ask where witnesses should go, which is the question the rest of the branch answers [AH]."),
  (H, "The three sections build up. The witness section states the definition and the toy script with its witness of 2. The signature witness section explains the public key and the signature as the identifier and the solution of a problem only the key's holder can solve, and shows the script with a public key and OP_CHECKSIG. The contract protocol section explains why developers building protocols on Bitcoin - the sequence branch's payment channel among them - ran into trouble with witnesses in the input script [AH].")), None),

 ("Witness", "Witness", 3, "WitnessIdea", ("the value 2 solves 2 OP_ADD 4 OP_EQUAL", "A witness is data that solves the math problem protecting an output, which full nodes check instead of trusting; for the script 2 OP_ADD 4 OP_EQUAL the witness is the value 2.", ("(lambda witness: witness + 2 == 4)(2)", "True")), P(
  (W, "A witness is data that solves the math problem that protects some bitcoins. The book arrives at the definition through the court: a witness there is someone who testifies that they saw something important happen, and courts interrogate witnesses because humans are not always reliable; for a math problem such as x plus 2 equals 4, a witness need not be a person at all, since the proposed value of x can be checked directly [AH]. Full nodes cannot interrogate humans, but they can accept witnesses that consist entirely of data for solving math problems."),
  (Y, "The definition matters because it separates the proof from the prover. A node does not know or care who provides a witness; it checks whether the data satisfies the script, and a valid witness from a thief is as good as one from the owner. That is why the problem must be one that only the owner can solve, which the next section's digital signature provides, and why the data itself must be protected from alteration in transit, which is the malleability group's subject [AH]."),
  (H, "The book's toy script is 2 OP_ADD 4 OP_EQUAL: an input supplies a value, the script adds 2 and checks for equality with 4, so the witness 2 succeeds and any other value fails. The worked example checks the arithmetic. In a real transaction the script is in the output being spent and the witness is supplied by the spending transaction; for Alice's transaction the witness is one 65-byte item, a signature, which satisfies the taproot script of the output she spends [AH] [MP]. The book notes that letting bitcoins be spent by anyone who can solve a simple equation would not be secure, which motivates the next section."),
  (K, "The caution is that the word has two technical uses in this chapter. In the abstract sense every input script of a legacy transaction contains a witness; in the concrete sense of the serialization, the witness structure is a separate field of segwit transactions, and the book says the abstract name for the data held by an input script is a witness when it introduces segregated witness [AH]. The two senses meet in the segregated witness group.")), None),

 ("SignatureWitness", "Public key and signature as witness", 3, "WitnessIdea", ("a problem only the key holder can solve", "In a digital signature scheme the public key is a public identifier of secret data and the signature a solution to an equation only the holder of that data can produce; a script of a public key and OP_CHECKSIG makes the signature the witness.", ("(lambda problem: (problem['identifier'], problem['solver'], problem['witness']))({'identifier': 'public key', 'solver': 'the holder of the private key', 'witness': 'signature'})", "('public key', 'the holder of the private key', 'signature')")), P(
  (W, "The public key and the signature are the identifier and the solution of the problem that really protects bitcoins. The book says an unforgeable digital signature scheme uses an equation that can only be solved by someone in possession of certain data they are able to keep secret, that they reference that secret data using a public identifier called a public key, and that a solution to the equation is called a signature; a script containing a public key and an opcode requiring a corresponding signature makes the signature the witness, like the number 2 in the toy example [AH]."),
  (Y, "The section matters because it connects this chapter to chapter 4 and to the book's chapter on digital signatures. Chapter 4 explained how a private key becomes a public key and an address; this chapter shows the public key placed in an output script with OP_CHECKSIG, and a signature placed in the witness, and says that the opcode requires the signature to commit to the data in the spending transaction, which is what prevents a valid signature from being reused on a different payment [AH]."),
  (H, "The worked example states the three roles. In the script the book shows, the public key is a push of the key's bytes and OP_CHECKSIG is the opcode that takes a signature and a key from the stack and checks them against the transaction; the signature is the witness because it is the datum the spender supplies. The book defers how the equation works to its chapter on signatures; here the point is structural, that the witness is a solution and the output script is the problem [AH]."),
  (K, "The caution is in the word commit: a signature covers the transaction's data, so changing the outputs invalidates it, but in the legacy format the signature cannot cover the input script that contains it, since the signature is part of that script. That gap is exactly where third-party malleability lives, as the next group shows. A second caution is that a signature requires a random number from the signer, and a different random number gives a different valid signature, which is the second-party malleability of the same group [AH].")), None),

 ("ContractProtocol", "Contract protocols", 3, "WitnessIdea", ("transactions signed out of order", "A contract protocol is a series of transactions between parties, often signed out of order so that each party is protected before committing; the payment channel is one, and such protocols exposed the problems with witnesses in the input script.", ("['setup transaction', 'refund transaction', 'rounds of the game', 'final transaction']", "['setup transaction', 'refund transaction', 'rounds of the game', 'final transaction']")), P(
  (W, "A contract protocol is a series of transactions between parties arranged so that the parties can rely on each other without trust. The book says that witnesses need to be included in the transactions where they are used so that full nodes can verify them, that in the legacy format signatures and other data are placed in the input script field, and that when developers started to implement contract protocols on Bitcoin, such as the payment channel of the sequence branch, they discovered several significant problems with placing witnesses in the input script field [AH]."),
  (Y, "Contract protocols matter because they are where Bitcoin's expressiveness is used: payment channels, the Lightning Network, escrows and swaps are all sequences of transactions whose signatures are exchanged in a particular order. The book's circular-dependency example describes a protocol in which Alice and Bob sign a refund before signing the deposit it refunds, so that neither can trap the other's money; the book calls such a design a trustless protocol [AH]. Whether such designs can be built depends on properties of the transaction format, which is why a chapter on serialization turns to them."),
  (H, "The worked example lists the four stages of the card game as a protocol. In each, a transaction is signed and held rather than broadcast, and the holder relies on being able to broadcast it later; that reliance is sound only if the earlier transactions it spends keep the identifiers it was signed against, which is the property the legacy format cannot guarantee. The three sections of the next group are the three ways that guarantee fails, and the segregated witness group is the repair [AH]."),
  (K, "The caution is that trustless means not requiring trust in the counterparty, not requiring no assumptions: such a protocol still assumes that the network relays transactions, that miners include them, and that timelocks are enforced. A second caution is that the book's examples are deliberately minimal - two parties, two or three transactions - while real protocols add penalty transactions and hashed timelocks; the mechanisms are those of the book's chapter on second-layer applications.")), None),

 ("MalleabilityProblems", "The malleability problems", 2, "Witnesses", None, P(
  (W, "This group states the three problems that the book found with placing witnesses in the input script: the circular dependency, in which a refund cannot be signed before the deposit whose identifier it needs; third-party transaction malleability, in which anyone can re-encode a push in an input script and change a transaction's identifier; and second-party malleability, in which a counterparty can produce an alternative signature and change it [AH]. A fourth section covers the malleability people want, which signature hashes provide."),
  (Y, "The group matters because the problems are not bugs in any program but properties of the data format, and because they are the reason segregated witness was adopted. Each problem ends the same way, with a presigned transaction made invalid because the identifier it spends has changed; the book's Bob loses his payment to Carol through no fault of Alice, Bob or Carol, and its Alice loses her refund because Bob re-signed [AH]. The Mt. Gox story of this chapter shows the third-party problem blamed, rightly or not, for an exchange's losses."),
  (H, "The four sections follow the book's order. The circular dependency explains why the refund in a two-party deposit cannot be constructed until the deposit's signatures are known. Third-party malleability shows the alternative encodings of the number 2 and computes that each gives a different identifier. The push encodings section does the computation on a real transaction. Second-party malleability explains the random number in a signature. And wanted malleability explains that the book prefixes the word unwanted for a reason [AH].")), None),

 ("CircularDependency", "Circular dependency", 3, "MalleabilityProblems", ("the refund needs the deposit's txid first", "A circular dependency arises when Alice and Bob want to sign a refund before the deposit it spends, but in the legacy format the deposit's txid depends on its signatures, so the refund cannot be built until both have signed the deposit.", ("(lambda needs: needs['refund'] in needs and needs[needs['refund']] == 'signatures of the deposit')({'refund': 'txid of the deposit', 'txid of the deposit': 'signatures of the deposit'})", "True")), P(
  (W, "A circular dependency is the first problem the book names with witnesses in the input script. Many contract protocols involve a series of transactions signed out of order: Alice and Bob deposit funds into a script that needs both signatures, but each wants their money back if the other becomes unresponsive, so they sign the refund transaction before the deposit. The book's problem: in the legacy format every field, including the input script that contains signatures, is used to derive a transaction's identifier, and the deposit's identifier is part of the refund's outpoint [AH]."),
  (Y, "The dependency matters because it makes a trustless two-party deposit impossible in the legacy format. The book spells it out: there is no way for Alice and Bob to construct the refund until both signatures for the deposit are known, but if they know the signatures for the deposit, one of them can broadcast it before signing the refund, eliminating the guarantee of a refund [AH]. The worked example models the chain of needs: the refund needs the deposit's identifier, which needs the deposit's signatures, which should come last."),
  (H, "The dependency is a consequence of what the identifier covers. If the identifier were computed over everything but the signatures, the deposit's identifier would be known as soon as its outputs were decided, the refund could be built and signed, and only then would the deposit be signed and broadcast; that is exactly the change segregated witness makes, by leaving the witness out of the identifier [AH] [B141]. The book's examples use two transactions it calls Tx 0 and Tx 1, the deposit and the refund, and the same pair reappears in the second-party section."),
  (K, "The caution is that a more complex series of transactions can sometimes eliminate a circular dependency, as the book says at the start of the next section, but at the price of meeting the next problem; the dependency is the first obstacle, not the only one [AH]. A second caution is that the problem is specific to protocols that presign: an ordinary payment, signed and broadcast at once, never needs the identifier of an unsigned transaction.")), None),

 ("ThirdPartyMalleability", "Third-party transaction malleability", 3, "MalleabilityProblems", ("a stranger changes the txid, not the payment", "Unwanted third-party transaction malleability is a stranger's ability to change a transaction's txid without invalidating it, for example by re-encoding a push in the input script, so that a conflicting copy confirms and any transaction spending the original's outputs becomes invalid.", (PROG("import hashlib\nh256 = lambda b: hashlib.sha256(hashlib.sha256(b).digest()).digest()\nbody = bytes.fromhex('01000000') + bytes.fromhex('00' * 32 + '00000000')\nvariants = {'OP_2': '52', 'OP_PUSH1 0x02': '0102', 'OP_PUSHDATA1 0x0102': '4c0102'}\nids = {k: h256(body + bytes([len(v) // 2]) + bytes.fromhex(v) + bytes.fromhex('ffffffff'))[::-1].hex()[:8] for k, v in variants.items()}\nresult = (len(set(ids.values())), ids)"), "(3, {'OP_2': '394f3eb1', 'OP_PUSH1 0x02': '146b3825', 'OP_PUSHDATA1 0x0102': '009ae5eb'})")), P(
  (W, "Third-party transaction malleability is the second problem: it is often possible to solve the same script in different ways. The book returns to the script 2 OP_ADD 4 OP_EQUAL and lists several ways to put the value 2 on the stack - OP_2, OP_PUSH1 0x02, OP_PUSH2 0x0002, and the OP_PUSHDATA1, OP_PUSHDATA2 and OP_PUSHDATA4 forms - each of which produces a slightly different transaction with a completely different txid; all versions spend the same outpoints and so conflict, and only one can be in a valid blockchain [AH]."),
  (Y, "The problem matters because of who can exploit it. The book's scenario: Alice creates a transaction with OP_2 in the input script paying Bob, Bob immediately spends that output to Carol, and anyone on the network replaces OP_2 with OP_PUSH1 0x02, creating a conflict; if the conflicting version confirms, Alice's original cannot, and Bob's transaction cannot spend its output, so Bob's payment to Carol is invalid even though neither Alice, Bob nor Carol did anything wrong. Someone not involved in the transaction, a third party, was able to mutate it, which the book calls unwanted third-party transaction malleability [AH]."),
  (H, "The worked example builds a minimal legacy transaction body with three encodings of the push and hashes each with double SHA-256: three different identifiers from three byte strings that mean the same thing to the script interpreter. The mutation does not touch the signature, because a legacy signature cannot cover the input script that contains it, so each variant is as valid as the original; the next section does the same computation on a real transaction. BIP62 was an attempt to forbid non-canonical encodings by consensus; its status in the proposals repository is closed, and the book presents it as an attempt that, even if it had entirely eliminated third-party malleability, would have left the second-party kind unsolved [B62]."),
  (K, "The caution is in the book's tip: there are cases when people want their transactions to be malleable, and Bitcoin provides features for that, notably the signature hashes of the book's chapter on signatures, so the book occasionally prefixes the word unwanted and means the unwanted variant whenever it uses the shorter term [AH]. A second caution is that the attacker gains nothing directly - the mutated transaction pays the same outputs - but can break anything that depended on the original identifier, which for an exchange tracking withdrawals by identifier can look like a payment that never happened.")), None),

 ("PushEncoding", "Alternative push encodings", 3, "MalleabilityProblems", ("four byte strings for the number 2", "The number 2 can be pushed as OP_2, as a one-byte push, as a two-byte push or with OP_PUSHDATA1; each is a different byte string, so each gives a legacy transaction a different txid while the script result is the same.", ("{'OP_2': '52', 'OP_PUSH1 0x02': '0102', 'OP_PUSH2 0x0002': '020200', 'OP_PUSHDATA1 0x0102': '4c0102'}", "{'OP_2': '52', 'OP_PUSH1 0x02': '0102', 'OP_PUSH2 0x0002': '020200', 'OP_PUSHDATA1 0x0102': '4c0102'}")), P(
  (W, "The alternative push encodings are the concrete bytes behind third-party malleability. A push is an opcode that places data on the script's stack; Bitcoin's script language has several: the opcodes OP_1 to OP_16 push the small numbers directly, the opcodes 1 to 75 push that many following bytes, and OP_PUSHDATA1, OP_PUSHDATA2 and OP_PUSHDATA4 push data whose length is given in one, two or four following bytes. The book lists these forms for the number 2 and notes that each produces a slightly different transaction with a completely different txid [AH]."),
  (Y, "The encodings matter because the script interpreter treats them alike while the hash function does not. OP_2 is the single byte 0x52; a one-byte push of 0x02 is the two bytes 01 02; a two-byte push of 0x0002 is 02 02 00; and OP_PUSHDATA1 with a length of one is 4c 01 02. The worked example lists these four byte strings. Since the input script is part of the legacy serialization, any of them changes the identifier, and the previous section's example showed three identifiers from three of them [AH]."),
  (H, "The chapter's library applies the same substitution to a real transaction: given the first bitcoin transaction of January 2009, which has a legacy input script, replacing that script with each of the four encodings and recomputing the identifier gives four different identifiers, which an executed claim records. The substituted transactions would not actually validate, since the real script needs a signature, but the computation shows what a third party could do to a transaction whose script accepted a bare number [AH]."),
  (K, "The caution is that relay policy has long refused non-canonical pushes - Bitcoin Core treats a push that is not the shortest encoding as non-standard - so the simplest mutations are not relayed today; the book's point is that policy is not consensus, and that a miner or a non-standard node could still produce the mutation [AH] [BCP]. A second caution is that the opcode numbers 0x01 to 0x4b are themselves lengths, so a push of 2 bytes written 02 is an opcode, not the number two.")), None),

 ("SecondPartyMalleability", "Second-party transaction malleability", 3, "MalleabilityProblems", ("a counterparty re-signs and changes the txid", "Unwanted second-party transaction malleability is a counterparty's ability to produce an alternative signature, because a signer chooses a random number each time, and so a conflicting transaction with a different txid that invalidates a presigned refund.", ("(lambda same_data, nonce_a, nonce_b: (same_data, nonce_a != nonce_b, 'different signature, different txid'))(True, 1234, 5678)", "(True, True, 'different signature, different txid')")), P(
  (W, "Second-party transaction malleability is the third problem. The book says that when the legacy format was the only format, developers worked on proposals such as BIP62 to minimise third-party malleability, but that even if third-party malleability were entirely eliminated, users of contract protocols faced another problem: if they required a signature from someone else involved in the protocol, that person could generate alternative signatures and change the txid [AH] [B62]."),
  (Y, "The problem matters because it cannot be fixed by canonical encodings. The book's example: Alice and Bob hold money in a two-signature script with a refund; Alice wants to spend some, so they build a chain in which the deposit's second output returns the remainder to the joint script and a new refund spends it, signed before the deposit. There is no circular dependency, and ignoring third-party malleability it looks trustless; but a signer has to choose a large random number when creating a signature, and a different number produces a different signature even if everything signed stays the same [AH]."),
  (H, "The worked example states the property: the same data signed with two different random numbers gives two different valid signatures, and in the legacy format two different identifiers. The book compares it to a handwritten signature, which looks slightly different on two copies of the same contract; the consequence is that if Alice broadcasts the deposit containing Bob's signature, Bob can broadcast a conflicting version with a fresh signature, and if his version confirms Alice cannot use the presigned refund, which the book calls unwanted second-party transaction malleability [AH]."),
  (K, "The caution is that the second party is a legitimate signer acting within the rules; nothing in the legacy format can distinguish the signature the protocol expected from the one the counterparty substituted, so the only remedy is to take signatures out of the identifier altogether. A second caution is terminological: the book counts the sender as the first party, so a second party is a counterparty in the protocol and a third party is a stranger [AH].")), None),

 ("WantedMalleability", "Wanted malleability", 3, "MalleabilityProblems", ("mutation the sender allows", "Some malleability is wanted: with a signature hash the sender can allow others to change parts of a transaction, as when Bob adds an input to help pay Alice's fee; the book says unwanted when it means the other kind.", ("(lambda kinds: [k for k in kinds if kinds[k]])({'unwanted third-party': False, 'unwanted second-party': False, 'sender-permitted (sighash)': True})", "['sender-permitted (sighash)']")), P(
  (W, "Wanted malleability is the kind the book's tip describes: there are cases when people want their transactions to be malleable, and Bitcoin provides several features to support that, most notably the signature hashes, or sighash, of the book's chapter on signatures. The example is Alice using a sighash to allow Bob to help her pay some transaction fees, which mutates Alice's transaction but only in a way that Alice wants [AH]."),
  (Y, "The distinction matters because it fixes the vocabulary of the whole branch. The book says that for this reason it occasionally prefixes the word unwanted to the term transaction malleability, and that even when it and other technical writers use the shorter term, they are almost certainly talking about the unwanted variant [AH]. A reader who takes malleability to mean any change to a transaction will misread both the problems and the remedy, since segregated witness removes only the unwanted kinds."),
  (H, "A signature hash is a flag attached to a signature that says which parts of the transaction the signature commits to; the default commits to everything, and other values leave some inputs or outputs uncommitted so that others may add to them. The worked example sorts the three kinds and keeps the one that is permitted. Wanted malleability survives segregated witness untouched, because it works through what the signature covers rather than through the identifier [AH]."),
  (K, "The caution is that a wanted mutation still changes the identifier in the legacy format and still changes the witness identifier in the segwit format, so a protocol that allows one must not presign transactions against the mutated transaction's identifier. A second caution is that sighash flags are a sharp tool: a signature that commits to nothing but one input can be attached to any transaction that spends that input, which is why the book treats them in a chapter of their own.")), None),

 ("SegregatedWitness", "Segregated witness", 2, "Witnesses", None, P(
  (W, "Segregated witness, segwit, is the idea of separating the rest of the data in a transaction from its witness for the purpose of generating a txid. The book says that as early as 2011 protocol developers knew how to solve circular dependence and both malleabilities by avoiding the input script in the calculation that produces a txid, and that the idea took its name from this separation [AH]. This group explains the idea, the two ways of deploying it, and the two new fields it introduced."),
  (Y, "The group matters because segwit is the format Alice's transaction uses and the reason her input script is empty. It also matters as the clearest example in the book of how Bitcoin changes its rules: the obvious implementation needed a hard fork, an alternative in late 2015 used a soft fork built on anyone-can-spend scripts, and the result is that old nodes allow what new nodes require [AH]. The weight branch shows the second thing segwit changed, the way transaction size is measured."),
  (H, "The five sections go from idea to fields. Segwit itself: the separation and what it eliminates. Hard fork: the incompatible change the obvious design needed. Soft fork: the backward-compatible change and its rule that new nodes may reject but not accept more. Witness program: the output script template of a version number and data that old nodes see as anyone-can-spend. Witness structure: the new field that holds what the input script no longer may, and the book's table of terms for authorization and authentication across the whitepaper, legacy and segwit [AH].")), None),

 ("Segwit", "Segregated witness", 3, "SegregatedWitness", ("the witness stays out of the txid", "Segregated witness is the separation of a transaction's witness from the data its txid is computed over; an empty input script keeps witnesses from affecting the txid and so removes circular dependencies and both unwanted malleabilities.", (PROG("import hashlib\nh256 = lambda b: hashlib.sha256(hashlib.sha256(b).digest()).digest()\ntx = bytes.fromhex('01000000000101eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a0100000000ffffffff02204e0000000000002251203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068f8240100000000001600147752c165ea7be772b2c0acb7f4d6047ae6f4768e0141cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e817130100000000')\nlegacy = tx[:4] + tx[6:-71] + tx[-4:]        # no marker, flag or witness\nresult = h256(legacy)[::-1].hex()"), "'466200308696215bbc949d5141a49a4138ecdfdfaa2a8029c1f9bcecd1f96177'")), P(
  (W, "Segregated witness is the idea of separating the rest of the data in a transaction from its witness for the purpose of generating a txid. The book says the abstract name for the data held by an input script is a witness, that protocol developers knew as early as 2011 that avoiding the input script in the txid calculation solved circular dependence and both malleabilities, and that the idea of the separation is called segregated witness, segwit for short [AH]. BIP141 is the consensus layer of the design and BIP144 its serialization [B141] [B144]."),
  (Y, "Segwit matters because it made the contract protocols of this branch possible. The book states the effect in one sentence: an empty input script keeps witnesses from affecting the txid, eliminating circular dependencies, third-party transaction malleability and second-party transaction malleability [AH]. A refund can now be signed against a deposit whose identifier is fixed before anyone signs the deposit, and no re-encoding or re-signing by anyone can change that identifier, because the identifier no longer covers the data being changed."),
  (H, "The worked example proves the separation on Alice's transaction: hashing the legacy serialization - the bytes without the marker, the flag and the witness structure - with double SHA-256 and reversing the result gives 46620030..., the identifier the book, the explorer and Bitcoin Core all report for her transaction, although the serialization they return includes the witness [AH] [MP]. BIP141 defines a second identifier, the wtxid, over the whole extended serialization, which does change with the witness and which blocks commit to separately [B141]. An executed claim shows that altering a witness item changes the wtxid and leaves the txid unchanged."),
  (K, "The caution is that segwit is a property of outputs, not of transactions as a whole: a transaction that spends a legacy output still has a witness in its input script and is still malleable in that input, and the book's closing section says a transaction with an empty witness structure must use the legacy format [AH]. A second caution is historical: the design was described in late 2015, activated on the main network at block 481,824 in August 2017, and the book's as early as 2011 refers to the idea rather than the deployment [AH] [BCK].")), None),

 ("HardFork", "Hard fork", 3, "SegregatedWitness", ("a change old nodes would reject", "A hard fork is a change to the consensus rules that is not compatible with older full nodes; the obvious way to implement segwit needed one, which is why an alternative was sought.", ("(lambda old_accepts, new_accepts: 'hard fork' if new_accepts - old_accepts else 'soft fork')({'legacy blocks'}, {'legacy blocks', 'blocks old nodes reject'})", "'hard fork'")), P(
  (W, "A hard fork is a change to Bitcoin's consensus rules that would not be compatible with older full nodes. The book introduces the term when it explains that the obvious method for implementing segwit - changing the serialization and the identifier for every node at once - requires such a change, and it says hard forks come with a lot of challenges, which it discusses in a later chapter [AH]. Chapter 1 and chapter 2 introduced consensus rules as the rules every full node enforces identically; a hard fork is a change that makes new rules accept something old rules reject."),
  (Y, "The term matters because it names the cost of the obvious design. A hard fork requires every node to upgrade or be left on a different chain, since old nodes would reject blocks containing the new transactions; for a change whose benefit is felt mainly by contract protocols, demanding that of every participant was judged too much, and the book says an alternative approach was described in late 2015 [AH]. The worked example states the test: if the new rules accept something the old rules reject, the change is a hard fork."),
  (H, "The mechanics follow from how nodes validate. An old node applies the old rules to every block; if a block is valid under the new rules and invalid under the old, old nodes reject it and continue on a chain of blocks that new nodes may in turn consider inferior, and the network splits into two chains with two histories. The book's chapter on mining and consensus treats what it takes to coordinate such a change; for this chapter it is enough that segwit chose the other path [AH]."),
  (K, "The caution is that hard and soft describe compatibility, not size or importance: a tiny change that lets a new kind of block through is a hard fork, and a large change that only tightens rules is a soft fork. A second caution is that a hard fork is not inherently bad - the book's later chapter discusses cases - but it needs the whole economy to move, which a soft fork does not.")), None),

 ("SoftFork", "Soft fork", 3, "SegregatedWitness", ("new nodes reject more, accept no more", "A soft fork is a backward-compatible change to the consensus rules: full nodes with the change must not accept any block that nodes without it would consider invalid, so new nodes can reject blocks old nodes accept but not the reverse.", ("(lambda old_accepts, new_accepts: 'soft fork' if new_accepts <= old_accepts else 'hard fork')({'any spend of a segwit output', 'other blocks'}, {'other blocks'})", "'soft fork'")), P(
  (W, "A soft fork is a backward-compatible change to the consensus rules. The book says the alternative approach to segwit described in late 2015 used one, and defines backward compatible: full nodes implementing the change must not accept any blocks that full nodes without the change would consider invalid; as long as they obey that rule, newer full nodes can reject blocks that older full nodes would accept, giving them the ability to enforce new consensus rules, but only if the newer nodes represent the economic consensus among Bitcoin users [AH]."),
  (Y, "The soft fork matters because it is how every consensus change in this chapter was made: BIP68, BIP112 and BIP113 for the sequence and lock time, BIP34 for the coinbase, BIP141 for segwit, and the earliest known soft fork that made lock time a consensus rule at block 31,000 [AH] [BCD]. Old nodes keep following the chain because every block that new nodes accept is also valid to them; what they lose is the ability to check the new rules, so they accept on trust what new nodes verify."),
  (H, "The worked example states the test as set inclusion: the set of what new nodes accept must be a subset of what old nodes accept. For segwit, the trick is that a spend of a segwit output is, to an old node, a spend of an anyone-can-spend output with an empty input script, which old rules accept; new rules add the requirement of a valid witness, which only tightens. The book notes the condition in its parenthesis: enforcing new rules this way works only if the upgraded nodes are the economic majority, which its chapter on mining explores [AH]."),
  (K, "The caution is that a soft fork can only restrict. A change that gives new meaning to previously forbidden data is impossible as a soft fork, which is why upgrades are built on reserved and anyone-can-spend features that are valid but unused under the old rules; the version branch's presigned-transaction section is the other side of this coin [AH]. A second caution is that old nodes after a soft fork are secure only to the extent that the miners enforce the new rules, since the old nodes cannot.")), None),

 ("WitnessProgram", "Witness program", 3, "SegregatedWitness", ("a version number and 2 to 40 bytes", "A witness program is the data in a segwit output script: a script of a number from 0 to 16 followed by 2 to 40 bytes is the segwit template, the number its version and the data the witness program; old nodes may spend it with an empty input script, new nodes require one.", ("(lambda s: (s[0] - 0x50 if s[0] else 0, s[1], len(s) - 2))(bytes.fromhex('51203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068'))", "(1, 32, 32)")), P(
  (W, "A witness program is the data part of a segwit output script. The book says the soft-fork segwit approach is based on anyone-can-spend output scripts: a script that starts with any of the numbers 0 to 16 followed by 2 to 40 bytes of data is defined as a segwit output script template, the number indicates its version - 0 is segwit version 0 - and the data is called a witness program; it is also possible to wrap the template in a P2SH commitment, which the chapter does not deal with [AH] [B141]."),
  (Y, "The template matters because it is how segwit became a soft fork. From the perspective of old nodes, the book says, these output script templates can be spent with an empty input script, while from the perspective of a new node any payment to a segwit template must only be spent with an empty input script; old nodes allow it, new nodes require it [AH]. Both of Alice's outputs are witness programs - a version 1 program of 32 bytes to Bob and a version 0 program of 20 bytes for her change - and the output she spends is a version 1 program too [MP]."),
  (H, "The worked example decodes Alice's first output script: the first byte 0x51 is the number 1, so the version is 1; the second byte is a push of 32; and 32 bytes follow, the witness program, which for taproot is a public key. For version 0, the book's chapter 4 explained the two program lengths - 20 bytes for a public key hash, 32 for a script hash - and the chapter's library checks the template's bounds of 2 to 40 bytes. The book connects the template to a trend of increasing abstraction: the whitepaper received to public keys and spent with signatures, the original release to output scripts and input scripts, and segwit to witness programs and the witness structure [AH]."),
  (K, "The caution is that an unknown version is still anyone-can-spend to every node, including new ones: versions 2 to 16 have no rules yet, so a payment to such a program can be taken by anyone, and wallets refuse to send to them. A second caution is that the version number in the script, 0 to 16, is unrelated to the transaction version of the version branch; both are called version and they count different things.")), None),

 ("WitnessStructure", "Witness structure", 3, "SegregatedWitness", ("the new field for what the input script held", "The witness structure is the field added by segwit to hold the data that an input script may no longer carry; it sits after the outputs and before the lock time and is not part of the txid.", ("[('whitepaper', 'public key', 'signature'), ('legacy', 'output script', 'input script'), ('segwit', 'witness program', 'witness structure')]", "[('whitepaper', 'public key', 'signature'), ('legacy', 'output script', 'input script'), ('segwit', 'witness program', 'witness structure')]")), P(
  (W, "The witness structure is the field segwit added to the transaction. The book says that with no ability to put data in an input script, users of segwit output script templates need a new field, and that field is called the witness structure [AH]. It is serialized after the outputs and before the lock time, it holds one witness stack per input, and it is excluded from the legacy serialization over which the txid is computed [B141] [B144]."),
  (Y, "The field matters because it is where authorisation now lives for most transactions, and because its placement outside the identifier is the whole of segwit's remedy. The book's table of terms lays out the three generations: the whitepaper authorised with a public key and authenticated with a signature, the original release with an output script and an input script, and segwit with a witness program and the witness structure; the worked example reproduces that table. Authorization is who may spend, authentication is proof that they did [AH]."),
  (H, "The structure is a sequence of stacks in input order, each stack a count followed by its items with their lengths; the serialization group reads Alice's, which has one stack of one 65-byte item. Because the field is outside the txid, a block cannot commit to witnesses through the ordinary transaction tree, so BIP141 adds a second commitment, a tree of witness identifiers placed in the coinbase transaction, which the coinbase group mentions and the book's chapter on mining explains [B141] [AH]."),
  (K, "The caution is that excluded from the txid does not mean uncommitted: the witness is covered by the wtxid and by the block's witness commitment, so it cannot be changed after confirmation; what it cannot do is change the txid before confirmation. A second caution is the book's own observation that the introduction of witness programs and the witness structure complicates Bitcoin, which is why the vocabulary of this branch has so many near-synonyms [AH].")), None),

 ("WitnessSerialization", "Witness structure serialization", 2, "Witnesses", None, P(
  (W, "This group reads the bytes of the witness structure. The book says that, similar to the inputs and outputs fields, the witness structure contains other fields, and it starts from a map of those bytes in Alice's transaction; unlike those fields, the overall structure does not start with any indication of the total number of witness stacks it contains, because that is implied by the inputs field - there is one witness stack for every input [AH]."),
  (Y, "The group matters because it is the last variable-length part of the transaction and the one whose count is implicit, which trips parsers. It also shows how legacy inputs coexist with segwit inputs in one transaction: every input has a stack, and a legacy input's stack is the single byte zero. Alice's transaction has one input and one witness item, a 65-byte signature, which is the whole of its authorisation [AH]."),
  (H, "The three sections read the structure from the outside in: the witness stack, one per input, with its count of items; the witness item, each prefixed by a compactSize length, which the book says it explores in detail in the next chapter; and the legacy input's witness, a count of zero that makes the structure uniform across input types [AH].")), None),

 ("WitnessStack", "Witness stack", 3, "WitnessSerialization", ("one stack per input, counted by the inputs", "A witness stack is the part of the witness structure belonging to one input: a compactSize count of items followed by the items; there is one stack per input, so the structure has no count of its own.", (PROG("tx = bytes.fromhex('01000000000101eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a0100000000ffffffff02204e0000000000002251203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068f8240100000000001600147752c165ea7be772b2c0acb7f4d6047ae6f4768e0141cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e817130100000000')\nn_inputs = tx[6]\nstack_count = tx[123]                      # the witness structure starts at offset 123\nresult = (n_inputs, stack_count)"), "(1, 1)")), P(
  (W, "A witness stack is the witness of one input: the book says the witness structure for a particular input starts with a count of the number of elements it contains, and that those elements are called witness items [AH]. The number of stacks is not stored; the book says it is implied by the inputs field, since there is one witness stack for every input in a transaction [AH]. In Alice's transaction the structure begins at offset 123 with the byte 01, one item."),
  (Y, "The stack matters because it is the unit that the output script's witness version interprets. A version 0 program paying a public key hash expects a stack of two items, a signature and a public key; a version 1 taproot key path expects a single item, the signature, which is Alice's case; and a script path expects the script and its control block as the last two items. What the items mean is for the next chapter; this chapter reads the counts [AH] [B141]."),
  (H, "The worked example reads the input count at offset 6 and the item count at offset 123 and finds 1 and 1. A parser must therefore remember the input count from the beginning of the transaction and read that many stacks here; the chapter's library does so, and the byte map of the witness structure that the book draws shows the count byte, the length byte and the 65-byte item [AH]. Because each stack is self-delimiting through its counts, stacks for several inputs simply follow one another."),
  (K, "The caution is the one the book makes explicit: there is no count at the start of the structure, and a parser that expects one will read the first stack's item count as a stack count and misread everything after. A second caution is that an item count of zero is a complete stack, which the legacy input section explains; the structure is never shorter than one byte per input.")), None),

 ("WitnessItem", "Witness item", 3, "WitnessSerialization", ("a 65-byte signature, length-prefixed", "A witness item is one element of a witness stack, prefixed by a compactSize integer giving its size; Alice's single item is a 65-byte signature.", (PROG("tx = bytes.fromhex('01000000000101eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a0100000000ffffffff02204e0000000000002251203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068f8240100000000001600147752c165ea7be772b2c0acb7f4d6047ae6f4768e0141cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e817130100000000')\nitem_len = tx[124]\nitem = tx[125:125 + item_len]\nresult = (item_len, item[:4].hex(), item[-1])"), "(65, 'cf5efe2d', 1)")), P(
  (W, "A witness item is one element of a witness stack. The book says each witness item is prefixed by a compactSize integer indicating its size, that the items are explored in detail in the next chapter, and that Alice's transaction contains one input and one witness item [AH]. The worked example reads the length byte at offset 124, 65, and the item that follows, which begins cf5efe2d and ends with the byte 01."),
  (Y, "The item is the witness in the concrete sense: for Alice's taproot spend it is a Schnorr signature of 64 bytes followed by one byte, the signature hash flag of the wanted-malleability section, which here is 1, the default that commits to the whole transaction. The explorer labels the output type v1_p2tr and shows this item as the input's witness [MP]. Its 65 bytes are also the largest single field of the transaction and the one most cheaply priced by the weight rules, which the weight branch explains."),
  (H, "The length prefix makes items of any size possible: a signature of 65 bytes, a public key of 33, a script of hundreds, each with its own prefix, and a prefix of 0xfd and two more bytes for an item above 252 bytes. The book's byte map of the witness structure shows the count, the length and the item; the chapter's library records each as a span, and an executed claim parses the item and checks its length and its last byte [AH]."),
  (K, "The caution is that a witness item is data, not script: the item is pushed onto the stack as it stands, so the push encodings that caused third-party malleability do not exist here, which is a second, less-noticed reason segwit removes that problem [B141]. A second caution is that the trailing 01 is part of the item - a 64-byte signature with the default flag could in principle omit it, which is why the next chapter treats the flag's encoding.")), None),

 ("LegacyInputWitness", "A legacy input's witness", 3, "WitnessSerialization", ("a stack of zero items", "A legacy input in a segwit transaction has a witness stack consisting entirely of a count of zero, 0x00, so the structure stays one stack per input.", ("(lambda stacks: [len(s) for s in stacks])([[], ['signature', 'public key']])", "[0, 2]")), P(
  (W, "A legacy input's witness is the empty stack. The book says legacy inputs do not contain any witness items, so their witness stack consists entirely of a count of zero, 0x00 [AH]. In a transaction that mixes a legacy input and a segwit input, the witness structure therefore has two stacks, one empty and one with items, in the order of the inputs."),
  (Y, "The rule matters because it keeps the structure regular. If legacy inputs had no stack at all, a parser would need to know, for every input, whether the output it spends is a segwit output - information that is in the UTXO database, not in the transaction - before it could parse the witness; with a zero count the parser needs only the input count. The worked example shows the two stacks, of zero and two items."),
  (H, "The zero byte is the compactSize encoding of the count zero, so it is one byte and takes one weight unit. A transaction whose inputs are all legacy would have a structure of nothing but zero bytes, which is why the book's closing section says the legacy format must be used for any transaction with an empty witness structure: the marker and flag would announce a witness that carries nothing [AH]. BIP144 makes the same rule for the network [B144]."),
  (K, "The caution is that a legacy input in a segwit transaction is still malleable: its signature is in its input script, which is in the txid, so a third party can still re-encode its pushes. The protections of this branch apply input by input, and a protocol that needs them must spend only segwit outputs. A second caution is that an empty stack is not an invalid one; the stack of an input spending an anyone-can-spend legacy output is empty and valid.")), None),
]

CHECKS_F = [
 Qb("ch06_transactions.adoc", "In court,", "a witness is someone who testifies that they saw something", "important happen."),
 Qb("ch06_transactions.adoc", "2 OP_ADD 4 OP_EQUAL", "<public key> OP_CHECKSIG"),
 Qb("ch06_transactions.adoc", "That public identifier is", "called a _public key_ and a", "solution to the equation is called a _signature_."),
 Qb("ch06_transactions.adoc", "making", "it a _trustless", "protocol_.", "This is a", "_circular dependency_."),
 Qb("ch06_transactions.adoc", "OP_2", "OP_PUSH1 0x02", "OP_PUSH2 0x0002", "OP_PUSHDATA1 0x0102", "OP_PUSHDATA4 0x0000000102"),
 Qb("ch06_transactions.adoc", "a problem called _unwanted third-party transaction", "malleability_."),
 Qb("ch06_transactions.adoc", "the signer has to choose a large random number when creating their", "signature", "is called _unwanted second-party transaction malleability_."),
 Qb("ch06_transactions.adoc", "we will occasionally prefix the", "word _unwanted_ to the term _transaction malleability_"),
 Qb("ch06_transactions.adoc", "The idea of separating the rest of", "the data in a transaction from its witness for the purpose of generating a", "txid is called _segregated witness_ (segwit)."),
 Qb("ch06_transactions.adoc", "also", "called", "a _hard fork_.", "called a", "_soft fork_."),
 Qb("ch06_transactions.adoc", "A script that starts with any of the numbers 0 to 16", "and followed by 2 to 40 bytes of data is defined as a segwit", "output script template", "The data is called a _witness", "program_."),
 Qb("ch06_transactions.adoc", "old nodes _allow_ an empty input script; new nodes", "_require_ an empty input script."),
 Qb("ch06_transactions.adoc", "That field is called the _witness structure_."),
 Qb("ch06_transactions.adoc", "there's one witness", "stack for every input in a transaction", "Those elements are", "called _witness", "items_.", "Legacy inputs don't contain any witness items, so their witness stack", "consists entirely of a count of zero (0x00)."),
 Qb("ch06_transactions.adoc", "Alice's transaction contains one input and one", "witness item."),
 Qe("bip-0141.mediawiki", "Segregated Witness (Consensus layer)"),
 Qe("bip-0062.mediawiki", "Dealing with malleability", "Status: Closed"),
 Qc("src/kernel/chainparams.cpp", "consensus.SegwitHeight = 481824;"),
 # the separation, executed on Alice's transaction
 X("T.txid(%r)" % ALICE, repr(ALICE_TXID)),
 X("T.wtxid(%r)" % ALICE, "'f7cdbc7cf8b910d35cc69962e791138624e4eae7901010a6da4c02e7d238cdac'"),
 X("(T.txid(T.with_witness_item(%r, '00' * 65)) == T.txid(%r), T.wtxid(T.with_witness_item(%r, '00' * 65)) == T.wtxid(%r))" % (ALICE, ALICE, ALICE, ALICE), (True, False)),
 X("T.parse_tx(%r)['witness']" % ALICE, [['cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e81713' + '01']]),
 X("[(n, p, k) for n, p, k in T.parse_tx(%r)['spans'] if n.startswith('witness')]" % ALICE, [('witness 0 count', 123, 1), ('witness 0 item 0 length', 124, 1), ('witness 0 item 0', 125, 65)]),
 X("C.ev_json('mempool_tx_466200308696215b_v1_0_0.json')['vin'][0]['witness']", ['cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e8171301']),
 # the push encodings, on the first bitcoin transaction's legacy input
 X("T.push_encodings(2)", {'OP_2': '52', 'OP_PUSH1 0x02': '0102', 'OP_PUSH2 0x0002': '020200', 'OP_PUSHDATA1 0x0102': '4c0102'}),
 X("len({T.txid(T.with_input_script(C.ev_hex('tx_first_f4184fc5_v1_0_0.hex'), s)) for s in T.push_encodings(2).values()})", 4),
 X("T.txid(C.ev_hex('tx_first_f4184fc5_v1_0_0.hex'))", "'f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16'"),
 X("[T.segwit_output_version(s) for s in ('0014' + '11' * 20, '0020' + '22' * 32, '5120' + '33' * 32, '76a914' + '44' * 20 + '88ac', '0001' + '55')]", [(0, '11' * 20), (0, '22' * 32), (1, '33' * 32), None, None]),
 ("(0x52 - 0x50, 0x51 - 0x50, 0x60 - 0x50)", "(2, 1, 16)"),
 ("(1 + 1 + 65, 64 + 1)", "(67, 65)"),
]
