"""SEN0401 chapter 4, corpus text part C (version 1.1.0): representations, key encodings and checksummed text."""
from sen0401_ch04_text_a_v1_1_0 import W, Y, E, H, K, KHEX, NHEX, YHEX
B58LIT = "'123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'"
WIFIO = ("(lambda h, d: (lambda n: ''.join(" + B58LIT + "[n // 58 ** i % 58] for i in range(60)[::-1]).lstrip('1'))(int.from_bytes(d + h(h(d).digest()).digest()[:4], 'big')))(__import__('hashlib').sha256, bytes.fromhex('80" + KHEX + "'))",
         "'5J3mBbAH58CpQ3Y5RNJpUKPE62SQ5tfcvU2JpbnkeyhfsYB1Jcn'")
ADDRCHK = ("(lambda d: __import__('hashlib').sha256(__import__('hashlib').sha256(d[:21]).digest()).digest()[:4] == d[21:])(sum(" + B58LIT + ".index(c) * 58 ** i for i, c in enumerate('1J7mdg5rbQyUHENYdx39WVWK7fsLpEoXZy'[::-1])).to_bytes(25, 'big'))", "True")
CHKHEX = ("__import__('hashlib').sha256(__import__('hashlib').sha256(bytes.fromhex('80" + KHEX + "')).digest()).digest()[:4].hex()", "'c47e83ff'")

NODES_C = [
 ("Format", None, 1, None, None, [
  (W, "This branch is about writing the same information down in different ways. A private key, a public key and a hash commitment are all numbers, and a number can be shown in binary, in hexadecimal, in a compact alphabet with a built-in checksum, or in a two-dimensional barcode. The choice of representation never changes the number, but it decides how long the text is, how easily a person can read it aloud, how likely a copying mistake is and whether the software can notice the mistake."),
  (Y, "Representation matters in Bitcoin because mistakes are expensive. The book points out that any mistake made in copying a commitment would result in the bitcoins being sent to an unspendable output, causing them to be lost forever [BK]. A payment cannot be recalled by a bank, so the text that Alice copies from Bob must either be correct or be recognised as incorrect before the money moves. All the formats of this branch are answers to that single concern, and the checksums in particular turn silent errors into visible ones."),
  (E, "The formats appear in every wallet. Hexadecimal and raw binary are used internally in software and rarely shown to users, while the wallet import format is used for importing and exporting keys between wallets and for printing them as barcodes [BK]. Addresses use the base58check or the bech32 family of encodings, and the first character or the first few characters of such a string tell a trained eye which kind of data it is."),
  (H, "The branch has three levels of content. The first covers the basic ways to count and store data, bits, bytes, number bases and barcodes. The second covers the encodings of keys: the compressed and the uncompressed public key, the wallet import format of a private key, and the oddly named compressed private key. The third covers checksummed text: the checksum, the base58check procedure built from it, the version prefix that identifies the data type and the choice between the main network and the test network."),
  (K, "Never judge two strings to be different data merely because they look different, and never judge them equal merely because they begin alike. The book's central example is a single private key that appears in three different formats and a single public key that appears in two formats and yields two different addresses [BK]. Keeping the data and its representation apart in the mind is the central discipline of this branch."),
 ], None),
 ("Representation", "Representation of data", 2, "Format", None, [
  (W, "The representation of data is the way a value is written down: as a count of bits, as a sequence of bytes, as digits in some number base, or as a picture that a camera can read. One and the same number has all of these forms at once, and none of them is more real than the others. This level gathers the three basic notions on which the encodings of the rest of the chapter build, so that a later section can speak of 65 bytes, of 130 hexadecimal digits or of a scanned code without having to explain itself again."),
  (Y, "Every length that the chapter quotes, 32 bytes, 65 bytes, 130 hexadecimal digits, is a statement about a representation, and every conversion between formats is a change of representation. A reader who is not at ease with bits, bytes and number bases will find the later sections impossible to follow, so they are defined here before they are used."),
  (H, "The concept of bits and bytes comes first, since every length in the chapter is counted in one or the other. The number base follows, because hexadecimal, base58, base64 and the base 32 of bech32 are all bases for writing the same numbers, and the choice of base decides how long the text is and which characters appear in it. The barcode closes the level, because the shortness of an address and the case in which it is written decide how well it can be shared as a picture rather than as text. Each of the three is met again in the levels that follow, where they are used and no longer explained."),
 ], None),
 ("BitsAndBytes", "Bits and bytes", 3, "Representation", ("65 bytes is 520 bits", "A bit is a binary digit, 0 or 1; a byte is 8 bits; a public key of 65 bytes has 520 bits, and each hexadecimal digit stands for 4 bits.", ("(65 * 8, 33 * 8)", "(520, 264)")), [
  (W, "A bit is a binary digit, which has the value 0 or 1, and a byte is a group of 8 bits. Sizes in Bitcoin are quoted in both units, and the chapter moves between them freely: the book describes a private key as 256 bits shown as 64 hexadecimal digits of 4 bits each [BK], a hash commitment as 160 bits or 20 bytes, and a public key as 65 bytes or 33 bytes."),
  (Y, "The units decide how much space data takes and how large the space of possible values is. A value of 256 bits can take 2 to the 256 different values, which is the reason for the book's statement that the private key space is unfathomably large [BK], while a value of 20 bytes has 160 bits and therefore only 2 to the 160 possible values. When the chapter later compares the strength of different commitments, it is comparing numbers of bits."),
  (E, "Everywhere in the chapter you will find the conversion between the two units. The book gives the uncompressed public key as a 520-bit number of 130 hexadecimal digits, and the compressed one as a number of 264 bits in 66 hexadecimal digits [BK]. These are the same lengths as 65 and 33 bytes, because 65 times 8 is 520 and 33 times 8 is 264, and because a hexadecimal digit carries 4 bits, so two digits make one byte; the chapter's checks verify these equalities."),
  (H, "In Python a sequence of bytes is the type bytes, bytes.fromhex turns a string of hexadecimal digits into bytes, and the method hex() turns bytes back into digits. The built-in function len returns the number of bytes, and an integer has a bit_length() method. These few tools are all that the chapter's examples need to move between a key as a number, as bytes and as text."),
  (K, "The most frequent mistake is to mix up the number of digits with the number of bytes: 64 hexadecimal digits are 32 bytes, not 64. Another is to forget that a byte is an unsigned quantity, so that the byte 0x80 stands for 128 and not for a negative number. Count carefully and state the unit."),
 ]),
 ("NumberBase", "Number base (hexadecimal, base58, base64)", 3, "Representation", ("ff is 255", "A number base, or radix, is the count of different symbols used to write numbers; hexadecimal uses 16, base64 uses 64 and base58 uses 58, and the same number is shorter in a larger base.", ("(int('ff', 16), int('11111111', 2))", "(255, 255)")), [
  (W, "A number base, also called a radix, is the number of distinct symbols that a notation uses for writing numbers. The traditional decimal system uses 10 numerals, 0 through 9, and the hexadecimal system uses 16, with the letters A through F as the six additional symbols. The book adds that a number written in hexadecimal is shorter than the equivalent decimal representation, and that base64 representation uses 26 lowercase letters, 26 capital letters, 10 numerals and 2 more characters such as + and /, in order to transmit binary data over text-based media such as email [BK]."),
  (Y, "The bigger the alphabet, the fewer symbols are needed for the same number, which is why compact formats are attractive for things that people have to copy. The book introduces base58 for this reason: it is a similar encoding to base64 that uses upper- and lowercase letters and numbers, but omits some characters that are frequently mistaken for one another and can appear identical when displayed in certain fonts [BK]. A larger alphabet gains length, a careful alphabet gains reliability, and base58 is a compromise."),
  (E, "Hexadecimal is the notation in which the chapter prints keys, hashes and coordinates, and base58 is the notation of legacy addresses and of keys in the wallet import format. Base64 is mentioned by the book only for comparison. Bech32, which later sections introduce, is a base 32 notation. The chapter's checks confirm that the base58 alphabet has 58 distinct characters, that it is the base64 alphabet without the six characters 0, O, l, I, + and /, and that the same private key needs fewer symbols in each larger base."),
  (H, "Writing a number in base b means finding its digits when it is divided repeatedly by b. In Python int(text, 16) reads hexadecimal and int(text, 2) reads binary, so that ff and 11111111 both give 255. For base58 the book gives the alphabet 123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz, whose symbols stand for the values 0 to 57 in order [BK]; a number is divided by 58 again and again, and each remainder selects one symbol. The one-expression example of the wallet import format in a later concept does exactly that."),
  (K, "A symbol means different things in different bases, and an alphabet is meaningful only together with its order. The digit 1 is the value one in decimal and hexadecimal but is the first symbol, the value 0, in the base58 alphabet, a fact that explains why leading zero bytes appear as the character 1 in addresses. Base conversion also needs care with leading zeros, which a number does not have but a byte string does."),
 ]),
 ("QrCode", "QR code", 3, "Representation", ("an address as a picture", "A QR code is a two-dimensional barcode that a camera can read; its alphanumeric mode makes uppercase text about 45 percent more compact than the normal byte mode, which is why bech32 addresses are put into QR codes in uppercase.", ("'BC1Q9D3XA5GG45Q2J39M9Y32XZVYGCGAY4RGC6AAEE'.lower()", "'bc1q9d3xa5gg45q2j39m9y32xzvygcgay4rgc6aaee'")), [
  (W, "A QR code is a two-dimensional barcode, a square pattern of dots, that a phone camera can read to obtain a short piece of text such as an address or an invoice. Wallets use it because it removes typing altogether: the book notes that QR codes are commonly used to share addresses and invoices between wallets [BK]. Chapter 2 already showed a QR code that carried a payment request with an address, an amount and a label."),
  (Y, "The size of the text decides the size of the picture. The book observes that a mixed-case alphabet requires extra space in QR codes, so that the codes need to be larger at the same resolution or become harder to scan quickly [BK]. The proposal that introduced bech32 lists the same point among its motivations: base58 needs a lot of space in QR codes, as it cannot use the alphanumeric mode [B173]. A smaller picture scans faster and is more tolerant of poor cameras."),
  (E, "QR codes are met next to cash registers, on invoices, on paper wallets and on screens. The proposal for pay to script hash named them as a reason for short commitments, saying that a 20-byte hash is short enough to scan from a QR code or easily copied and pasted [B16]. The book's figure of the same bech32 address encoded twice shows the effect in practice: the lowercase version and the uppercase version give two QR codes of visibly different size and complexity [BK]."),
  (H, "The bech32 specification says that encoders must always output a lowercase string, and that an uppercase version may be produced outside the encoding process, for presentation or for QR code use; decoders must not accept strings that mix uppercase and lowercase letters [B173]. Inside QR codes uppercase should be used, because uppercase permits the alphanumeric mode, which the proposal describes as 45 percent more compact than the normal byte mode [B173]. The chapter's checks confirm that the uppercase form of the book's address decodes to the same witness program as the lowercase form, and that a mixed-case form is rejected."),
  (K, "The saving applies only to alphabets that fit the alphanumeric mode, which is why base58 text, with its mixed case, cannot profit from it. Another caution is that the picture is only the address in a different form: whatever the camera reads is still text, and a careful wallet shows the decoded text so that the person can compare it with what was intended."),
 ]),
 ("KeyEncoding", "Key encoding", 2, "Format", None, [
  (W, "A key encoding is a particular way of writing a key down as bytes or as text. The same private key has several (hexadecimal, wallet import format, wallet import format with a compression flag), and the same public key has two (compressed and uncompressed). All of them stand for the same underlying number or point, and the book stresses that any one format can easily be converted to any other [BK]."),
  (Y, "Software that exports or imports keys must agree on the encoding, otherwise the receiving wallet may look for the wrong addresses. The book explains the case concretely: a wallet that imports keys from an older wallet needs to know whether to scan the blockchain for 65-byte keys and the commitments to them, or for 33-byte keys and their commitments, and failure to scan for the right type can lead to the user not being able to spend the full balance [BK]."),
  (H, "The four concepts of this level start with the two forms of the public key, which differ in size and in the address they produce. They continue with the wallet import format, the text form in which a private key is exported, and they end with the compressed private key, a name that the book calls a misnomer and that the section explains in order to retire it."),
 ], None),
 ("CompressedPublicKey", "Compressed public key", 3, "KeyEncoding", ("33 bytes: 02 or 03 and x", "A compressed public key keeps only x and one byte for the parity of y, 33 bytes instead of 65, and the y coordinate is recovered by solving the curve equation.", ("round(1 - 33 / 65, 3)", "0.492")), [
  (W, "A compressed public key is an encoding of a public key that stores the x coordinate and one extra byte instead of both coordinates. When Bitcoin was first written its developers only knew how to create 65-byte public keys; a later developer found an alternative encoding that used only 33 bytes and was backward compatible with all Bitcoin full nodes at the time, so that the protocol did not need to change [BK]. The 33-byte keys are called compressed public keys and the original 65-byte keys are called uncompressed public keys."),
  (Y, "Smaller keys make smaller transactions, and smaller transactions let more payments fit into the same block [BK]. Omitting the 256-bit y coordinate reduces the size of the key by almost 50 percent, which the chapter's checks put at 49.2 percent, and the saving is repeated in every transaction that reveals a key. Compressed public keys are now the default in almost all Bitcoin software and were required for certain features added by later protocol upgrades [BK]."),
  (E, "The compressed form of the book's example key is 03F028892BAD7ED57D2FB57BF33081D5CFCF6F9ED3D3D7F159C2E2FFF579DC341A, a number of 264 bits written in 66 hexadecimal digits [BK]. It is the form that modern wallets hash into addresses, and it is the form that the 'compressed' private key format of a later concept announces. Older wallets that still use the uncompressed form are the reason why software must be able to read both."),
  (H, "The method rests on the curve equation. Since the point (x, y) satisfies y squared = x cubed + 7, knowing x leaves only two possible values of y, which are a number and its negative modulo p, the mirror pair of the curve's symmetry [BK]. One of the two is even and the other is odd, because p is odd, so a single prefix byte settles the choice: 02 means that y is even and 03 means that y is odd [BK]. For the book's key the y coordinate ends in B, an odd digit, hence the prefix 03. The chapter's checks recover the full point from the 33 bytes by computing a modular square root, and they find the original coordinates."),
  (K, "Compression changes the bytes that are hashed. The same private key gives two public key formats, and if the compressed key is turned into a commitment with HASH160 it produces a different commitment from the uncompressed key, leading to a different address; the private key is identical for both addresses [BK]. A wallet that scans for only one of the two forms will miss funds that were paid to the other."),
 ]),
 ("UncompressedPublicKey", "Uncompressed public key", 3, "KeyEncoding", ("65 bytes: 04, x and y", "An uncompressed public key is the prefix 04 followed by the x and y coordinates, 65 bytes, and it hashes to a different address than the compressed form of the same key.", ("len(bytes.fromhex('04F028892BAD7ED57D2FB57BF33081D5CFCF6F9ED3D3D7F159C2E2FFF579DC341A07CF33DA18BD734C600B96A72BBC4749D5141C90EC8AC328AE52DDFE2E505BDB'))", "65")), [
  (W, "An uncompressed public key is the original encoding of a public key: the prefix byte 04 followed by the 32-byte x coordinate and the 32-byte y coordinate, 65 bytes in all. The book writes it as 04 x y and shows the example key as a 520-bit number of 130 hexadecimal digits [BK]. The shortest version of Bitcoin public keys known to the early developers was this 65-byte form, the equivalent of 130 characters in hexadecimal [BK]."),
  (Y, "Understanding the uncompressed form is necessary because it has not disappeared. The book says that some software still needs to support uncompressed public keys, such as a wallet application importing private keys from an older wallet, and that such a wallet must scan for both kinds of key and for commitments to both [BK]. The funds paid to an address built from an uncompressed key can only be spent by presenting that same uncompressed key."),
  (E, "Early Bitcoin addresses, some of which still hold funds, were built from uncompressed keys. The book's example key gives the P2PKH address 1424C2F4bC9JidNjjTUZCbUxv6Sa1Mt62x in this form, and Bitcoin Core 31.1 returned the same address when asked for the address of that uncompressed key and called it valid [CORE]. This is a different address from the one derived from the compressed form of the same key."),
  (H, "The prefix byte 04 tells the reader that both coordinates follow. To obtain the uncompressed form from a compressed one, software performs the square-root calculation described in the previous concept, and to compress, it keeps x and the parity of y. The two conversions lose nothing in either direction, which the chapter's checks demonstrate by a round trip on the example key."),
  (K, "Since the compressed and uncompressed keys are two encodings of one point, they are easily taken for two different keys. They correspond to the same private key, yet they lead to different HASH160 values and different legacy addresses, and a user who exports a key from an old wallet without recording which form it used may later look in the wrong place for the balance."),
 ]),
 ("WalletImportFormat", "Wallet import format (WIF)", 3, "KeyEncoding", ("5J3m... and KxFC...", "The wallet import format is the base58check encoding of version byte 0x80 and the private key, with a 0x01 suffix for the compressed form, which changes the first character from 5 to K or L.", WIFIO), [
  (W, "The wallet import format, abbreviated WIF, is the text form in which a private key is exported from one wallet and imported into another. It is the base58check encoding of the version byte 0x80 followed by the 32-byte private key, and, for keys that produce compressed public keys, an extra byte 01 at the end [BK]. For the book's example key the WIF is 5J3mBbAH58CpQ3Y5RNJpUKPE62SQ5tfcvU2JpbnkeyhfsYB1Jcn, and the compressed WIF is KxFC1jmwwCoACiCAWZ3eXa96mBM6tb3TYzGmf6YwgdGWZgawvrtJ."),
  (Y, "A raw 64-digit hexadecimal number is awkward to copy and carries no protection against typing errors. The WIF gives the key a recognisable first character and a checksum, so that a wallet can reject a mistyped key instead of importing a different one. The book says that the WIF is used for import and export of keys between wallets and often for QR code representations of private keys [BK]."),
  (E, "The WIF is met when someone moves a single key from an old wallet to a new one, and in older instructions for paper wallets and key backups. The book notes, however, that modern wallets generate all their keys from a single seed and rarely allow a single key to be imported or exported, so that the information about private key formats is mainly of interest to anyone needing compatibility with early Bitcoin wallets [BK]. A later concept on key export describes what Bitcoin Core did about the question."),
  (H, "The procedure has four steps. Put the version byte 0x80 in front of the key, add the byte 01 behind it if the key is for compressed public keys, append the first four bytes of the double SHA256 of the result, and write the whole in the base58 alphabet. The chapter's checks do this in one expression and obtain the book's WIF string, and with the extra byte they obtain the book's compressed string. Decoding reverses the steps and verifies the four checksum bytes. Without the suffix the result is 51 characters long and with it 52, and the first character is always 5 for the first and K or L for the second."),
  (K, "A WIF string is a private key, to be treated like one: anyone who sees it can spend the funds. Do not paste it into web pages, do not photograph it and do not mix up the two forms. The first character is the safety signal: 5 means that the wallet must look for the uncompressed public key and its addresses, and K or L means that it must look for the compressed ones [BK]."),
 ]),
 ("CompressedPrivateKey", "Compressed private key", 3, "KeyEncoding", ("a misnomer: one byte longer", "A 'compressed private key' is not compressed: it is the private key followed by a one-byte suffix 01 that says only compressed public keys should be derived from it, so its WIF is one character longer.", ("len('KxFC1jmwwCoACiCAWZ3eXa96mBM6tb3TYzGmf6YwgdGWZgawvrtJ') - len('5J3mBbAH58CpQ3Y5RNJpUKPE62SQ5tfcvU2JpbnkeyhfsYB1Jcn')", "1")), [
  (W, "The commonly used term 'compressed private key' is a misnomer. When a private key is exported as WIF-compressed it is actually one byte longer than an 'uncompressed' private key, because it has an added one-byte suffix, shown as 01 in hexadecimal, which signifies that the private key is from a newer wallet and should only be used to produce compressed public keys [BK]. Private keys are not themselves compressed and cannot be compressed."),
  (Y, "The distinction prevents a practical error. The term really means 'private key from which only compressed public keys should be derived', and the term 'uncompressed private key' really means 'private key from which only uncompressed public keys should be derived' [BK]. The book therefore advises referring to the export format as WIF-compressed or WIF and not to the private key itself as compressed, to avoid further confusion."),
  (E, "The flag shows up in exported keys. The hexadecimal form of the book's example with the suffix is the original 64 digits followed by 01, and the base58check form begins with K or L. The base58 version prefix is the same, 0x80, for both WIF and WIF-compressed; the extra byte changes the length of the number and therefore the first character from 5 to K or L [BK]."),
  (H, "The book offers an analogy: the difference is like that between the decimal numbers 100 and 99, where 100 is one digit longer and also has a prefix of 1 instead of 9. As the length changes, it affects the prefix, and in base58 the prefix 5 changes to K or L as the length increases by one byte [BK]. The chapter's checks confirm the mechanism for the extreme keys, the smallest and the largest possible 32-byte values: without the suffix the first character is 5, with it the first character is K or L, and the decoded payload has 34 bytes against 33 bytes without the suffix when the version byte is counted."),
  (K, "The formats are not used interchangeably. In a newer wallet that implements compressed public keys the private keys are only ever exported as WIF-compressed with a K or L prefix, and in an older implementation that does not use compressed public keys they are exported as WIF with a prefix of 5 [BK]. The goal is to signal to the importing wallet whether it must search the blockchain for compressed or uncompressed public keys and addresses. Treat the suffix as a message, not as a compression."),
 ]),
 ("Checksummed", "Checksummed text", 2, "Format", None, [
  (W, "Checksummed text is text that carries a few extra characters computed from the rest, so that the reader of the text can detect a copying mistake. Base58check is the first such format in this chapter and bech32 is the second. This level gathers the notion of the checksum, the base58check procedure, the version prefix that is part of the data it protects, and the distinction between networks that the prefix expresses."),
  (Y, "An address is typed, read aloud or copied by people, and a payment to a mistyped address is lost. A checksum is the cheapest defence: the wallet recomputes the check and refuses an address that does not match. The book states the benefit in a single sentence, that the check prevents a mistyped Bitcoin address from being accepted by the wallet software as a valid destination, an error that would otherwise result in loss of funds [BK]."),
  (H, "The concepts below follow the construction. The checksum is explained in general, the base58check algorithm builds on it, the version prefix is the first part of the protected data, and the network selector explains the second function of the prefix and of the human-readable part of bech32 addresses, which is to keep the main network and the test network apart."),
 ], None),
 ("Checksum", "Checksum", 3, "Checksummed", ("four bytes that catch typos", "A checksum is a short value computed from data and attached to it so that a changed copy can be detected; base58check uses the first four bytes of a double SHA256, a mistyped address fails the check.", ADDRCHK), [
  (W, "A checksum is a short value derived from a piece of data and attached to it. Anyone who has the data and the attached value can recompute the check and see whether they still agree; if the data was altered, they will with overwhelming probability disagree. In base58check the checksum is an additional four bytes added to the end of the data being encoded, derived from the hash of that data, and therefore able to detect transcription and typing errors [BK]."),
  (Y, "Detection is worth a lot even without correction. When the decoding software calculates the checksum of the data and compares it with the one included in the code, a mismatch means that an error has been introduced and the data is invalid [BK]. The wallet can then ask for the address again. The only alternative is to send the money and find out afterwards."),
  (E, "Checksums are common outside Bitcoin, in the check digits of identification numbers and in file downloads. Inside the chapter they appear twice: as the four bytes of base58check, and as the six characters of a bech32 address, which the book describes as a checksum produced by a BCH code that is exactly 6 characters long [BK]. In both cases the checksum carries no information of its own."),
  (H, "The check is only as strong as its length. Four bytes are 32 bits, so a string that was changed at random still passes the base58check test with probability 1 in 2 to the 32, about 2.3 times 10 to the minus 10, and six bech32 characters are 30 bits, giving less than 1 in 10 to the 9, which is the figure the bech32 proposal states for errors beyond the guaranteed ones [B173]. The chapter's checks recompute the four checksum bytes of the book's P2PKH address from its first 21 bytes and find them equal to the last four, and they show that changing one character of the address breaks the check."),
  (K, "A checksum detects accident, not attack. Anyone who changes an address on purpose can compute a new valid checksum, so the check protects against typing mistakes and not against a malicious replacement of the whole string. It also says nothing about whether the address is the one you meant: a perfectly valid address that belongs to someone else passes every check."),
 ]),
 ("Base58Check", "Base58check encoding", 3, "Checksummed", ("an alphabet without 0, O, l and I", "Base58check encodes a version byte, the data and the first four bytes of a double SHA-256 checksum in a 58-character alphabet that leaves out the characters easily mistaken for each other.", CHKHEX), [
  (W, "Base58check is the encoding that Bitcoin's legacy addresses and exported private keys use. It combines three ingredients: a version byte in front of the data, a checksum of four bytes behind it, and the base58 alphabet, which consists of lowercase and capital letters and numbers without the four characters 0, O, l and I [BK]. The book's alphabet is 123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz, with 58 symbols."),
  (Y, "The design serves people. Omitting the characters that look alike in certain fonts reduces misreading, the version prefix makes the type of data visible at a glance, and the checksum lets software refuse a damaged string. The book explains that this prevents a mistyped Bitcoin address from being accepted by the wallet software as a valid destination [BK]. A shorter representation also takes less room on paper and in messages than a hexadecimal one."),
  (E, "Base58check is used in the legacy P2PKH and P2SH addresses and in the wallet import format of private keys, and, as the book says, other data besides public key commitments are presented in it to make that data compact, easy to read and easy to check [BK]. The book's table of version prefixes lists addresses, private keys and the extended public key among the data types that use it."),
  (H, "To encode, first add the version byte to the data. Then compute the checksum as the SHA256 of the SHA256 of the prefix followed by the data, the book's double-SHA checksum, and keep the first four bytes of the resulting 32-byte hash. Append the four bytes, and write the three-part result as a number in base58 [BK]. The chapter's checks do this for the book's key: the double SHA256 of the version byte and the key begins with the four bytes that the WIF string ends with when decoded, and the toolkit's decoder verifies them again. A leading version byte of zero becomes the character 1 in front of the text."),
  (K, "Base58check is not secure encoding, and it is not even particularly efficient to compute. The bech32 proposal lists its limitations as a double SHA256 checksum that is slow and has no error-detection guarantees, a mixed case that is inconvenient to read aloud and to place in a QR code, and a decoding procedure that is complicated and relatively slow, and these are reasons why newer address types moved to another format [B173]. The book names the same weaknesses, adding that the format can detect errors but cannot help correct them [BK]."),
 ]),
 ("VersionPrefix", "Version prefix", 3, "Checksummed", ("0x00 gives 1, 0x05 gives 3", "The version byte makes the encoded text start with a recognisable character: 1 for a P2PKH address, 3 for P2SH, 5, K or L for a WIF key, and xpub for a BIP32 extended public key.", None), [
  (W, "The version prefix, which the book calls the version byte, is the first byte of the data that base58check encodes, and it identifies the type of data. The prefix zero, 0x00 in hexadecimal, indicates that the data is the commitment of a legacy pay to public key hash output script; the book's table lists 0x00 for a P2PKH address, 0x05 for a P2SH address, 0x6F and 0xC4 for the testnet counterparts, 0x80 for a private key in WIF and 0x0488B21E for a BIP32 extended public key [BK]."),
  (Y, "The prefix makes data self-describing. Because the version byte is encoded together with the rest, each prefix gives encoded strings that begin with specific characters, which makes it easy for humans to identify the type of data and how to use it. This is what differentiates, for example, a base58check-encoded address that starts with 1 from a private key in WIF that starts with 5 [BK]."),
  (E, "The resulting leading characters are the ones people recognise: 1 for P2PKH addresses, 3 for P2SH addresses, m or n for testnet P2PKH addresses, 2 for testnet P2SH addresses, 5, K or L for private keys in WIF and the letters xpub for extended public keys [BK]. The extended public key belongs to the wallet structures that Chapter 5 will present. The chapter's checks encode data of each prefix and show the first characters that come out."),
  (H, "The leading character is a consequence of the numbers and not an extra field: the prefix byte is the most significant part of a number that is then written in base 58, so its value selects the first digit or the first few. For a 20-byte payload the version 0x00 gives the character 1, the version 0x05 gives 3, and the version 0xC4 gives 2; 0x6F gives m or n depending on the payload, as the checks show for the smallest and the largest payloads. For a 32-byte payload the version 0x80 gives 5, and with the suffix 01 it gives K or L."),
  (K, "The prefix identifies the type; it does not authenticate the data. A string that starts with 1 and passes the checksum test is a plausible P2PKH address, nothing more: it may belong to anyone, and it may belong to a key that nobody holds any longer. Nor does the prefix tell the payer which script the receiver will use to spend, since the version byte names a template and the template is the same for every receiver. The prefixes of the book's table apply to base58check only; bech32 addresses express the same two ideas, the network and the kind of output, through the human-readable part and the witness version, as a later section explains."),
 ]),
 ("NetworkSelector", "Mainnet and testnet", 3, "Checksummed", ("bc and tb, 0x00 and 0x6F", "The main network and a test network are separate chains with their own data; addresses show which one they belong to through the version byte of base58check (0x00 against 0x6F for P2PKH) or through the human-readable part of bech32 (bc against tb).", ("('bc1q9d3xa5gg45q2j39m9y32xzvygcgay4rgc6aaee'[:2], 'tb1qw508d6qejxtdg4y5r3zarvary0c5xw7kxpjzsx'[:2])", "('bc', 'tb')")), [
  (W, "Bitcoin software can work with more than one network. The main network is usually called mainnet, and a test network, testnet, is a separate chain whose name says what it is for. Bitcoin Core states that all content of its data directory, except the configuration file, is chain-specific, and it keeps the data of the main chain, testnet3, testnet4, signet and regtest in separate directories [CORE]."),
  (Y, "Addresses must tell the networks apart, otherwise a payment prepared for the test network could be sent to the main network or the other way round. The version byte does the work for base58check: a P2PKH address uses 0x00 on the main network and 0x6F on the test network, and a P2SH address uses 0x05 and 0xC4, giving first characters 1, m or n, 3 and 2 [BK]. In bech32 addresses the human-readable part has the same function."),
  (E, "The book's table of human-readable parts for Bitcoin lists two entries: bc for Bitcoin mainnet and tb for Bitcoin testnet [BK]. The proposal for bech32 shows both in its examples, for instance a mainnet pay to witness public key hash address that begins with bc1q and a testnet address for the same key that begins with tb1q [B173]. The chapter's checks read the first two characters from the book's mainnet address and from the proposal's testnet address."),
  (H, "For base58check the network is part of the data that the checksum protects, so changing the prefix byte of an address changes the text and breaks the check. For bech32 the human-readable part is mixed into the checksum computation: the checksum covers the human-readable part as well as the data part, which is why an address cannot be moved to another network by replacing the letters bc with tb [B173]. The consequence is that every wallet validates the network and the checksum in one step."),
  (K, "Test coins are for testing. Do not read the validity of a testnet address as a statement about money, and do not send mainnet funds to a testnet address; the formats differ exactly so that software can stop you. Bitcoin Core lists several test chains, namely testnet3, testnet4, signet and regtest [CORE], so a tutorial that speaks of 'the testnet' without naming one is ambiguous."),
 ]),
]
