"""Source quotations behind the Usage, Foundations and Nature branches of the chapter 1 corpus (version 1.2.0): (node, saved source, pieces that must occur in it).
Each piece is a string that occurs literally in the saved copy of the source in 08-tooling/ch01-sources (index markup removed, quotes unified, white space collapsed)."""
B = "ch01_intro.adoc"; G = "glossary.asciidoc"; WP = "wp.txt"; SH = "rfc4949.txt"

SRC_C = [
 # ---------------------------------------------------------------- MONEY, the one group still without a check
 ("Supply", B, ["limiting the total number of bitcoins that will ever be created to a fixed total just below 21 million coins",
                "half of the remaining coins are added to circulation every four years"]),

 # ---------------------------------------------------------------- USAGE
 ("Usage", B, ["In this chapter we'll get started by explaining some of the main concepts and terms, getting the necessary software, and using Bitcoin for simple transactions",
               "In the next chapter we will look at her first purchase with Bitcoin, and examine the underlying transaction and propagation technologies in more detail"]),
 ("Address", B, ["There are a variety of Bitcoin addresses and invoice formats", "Addresses and invoices can be shared with other Bitcoin users who can use them to send bitcoins directly to your wallet"]),
 ("BitcoinAddress", B, ["Her wallet application randomly generated a private key", "that will be used to derive Bitcoin addresses that direct to her wallet",
                        "Her Bitcoin addresses are simply numbers that correspond to her private key that she can use to control access to the funds",
                        "The addresses are generated independently by her wallet without reference or registration with any service",
                        "Unlike a bank account number, nobody who learns one of your Bitcoin addresses can withdraw money from your wallet",
                        "you must initiate all spends", "which is quite long"]),
 ("Invoice", B, ["There are a variety of Bitcoin addresses and invoice formats", "You can share an address or invoice with other people without worrying about the security of your bitcoins"]),
 ("Invoice", "ch02_overview.adoc", ["This allows a Bitcoin wallet application to prefill the information used to send the payment while showing a human-readable description to the user",
                                    "The invoice QR code encodes the following URI, defined in BIP21"]),
 ("AddressReuse", B, ["if you give two people the same address, they will be able to see how many bitcoins the other person sent you",
                      "If you post your address publicly, everyone will be able to see how much bitcoin other people sent to that address",
                      "To protect your privacy, you should generate a new invoice with a new address each time you request a payment",
                      "once a Bitcoin address is attached to an identity, other associated Bitcoin transactions may also become easy to identify and track"]),
 ("AddressReuse", WP, ["As an additional firewall, a new key pair should be used for each transaction to keep them from being linked to a common owner",
                       "Some linking is still unavoidable with multi-input transactions, which necessarily reveal that their inputs were owned by the same owner",
                       "if the owner of a key is revealed, linking could reveal other transactions that belonged to the same owner"]),
 ("Transfer", B, ["he presses Send to transmit the transaction", "As the transaction is transmitted via the peer-to-peer protocol, it quickly propagates across the Bitcoin network"]),
 ("SendingAndReceiving", B, ["has decided to buy 0.001 bitcoins", "she gives Joe an appropriate amount of cash, opens her mobile wallet application, and selects Receive",
                             "This displays a QR code with Alice's first Bitcoin address", "Joe then selects Send on his smartphone wallet and opens the QR code scanner",
                             "The higher the transaction fee, the faster the transaction will be confirmed",
                             "Joe then carefully checks to make sure he has entered the correct amount, because he is about to transmit money and mistakes will soon become irreversible",
                             "Joe's mobile Bitcoin wallet constructs a transaction that assigns 0.001 BTC to the address provided by Alice, sourcing the funds from Joe's wallet, and signing the transaction with Joe's private keys",
                             "Alice's wallet is constantly \"listening\" for new transactions on the Bitcoin network",
                             "Alice's wallet will indicate that it is receiving 0.001 BTC"]),
 ("Transaction", B, ["The coins are implied in transactions that transfer value from spender to receiver"]),
 ("Transaction", G, ["a transaction is a signed data structure expressing a transfer of value",
                     "Transactions are transmitted over the Bitcoin network, collected by miners, and included into blocks, made permanent on the blockchain"]),
 ("Transaction", WP, ["We define an electronic coin as a chain of digital signatures",
                      "Each owner transfers the coin to the next by digitally signing a hash of the previous transaction and the public key of the next owner and adding these to the end of the coin"]),
 ("InputsAndOutputs", WP, ["To allow value to be split and combined, transactions contain multiple inputs and outputs",
                           "Normally there will be either a single input from a larger previous transaction or multiple inputs combining smaller amounts, and at most two outputs: one for the payment, and one returning the change, if any, back to the sender",
                           "If the output value of a transaction is less than its input value, the difference is a transaction fee that is added to the incentive value of the block containing the transaction"]),
 ("InputsAndOutputs", B, ["constructs a transaction that assigns 0.001 BTC to the address provided by Alice, sourcing the funds from Joe's wallet"]),
 ("TransactionFee", B, ["the wallet may ask Joe to either enter a transaction fee rate or prompt him with a suggested fee (or fee rate)",
                        "is rewarded with both brand new bitcoins and the fees paid by recent transactions"]),
 ("TransactionFee", "ch09_fees.adoc", ["miners evaluate transactions the same way you might comparison shop between several equivalent items at the market: they divide the price by the quantity",
                                        "miners divide the fee of a transaction by its size", "Satoshi/Vbyte (most commonly used today)"]),
 ("TransactionFee", WP, ["Once a predetermined number of coins have entered circulation, the incentive can transition entirely to transaction fees and be completely inflation free"]),
 ("Confirmation", B, ["Alice's address will show the transaction from Joe as \"Unconfirmed.\"",
                      "This means that the transaction has been propagated to the network but has not yet been recorded in the Bitcoin transaction journal, known as the blockchain",
                      "To be confirmed, a transaction must be included in a block and added to the blockchain, which happens every 10 minutes, on average",
                      "In traditional financial terms this is known as clearing"]),
 ("Confirmation", G, ["Once a transaction is included in a block, it has one confirmation",
                      "As soon as another block is mined on the same blockchain, the transaction has two confirmations, and so on",
                      "Six or more confirmations is considered sufficient proof that a transaction cannot be reversed"]),
 ("Confirmation", WP, ["z=6 P=0.0002428", "q=0.1"]),
 ("Irreversibility", B, ["Bitcoin transactions are irreversible",
                         "Most electronic payment networks such as credit cards, debit cards, PayPal, and bank account transfers are reversible",
                         "this difference introduces a very high risk that the buyer will reverse the electronic payment after they have received bitcoin, in effect defrauding the seller"]),
 ("Irreversibility", WP, ["Completely non-reversible transactions are not really possible, since financial institutions cannot avoid mediating disputes",
                          "The cost of mediation increases transaction costs",
                          "With the possibility of reversal, the need for trust spreads", "Merchants must be wary of their customers",
                          "Transactions that are computationally impractical to reverse would protect sellers from fraud, and routine escrow mechanisms could easily be implemented to protect buyers"]),
 ("OffchainPayment", B, ["Many Bitcoin payments are now made using offchain technology, where not every payment is stored in the public blockchain",
                         "This reduces user's costs and improves privacy, among other benefits",
                         "it means that a mechanism like recovery codes that depends on onchain data can't guarantee recovery of all of a user's bitcoins",
                         "For applications with offchain support, it's important to make frequent backups of the wallet database"]),
 ("OffchainPayment", G, ["An offchain transaction is the movement of value outside of the blockchain"]),
 ("SemanticBridge", B, ["Users of Bitcoin control keys that allow them to prove ownership of bitcoin in the Bitcoin network"]),
 ("SemanticBridge", "did.txt", ["decentralized digital identity"]),
 ("DecentralizedIdentity", "did.txt", ["A DID refers to any subject (e.g., a person, organization, thing, data model, abstract entity, etc.) as determined by the controller of the DID",
                                       "In contrast to typical, federated identifiers, DIDs have been designed so that they may be decoupled from centralized registries, identity providers, and certificate authorities",
                                       "the design enables the controller of a DID to prove control over it without requiring permission from any other party",
                                       "19 July 2022"]),
 ("VerifiableCredential", "vc.txt", ["how they can be secured from tampering, and a three-party ecosystem for the exchange of these credentials that is composed of issuers , holders , and verifiers",
                                      "digital signatures can make verifiable credentials more tamper-evident and trustworthy than their physical counterparts",
                                      "Holders of verifiable credentials can generate verifiable presentations and then share these verifiable presentations with verifiers to prove they possess verifiable credentials with specific characteristics",
                                      "15 May 2025"]),
 ("Acquisition", B, ["The first task for new users is to acquire some bitcoin", "Here are some methods for acquiring bitcoin as a new user"]),
 ("BuyFromFriend", B, ["Find a friend who has bitcoins and buy some from him or her directly", "Many Bitcoin users start this way",
                       "This method is the least complicated", "One way to meet people with bitcoins is to attend a local Bitcoin meetup listed at",
                       "you cannot buy bitcoin instantly with a credit card"]),
 ("EarnBitcoin", B, ["Earn bitcoin by selling a product or service for bitcoin", "If you are a programmer, sell your programming skills",
                     "If you're a hairdresser, cut hair for bitcoins",
                     "including buying and selling goods, sending money to people or organizations, or extending credit"]),
 ("BitcoinATM", B, ["Use a Bitcoin ATM in your city", "A Bitcoin ATM is a machine that accepts cash and sends bitcoins to your smartphone Bitcoin wallet",
                    "Alice buys more bitcoin using an ATM and an exchange"]),
 ("CurrencyExchange", B, ["Use a Bitcoin currency exchange linked to your bank account",
                          "Many countries now have currency exchanges that offer a market for buyers and sellers to swap bitcoins with local currency",
                          "Exchange-rate listing services, such as", "often show a list of Bitcoin exchanges for each currency",
                          "where bitcoin touches traditional systems, such as currency exchanges, national and international regulations often apply",
                          "many users choose to maintain dedicated exchange accounts independent from their wallets"]),
 ("IdentityVerification", B, ["companies accepting traditional electronic payments in return for bitcoin usually require buyers to undergo identity verification and credit-worthiness checks, which may take several days or weeks",
                              "With a bit of patience and creative thinking, however, you won't need to",
                              "In order to exchange bitcoin for your national currency, you will often be required to provide proof of identity and banking information",
                              "Acquiring, holding, and spending bitcoin does not require you to divulge sensitive and personally identifiable information to third parties"]),

 ("BitcoinImprovementProposal", "appc_bips.adoc", ["Bitcoin Improvement Proposals are design documents providing information to the Bitcoin community or describing a new feature for Bitcoin or its processes or environment",
                                                   "Hierarchical Deterministic Wallets has been implemented since v0.13.0",
                                                   "173: Bech32 addresses for native Segregated Witness outputs are supported as of v0.16.0"]),

 # ---------------------------------------------------------------- FOUNDATIONS: cryptography
 ("Foundations", B, ["Bitcoin builds on decades of research in cryptography and distributed systems and includes at least four key innovations brought together in a unique and powerful combination"]),
 ("Cryptography", SH, ["The mathematical science that deals with transforming data to render its meaning unintelligible",
                       "prevent its undetected alteration, or prevent its unauthorized use"]),
 ("Cryptography", "mdn_Cryptography.txt", ["is the science that studies how to encode and transmit messages securely",
                                           "More than just data confidentiality , cryptography also tackles identifi"]),
 ("Cryptography", B, ["cryptography provides the basis for trusting the legitimacy of a user's claim to value",
                      "cryptographic digital signatures enable a user to sign a digital asset or transaction proving the ownership of that asset",
                      "digital signatures also can be used to address the double-spend issue"]),
 ("HashFunction", SH, ["A function H that maps an arbitrary, variable-length bit string, s, into a fixed-length string",
                       "For most computing applications, it is desirable that given a string s with H(s) = h, any change to s that creates"]),
 ("HashFunction", G, ["A digital commitment to some binary input"]),
 ("HashFunction", "rfc6234.txt", ["it is computationally infeasible to (1) find a message that corresponds to a given message digest, or (2) find two different messages that produce the same message digest",
                                   "BA7816BF8F01CFEA4141"]),
 ("DigitalSignature", SH, ["A value computed with a cryptographic algorithm and associated with a data object in such a way that any recipient of the data can use the signature to verify the data's origin and integrity"]),
 ("DigitalSignature", WP, ["We define an electronic coin as a chain of digital signatures"]),
 ("PublicKeyCryptography", SH, ["A set of mathematically related keys -- a public key and a private key -- that are used for asymmetric cryptography and are generated in a way that makes it computationally infeasible to derive the private key from knowledge of the public key"]),
 ("PrivateKey", SH, ["The secret component of a pair of cryptographic keys used for asymmetric cryptography"]),
 ("PrivateKey", B, ["access to bitcoins is controlled by \"private keys,\" which are like very long PINs",
                    "Possession of the key that can sign a transaction is the only prerequisite to spending bitcoin",
                    "Your keys, your coins. Not your keys, not your coins"]),
 ("PrivateKey", "ch04_keys.adoc", ["256 bits shown as 64 hexadecimal digits, each 4 bits", "to produce 256 bits of entropy"]),
 ("Entropy", SH, ["An information-theoretic measure (usually stated as a number of bits) of the amount of uncertainty that an attacker faces to determine the value of a secret"]),
 ("Entropy", "bip39.txt", ["We refer to the initial entropy length as ENT", "The allowed size of ENT is 128-256 bits"]),
 ("Checksum", SH, ["A value that (a) is computed by a function that is dependent on the contents of a data object and (b) is stored or transmitted together with the object, for detecting changes in the data"]),
 ("Checksum", "bip39.txt", ["A checksum is generated by taking the first", "bits of its SHA256 hash. This checksum is appended to the end of the initial entropy"]),
 ("KeyedHash", "rfc6234.txt", ["a keyed-hash message authentication algorithm", "HMAC-SHAs, and HKDF"]),
 ("KeyedHash", "bip39.txt", ["The iteration count is set to 2048 and HMAC-SHA512 is used as the pseudo-random function"]),
 ("KeyStretching", "rfc8018.txt", ["include an iteration count in the key derivation technique, indicating how many times to iterate some underlying function by which keys are derived",
                                    "A modest number of iterations (say, 1000) is not likely to be a burden for legitimate parties when computing a key, but will be a significant burden for opponents"]),
 ("KeyStretching", "bip39.txt", ["The iteration count is set to 2048 and HMAC-SHA512 is used as the pseudo-random function",
                                  "The length of the derived key is 512 bits (= 64 bytes)", "the string \"mnemonic\" + passphrase"]),

 # ---------------------------------------------------------------- FOUNDATIONS: the chain
 ("Chain", B, ["To be confirmed, a transaction must be included in a block and added to the blockchain, which happens every 10 minutes, on average"]),
 ("Block", G, ["A grouping of transactions, marked with a timestamp, and a commitment to the previous block",
               "block header is hashed to produce a proof of work, thereby validating the transactions",
               "Valid blocks are added to the main blockchain by network consensus"]),
 ("Block", "block840000.json", ["\"tx_count\":3050"]),
 ("Block", "block0.json", ["\"tx_count\":1"]),
 ("Blockchain", G, ["genesis block"]),
 ("Blockchain", B, ["has not yet been recorded in the Bitcoin transaction journal, known as the blockchain"]),
 ("Blockchain", WP, ["the honest chain will grow the fastest and outpace any competing chains",
                     "To modify a past block, an attacker would have to redo the proof-of-work of the block and all blocks after it"]),
 ("Timestamp", SH, ["a label or marking in which is recorded the time (time of day or other instant of elapsed time) at which the label or marking was affixed to the data object"]),
 ("Timestamp", WP, ["A timestamp server works by taking a hash of a block of items to be timestamped and widely publishing the hash",
                    "The timestamp proves that the data must have existed at the time", "Each timestamp includes the previous timestamp in its hash, forming a chain"]),
 ("Timestamp", "block0.json", ["\"timestamp\":1231006505"]),
 ("Node", "ch10_network.adoc", ["The term \"Bitcoin network\" refers to the collection of nodes running the Bitcoin P2P protocol",
                                 "there are other protocols that are used for mining and lightweight wallets"]),
 ("Node", B, ["most of the well-connected nodes in the network receive the transaction and see Alice's address for the first time"]),

 # ---------------------------------------------------------------- FOUNDATIONS: computing
 ("Computing", B, ["Bitcoin users communicate with each other using the Bitcoin protocol primarily via the internet, although other transport networks can also be used"]),
 ("Internet", "mdn_Internet.txt", ["The Internet is a worldwide network of networks that uses the Internet protocol suite"]),
 ("Internet", SH, ["The Internet is the single, interconnected, worldwide system of commercial, governmental, educational, and other computer networks that share"]),
 ("Internet", B, ["Bitcoin users communicate with each other using the Bitcoin protocol primarily via the internet"]),
 ("Protocol", "mdn_Protocol.txt", ["the devices agree on the format of the data that is being exchanged", "The set of rules that defines a format is called a protocol"]),
 ("Protocol", SH, ["A set of rules (i.e., formats and procedures) to implement and control some type of association (e.g., communication) between systems"]),
 ("Protocol", B, ["The Bitcoin protocol stack, available as open source software, can be run on a wide range of computing devices",
                  "There are many implementations and brands of Bitcoin wallets, just like there are many brands of web browsers"]),
 ("Http", "mdn_HTTP.txt", ["is the underlying network protocol that enables transfer of hypermedia documents on the Web , typically between a browser and a server so that humans can read them"]),
 ("Http", "rfc9112.txt", ["A request-line begins with a method token, followed by a single space (SP), the request-target, and another single space (SP), and ends with the protocol version"]),
 ("Http", B, ["A \"Bitcoin wallet\" is the most common user interface to the Bitcoin system, just like a web browser is the most common user interface for the HTTP protocol"]),
 ("WebBrowser", "mdn_Browser.txt", ["is a program that retrieves and displays pages from the web , and lets users access additional pages through hyperlinks",
                               "A browser is the most familiar type of user agent", "It uses a rendering engine to display web pages"]),
 ("WebBrowser", B, ["just like there are many brands of web browsers (e.g., Chrome, Safari, and Firefox)",
                    "Web wallets are accessed through a web browser and store the user's wallet on a server owned by a third party",
                    "Some of these services operate using client-side code running in the user's browser, which keeps control of the Bitcoin keys in the hands of the user"]),
 ("Server", "mdn_Server.txt", ["A server is a software or hardware offering a service to a user, usually referred to as client",
                               "A client program and server program traditionally connect by passing messages encoded using a protocol over an API"]),
 ("Server", SH, ["A system entity that requests and uses a service provided by another system entity, called a \"server\""]),
 ("Server", B, ["there is no central server or point of control", "most mobile wallets retrieve information from remote servers, reducing your privacy by disclosing to third parties information about your Bitcoin addresses and balances",
                "the client trusts the remote server to provide it with accurate information and protect its privacy"]),
 ("Api", "mdn_API.txt", ["API can be seen as a simple contract (the interface) between the application offering it and other items, such as third-party software or hardware"]),
 ("Api", B, ["A third-party API client is one that interacts with Bitcoin through a third-party system of APIs rather than by connecting to the Bitcoin network directly"]),
 ("Uri", "mdn_URI.txt", ["URNs , by contrast, refer to a resource by a name, in a given namespace, such as the ISBN of a book"]),
 ("Uri", "rfc3986.txt", ["provides a simple and extensible means for identifying a resource", "URI = scheme \":\" hier-part [ \"?\" query ] [ \"#\" fragment ]"]),
 ("Uri", "bip21.txt", ["bitcoin:175tWpb8K1S7NmH4Zx6rewF9WQrcZv245W?amount=20.3&label=Luke-Jr", "This BIP has been superseded and replaced with BIP 321"]),
 ("Uri", G, ["BIP21 is a proposal to improve the bitcoin uniform resource identifier (URI) scheme"]),
 ("QrCode", "wp_QRcode.txt", ["is a type of two-dimensional matrix barcode invented in 1994", "Version 1 (21", "Version 40 (177"]),
 ("QrCode", B, ["The QR code is the square with a pattern of black and white dots, serving as a form of barcode that contains the same information in a format that can be scanned by Joe's smartphone camera",
                "he doesn't have to type in Alice's Bitcoin address", "Any funds sent to the addresses in this book will be lost"]),
 ("Database", "mdn_Database.txt", ["A database is a storage system that collects organized data, making it easier to search, structure, and extend"]),
 ("Database", B, ["rebuild the wallet database of all the onchain transactions she's ever sent or received",
                  "it's important to make frequent backups of the wallet database"]),
 ("Database", G, ["they also devised the first blockchain database"]),
 ("OperatingSystem", "wp_Operating_system.txt", ["is system software that manages computer hardware and software resources, and provides common services for computer programs"]),
 ("OperatingSystem", B, ["Running on general-use operating systems such as Windows and macOS has certain security disadvantages, however, as these platforms are often insecure and poorly configured",
                         "Running on smart-phone operating systems such as Apple iOS and Android"]),
 ("DistributedSystem", "wp_Distributed.txt", ["computer systems whose inter-communicating components are located on different networked computers"]),
 ("DistributedSystem", B, ["Bitcoin is a distributed, peer-to-peer system",
                           "Bitcoin is also the name of the protocol, a peer-to-peer network, and a distributed computing innovation",
                           "represents a breakthrough in distributed computing"]),
 ("DistributedSystem", "ch10_network.adoc", ["the largest and most successful application of P2P technologies is file sharing"]),
 ("BitsAndBytes", SH, ["A contraction of the term \"binary digit\"; the smallest unit of information storage, which has two possible states or values",
                       "A data unit of eight bits"]),
 ("BitsAndBytes", "ch04_keys.adoc", ["256 bits shown as 64 hexadecimal digits, each 4 bits"]),
 ("BitsAndBytes", "rfc4648.txt", ["Base 16 Encoding"]),

 # ---------------------------------------------------------------- FOUNDATIONS: threats
 ("Threats", B, ["there are also many malware applications that mimic the design of a wallet, insist you enter your recovery code, and then relay any entered code to the malware developer so they can steal your funds"]),
 ("Malware", "wp_Malware.txt", ["is any software intentionally designed to cause disruption or destruction to a computer, server, client, or computer network, leak private information, gain unauthorized access to information or systems"]),
 ("Malware", SH, ["A contraction of \"malicious software\""]),
 ("Malware", B, ["these platforms are often insecure and poorly configured",
                 "By handling all Bitcoin-related operations on the specialized hardware, these wallets are less vulnerable to many types of attacks"]),
 ("Phishing", "wp_Phishing.txt", ["social engineering and a scam in which attackers deceive people into revealing sensitive information or installing malware"]),
 ("Phishing", SH, ["A technique for attempting to acquire sensitive data, such as bank account numbers, through a fraudulent solicitation in email or on a Web site, in which the perpetrator masquerad"]),
 ("Phishing", B, ["This is the equivalent of phishing websites that try to trick you into giving them your bank passphrase",
                  "the only times they will ask for your recovery code are during the initial set up (before you have received any bitcoins) and during recovery (after you lost access to your original wallet)",
                  "consult with an expert to ensure you aren't being phished"]),

 # ---------------------------------------------------------------- NATURE
 ("Nature", B, ["Bitcoin is arguably the perfect form of money for the internet because it is fast, secure, and borderless",
                "A decentralized peer-to-peer network (the Bitcoin protocol)", "A public transaction journal (the blockchain)",
                "A set of rules for independent transaction validation and currency issuance (consensus rules)",
                "A mechanism for reaching global decentralized consensus on the valid blockchain (proof-of-work algorithm)"]),
 ("Characteristic", B, ["the bitcoin currency is entirely virtual",
                        "a decentralized digital currency was needed to avoid a single point of attack"]),
 ("Virtual", B, ["Unlike traditional currencies, the bitcoin currency is entirely virtual",
                 "There are no physical coins or even individual digital coins",
                 "The coins are implied in transactions that transfer value from spender to receiver",
                 "Users of Bitcoin control keys that allow them to prove ownership of bitcoin in the Bitcoin network",
                 "they can sign transactions to unlock the value and spend it by transferring it to a new owner"]),
 ("Borderless", B, ["Bitcoin is arguably the perfect form of money for the internet because it is fast, secure, and borderless",
                    "Bitcoin can be purchased, sold, and exchanged for other currencies at specialized currency exchanges",
                    "including laptops and smartphones, making the technology easily accessible",
                    "national and international regulations often apply"]),
 ("Decentralized", B, ["Bitcoin is such a system, decentralized by design, and free of any central authority or point of control that can be attacked or corrupted",
                       "they were centralized and, as a result, were easy to attack by governments and hackers",
                       "Early digital currencies used a central clearinghouse to settle all transactions at regular intervals, just like a traditional banking system",
                       "Some failed in spectacular crashes when the parent company liquidated abruptly",
                       "neither Satoshi Nakamoto nor anyone else exerts individual control over the Bitcoin system, which operates based on fully transparent mathematical principles, open source code, and consensus among participants"]),
 ("Robust", B, ["To be robust against intervention by antagonists, whether legitimate governments or criminal elements, a decentralized digital currency was needed to avoid a single point of attack",
                "eventually litigated out of existence",
                "their combined computational power now exceeds the combined number of computing operations of the world's top supercomputers"]),
 ("Robust", WP, ["If a majority of CPU power is controlled by honest nodes, the honest chain will grow the fastest and outpace any competing chains"]),
 ("Architecture", B, ["Bitcoin consists of:", "A decentralized peer-to-peer network (the Bitcoin protocol)"]),
 ("PeerToPeerProtocol", B, ["A decentralized peer-to-peer network (the Bitcoin protocol)", "Full nodes are the peers:"]),
 ("PeerToPeerProtocol", "ch10_network.adoc", ["means that the full nodes that participate in the network are peers to each other, that they can all perform the same functions, and that there are no \"special\" nodes",
                                                "P2P networks are inherently resilient, decentralized, and open",
                                                "Nodes in a P2P network both provide and consume services at the same time"]),
 ("PublicJournal", B, ["A public transaction journal (the blockchain)",
                       "has not yet been recorded in the Bitcoin transaction journal, known as the blockchain"]),
 ("PublicJournal", WP, ["The only way to confirm the absence of a transaction is to be aware of all transactions",
                        "transactions must be publicly announced"]),
 ("ConsensusRuleSet", B, ["A set of rules for independent transaction validation and currency issuance (consensus rules)",
                          "nobody can force you to accept any bitcoins that were created beyond the expected issuance rate"]),
 ("ConsensusRuleSet", "core_validation.cpp", ["CAmount blockReward = nFees + GetBlockSubsidy(pindex->nHeight, params.GetConsensus());",
                                               "coinbase pays too much"]),
 ("PaymentChannel", G, ["A micropayment channel or payment channel is class of techniques designed to allow users to make multiple Bitcoin transactions without committing all of the transactions to the bitcoin blockchain",
                         "In a typical payment channel, only two transactions are added to the blockchain"]),
 ("PaymentChannel", B, ["This reduces user's costs and improves privacy, among other benefits"]),
 ("LightningNetwork", G, ["Lightning Network is a proposed implementation of Hashed Timelock Contracts (HTLCs) with bi-directional payment channels which allows payments to be securely routed across multiple peer-to-peer payment channels",
                           "any peer on the network can pay any other peer even if they don't directly have a channel open between each other"]),
 ("LightningNetwork", "lightning.txt", ["The Bitcoin Lightning Network: Scalable Off-Chain Instant Payments", "Joseph Poon", "Thaddeus Dryja"]),
 ("ElectronicPayment", B, ["Most electronic payment networks such as credit cards, debit cards, PayPal, and bank account transfers are reversible",
                           "For someone selling bitcoin, this difference introduces a very high risk that the buyer will reverse the electronic payment after they have received bitcoin"]),
 ("ElectronicPayment", WP, ["With the possibility of reversal, the need for trust spreads", "Merchants must be wary of their customers"]),
 ("Privacy", B, ["when used correctly, it affords users much more privacy",
                 "Acquiring, holding, and spending bitcoin does not require you to divulge sensitive and personally identifiable information to third parties",
                 "once a Bitcoin address is attached to an identity, other associated Bitcoin transactions may also become easy to identify and track"]),
 ("Privacy", WP, ["The traditional banking model achieves a level of privacy by limiting access to information to the parties involved and the trusted third party",
                  "privacy can still be maintained by breaking the flow of information in another place: by keeping public keys anonymous",
                  "The public can see that someone is sending an amount to someone else, but without information linking the transaction to anyone"]),
 ("Privacy", "wp_Pseudonym.txt", ["Fictitious name used for a particular purpose"]),
 ("Privacy", SH, ["The condition of an identity being unknown or concealed"]),
 ("W3cStandard", "w3c_about.txt", ["is an international public-interest non-profit organization where Member organizations, a full-time staff, and the public work together to develop web standards",
                                    "Founded by Web inventor Tim Berners-Lee", "the Web Consortium's mission is to make the web work - for everyone",
                                    "Web inventor Tim Berners-Lee founded the World Wide Web Consortium in 1994 to ensure the long-term growth of the web"]),
 ("W3cStandard", "did.txt", ["19 July 2022", "This version: https://www.w3.org/TR/2022/REC-did-core-20220719/", "Latest published version: https://www.w3.org/TR/did-core/"]),
 ("W3cStandard", "vc.txt", ["15 May 2025", "This version: https://www.w3.org/TR/2025/REC-vc-data-model-2.0-20250515/"]),
]
