"""SEN0401 chapter 7, corpus text part E (version 1.0.0): the branch 'Data output and timelocks' - the OP_RETURN data output and the
relay policy that limits it, the lock time of a transaction and its limits, OP_CHECKLOCKTIMEVERIFY, the sequence field as a relative
lock and OP_CHECKSEQUENCEVERIFY. Markers such as [AH] become author-year strings (sen0401_ch07_common). Every number is computed by
the chapter's library or read from the saved blocks in CHECKS_E."""
from sen0401_ch07_common_v1_0_0 import *

BK = "ch07_authorization-authentication.adoc"
NULLDATA = "[(v, len(s)) for r in C.block_records() for v, s in L.parse_tx(r['hex']).vout if L.classify(s)[0] == 'nulldata']"
TLK = "<pk> CHECKSIGVERIFY <n> CHECKLOCKTIMEVERIFY"
def _sc(op, n):          # the book's script  <Bob's pubkey> OP_CHECKSIGVERIFY <n> OP_CHECKLOCKTIMEVERIFY  (op 0xb1) or the same with OP_CHECKSEQUENCEVERIFY (op 0xb2), built by the library
    return "(L.push_data(C.pub(1)) + b'\\xad' + L.push_int(%d) + bytes([%d]))" % (n, op)

NODES_E = [
 ("DataAndTime", "Data output and timelocks", 1, None, None, P(
  (W, "This branch collects two kinds of condition that have nothing to do with keys. The first is an output that carries data and cannot be spent, the OP_RETURN output; the second is a set of conditions about time, which restrict when a transaction may be included in a block or when an output may be spent. The book treats them one after the other: the data recording output, the limits of a transaction lock time, the absolute timelock opcode OP_CHECKLOCKTIMEVERIFY, and the relative timelocks, the sequence field and OP_CHECKSEQUENCEVERIFY [AH]."),
  (Y, "Time is the one input to a script that every node can agree on, and the branch explains how it is brought in. A script is stateless, so it can not look at a clock; the transaction carries the numbers, a lock time and a sequence, and the opcodes compare them with the numbers in the script. Timelocks are the basis of savings plans, of inheritance and escrow arrangements with a deadline, and of payment channels, and the data output is the standard way to record a fingerprint of a document in the chain without creating an output that every node must remember [B65] [B112]."),
  (E, "In the 599 transactions saved from block 775,072 the data output and the lock time are both present: 8 outputs carry data, and 131 transactions set a lock time, of which 108 use the height of the preceding block; but none of the 91 witness scripts that were revealed uses a timelock opcode [MP]. The same block shows how far reality is from the examples of the book: wallets use the lock time field of the transaction as a protective measure, and timelocks as a feature of a script are rare."),
  (H, "The branch has three groups. The data output group shows what a provably unspendable output is and how Bitcoin Core's relay policy limits it. The absolute timelock group explains why a lock time alone does not bind the signer and how the opcode adds the missing guarantee. The relative timelock group explains the encoding of the sequence field and the opcode that reads it. The examples run on real signatures and on real transactions, and the activation dates come from the blocks at the heights in Bitcoin Core's chain parameters."),
 ), None),

 ("DataOutput", "Recording data without bloat", 2, "DataAndTime", None, P(
  (W, "This group is about outputs that exist only to carry data. The book describes the controversy: using the blockchain for data that is not payment, such as a commitment to a file as proof that it existed on a date, is considered abusive by some and a demonstration of the technology by others [AH]."),
  (Y, "The two sections show a compromise between those views and its present setting. The OP_RETURN output costs the network disk space in the chain but not the more expensive memory and database space of the set of unspent outputs, and the relay policy of Bitcoin Core decides how many bytes of such data a transaction may carry. The group is a case of the difference between what the consensus rules allow and what nodes agree to relay."),
  (H, "The first section describes the output and what happens if an input tries to spend it, with the proof-of-existence prefix of the book and the real outputs of block 775,072. The second section reads the policy of Bitcoin Core at the pinned commit: a default that accepts data carriers, a size in vbytes derived from the standard weight, and the budget that is shared by all data outputs of a transaction."),
  (K, "The default of the policy is not a rule of the protocol. A miner may include any transaction that follows the consensus rules, including one that carries more data than the relay policy of its neighbours accept, and a user can change the default with a start-up option. The group therefore keeps the two apart each time a number appears."),
 ), None),

 ("OpReturnOutput", "OP_RETURN output", 3, "DataOutput", ("OP_RETURN <data>", "An OP_RETURN output is an output whose script begins with OP_RETURN followed by data; it can never be spent, so nodes need not keep it in the set of unspent outputs.",
   (PROG(MINI + "import hashlib\ndata = b'DOCPROOF' + hashlib.sha256(b'hello').digest()       # the prefix of a notary service and the SHA-256 of a document\nspk = bytes([0x6a, len(data)]) + data\nresult = (len(spk), spk[:10].hex(), run('RETURN'))"), "(42, '6a28444f4350524f4f46', 'FAIL: RETURN')")), P(
  (W, "An OP_RETURN output is an output script of the form OP_RETURN followed by data. The book explains it as a compromise: it allows an output script that starts with OP_RETURN to add data that is not a payment to a transaction output, and unlike the use of fake outputs, which hide data in the 20 bytes of an address and can never be spent but stay in the database for ever, the output is explicitly provably unspendable and need not be stored in the set of unspent outputs [AH]."),
  (Y, "The output matters because it separates the cost of data from the cost of payments. A fake output built from an address that corresponds to no private key bloats the database of every full node, which must remember it in case it is spent. An OP_RETURN output is recorded in the blockchain, so it uses disk space, but it is not stored in the set of unspent outputs and does not make the database operations more expensive. Bitcoin Core's function IsUnspendable says that a script is unspendable if it starts with OP_RETURN or is longer than the script size limit, so that the output can be pruned at once when it enters the set [BCS]."),
  (E, "The data is often a hash such as the 32 bytes of SHA-256, sometimes with a prefix that identifies the application. The book gives the example of a notarization service that uses the 8-byte prefix DOCPROOF, written 44 4f 43 50 52 4f 4f 46 in hexadecimal; the example builds such an output script for the hash of a document and finds it 42 bytes long. Block 775,072 holds 8 data outputs among the 1,668 outputs of its first 599 transactions: 5 of 83 bytes whose first bytes push 80 bytes of data, and three shorter ones of 3, 55 and 54 bytes. Five of them carry a value of 5,500 or 6,213 satoshis [MP]."),
  (H, "The engine stops at once when it reaches the opcode. In Bitcoin Core's interpreter the case for OP_RETURN returns the error SCRIPT_ERR_OP_RETURN, so a script that executes it fails; the book puts it in words: if an OP_RETURN output is referenced as an input, the validation engine halts and marks the transaction invalid, and there is no input script that could spend it. The page's stack machine shows the same: a script that reaches RETURN fails whatever else is on the stack [BCI] [AH]."),
  (K, "The book says that OP_RETURN outputs usually have a zero amount, because any bitcoins assigned to such an output are lost for ever. The saved block shows that this is a habit and not a rule: five of its eight data outputs hold a few thousand satoshis, which are burned. The opcode also had a history as a bug: in the first versions of the software the opcode ended the evaluation of a script with success, a story the page tells in the branch on the language of Script."),
 ), None),

 ("DataCarrierPolicy", "Data carrier policy", 3, "DataOutput", ("budget 100,000 bytes for all data outputs of one transaction", "The data carrier policy is the relay rule that decides how many bytes of OP_RETURN data a transaction may carry; in Bitcoin Core it accepts data carriers by default and shares one budget of 100,000 vbytes among all the data outputs of a transaction.",
   (PROG("budget = 400000 // 4                  # MAX_STANDARD_TX_WEIGHT divided by the witness scale factor\nresult = []\nfor size in (60000, 50000):                 # two data outputs of a transaction, their script sizes in bytes\n    if size > budget: result.append('datacarrier'); break\n    budget -= size; result.append('standard')"), "['standard', 'datacarrier']")), P(
  (W, "The data carrier policy is the part of Bitcoin Core's relay rules that concerns outputs with data. The source declares a default that accepts data carriers, DEFAULT_ACCEPT_DATACARRIER, and a default size setting in vbytes, MAX_OP_RETURN_RELAY, which is the standard transaction weight of 400,000 divided by the witness scale factor of 4, that is 100,000. In the function that decides whether a transaction is standard, every output that is a data carrier takes its whole script size from a budget, and a transaction that exceeds the budget is refused with the reason datacarrier [BCQ] [BCP]."),
  (Y, "The policy is the answer to the controversy that the book describes. Those who want to discourage the use of the chain for data can limit what their node relays, and those who want to encourage it can raise the limit; the setting is a policy, which each node operator controls, and not a consensus rule. The book does not quote a number; this page reads the value in the source at the commit pinned for the course, and a later release may set another."),
  (E, "The budget is shared. Because the loop subtracts the size of each data output from one variable, two outputs of 60,000 and 50,000 bytes cannot both be relayed even though each is below the limit; the example runs this rule on the two sizes and the second one is refused. The eight data outputs of block 775,072 hold 527 bytes of script between them, which is far below the budget [BCP] [MP]."),
  (H, "A relay node checks the transaction in the function IsStandardTx. For each output it first asks whether the script is standard at all; for a data carrier it takes the script size from the remaining budget and rejects the transaction if the size is larger than what is left; for a bare multisignature output it rejects the transaction unless the node permits bare multisignature. The same loop is why a transaction with several data outputs is judged by their total [BCP]."),
  (K, "The word vbytes means virtual bytes, a measure of the weight of a transaction divided by four, which is the unit in which fees are priced; for a script outside the witness the vbytes are equal to the bytes. A policy limit is also not a promise that a transaction below it is relayed, since other rules, such as the fee rate, apply too. Because miners are not bound by the policy, a transaction that no node relays can still be mined when someone sends it to a miner directly."),
 ), None),

 ("AbsoluteTimelocks", "Absolute timelocks", 2, "DataAndTime", None, P(
  (W, "This group is about conditions that name a point in time or a block height. A transaction has a lock time, which restricts the blocks it can be included in, and a script can use the opcode OP_CHECKLOCKTIMEVERIFY to restrict an output so that it is spent only by a transaction whose lock time has passed a given value [AH]."),
  (Y, "The two mechanisms are different in who they bind. The lock time of a transaction binds nobody: whoever signed it can also sign a different transaction that spends the same inputs without a lock time. The opcode puts the restriction on the output itself, so that no transaction, signed by anyone, can spend the output before the time. The book builds this contrast in two sections, and so does the group."),
  (H, "The first section states the limitation of the lock time with the example of Alice and Bob and reads the rule of Bitcoin Core that decides whether a transaction with a given lock time can be in a block. The second section explains the opcode, runs it on real signatures, and notes how the activation dates of the soft forks are known from the blocks. The example numbers of the book are recomputed along the way."),
  (K, "Absolute means counted from a fixed point, the beginning of the chain or of the year 1970, not from the moment an output was created. A value below 500,000,000 is a block height and a value at or above it is a time in seconds since 1 January 1970, and the two kinds cannot be compared with each other."),
 ), None),

 ("LockTimeLimits", "Lock time limits", 3, "AbsoluteTimelocks", ("lock time stops a transaction, not a spender", "The lock time of a transaction restricts only when that transaction can be included in a block; it does not stop the signer from spending the same inputs in another transaction without a lock time.",
   (PROG("def final(lock_time, height):          # may the transaction be in a block of this height? (all inputs not final, height-type lock time)\n    return lock_time == 0 or lock_time < height\nresult = (final(775071, 775072), final(775071, 775071))"), "(True, False)")), P(
  (W, "The lock time is the last field of a transaction, and the book explains its rules: a lock time of 0 means the transaction can be included in any block; a value below 500,000,000 restricts it to a block height, and a value of 500,000,000 or more is a time in seconds since the beginning of 1970 that the median time past of the block must exceed; this was added by Bitcoin's earliest known soft fork, starting at block height 31,000 [AH6]. The limitation that the chapter explains is the one of a promise: the only guarantee a lock time gives is that the receiver cannot redeem the signed transaction before the time [AH]."),
  (Y, "The limitation is why the opcode exists. In the book's example Alice signs a transaction paying Bob with a lock time three months ahead and gives it to Bob to hold. Bob cannot send it for three months and may send it afterwards; but Alice can create a conflicting transaction that spends the same inputs without a lock time and spend the output earlier, and Bob has no guarantee that she will not. The only way to guarantee that Bob receives the funds, but cannot spend them for three months, is to put the restriction on the output as part of the script [AH]."),
  (E, "In practice wallets use the lock time for a different purpose. The saved block of 775,072 contains 131 transactions with a nonzero lock time among its first 599, and all 131 are heights below 500,000,000; 108 of them are 775,071, the height of the block before. The book's chapter on fees explains the reason: several wallets create transactions with a lock time that limits them to the next block or any later block, which discourages miners from rewriting history to take higher-fee transactions [AH9] [MP]."),
  (H, "The rule is in Bitcoin Core's function IsFinalTx. A transaction is final if its lock time is 0 or if the lock time is less than the height of the block (for a height) or the median time past of the block's predecessor (for a time); and even if not, it is final if every input has the sequence number 0xffffffff, which switches the lock time off. The example applies the first two conditions: a transaction with lock time 775,071 is final in block 775,072 and not final in block 775,071 [BCT]."),
  (K, "The book states the rule as an equal-or-higher comparison, for example that a lock time of 123,456 can be included in block 123,456 or any later block; the source says less than, so that the block 123,456 is excluded and the first block that can include it is 123,457. A comment in the same file calls the lock time the last invalid height or time. The difference is one block, and the saved block agrees with the source: its transactions with lock time 775,071 sit in block 775,072. The sequence number 0xffffffff also matters: it disables the lock time, which is why the opcode in the next section checks it."),
 ), None),

 ("CheckLockTimeVerify", "OP_CHECKLOCKTIMEVERIFY", 3, "AbsoluteTimelocks", ("<pk> OP_CHECKSIGVERIFY <n> OP_CHECKLOCKTIMEVERIFY", "OP_CHECKLOCKTIMEVERIFY fails a script unless the lock time of the spending transaction is of the same kind as, and at least as large as, the number on top of the stack, and the input is not final.",
   (PROG("def cltv(n, lock, seq):                # the failure conditions of BIP65 that do not depend on the stack\n    if n < 0: return 'fail'\n    if (n < 500000000) != (lock < 500000000): return 'fail'\n    if n > lock: return 'fail'\n    if seq == 0xffffffff: return 'fail'\n    return 'ok'\nresult = (cltv(500000, 500000, 0), cltv(500000, 499999, 0), cltv(500000, 500000, 0xffffffff), cltv(500000, 1700000000, 0))"), "('ok', 'fail', 'fail', 'fail')")), P(
  (W, "OP_CHECKLOCKTIMEVERIFY, written CLTV in short, is an opcode that makes an output spendable only after a given block height or time. The book says it was introduced in December 2015 as a soft fork on the specification BIP65, that it is a per-output timelock where the lock time is per transaction, and that the output is restricted so it can be spent only in a transaction whose lock time is greater than or equal to the value in the script [AH] [B65]."),
  (Y, "The opcode closes the gap that the previous section described. With it, Alice sends her transaction at once, assigning the funds to Bob's key; she can no longer spend the money, and Bob cannot spend it before the three months have passed. BIP65 gives further uses: an escrow in which a lawyer can sign with one of two parties only after three months, refunds for payment channels that do not depend on the cooperation of the other party, and two-factor wallets in which the user can spend alone after an expiry time [B65]."),
  (E, "Bitcoin Core enforces the opcode from block 388,381, which was mined on 14 December 2015 and which has the hash that a comment in the chain parameters records; it is the first block at which the rule applied [BCL] [MA]. The example script is the book's form, the signature check followed by the time and the opcode, wrapped in a script hash. The library signs it with a real key and runs it: a transaction with lock time 500,000 and a sequence that is not final succeeds, one with lock time 499,999 fails, and one whose sequence is final fails with UNSATISFIED_LOCKTIME."),
  (H, "The engine takes the number from the top of the stack, which may have up to five bytes, because four would end the usable range in the year 2038, and fails with a negative-lock-time error if the number is below zero. It then compares: the kinds must match, both a height or both a time; the number in the script must not exceed the lock time of the transaction; and the input's sequence must not be 0xffffffff. BIP65 lists exactly these conditions, plus the empty stack. If they hold, the opcode does nothing and the number stays on the stack, which is why scripts often have OP_DROP after it, as the book explains [BCI] [B65] [AH]."),
  (K, "The opcode redefined the existing no-operation opcode NOP2, and that is the source of its odd behaviour: old software treated the opcode as doing nothing, so the new behaviour had to be a restriction that old nodes do not enforce, a soft fork. The library shows what an old node would do: with the flag switched off it accepts a spend with lock time 0. The book gives the amount for three months as 12,960 blocks or 7,760,000 seconds; 12,960 blocks of ten minutes are exactly 90 days, but 90 days are 7,776,000 seconds, so the second figure is about 16,000 seconds short. And two calls of the opcode, one with a height and one with a time, can never both succeed in one script."),
 ), None),

 ("RelativeTimelocks", "Relative timelocks", 2, "DataAndTime", None, P(
  (W, "This group is about conditions that count time from the moment an output was confirmed. The book says that lock time and OP_CHECKLOCKTIMEVERIFY are absolute timelocks, and the next two features are relative timelocks, which specify as a condition of spending an elapsed time since the confirmation of the output in the blockchain. The transaction-level form uses the sequence field of each input, and the script-level form is the opcode OP_CHECKSEQUENCEVERIFY [AH]."),
  (Y, "A relative timelock allows a time constraint on one transaction that depends on the age of a previous transaction: the clock does not start until the output is recorded in the blockchain. This is what makes it possible to sign and keep a chain of transactions off the chain, since a child cannot be used until the parent has been mined and has aged, and it is the basis of the bidirectional payment channels and the Lightning Network that the book describes in a later chapter [AH] [B68]."),
  (H, "The first section decodes the sequence field according to BIP68, with its flag bits and its unit of 512 seconds; the second explains the opcode of BIP112 that compares a number in the script with the sequence of the spending input, and runs it with real signatures. The activation of both is read from the block at the height in the chain parameters."),
  (K, "The sequence field has an older meaning that is still in use: the value 0xffffffff means a final input, and the lock time of a transaction is ignored if all inputs are final; the values just below it are used by wallets for other purposes. The new meaning applies only to transactions of version 2 or higher, and only if bit 31 of the field is clear."),
 ), None),

 ("RelativeTimelock", "Relative timelock (sequence)", 3, "RelativeTimelocks", ("sequence 144 means: not before 144 blocks of age", "A relative timelock is encoded in the sequence field of an input: if bit 31 is clear, the low 16 bits are a number of blocks, or of 512-second units when bit 22 is set, that the spent output must have aged before the input is valid.",
   (PROG("def decode(seq):\n    if seq & (1 << 31): return 'no relative lock'\n    n = seq & 0xffff\n    return (n * 512, 'seconds') if seq & (1 << 22) else (n, 'blocks')\nresult = [decode(s) for s in (144, (1 << 22) | 10, 1 << 31, 0xfffffffd)]"), "[(144, 'blocks'), (5120, 'seconds'), 'no relative lock', 'no relative lock']")), P(
  (W, "A relative timelock is a restriction on an input that counts time from the confirmation of the output it spends. BIP68 repurposes the sequence number of each input for it. If bit 31 of the sequence is set, no consensus meaning is applied. If it is clear, the sequence is an encoded relative lock time: bit 22 decides whether the lock is in blocks, when the bit is clear, or in units of 512 seconds, when it is set, and only the low 16 bits, selected with the mask 0x0000ffff, carry the number [B68]."),
  (Y, "The design gives a year of range and the same resolution in both units. BIP68 explains the 512 seconds: blocks come about every 600 seconds, so the same number of bits can encode the same amount of time whether it is counted in blocks or in time; converting a sequence to seconds means multiplying by 512, which is 2 to the power 9. With 16 bits the largest block lock is 65,535 blocks, about 455 days, and the largest time lock is 65,535 times 512 seconds, about 388 days. The rules apply only to transactions of version 2 or higher, and not to the coinbase [B68]."),
  (E, "The encoding is in Bitcoin Core's header: the constants SEQUENCE_LOCKTIME_DISABLE_FLAG as bit 31, SEQUENCE_LOCKTIME_TYPE_FLAG as bit 22, the mask 0x0000ffff and the granularity of 9. The page's example decodes four sequence numbers: 144 is a lock of 144 blocks, the value with bit 22 and the number 10 is 5,120 seconds, and the two values with bit 31 set, among them 0xfffffffd that wallets use for other purposes, have no relative lock. In block 775,072, among 594 inputs of version-2 transactions, only one has an enabled and nonzero relative lock [BCX] [MP]."),
  (H, "The consensus code that applies the rule is the function CalculateSequenceLocks. For each input it finds the height of the block that confirmed the spent output, adds the number of blocks, or reads the median time past of the block before the confirming one and adds the number of 512-second units, and turns the result into the last invalid height and the last invalid time of the transaction, the same convention as for the lock time. The transaction can be in a block only if the block's height and the median time past of its predecessor are beyond both [BCT]."),
  (K, "The block lock counts from the block that confirmed the output, and the time lock from the median time past of that block's predecessor, not from the time stamp of the block, so a time lock measured in 512-second units can be a few blocks off what a clock shows. And the commonly used values just below the maximum sequence have bit 31 set, so they are not relative locks at all; confusing the old and new meaning of the field is the usual mistake."),
 ), None),

 ("CheckSequenceVerify", "OP_CHECKSEQUENCEVERIFY", 3, "RelativeTimelocks", ("<pk> OP_CHECKSIGVERIFY <n> OP_CHECKSEQUENCEVERIFY", "OP_CHECKSEQUENCEVERIFY fails a script unless the transaction has version 2 or more and the sequence of the spending input carries a relative lock of the same kind as, and at least as large as, the number on top of the stack.",
   (PROG("def csv(n, seq, version):              # the failure conditions of BIP112 once the operand has the disable flag clear\n    if version < 2 or seq & (1 << 31): return 'fail'\n    if bool(n & (1 << 22)) != bool(seq & (1 << 22)): return 'fail'\n    return 'ok' if (n & 0x40ffff) <= (seq & 0x40ffff) else 'fail'\nresult = (csv(144, 144, 2), csv(144, 143, 2), csv(144, 144, 1), csv(144, (1 << 22) | 144, 2))"), "('ok', 'fail', 'fail', 'fail')")), P(
  (W, "OP_CHECKSEQUENCEVERIFY, written CSV, is the script opcode for relative timelocks. The book says that, as with lock time and OP_CHECKLOCKTIMEVERIFY, there is an opcode for relative timelocks that reads the sequence value: when it is evaluated in the script of an output, the output can be spent only in a transaction whose input sequence is greater than or equal to the parameter, which restricts spending until a number of blocks or seconds have passed relative to the time the output was mined [AH]."),
  (Y, "The opcode lets a script decide by the age of the output. BIP112 gives an escrow with a timeout as its first example: three parties lock funds in a 2-of-3 script with an alternative branch, and after 30 days one of them can sign alone, but the clock does not start until the payment to the escrow address confirms. It also names hash time-locked contracts, bidirectional payment channels and the Lightning Network, where the delay gives a party a predictable time to respond when the other broadcasts an old state [B112]."),
  (E, "BIP68 and BIP112 are enforced from block 419,328 of the chain, which was mined on 4 July 2016. The book says that they were activated in May 2016; the BIPs say the voting period started on 1 May 2016, and the rules applied from the later block that Bitcoin Core records [BCL] [MA] [AH]. The page's example runs the script with real signatures: with version 2 and a sequence of 144 the spend succeeds, a sequence of 143 fails, a version-1 transaction fails, and a sequence with bit 22 set fails because the kind differs. None of the 91 witness scripts revealed in block 775,072 contains the opcode, so the sampled block shows no use of it [MP]."),
  (H, "The engine reads the operand, which can have five bytes, fails if it is negative, and treats the opcode as a no-operation if the operand has the disable flag set, a hook for later soft forks. Otherwise it asks the checker to compare: the transaction version must be at least 2, the sequence of the input must not have bit 31 set, the kind bit must be the same in both, and the operand masked with the type bit and the 16-bit mask must not exceed the masked sequence. As for CLTV, the operand stays on the stack [BCI] [B112]."),
  (K, "The book points out a difference from CLTV: a script that executes several CSV opcodes must use only one kind, otherwise it can never be spent; but CSV allows any two valid inputs in one transaction, since each input has its own sequence, so the problem of interaction across inputs that exists for the absolute opcode does not occur. The opcode checks the sequence of the input and the sequence has to be set by the spender before signing, since the signature commits to it."),
 ), None),
]

CHECKS_E = [
 Qb(BK, "Bitcoin's", "distributed", "and timestamped blockchain has potential uses", "beyond payments.", "digital notary services", "proof-of-existence of that file on a specific date by reference to that", "transaction."),
 Qb(BK, "The use of Bitcoin's blockchain to store data", "unrelated to Bitcoin payments is a controversial subject.", "Many", "people consider such use abusive and want to discourage it.", "Others", "view it as a demonstration of the powerful capabilities of blockchain", "technology and want to encourage such experimentation.", "using a legacy Bitcoin address as a freeform 20-byte field.", "the resulting UTXO can _never_ be spent; it's a fake payment.", "cause the size of the UTXO database to forever", "increase, or \"bloat.\""),
 Qb(BK, "A compromise was reached", "that allows an output script starting with +OP_RETURN+ to", "add nonpayment data to a transaction output.", "the +OP_RETURN+ operator creates an explicitly", "_provably unspendable_ output, which does not need to be stored in the", "UTXO set.", "they are not stored in the UTXO set and therefore do not bloat", "full nodes with the cost of more", "expensive database operations.", "OP_RETURN <data>"),
 Qb(BK, "The data portion", "often represents a hash, such as the output", "from the SHA256 algorithm (32 bytes).", "uses the 8-byte prefix +DOCPROOF+, which is ASCII encoded as +44", "4f 43 50 52 4f 4f 46+ in hexadecimal."),
 Qb(BK, "there is no input script that corresponds to", "+OP_RETURN+ that could possibly be used to \"spend\" an +OP_RETURN+ output.", "+OP_RETURN+ outputs are _provably unspendable_.", "usually have a zero amount because any bitcoins", "assigned to such an output are effectively lost forever.", "the script validation engine", "will halt the execution of the validation script and mark the", "transaction as invalid."),
 Qb(BK, "Use of the", "lock time allows a spender to restrict a transaction from", "being included in a block until a specific block height, but it does not", "prevent spending the funds in another transaction earlier than that.", "sets the transaction lock time to 3 months in the future.", "Bob cannot transmit the transaction to redeem the funds until 3 months have elapsed.", "Alice can create a conflicting transaction, spending the same inputs without a lock time.", "Bob has no guarantee that Alice won't do that.", "The only guarantee is that Bob will not be able to redeem the presigned transaction before 3 months have elapsed.", "place the timelock restriction on the UTXO itself as part of the script, rather than on the transaction."),
 Qb(BK, "December 2015, a new form of", "timelock was introduced to Bitcoin as a soft fork upgrade.", "BIP65, a new script operator called", "+OP_CHECKLOCKTIMEVERIFY+ (+OP_CLTV+) was added to the scripting language.", "+OP_CLTV+ is a per-output timelock rather than a per-transaction timelock,", "that output is restricted so that it can only be spent after the", "specified time has elapsed.", "restricts specific UTXOs", "such that they can only be spent in a future transaction with", "lock time set to a greater or equal value."),
 Qb(BK, "<Bob's pubkey> OP_CHECKSIGVERIFY <now + 3 months> OP_CHECKLOCKTIMEVERIFY", "current block height", "{plus} 12,960 (blocks) or current Unix epoch time {plus} 7,760,000", "(seconds)."),
 Qb(BK, "If the +OP_CHECKLOCKTIMEVERIFY+", "parameter Alice set is less than or equal to the spending transaction's", "lock time, script execution continues", "The stack is empty.", "The top item on the stack is less than 0.", "The lock-time type (height versus timestamp) of the top stack item and the lock time field are not the same.", "The top stack item is greater than the transaction's lock time field.", "The sequence field of the input is 0xffffffff."),
 Qb(BK, "a script can never be valid if it must execute", "two different calls to +OP_CLTV+, one that uses a height and one that", "uses a time.", "the parameter that", "preceded it remains as the top item on the stack and may need to be", "dropped, with +OP_DROP+", "redefined existing opcodes that", "did not drop stack items", "Alice can no longer spend", "the money, but Bob cannot spend it before the 3-month lock time has", "expired."),
 Qb(BK, "_absolute timelocks_ in that they specify an absolute point in time.", "_relative timelocks_", "an elapsed time", "from the confirmation of the output in the blockchain.", "the clock", "doesn't start counting until the UTXO is recorded on the blockchain.", "implemented as a consensus rule", "on the value of +sequence+, a transaction field that is set in every", "transaction input.", "BIP68 and BIP112 were activated in May 2016 as a soft fork upgrade to", "the consensus rules."),
 Qb(BK, "allows", "spending only in a transaction whose input sequence value is greater", "than or equal to the +OP_CSV+ parameter.", "If +OP_CSV+ is specified in terms of", "blocks, then so must sequence.", "A script executing multiple +OP_CSV+ opcodes must only use the same", "variety", "+OP_CSV+ allows", "any two valid inputs to be included in the same transaction", "A child transaction cannot be used until the", "parent transaction has been propagated, mined, and aged by the time", "specified in the relative timelock."),
 Qb("ch06_transactions.adoc", "Bitcoin's earliest known soft fork added a rule", "that, starting at block height 31,000, forbid the inclusion of a", "transaction in a block unless it satisfies one of the following rules:", "by setting its lock time to 0.", "by setting its lock time to a value less than", "500,000,000.", "block that has a height equal to the lock time or higher.", "a transaction with a lock time of 123,456 can be included in", "block 123,456 or any later block.", "500,000,000 or greater.", "(MTP) greater than the lock time."),
 Qb("ch09_fees.adoc", "Several wallets discourage fee sniping by creating transactions with a", "lock time that limits those transactions to being included in the next", "block or any later block.", "our wallet would set lock time to 100,001 on any", "transaction it created."),
 Qe("bip-0065.mediawiki", "CHECKLOCKTIMEVERIFY redefines the existing NOP2 opcode.", "the stack is empty; or", "the top item on the stack is less than 0; or", "the lock-time type (height vs. timestamp) of the top stack item and the nLockTime field are not the same; or", "the top stack item is greater than the transaction's nLockTime field; or", "the nSequence field of the txin is 0xffffffff;", "the nLockTime field can't prove that it is ''impossible'' to spend a", "<now + 3 months> CHECKLOCKTIMEVERIFY DROP", "Lenny"),
 Qe("bip-0068.mediawiki", "If bit (1 << 31) of the sequence number is set, then no consensus meaning is applied", "Bit (1 << 22) determines if the relative lock-time is time-based or block based", "a timespan in units of 512 seconds granularity", "a mask of 0x0000ffff MUST be applied to the sequence field", "The 16-bit specification allows for a year of relative lock-time", "multiplying by 512 = 2^9, or equivalently shifting up by 9 bits", "The new rules are not applied to the nSequence field of the input of the coinbase transaction.", "transactions with an nVersion greater than or equal to 2", "So when using block-based or time-based, the same amount of time can be encoded with the available number of bits."),
 Qe("bip-0112.mediawiki", "CHECKSEQUENCEVERIFY redefines the existing NOP3 opcode.", "the top item on the stack is less than 0; or", "the transaction version is less than 2; or", "the transaction input sequence number disable flag (1 << 31) is set; or", "the relative lock-time type is not the same; or", "the top stack item is greater than the transaction input sequence (when masked according to the BIP68);", "An escrow that times out automatically 30 days after being funded", "The clock does not start ticking until the payment to the escrow address", "the BIP9 '''starttime''' will be midnight 1st May 2016 UTC", "This BIP must be deployed simultaneously with BIP68 and BIP113"),
 Qc("src/script/interpreter.cpp", "case OP_RETURN:", "return set_error(serror, SCRIPT_ERR_OP_RETURN);", "// not enabled; treat as a NOP2", "// not enabled; treat as a NOP3", "const CScriptNum nLockTime(stacktop(-1), fRequireMinimal, 5);", "return set_error(serror, SCRIPT_ERR_NEGATIVE_LOCKTIME);", "return set_error(serror, SCRIPT_ERR_UNSATISFIED_LOCKTIME);", "if (CTxIn::SEQUENCE_FINAL == txTo->vin[nIn].nSequence)", "if ((nSequence & CTxIn::SEQUENCE_LOCKTIME_DISABLE_FLAG) != 0) break;", "if (txTo->version < 2) return false;", "if (txToSequence & CTxIn::SEQUENCE_LOCKTIME_DISABLE_FLAG) return false;", "if (nSequenceMasked > txToSequenceMasked) return false;", "if (nLockTime > (int64_t)txTo->nLockTime) return false;"),
 Qc("src/script/script.h", "bool IsUnspendable() const", "return (size() > 0 && *begin() == OP_RETURN) || (size() > MAX_SCRIPT_SIZE);", "This allows outputs to be pruned", "instantly when entering the UTXO set."),
 Qc("src/policy/policy.h", "/** Default for -datacarrier */", "inline constexpr bool DEFAULT_ACCEPT_DATACARRIER = true;", "* Default setting for -datacarriersize in vbytes.", "inline constexpr unsigned int MAX_OP_RETURN_RELAY = MAX_STANDARD_TX_WEIGHT / WITNESS_SCALE_FACTOR;", "inline constexpr int32_t MAX_STANDARD_TX_WEIGHT{400'000};"),
 Qc("src/policy/policy.cpp", "unsigned int datacarrier_bytes_left = max_datacarrier_bytes.value_or(0);", "if (whichType == TxoutType::NULL_DATA) {", "unsigned int size = txout.scriptPubKey.size();", "if (size > datacarrier_bytes_left) {", "reason = \"datacarrier\";", "datacarrier_bytes_left -= size;"),
 Qc("src/consensus/consensus.h", "inline constexpr int WITNESS_SCALE_FACTOR = 4;"),
 Qc("src/consensus/tx_verify.cpp", "bool IsFinalTx(const CTransaction &tx, int nBlockHeight, int64_t nBlockTime)", "if (tx.nLockTime == 0) return true;", "if ((int64_t)tx.nLockTime < ((int64_t)tx.nLockTime < LOCKTIME_THRESHOLD ? (int64_t)nBlockHeight : nBlockTime)) return true;", "if (!(txin.nSequence == CTxIn::SEQUENCE_FINAL)) return false;", "// The semantics of nLockTime are the last invalid height/time, so", "bool fEnforceBIP68 = tx.version >= 2 && flags & LOCKTIME_VERIFY_SEQUENCE;"),
 Qc("src/primitives/transaction.h", "static constexpr uint32_t SEQUENCE_FINAL{0xffffffff};", "static constexpr uint32_t SEQUENCE_LOCKTIME_DISABLE_FLAG{1U << 31};", "static constexpr uint32_t SEQUENCE_LOCKTIME_TYPE_FLAG{1 << 22};", "static constexpr uint32_t SEQUENCE_LOCKTIME_MASK{0x0000ffff};", "static constexpr int SEQUENCE_LOCKTIME_GRANULARITY{9};"),
 Qc("src/kernel/chainparams.cpp", "consensus.BIP65Height = 388381; // 000000000000000004c2b624ed5d7756c508d90fd0da2c7c679febfa6c4735f0", "consensus.CSVHeight = 419328; // 000000000000000004a1b34462cb8aeebd5799177f7a29cf28f2d1961716b5b5"),
 # executed: the data output
 X("L.classify(bytes([0x6a, 40]) + b'DOCPROOF' + L.sha256(b'hello'))", ("nulldata", "OP_RETURN <data>")),
 X("(b'DOCPROOF'.hex(), len(bytes([0x6a, 40]) + b'DOCPROOF' + L.sha256(b'hello')))", ("444f4350524f4f46", 42)),
 X("L.run('', 'OP_RETURN')", "OP_RETURN"),
 X("L.run('1', 'OP_RETURN')", "OP_RETURN"),
 X("L.run('1', 'OP_RETURN 1')", "OP_RETURN"),
 X(NULLDATA, [(5500, 83), (5500, 83), (5500, 83), (6213, 83), (5500, 83), (0, 3), (0, 55), (0, 54)]),
 X("sum(len(L.parse_tx(r['hex']).vout) for r in C.block_records())", 1668),
 X("sum(s for v, s in " + NULLDATA.replace("[(v, len(s))", "[(v, len(s))") + ")", 527),
 X("[s[:3].hex() for r in C.block_records() for v, s in L.parse_tx(r['hex']).vout if L.classify(s)[0] == 'nulldata' and len(s) == 83]", ["6a4c50"] * 5),
 X("(400000 // 4, 400000 // 4 == 100000)", (100000, True)),
 X("[s[2:12].decode('ascii') for r in C.block_records() for v, s in L.parse_tx(r['hex']).vout if L.classify(s)[0] == 'nulldata' and len(s) in (55, 54)]", ["+:BTC.BTC:", "ion:1.QmVx"]),
 # executed: lock time
 X("(C.is_final(775071, 775072, 0, [0]), C.is_final(775071, 775071, 0, [0]), C.is_final(0, 1, 0, [0]), C.is_final(775071, 775071, 0, [0xffffffff]))", (True, False, True, True)),
 X("(C.is_final(1700000000, 1, 1700000001, [0]), C.is_final(1700000000, 1, 1700000000, [0]))", (True, False)),
 X("sum(1 for r in C.block_records() if L.parse_tx(r['hex']).locktime)", 131),
 X("max(L.parse_tx(r['hex']).locktime for r in C.block_records() if L.parse_tx(r['hex']).locktime) < 500000000", True),
 X("sum(1 for r in C.block_records() if L.parse_tx(r['hex']).locktime == 775071)", 108),
 X("C.ev_json('mainnet_block775072_census_v1_0_0.json')['block_height'] if 'block_height' in C.ev_json('mainnet_block775072_census_v1_0_0.json') else 775072", 775072),
 X("all(C.is_final(L.parse_tx(r['hex']).locktime, 775072, 1677000000, [i[3] for i in L.parse_tx(r['hex']).vin]) for r in C.block_records())", True),
 X("(12960 * 600 / 86400, 90 * 86400, 7776000 - 7760000)", (90.0, 7776000, 16000)),
 # executed: CLTV
 X("[C.key_spend(" + _sc(0xb1, 500000) + ", 1, locktime=lt, sequence=sq) for lt, sq in ((500000, 0), (600000, 0), (499999, 0), (500000, 0xffffffff), (1700000000, 0))]", ["OK", "OK", "UNSATISFIED_LOCKTIME", "UNSATISFIED_LOCKTIME", "UNSATISFIED_LOCKTIME"]),
 X("(C.key_spend(" + _sc(0xb1, 500000) + ", 1, locktime=0, sequence=0, flags=frozenset({'P2SH'})), C.key_spend(" + _sc(0xb1, 500000) + ", 1, locktime=0, sequence=0))", ("OK", "UNSATISFIED_LOCKTIME")),
 X("C.key_spend(" + _sc(0xb1, 500000) + ", 1, locktime=500000, sequence=0, wrap='p2wsh')", "OK"),
 X("C.key_spend(" + _sc(0xb1, 500000) + ", 2, locktime=500000, sequence=0)", "CHECKSIGVERIFY"),
 X("L.run('', '500 OP_CHECKLOCKTIMEVERIFY OP_DROP 1', flags=L.MAINNET_FLAGS, locktime=500, sequence=0)", "OK"),
 X("L.run('', '-1 OP_CHECKLOCKTIMEVERIFY OP_DROP 1', flags=L.MAINNET_FLAGS, locktime=500, sequence=0)", "NEGATIVE_LOCKTIME"),
 X("L.run('', 'OP_CHECKLOCKTIMEVERIFY OP_DROP 1', flags=L.MAINNET_FLAGS, locktime=500, sequence=0)", "INVALID_STACK_OPERATION"),
 X("L.run('', '500 OP_CHECKLOCKTIMEVERIFY 1', flags=L.MAINNET_FLAGS, locktime=500, sequence=0)", "OK"),
 X("L.run('', '500 OP_CHECKLOCKTIMEVERIFY', flags=L.MAINNET_FLAGS, locktime=500, sequence=0)", "OK"),
 X("L.run('', '500 OP_CHECKLOCKTIMEVERIFY OP_DROP 0', flags=L.MAINNET_FLAGS, locktime=500, sequence=0)", "EVAL_FALSE"),
 X("L.run('', '0 OP_CHECKLOCKTIMEVERIFY', flags=L.MAINNET_FLAGS, locktime=0, sequence=0)", "EVAL_FALSE"),
 X("L.run('', '500000 OP_CHECKLOCKTIMEVERIFY OP_DROP 500000000 OP_CHECKLOCKTIMEVERIFY OP_DROP 1', flags=L.MAINNET_FLAGS, locktime=500000, sequence=0)", "UNSATISFIED_LOCKTIME"),
 X("L.run('', '500000 OP_CHECKLOCKTIMEVERIFY OP_DROP 500000000 OP_CHECKLOCKTIMEVERIFY OP_DROP 1', flags=L.MAINNET_FLAGS, locktime=600000000, sequence=0)", "UNSATISFIED_LOCKTIME"),
 # executed: relative locks and CSV
 X("[C.key_spend(" + _sc(0xb2, 144) + ", 1, sequence=sq, version=v) for v, sq in ((2, 144), (2, 200), (2, 143), (1, 144), (2, 144 | (1 << 31)), (2, 144 | (1 << 22)))]", ["OK", "OK", "UNSATISFIED_LOCKTIME", "UNSATISFIED_LOCKTIME", "UNSATISFIED_LOCKTIME", "UNSATISFIED_LOCKTIME"]),
 X("C.key_spend(" + _sc(0xb2, 144 | (1 << 22)) + ", 1, sequence=(1 << 22) | 150, version=2)", "OK"),
 X("C.key_spend(" + _sc(0xb2, 144) + ", 1, sequence=0, version=1, flags=frozenset({'P2SH'}))", "OK"),
 X("L.run('', '%d OP_CHECKSEQUENCEVERIFY OP_DROP 1' % (1 << 31), flags=L.MAINNET_FLAGS, sequence=0xffffffff, version=1)", "OK"),
X("(round(65535 * 600 / 86400), round(65535 * 512 / 86400))", (455, 388)),
 X("[0x80000000 & s != 0 for s in (0xffffffff, 0xfffffffd, 0xfffffffe, 144)]", [True, True, True, False]),
 X("sorted(__import__('collections').Counter(i[3] for r in C.block_records() for i in L.parse_tx(r['hex']).vin).items(), key=lambda kv: -kv[1])[:3]", [(4294967295, 642), (4294967293, 205), (4294967294, 89)]),
 X("sum(len(L.parse_tx(r['hex']).vin) for r in C.block_records() if L.parse_tx(r['hex']).version >= 2)", 594),
 X("sum(1 for r in C.block_records() if L.parse_tx(r['hex']).version >= 2 for i in L.parse_tx(r['hex']).vin if not i[3] & (1 << 31) and i[3] != 0)", 1),
 X("sum(1 for s in C.witness_scripts(L) if any(op[1] in (0xb1, 0xb2) for op in L.get_ops(s)))", 0),
 X("len(C.witness_scripts(L))", 91),
 # executed: the dates
 X("(lambda a: [(b['height'], __import__('datetime').datetime.fromtimestamp(b['timestamp'], __import__('datetime').UTC).strftime('%Y-%m-%d')) for b in a['blocks']])(C.ev_json('mainnet_activation_blocks_v1_0_0.json'))", [(227931, "2013-03-25"), (363725, "2015-07-04"), (388381, "2015-12-14"), (419328, "2016-07-04"), (481824, "2017-08-24"), (709632, "2021-11-14")]),
 X("all(b['hash'] in C.core_text('src/kernel/chainparams.cpp') for b in C.ev_json('mainnet_activation_blocks_v1_0_0.json')['blocks'] if b['height'] in (388381, 419328, 481824))", True),
]
