"""SEN0401 chapter 6, corpus text part D (version 1.0.0): the branch 'The sequence field' - the four bytes whose meaning changed three
times: the original sequence-based replacement and the payment channel it sketched, the opt-in replace-by-fee signal of BIP125, and
the consensus-enforced relative timelock of BIP68 with its flags and mask. Markers become author-year strings."""
from sen0401_ch06_common_v1_0_0 import *

NODES_D = [
 ("SequenceField", "The sequence field", 1, None, None, P(
  (W, "This branch reads the last four bytes of an input, which the book calls its sequence number, and follows the three meanings the field has carried. The book says the use and meaning of this field has changed over time: it was originally intended to allow creation of multiple versions of the same transaction, with later versions replacing earlier versions as candidates for confirmation; it was later used as the signal for opt-in replace-by-fee; and since BIP68 it is a consensus-enforced relative timelock for transactions of version 2 or higher [AH]."),
  (Y, "The field matters out of proportion to its size because it is the hook on which Bitcoin's contract protocols hang. The book's first use of it is a card game between Alice and Bob that is, in effect, the first payment channel; its second use decides whether an unconfirmed payment can be replaced, which is what a merchant waiting for a payment needs to know; and its third use lets an output be made unspendable until it has aged, which the Lightning Network depends on [AH] [B68] [B125]. Alice's transaction sets it to 0xffffffff, the value that opts out of all three."),
  (E, "The reader meets the field in every input of every transaction, usually as ffffffff, and meets its meanings in three places: in a wallet's choice to make a payment replaceable, which sets the value to 0xfffffffd; in explorers, which flag such transactions as replaceable; and in the construction of any protocol that uses relative timelocks, where BIP68's encoding of blocks and seconds must be computed exactly. Bitcoin Core's transaction header declares the constants - SEQUENCE_FINAL, the disable flag, the type flag, the mask and the granularity - that this branch computes with [BCX]."),
  (H, "The branch has three groups in the historical order of the book. The first explains the original replacement scheme and the payment channel it enabled: the setup transaction, the refund, the rounds of a card game, and the three problems that led the scheme to be disabled, including a bandwidth attack that the book costs out. The second explains replace-by-fee and the BIP125 signal. The third explains the BIP68 timelock: which sequence values are locks, the type flag that chooses blocks or 512-second units, the disable flag, and the 16-bit mask [AH].")), None),

 ("SequenceReplacement", "Original sequence-based replacement", 2, "SequenceField", None, P(
  (W, "The original sequence-based replacement is the first meaning of the field: the book says the sequence field was originally intended to allow creation of multiple versions of the same transaction, with later versions replacing earlier versions as candidates for confirmation, the sequence number tracking the version of the transaction [AH]. This group follows the book's example of Alice and Bob betting on a game of cards, names the kind of protocol it is, and gives the three problems that ended the scheme."),
  (Y, "The scheme matters as the ancestor of every payment channel. The book says this type of protocol is what we now call a payment channel, that Bitcoin's creator in an email attributed to him called these high-frequency transactions, and that modern versions of payment channels are increasingly used in Bitcoin today [AH]. Understanding why the original scheme failed - a policy with no incentive, a race that bad luck could lose, and an unlimited free replacement that burdened every node - explains the design of its successors [AH]."),
  (H, "The four sections take the story in order. The sequence number section states the field and the final value. The setup and refund section explains the multisignature deposit and the first, refund version of the spend. The payment channel section follows the rounds in which the sequence is incremented and the balances move, and the alternative scenarios in which an old version is broadcast. The replacement attack section costs out the bandwidth attack that led to the scheme being disabled in an early version of the software [AH].")), None),

 ("SequenceNumber", "Sequence number", 3, "SequenceReplacement", ("the last four bytes of an input", "The sequence is the 4-byte field that ends every input; its maximal value 0xffffffff, called final, opts out of replacement, of the BIP125 signal and of any relative timelock.", ("int.from_bytes(bytes.fromhex('ffffffff'), 'little')", "4294967295")), P(
  (W, "The sequence number is the four-byte unsigned integer that ends each input, after the outpoint and the input script. The book says the final four bytes of an input are its sequence number and that the use and meaning of this field has changed over time [AH]. In Alice's transaction the bytes are ffffffff, the maximal value, which the worked example reads as 4,294,967,295; Bitcoin Core names that value SEQUENCE_FINAL [BCX]."),
  (Y, "The number matters because it is a per-input field, not a per-transaction one. Each input carries its own, so one transaction can have inputs with different sequence values, which is what lets BIP68 lock some inputs and not others, and what the book notes when it says a transaction may contain any number of timelocked inputs, all of which must have sufficiently aged [AH] [B68]. The maximal value is the one that means nothing special under every rule: no replacement in the original scheme, no BIP125 signal, no relative timelock, and no lock time either, since Bitcoin Core ignores a lock time when every input is final [BCV]."),
  (H, "The field is read as a little-endian integer, so ffffffff is the maximum and 00000000 the minimum. The original software compared sequence values to choose between versions of a transaction, with the highest winning; BIP125 reads any value up to 0xfffffffd as a signal; BIP68 reads the bits of a value below 2 to the 31 as a timelock; and the lock-time rule reads the value only to see whether it is final [AH] [B125] [B68] [BCV]. All four readings are of the same four bytes, and the later groups give each its own section."),
  (K, "The caution is that the word sequence suggests an order of inputs, which it is not; the inputs are ordered by their position in the list, and the sequence is a per-input number with the meanings above. A second caution is historical: a reader who meets sequence described as a transaction version counter in old material is reading about the first meaning, which the book says was disabled in an early version of the software [AH].")), None),

 ("SetupTransaction", "Setup and refund transactions", 3, "SequenceReplacement", ("a deposit that needs both signatures", "The setup transaction deposits Alice's and Bob's money into a multisignature output that needs both signatures; the refund transaction, with sequence 0, pays each their deposit back and is kept unbroadcast.", ("(lambda deposits: (sum(deposits.values()), dict(deposits)))({'Alice': 50000, 'Bob': 50000})", "(100000, {'Alice': 50000, 'Bob': 50000})")), P(
  (W, "The setup transaction is the first transaction of the book's card game. Alice and Bob start by each signing a transaction that deposits some money into an output with a script that requires signatures from both of them to spend, a multisignature script, multisig for short, and this is called the setup transaction [AH]. The first version of the transaction that spends that output, with sequence 0, pays Alice and Bob back the money they initially deposited; this is called a refund transaction, and neither of them broadcasts it, since they only need it if there is a problem [AH]."),
  (Y, "The pair matters because it is the skeleton of every contract between two parties on Bitcoin. A multisignature output is one that neither party can spend alone, which chapter 5 met as the arrangement in which several signers each hold a key and the book's next chapter explains as a script; the refund is what makes depositing into such an output safe, because either party can get their money back if the other disappears [AH]. The worked example models the deposit as two amounts that sum to the output, the state from which every later version of the spend redistributes."),
  (H, "The two transactions are created in a particular order. Both parties must sign the refund before the setup is broadcast, or one of them could lock the other's money forever by refusing to cooperate; the witness branch shows that in the legacy format this ordering is impossible without trust, because the refund must name the setup's identifier, which depends on signatures that are not yet known, a circular dependency [AH]. The sequence field's role is only in the versions of the spend: the refund carries sequence 0 so that any later version, with a higher sequence, replaces it."),
  (K, "The caution is that a refund with sequence 0 could, under the original software, be replaced by any transaction with a higher sequence, so it protected a party only until the other broadcast a later version; the book's alternative scenarios show the race. A second caution is that the setup's multisignature output has nothing to do with the sequence field; the field lives in the spending transactions, and the deposit itself uses a final sequence.")), None),

 ("PaymentChannel", "Payment channel", 3, "SequenceReplacement", ("many versions, one broadcast", "A payment channel is a protocol in which two parties sign many versions of one transaction off the chain, each with a higher sequence, and broadcast only the final one; the book's card game is the original form.", (PROG("balance = {'Alice': 50000, 'Bob': 50000}\nversions = [(0, dict(balance))]                           # the refund, sequence 0\nfor seq, (winner, loser, amount) in enumerate([('Alice', 'Bob', 10000), ('Bob', 'Alice', 25000)], start=1):\n    balance[winner] += amount; balance[loser] -= amount\n    versions.append((seq, dict(balance)))\nversions.append((0xffffffff, dict(balance)))              # the final version, broadcast\nresult = (len(versions), versions[-1])"), "(4, (4294967295, {'Alice': 35000, 'Bob': 65000}))")), P(
  (W, "A payment channel is the kind of protocol the book's card game describes: the book says this type of protocol is what we now call a payment channel, and that Bitcoin's creator, in an email attributed to him, called these high-frequency transactions and described a number of features added to the protocol to support them [AH]. Alice wins the first round, so the second version of the transaction, with sequence 1, increases her share; Bob wins the second, so the sequence becomes 2 and the shares move back; after many rounds they set the sequence to its maximum, 0xffffffff, finalise, and broadcast only that version [AH]."),
  (Y, "The channel matters because it moves value many times with one confirmed transaction. Every version is a complete, signed, valid transaction that spends the setup output, but only the last is broadcast, so the chain records one setup and one settlement no matter how many rounds were played. The book's alternative scenarios show what the replacement rule was for: if Bob broadcasts an earlier version where his balance was higher, full nodes running the original code will not relay it against a version with a higher sequence, and miners using that code will not mine it [AH]."),
  (H, "The worked example plays two rounds: the refund with sequence 0 and equal balances, Alice winning 10,000, Bob winning 25,000, and then the final version with the maximal sequence, four versions in all, the last paying Alice 35,000 and Bob 65,000. In the original software the rule was simple - a higher sequence replaces a lower one - and the book's second scenario shows its weakness: if Bob's old version is broadcast a few seconds before Alice's final one, nodes relay Bob's and miners try to mine it, and unless Bob gets lucky and a block is found first, Alice's version replaces it [AH]."),
  (K, "The caution is in the words unless Bob got lucky. The book names three problems with purely sequence-based channels: the replacement rule was only software policy with no incentive for miners to prefer one version, the first transaction sent might get confirmed by luck even when it was not the highest-sequence one, and a security protocol that fails a few percent of the time due to bad luck is not a very effective protocol [AH]. Modern channels fix these with timelocks and penalties, which the book defers to its chapter on second-layer applications.")), None),

 ("ReplacementAttack", "The replacement bandwidth attack", 3, "SequenceReplacement", ("20 KB in, 10 GB out, every minute", "Unlimited free replacement let an attacker with 1,000 replacements a minute at 200 bytes each cost 50,000 relaying nodes about 10 GB of bandwidth a minute for 20 KB of their own, so the scheme was disabled.", ("(lambda nodes, per_minute, size: (per_minute * size // 1000, nodes * per_minute * size // 10 ** 9))(50000, 1000, 200)", "(200, 10)")), P(
  (W, "The replacement bandwidth attack is the third problem the book gives with the original scheme: it was possible to replace one version of a transaction with a different version an unlimited number of times, and each replacement would consume the bandwidth of all the relaying full nodes on the network. The book's figures: with about 50,000 relaying full nodes, an attacker creating 1,000 replacement transactions per minute at 200 bytes each would use about 20 KB of their own bandwidth but about 10 GB of full-node network bandwidth every minute [AH]."),
  (Y, "The attack matters because it is the reason replacement was removed and then returned in a restricted form. The book says that except for the cost of their 20 KB per minute and the occasional fee when a transaction was confirmed, the attacker would pay nothing for the enormous burden placed on full-node operators, and that to eliminate the risk the original type of sequence-based replacement was disabled in an early version of the software; for several years, nodes would not let an unconfirmed transaction containing a particular input be replaced at all [AH]."),
  (H, "The worked example recomputes the book's arithmetic: 1,000 transactions of 200 bytes is 200,000 bytes, which the book rounds to about 20 KB in the attacker's own uplink, and the same bytes relayed to 50,000 nodes is 10 gigabytes a minute across the network. The asymmetry is the whole attack: a replacement costs its sender once and costs the network once per node, and with no fee required for a replacement the ratio is unbounded. BIP125's rule that a replacement must pay more fee than what it replaces, and enough extra to pay for its own relay, is the answer the next group describes [B125]."),
  (K, "The caution is in the book's own figure: 1,000 transactions of 200 bytes is 200 KB, not 20 KB, so the text understates the attacker's cost by a factor of ten while the network figure of 10 GB is correct; the worked example shows both. The lesson is unchanged, since the ratio of 50,000 to one is what matters. A second caution is that the attack is about relay, not about blocks: no replacement needs to be confirmed for the damage to be done.")), None),

 ("ReplaceByFee", "Opt-in replace-by-fee", 2, "SequenceField", None, P(
  (W, "Replace-by-fee is the second meaning of the sequence field. The book says that after the original replacement was disabled for its potential for abuse, a solution was proposed: programming Bitcoin Core and other relaying full-node software to allow a transaction that paid a higher fee rate to replace a conflicting transaction that paid a lower fee rate, called replace by fee or RBF; some users and businesses objected, so a compromise once again used the sequence field as an opt-in signal [AH]."),
  (Y, "The group matters for anyone who accepts an unconfirmed payment. A payment that signals replaceability can be replaced by a conflicting one before it confirms, so a merchant who sees the signal knows to wait; the book says this let users and businesses that objected to replacement simply ignore unconfirmed transactions containing the BIP125 signal until they became confirmed [AH]. It also matters to the sender, who can raise a fee that turned out too low rather than wait indefinitely."),
  (H, "The two sections are the policy and its signal. The opt-in replace-by-fee section explains what a replacement must do - conflict, pay a higher rate, and pay for its own bandwidth - and what Bitcoin Core allowed and disallowed; the BIP125 signal section gives the rule from the proposal, that any input with a sequence below 0xfffffffe signals replaceability, and computes which values do and do not signal [AH] [B125].")), None),

 ("OptInRbf", "Opt-in replace-by-fee", 3, "ReplaceByFee", ("a higher fee rate replaces a lower one", "Opt-in replace-by-fee is the relay policy under which a conflicting transaction paying a higher fee rate replaces an unconfirmed one that signalled replaceability; the replacement must also pay for its own relay.", ("(lambda old_fee, old_size, new_fee, new_size: (round(old_fee / old_size, 1), round(new_fee / new_size, 1), new_fee > old_fee and new_fee / new_size > old_fee / old_size))(5000, 143, 8000, 143)", "(35.0, 55.9, True)")), P(
  (W, "Opt-in replace-by-fee is the policy under which a relaying node allows a transaction that pays a higher fee rate to replace a conflicting transaction that paid a lower fee rate, provided the original signalled that it may be replaced. The book says RBF was proposed after the original replacement was disabled, that some users and businesses objected to adding replacement back into Bitcoin Core, and that the compromise used the sequence field so that replacement is opt-in [AH]. The fee rate is the fee divided by the transaction's size, a quantity the book's chapter on fees develops."),
  (Y, "The policy matters because it restores a safe form of what the original scheme offered. A sender whose payment is stuck at a fee that miners ignore can issue a replacement; a payment-channel protocol can rely on a later version displacing an earlier one if it pays more; and the bandwidth attack is priced out, because each replacement must pay more than the one it replaces. Bitcoin Core's replacement checks require the replacement to pay more fees than the original transactions and to pay for its own bandwidth at or above the incremental relay fee rate [BCP] [B125]."),
  (H, "The worked example compares two fee rates for a transaction of 143 virtual bytes, the size of Alice's: 5,000 satoshis is about 35 satoshis per vbyte, 8,000 is about 56, and the replacement both pays more in total and has the higher rate, so it qualifies. The book notes that there is more to modern replacement policies than fee rates and sequence signals, which it takes up under a later chapter's section on replace-by-fee; BIP125 itself adds that a replacement may not add new unconfirmed inputs and may not evict more than a limited number of transactions [AH] [B125]."),
  (K, "The caution is that replace-by-fee is policy, not consensus. A node may run a different policy, a miner may mine whichever conflicting version it prefers, and nothing in the blockchain's validity rules refers to the signal; what the policy gives is predictability on the network as it is actually run. A second caution is that replacement works on conflicts, so a replacement must spend at least one of the same outpoints as the original, which is what makes it a replacement rather than a second payment [B125].")), None),

 ("Bip125Signal", "The BIP125 signal", 3, "ReplaceByFee", ("below 0xfffffffe means replaceable", "By BIP125 an unconfirmed transaction with any input whose sequence is below 0xfffffffe, at least two below the maximum, signals that it may be replaced by a conflicting transaction paying a higher fee rate.", ("[(hex(s), s <= 0xfffffffd) for s in (0xffffffff, 0xfffffffe, 0xfffffffd, 0)]", "[('0xffffffff', False), ('0xfffffffe', False), ('0xfffffffd', True), ('0x0', True)]")), P(
  (W, "The BIP125 signal is the use of the sequence field as an opt-in flag for replacement. The book says that as documented in BIP125, an unconfirmed transaction with any input that has a sequence set to a value below 0xfffffffe, that is at least two below the maximum value, signals to the network that its signer wants it to be replaceable by a conflicting transaction paying a higher fee rate; Bitcoin Core allowed those unconfirmed transactions to be replaced and continued to disallow other transactions from being replaced [AH]."),
  (Y, "The signal matters because it put the choice in the sender's hands and left everyone else able to read it. A wallet that wants the option of raising a fee sets one input's sequence to 0xfffffffd; a merchant who will not accept replaceable payments before confirmation checks for any sequence below 0xfffffffe; and the explorer that this course consulted reports exactly this flag for every transaction it shows [B125] [MP]. Alice's transaction, with every sequence at the maximum, does not signal."),
  (H, "The worked example tests the four interesting values: the maximum and the value one below it do not signal, 0xfffffffd and every lower value do. The threshold is two below the maximum because the value one below, 0xfffffffe, already had a meaning - it is the highest value that still lets the lock-time field apply - and BIP125 chose not to collide with it [B125] [BCV]. BIP125 also describes inherited signalling: a transaction that does not signal is nonetheless replaceable while any unconfirmed ancestor of it signals, since replacing the ancestor removes the descendant too [B125]."),
  (K, "The caution is one the book itself makes at the end of the timelock group: any transaction that sets a relative timelock using the sequence field also sends the signal for opt-in replace-by-fee, because a timelock value is far below 0xfffffffe [AH]. A second caution is that Bitcoin Core has moved beyond the signal in its default policy: its release notes for version 28.0 record that the default of the mempoolfullrbf option changed from 0 to 1, so a default node now treats every unconfirmed transaction as replaceable; the book's statement describes the policy as the proposal defined it, and a reader should check the policy of the software in use [BCN].")), None),

 ("RelativeTimelock", "Sequence as a relative timelock", 2, "SequenceField", None, P(
  (W, "The relative timelock is the third meaning of the sequence field and the only one enforced by consensus. The book says the BIP68 soft fork added a new constraint to transactions with version numbers 2 or higher, that the constraint applies to the sequence field, and that inputs with sequence values less than 2 to the 31 are interpreted as having a relative timelock: such a transaction may only be included in the blockchain once the previous output referenced by the outpoint has aged by the relative timelock amount [AH] [B68]."),
  (Y, "A relative timelock is relative to the confirmation of the output being spent rather than to a fixed height or time, which is what contract protocols need: a party can be given a window after a deposit confirms, however long the deposit takes. BIP68's own motivation names bidirectional payment channels and hashed timelock contracts, the building blocks of the Lightning Network, and the version gate of the version branch is what let the meaning be added without invalidating old transactions [B68] [AH]."),
  (H, "The four sections follow the bits of the field as BIP68's figure lays them out: the timelock itself and the rule of aging, the type flag at bit 22 that chooses between a count of blocks and a count of 512-second units, the disable flag at bit 31 that lets an input of a version 2 transaction opt out, and the 16-bit mask that extracts the value, whose maximum of 65,535 is a bit more than a year in either unit [AH] [B68].")), None),

 ("Bip68Timelock", "BIP68 relative timelock", 3, "RelativeTimelock", ("30 blocks: confirm 29 blocks after the output", "Under BIP68 a version 2 input with sequence below 2 to the 31 may only be confirmed once the output it spends has aged by the sequence's value: a lock of 30 blocks allows confirmation with at least 29 blocks between the two.", ("(lambda spent_at, lock: (spent_at + lock, spent_at + lock - spent_at - 1))(774958, 30)", "(774988, 29)")), P(
  (W, "The BIP68 relative timelock is the consensus rule that reads a low sequence value as a minimum age of the output being spent. The book states it with an example: a transaction with one input with a relative timelock of 30 blocks can only be confirmed in a block with at least 29 blocks between it and the block containing the output being spent on the same blockchain; and since sequence is a per-input field, a transaction may contain any number of timelocked inputs, all of which must have sufficiently aged for the transaction to be valid [AH]."),
  (Y, "The rule matters because it is enforced by every node rather than by policy. An output can be deposited with the knowledge that whoever spends it along a given path must wait, and no amount of fee or luck shortens the wait; BIP68 says its purpose is to prevent mining of a transaction until a certain age of the spent output in blocks or timespan, allowing among other uses the bidirectional payment channels of BIP112 [B68]. The companion opcode of BIP112 lets an output script demand such a lock, so the restriction can be imposed by the script rather than chosen by the spender."),
  (H, "The worked example applies the book's example to Alice's chain: her input spends an output confirmed at height 774,958, and with a lock of 30 blocks the earliest confirming block is 774,988, leaving 29 blocks strictly between. Bitcoin Core computes the same bound in CalculateSequenceLocks as the output's height plus the masked value minus one, which is the last height at which the spend is still forbidden [BCV]. The rule applies only to version 2 or higher and only when the disable flag is clear, as the next sections explain [B68]."),
  (K, "The caution is that a relative timelock is a minimum, never a maximum; it cannot make an output expire, only delay it, and the book's note on the maturity rule of coinbase outputs is the same shape of rule. A second caution is that the lock is measured on the same blockchain: if the output's block is reorganised away, the age is counted again from its new confirmation, which is what the phrase on the same blockchain in the book's example means [AH].")), None),

 ("TypeFlag", "The type flag", 3, "RelativeTimelock", ("bit 22 chooses blocks or 512-second units", "The type flag is bit 22 of the sequence, value 1 shifted left 22; set, the lock counts units of 512 seconds, clear, it counts blocks.", ("(1 << 22, hex(1 << 22), (1 << 22 | 8) & 0xffff, ((1 << 22 | 8) & 0xffff) * 512)", "(4194304, '0x400000', 8, 4096)")), P(
  (W, "The type flag is the bit of the sequence field that says whether a relative timelock counts blocks or time. The book says the sequence value is specified in either blocks or seconds, that a type flag is used to differentiate between values counting blocks and values counting time in seconds, that the flag is set in the 23rd least-significant bit, value 1 shifted left 22, and that if it is set the sequence value is interpreted as a multiple of 512 seconds, otherwise as a number of blocks [AH]."),
  (Y, "The flag matters because the two units suit different contracts. A lock in blocks is exact in the chain's own terms but uncertain in wall-clock time; a lock in seconds is what a human agreement usually wants. BIP68 explains the choice of 512 seconds: blocks are generated every 600 seconds, so with 512-second units the same number of bits encodes about the same span either way, and converting a sequence number to seconds is a multiplication by 512, which is a shift left by nine bits [B68]."),
  (H, "The worked example computes the flag's value, 4,194,304 or 0x400000, and decodes a sequence with the flag set and a value of 8: the masked value is 8 and the lock is 8 times 512, which is 4,096 seconds. Bitcoin Core names the constant SEQUENCE_LOCKTIME_TYPE_FLAG and the shift SEQUENCE_LOCKTIME_GRANULARITY, nine; its CalculateSequenceLocks compares a time-based lock against the median time past of the output's block rather than against block times, as BIP68 specifies [BCX] [BCV] [B68]."),
  (K, "The caution is the ordinal in the book's sentence: the 23rd least-significant bit is bit 22 when counting from zero, which is why the value is 1 shifted left 22 and not 23. A second caution is that the time-based lock is measured in median time past, which is normally an hour or two behind the clock, so a lock of 4,096 seconds does not expire 4,096 seconds after the output's block was seen but after the chain's median time has advanced that far [AH] [B68].")), None),

 ("DisableFlag", "The disable flag", 3, "RelativeTimelock", ("bit 31 switches the timelock off", "The disable flag is bit 31 of the sequence; an input with it set has no relative timelock even in a version 2 transaction, so a transaction may mix locked and unlocked inputs.", ("[(hex(s), bool(s & 1 << 31)) for s in (0xffffffff, 0x80000000, 0x7fffffff, 30)]", "[('0xffffffff', True), ('0x80000000', True), ('0x7fffffff', False), ('0x1e', False)]")), P(
  (W, "The disable flag is the highest bit of the sequence field. The book says a disable flag allows a transaction to include both inputs with a relative timelock, sequence below 2 to the 31, and inputs without a relative timelock, sequence of 2 to the 31 or more [AH]. The flag is the reason the rule speaks of values below 2 to the 31: any value with bit 31 set is not a timelock, whatever its lower bits hold."),
  (Y, "The flag matters because it keeps old behaviour available input by input. Without it, every input of a version 2 transaction would carry a lock, and a wallet wanting one locked input would have to lock them all; with it, an input that should be spendable at once simply sets the bit. It is also what keeps the final value harmless: 0xffffffff has the disable flag set, so a version 2 transaction whose inputs are all final has no timelock at all, which the book's sequence of meanings relies on [AH] [B68]."),
  (H, "The worked example tests four values: the final value and 0x80000000 have the bit set and so carry no lock; 0x7fffffff and 30 do not and so are read as locks. Bitcoin Core's CalculateSequenceLocks checks this bit first and skips the input entirely when it is set, before looking at the type flag or the mask, which is the order the book's figure of the encoding suggests [BCV] [BCX]. BIP68 adds that the new rules are not applied to the sequence field of the input of the coinbase transaction, whatever its bits [B68]."),
  (K, "The caution is that the disable flag disables only the relative timelock. A sequence of 0x80000000 still signals replaceability under BIP125, since it is below 0xfffffffe, and still permits the lock-time field to apply, since it is not final; the three meanings of the field are independent readings of the same bits. A second caution is that version 1 transactions have no timelocks regardless of this bit, since the whole rule is gated on the version [AH].")), None),

 ("TimelockMask", "The 16-bit mask", 3, "RelativeTimelock", ("65,535 blocks or units, about a year", "Only the 16 least significant bits of the sequence carry the relative timelock, so the mask 0x0000ffff extracts a value of at most 65,535, which in blocks or in 512-second units is a bit more than a year.", ("(0xffff, 0xffff * 512 // 86400, 0xffff * 600 // 86400)", "(65535, 388, 455)")), P(
  (W, "The mask is the way a node extracts the timelock value from the sequence field. The book says that when interpreting sequence as a relative timelock only the 16 least significant bits are considered: once the flags, bits 32 and 23 in the book's counting, are evaluated, the value is usually masked with a 16-bit mask, sequence and 0x0000FFFF; and because the multiple of 512 seconds is roughly the average time between blocks, the maximum relative timelock in both blocks and seconds from 16 bits is a bit more than one year [AH]."),
  (Y, "The mask matters because it fixes the range of what a relative timelock can express and leaves bits free. Sixteen bits give at most 65,535; in 512-second units that is about 388 days, and at ten minutes a block 65,535 blocks is about 455 days, both a bit more than a year as the book says. The bits between the value and the type flag, and between the type flag and the disable flag, are unused and are among the features reserved for upgrades that a presigned transaction must not set [AH] [B68]."),
  (H, "The worked example computes the three figures: the maximal masked value, its span in days at 512 seconds a unit, and its span in days at 600 seconds a block. Bitcoin Core names the mask SEQUENCE_LOCKTIME_MASK with the value 0x0000ffff, and its time-based computation shifts the masked value left by the granularity of nine bits, which multiplies by 512 [BCX] [BCV]. The chapter's library applies the mask after the two flags, in the order the book describes."),
  (K, "The caution is in the book's bit numbering: it says bits 32 and 23 where the flags are at positions 31 and 22 counting from zero, the same convention as the type flag's 23rd least-significant bit; the values 1 shifted left 31 and 1 shifted left 22 are the unambiguous statement. A second caution is that the one-year ceiling is approximate in both units, because blocks are not exactly ten minutes apart and the 512-second units are measured in median time past.")), None),
]

CHECKS_D = [
 Qb("ch06_transactions.adoc", "The sequence field was originally intended to allow creation of", "multiple versions of the same transaction"),
 Qb("ch06_transactions.adoc", "This is called the", "_setup transaction_", "This is", "called a _refund transaction_"),
 Qb("ch06_transactions.adoc", "This type of protocol is what we now", "call a _payment channel_", "_high-frequency transactions_"),
 Qb("ch06_transactions.adoc", "there are about 50,000", "relaying full nodes; an attacker creating 1,000 replacement transactions", "per minute at 200 bytes each would use about 20 KB", "about 10 GB of full node network bandwidth"),
 Qb("ch06_transactions.adoc", "A", "security protocol that fails a few percent of the time due to bad luck", "isn't a very effective protocol."),
 Qb("ch06_transactions.adoc", "has a sequence set to a value below 0xfffffffe (i.e., at least 2 below", "the maximum value) signals to the network"),
 Qb("ch06_transactions.adoc", "a", "transaction with one input with a relative timelock of 30 blocks can", "only be confirmed in a block with at least 29 blocks between it"),
 Qb("ch06_transactions.adoc", "The type-flag is set in the 23rd", "least-significant bit (i.e., value 1<<22)", "interpreted as a multiple of 512 seconds"),
 Qb("ch06_transactions.adoc", "only the 16 least", "significant bits are considered", "+sequence+ & 0x0000FFFF", "is a bit more than one year"),
 Qb("ch06_transactions.adoc", "any transaction that sets a relative timelock using sequence", "also sends the signal for opt-in replace by fee"),
 Qe("bip-0125.mediawiki", "Opt-in Full Replace-by-Fee Signaling", "Inherited signaling"),
 Qe("bip-0068.mediawiki", "512 second granularity was chosen because bitcoin blocks are generated every 600 seconds", "The new rules are not applied to the nSequence field of the input of the coinbase transaction."),
 Qe("bip-0068.mediawiki", "nSequence will be repurposed to prevent mining of a transaction until a certain age of the spent output in blocks or timespan"),
 Qc("src/primitives/transaction.h", "SEQUENCE_FINAL{0xffffffff}", "SEQUENCE_LOCKTIME_DISABLE_FLAG{1U << 31}", "SEQUENCE_LOCKTIME_TYPE_FLAG{1 << 22}", "SEQUENCE_LOCKTIME_MASK{0x0000ffff}", "SEQUENCE_LOCKTIME_GRANULARITY{9}"),
 Qc("src/consensus/tx_verify.cpp", "nMinHeight = std::max(nMinHeight, nCoinHeight + (int)(txin.nSequence & CTxIn::SEQUENCE_LOCKTIME_MASK) - 1);"),
 Qc("src/policy/rbf.h", "The replacement transaction must pay more fees than the original transactions.", "fees must pay for the replacement's bandwidth at or above the incremental relay feerate."),
 Qe("core_doc_release-notes_release-notes-28.0.md", "The default value of the `-mempoolfullrbf` configuration option has been changed from 0 to 1,"),
 X("T.parse_tx(%r)['inputs'][0]['sequence'] == T.SEQUENCE_FINAL" % ALICE, True),
 X("C.ev_json('mempool_tx_466200308696215b_v1_0_0.json')['vin'][0]['sequence']", 4294967295),
 X("T.sequence_decode(T.SEQUENCE_FINAL)", {'value': 4294967295, 'hex': '0xffffffff', 'rbf_signal': False, 'final': True, 'relative_timelock': None}),
 X("[T.sequence_decode(s)['rbf_signal'] for s in (0xffffffff, 0xfffffffe, 0xfffffffd, 0)]", [False, False, True, True]),
 X("T.sequence_decode(30)['relative_timelock']", ('blocks', 30)),
 X("T.sequence_decode(T.sequence_for(seconds=4096))['relative_timelock']", ('seconds', 4096)),
 X("T.sequence_for(seconds=4096)", (1 << 22) | 8),
 X("T.sequence_decode(0x80000000)['relative_timelock'] is None", True),
 X("T.earliest_block(774958, 30)", 774988),
 X("T.earliest_block(774958, T.SEQUENCE_FINAL)", 774959),
 X("(T.SEQUENCE_LOCKTIME_MASK, T.SEQUENCE_LOCKTIME_TYPE_FLAG, T.SEQUENCE_LOCKTIME_DISABLE_FLAG, T.MAX_BIP125_RBF_SEQUENCE)", (0xffff, 1 << 22, 1 << 31, 0xfffffffd)),
 ("(1000 * 200, 1000 * 200 // 1024, 50000 * 1000 * 200 / 1e9)", "(200000, 195, 10.0)"),
 ("(2 ** 31, 0x7fffffff + 1 == 2 ** 31, 0xfffffffe - 0xfffffffd)", "(2147483648, True, 1)"),
 ("(65535 * 512 / 86400 > 365, 65535 * 600 / 86400 > 365)", "(True, True)"),
 ("(round(5000 / 143, 1), round(8000 / 143, 1))", "(35.0, 55.9)"),
]
