"""SEN0401 chapter 6, corpus text part C (version 1.0.0): the branch 'Inputs' - the count and the compactSize integer that encodes it,
the outpoint that points at a previous output (txid, output index, the lookup a full node performs, the rule against double spending
and the UTXO database), the two byte orders of a hash, and the input script with its length prefix. Markers become author-year strings."""
from sen0401_ch06_common_v1_0_0 import *

NODES_C = [
 ("Inputs", "Inputs", 1, None, None, P(
  (W, "This branch reads the inputs field of a transaction, the 42 bytes of Alice's transaction that say where the bitcoins she spends come from. The book says the inputs field contains several other fields and starts by showing a map of those bytes; the list begins with an integer giving the number of inputs, and each input must contain three fields: an outpoint, a length-prefixed input script and a sequence [AH]. The sequence is given its own branch because its meaning has changed three times."),
  (Y, "Inputs are where a transaction connects to the past. A transaction never states how many bitcoins it spends; it points at outputs of earlier transactions, and a full node reads the amount, the spending conditions and the confirmation data from the outputs it finds. Everything a node can refuse - spending an output twice, spending one that does not exist, spending without satisfying its conditions - is decided at the inputs, so the branch is where the rule against double spending lives [AH]."),
  (E, "The reader meets inputs every time a payment is traced: an explorer shows each input as a link to a previous transaction, and following those links backwards is following outpoints. The compactSize integer met here recurs in every counted field of the chapter, the byte-order confusion recurs in every identifier a user copies, and the empty input script of Alice's transaction is the first visible trace of segregated witness, whose reasons the witness branch gives [AH]."),
  (H, "The branch has four groups. The input list explains the count and the compactSize encoding that Bitcoin uses for integers that are usually small; the outpoint group explains the 36 bytes that identify one previous output, what a node obtains from that output, the double-spending rule and the database of unspent outputs; the byte order group explains why the identifier in the outpoint is written backwards from the form a user sees; and the input script group explains the field that legacy transactions fill with signatures and Alice's transaction leaves empty [AH].")), None),

 ("InputList", "The input list", 2, "Inputs", None, P(
  (W, "The input list is the inputs field as a whole: a count followed by that many inputs. The book says the transaction input list starts with an integer indicating the number of inputs, that the minimum value is one, that there is no explicit maximum but restrictions on the size of a transaction effectively limit transactions to a few thousand inputs, and that the number is encoded as a compactSize unsigned integer [AH]. This group explains the count and the encoding, and warns about the other variable-length integers that are not compactSize."),
  (Y, "The count is the first field whose length depends on its value, which is the feature that makes Bitcoin's format compact and makes it necessary to parse in order. A fixed four-byte count would waste three bytes in almost every transaction; a compactSize count costs one byte for up to 252 inputs and grows only when needed [AH]. The pizza transaction of this chapter's stories has 131 inputs and still spends one byte on its count, as an executed claim shows [MP]."),
  (H, "The three sections take the field apart. The input count section states the rule of at least one and the effective ceiling; the compactSize section gives the encoding table and the worked arithmetic of its four sizes; and the varint varieties section records the book's warning that several variable-length integers exist in Bitcoin programs, that Bitcoin Core's database uses a different one called VarInts, and that the nBits field of a block header uses yet another encoding called Compact, so the full name compactSize is always used for this one [AH].")), None),

 ("InputCount", "Input count", 3, "InputList", ("at least one, in practice a few thousand", "The input count is the compactSize integer that opens the inputs field; it must be at least one, and transaction size limits keep it to a few thousand in practice.", ("int.from_bytes(bytes.fromhex('01000000000101eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a0100000000ffffffff02204e0000000000002251203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068f8240100000000001600147752c165ea7be772b2c0acb7f4d6047ae6f4768e0141cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e817130100000000')[6:7], 'little')", "1")), P(
  (W, "The input count is the integer that opens the inputs field and says how many inputs follow. The book states that the minimum value is one, that there is no explicit maximum value, but that restrictions on the maximum size of a transaction effectively limit transactions to a few thousand inputs, and that the number is encoded as a compactSize unsigned integer [AH]. In Alice's transaction the count is the seventh byte, 01, after the version, the marker and the flag."),
  (Y, "The lower bound is a consensus rule and the reason the marker works. Bitcoin Core's CheckTransaction refuses a transaction whose input list is empty with the error bad-txns-vin-empty, so a count of zero can never appear in a valid legacy transaction, which is why the extended format can use a zero byte in that position as its marker [BCT] [AH]. The upper bound is indirect: a transaction's legacy serialization times the witness scale factor may not exceed the maximum block weight, and since each input takes at least 41 bytes the arithmetic caps the count in the thousands [BCT] [BCC]."),
  (H, "The worked example reads the byte at offset 6 of Alice's transaction as a little-endian integer and gets 1. The count is a compactSize integer, so for up to 252 inputs it is one byte read directly; the pizza transaction of 2010, with 131 inputs, still has a one-byte count of 0x83, and an executed claim parses that transaction and finds the 131 inputs the explorer reports [MP]. A parser must read the count before it can read anything else in the field, because the inputs that follow have no terminator."),
  (K, "The caution is that the count counts inputs, not bitcoins and not addresses. A transaction with one input may spend a large output, and one with hundreds may spend dust; and several inputs may belong to the same key. A second caution is that the count is the number of witness stacks too: the witness structure has no count of its own, so a parser of a segwit transaction uses this number again when it reaches the witness [AH].")), None),

 ("CompactSize", "CompactSize unsigned integer", 3, "InputList", ("1, 3, 5 or 9 bytes, by value", "A compactSize unsigned integer is one byte for values up to 252 and otherwise a prefix byte 0xfd, 0xfe or 0xff followed by the value as a 2-, 4- or 8-byte little-endian integer.", (PROG("def cs(n):\n    if n <= 252: return bytes([n])\n    if n <= 0xffff: return b'\\xfd' + n.to_bytes(2, 'little')\n    if n <= 0xffffffff: return b'\\xfe' + n.to_bytes(4, 'little')\n    return b'\\xff' + n.to_bytes(8, 'little')\nresult = [cs(n).hex() for n in (1, 252, 253, 65535, 65536, 2 ** 32)]"), "['01', 'fc', 'fdfd00', 'fdffff', 'fe00000100', 'ff0000000001000000']")), P(
  (W, "A compactSize unsigned integer is Bitcoin's encoding for integers that often have low values but may sometimes have high values. The book says such integers are usually encoded using the compactSize data type, which is a version of a variable-length integer sometimes called var_int or varint, as in the documentation of BIPs 37 and 144, and it gives the table: values from 0 to 252 take one byte, identical to a C uint8_t; otherwise a prefix byte indicates the length and the number follows as a regular little-endian unsigned integer [AH]."),
  (Y, "The encoding is why most of the counts and lengths in a transaction cost one byte. An input count, an output count, a script length and a witness item length are almost always below 253, so each costs a single byte, and only a rare large value pays for the prefix. The book's table lists the three larger forms: 0xfd followed by a 16-bit number for 253 to 0xffff, 0xfe followed by a 32-bit number up to 0xffffffff, and 0xff followed by a 64-bit number up to 0xffffffffffffffff, for 3, 5 and 9 bytes in all [AH]."),
  (H, "The worked example writes the encoder in four lines and runs it on six values: 1 and 252 are single bytes, 253 becomes fd followed by fd00, the largest two-byte value 65535 becomes fdffff, 65536 needs the fe prefix and four bytes, and 2 to the 32 needs ff and eight bytes. Decoding reverses the test: read one byte, and if it is 0xfd, 0xfe or 0xff read two, four or eight more. Bitcoin Core's serialize.h implements exactly this reader and writer, and the chapter's library reproduces the same bytes [BCR]."),
  (K, "The caution is in the book's warning box: several varieties of variable-length integer are used in different programs, including different Bitcoin programs. Bitcoin Core serializes its UTXO database with a type it calls VarInts, which is different from compactSize, and the nBits field in a block header uses a custom type known as Compact, which is unrelated; the book therefore always uses the full name compactSize for the integers of transaction serialization and the peer-to-peer protocol [AH]. A reader who meets varint in another document should check which one is meant.")), None),

 ("VarintVarieties", "Other variable-length integers", 3, "InputList", ("three encodings, one name that is safe", "Bitcoin programs use several variable-length integers: compactSize in transactions and the P2P protocol, Bitcoin Core's VarInts in its UTXO database, and the unrelated Compact encoding of a block header's nBits field.", ("sorted({'compactSize': 'transactions and P2P', 'VarInts': 'UTXO database', 'Compact': 'nBits in a block header'})", "['Compact', 'VarInts', 'compactSize']")), P(
  (W, "The other variable-length integers are the encodings that share a family resemblance with compactSize but are not it. The book warns that several varieties of variable length integers are used in different programs, including in different Bitcoin programs: Bitcoin Core serializes its UTXO database using a data type it calls VarInts, which is different from compactSize, and the nBits field in a Bitcoin block header is encoded using a custom data type known as Compact, which is unrelated to compactSize [AH]."),
  (Y, "The warning matters because the names collide. A developer who reads varint in one document and compactSize in another may implement the wrong one and produce bytes that no node accepts, and the error is silent until a transaction is rejected. The book resolves it by convention: when talking about the variable-length integers used in Bitcoin transaction serialization and other parts of the peer-to-peer protocol, it always uses the full name compactSize [AH]. The worked example simply lists the three encodings with where each is used."),
  (H, "The three encodings differ in mechanism, not only in name. CompactSize puts the length in a prefix byte, as the previous section shows. Bitcoin Core's VarInts use a continuation bit in each byte so that small numbers take one byte and the encoding grows by one byte at a time, a form suited to a database that stores millions of small values [BCR]. The Compact encoding of nBits is not a variable-length integer at all but a base-and-exponent representation of a 256-bit target in four bytes, which chapter 12 of the book explains under mining; it belongs to blocks, not to transactions."),
  (K, "The caution is to let the context decide the encoding rather than the word. Inside a serialized transaction, every count and every length is compactSize, without exception; inside Bitcoin Core's own files other encodings appear, and a program that reads those files needs their rules. A second caution is that the compactSize encoding is not unique in principle - 1 could be written as fd0100 - but Bitcoin Core treats a non-minimal encoding as an error, so a parser should refuse it too [BCR].")), None),

 ("OutpointField", "The outpoint", 2, "Inputs", None, P(
  (W, "The outpoint is the field with which an input points at the previous output it spends. The book explains it from the definition of a transaction: a transaction is a request for full nodes to update their database of coin ownership information, and for Alice to transfer control of some of her bitcoins she first needs to tell full nodes how to find the previous transfer where she received them; since control is assigned in transaction outputs, Alice points to the previous output using an outpoint, and each input must contain a single outpoint [AH]."),
  (Y, "The outpoint is the whole of what an input says about value. An input carries no amount; the amount is the amount of the output the outpoint names, and all of it is transferred. The book lists what a full node obtains on finding the previous output - its amount, its authorization conditions, the height and median time past of its confirming block, and proof that it exists and has not been spent - and it is from these that every later check proceeds [AH]. The rule that no output may be spent twice is a rule about outpoints: two transactions that name the same one conflict."),
  (H, "The six sections take the 36 bytes and their consequences in turn: the outpoint as a field, the 32-byte transaction identifier it begins with, the 4-byte output index that follows, the rule against double spending, the conflicting transactions that rule produces, and the database of unspent outputs that Bitcoin Core keeps so that the lookup is fast and the rule can be enforced [AH].")), None),

 ("Outpoint", "Outpoint", 3, "OutpointField", ("36 bytes: a txid and an index", "An outpoint is the 32-byte txid of a previous transaction followed by the 4-byte index of one of its outputs; every input has exactly one, and a node uses it to find the output being spent.", (PROG("tx = bytes.fromhex('01000000000101eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a0100000000ffffffff02204e0000000000002251203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068f8240100000000001600147752c165ea7be772b2c0acb7f4d6047ae6f4768e0141cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e817130100000000')\noutpoint = tx[7:43]\nresult = (outpoint[:32][::-1].hex(), int.from_bytes(outpoint[32:], 'little'))"), "('4ac541802679866935a19d4f40728bb89204d0cac90d85f3a51a19278fe33aeb', 1)")), P(
  (W, "An outpoint is the field of an input that points at the output being spent. The book says that since control over bitcoins is assigned in transaction outputs, Alice points to the previous output using an outpoint field, that each input must contain a single outpoint, and that the outpoint contains a 32-byte txid for the transaction where Alice received the bitcoins she now wants to spend, followed by the output index [AH]. The name is a contraction: a point to an output."),
  (Y, "The outpoint is what makes the ownership record a chain. Chapter 2 drew Alice's payment as a link in a chain of transactions, each spending an output of an earlier one [AH2]; the outpoint is that link written as bytes. Because the identifier is a hash of the previous transaction, an outpoint commits to the whole of the transaction it names, and because the index chooses one output, two inputs that name the same outpoint claim the same bitcoins, which is the double-spending situation the later section describes [AH]."),
  (H, "The worked example cuts the 36 bytes at offset 7 of Alice's transaction - after the version, the marker, the flag and the input count - and reads them as the transaction identifier, which it reverses into display order, and the index 1. A full node that encounters an outpoint uses the information to find the referenced output, and the book notes that it is only required to look at earlier transactions in the blockchain: within the block that contains the spending transaction, only at transactions placed before it, as determined by the order of leaves in the block's merkle tree [AH]. The explorer that this course consulted reports the same identifier and index for Alice's input [MP]."),
  (K, "The caution is that the identifier in the outpoint is written in Bitcoin's internal byte order, so the 32 bytes read directly do not match what an explorer displays; the byte-order group explains the reversal, which the worked example performs. A second caution is that an outpoint names an output, not a transaction: the previous transaction in Alice's chain had two outputs, and the index 1 chooses the second of them, the one of 100,000 satoshis that chapter 2 followed [AH] [MP].")), None),

 ("PreviousTxid", "The previous transaction's identifier", 3, "OutpointField", ("the first 32 bytes of an outpoint", "The txid in an outpoint is the 32-byte double-SHA-256 identifier of the transaction that created the output being spent, stored in internal byte order.", (PROG("prev = bytes.fromhex('eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a')\nresult = (len(prev), prev[::-1].hex()[:16])"), "(32, '4ac5418026798669')")), P(
  (W, "The previous transaction's identifier is the first part of an outpoint: the book says the outpoint contains a 32-byte txid for the transaction where Alice received the bitcoins she now wants to spend, and that this txid is in Bitcoin's internal byte order for hashes [AH]. A txid is a digest, the output of a hash function run over the transaction's serialization; chapter 4 introduced hash functions and the double application of SHA-256 that Bitcoin uses for its identifiers, and the foundations group of this chapter returns to how a txid is computed."),
  (Y, "The identifier is what ties the input to exactly one earlier transaction. Because it is a hash of that transaction's bytes, no other transaction has it, and a change of a single byte in the earlier transaction would change it entirely - which is the property that makes malleability dangerous, as the witness branch explains: if the earlier transaction's identifier can change, every outpoint that names it breaks [AH]. In the book's example the identifier is eb3ae38f... in the bytes, which displays as 4ac54180..., the transaction that paid Alice in block 774,958 [AH] [MP]."),
  (H, "The worked example takes the 32 bytes as they stand in the outpoint, confirms their length, and reverses them to obtain the first sixteen hexadecimal characters of the display form. A full node uses the internal form as a key into its database of unspent outputs; a user uses the display form in an explorer or a command line, and the book's own demonstration of asking Bitcoin Core for the internal form and receiving an error is reproduced in the byte-order group [AH]."),
  (K, "The caution is the one the book makes its sidebar about: the same 32 bytes have two spellings, and a program that mixes them looks up a transaction that does not exist. The second caution is that a transaction identifier only commits to the legacy serialization, so for a segwit transaction the signature that authorises the spend is not part of what the identifier covers; that is deliberate and is the subject of the witness branch [B141].")), None),

 ("OutputIndex", "Output index", 3, "OutpointField", ("four bytes counting from zero", "The output index is the 4-byte unsigned integer after the txid in an outpoint; it chooses one output of the previous transaction, counting from zero.", ("int.from_bytes(bytes.fromhex('01000000'), 'little')", "1")), P(
  (W, "The output index is the second part of an outpoint. The book explains that because transactions may contain multiple outputs, Alice also needs to identify which particular output from that transaction to use, called its output index, and that output indexes are 4-byte unsigned integers starting from zero [AH]. In Alice's transaction the index bytes are 01000000, which the worked example reads as 1, the second output of the previous transaction."),
  (Y, "The index is why an outpoint identifies an output rather than a transaction. Most transactions have at least two outputs, a payment and change, and the one being spent must be named exactly; naming the transaction alone would be ambiguous and would let a spender claim both. The previous transaction in Alice's chain has two outputs, 18,210,494 satoshis at index 0 and 100,000 satoshis at index 1, and her outpoint chooses the second [MP]."),
  (H, "The field is a fixed four bytes in little-endian order, so the value 1 is written as 01 followed by three zero bytes, and the largest possible index is 0xffffffff. That maximal value has a special use: the coinbase transaction of every block, which creates bitcoins rather than spending an output, sets its single outpoint to a null txid and this maximal index, as the coinbase group explains [AH]. For every ordinary input, the index must be smaller than the number of outputs of the referenced transaction, or the output does not exist and the node rejects the transaction."),
  (K, "The caution is that indexes start at zero, so the first output is output 0 and the book's phrase second output means index 1. A reader counting from one will spend the wrong output, and an explorer that labels outputs from zero and a wallet that labels them from one can describe the same outpoint with different numbers.")), None),

 ("DoubleSpendRule", "The rule against double spending", 3, "OutpointField", ("an output is spent at most once", "One of Bitcoin's consensus rules forbids any output from being spent more than once within a valid blockchain: Alice cannot use the same previous output to pay both Bob and Carol.", ("(lambda spent, outpoint: 'refused: already spent' if outpoint in spent else 'accepted')({'4ac54180:1'}, '4ac54180:1')", "'refused: already spent'")), P(
  (W, "The rule against double spending is the consensus rule that forbids any output from being spent more than once within a valid blockchain. The book states it among the things a full node obtains from the previous output - proof that it exists and that no other transaction has spent it - and gives the example: Alice cannot use the same previous output to pay both Bob and Carol in separate transactions [AH]. Chapter 2 introduced the problem that this rule solves; this chapter shows where in the data the rule is checked."),
  (Y, "The rule is the reason the outpoint is enough. Because each output can be spent once, the outpoint names a fixed quantity of bitcoins that the spending transaction takes in full, and the node can delete the output from its record after the spend. Without the rule, Bitcoin would be a copyable file rather than a scarce record, which is the problem chapter 1 called the copy problem. The rule is also why conflicting transactions exist as a category: a second transaction naming the same outpoint is not wrong in form, it is simply the one that lost [AH]."),
  (H, "A node enforces the rule by lookup rather than by search. The worked example models the simplest form: a set of spent outpoints, and a refusal when the new outpoint is already in it. Bitcoin Core does the converse, keeping the set of unspent outputs and refusing an outpoint that is not in it, and its CheckTransaction additionally refuses a transaction that names the same outpoint twice among its own inputs, with the error bad-txns-inputs-duplicate; the source comment records that this check guards against a crash or an inflation bug depending on the database [BCT]."),
  (K, "The caution is in the words within a valid blockchain. Two conflicting transactions can both exist in the network at once, and both may be relayed for a time; the rule only says that a chain of blocks containing both is invalid, so one of them, and only one, will ever be confirmed. The second caution is that the rule says nothing about which one, which is the gap that the sequence branch's replacement policies and the witness branch's malleability problems both live in [AH].")), None),

 ("ConflictingTransactions", "Conflicting transactions", 3, "OutpointField", ("same outpoint, two spenders", "Two transactions that each try to spend the same previous output are conflicting transactions; only one of them can be included in a valid blockchain.", ("(lambda a, b: 'conflict' if set(a) & set(b) else 'compatible')(['4ac54180:1'], ['4ac54180:1', 'f4184fc5:0'])", "'conflict'")), P(
  (W, "Conflicting transactions are two transactions that each try to spend the same previous output. The book defines them in the sentence after the double-spending rule and gives their property: they are called conflicting because only one of them can be included in a valid blockchain [AH]. The worked example tests two input lists for a shared outpoint and reports the conflict."),
  (Y, "The category matters because conflicts are not always attacks. The book's own examples in the sequence branch are deliberate: Alice and Bob sign many versions of one transaction, each spending the same output, and intend only the last to confirm; replace-by-fee is a conflict a sender creates on purpose to raise a fee; and the malleability problems of the witness branch are conflicts created by a third party or a counterparty against the sender's wish [AH]. The same data structure covers all of them, and what differs is who created the conflict and why."),
  (H, "A conflict is detected by comparing outpoints. Two transactions conflict if any input of one names an outpoint that any input of the other names, which is what the worked example's set intersection does. A full node that already holds one unconfirmed transaction and receives a conflicting one must choose: the original Bitcoin software chose by sequence number, later software refused the second one, and current software applies replace-by-fee rules, all of which the sequence branch describes [AH] [B125]. Once one of them is in a block, the choice is made for everyone."),
  (K, "The caution is that a conflicting transaction can have a different identifier while spending the same money, so a payee who watches for a specific txid can miss the payment that actually confirmed. The book's malleability example is exactly this: a mutated copy of Alice's transaction confirms, her original cannot, and Bob's transaction that spent her original output becomes invalid even though nobody acted wrongly [AH]. Watching outpoints rather than identifiers is the defence.")), None),

 ("UtxoDatabase", "The UTXO database", 3, "OutpointField", ("remove what is spent, add what is created", "Bitcoin Core keeps a database of every unspent transaction output with essential metadata; each new block removes the outputs its transactions spend and adds the outputs they create.", (PROG("utxo = {'4ac54180:0': 18210494, '4ac54180:1': 100000}\nutxo.pop('4ac54180:1')                     # Alice's input spends it\nutxo['46620030:0'] = 20000                 # Bob's output\nutxo['46620030:1'] = 75000                 # Alice's change\nresult = sorted(utxo.items())"), "[('46620030:0', 20000), ('46620030:1', 75000), ('4ac54180:0', 18210494)]")), P(
  (W, "The UTXO database is the record Bitcoin Core keeps of every unspent transaction output. The book says that different approaches to tracking previous outputs have been tried by different full node implementations, and that Bitcoin Core currently uses the solution believed most effective at retaining all necessary information while minimising disk space: a database that stores every UTXO and essential metadata about it, such as its confirmation block height; each time a new block arrives, all the outputs its transactions spend are removed and all the outputs they create are added [AH]."),
  (Y, "The database is what turns the double-spending rule from a search into a lookup. Without it, a node checking an outpoint would have to scan the whole blockchain to find the output and then scan again to be sure nothing spent it; with it, the node asks one question of one table. The metadata is what makes the other checks possible: the height is needed for the maturity rule of coinbase outputs and for relative timelocks, which the book names as the reason a node records it [AH]. The database is also the reason uneconomical outputs are a public cost, since every entry must be kept by every node, a point the outputs branch takes up."),
  (H, "The worked example runs one update by hand: starting from the two outputs of the transaction that paid Alice, it removes the one her input spends and adds the two her transaction creates, Bob's 20,000 satoshis and her change of 75,000, leaving three entries. A real node does this for every transaction of every block in order, and the book notes that the database is a few gigabytes - it mentions over five gigabytes as of its writing - which a later proposal called Utreexo hopes to replace with a commitment of a kilobyte or two for most nodes [AH] [MP]."),
  (K, "The caution is that the database is a consequence of the blockchain, not a part of it. It can be rebuilt from the blocks and it is not transmitted between nodes; two nodes that have processed the same blocks hold the same set, but neither trusts the other's copy. A second caution is that a UTXO is identified by an outpoint, not by an address, so the database can hold many entries for one address and the balance a wallet shows is a sum the wallet computes, not a value the node stores.")), None),

 ("ByteOrder", "Internal and display byte order", 2, "Inputs", None, P(
  (W, "This group explains the book's sidebar on the two byte orders of a hash. The book says Bitcoin uses the output of hash functions, called digests, in various ways - as identifiers for blocks and transactions, in commitments, and in proof of work - and that in some cases digests are displayed to users in one byte order but used internally in a different byte order, creating confusion [AH]. It names the two: internal byte order for data within transactions and blocks, display byte order for the form shown to users."),
  (Y, "The confusion is real and the book demonstrates it: asked for the transaction whose identifier appears in Alice's outpoint, Bitcoin Core replies that there is no such transaction, and only after the bytes are reversed does it return the transaction [AH]. The book calls the behaviour probably an unintentional consequence of a design decision in early Bitcoin software and draws the practical lesson that developers need to remember to reverse the order of bytes in transaction and block identifiers they show to users [AH]."),
  (H, "The three sections explain the digest itself, the internal order in which a digest is stored and hashed, and the display order in which it is printed, with the book's own shell pipeline - fold, tac, tr - recomputed in Python so that the reversal can be checked. The alternative names the book gives, little-endian for the internal and big-endian for the display form, are explained in the display section [AH].")), None),

 ("Digest", "Digest", 3, "ByteOrder", ("32 bytes that identify a transaction", "A digest is the output of a hash function; Bitcoin uses digests as identifiers of blocks and transactions, in commitments, and in proof of work.", ("len(__import__('hashlib').sha256(__import__('hashlib').sha256(b'a serialized transaction').digest()).digest())", "32")), P(
  (W, "A digest is the output of a hash function. The book's sidebar says Bitcoin uses digests in various ways: they provide unique identifiers for blocks and transactions, they are used in commitments for addresses, blocks, transactions, signatures and more, and they are iterated upon in Bitcoin's proof-of-work function [AH]. Chapter 4 introduced the hash function as a one-way function with a fixed-length output; here the output has a name because its byte order is about to matter."),
  (Y, "Digests are the glue of the data structures in this chapter. A transaction identifier is a digest of the transaction, an outpoint carries that digest, and a block commits to its transactions through a tree of digests, so the same 32 bytes travel from the hash function into an outpoint and onto a user's screen. The book's warning is that those bytes are shown in one order and used in another, and a digest is the thing that is reversed [AH]."),
  (H, "The worked example computes the double SHA-256 of a short byte string and reports its length, 32 bytes, which is the length of every transaction and block identifier. Bitcoin applies SHA-256 twice for these identifiers, a construction the foundations group explains; the first application gives 32 bytes and the second gives 32 bytes again, so the length does not depend on the input. Any change to the input changes the digest unpredictably, which is why a digest can serve as a commitment: showing the digest first and the data later proves the data was fixed in advance."),
  (K, "The caution is that a digest is a value, not a text, and the same value has two hexadecimal spellings in Bitcoin, which the next two sections explain. A second caution is that the uniqueness of a digest as an identifier is practical rather than absolute: two different transactions with the same identifier are astronomically unlikely but not impossible in principle, and BIP30 exists because two early coinbase transactions were in fact identical and therefore had identical identifiers [B30].")), None),

 ("InternalByteOrder", "Internal byte order", 3, "ByteOrder", ("the order inside the bytes", "Internal byte order is the order in which a digest's bytes appear within transactions and blocks and are fed to hash functions; the book also calls it little-endian.", ("bytes.fromhex('4ac541802679866935a19d4f40728bb89204d0cac90d85f3a51a19278fe33aeb')[::-1].hex()", "'eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a'")), P(
  (W, "Internal byte order is the book's term for the data as it appears within transactions and blocks. The book introduces the term in its sidebar, after the demonstration that the identifier in Alice's outpoint has to be reversed before Bitcoin Core recognises it, and offers the alternative pair of names: little-endian byte order for the internal version and big-endian byte order for the display version [AH]. The 32 bytes of an outpoint's txid are in internal order."),
  (Y, "The order matters because it is the one the hash function sees. A node computing a block's merkle tree, a transaction's identifier or the previous-block link of a header hashes digests in internal order, so a program that reversed them would compute different digests and reject valid blocks. The book calls the split probably an unintentional consequence of a design decision in early Bitcoin software, which stored 256-bit numbers as little-endian integers and printed them as numbers, with the most significant byte first [AH]."),
  (H, "The worked example takes the display form of the identifier of the transaction that paid Alice and reverses its bytes to obtain the internal form, eb3ae38f..., which is exactly what the outpoint of her transaction contains. Reversal is its own inverse, so the same operation converts in either direction; the chapter's library names both directions for readability but implements one function. The explorer that this course consulted shows the display form, and the byte at offset 7 of Alice's transaction is eb, the first byte of the internal form [MP]."),
  (K, "The caution is to reverse digests and nothing else. The little-endian integers of a transaction - version, amount, index, sequence, lock time - are also stored least significant byte first, but they are read as numbers, not reversed as strings; a reader who reverses a 4-byte sequence as if it were a digest gets a wrong value. Only the 32-byte identifiers have the two spellings the book describes.")), None),

 ("DisplayByteOrder", "Display byte order", 3, "ByteOrder", ("the order on the screen", "Display byte order is the reversed form in which identifiers are shown to users and accepted by explorers and bitcoin-cli; the book also calls it big-endian.", (PROG("internal = 'eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a'\npairs = [internal[i:i + 2] for i in range(0, 64, 2)]   # fold -w2\nresult = ''.join(reversed(pairs))                       # tac | tr -d newline"), "'4ac541802679866935a19d4f40728bb89204d0cac90d85f3a51a19278fe33aeb'")), P(
  (W, "Display byte order is the book's term for the form of a digest displayed to users. The sidebar shows the need for it: asking Bitcoin Core for the identifier as it appears in the outpoint returns the error no such mempool or blockchain transaction, and the book then reverses the bytes with a shell pipeline - echo the hex, fold it into two-character pairs, reverse the lines with tac, delete the newlines - and the reversed identifier returns the transaction [AH]."),
  (Y, "The display form is the one every user handles: it is what an explorer prints, what a wallet shows as a transaction identifier, what bitcoin-cli accepts, and what this chapter writes when it names a transaction. The book draws the practical consequence for developers, who need to remember to reverse the order of bytes in transaction and block identifiers they show to users, and it fixes its own vocabulary so that the two forms can be named without ambiguity [AH]."),
  (H, "The worked example performs the book's pipeline in Python: the internal form is cut into 32 two-character pairs, the pairs are reversed, and the result is the display form 4ac54180..., which the explorer confirms as the identifier of the transaction that paid Alice [MP]. The book notes that another common pair of terms is little-endian for the internal and big-endian for the display version, from the two conventions for writing a multi-byte number; the display form reads like a number with its most significant byte first [AH]."),
  (K, "The caution is the one that produced the book's error message: a display-order identifier pasted into a field that expects internal order, or the reverse, names a transaction that does not exist, and the failure is a not-found rather than a format error. A second caution is that block identifiers follow the same convention, and the leading zeros that a user sees at the start of a block hash are, in internal order, trailing zeros - which is why the proof-of-work target is said to require leading zeros in display order.")), None),

 ("InputScriptField", "The input script", 2, "Inputs", None, P(
  (W, "The input script is the second field of every input, after the outpoint and before the sequence, and it is length-prefixed. The book calls the field a remnant of the legacy transaction format: Alice's example input spends a native segwit output that does not require any data in the input script, so the length prefix for her input script is zero, and the book takes an input script from a legacy transaction in the most recent block as of its writing to show what a filled one looks like [AH]."),
  (Y, "The field matters for what it used to hold and for why it is now often empty. In the legacy format signatures and other data are placed in the input script, so it is where a legacy transaction proves it is authorised; and because that data was included in the hash that makes a txid, it is where the malleability problems of the witness branch arose. Segregated witness moved that data out of the field, which is why a modern input often carries only a zero length byte [AH]."),
  (H, "The two sections cover the field and its prefix. The input script section explains what a legacy input script contains, using the book's 107-byte example of a signature followed by a public key, and why Alice's is empty; the length prefix section explains the compactSize byte that precedes the script, which is 0x6b for the book's example and 0x00 for Alice's, and why a parser cannot find the sequence without it [AH].")), None),

 ("InputScript", "Input script", 3, "InputScriptField", ("107 bytes for a legacy spend, 0 for segwit", "The input script is the legacy field in which a spending transaction places its signatures and other authorising data; a segwit input leaves it empty.", (PROG("legacy = bytes.fromhex('483045022100a6cc4e8cd0847951a71fad3bc9b14f24d44ba59d19094e0a8cfa2580bb664b020220366060ea8203d766722ed0a02d1599b99d3c95b97dab8e41d3e4d3fe33a5706201210369e03e2c91f0badec46c9c903d9e9edae67c167b9ef9b550356ee791c9a40896')\nsig_len = legacy[0]                       # 0x48: a 72-byte signature follows\npub_len = legacy[1 + sig_len]             # 0x21: a 33-byte public key follows\nresult = (len(legacy), sig_len, pub_len, 1 + sig_len + 1 + pub_len)"), "(107, 72, 33, 107)")), P(
  (W, "The input script is the field of an input that, in the legacy format, carries the signatures and other data that authorise the spend. The book says the field is a remnant of the legacy transaction format: Alice's example input spends a native segwit output that does not require any data in the input script, so its length prefix is set to zero, and for an example of a length-prefixed input script that spends a legacy output the book takes one from an arbitrary transaction in the most recent block as of its writing, a script of 107 bytes [AH]."),
  (Y, "The field is where authorisation lived before segregated witness and the reason it moved. Chapter 4 explained that spending requires a signature made with the private key matching the public key an output names; in a legacy transaction that signature and that public key are pushed onto the stack by the input script, and the output script checks them. Because the input script is part of the bytes a txid is computed over, anyone who could rewrite it without invalidating the signature could change the txid, which is the third-party malleability of the witness branch; an empty input script is immune [AH]."),
  (H, "The worked example parses the book's 107-byte legacy input script by its own structure: the first byte, 0x48, is a push of 72 bytes, the signature; the byte after the signature, 0x21, is a push of 33 bytes, the compressed public key; and one plus 72 plus one plus 33 is 107, the whole script. The push opcodes are met again in the malleability section, where the same number can be pushed in several ways. The book defers parsing and using scripts to the next chapter; here it is enough to see that the field is data for a stack machine, and that Alice's transaction has none of it [AH]."),
  (K, "The caution is that an empty input script does not mean an unauthorised spend. Alice's transaction is authorised by the 65-byte signature in its witness structure, which the witness branch reads; the input script is empty because the output she spends is a segwit output, and the book says that for such outputs new nodes require the input script to be empty while old nodes merely allow it [AH]. A second caution is that the 107-byte example is not from Alice's transaction and its signature cannot be checked here, since the output it spends is not in the chapter.")), None),

 ("LengthPrefix", "Script length prefix", 3, "InputScriptField", ("0x6b says 107 bytes follow", "The length prefix is the compactSize integer before an input script that says how many bytes of script follow; it is 0x6b for the book's 107-byte example and 0x00 for Alice's empty script.", ("(0x6b, int.from_bytes(bytes.fromhex('6b'), 'little') == 107, 0x00)", "(107, True, 0)")), P(
  (W, "The length prefix is the compactSize unsigned integer that precedes an input script and gives its length in bytes. The book explains it on its legacy example: the prefix is a single byte, 0x6b, indicating that the input script is 107 bytes, and on Alice's transaction, where the prefix is zero because a native segwit input needs no input script [AH]. The same kind of prefix precedes every output script and every witness item in the chapter."),
  (Y, "The prefix is what makes a variable field parseable. An input script has no terminator and may contain any bytes, so the only way a parser can know where the script ends and the sequence begins is to be told the length first; a wrong prefix shifts every later field and corrupts the whole transaction. The prefix is also counted in the transaction's size and weight - the book's weight table charges Alice's empty input script four weight units, which are the four-times-weighted single byte of its prefix [AH]."),
  (H, "The worked example shows the arithmetic the book states: 0x6b is 107, and reading the byte as a little-endian integer gives the same; Alice's prefix is 0x00. Because the prefix is compactSize, a script longer than 252 bytes would need the 0xfd form with two further bytes, which happens for some multisignature input scripts. Bitcoin Core's relay policy caps a standard input script at 1,650 bytes, a limit its policy header names MAX_STANDARD_SCRIPTSIG_SIZE, while consensus allows up to the script size limit of 10,000 bytes [BCP] [BCS]."),
  (K, "The caution is that the prefix counts bytes of script, not elements of it: the book's example holds two pushes, a signature and a public key, but the prefix says 107, the total length, and a parser learns the structure inside only by executing the script's push opcodes. A second caution is that the prefix is present even when the script is empty, as Alice's transaction shows; the field is never omitted, only its content.")), None),
]

CHECKS_C = [
 Qb("ch06_transactions.adoc", "The minimum value is one.", "effectively limit transactions to a few thousand inputs", "encoded as a compactSize unsigned integer"),
 Qb("ch06_transactions.adoc", "Bitcoin Core serializes its UTXO database using a data type it", "calls +VarInts+, which is different from compactSize", "known as +Compact+, which is unrelated to compactSize"),
 Qb("ch06_transactions.adoc", "Each input must", "contain a single outpoint.", "The outpoint contains a 32-byte txid"),
 Qb("ch06_transactions.adoc", "Output indexes are 4-byte unsigned", "integers starting from zero."),
 Qb("ch06_transactions.adoc", "Alice's transaction is", "included in block 774,958."),
 Qb("ch06_transactions.adoc", "the value of the previous output was 100,000 satoshis"),
 Qb("ch06_transactions.adoc", "Alice can't use the same previous output to pay", "both Bob and Carol in separate transactions", "called _conflicting transactions_"),
 Qb("ch06_transactions.adoc", "error code: -5", "No such mempool or blockchain transaction.", "| fold -w2 | tac | tr -d"),
 Qb("ch06_transactions.adoc", "_little-endian byte order_ for the internal version and _big-endian byte", "order_ for the display version"),
 Qb("ch06_transactions.adoc", "byte (0x6b) indicating the input script is 107 bytes"),
 Qb("ch06_transactions.adoc", "compare that to the over five gigabytes Bitcoin Core stores", "as of this writing"),
 Qc("src/consensus/tx_check.cpp", "bad-txns-vin-empty", "bad-txns-inputs-duplicate", "Failure to run this check will result in either a crash or an inflation bug"),
 Qc("src/policy/policy.h", "MAX_STANDARD_SCRIPTSIG_SIZE{1650}"),
 Qc("src/script/script.h", "MAX_SCRIPT_SIZE{10'000}"),
 Qe("bip-0030.mediawiki", "Duplicate transactions"),
 # the compactSize table, executed
 X("[T.cs_encode(n).hex() for n in (0, 252, 253, 0xffff, 0x10000, 0xffffffff, 0x100000000)]", ['00', 'fc', 'fdfd00', 'fdffff', 'fe00000100', 'feffffffff', 'ff0000000001000000']),
 X("[len(T.cs_encode(n)) for n in (252, 253, 0x10000, 0x100000000)]", [1, 3, 5, 9]),
 X("[T.cs_decode(T.cs_encode(n))[0] == n for n in (0, 252, 253, 65535, 65536, 2 ** 32, 2 ** 64 - 1)]", [True] * 7),
 # Alice's input: outpoint, empty script, sequence; the previous transaction's outputs
 X("(lambda i: (i['txid'], i['txid_internal'], i['vout'], i['script'], i['sequence']))(T.parse_tx(%r)['inputs'][0])" % ALICE, (PREV_DISPLAY, PREV_INTERNAL, 1, '', 0xffffffff)),
 X("[(o['value'], len(bytes.fromhex(o['script']))) for o in T.parse_tx(C.ev_hex('tx_alice_prev_4ac54180_v1_0_0.hex'))['outputs']]", [(18210494, 22), (100000, 34)]),
 X("T.txid(C.ev_hex('tx_alice_prev_4ac54180_v1_0_0.hex'))", repr(PREV_DISPLAY)),
 X("T.internal_to_display(%r)" % PREV_INTERNAL, repr(PREV_DISPLAY)),
 X("T.display_to_internal(%r)" % PREV_DISPLAY, repr(PREV_INTERNAL)),
 # the block heights: the previous transaction is in 774,958, Alice's own in 775,072 (two explorers agree)
 X("(C.ev_json('mempool_tx_4ac5418026798669_v1_0_0.json')['status']['block_height'], C.ev_json('mempool_tx_466200308696215b_v1_0_0.json')['status']['block_height'])", (774958, 775072)),
 X("C.ev_json('mempool_tx_466200308696215b_v1_0_0.json')['vin'][0]['prevout']['value']", 100000),
 # the pizza transaction: 131 inputs, one byte of count
 X("(len(T.parse_tx(C.ev_hex('tx_pizza_a1075db5_v1_0_0.hex'))['inputs']), bytes.fromhex(C.ev_hex('tx_pizza_a1075db5_v1_0_0.hex'))[4], len(C.ev_json('mempool_tx_a1075db55d416d3c_v1_0_0.json')['vin']))", (131, 0x83, 131)),
 # the legacy input script of the book, after its prefix
 X("(len(bytes.fromhex(%r)), bytes.fromhex(%r)[0], bytes.fromhex(%r)[73])" % (LEGACY_INPUT_SCRIPT, LEGACY_INPUT_SCRIPT, LEGACY_INPUT_SCRIPT), (107, 0x48, 0x21)),
 X("T.is_coinbase(T.parse_tx(C.ev_hex('tx_first_f4184fc5_v1_0_0.hex')))", False),
 ("(0x6b, 0x83, 0xfd, 0xfe, 0xff)", "(107, 131, 253, 254, 255)"),
 ("(41, 41 * 1000 * 4 <= 4000000, 4000000 // 4 // 41)", "(41, True, 24390)"),
 ("len(__import__('hashlib').sha256(b'').digest())", "32"),
]
