# Non-Apply items of the chapter 2 question bank, part A: the Transaction branch.
# Each row is (concept, level, question, correct option, [three wrong options], one-sentence reason).
# The generator places the correct option at a rotating index so the four answer positions stay balanced.
TEXT_A = [
 ("Transaction", "Remember", "What does a transaction tell the Bitcoin network?",
  "That the owner of certain bitcoins has authorized the transfer of that value to another owner",
  ["That a bank or a payment processor has cleared a payment between two account holders and will settle it with the other participants overnight",
   "That a miner has agreed to include a payment in the next block",
   "That a wallet has moved a coin file from one computer to another"],
  "The chapter opens its account of transactions with exactly this sentence."),
 ("TransactionPart", "Understand", "Why does reading a transaction correctly depend on knowing which part does which job?",
  "Because an input says what is being spent, an output what is created, and the fee is whatever remains",
  ["Because the parts of a transaction are written in a different order by every wallet, so a reader has to work out from the amounts which part is which",
   "Because only the fee is signed, so the other parts can be changed later",
   "Because the inputs and outputs must always add up to exactly the same amount"],
  "Confusing the parts leads to the belief that a payment is one amount sent from one address to another."),
 ("DoubleEntryLedger", "Analyze", "Where does the bookkeeping analogy stop describing a Bitcoin transaction?",
  "A ledger names accounts and their owners, while a transaction names earlier outputs and spending conditions",
  ["A ledger is written by hand, while a transaction is written by a computer",
   "A ledger balances exactly, and so do a transaction's two sides once the fee is counted",
   "A ledger records amounts, while a transaction records only addresses"],
  "The transaction data has no field for an owner or for a running balance; a wallet computes a balance itself."),
 ("Input", "Understand", "Why do inputs turn separate transactions into a connected history?",
  "Because every input names the earlier output it consumes, so a payment can be followed backward",
  ["Because every input carries the date on which the earlier transaction was confirmed",
   "Because inputs are numbered consecutively across the whole blockchain",
   "Because an input repeats the amount of the output it spends, so the chain can be summed"],
  "The reference also lets anyone see whether the same output is being spent twice."),
 ("Output", "Analyze", "Why can outputs of very small value become a problem?",
  "They can be uneconomical to spend and still burden every node that must track them",
  ["They are deleted by the network after a fixed number of blocks",
   "They cannot be spent at all, because the protocol forbids amounts below one satoshi",
   "They are counted twice in the fee, so spending them costs double"],
  "An output never expires: it stays in every full node's database until a valid transaction spends it."),
 ("TransactionFee", "Understand", "Why is a transaction fee more like a bid in an auction than a price?",
  "Because the good being bought is the limited space in a block, not a service with a fixed price",
  ["Because miners publish a price list and users accept or reject it",
   "Because the fee is set by the protocol and rises with the amount being sent",
   "Because the fee is returned to the sender if the transaction is not mined"],
  "The chapter on fees says it is not a fee in the usual sense but much more like a bid for block space."),
 ("TransactionSize", "Analyze", "Why do the three size figures of a transaction answer different questions?",
  "The byte size is the serialized length, the weight is what the block limit counts, and the vbyte is the weight in a familiar unit",
  ["The byte size is the figure that wallets display, the weight is the figure that block explorers index, and the virtual byte is reserved for the fee estimates that miners publish",
   "The three are the same number written in three notations, so any one of them can be used",
   "The byte size includes the witness, the weight excludes it and the vbyte averages the two"],
  "Mixing them up is a common reason for fee figures that do not match between two tools."),
 ("FeeRate", "Understand", "Why does a miner compare transactions by fee rate rather than by total fee?",
  "Because a larger transaction leaves room for fewer others, so revenue depends on fee per unit of space",
  ["Because the consensus rules forbid a block from including two transactions whose total fees are equal, so miners have to rank them by a ratio instead",
   "Because the fee rate is the only figure stated inside the transaction",
   "Because the total fee is unknown until the block has been mined"],
  "The chapter says transactions are added to a block prioritized by the highest fee rate first."),
 ("UnspentOutput", "Analyze", "Why is a wallet's balance not simply a number stored somewhere?",
  "Because the balance is the sum of the separate unspent outputs the wallet's keys can spend",
  ["Because balances are kept only by the block explorers and never by a wallet, so a wallet has to ask an explorer before it can show a figure",
   "Because the balance is recomputed by the miners at every block",
   "Because a balance exists only after six confirmations have passed"],
  "An unspent output is not an account balance, and each one is spent whole."),
 ("TransactionIdentifier", "Analyze", "Why can pasting a transaction identifier from one tool into another find nothing?",
  "Because a hash is displayed in one byte order and stored in another, so the two printings differ",
  ["Because an identifier expires once its transaction has six confirmations, after which explorers index the payment by the address that received it",
   "Because explorers index only transactions that paid above a minimum fee",
   "Because the identifier changes every time the transaction is relayed"],
  "The book warns that hash digests are displayed to users in one byte order and used internally in another."),
 ("Cryptography", "Understand", "What question should a learner keep in mind while reading this group of concepts?",
  "What exactly does this tool guarantee, and what does it leave open",
  ["Which of these tools makes a transaction secret from other users",
   "Which of these tools is fastest to compute on a telephone",
   "Which of these tools the protocol allows a user to replace"],
  "The tools differ sharply in what they promise, and none of them is encryption."),
 ("HashFunction", "Analyze", "Why is the promise about collisions a statement about effort rather than an impossibility?",
  "Because a fixed-length output must map many inputs to the same value, so pairs exist but are infeasible to find",
  ["Because the function can be inverted whenever enough memory is available to store every digest it has ever produced for a short input",
   "Because collisions are prevented by the length of the input",
   "Because two equal inputs sometimes give different outputs"],
  "The book calls such a pair a collision and says that finding one is computationally infeasible."),
 ("KeyPair", "Remember", "What happens when a private key is revealed to a third party?",
  "It is equivalent to giving them control over the bitcoins that key secures",
  ["It is safe for as long as the matching public key is kept secret, because a signature can only be checked by somebody who holds both halves",
   "It only allows them to read the transactions, not to spend",
   "It can be undone by generating a new public key from the same private key"],
  "Control over the private key is the root of user control over all funds associated with the public key."),
 ("PublicKeyCryptography", "Understand", "What is public-key cryptography used for in Bitcoin?",
  "To generate digital signatures, not to encrypt transactions",
  ["To encrypt each payment so that only the receiver can read it",
   "To compress the blockchain so that nodes need less disk space",
   "To agree a shared secret between the payer's and the payee's wallets"],
  "The book says plainly that it is not used to make the transactions secret."),
 ("EllipticCurve", "Analyze", "Why is the smooth curve drawn in textbooks misleading for Bitcoin?",
  "Because the arithmetic is done modulo a large prime, so the curve is a cloud of points in a huge grid",
  ["Because Bitcoin uses a different equation from the one in the pictures",
   "Because the curve is only an analogy and no multiplication is actually performed",
   "Because the picture shows the public key rather than the private one"],
  "The geometric rule of tangents and reflections is an analogy for the algebra that is really computed."),
 ("DigitalSignature", "Remember", "Which three purposes does a digital signature serve?",
  "It proves authorization, it cannot be denied afterwards, and the transaction cannot be changed by others",
  ["It hides the amount being transferred, identifies the payer by name and fixes the fee that the miner of the block will be allowed to collect",
   "It compresses the transaction, proves its age and names the miner",
   "It encrypts the output, authorizes the fee and fixes the exchange rate"],
  "The chapter on signatures lists authorization, nonrepudiation and integrity."),
 ("Checksum", "Analyze", "Why does a checksum not protect an address against a malicious change?",
  "Because an adversary who changes the data can simply compute a new matching checksum",
  ["Because the checksum of an address is only four characters long, so an adversary can try every possible value until one of them matches the data",
   "Because wallets ignore the checksum when an amount is given",
   "Because the checksum is computed over the amount and not over the address"],
  "A checksum detects accidents; protecting against deliberate substitution needs a signature."),
 ("BitsAndBytes", "Analyze", "Why is the block limit quoted as a weight of 4,000,000 rather than in megabytes?",
  "Because the prefix mega is ambiguous, while a count of units is exact",
  ["Because weight units are eight times larger than bytes",
   "Because megabytes are reserved for disk space and not for blocks",
   "Because the limit changes with every difficulty retarget"],
  "A kilobyte may mean 1,000 or 1,024 bytes depending on the author, so an exact count avoids the question."),
 ("HexadecimalNotation", "Understand", "Why is hexadecimal the usual way to print binary data for human eyes?",
  "Because one digit stands for four bits, so two digits are exactly one byte",
  ["Because it uses fewer characters than any other notation",
   "Because it can represent negative numbers without a sign",
   "Because decimal cannot express values above 255"],
  "Hexadecimal lines up with byte boundaries, which decimal does not."),
 ("Entropy", "Analyze", "Why can entropy not be judged by looking at a value?",
  "Because a value produced by a predictable generator looks exactly as unguessable as a random one",
  ["Because entropy is measured in bytes while values are printed in hexadecimal digits, so the figure has to be converted before it can be compared",
   "Because entropy depends on the length of the value alone",
   "Because only the wallet that made the value can measure it"],
  "Entropy is a property of the process that produced the value, not of the digits."),
 ("Nonce", "Analyze", "Why must the mining nonce and the signing nonce never be confused?",
  "Because the mining nonce is public and may be anything, while the signing nonce must be secret and used once",
  ["Because the mining nonce is a four-byte field of the header while the signing nonce is eight bytes long and is stored beside the signature in the witness",
   "Because the signing nonce is stored in the block header",
   "Because the mining nonce must never be reused with the same key"],
  "Reusing a signing nonce with the same key allows the private key to be recovered."),
 ("Encryption", "Understand", "Why are the amounts and conditions of a Bitcoin transaction readable by everyone?",
  "Because nodes must read a transaction in order to verify it, so the data is deliberately public",
  ["Because encrypting every transaction would be far too slow for the number of payments the network carries, so the designers left the data in the clear",
   "Because only the signature is encrypted and the rest is left plain",
   "Because wallets encrypt transactions only when a fee is paid for it"],
  "A user's privacy rests on other things, such as the fact that an address names no person."),
 ("Script", "Remember", "What does an output script specify?",
  "The conditions that must be met to spend the output in the future",
  ["The amount that the output carries, in satoshis",
   "The address of the wallet that created the transaction",
   "The fee rate that the spender of the output must pay"],
  "An input script then satisfies those conditions and allows the output to be spent."),
 ("Serialization", "Understand", "Why must the serialized form of a transaction be defined to the last detail?",
  "Because the identifier is a hash of those bytes and the signature commits to them",
  ["Because wallets display the serialized form to the user before signing",
   "Because the serialized form is what a block explorer indexes by address",
   "Because the fee is computed from the number of fields rather than from the amounts"],
  "Two programs that serialized the same transaction differently would compute different identifiers."),
 ("ByteOrder", "Understand", "What is the practical rule when a hash does not match between two tools?",
  "Try the other byte order before concluding that the data is wrong",
  ["Reverse the hexadecimal characters of the string",
   "Recompute the hash with a single pass of SHA-256",
   "Add the missing leading zeros until the length is 64"],
  "Reversal is on whole bytes, and Bitcoin displays hashes in one order and stores them in another."),
 ("Outpoint", "Analyze", "Why does an outpoint not say who may spend the output it names?",
  "Because the spending condition lives in the script of the output, not in the reference to it",
  ["Because the owner's address is stored in the input script instead",
   "Because the outpoint is hashed, so the owner cannot be read from it",
   "Because ownership is recorded separately in each node's database of balances"],
  "A chain of outpoints can therefore be followed without learning anybody's identity."),
 ("Witness", "Understand", "Why does separating the witness from the rest of a transaction matter?",
  "Because the identifier no longer changes when the proof changes, and witness bytes count less in the weight",
  ["Because the witness can then be kept secret from other nodes",
   "Because an output that is paid to a witness program can be spent without any signature at all, which is what makes the separation worth the complexity",
   "Because it removes the need for an output script in the spending transaction"],
  "The book lists the problems that separation removes, among them third-party malleability."),
 ("Linkage", "Understand", "What do the links between transactions make possible for any node?",
  "Deciding whether an output being spent exists and has not been spent before",
  ["Computing the exchange rate at the time of each payment",
   "Finding the name of the person who created each transaction",
   "Recovering a private key from a chain of earlier signatures"],
  "The links turn individual transactions into a history that anyone can check."),
 ("TransactionChain", "Analyze", "Where does the illustrated chain differ from the real transaction?",
  "The figure labels Alice's input Tx1:0 while the bytes store the output index 1",
  ["The figure shows two inputs for Alice's payment where the real transaction has one, and it gives the amounts in bitcoin where the protocol uses satoshis",
   "The figure gives a fee of 8,000 where the real fee is 5,000",
   "The figure shows the payment before the change, as the real transaction does"],
  "The order of Alice's outputs does agree with the figure: change at position 0 and the payment at position 1."),
 ("MakingChange", "Remember", "Why does a transaction need a change output at all?",
  "Because a transaction input, like a currency note, cannot be partly spent",
  ["Because the protocol requires every transaction to have two outputs",
   "Because the miner refuses a transaction with a single output",
   "Because the fee must be paid from a separate output"],
  "The surplus must be sent back to the payer, exactly as a shop gives change for a larger note."),
 ("CoinSelection", "Analyze", "Why is coin selection a design decision with competing aims?",
  "Because many small inputs raise the fee while always spending large ones leaves many small outputs",
  ["Because the consensus rules limit a transaction to three inputs, so a wallet holding many small outputs must consolidate them before it can pay",
   "Because only a full node is allowed to choose inputs",
   "Because the fee rate depends on which addresses the inputs belong to"],
  "The book presents it as a balance, like a person choosing between big notes and loose change."),
 ("Form", "Understand", "In what sense is a transaction form not a rule of the protocol?",
  "The protocol sees only inputs and outputs; the forms are names for typical shapes",
  ["The forms are enforced by miners but not by full nodes",
   "The forms apply only to transactions with a change output",
   "The forms were rules in the first version of Bitcoin and were later removed"],
  "A transaction can combine the features, for example consolidating many inputs while paying two recipients."),
 ("SimplePayment", "Understand", "Why is the one-input, two-output shape so common?",
  "Because a payer usually holds an output larger than the price and an output cannot be partly spent",
  ["Because the consensus rules require every transaction that spends a single input to create exactly two outputs, one for the receiver and one for the change",
   "Because two outputs are the cheapest possible transaction",
   "Because a second output is needed to carry the fee"],
  "The wallet writes one output for the seller and one back for the buyer."),
 ("Consolidation", "Analyze", "What does a consolidation cost its owner, beyond the fee?",
  "Privacy, because spending many inputs together suggests that one owner controls them all",
  ["The ability to spend the single output for the next hundred blocks, because the rules treat a consolidation like a coinbase output until it matures",
   "The change output, which a consolidation cannot have",
   "The right to use the same addresses again"],
  "It must also be paid for now, since a transaction with many inputs is large."),
 ("PaymentBatching", "Analyze", "What does a payroll batch disclose to anyone who looks?",
  "The full list of amounts paid in that one transaction",
  ["The names of the employees who were paid",
   "The private key that authorized the payments",
   "The balance remaining in the employer's wallet"],
  "The transaction is public, so every recipient can see the other outputs and their amounts."),
 ("Unit", "Understand", "Why are transaction amounts usually given in satoshis rather than in bitcoin?",
  "Because that is the unit the protocol itself uses, so the amounts are whole numbers",
  ["Because whole satoshis are easier for a student to read than decimal fractions of a bitcoin, which is the only reason the chapter prefers them",
   "Because wallets refuse amounts written in bitcoin",
   "Because the exchange rate is quoted per satoshi"],
  "A mistake of the unit is a mistake of a factor of one hundred million."),
 ("Satoshi", "Remember", "Where does the name satoshi come from?",
  "Users began calling the smallest unit a satoshi in honour of Bitcoin's creator",
  ["It was defined under that name in the whitepaper of 2008",
   "It was the name of the first exchange that quoted the unit",
   "It is an abbreviation of the phrase smallest atomic token"],
  "When Bitcoin was created the unit had no name and some developers simply called it the base unit."),
 ("PaymentRequest", "Analyze", "Why is a payment request not itself a payment?",
  "Nothing is sent to the network when a code is displayed or scanned, and the buyer can still decline",
  ["Because the request carries no destination address until the buyer's wallet adds one of its own, which is why the seller cannot be paid by mistake",
   "Because a request is only valid once it has one confirmation",
   "Because the request is signed by the seller rather than by the buyer"],
  "The standard also says that clients must not act on such a link without the user's authorization."),
 ("Uri", "Analyze", "Why must a wallet ask the user to approve a payment read from a link?",
  "Because a link is text and a page can show one address while containing another",
  ["Because the link does not contain the amount to be paid",
   "Because the scheme bitcoin is not registered with the operating system",
   "Because the link expires a few seconds after it is created"],
  "The standard therefore forbids acting on such a link without the user's authorization."),
 ("QrCode", "Understand", "Why can a bech32 address be packed more densely into a QR code?",
  "Because writing it in capitals makes it alphanumeric, which allows a more compact encoding mode",
  ["Because an address of the newer format is shorter than one of the older format, so fewer dots are needed whatever encoding mode the wallet chooses",
   "Because its checksum can be left out inside a code",
   "Because a code can store lower-case letters in half a byte"],
  "BIP 173 says the alphanumeric mode is forty-five per cent more compact than the normal byte mode."),
 ("Bip", "Analyze", "Why does a reference to BIP 21 need to be read together with its date?",
  "Because that document now has the status Closed and has been replaced by BIP 321",
  ["Because BIP numbers are reassigned every year",
   "Because the document was never published in the BIPs repository",
   "Because its status is still Draft and may never be adopted"],
  "A status such as Closed or Complete says what has happened to the document, so a citation is a snapshot."),
 ("Bip21Uri", "Analyze", "Why should a reader not conclude that the address in the printed invoice received the payment?",
  "The invoice asks for 1,577,764 satoshis while the real payment is 75,000, and the output encodes a different program",
  ["Because the invoice was printed before the payment was made, so its address was replaced by the wallet when Alice scanned the code",
   "Because the address in the invoice belongs to a test network",
   "Because the real payment has no output script at all"],
  "The invoice is an illustration, and the book's own tip is to scan it but not to send money."),
 ("Address", "Analyze", "Why is a Bitcoin address not an account?",
  "It holds no balance of its own and names no person; a balance is a sum of unspent outputs",
  ["Because an address may be used only once and then expires, so the network refuses any later payment that is sent to the same string of characters",
   "Because it is derived from the amount being paid",
   "Because only a full node is allowed to create one"],
  "Addresses are also meant to be used once, which is why a change address is usually a new one."),
 ("ExchangeRate", "Understand", "Why is the amount in Bob's invoice not a round number?",
  "Because it is a dollar price converted at the exchange rate of that moment",
  ["Because the fee has already been subtracted from it",
   "Because the protocol rounds every amount to eight decimals at random",
   "Because it includes the value of the change output"],
  "The shop lists prices in dollars and converts them to bitcoin at checkout."),
 ("Construction", "Understand", "Why can two wallets build different transactions for the same payment?",
  "Because the choice of inputs, the change and the fee are decisions of the software, not of the user",
  ["Because each wallet writes the transaction in its own serialization format, so the same payment produces a different set of bytes in every program",
   "Because the payer's address is chosen by the wallet at random",
   "Because only one of them can reach the network"],
  "A user sees only a destination, an amount and a fee; everything else is the wallet's decision."),
 ("TransactionConstruction", "Analyze", "What can go wrong when a wallet builds a transaction while offline?",
  "Its inputs may already have been spent, because it does not know the current state of the network",
  ["It cannot sign the transaction at all, because the signature has to commit to the height of the newest block and that height is only known online",
   "It must leave the fee out, because fee rates are unknown offline",
   "It cannot compute the change, because the exchange rate is unavailable"],
  "A transaction built offline is only a candidate until the network accepts it."),
 ("Wallet", "Remember", "What does a wallet actually contain?",
  "Keys and a view of the ledger, not bitcoins",
  ["A file of coins that can be copied to another computer",
   "A share of the blockchain proportional to the balance",
   "A signed receipt from the miner for every payment received"],
  "That is why a backup of the keys restores the funds and a copy of the balance does not."),
]
