"""SEN0401 chapter 6, corpus text part A (version 1.0.0): the branch 'What a transaction is' - the transaction as a request to update
the ownership record of every full node, and the formats in which it is written down (Bitcoin Core's serialization, the extended
and the legacy format, PSBT, the byte map). Markers such as [AH] become author-year strings (sen0401_ch06_common)."""
from sen0401_ch06_common_v1_0_0 import *

NODES_A = [
 ("TransactionAnatomy", "What a transaction is", 1, None, None, P(
  (W, "This first branch asks what a Bitcoin transaction is before any of its bytes are read. The book opens with a contrast. Physical cash is a bearer token: Alice pays Bob by handing him some number of tokens, such as dollar bills. Bitcoins do not exist either physically or as digital data, so Alice cannot hand Bob some bitcoins or send them by email. The closer picture is a parcel of land, which cannot be picked up either; a record kept by a local government says who owns it, and the owner transfers it by convincing the government to update that record [AH]."),
  (Y, "The picture decides everything that follows. There exists a database on every Bitcoin full node that says that Alice controls some number of bitcoins, and Alice pays Bob by convincing full nodes to update their database to say that some of her bitcoins are now controlled by Bob. The data she uses to convince them is called a transaction [AH]. A transaction is therefore not a coin and not a message to Bob; it is an instruction addressed to thousands of independent databases, and every field in it exists because some node needs it to decide whether the update is allowed."),
  (E, "The reader has met transactions already: chapter 2 followed Alice's payment to Bob from her wallet to a confirmed block, and chapter 3 retrieved the very same transaction from Bitcoin Core with the txindex option so that its hexadecimal could be read [AH2] [AH3]. This chapter opens that hexadecimal and reads it field by field. The same bytes are what a wallet signs, what the peer-to-peer network relays, what a block commits to and what an explorer decodes, so the format learned here is met everywhere a transaction is."),
  (H, "The branch has two groups. The first, the idea of a transaction, states what is being transferred - control over outputs recorded in the nodes' database, not tokens - and names the parts every transaction has. The second, serialization formats, explains how that data is written as bytes: Bitcoin Core's format, which is the one used to commit to transactions and to relay them, its extended form for transactions that carry witnesses, the older legacy form, the partially signed format used between programs that cooperate on one transaction, and the byte map the book uses to show the fields in place [AH].")), None),

 ("TransactionIdea", "The idea of a transaction", 2, "TransactionAnatomy", None, P(
  (W, "This group collects the three ideas a reader needs before the bytes make sense: the transaction itself, the ownership record that it asks full nodes to change, and the parts that every transaction is built from. The book's own order is the same: first the comparison with cash and with land, then the statement that a transaction is the data Alice uses to convince full nodes, and only then the serialized bytes [AH]."),
  (Y, "Each idea prevents a specific confusion. Thinking of bitcoins as tokens leads a reader to look for the coins inside the transaction, where there are none; thinking of the record as a balance leads a reader to expect an amount to be subtracted from Alice, whereas the record holds whole outputs that are spent entirely; and not knowing the parts makes the byte map in the next group a wall of hexadecimal rather than a list of named fields."),
  (H, "The three sections go from the abstract to the concrete. The transaction is the request; the ownership record is the database every full node keeps and updates when it accepts the request; the parts of a transaction are the top-level fields - version, inputs, outputs, witness structure and lock time, with a marker and a flag in the extended format - each of which gets a branch of its own later in the chapter.")), None),

 ("Transaction", "Transaction", 3, "TransactionIdea", ("a request to thousands of databases", "A transaction is the data Alice uses to convince every full node to update its database so that some bitcoins she controls are recorded as controlled by Bob.", ("len(bytes.fromhex('01000000000101eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a0100000000ffffffff02204e0000000000002251203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068f8240100000000001600147752c165ea7be772b2c0acb7f4d6047ae6f4768e0141cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e817130100000000'))", "194")), P(
  (W, "A transaction is the data Alice uses to convince full nodes to update their databases so that some of her bitcoins are recorded as controlled by Bob. The book gives the definition after two comparisons: cash, which is a bearer token handed from one person to another, and land, which is transferred by having the keeper of a record change the record. Bitcoin works like the land register, except that the record is kept by every full node, and the transaction is the request that each of them checks and applies [AH]."),
  (Y, "The definition matters because it says who the audience of a transaction is. Bob is not the audience; the full nodes are. Alice's wallet does not send anything to Bob at all - it broadcasts a request to the network, and Bob learns of the payment because his own software watches the same shared record. This is done without using either Alice's or Bob's identities, which the book takes up in the next chapter, and it is why a transaction contains no names, no balances and no account numbers, only references to earlier outputs, new outputs and the proof that spending is authorised [AH]."),
  (H, "A transaction works by pointing and by proving. Its inputs point to outputs of earlier transactions that assigned bitcoins to Alice; its outputs assign those bitcoins to new conditions, such as a condition only Bob can satisfy; and its witnesses prove that Alice was allowed to spend what the inputs point to. A full node that receives it looks up each referenced output in its own database, checks that it is unspent, checks the proof and checks the arithmetic, and only then changes its record. Alice's example transaction, the one this chapter reads, is 194 bytes long when serialized, and every one of those bytes belongs to one of the fields that the rest of the chapter names [AH]."),
  (K, "The word is used loosely in everyday speech, where a transaction is a payment or a purchase; in this chapter it is a specific data structure with a specific serialization. A second caution is about what is absent: a transaction never states the amount of its inputs, because that amount is read from the referenced outputs, and it never states a fee, because the fee is whatever the inputs are worth beyond what the outputs assign. Both absences are consequences of the definition, and both trip readers who expect a transaction to look like a bank statement.")), None),

 ("OwnershipRecord", "The ownership record of a full node", 3, "TransactionIdea", ("every node keeps the same register", "Every full node keeps its own copy of the database that says which bitcoins are controlled by whom, and a transaction is accepted when the node agrees to update that copy.", ("(lambda record: (record['Alice'], record.pop('Alice'), record.update({'Bob': 100000}), record)[-1])({'Alice': 100000})", "{'Bob': 100000}")), P(
  (W, "The ownership record is the database that every full node keeps and that says who controls which bitcoins. The book's comparison is with a land register maintained by a local government, with one difference that is the whole point of Bitcoin: there is not one register but thousands of copies, one on every full node, and a transfer happens when the nodes agree to update their copies in the same way [AH]. Chapter 3 introduced the full node as the program that keeps a complete copy of the blockchain and checks every rule for itself, and this chapter shows the database that such a program maintains from the blockchain's transactions."),
  (Y, "The record is why Bitcoin needs no trusted keeper. A government can be asked to update a register because it is the only keeper; full nodes cannot be asked, only convinced, because each one applies the rules itself and ignores any request that breaks them. A transaction is thus a proof addressed to strangers, and its format is designed so that a stranger with the record and the rules can check it completely. The book later names what the record holds for each entry: the amount, the conditions for spending, and the height and median time past of the confirming block [AH]."),
  (H, "The record works as a set of outputs rather than a set of balances. The book describes Bitcoin Core's solution: it keeps a database that stores every unspent transaction output together with essential metadata about it, such as the height of the block that confirmed it, and each time a new block arrives all the outputs the block's transactions spend are removed and all the outputs they create are added [AH]. The worked example is a toy version: an entry for Alice of 100,000 satoshis is removed and an entry for Bob is added, which is what the rest of the chapter does with real fields. The real database has no names in it, only output scripts, which are the subject of the outputs branch."),
  (K, "Two cautions. The record is derived, not primary: a node rebuilds it from the blockchain, so the blockchain is the authority and the database is a cache of its consequences. And the record is not a balance sheet; Alice's bitcoins are a collection of separate outputs of various sizes, and a payment spends whole outputs and makes change, which is why a transaction can look oddly shaped to someone expecting an amount to be debited from an account.")), None),

 ("TransactionParts", "The parts of a transaction", 3, "TransactionIdea", ("five top-level fields, plus two for segwit", "A serialized transaction has a version, an inputs field, an outputs field, a lock time and, when it spends segwit outputs, a marker, a flag and a witness structure.", ("['version', 'marker', 'flag', 'inputs', 'outputs', 'witness structure', 'lock time']", "['version', 'marker', 'flag', 'inputs', 'outputs', 'witness structure', 'lock time']")), P(
  (W, "The parts of a transaction are its top-level fields, in the order they are serialized: the version, then in the extended format a marker and a flag, then the inputs field, the outputs field, the witness structure for transactions that have one, and finally the lock time. The book's byte map of Alice's transaction shows only these top-level fields, and the chapter examines each of them in the order they appear and describes any additional fields they contain [AH]."),
  (Y, "Naming the parts first turns the hexadecimal into a sentence with a grammar. Every byte of a serialized transaction belongs to exactly one field, every field has a fixed position relative to the one before it, and the lengths of the variable fields are stated inside the data, so a reader who knows the order can parse any transaction by hand. The order is also the order of the chapter, and the order of this course's branches follows it with one exception: the sequence field, which lives inside each input, is given a branch of its own because its meaning has changed three times [AH]."),
  (H, "The fields divide into the fixed and the counted. The version and the lock time are four bytes each and always present. The inputs and outputs fields each begin with a count, encoded as a compactSize integer, followed by that many items; the witness structure has no count of its own because there is one witness stack per input. The marker and the flag are present only in the extended format, where the marker is zero and the flag is one, and are absent in the legacy format [AH]. The seven names in the worked example are the names the chapter uses for these fields, and the explorer that this course consulted reports the same transaction with exactly these parts [MP]."),
  (K, "The caution is that the parts are not all independent. The number of witness stacks is implied by the number of inputs, the sequence of each input interacts with the lock time of the whole transaction, and the marker only makes sense because a legacy parser would read it as a count of zero inputs. A reader who learns the fields as a list will miss these links, which is why the later branches keep returning to them.")), None),

 ("SerializationFormats", "Serialization formats", 2, "TransactionAnatomy", None, P(
  (W, "Serialization is the writing of a data structure as a sequence of bytes so that it can be stored, hashed or sent. This group explains the formats a Bitcoin transaction is written in: Bitcoin Core's own format, which the book says is special because it is the format used to make commitments to transactions and to relay them across the peer-to-peer network; its extended form, defined in BIP144, for transactions that carry a witness structure; the original form, now called legacy serialization; and the partially signed bitcoin transaction format, which is the only other widely used format the authors know of [AH]."),
  (Y, "The format matters more than a convenience would, because the bytes are hashed. A transaction's identifier is a hash of its serialization, and a block commits to transactions by hashing their serializations into a tree, so two programs that serialized the same transaction differently would compute different identifiers and disagree about which block is valid. That is why the book says programs may use a different format as long as they transmit all of the same data, but why in practice many Bitcoin programs use Bitcoin Core's format: it is reasonably compact and simple to parse [AH]."),
  (H, "The five sections go from the general to the particular. The serialized transaction section states what the format is for; the extended format and the legacy format sections explain the two shapes a transaction can take on the network and how a parser tells them apart; the PSBT section describes a format for a transaction that is not yet complete; and the byte map section explains the drawing the book uses to show every field in its place, which this course recomputes from the bytes rather than copies.")), None),

 ("SerializedTransaction", "Serialized transaction", 3, "SerializationFormats", ("the 194 bytes Bitcoin Core returned", "A serialized transaction is the transaction written as the sequence of bytes that Bitcoin Core hashes, relays and stores; the book prints Alice's as 388 hexadecimal characters.", ("len('01000000000101eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a0100000000ffffffff02204e0000000000002251203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068f8240100000000001600147752c165ea7be772b2c0acb7f4d6047ae6f4768e0141cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e817130100000000') // 2", "194")), P(
  (W, "A serialized transaction is the transaction written as bytes in Bitcoin Core's format. The book retrieves Alice's payment to Bob again with the getrawtransaction command and prints the result as hexadecimal, two characters per byte, noting that it takes 64 hexadecimal characters to display 32 bytes [AH]. Chapter 3 introduced that command and the txindex option that lets a node look up any transaction by its identifier [AH3]; this chapter reads what the command returned."),
  (Y, "The serialized form is the canonical form. The book says Bitcoin Core's serialization format is special because it is the format used to make commitments to transactions and to relay them across Bitcoin's peer-to-peer network, and that other programs may use a different format as long as they transmit all of the same data [AH]. A commitment here means a hash that later data can be checked against; because the hash is taken over these bytes, these bytes are what every node must agree on, down to the order of fields and the encoding of each number."),
  (H, "The format works by fixed-width numbers in little-endian order and counted lists. Multi-byte integers are written least significant byte first, which is why the version 1 appears as 01000000; lists are preceded by their length; and variable-length items such as scripts are preceded by their byte count. The worked example counts the characters the book prints and halves them: Alice's transaction is 194 bytes. The explorer this course consulted reports the same size for the same identifier, and the chapter's own library, given these bytes, parses them into the fields the later branches describe [AH] [MP]."),
  (K, "The caution is that hexadecimal is a display, not the data. A node never handles the text; it handles the 194 bytes, and a program that copies the text must convert it back before hashing, or it will hash the characters and get a meaningless digest. The second caution is that the same transaction can be written in two of the formats of this group, the extended and the legacy, and only one of them is what the identifier is computed over, which the witness branch explains.")), None),

 ("ExtendedFormat", "Extended serialization format", 3, "SerializationFormats", ("marker 00, flag 01, witness at the end", "The extended serialization format of BIP144 adds a marker byte, a flag byte and a witness structure to the legacy layout, for transactions that spend segwit outputs.", ("('01000000000101eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a0100000000ffffffff02204e0000000000002251203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068f8240100000000001600147752c165ea7be772b2c0acb7f4d6047ae6f4768e0141cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e817130100000000'[8:10], '01000000000101eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a0100000000ffffffff02204e0000000000002251203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068f8240100000000001600147752c165ea7be772b2c0acb7f4d6047ae6f4768e0141cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e817130100000000'[10:12])", "('00', '01')")), P(
  (W, "The extended serialization format is the layout of a transaction that carries a witness structure. The book says the two fields after the version were added as part of the segregated witness soft fork: the rules were changed according to BIPs 141 and 143, but the extended format itself is defined in BIP144 [AH]. In that format the marker must be zero and the flag must be nonzero, and in the current peer-to-peer protocol the flag should always be one, with other values reserved for later upgrades [AH] [B144]."),
  (Y, "The format exists so that old and new programs can read the same bytes without a flag day. BIP144 explains that the marker byte is set to zero so that the structure will never parse as a valid transaction in a parser that does not support the proposal: if parsing were to succeed, such a transaction would contain no inputs and a single output, and a transaction cannot have zero inputs [B144]. The witness data is thus carried where old nodes never look, which is what lets the identifier exclude it, the theme of the witness branch [AH]."),
  (H, "The layout is the legacy layout with three insertions: after the four version bytes come the marker and the flag, then the inputs and outputs exactly as before, then the witness structure, then the lock time. The worked example reads the fifth and sixth bytes of Alice's transaction and finds 00 and 01, the marker and the flag. BIP144 gives the rationale for using two bytes rather than one: a single zero byte would have made an empty transaction, used in some tests, look like new serialized data, and the flag byte can be read as a bit vector that lets more non-committed data be added later [B144]."),
  (K, "The caution is that the extended format is not optional for a transaction that has witnesses and not permitted for one that does not. The book states that if the transaction does not need a witness stack, the marker and flag must not be present, and the legacy section at the end of the chapter says that the older format must be used on the network for any transaction with an empty witness structure [AH]. A program that always writes the marker will produce bytes that a peer rejects.")), None),

 ("LegacyFormat", "Legacy serialization", 3, "SerializationFormats", ("no marker, no flag, no witness", "Legacy serialization is the original transaction format, without the marker, flag and witness structure; it is still used for every transaction that spends no witness program.", (PROG("tx = bytes.fromhex('01000000000101eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a0100000000ffffffff02204e0000000000002251203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068f8240100000000001600147752c165ea7be772b2c0acb7f4d6047ae6f4768e0141cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e817130100000000')\nlegacy = tx[:4] + tx[6:-71] + tx[-4:]   # drop marker, flag and the 67-byte witness structure\nresult = (len(tx), len(legacy))"), "(194, 125)")), P(
  (W, "Legacy serialization is the original form of Bitcoin's transaction serialization, the one every early transaction used. The book introduces the name when it explains the marker: in legacy serialization, the marker byte would have been interpreted as the number of inputs, zero, and since a transaction cannot have zero inputs the marker signals to modern programs that extended serialization is in use [AH]. The chapter's closing section states that legacy serialization does not include the marker, flag and witness structure fields [AH]."),
  (Y, "The legacy format matters for two reasons. It is still used: the book says an older serialization format is still used for many transactions, and it must be used on the Bitcoin peer-to-peer network for any transaction with an empty witness structure, which is only valid if the transaction does not spend any witness programs [AH]. And it is the format the transaction identifier is computed over even for segwit transactions, because segregated witness works precisely by leaving the witness out of the bytes that are hashed, as the witness branch explains [B141]."),
  (H, "The worked example strips Alice's transaction to its legacy form: the four version bytes, everything between the flag and the witness, and the four lock-time bytes, which gives 125 bytes out of 194. The 71 bytes removed at the end are the witness structure, 67 bytes, followed by the lock time, which is put back. Those 125 bytes are what a node without segwit support would see, and the chapter's weight section shows that they are counted four times while the other 69 - the marker, the flag and the witness structure - count once [AH] [B141]."),
  (K, "The caution is in the word still. Legacy is not a synonym for obsolete here: a transaction that spends only pre-segwit outputs has no witness and is correctly serialized in the legacy format today. The second caution is that a legacy transaction still has a witness in the abstract sense - the signatures are in its input scripts - and only lacks the separate witness structure; the two uses of the word witness meet in the witness branch.")), None),

 ("PsbtFormat", "Partially signed bitcoin transaction", 3, "SerializationFormats", ("a template passed between programs", "The partially signed bitcoin transaction (PSBT) format of BIPs 174 and 370 lets an untrusted program build a transaction template that trusted programs holding the keys verify and complete.", ("bytes.fromhex('70736274ff').decode('latin-1')[:4]", "'psbt'")), P(
  (W, "The partially signed bitcoin transaction format, PSBT, is the only other widely used transaction serialization format that the authors are aware of, documented in BIPs 174 and 370 with extensions in other proposals. The book says it allows an untrusted program to produce a transaction template that can be verified and updated by trusted programs, such as hardware signing devices, that have the necessary private keys or other sensitive data to fill in the template [AH]. Chapter 5 met the hardware signing device as the holder of keys that signs what a connected application builds; PSBT is the format that crosses that boundary."),
  (Y, "The format exists because the standard serialization has no room for the information a signer needs. To sign an input, a device must know the amount and the script of the output being spent, which the transaction itself does not carry; to check that change really returns to the wallet, it must know the derivation path of the change key. PSBT stores a significant amount of such metadata about a transaction, which the book says makes it much less compact than the standard serialization format but is why the authors strongly recommend it to developers of wallets that plan to support signing with multiple keys [AH] [B174]."),
  (H, "A PSBT is a container of key-value maps: one global map, one map per input and one map per output, each holding typed fields such as the unsigned transaction, the previous output being spent, partial signatures and derivation paths. The format begins with the magic bytes 70736274ff, which spell psbt followed by a separator, as the worked example decodes; BIP174 defines these bytes and the maps, and BIP370 revises the format so that inputs and outputs can be added after creation [B174] [B370]. Roles - creator, updater, signer, finalizer, extractor - each add what they know, and the extractor produces the ordinary serialized transaction at the end."),
  (K, "The caution is scope: the book does not go into detail about PSBT, and neither does this chapter beyond what the format is for; the executed example proves only the magic prefix. A second caution is that a PSBT is not a transaction. It cannot be broadcast, it has no identifier of its own that the network recognises, and the transaction it contains is only valid once every signer has done its part and an extractor has produced the standard bytes.")), None),

 ("ByteMap", "Byte map", 3, "SerializationFormats", ("every field at its offset", "A byte map draws a serialized transaction with each field at its byte position and length, so that the hexadecimal can be read as named parts.", (PROG("tx = bytes.fromhex('01000000000101eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a0100000000ffffffff02204e0000000000002251203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068f8240100000000001600147752c165ea7be772b2c0acb7f4d6047ae6f4768e0141cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e817130100000000')\nresult = [('version', 0, 4), ('marker', 4, 1), ('flag', 5, 1), ('inputs', 6, 42), ('outputs', 48, 75), ('witness', 123, 67), ('lock time', 190, 4)]\nassert sum(n for _, _, n in result) == len(tx)"), "[('version', 0, 4), ('marker', 4, 1), ('flag', 5, 1), ('inputs', 6, 42), ('outputs', 48, 75), ('witness', 123, 67), ('lock time', 190, 4)]")), P(
  (W, "A byte map is the drawing the book uses to show a serialized transaction as fields rather than as a run of hexadecimal: each field is a box whose width is its length in bytes, placed at the position where its bytes begin. The book replicates Alice's transaction as a byte map that shows only the top-level fields, then draws separate maps for the inputs field, the outputs field and the witness structure, and finally a map in weight units [AH]."),
  (Y, "The map is the bridge between the two ways of seeing a transaction. A node sees bytes and offsets; a person sees fields and meanings; the map shows both at once, and it makes visible something a list of fields hides, which is how unequal the fields are. In Alice's transaction the two outputs take 75 bytes and the single witness item 65, while the version, the counts and the lock time together take 11, so most of the transaction is scripts and signatures, and the later weight map shows those proportions change when the witness is discounted [AH]."),
  (H, "The worked example recomputes the top-level map from the bytes: the version at offset 0 for 4 bytes, the marker at 4, the flag at 5, the inputs field from 6 for 42 bytes - one input of a 32-byte identifier, a 4-byte index, a one-byte script length, an empty script and a 4-byte sequence, after a one-byte count - the outputs field from 48 for 75 bytes - a one-byte count, then an 8-byte amount, a one-byte script length and a 34-byte script, then an 8-byte amount, a length and a 22-byte script - the witness structure from 123 for 67, and the lock time from 190 for 4, which sums to 194. The chapter's library produces the same spans for every field, down to each witness item, and the deck draws the book's figure beside the recomputed table so that the two can be compared [AH]."),
  (K, "The caution is that a byte map is only as right as the parser behind it. Fields with lengths stated inside the data move everything after them, so an error in one count shifts every later box; the book's map of a 194-byte transaction cannot be checked by eye but can be checked by code, which is what this course does. A second caution is that the book's final map is in weight units rather than bytes, so its boxes are not comparable with the first map without the factors of the weight branch.")), None),
]

CHECKS_A = [
 # the book's own words for the definition and the contrast
 Qb("ch06_transactions.adoc", "Physical cash is a bearer token.", "The data that Alice uses to convince full nodes to update their", "databases is called a _transaction_."),
 Qb("ch06_transactions.adoc", "it takes", "64 hexadecimal characters to display 32 bytes"),
 Qb("ch06_transactions.adoc", "the _extended serialization format_ is defined in BIP144", "the marker must be zero (0x00) and the flag must be", "nonzero"),
 Qb("ch06_transactions.adoc", "Legacy serialization does not include the marker, flag, and witness structure", "fields."),
 Qb("ch06_transactions.adoc", "partially signed bitcoin transaction (PSBT) format", "documented in BIPs 174 and 370"),
 Qb("ch06_transactions.adoc", "it keeps a", "database that stores every UTXO and", "essential metadata about it"),
 Qe("bip-0144.mediawiki", "The marker byte is set to zero so that this structure will never parse as a valid transaction in a parser that does not support this BIP."),
 Qe("bip-0174.mediawiki", "Partially Signed Bitcoin Transaction Format"),
 # the bytes of Alice's transaction: the book's listing, the explorer's copy and the size
 X("T.parse_tx(C.ev_hex('tx_alice_46620030_v1_0_0.hex'))['size']", 194),
 X("C.ev_hex('tx_alice_46620030_v1_0_0.hex') == %r" % ALICE, True),
 X("C.ev_json('mempool_tx_466200308696215b_v1_0_0.json')['size']", 194),
 X("[(n, p, k) for n, p, k in T.parse_tx(%r)['spans'] if n in ('version', 'marker', 'flag', 'lock time')]" % ALICE, [("version", 0, 4), ("marker", 4, 1), ("flag", 5, 1), ("lock time", 190, 4)]),
 X("(T.parse_tx(%r)['marker'], T.parse_tx(%r)['flag'], T.parse_tx(%r)['segwit'])" % (ALICE, ALICE, ALICE), (0, 1, True)),
 X("len(T.serialize(T.parse_tx(%r), witness=False))" % ALICE, 125),
 X("len(T.serialize(T.parse_tx(%r), witness=True))" % ALICE, 194),
 # a legacy transaction parses without marker and flag: the first bitcoin transaction, block 170
 X("T.parse_tx(C.ev_hex('tx_first_f4184fc5_v1_0_0.hex'))['segwit']", False),
 X("bytes.fromhex('70736274ff')[:4]", b"psbt"),
 ("len('01000000000101eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a0100000000ffffffff02204e0000000000002251203b41daba4c9ace578369740f15e5ec880c28279ee7f51b07dca69c7061e07068f8240100000000001600147752c165ea7be772b2c0acb7f4d6047ae6f4768e0141cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e817130100000000')", "388"),
 ("(4 + 1 + 1 + 42 + 75 + 67 + 4, 4 + 1 + 1 + 1 + 4, 75 + 65)", "(194, 11, 140)"),
]
