"""SEN0401 chapter 1, text part C (version 1.2.0): the Foundations branch (cryptography, the chain, computing, threats). See sen0401_ch01_corpus_v1_2_0.py.
These are the technical terms that the other branches use; each one is explained here so that no term of the chapter is left without a concept."""
from sen0401_ch01_common_v1_2_0 import W, Y, E, H, K, js, prog
_CHAIN = prog('''import hashlib
def link(prev, data): return hashlib.sha256((prev + data).encode()).hexdigest()
data = ['Joe pays Alice 1', 'Alice pays Eve 2', 'Eve pays Joe 3']
def build(items):
    hs, prev = [], 'genesis'
    for d in items:
        prev = link(prev, d); hs.append(prev)
    return hs
stored = build(data)
tampered = ['Joe pays Alice 100'] + data[1:]
result = (build(data) == stored, build(tampered) == stored)''')
NODES_C = [
 # ------------------------------------------------------------------ FOUNDATIONS
 ("Foundations", None, 1, None, None, [
  (W, "The Foundations branch collects the general technical ideas that the rest of the chapter takes for granted. Chapter 1 of the textbook introduces Bitcoin through a story about Alice and Joe, and in doing so it uses words such as digital signature, private key, blockchain, node, protocol and QR code as if every reader already knew them [AH]. This branch stops to explain each of those words, so that a student who has not met them before can follow the later branches without guessing."),
  (Y, "A technical text is only as clear as its vocabulary. Bitcoin is built from ideas of cryptography, of distributed computing and of ordinary internet engineering, and none of the three is new to the specialist while all of them are new to many beginners. Explaining them once and in one place also shows an important fact about the subject: Bitcoin invents very little vocabulary of its own and mostly combines established techniques in a new arrangement, which is how the chapter itself describes Nakamoto's contribution [AH]."),
  (E, "The ideas appear throughout the chapter. A hash function is used by proof of work, by the checksum of a recovery code and by Hashcash; a digital signature is what makes a transaction valid; a block and a blockchain are the record that the whole network maintains; and a protocol, an API, a URI and a QR code are the means by which wallets talk to each other and to the people who use them. Each later explanation points back to the concept here."),
  (H, "The branch has four sections. The Cryptography section explains the mathematical tools: the hash function, the digital signature, public-key cryptography, the private key, entropy, the checksum, the keyed hash and key stretching. The Chain section explains the block, the blockchain, the timestamp and the node. The Computing section explains the everyday technology on which Bitcoin runs, from the internet and its protocols to databases and operating systems. The Threats section explains malware and phishing, the two attacks that the chapter warns about."),
  (K, "Two cautions apply to the whole branch. The explanations are introductions, and the later chapters of the textbook return to the same ideas in greater depth, so a student should treat the examples here as the smallest correct version of each idea and not as a complete treatment. The examples in this branch are also deliberately small, with tiny numbers, so that they can be computed by hand or in a few lines of Python; real Bitcoin uses far larger values and different algorithms for some of them, and the text says where this matters."),
 ], None),
 ("Cryptography", None, 2, "Foundations", None, [
  (W, "Cryptography is the science of transforming data so that its meaning is hidden, so that undetected alteration is prevented, or so that unauthorised use is prevented. The Internet Security Glossary describes it in these terms and adds that if the transformation is reversible, cryptography also deals with restoring the data [SH]. The Mozilla glossary puts it more simply, as the science that studies how to encode and transmit messages securely, and adds that it tackles identification, authentication and data integrity as well as confidentiality [MD]."),
  (Y, "Digital money has a problem that physical money does not have. A banknote is hard to copy because of its paper and its printing, but a digital file can be copied perfectly and without cost. Chapter 1 explains that cryptography takes the place of the special paper and inks: it provides the basis for trusting the legitimacy of a user's claim to value, and cryptographic digital signatures let a user prove ownership of a digital asset [AH]. Without cryptography there would be no way to say who may spend which coin."),
  (E, "Cryptography is met every time a person uses a secure website, signs a document digitally, or opens a payment application. In Bitcoin it appears in eight forms that this section explains: the hash function that condenses data into a fingerprint, the digital signature that proves who authorised a transaction, the public-key cryptography that makes signatures possible, the private key that a wallet protects, the entropy that makes keys unpredictable, the checksum that detects typing errors, the keyed hash that binds a result to a secret, and the key stretching that makes guessing slow."),
  (H, "The eight concepts form a chain. A wallet begins with entropy, which is randomness that an attacker cannot predict. The randomness becomes a private key, from which a public key is derived. The wallet then signs data with the private key, and anyone can check the signature with the public key, using a hash function to condense the data first. A checksum protects the backup against mistakes; a keyed hash is the building block from which the slow derivation is made; and key stretching slows down an attacker who tries to guess the backup."),
  (K, "Cryptography is often imagined as secrecy alone, which is a mistake that this chapter corrects. Bitcoin transactions are public, and nothing in them is encrypted; the cryptography of Bitcoin is used to prove who authorised a payment and to make the record hard to alter, not to hide it. A second mistake is to think that cryptography is magic. Its security rests on mathematical assumptions and on correct use, and most real losses come from bad use, such as a weak password or a stolen backup, and not from a failure of the mathematics."),
 ], None),
 ("HashFunction", "Hash function", 3, "Cryptography", ("the SHA-256 hash of abc", "A hash function maps data of any length to a fixed-length fingerprint; SHA-256 produces 256 bits, and any change to the input gives a different result.", ("__import__('hashlib').sha256(b'abc').hexdigest()", "'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'")), [
  (W, "A hash function is a function that maps data of any length to a result of fixed length, called the hash or digest. The Internet Security Glossary defines it as a function that maps an arbitrary, variable-length bit string into a fixed-length string and adds that, for most computing applications, any change to the input should produce a different result [SH]. The chapter's glossary calls a hash a digital commitment to some binary input [AH], which expresses the same idea: the short result commits its author to exactly one input."),
  (Y, "A fixed-length fingerprint is valuable because it makes large things easy to compare and to refer to. Two files are the same if their hashes are the same, and a signature need only cover the short hash and not the whole file. The standard that defines the SHA-2 family explains that a good hash function is secure in two ways: it is computationally infeasible to find a message that corresponds to a given digest, or to find two different messages with the same digest [EH]. These properties are what proof of work and the linking of blocks rely on."),
  (E, "In this chapter the hash function appears in four places. Proof of work searches for an input whose SHA-256 hash begins with zeros, Hashcash did the same for email, the recovery code of a wallet carries a checksum taken from a hash, and a block commits to the previous block by containing its hash [NK][BK][B39]. Outside Bitcoin the same tools protect passwords, verify downloaded software and identify files."),
  (H, "SHA-256, the function used by Bitcoin, takes a message of any practical length and returns 256 bits, which are normally written as 64 hexadecimal digits. The standard's own test vector shows the result for the three letters abc, and the example reproduces it with Python's hashlib module: the hash of abc begins ba7816bf and ends 20015ad [EH]. A change of a single letter produces a completely different result: the hashes of abc and abd differ in 122 of their 256 bits, which is close to the half that one expects of an unpredictable function."),
  (K, "A hash function is not encryption. Nothing is hidden, because the same input always gives the same output, and nothing can be recovered from the output, because many inputs share the same hash in principle and the function is designed to be hard to run backwards. A hash also does not authenticate by itself, since anyone can compute the hash of altered data; it becomes useful when it is signed, published in a trusted place, or buried in a chain of blocks. Finally, short or guessable inputs can be found by trying them one after another, so a hash of a weak password protects little."),
 ]),
 ("DigitalSignature", "Digital signature", 3, "Cryptography", ("a toy signature with tiny numbers", "A digital signature is a value computed from data and a private key that anyone holding the matching public key can use to verify the origin and integrity of the data.", ("(lambda n, e, d, m: (pow(m, d, n), pow(pow(m, d, n), e, n) == m, pow(pow(m, d, n), e, n) == 66))(3233, 17, 2753, 65)", "(588, True, False)")), [
  (W, "A digital signature is a value computed from a data object and a secret key, which lets any recipient verify where the data came from and that it has not been changed. The Internet Security Glossary defines it as a value computed with a cryptographic algorithm and associated with a data object in such a way that any recipient of the data can use the signature to verify the data's origin and integrity [SH]. A handwritten signature offers a loose version of the same promise on paper."),
  (Y, "A digital signature is what allows money to be spent without a bank. Chapter 1 explains that cryptographic digital signatures enable a user to sign a digital asset or a transaction, proving the ownership of that asset, and that with the appropriate architecture they can also be used to address the double-spend issue [AH]. The whitepaper defines the electronic coin as a chain of digital signatures, in which each owner transfers the coin to the next by signing [NK]. Without signatures, anybody could write a transaction in anybody else's name."),
  (E, "Every Bitcoin transaction carries signatures: Joe's wallet signs the transaction that pays Alice with his private keys, and this tells the network that Joe has authorised the transfer [AH]. Outside Bitcoin, digital signatures protect software updates, secure web connections, electronic contracts and the verifiable credentials that the semantic bridge of this chapter describes [VC]."),
  (H, "Signing uses a pair of related keys. The signer computes the signature from the data and the private key, and a verifier checks it with the public key, which anyone may know. The example uses a toy scheme with the tiny public numbers n = 3233 and e = 17 and the private number d = 2753, which the next two concepts explain: the message 65 is signed as 65 raised to the power d, taken modulo n, which gives 588, and the verification raises 588 to the power e and recovers 65. The recovered value is 65 and not 66, so a verifier who is told that the message was 66 rejects the signature. Real systems sign the hash of the data and use far larger numbers."),
  (K, "A valid signature proves that someone holding the private key signed this exact data; it does not prove who that someone is, or that the signer meant well. If the private key is stolen, the thief can sign as the owner, and no one can tell the difference. A signature also covers only the data that was signed: a transaction that is changed after signing no longer verifies, but a transaction that was signed in error remains valid. The toy numbers of the example are far too small to be secure, and Bitcoin does not use this scheme; later chapters of the textbook explain the algorithm that it does use."),
 ]),
 ("PublicKeyCryptography", "Public-key cryptography", 3, "Cryptography", ("a key pair with tiny numbers", "Public-key cryptography uses a pair of mathematically related keys, one public and one private, so that what one key does only the other can undo.", ("pow(pow(65, 17, 3233), 2753, 3233)", "65")), [
  (W, "Public-key cryptography, also called asymmetric cryptography, is cryptography in which each user has a pair of mathematically related keys. The Internet Security Glossary defines the public key as the publicly disclosable component of the pair and the private key as the secret component, and it describes the key pair as a set of related keys that is generated in a way that makes it computationally infeasible to derive the private key from knowledge of the public key [SH]."),
  (Y, "Before public-key cryptography, two people who wanted to exchange secret or authenticated messages first had to share a secret key in some safe way, which does not work between strangers on the internet. With a key pair, the public half can be published to everybody, and only the private half has to be protected. This asymmetry is what makes it possible to prove ownership without revealing the secret, which is exactly what a payment system between strangers needs [AH]."),
  (E, "Public-key cryptography is used in secure web connections, in signed email and software, and in Bitcoin. A Bitcoin wallet generates a private key, derives from it the public data that others see, and uses the pair to sign transactions, as chapter 1 describes when it says that Alice's wallet randomly generated a private key that is used to derive Bitcoin addresses [AH]. The W3C identity standards of the semantic bridge rely on the same technique [DID]."),
  (H, "The example uses a classic textbook construction with tiny numbers. Two small primes, 61 and 53, give n = 61 * 53 = 3233, and the public exponent e = 17 and the private exponent d = 2753 are chosen so that 17 * 2753 leaves the remainder 1 when divided by 60 * 52 = 3120. A message m = 65 is transformed with the public key as pow(65, 17, 3233), and the private key undoes the transformation: pow(that result, 2753, 3233) returns 65. Used in the other direction, the same pair produces and verifies signatures, as the previous concept shows."),
  (K, "The security of such a scheme depends on the difficulty of one mathematical problem, which for the toy numbers is trivial: anybody can split 3233 into its two factors and recompute the private key. Real keys use numbers that are hundreds of digits long, and Bitcoin uses a different mathematical construction altogether, which later chapters explain. A further caution is that the public key is public only in the sense that it may be shared; it must still be authentic, because an attacker who can substitute his own public key for yours receives what was meant for you."),
 ]),
 ("PrivateKey", "Private key", 3, "Cryptography", ("a 256-bit secret number", "A private key is the secret half of a key pair; in Bitcoin it is a very large number whose holder alone can sign transactions that spend the corresponding bitcoin.", ("len(str(2**256))", "78")), [
  (W, "A private key is the secret component of a pair of cryptographic keys. The Internet Security Glossary describes it as the key that is known only by its user and used for asymmetric cryptography [SH]. In Bitcoin the glossary of the textbook calls it the secret number that unlocks bitcoin sent to the corresponding address, and chapter 1 compares private keys to very long PINs [AH]."),
  (Y, "The private key is the only thing that a Bitcoin user must protect, because possession of the key that can sign a transaction is the only prerequisite to spending bitcoin [AH]. This is why the control of the key decides who owns the money: whoever holds the key controls the funds, and nobody else, not even the network, can stop them. The slogan of the chapter, your keys, your coins, is a statement about the private key."),
  (E, "Private keys live inside wallets. A noncustodial wallet generates them on the user's device and keeps them there, a hardware signing device keeps them inside special-purpose hardware, and a custodian keeps them for its customers [AH]. The recovery code of a wallet is a compact way of storing the information from which all of its private keys can be rebuilt."),
  (H, "A private key is a number chosen at random from an enormous range. The textbook's chapter on keys explains that a wallet obtains 256 bits of entropy from a random number generator and uses them to form a 256-bit number [AH]. A number of 256 bits can take 2 to the power 256 values, a figure with 78 decimal digits, which is far too many for anybody to try one after another. The wallet then derives the public data from the private key in a way that cannot be reversed in practice."),
  (K, "A private key must never be revealed, copied carelessly or typed into a page that asks for it. Anyone who sees it can spend the funds, and nothing can reverse the theft, since Bitcoin transactions are irreversible. The opposite danger is loss: a key that is destroyed without a backup takes the funds with it. Because of both dangers the chapter pairs the idea of control with the duty of backup, and it warns that applications which ask for the recovery code at unexpected moments may be fraudulent [AH]."),
 ]),
 ("Entropy", "Entropy", 3, "Cryptography", ("128 bits chosen at random", "Entropy is a measure of unpredictability, counted in bits; a wallet needs enough of it that nobody can guess the key or recovery code.", ("(2048 .bit_length() - 1, 12 * 11, 128 + 128 // 32)", "(11, 132, 132)")), [
  (W, "In cryptography, entropy is a measure of how unpredictable a secret is. The Internet Security Glossary defines it as an information-theoretic measure, usually stated as a number of bits, of the amount of uncertainty that an attacker faces to determine the value of a secret [SH]. A secret with 20 bits of entropy is as hard to guess as a number chosen uniformly from about a million possibilities."),
  (Y, "A key is only as secret as the randomness behind it. If a wallet chose its keys in a predictable way, for example from the time of day, an attacker could try the likely values and find them. Chapter 1 therefore insists that the recovery code consists of numbers, letters or words selected randomly by the software [AH], and the standard behind the word lists says that the sentence must encode entropy in a multiple of 32 bits [B39]."),
  (E, "Entropy appears when a wallet is created and whenever a recovery code is generated. BIP 39 calls the random bits at the start of the process the initial entropy and allows 128 to 256 bits of it, which gives sentences of 12 to 24 words [B39]. Operating systems provide random number generators for this purpose, and hardware signing devices include their own."),
  (H, "The BIP 39 recovery code turns entropy into words. Each word is chosen from a list of 2048 words, so each word carries 11 bits, because 2 to the power 11 is 2048. A sentence of 12 words therefore carries 12 * 11 = 132 bits, which are the 128 bits of initial entropy plus a 4-bit checksum, as the next concept explains. The number of bits, not the number of words, measures the security."),
  (K, "Entropy cannot be seen in the result, since a predictable secret may look as random as a good one. A recovery code that the user made up, or that came from a source of poor randomness, is far weaker than its length suggests, which is why the standard states that it is not a way to process user-created sentences into a wallet seed [B39]. A second caution is that entropy is used up by disclosure: a recovery code that was photographed or stored online is no longer secret, however many bits it carries."),
 ]),
 ("Checksum", "Checksum", 3, "Cryptography", ("the first 4 bits of a SHA-256 hash", "A checksum is a short value computed from data and stored with it so that changes can be detected; a BIP 39 recovery code carries ENT/32 bits taken from a SHA-256 hash.", ("__import__('hashlib').sha256(bytes(16)).digest()[0] >> 4", "3")), [
  (W, "A checksum is a value that is computed from the contents of a data object and is stored or transmitted together with the object, so that changes in the data can be detected. This is the definition of the Internet Security Glossary [SH]. A familiar example is the final check digit of a long number, which lets a machine notice that a digit was mistyped."),
  (Y, "People make mistakes when they copy a long secret by hand, and in Bitcoin a mistake can be costly because nobody can restore a lost or wrongly recorded key. A checksum turns many such mistakes into an error message instead of a silent failure. The standard for recovery codes uses one for exactly this reason, and it also states its limit: the checksum is short, so it only gives modest odds of catching random errors, and it cannot help to correct them [B39]."),
  (E, "Checksums are found in credit card numbers, in barcodes, in file downloads and in the recovery codes of Bitcoin wallets. In BIP 39 a checksum is generated by taking the first ENT / 32 bits of the SHA-256 hash of the initial entropy, where ENT is the length of the entropy in bits, and the checksum is appended to the entropy before the whole is divided into words [B39]."),
  (H, "The method is simple. The wallet computes the hash of the random bytes and keeps the first few bits. For 128 bits of entropy the checksum has 128 / 32 = 4 bits, and the example computes them for 16 bytes that are all zero: the first byte of their SHA-256 hash is shifted right by four places and leaves the value 3, which is the bit group 0011. A program that receives the words recomputes the hash of the entropy it decodes and compares the first bits; if they differ, it reports that the sentence is invalid."),
  (K, "A checksum detects accidental changes and does not defend against an attacker, who can recompute it after altering the data. It also does not tell where the error is. With 4 bits of checksum, one random error in 16 slips through unnoticed, and with 8 bits one in 256 does, which is the figure the standard gives [B39]. A checksum is therefore a convenience for honest users and not a form of security."),
 ]),
 ("KeyedHash", "Keyed hash", 3, "Cryptography", ("HMAC-SHA512 of a short message", "A keyed hash, or message authentication code, mixes a secret key into a hash so that only a holder of the key can produce or confirm the result; HMAC is the standard construction.", ("len(__import__('hmac').new(b'key', b'message', 'sha512').digest())", "64")), [
  (W, "A keyed hash is a hash that is computed from two things rather than one: the data and a secret key. The result is usually called a message authentication code, because it lets a receiver who knows the same key confirm both that the data is unaltered and that it came from someone holding the key. The construction that is used almost everywhere is called HMAC, which takes an ordinary hash function and a key and combines them in a fixed way; written as HMAC-SHA512, it means the construction applied with SHA-512 as the inner hash function."),
  (Y, "A plain hash proves nothing about who computed it, because anybody can hash anything, as the section on the hash function warns. Mixing in a secret repairs exactly that gap: a value that could only be produced by a holder of the key is evidence about the author and not only about the data. The same property has a second use, which is the one this chapter needs. If the key is the secret from which a wallet derives its keys, then the keyed hash is a function that nobody without the secret can compute, which is what a key derivation needs at its core."),
  (E, "A reader meets the keyed hash in the standard for recovery codes, which turns the words into a binary seed using the function PBKDF2 with HMAC-SHA512 as the underlying function and an iteration count of 2048 (Palatinus et al., 2013). Outside Bitcoin, keyed hashes protect session cookies, sign programming interface requests and authenticate messages on the network, and the standard that defines SHA also defines HMAC alongside it."),
  (H, "The construction pads the key to the block length of the hash function, combines it with two fixed byte patterns, and hashes twice: once over the first pattern and the message, and once over the second pattern and that intermediate result. The reader does not have to carry out those steps, because the standard library offers the whole construction: the example computes HMAC-SHA512 over the message with the key and finds that the result is 64 bytes long, the same 512 bits that the hash function alone would give. Only the length is public; the value itself depends on the key."),
  (K, "A keyed hash is not encryption, so the data it protects is not hidden, and it is not a digital signature, because the same key is needed to check the result as to produce it: a keyed hash convinces the two parties who share the key and nobody else, while a signature convinces everyone. The security also rests entirely on the key: a keyed hash computed with a guessable key is as weak as that key, which is why the next section's slow derivation exists."),
 ]),
 ("KeyStretching", "Key stretching", 3, "Cryptography", ("a 64-byte seed from PBKDF2", "Key stretching derives a key from a secret by repeating a function many times, so that every guess of an attacker costs as much work as the honest computation.", (prog("import hmac\npassword, salt, iters = b'abandon', b'mnemonic', 2048\nu = hmac.new(password, salt + bytes([0, 0, 0, 1]), 'sha512').digest()\nseed = u\nfor _ in range(iters - 1):\n    u = hmac.new(password, u, 'sha512').digest()\n    seed = bytes(a ^ b for a, b in zip(seed, u))\nresult = (len(seed), seed.hex()[:8])"), "(64, 'd96147bf')")), [
  (W, "Key stretching is the use of a deliberately slow, repeated computation to derive a key from a secret. The standard for password-based cryptography describes the technique as including an iteration count in the key derivation, which indicates how many times to iterate some underlying function by which keys are derived [PK]. The function that BIP 39 uses is called PBKDF2, and it is defined in that standard."),
  (Y, "Human-chosen or short secrets can be guessed by trying them one after another. If one guess costs a single fast computation, an attacker can try billions of them; if each guess costs thousands of repetitions, the attacker's work grows by the same factor while the honest user, who computes only once, hardly notices. The standard explains the reasoning: a modest number of iterations, say 1000, is not likely to be a burden for legitimate parties but will be a significant burden for opponents [PK]."),
  (E, "Key stretching is used wherever a key is made from a password or a phrase: in disk encryption, in password storage and in wallets. In the recovery code standard, the sentence of words is turned into a binary seed with the PBKDF2 function, using the sentence as the password and the word mnemonic, followed by an optional passphrase, as the salt; the iteration count is 2048 and the underlying function is HMAC-SHA512 [B39]."),
  (H, "PBKDF2 applies a pseudorandom function, which is a function whose output cannot be told apart from random bits without the key, and in this standard is the keyed hash of the previous concept, to the password and a salt, a public value that makes the work specific to this use, repeats the application the stated number of times, and combines the results into the derived key [PK]. The worked example builds that loop out of the keyed hash rather than calling a ready-made function, so that every step is visible: it applies HMAC-SHA512 to the password and the salt followed by the block number 1, then applies it 2047 more times to its own previous output, and combines all the results with the exclusive-or operation. With SHA-512 as the underlying hash function the derived key has 512 bits, which is 64 bytes, and for the word abandon with the salt mnemonic the first four bytes of the result are d96147bf."),
  (K, "Stretching raises the cost of guessing but does not remove it; a weak secret remains weak, only slower to attack. The iteration count of 2048 in the recovery code standard is modest by present standards, and the strength of the code comes mainly from the random entropy behind it and not from the stretching. The same words with the same passphrase always give the same seed, which is the feature that makes recovery possible and also the reason that the words must be guarded."),
 ]),
 # ------------------------------------------------------------------ CHAIN
 ("Chain", None, 2, "Foundations", None, [
  (W, "The Chain section explains the data structure at the centre of Bitcoin and the computers that maintain it. The block is a group of transactions that the network accepts together, the blockchain is the list of blocks linked one to the next, the timestamp is the mark of time that orders them, and the node is a computer that takes part in the network. The chapter uses all four words in its first pages [AH]."),
  (Y, "A payment system needs a single agreed record of what happened and in what order. In the system of a bank this record is a database that the bank keeps. In Bitcoin it is the blockchain, kept by thousands of nodes at once, with each block fixing the order of its transactions and tying itself to the past. Understanding the chain makes clear why changing an old payment is so hard."),
  (E, "The vocabulary of the chain appears throughout chapter 1: in the description of mining, which adds a block roughly every ten minutes; in the sidebar on confirmations, which counts blocks to decide when a payment may be trusted; and in the account of how Joe's transaction spreads from node to node until most of the well-connected nodes have it [AH]. The same four words are used outside the book by block explorers, which display the chain, by wallets, which report a confirmation count, and by news reports, which quote block heights and times. A student who reads them in this course should expect to meet them again in every later chapter."),
  (H, "The four concepts are explained from the inside out. The block is the unit. The blockchain is the chain of units, tied together by hashes. The timestamp explains the time mark that each block carries and what it is good for. The node explains who stores and checks the chain, and prepares the later sections on full nodes and lightweight clients."),
  (K, "The word blockchain is used in many different senses in popular writing, where it often means any shared database with some cryptography in it. In this course it keeps the narrower sense of the textbook's glossary: the particular list of validated blocks that the Bitcoin network agrees on, each one linked to its predecessor back to the first block [AH]. The word node is similarly narrowed, since the chapter uses it for a computer that takes part in this network and not for any point in any graph. Keeping the vocabulary this strict is what lets the later chapters make precise statements."),
 ], None),
 ("Block", "Block", 3, "Chain", ("the transactions of block 840000", "A block is a group of transactions, marked with a time and committing to the previous block, that is added to the blockchain once it carries a valid proof of work.", ("(%s['tx_count'], %s['tx_count'])" % (js('block840000.json'), js('block0.json')), "(3050, 1)")), [
  (W, "A block is a group of transactions that the network accepts as one unit. The glossary of the textbook defines it as a grouping of transactions, marked with a timestamp, and a commitment to the previous block; its header is hashed to produce a proof of work, thereby validating the transactions, and valid blocks are added to the main blockchain by network consensus [AH]. A block also contains one special first transaction that pays the miner's reward."),
  (Y, "Blocks give the network a rhythm and an order. Transactions arrive continuously and in different orders at different nodes, so the network needs a periodic moment at which one set of transactions is fixed. The chapter explains that a transaction is confirmed when it is included in a block, which happens every 10 minutes on average and is called clearing in traditional financial terms [AH]. A block is also the unit in which the reward is paid and the unit that proof of work protects."),
  (E, "Blocks are seen in every block explorer and every wallet that displays a confirmation count. The data of the first block, saved from the explorer of Blockstream, shows that it contains one transaction, whereas block 840000, in which the fourth halving took effect, contains 3050 transactions [BS]. The size of a block therefore varies with the demand for space, even though its rhythm is steady."),
  (H, "A miner collects waiting transactions, places a special reward transaction first, and builds a block header that contains, among other data, the hash of the previous block, a summary of the transactions and the time. The miner then searches for a header whose hash is small enough, which is the proof of work. Nodes that receive the block check the header, the transactions and the reward, and add the block to their chain only if all checks pass. The glossary adds that the first transaction is created by a miner and includes a single special field, which allows claiming the block reward [AH]."),
  (K, "A block is not a file of money; it records transfers, and the coins themselves are implied by those transfers. A block is also not final the moment it is found, because a rival block at the same height may win, so the transactions inside it gain certainty only as further blocks are added. The number of transactions in a block is not fixed, and the figures in the example are only two data points."),
 ]),
 ("Blockchain", "Blockchain", 3, "Chain", ("a chain of three linked blocks", "The blockchain is the list of validated blocks, each linking to its predecessor all the way back to the first block; changing an old block breaks every later link.", (_CHAIN, "(True, False)")), [
  (W, "The blockchain is the list of validated blocks in which each block links to its predecessor all the way back to the first block, which the glossary of the textbook calls the genesis block [AH]. Chapter 1 also uses the word for the transaction journal: a transaction is confirmed when it has been recorded in the Bitcoin transaction journal, known as the blockchain [AH]. The whitepaper itself speaks of a chain of blocks and of the longest proof-of-work chain."),
  (Y, "Linking the blocks is what turns a pile of records into a history that is hard to rewrite. Each block contains the hash of the one before it, so changing an old block changes its hash, which no longer matches the link stored in the next block. The attacker would have to redo the proof of work for that block and for every block that follows. The whitepaper describes the rule that makes this decisive: nodes treat the longest chain, the one with the most work invested in it, as the correct one [NK]."),
  (E, "The blockchain is stored by every full node, displayed by block explorers and quoted in news reports. The chapter's sidebar on digital currencies before Bitcoin explains why the structure was needed: earlier systems used a central clearinghouse, whereas Bitcoin keeps the public journal itself on a decentralized network [AH]."),
  (H, "The example builds a toy chain in which each block is the SHA-256 hash of the previous hash joined with the block's data. The program creates three blocks, recomputes the chain to check it, and gets True; it then changes the data of the first block, recomputes, and finds that the stored hashes no longer match, which gives False. Bitcoin does the same with real block headers, and adds proof of work, so that rebuilding the chain after a change also costs an enormous amount of computation."),
  (K, "The blockchain is not secret, not encrypted, and not a database that a company controls; its entire content is public. It is also not a guarantee that its content is true: it proves that a transaction was recorded, not that the sale behind the transaction was honest. A final caution concerns the word itself, which is used loosely for any shared ledger; this course reserves it for the chain that the Bitcoin network maintains."),
 ]),
 ("Timestamp", "Timestamp", 3, "Chain", ("the time of the first block", "A timestamp is a recorded time attached to data; each block carries one, and together they place the transactions in an agreed order.", ("str(__import__('datetime').datetime.fromtimestamp(1231006505, __import__('datetime').timezone.utc))", "'2009-01-03 18:15:05+00:00'")), [
  (W, "A timestamp is a label that records the time at which a data object was marked. The Internet Security Glossary defines it as a label or marking in which is recorded the time, of day or other instant of elapsed time, at which the label or marking was affixed to the data object [SH]. In Bitcoin, the glossary of the textbook says that a block is marked with a timestamp [AH]."),
  (Y, "Time gives order, and order is the answer to the double-spend problem: when two transactions spend the same coin, the one that came first counts. The whitepaper builds its solution on this point and begins with a timestamp server, which takes a hash of a block of items to be timestamped and widely publishes the hash, proving that the data must have existed at that time [NK]. Bitcoin replaces the trusted server by the network."),
  (E, "Timestamps are met in block explorers, in file systems and in digital certificates. Each Bitcoin block carries one; the block data of the first block shows the number 1231006505, which counts the seconds since the start of 1 January 1970 in universal time [BS]. Programs convert that number into a calendar date."),
  (H, "The number is a count of seconds, and the example converts it: 1231006505 seconds after the origin of the count is 2009-01-03 18:15:05 in universal time, the moment that the first block's header claims. A timestamp inside a block is set by the miner and is checked only roughly by the nodes, so it is accurate enough to order blocks and to adjust difficulty, but not to settle a dispute about a minute."),
  (K, "A timestamp does not prove that an event happened at that time, only that the data was marked then, and a miner can choose a time within the permitted limits. Block times are also averages: although the target is one block in 10 minutes, individual blocks can arrive seconds or hours apart, so a calendar prediction based on blocks, such as the date of a halving, is an estimate."),
 ]),
 ("Node", "Node", 3, "Chain", ("a computer on the network", "A node is a computer that takes part in the Bitcoin network and runs software that speaks its protocol; full nodes validate blocks and may also route, mine or serve wallets.", None), [
  (W, "A node is a computer that takes part in the Bitcoin network by running software that speaks its protocol. The textbook's chapter on the network defines the term Bitcoin network as the collection of nodes running the Bitcoin peer-to-peer protocol, and says that a Bitcoin full node validates blocks and may contain other functions, such as routing, mining and wallet services [AH]. In everyday use the word means a full node unless something else is said."),
  (Y, "The network has no central server, so the nodes together do the work that a server would do. They receive transactions, check them, pass them on, and keep copies of the chain. Because anyone can run a node, the rules of Bitcoin are enforced by the participants and not by a company, and the more independent nodes there are, the harder it is for any party to change the rules by force."),
  (E, "In the chapter's story, the transaction that Joe's wallet sends spreads from node to node, and after just a few seconds most of the well-connected nodes in the network receive it and see Alice's address for the first time [AH]. Nodes are run by individuals, companies and exchanges, in homes and data centres, on laptops and dedicated machines."),
  (H, "A node connects to several other nodes at random, asks them for the blocks it does not have, checks each block and each transaction against the rules, and relays what it accepts. The network chapter lists the roles a node can take: some keep a complete copy of the chain, some mine, and some offer wallet services [AH]."),
  (K, "A node is not a wallet and not a miner, although one program may play all three roles. A node is also not the same as a user: most users run lightweight wallets that depend on nodes. Finally, the number of nodes is not a measure of security by itself, since many nodes may be run by the same party; what matters is how independent they are."),
 ]),
]
