"""SEN0401 chapter 5, corpus text part E (version 1.0.0): the branch 'Hierarchical deterministic wallet', second half - the extended keys
(the pair of key and chain code, its private and public forms, the base58check serialisation, the fingerprint) and navigating the tree
(the path notation, BIP43's purpose, BIP44's five levels, account, change and address index). Markers such as [AH] become author-year strings."""
from sen0401_ch05_common_v1_0_0 import *

XPRV = "xprv9tyUQV64JT5qs3RSTJkXCWKMyUgoQp7F3hA1xzG6ZGu6u6Q9VMNjGr67Lctvy5P8oyaYAL9CAWrUE9i6GoNMKUga5biW6Hx4tws2six3b9c"
XPUB = "xpub67xpozcx8pe95XVuZLHXZeG6XWXHpGq6Qv5cmNfi7cS5mtjJ2tgypeQbBs2UAR6KECeeMVKZBPLrtJunSDMstweyLXhRgPxdp14sk9tJPW9"
_B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"


def _decode(text, pick):
    """a self-contained base58check decoder of an extended key, written out so that the program also runs in the reader's browser"""
    return ("import hashlib\n"
            "B58 = %r\n"
            "t = %r\n"
            "n = 0\n"
            "for ch in t: n = n * 58 + B58.index(ch)\n"
            "raw = n.to_bytes(82, 'big')\n"
            "ok = hashlib.sha256(hashlib.sha256(raw[:-4]).digest()).digest()[:4] == raw[-4:]\n"
            "result = %s" % (_B58, text, pick))


NODES_E = [
 ("ExtendedKeys", "Extended keys", 2, "HdWallet", None, P(
  (W, "This group is about the object a wallet actually passes around. The chapter introduces it from the derivation function: the function needs a key, a chain code and an index, of which the two essential ingredients are the key and the chain code, and combined these are called an extended key; the term could also be thought of as extensible key, because such a key can be used to derive children [AH]. The group covers the idea, its two forms, the way it is written as text and the short identifier that points back to a parent."),
  (Y, "The group matters because extended keys are what users copy and paste, and because what they can do is easy to misjudge. The chapter gives the right picture: think of an extended key as the root of a branch in the tree structure, with which the rest of the branch can be derived, where the extended private key can create a complete branch and the extended public key can only create a branch of public keys [AH]. A reader who understands that sentence can tell, of any string beginning xprv or xpub, what has been handed over."),
  (H, "The sections take the object apart. The first explains the pair itself and how it is stored, as the concatenation of the key and the chain code. The second and third treat the private and the public form, each with the operations it permits and the risks it carries. The fourth explains the base58check encoding that gives the familiar prefixes and the 78 bytes behind them. The last covers the key fingerprint, the four bytes by which software recognises a parent, which the reader will meet again in the key origin of a descriptor.")), None),

 ("ExtendedKey", "Extended key", 3, "ExtendedKeys", ("78 bytes before encoding",
   "An extended key is a key together with its chain code, stored as the two concatenated; it is the root of a branch and is what a derivation function needs.",
   ("4 + 1 + 4 + 4 + 32 + 33", "78")), P(
  (W, "An extended key is the pair consisting of a key and a chain code. The chapter says that extended keys are stored and represented simply as the concatenation of the key and the chain code, and that there are two types, the extended private key, which is a private key with a chain code and can derive child private keys and from them child public keys, and the extended public key, which is a public key with a chain code and can create child public keys only [AH]. BIP32 writes the private pair as k with c and the public pair as K with c, where K is the point for k [B32]."),
  (Y, "The pairing is necessary because neither half derives anything alone. The chain code is the key of the HMAC and the key is part of its message, so a derivation needs both, which is why the standard introduced the chain code in the first place: to stop derived keys depending solely on the key itself [B32]. Treating the pair as one object also makes the tree easy to talk about, since every node of the tree is exactly one extended key."),
  (E, "A reader meets extended keys in text form, which the serialisation section explains, and in the structure the chapter describes as a branch root. The worked example counts the bytes of BIP32's serialisation before the checksum: four version bytes, one of depth, four of parent fingerprint, four of child number, 32 of chain code and 33 of key data make 78, which the standard calls this 78-byte structure [B32]. The key data is 33 bytes in both forms, which is why the two are the same length: a compressed public key is 33 bytes, and a private key is padded with a leading zero byte to match [B32]."),
  (H, "The depth and the child number in that layout are what let software place a key in the tree: the depth is zero for a master node, one for a level-1 derived key and so on, and the child number is the index with which this key was derived, zero for a master key [B32]. Neither is needed for the arithmetic of derivation; both are recorded so that an extended key can be interpreted without being told where it came from. BIP32 also requires an importing implementation to check that the public key data corresponds to a point on the curve, and declares the key invalid if it does not [B32]."),
  (K, "The chapter's own phrase, that extended keys are stored simply as the concatenation of the key and the chain code, describes the pair and not the serialised string, which carries five more fields and a checksum [AH] [B32]. A second caution is that an extended key is not a wallet: it says nothing about which script types or which paths were used, which is the gap that descriptors fill in the next branch [B380].")), None),

 ("ExtendedPrivateKey", "Extended private key", 3, "ExtendedKeys", ("the book's xprv, decoded",
   "An extended private key is a private key with its chain code; it can derive every descendant key, private and public, and is written with the prefix xprv.",
   (PROG(_decode(XPRV, "(ok, raw[:4].hex(), raw[4], raw[45])")), "(True, '0488ade4', 1, 0)")), P(
  (W, "An extended private key is the extended key whose key half is private. The chapter says it is the combination of a private key and chain code and can be used to derive child private keys, and from them child public keys [AH]. BIP32 adds what that implies for the whole subtree: knowing an extended private key allows reconstruction of all descendant private keys and public keys [B32]. The chapter prints an example, a 111-character string beginning xprv9tyUQ, and the worked example decodes exactly that string."),
  (Y, "Such a key is the most dangerous object in a wallet after the seed, and the most useful. It is what a signing device holds, what a cold backup contains and what has to be kept offline; BIP32's use cases list full wallet sharing as the case in which two systems both need to spend and therefore the master private extended key must be shared [B32]. Because one such key stands for an unbounded number of future keys, losing control of it cannot be repaired by generating new addresses."),
  (E, "The worked example takes the chapter's printed xprv and decodes it with nothing but base58 arithmetic and SHA-256: the checksum is correct, the version bytes are 0488ade4, the depth is 1, and the 33 bytes of key data begin with a zero byte, the padding BIP32 prescribes for a private key [AH] [B32]. The depth of 1 is worth noticing: the key the chapter prints as an example is not a master key but a level-1 child, and its parent fingerprint is not zero."),
  (H, "The operations the key permits follow from the previous group. With the chain code it derives any child, normal or hardened; by multiplication it gives the matching public key; by discarding the private half it gives the extended public key, which BIP32 calls the neutered version, since it removes the ability to sign transactions [B32]. The claims of this chapter check that the extended public key the chapter prints beside its xprv is exactly the neutered form of it, which is how a reader can confirm the two strings are a pair."),
  (K, "Two warnings belong here. The first is that an extended private key is not protected by being long or unfamiliar: anyone who copies the string has the subtree. The second is about the prefix: the version bytes are chosen so that base58 encoding yields xprv on mainnet and tprv on testnet, and BIP49 and BIP84 define further version bytes that give yprv and zprv for their own script types, so a string that does not begin xprv may still be an extended private key [B32] [B49] [B84]. BIP43 recommends against that practice, suggesting that the xpub and xprv prefixes always be used and the purpose level carry the meaning instead [B43].")), None),

 ("ExtendedPublicKey", "Extended public key", 3, "ExtendedKeys", ("111 characters of base58check",
   "An extended public key is a public key with its chain code: it derives all the normal public keys of its branch and none of the private ones, and is written with the prefix xpub.",
   ("len('%s')" % XPUB, "111")), P(
  (W, "An extended public key is the extended key whose key half is public. The chapter says it is a public key and chain code which can be used to create child public keys, public only, and that an extended public key can therefore be used to derive all of the public keys, and only the public keys, in that branch of the wallet [AH]. It is abbreviated xpub after its prefix, and the worked example counts the characters of the chapter's own example: 111, the length BIP32 says the encoding always has [B32]."),
  (Y, "This is the object that makes the standard worth having, and the chapter gives its two classic uses. One is to install an extended public key on a web server serving an online shop, so that the server can create a new address for every transaction while holding no private keys that could be stolen [AH]. The other is cold storage: the extended private key is kept on paper or on a hardware device while the extended public key is kept online, so that receive addresses can be created at will while the private keys stay offline [AH]. BIP32's own use cases add audits, where all account public keys are shared so that an auditor can see every payment but no secret key [B32]."),
  (E, "A reader meets xpubs in several concrete places in this course. The chapter's web store section has Gabriel export one from a hardware signing device and copy it into his payment processing software [AH]. The descriptors of the wallet created by Bitcoin Core 31.1 for this chapter each contain an xpub with its key origin, for example an account at m/84h/0h/0h followed by the branch 0 and a wildcard [B31]. BIP329's label export format even defines a record type whose reference is an extended public key as defined by BIP32 [B329]."),
  (H, "The derivation it permits is the public function of the previous group, and the limits are exact. Normal children can be derived, hardened children cannot, and no private key is reachable; BIP32 states the identity that makes this work and the failure for hardened indices [B32]. The chapter also notes what is unchanged: the chain code inside the xpub is the same as the one inside the matching xprv, which is what allows the two to produce the same public keys by different routes [AH] [B32]."),
  (K, "An extended public key must be protected even though it cannot spend. BIP32 says that leaking a public key can mean loss of privacy, that more care must be taken with extended keys because they correspond to a whole subtree, and warns of the leak that a non-hardened child private key makes possible; the chapter repeats the practical version of that, that a leaked child private key with a parent chain code reveals all the children and even the parent private key [B32] [AH]. The defence is to derive the shared xpub below a hardened step, which is what the standard paths of the next branch do.")), None),

 ("ExtendedKeyEncoding", "Extended key encoding", 3, "ExtendedKeys", ("the book's xpub, decoded",
   "An extended key is written in base58check with four version bytes, which is what produces the recognisable xprv and xpub prefixes and a fixed length of 111 characters.",
   (PROG(_decode(XPUB, "(ok, raw[:4].hex(), raw[45])")), "(True, '0488b21e', 2)")), P(
  (W, "The encoding is how an extended key becomes a string a person can copy. The chapter says that extended keys are encoded using base58check to make them easy to export and import between compatible wallets, and that the encoding uses a special version number that results in the prefixes xprv and xpub when encoded in base58 characters, to make them easily recognisable; it adds that because an extended key contains many more bytes than a regular address, the string is much longer than the base58check strings seen earlier [AH]. Base58check itself is the encoding chapter 4 of the book explains."),
  (Y, "A readable encoding with a checksum is what makes the key transferable at all. The checksum catches typing errors before any derivation is attempted, and the version prefix tells the reader and the software what kind of object they have, which matters because an extended public and an extended private key are otherwise the same length and shape. The fixed length of 111 characters is itself a check: a string of another length is not a mainnet extended key [B32]."),
  (E, "The worked example decodes the chapter's own xpub with base58 arithmetic and a double SHA-256: the checksum holds, the version bytes are 0488b21e, and the key data begins with the byte 2, the prefix of a compressed public key with an even y coordinate [AH] [B32]. The claims of this chapter decode the matching xprv in the same way and show that the two strings differ only in the version bytes and the key data, having the same depth, parent fingerprint, index and chain code."),
  (H, "The layout and the constants are given by BIP32: four version bytes, which on mainnet are 0x0488B21E for public and 0x0488ADE4 for private and on testnet 0x043587CF and 0x04358394; one byte of depth; four bytes of parent fingerprint; four bytes of child number; 32 bytes of chain code; and 33 bytes of key data; the 78-byte structure is then encoded like other Bitcoin data in base58 by adding 32 checksum bits derived from the double SHA-256 and converting, which results in exactly 111 characters [B32]. Because of the choice of version bytes the string begins xprv or xpub on mainnet and tprv or tpub on testnet [B32]."),
  (K, "The prefixes are a convention about display, not a statement about derivation, and this has caused real confusion. BIP49 and BIP84 define alternative version bytes producing ypub and zpub for their script types, and BIP43 argues against the whole practice, suggesting that 0x0488B21E and 0x0488ADE4 always be used because a scheme may generate nodes for several currencies or for something unrelated to currencies at all [B49] [B84] [B43]. BIP380 makes the same criticism of version-byte tricks, calling them a layer violation because key derivation should be separate from script type meaning [B380]. A learner should therefore read the prefix as a hint and the descriptor or the path as the truth.")), None),

 ("KeyFingerprint", "Key fingerprint", 3, "ExtendedKeys", ("the first 32 bits of an identifier",
   "A key fingerprint is the first four bytes of the hash identifier of an extended key, used as a short, non-unique label for the parent a derivation started from.",
   ("len('0a2683ed') * 4", "32")), P(
  (W, "A key fingerprint is a four-byte label for an extended key. BIP32 defines it in two steps: extended keys can be identified by the hash of the serialised public key, that is RIPEMD-160, another hash function, applied after SHA-256, ignoring the chain code, which is exactly the data used in traditional Bitcoin addresses; and the first 32 bits of that identifier are called the key fingerprint [B32]. The worked example counts those bits: eight hexadecimal digits, four bits each, make the 32 bits of the fingerprint."),
  (Y, "The fingerprint exists so that software can match a child with its parent quickly. BIP32 says that it serves only as a fast way to detect parent and child nodes in software, that software must be willing to deal with collisions, and that internally the full 160-bit identifier could be used [B32]. It is therefore a convenience, not an identity, and a design that treats it as unique is wrong."),
  (E, "A reader meets the fingerprint in two places. It is one of the fields inside every serialised extended key, where it records the parent: the chapter's own example xprv and xpub both carry the parent fingerprint 0a2683ed, which the claims of this chapter read out of the decoded bytes [AH]. And it is the first element of the key origin of a descriptor, where BIP380 requires exactly eight hexadecimal characters for the fingerprint of the key where the derivation starts; the evidence of this chapter shows Bitcoin Core writing such origins, for example the fingerprint 6d8c4b8f followed by the path 84h/0h/0h [B380] [B31]."),
  (H, "The computation is the hash160 of chapter 4 applied to the compressed public key and truncated. One consequence is that a fingerprint can be computed from a public key alone, so a wallet holding only an xpub can state the origin of the keys it derives. Another is that it cannot be computed in the course's browser pages, because the Python available there has no RIPEMD-160 implementation, which is why the fingerprints in this chapter's examples are given as data read from real wallets and standards rather than recomputed in the page."),
  (K, "BIP32 warns against reading too much into the identifier, and the warning has two parts. The first is the collision risk already mentioned: four bytes are not an identity. The second concerns the full identifier: it is not advised to represent that data in base58 format, because it may be interpreted as an address, and wallet software is not required to accept payment to the chain key itself [B32]. The practical rule for a student is that a fingerprint is a lookup hint recorded for convenience, and that the authority for which key is meant is the full extended key or the descriptor that contains it.")), None),

 ("TreeNavigation", "Navigating the tree", 2, "HdWallet", None, P(
  (W, "This group is about saying which key of the tree is meant. The chapter introduces the notation first: keys in an HD wallet are identified using a path naming convention, with each level of the tree separated by a slash, where private keys derived from the master private key start with m and public keys derived from the master public key start with M [AH]. It then presents the two standards that give the levels a meaning, BIP43, which reserves the first level for a purpose, and BIP44, which defines five levels for multi-account wallets [AH]."),
  (Y, "The group matters because the tree is unmanageably large without a convention. The chapter sets out the problem: each parent extended key can have four billion children, each of those another four billion, the tree can be as deep as one likes, and with all that flexibility it becomes quite difficult to navigate, and especially difficult to transfer wallets between implementations, because the possibilities for internal organisation are endless [AH]. Two standards narrow that down to a handful of paths every wallet understands."),
  (H, "The sections begin with the notation itself, then the purpose level of BIP43, then BIP44's five-level structure, and then the three levels of that structure a user meets by name: the account, the change branch and the address index. Each section recomputes the chapter's own examples, including the paths printed in its two tables, so that a reader can read any path in the course's later material and say exactly which key it names.")), None),

 ("KeyPath", "Key path", 3, "TreeNavigation", ("m/84h/0h/0h/0/2 as five indices",
   "A key path names a key by the sequence of indices from the root, written with slashes, beginning m for private or M for public keys, with a prime or h for hardened steps.",
   ("[int(p.rstrip('h')) + (2 ** 31 if p.endswith('h') else 0) for p in 'm/84h/0h/0h/0/2'.split('/')[1:]]",
    "[2147483732, 2147483648, 2147483648, 0, 2]")), P(
  (W, "A key path is the name of one key, written as the route from the root to it. The chapter gives the rules: each level is separated by a slash; private keys derived from the master private key start with m and public keys from the master public key with M; so the first child private key of the master private key is m/0 and the first child public key is M/0, while the second grandchild of the first child is m/0/1 [AH]. BIP32 uses the same shorthand and notes the identity that lets a path be read either way: neutering at any level and then deriving publicly gives the same keys as deriving privately and neutering at the end [B32]."),
  (Y, "The notation is what makes a backup complete. A recovery code gives the seed, but the chapter's whole next branch exists because the seed does not say which paths a wallet used, and a path written down removes that ambiguity. A path is also the unit in which wallets and devices talk to each other: a signing device is asked for a signature at a path, and a descriptor records the path by which an extended key was reached [B380]."),
  (E, "A reader meets paths everywhere in this course from here on, and the worked example converts one of them into the numbers a derivation function actually uses: m/84h/0h/0h/0/2 is the five indices 2147483732, 2147483648, 2147483648, 0 and 2, where the first three are hardened, being 2 to the 31 plus 84, 0 and 0 [AH]. The evidence files of this chapter show a real wallet reporting such a path for its first address, m/84h/0h/0h/0/0 [B31]."),
  (H, "Reading a path is mechanical: start at the root, apply the derivation function once for each element, choosing the hardened variant where the element carries a prime or an h, and the key named is the one left at the end. The chapter gives the rule for reading the other way, which is how its table is written: the ancestry of a key is read from right to left until the master key is reached, so m/x/y/z is the z-th child of m/x/y, which is the y-th child of m/x, which is the x-th child of m [AH]. The claims of this chapter check every row of the chapter's own table of path examples against the derivations the notation implies."),
  (K, "Three details trip readers up. The capital M means only that the key named is public; it is not a different tree, and M/0 is the public key of m/0 [AH]. A hardened step cannot be taken from a public parent, so a path that contains a prime after an M is meaningless unless the prime comes above the point at which the public key was taken [B32]. And a path alone does not say which script type the key is for, which is why the two paths m/44h/0h/0h and m/84h/0h/0h, differing only in the purpose level, mean different kinds of address [B44] [B84].")), None),

 ("Bip43Purpose", "Purpose level (BIP43)", 3, "TreeNavigation", ("44 hardened is 0x8000002c",
   "BIP43 reserves the first hardened level of a BIP32 tree for a purpose number that says which scheme the rest of the tree follows, and recommends using the scheme's own BIP number.",
   ("hex(2 ** 31 + 44)", "'0x8000002c'")), P(
  (W, "The purpose level is the first level of the tree, used as a label for the structure below it. The chapter says that BIP43 proposes the use of the first hardened child index as a special identifier that signifies the purpose of the tree structure, and that an HD wallet should use only one level-1 branch, with the index number identifying the structure and namespace of the rest of the tree by defining its purpose, so that a wallet using only the branch m/i followed by a prime signifies a specific purpose identified by that number [AH]. BIP43 writes the pattern as m / purpose' / and notes that the apostrophe indicates hardened derivation [B43]."),
  (Y, "The level exists because BIP32 alone does not make wallets interoperable. BIP43's motivation says this bluntly: although the hierarchical structure of BIP32 is an important step, the specification offers implementers too many degrees of freedom, so multiple implementations may claim to be BIP32 compatible while in fact producing wallets with different logical structures, which renders the statement BIP32 compatible rather useless [B43]. A purpose number turns a claim about an algorithm into a claim about a layout."),
  (E, "A reader meets purpose numbers as the first element of every standard path: 44 for the multi-account hierarchy, 49 for segwit nested in a script hash, 84 for native segwit and 86 for single-key taproot, each a hardened index [B44] [B49] [B84] [B86]. The worked example converts the first of them: 2 to the 31 plus 44 is 0x8000002c, which is exactly the value BIP43 gives when it says that the scheme described in BIP44 should use 44 with a prime, or 0x8000002C, as purpose [B43]."),
  (H, "The convention is a request rather than a mechanism, and BIP43 states how it is meant to be followed: different schemes are encouraged to apply for a separate BIP number and use the same number for the purpose field, so that addresses are not generated from overlapping BIP32 spaces; purpose codes from 10001 to 19999 are reserved for the SatoshiLabs improvement proposals; and the branch m/0' is already taken by BIP32's default account, which preceded the proposal [B43]. The standard also suggests that software needing only a limited structure should describe it in another BIP with a different purpose value rather than claim partial compatibility [B43]."),
  (K, "Two points are easy to miss. The first is that the purpose level is hardened, so nothing above it can be shared as an extended public key and the purpose cannot be read off a shared xpub. The second is that the number is a namespace and not a feature list: a wallet that finds a tree under 44' knows which document describes the layout, but still has to support that document, which is exactly the forward-compatibility problem Electrum's version numbers were designed to solve from the other end [EL] [B43].")), None),

 ("Bip44Structure", "BIP44 structure", 3, "TreeNavigation", ("five predefined levels",
   "BIP44 defines the five levels purpose, coin type, account, change and address index under purpose 44 hardened, with the first three hardened and the last two normal.",
   ("len('m / purpose / coin_type / account / change / address_index'.split(' / ')) - 1", "5")), P(
  (W, "BIP44 is the layout that gives a tree its familiar shape. The chapter says that, extending BIP43, BIP44 proposes a multi-account structure as purpose number 44 with a prime, that all wallets following the structure are identified by using only the branch m/44', and that the structure consists of five predefined tree levels: purpose, coin type, account, change and address index [AH]. The worked example counts them in the chapter's own line: five levels below m."),
  (Y, "The structure answers the two questions a wallet has to answer before it can scan anything: which currency and which account. BIP44's motivation says the hierarchy is comprehensive, allowing the handling of multiple coins, multiple accounts, external and internal chains per account and millions of addresses per chain [B44]. Because the layout is fixed, a wallet restored from a code knows where to look, which is the whole point of what the next branch calls an implicit path."),
  (E, "A reader meets the structure in the chapter's own examples and in real wallets. The chapter explains the first two levels: the purpose is always 44 with a prime; the coin type specifies the type of cryptocurrency, allowing multi-currency wallets where each currency has its own subtree, with Bitcoin at m/44'/0' and Bitcoin testnet at m/44'/1' [AH]. BIP44 registers exactly those two values and refers to SLIP-0044 for the rest, whose table gives 0 for Bitcoin, 1 for testnet and 2 for Litecoin, the coin in the chapter's third table row [B44] [S44]. Bitcoin Core's own descriptor wallets use the same shape, and its documentation records BIP44 as used by default since version 0.21.0 [BC] [B31]."),
  (H, "The division of hardened and normal levels is the part worth learning by heart. BIP44 says hardened derivation is used at the purpose, coin type and account levels, and public derivation at the change and index levels [B44]; the chapter explains why: the change level uses normal derivation to allow this level of the tree to export extended public keys for use in a non-secured environment [AH]. An account's extended public key can therefore be given to a server, which can derive both the receive and the change branches, while the account itself is hardened so that a leak below it cannot reach the master key [B32]."),
  (K, "BIP44 adds rules about discovery that a reader should know before trusting a restoration. Software should prevent the creation of an account if the previous account has no transaction history, and after importing a seed it should discover accounts by deriving the first account, scanning its external chain while respecting the gap limit, and continuing only while transactions are found; the standard sets that gap limit at 20 addresses and says wallets should warn when a user exceeds it [B44]. The chapter's own sidebar on the gap limit, in the next branch, shows how production systems stretch that number.")), None),

 ("AccountBranch", "Account branch", 3, "TreeNavigation", ("the second account of a BIP44 wallet",
   "The account level is the third level of a BIP44 path, hardened, which splits a wallet into independent subaccounts that never mix coins.",
   ("'m/44h/0h/%dh' % 1", "'m/44h/0h/1h'")), P(
  (W, "The account branch is the third level of a BIP44 path. The chapter says that the third level of the tree is the account, which allows users to subdivide their wallets into separate logical subaccounts for accounting or organisational purposes, and gives the example of a wallet containing two Bitcoin accounts, m/44'/0'/0' and m/44'/0'/1', each the root of its own subtree [AH]. The worked example writes the second of those paths from its index."),
  (Y, "Accounts are the level at which a wallet becomes usable by an organisation. BIP44 says the level splits the key space into independent user identities so that the wallet never mixes coins across accounts, and suggests the same uses the chapter does, organising funds as bank accounts are organised, for donations where all addresses are considered public, for savings, or for common expenses [B44]. BIP32's use cases add the per-office case, in which several offices use wallets derived from one master while headquarters keeps a super-wallet that sees all of them [B32]."),
  (E, "A reader meets accounts as the third element of a path and as the unit a wallet exports. The extended public key a wallet hands to a server or an auditor is normally the account key, which is why the descriptors of the Bitcoin Core wallet in the evidence of this chapter each name an account, such as the origin 6d8c4b8f followed by 84h/0h/0h, and then the branch and index below it [B31] [B380]. BIP32's audit use case describes sharing all account public extended keys so that an auditor sees all transactions but no secret key [B32]."),
  (H, "The level is hardened, and that is the design decision that makes it safe to export. Because the account key is derived with a hardened step, its extended public key cannot be used to work back to the master key even if a private key below it leaks, which BIP32 gives as the reason hardened keys are used at the account level: a leak of account-specific or lower private keys never risks compromising the master or other accounts [B32]. Accounts are numbered from zero and increase sequentially, and the number is the child index of the derivation [B44]."),
  (K, "The word account here means a branch of a key tree and nothing more: it is not an account in the sense of a balance held somewhere, and no one but the wallet's owner can tell that two addresses belong to the same account. A reader should also note the discovery rule that goes with the level: because software is told not to create an account unless the previous one has history, a wallet restored from a code stops looking after the first account with no transactions, so an account created out of order can be missed [B44].")), None),

 ("ChangeBranch", "Change branch", 3, "TreeNavigation", ("the fifteenth change address of the fourth account",
   "The fourth level of a BIP44 path is 0 for the external chain, whose addresses are given out, and 1 for the internal chain, which receives change; both use normal derivation.",
   ("'M/44h/0h/%dh/%d/%d' % (3, 1, 14)", "'M/44h/0h/3h/1/14'")), P(
  (W, "The change branch is the fourth level of a BIP44 path, and it has only two values. The chapter says that on the fourth level, change, an HD wallet has two subtrees, one for creating receiving addresses and one for creating change addresses, and notes that whereas the previous levels used hardened derivation, this level uses normal derivation [AH]. BIP44 fixes the numbers: the constant 0 is used for the external chain and 1 for the internal chain, also known as change addresses [B44]."),
  (Y, "The split exists because the two kinds of address have different audiences. BIP32 explains the distinction when it describes the default layout: the external keychain is used to generate new public addresses while the internal keychain is used for all other operations, change addresses and anything that does not need to be communicated, and clients that do not support separate chains should use the external one for everything [B32]. Chapter 2 of the book explained why change exists at all: a payment usually spends more than it sends and returns the remainder to its own wallet."),
  (E, "The worked example writes one of the chapter's own table rows: M/44'/0'/3'/1/14, which the chapter describes as the fifteenth change-address public key for the fourth Bitcoin account [AH]. The same structure appears in every descriptor pair of the Bitcoin Core wallet in this chapter's evidence, where two descriptors share an account key and differ only in that branch, one marked internal and one not [B31]. BIP389's multipath notation, in the next branch, exists precisely to write those two descriptors as one [B389]."),
  (H, "Normal derivation at this level is what makes an account's extended public key useful, and the chapter says so: this is to allow this level of the tree to export extended public keys for use in a non-secured environment [AH]. A server given the account xpub can derive both branches, so it can recognise change as well as receipts; BIP44 notes the asymmetry that follows for scanning, saying that only external chains need be scanned because internal chains receive only coins that come from the associated external chains [B44]."),
  (K, "Two cautions. The first is that change addresses are addresses of the same wallet, so a tool that scans only branch 0 will under-report a balance, and one that hands out addresses from branch 1 will leak which outputs are change. The second is that the numbering is a convention of BIP44 and its successors, not a rule of BIP32: a wallet is free to use another layout, and BIP32's own default simply calls the two chains internal and external without fixing the indices in the same words [B32] [B44].")), None),

 ("AddressIndex", "Address index", 3, "TreeNavigation", ("the third receiving address of an account",
   "The fifth level of a BIP44 path is the address index, counted from zero with normal derivation, and it is the level a wallet advances each time it needs a new address.",
   ("'M/44h/0h/0h/0/%d' % (3 - 1)", "'M/44h/0h/0h/0/2'")), P(
  (W, "The address index is the last level of a BIP44 path. The chapter says that usable addresses are derived by the wallet as children of the fourth level, making the fifth level the address index, and gives an example: the third receiving address for payments in the primary account would be M/44'/0'/0'/0/2 [AH]. The worked example writes exactly that path from the ordinal, since the third address has index 2. BIP44 adds that addresses are numbered from index 0 in sequentially increasing manner and that public derivation is used at this level [B44]."),
  (Y, "This level is where privacy is won or lost. The chapter's web store section explains the gain: a unique address for every customer order immediately improves privacy and gives each order a unique identifier for tracking which invoices have been paid [AH]. The chapter's first branch made the opposite case, that using a single key severely reduces the privacy of that user and of everyone they transact with [AH]. Advancing the index is the cheap way to avoid that."),
  (E, "A reader meets the index as the number at the end of every descriptor and every reported path. The wallet created by Bitcoin Core 31.1 for this chapter reports its first address at m/84h/0h/0h/0/0, and its descriptors end in a wildcard with a range from 0 to 999, which is the pool of indices it has prepared [B31]. The chapter's table of BIP44 examples gives three more rows, which the claims of this chapter reproduce by derivation [AH]."),
  (H, "Because the level uses normal derivation, the whole sequence of addresses can be produced from the account's extended public key, which is what the web store does. The consequence for software is that a wallet must decide how many indices to prepare in advance: Bitcoin Core calls this a keypool and sets it to 1,000 pre-generated keys or scripts by default, describing it as part of the look-ahead process used to detect payments [BCW]. The next branch's section on the gap limit explains what happens when a user runs past that pool."),
  (K, "The index is not visible to anyone else, and that cuts both ways. Nobody can tell from an address that it is the third of an account, which is good for privacy; but neither can a restored wallet tell how far a user had gone, which is why scanning stops after a run of unused indices and why a payment to a far-away index can be missed [B44] [AH]. A reader should also not confuse the index with the number of addresses a wallet has used: indices may be skipped when an address is given out and never paid.")), None),
]

CHECKS_E = [
 # extended keys
 Qb("ch05_wallets.adoc", "The two essential\ningredients are the key and chain code, and combined these are called an\n_extended key_",
    "The term \"extended key\" could also be thought of as\n\"extensible key\" because such a key can be used to derive children",
    "Extended keys are stored and represented simply as the concatenation of\nthe key and chain code",
    "An extended private key is the\ncombination of a private key and chain code and can be used to derive\nchild private keys",
    "An extended\npublic key is a public key and chain code, which can be used to create\nchild public keys (_public only_)",
    "Think of an extended key as the root of a branch in the tree structure\nof the HD wallet",
    "The extended private key can create a complete branch,\nwhereas the extended public key can _only_ create a branch of public\nkeys",
    "Extended keys are encoded using base58check, to easily export and import\nbetween different BIP32-compatible wallets",
    "the prefix \"xprv\" and \"xpub\" when encoded in base58 characters"),
 Qb("ch05_wallets.adoc", XPRV[:77], XPRV[77:], XPUB[:78], XPUB[78:]),
 Qe("bip-0032.mediawiki", "* 4 bytes: version bytes (mainnet: 0x0488B21E public, 0x0488ADE4 private; testnet: 0x043587CF public, 0x04358394 private)",
    "* 1 byte: depth: 0x00 for master nodes, 0x01 for level-1 derived keys, ....", "* 4 bytes: the fingerprint of the parent's key (0x00000000 if master key)",
    "* 32 bytes: the chain code", "* 33 bytes: the public key or private key data (ser<sub>P</sub>(K) for public keys, 0x00 || ser<sub>256</sub>(k) for private keys)",
    "This 78 byte structure can be encoded like other Bitcoin data in Base58, by first adding 32 checksum bits (derived from the double SHA-256 checksum)",
    "This results in a Base58-encoded string of exactly 111 characters",
    "the Base58 representation will start with \"xprv\" or \"xpub\" on mainnet, \"tprv\" or \"tpub\" on testnet",
    "implementations must verify whether the X coordinate in the public key data corresponds to a point on the curve",
    "The function N((k, c)) &rarr; (K, c) computes the extended public key corresponding to an extended private key (the \"neutered\" version, as it removes the ability to sign transactions)",
    "knowing an extended private key allows reconstruction of all descendant private keys and public keys",
    "Extended keys can be identified by the Hash160 (RIPEMD160 after SHA256) of the serialized ECDSA public key K, ignoring the chain code",
    "The first 32 bits of the identifier are called the key fingerprint",
    "the fingerprint of the parent only serves as a fast way to detect parent and child nodes in software, and software must be willing to deal with collisions",
    "It is not advised to represent this data in base58 format though, as it may be interpreted as an address"),
 ("4 + 1 + 4 + 4 + 32 + 33", "78"), ("78 + 4", "82"), ("len('%s')" % XPUB, "111"), ("len('%s')" % XPRV, "111"),
 (PROG(_decode(XPRV, "(ok, raw[:4].hex(), raw[4], raw[45])")), "(True, '0488ade4', 1, 0)"),
 (PROG(_decode(XPUB, "(ok, raw[:4].hex(), raw[45])")), "(True, '0488b21e', 2)"),
 X("W.parse_extended('%s')['version'].hex()" % XPRV, "'0488ade4'"),
 X("W.parse_extended('%s')['version'].hex()" % XPUB, "'0488b21e'"),
 X("(lambda a, b: (a['depth'], a['fp'].hex(), a['index'], a['chain'] == b['chain'], a['depth'] == b['depth'], a['fp'] == b['fp']))(W.parse_extended('%s'), W.parse_extended('%s'))" % (XPRV, XPUB),
   "(1, '0a2683ed', 0, True, True, True)"),
 X("(lambda p: W.serialize_xpub(W.ec_mul(int.from_bytes(p['key'][1:], 'big')), p['chain'], p['depth'], p['fp'], p['index']))(W.parse_extended('%s'))" % XPRV, "'%s'" % XPUB),
 X("len(W.b58check_decode('%s'))" % XPRV, "78"),
 ("len('0a2683ed') * 4", "32"),
 X("len(W.fingerprint(W.ec_mul(1)))", "4"),
 Qe("bip-0043.mediawiki", "We suggest to use always 0x0488B21E for public and 0x0488ADE4 for private nodes (leading to prefixes \"xpub\" and \"xprv\" respectively)",
    "Because this scheme can be used to generate nodes for more cryptocurrencies at once, or even something totally unrelated to cryptocurrencies, there's no point in using a special version magic"),
 Qe("bip-0049.mediawiki", "Extended public keys use <code>0x049d7cb2</code> to produce a \"ypub\" prefix, and private keys use <code>0x049d7878</code> to produce a \"yprv\" prefix"),
 Qe("bip-0084.mediawiki", "Extended public keys use <code>0x04b24746</code> to produce a \"zpub\" prefix, and private keys use <code>0x04b2430c</code> to produce a \"zprv\" prefix"),
 Qe("bip-0380.mediawiki", "Solutions such as introducing different version bytes for extended key serialization both are a layer violation (key derivation should be separate from script type meaning)",
    "Exactly 8 hex characters for the fingerprint of the key where the derivation starts (see BIP 32 for details)"),
 Qe("core_fresh_wallet_31_1_v1_0_0.json", "[6d8c4b8f/84h/0h/0h]", "[6d8c4b8f/44h/0h/0h]", "[6d8c4b8f/49h/0h/0h]", "[6d8c4b8f/86h/0h/0h]"),
 # paths and the two standards
 Qb("ch05_wallets.adoc", "identified using a \"path\" naming convention, with each level of the tree\nseparated by a slash (/) character",
    "Private keys\nderived from the master private key start with \"m.\" Public keys derived\nfrom the master public key start with \"M.\"",
    "the first child\nprivate key of the master private key is m/0", "identifier m/x/y/z\ndescribes the key that is the z-th child of key m/x/y, which is the y-th\nchild of key m/x, which is the x-th child of m",
    "<td><p>m/0'/0</p></td>", "<td><p>M/23/17/0/0</p></td>"),
 Qb("ch05_wallets.adoc", "BIP43 proposes the use\nof the first hardened child index as a special identifier that signifies\nthe \"purpose\" of the tree structure",
    "an HD wallet\nshould use only one level-1 branch of the tree", "BIP44 proposes a multiaccount structure\nas \"purpose\" number +44'+ under BIP43",
    "BIP44 specifies the structure as consisting of five predefined tree levels",
    "m / purpose' / coin_type' / account' / change / address_index",
    "The second-level\n\"coin_type\" specifies the type of cryptocurrency coin", "The third level of the tree is \"account,\"",
    "whereas the previous levels used hardened derivation, this level uses\nnormal derivation. This is to allow this level of the tree to export\nextended public keys for use in a nonsecured environment",
    "making the fifth level of the tree the \"address_index.\""),
 Qb("ch05_wallets.adoc", "<td><p>M/44<code>'</code>/0<code>'</code>/0<code>'</code>/0/2</p></td>", "<td><p>The third receiving public key for the primary Bitcoin account</p></td>",
    "<td><p>M/44<code>'</code>/0<code>'</code>/3<code>'</code>/1/14</p></td>", "<td><p>The fifteenth change-address public key for the fourth Bitcoin account</p></td>",
    "<td><p>m/44<code>'</code>/2<code>'</code>/0<code>'</code>/0/1</p></td>", "<td><p>The second private key in the Litecoin main account, for signing transactions</p></td>"),
 Qe("bip-0043.mediawiki", "the BIP32 specification offers implementers too many degrees of freedom",
    "Multiple implementations may claim they are BIP32 compatible, but in fact they can produce wallets with different logical structures making them non-interoperable",
    "This situation unfortunately renders \"BIP32 compatible\" statement rather useless",
    "m / purpose' / *", "Apostrophe indicates that BIP32 hardened derivation is used",
    "We encourage different schemes to apply for assigning a separate BIP number and use the same number for purpose field, so addresses won't be generated from overlapping BIP32 spaces",
    "Purpose codes from 10001 to 19999 are reserved for", "Scheme described in BIP44 should use 44' (or 0x8000002C) as purpose",
    "Note that m / 0' / * is already taken by BIP32 (default account), which preceded this BIP"),
 Qe("bip-0044.mediawiki", "m / purpose' / coin_type' / account' / change / address_index",
    "It allows the handling of multiple coins, multiple accounts, external and internal chains per account and millions of addresses per chain",
    "Purpose is a constant set to 44' (or 0x8000002C) following the BIP43 recommendation",
    "This level creates a separate subtree for every cryptocoin, avoiding reusing addresses across cryptocoins and improving privacy issues",
    "This level splits the key space into independent user identities, so the wallet never mixes the coins across different accounts",
    "for donation purposes (where all addresses are considered public), for saving purposes, for common expenses etc",
    "Accounts are numbered from index 0 in sequentially increasing manner",
    "Software should prevent a creation of an account if a previous account does not have a transaction history",
    "Constant 0 is used for external chain and constant 1 for internal chain (also known as change addresses)",
    "Addresses are numbered from index 0 in sequentially increasing manner", "Public derivation is used at this level",
    "Address gap limit is currently set to 20", "Wallet software should warn when the user is trying to exceed the gap limit on an external chain by generating a new address",
    "We scan just the external chains, because internal chains receive only coins that come from the associated external chains",
    "|0\n|0x80000000\n|Bitcoin", "|1\n|0x80000001\n|Bitcoin Testnet"),
 Qe("slip-0044.md", "| 0          | BTC     | Bitcoin                           |", "| 1          |         | Testnet (all coins)               |",
    "| 2          | LTC     | Litecoin                          |", "The hardened path component for coin type `n` is computed as `0x80000000 + n`"),
 Qe("bip-0032.mediawiki", "The external keychain is used to generate new public addresses, while the internal keychain is used for all other operations (change addresses, generation addresses, ..., anything that doesn't need to be communicated)",
    "In case an auditor needs full access to the list of incoming and outgoing payments, one can share all account public extended keys",
    "When a business has several independent offices, they can all use wallets derived from a single master",
    "N(m/a/b/c) = N(m/a/b)/c = N(m/a)/b/c = N(m)/a/b/c = M/a/b/c"),
 ("[int(p.rstrip('h')) + (2 ** 31 if p.endswith('h') else 0) for p in 'm/84h/0h/0h/0/2'.split('/')[1:]]", "[2147483732, 2147483648, 2147483648, 0, 2]"),
 X("W.path_indices(\"m/44'/0'/0'/0/2\")", "[2147483692, 2147483648, 2147483648, 0, 2]"),
 X("W.path_indices('m/84h/0h/0h/1/14') == W.path_indices(\"m/84'/0'/0'/1/14\")", "True"),
 ("[hex(2 ** 31 + n) for n in (43, 44, 49, 84, 86)]", "['0x8000002b', '0x8000002c', '0x80000031', '0x80000054', '0x80000056']"),
 ("len('m / purpose / coin_type / account / change / address_index'.split(' / ')) - 1", "5"),
 ("'m/44h/0h/%dh' % 1", "'m/44h/0h/1h'"), ("'M/44h/0h/%dh/%d/%d' % (3, 1, 14)", "'M/44h/0h/3h/1/14'"), ("'M/44h/0h/0h/0/%d' % (3 - 1)", "'M/44h/0h/0h/0/2'"),
 Qe("core_fresh_wallet_31_1_v1_0_0.json", '"hdkeypath": "m/84h/0h/0h/0/0"', '"range": [\n    0,\n    999\n   ]', '"internal": true', '"internal": false'),
 Qc("src/wallet/scriptpubkeyman.h", "inline constexpr unsigned int DEFAULT_KEYPOOL_SIZE = 1000;", "Number of pre-generated keys/scripts (part of the look-ahead process, used to detect payments)"),
 Qc("doc/bips.md", "BIP 44`](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki): The experimental descriptor wallets introduced in **v0.21.0** by default use the Hierarchical Deterministic Wallet derivation proposed by BIP 44"),
 Qb("appc_bips.adoc", "BIP43: The experimental descriptor wallets introduced in v0.21.0 by default use the Hierarchical Deterministic Wallet derivation proposed by BIP43",
    "BIP32: Hierarchical Deterministic Wallets has been implemented since v0.13.0"),
 Pp("Chapter_5_Wallets_v1_0_0.pptx", "HD Wallet Key Identifier (Path)", "Navigating The HD Wallet Tree Structure", "Table 5-7. BIP-44 HD wallet structure examples"),
]
