"""SEN0401 chapter 5, corpus text part A (version 1.0.0): the branch 'Wallet keys' - what a wallet database holds, who signs, and the ways keys come into being
(independent generation, a seed, deterministic generation, key tweaks, the key tree). Markers such as [AH] become author-year strings (sen0401_ch05_common)."""
from sen0401_ch05_common_v1_0_0 import *
SEED_HEX = "f1cc3bc03ef51cb43ee7844460fa5049e779e7425a6349c8e89dfbb0fd97bb73"
K4 = "0x1E99423A4ED27608A15A2616A2B0E9E52CED330AC530EDCC32C8FFC6A526AEDD"   # the private key that chapter 4 of the book works with

NODES_A = [
 ("WalletKeys", "Wallet keys", 1, None, None, P(
  (W, "This first branch of the chapter asks what a Bitcoin wallet really contains and where its keys come from. The chapter begins by correcting a common belief. Wallets for physical cash hold the cash, so many people assume that a Bitcoin wallet holds bitcoins. The book says instead that what many people call a Bitcoin wallet, which it calls a wallet database to tell it apart from the wallet applications that use it, contains only keys, and that those keys are associated with bitcoins recorded on the blockchain [AH]."),
  (Y, "The correction has a practical consequence that shapes the whole chapter. Bitcoin does not store coins in a place that a person can lose; it stores outputs on the blockchain, and a person is the owner of an output only as long as she can prove control of the keys that guard it. The book opens with exactly this warning: losing access to a private key can make it impossible for anyone to spend the bitcoins that were received to the matching public key [AH]. Every technique in the chapter, from seeds to recovery codes to derivation paths, is an attempt to stop the loss of data from turning into a loss of money without weakening security at other times."),
  (E, "Everything in this branch is met in the wallet application that a reader uses. Chapter 1 introduced the wallet as the software through which people use Bitcoin and explained who holds the keys in a custodial and in a noncustodial wallet. Chapter 3 showed the wallet of Bitcoin Core, and Chapter 4 explained how a single private key becomes a public key and an address. The present chapter takes the next step: a real wallet needs many keys, not one, and it has to make them, store them and restore them in a way that survives the loss of a phone, a computer or a hardware signing device."),
  (H, "The branch has two sections. The first, wallet contents, separates the wallet database from the wallet application, shows that a database may hold only some of the keys that a spending transaction needs, and explains why a wallet application may have to work with an external device to produce a signature. The second, key generation methods, follows the history of how keys are made: first independently, one random key at a time, then from a single seed by a deterministic rule, then with key tweaks that let a public key be derived without the private key, and finally as a whole tree of keys under the hierarchical deterministic standard."),
  (K, "Two cautions apply from the start. The word wallet is used loosely, for the database, for the application and for the hardware device, so a statement about wallets should always be read with the question in mind which of the three is meant. And the safe handling of keys is not a one-time decision: the chapter says that the solutions with almost no downsides are simply recommended, while the others have advantages and disadvantages on which wallet authors make different trade-offs [AH]. A learner should expect to meet more than one correct answer.")), None),
 ("WalletContents", "Wallet contents", 2, "WalletKeys", None, P(
  (W, "Wallet contents is the group of ideas that answer a simple question: what is inside a Bitcoin wallet, and what is not? It collects three concepts. The wallet database is the stored collection of keys that a wallet application works with. Some databases hold only public keys, or only some of the private keys that a spending transaction needs. And the signatures that such incomplete databases cannot produce are obtained by external signing, from a hardware device or from other wallets in a multisignature arrangement [AH]."),
  (Y, "The distinction matters because security and convenience pull in opposite directions. A wallet application that sits on a phone or a web server is exposed to theft and mistakes, while a device that keeps the private keys offline is safer and clumsier to use. Splitting the contents of the wallet between a part that can see payments and a part that can sign them lets a design obtain most of the convenience and most of the safety. The same split is what later sections use for cold storage and for the web store whose server holds no private keys."),
  (H, "The three sections that follow go from the inside to the outside. The wallet database explains what is stored and why it holds keys rather than coins. The wallet with public keys only describes a database that can recognise payments but cannot spend. External signing describes the other half of that arrangement: the device or the partners that hold the private keys and return signed transactions to the application.")), None),
 ("WalletDatabase", "Wallet database", 3, "WalletContents", ("a file of keys, not coins", "The wallet database is the stored collection of keys (and the notes about them) that a wallet application reads and writes; it holds the means to prove control of bitcoins, not the bitcoins themselves.", None), P(
  (W, "A wallet database is the stored collection of keys that a wallet application uses. The book introduces the term on purpose: it observes that many people call this thing a Bitcoin wallet, and it prefers the name wallet database so that the data can be told apart from the wallet applications, the programs that read and write it [AH]. The book states the central fact in one sentence: the database contains only keys, and those keys are associated with bitcoins that are recorded on the blockchain."),
  (Y, "This definition corrects an intuition borrowed from cash. A leather wallet that is lost takes its banknotes with it, but a Bitcoin wallet database never contained the bitcoins. What it contains is the ability to prove to Bitcoin full nodes that its owner controls certain keys, and the book says that by proving this to the nodes a person can spend the associated bitcoins [AH]. Control is therefore a matter of knowledge, and the consequences follow directly: whoever copies the keys obtains the ability to spend, and whoever loses every copy of the keys loses it, even though the outputs remain on the blockchain for everybody to see."),
  (E, "Every wallet application has such a database, though it rarely shows it. In Bitcoin Core the database is a file that the program creates for each wallet; the release 31.1 created for this course reported the wallet format as sqlite and the wallet as a descriptor wallet [B31]. Its documentation describes the command backupwallet as one that safely copies the current wallet file to a destination [B31], which is how a user obtains a copy of the database. Simple databases hold both the public keys to which bitcoins are received and the private keys that make the signatures to spend them [AH]."),
  (H, "The database is a long list of entries, and each entry ties a key to what it was created for. In the oldest wallets that was all there was: a private key and its public key, one after another. Modern databases also keep information about how the keys were derived, notes that the user typed, and settings. What matters for recovery is the split between data that can be recomputed and data that cannot. Keys derived from a seed can be recomputed from the seed, while the user's notes cannot, and the later sections of this chapter treat the two cases separately."),
  (K, "The word wallet is still used for the database, so a sentence such as the wallet holds the coins is shorthand that hides the real situation. The same hidden assumption leads people to protect the application, which can be reinstalled, and to neglect the database or the seed, which cannot be replaced. A good habit is to ask of any backup what exactly was saved: the program, the database, the keys or a seed from which the keys can be computed again.")), None),
 ("PublicKeyOnlyWallet", "Wallet with public keys only", 3, "WalletContents", ("receiving without the power to spend", "A wallet database that holds public keys but not the private keys can recognise payments and create receiving addresses but cannot sign a spending transaction.", None), P(
  (W, "Not every wallet database holds everything that a spending transaction needs. The book points out that some databases contain only public keys, and others only some of the private keys that are necessary to authorize a spending transaction [AH]. A wallet application that works with such a database can see the funds sent to its public keys and can show them to the user, but it cannot make the signatures that spending requires. The standard on hierarchical deterministic wallets describes the same idea as sharing a wallet with or without the ability to spend coins [B32]."),
  (Y, "The arrangement is useful because the dangerous part of a wallet is the private key and the convenient part is the knowledge of which payments have arrived. A merchant's web server needs the second and must not have the first, because a server that is hacked can then lose only the funds that arrive later and not those received before. An accountant who audits a business needs to see every incoming and outgoing payment but should not be able to move the money. The standard lists audits and per-office balances among its use cases for exactly this reason [B32]."),
  (E, "Public-key-only wallets appear in three common places. A web store keeps an extended public key on its server so that it can give each customer a fresh address, a case developed later in this chapter. A hardware signing device is paired with a phone or a computer that holds only the public side. And a multisignature wallet is made of several databases, each of which holds only the keys of one participant, so that no single database can spend alone."),
  (H, "The mechanism rests on the one-way relationship between the two keys of a pair. A public key is computed from a private key by elliptic curve multiplication, a calculation that Chapter 4 explained and that cannot be run backwards. A database that keeps only the public keys, or only an extended public key from which further public keys can be derived, has therefore no way to recover the private keys. The standard calls the extended public key that results from removing the private part the neutered version of the extended private key, because it removes the ability to sign transactions [B32]."),
  (K, "A database without private keys is not worthless to an attacker. The standard warns that leaking a public key can mean the loss of privacy, because anyone who holds an extended public key can derive all the addresses below it and so can see the complete history of payments they received [B32]. Such a database must therefore be protected like private information, even though it cannot be used to spend.")), None),
 ("ExternalSigning", "External signing", 3, "WalletContents", ("the application builds, the device signs", "In external signing the wallet application builds a transaction and another party, a hardware signing device or the other signers of a multisignature scheme, holds the private keys and returns the signature.", None), P(
  (W, "External signing means that the program which prepares a transaction is not the one that signs it. The book describes the situation in its discussion of databases without private keys: their wallet applications produce the necessary signatures by working with external tools, such as hardware signing devices or other wallets in a multisignature scheme [AH]. A hardware signing device, which the book notes is sometimes confusingly called a hardware wallet, is a separate device that securely stores a private key and does nothing except sign what it is asked to sign."),
  (Y, "The reason for the separation is the difference in exposure. A phone or a laptop connects to the internet, installs software of uncertain origin and gets infected; a device built only to sign is a much smaller target. The book adds that most hardware signing devices never export private keys, which always remain on the device [AH]. A multisignature scheme goes one step further and spreads the authority itself: Chapter 7 describes a multisignature script as one in which t of k listed public keys must provide signatures before the funds can move [AH7]."),
  (E, "In the book's example, Alice's wallet frontend gives out her public keys to the people who want to pay her. When she wants to spend, she supplies to the hardware signing device the key tweaks that she used, the device derives the needed child private keys, signs the transaction and returns it to the less secure frontend for broadcast to the Bitcoin network [AH]. The same pattern appears in the web store of Gabriel and in every cold storage arrangement that this chapter describes."),
  (H, "The flow has three steps. The application, which knows only public data, assembles an unsigned transaction. The signer receives it, together with enough information to find the right key, and checks what it is asked to sign. Finally the signature is returned and placed in the transaction, which the application broadcasts. At no point does a private key travel to the application, and that is the property that makes the arrangement worth its inconvenience."),
  (K, "External signing protects the keys but not the user's judgement. A signer can only sign what it is shown, so the transaction details displayed by the device must be checked by the user, because a compromised application may have built a transaction that pays someone else. Nor does a hardware signing device remove the need for a backup: if the device is lost, its keys can be restored only from the seed or recovery code that the following sections describe.")), None),
 ("KeyGenerationMethods", "Key generation methods", 2, "WalletKeys", None, P(
  (W, "Key generation methods are the ways a wallet application produces the key pairs that it will later distribute and use. The book separates two ways. In independent key generation, every key is created on its own from random data, and the application must store each one. In deterministic key generation, a single random value, the seed, is expanded by a fixed algorithm into as many keys as needed, so that the same seed always gives the same keys [AH]."),
  (Y, "The choice decides what a user has to back up. With independent keys, every new key makes the old backup out of date; with a seed, a single record made once covers all keys that will ever be derived from it. The history of wallets can be told as the discovery of this fact, followed by a series of refinements: keys whose public halves can be derived on a machine that has no private keys, and a tree of keys in which a branch can be given a purpose, a department or an account."),
  (H, "The group has five concepts in the order of that history. Independent key generation describes the first wallets and their backup problem. The seed is the value from which all later schemes start. Deterministic key generation shows the seed at work with the simplest possible rule. The key tweak explains the property of elliptic curves that lets public keys be derived without private keys. And the hierarchical deterministic standard combines everything into a tree.")), None),
 ("IndependentKeyGeneration", "Independent key generation", 3, "KeyGenerationMethods", ("1,000 keys, 32,000 bytes to back up", "In independent key generation every key is created separately from random data, so every key has to be saved on its own and the backup is out of date after each new key.", ("32 * 1000", "32000")), P(
  (W, "Independent key generation is the method in which a wallet application creates each of the keys that it plans to use independently of the others. Each is a fresh random number with no connection to the rest, and the wallet database is simply the collection of them. The book calls this the earliest design, illustrated as a collection of independently generated keys stored in a wallet database, and notes that all early Bitcoin wallet applications worked this way [AH]. The figure that illustrates it is captioned nondeterministic key generation."),
  (Y, "The method is simple, and its weakness is the backup. The book explains that users had to back up the wallet database each time they generated and distributed new keys, which could be as often as each time they created an address for a new payment. A failure to back up in time meant losing access to any funds received to keys that had not yet been saved. For each independently generated key the user has to back up about 32 bytes plus overhead, a figure that is small for one key and large for a wallet that is used the way privacy advises [AH]."),
  (E, "The design left a mark on user behaviour that the book describes. Some users and applications tried to minimise the data to be backed up by using a single key, which can be secure but severely reduces the privacy of that user and of everyone who transacts with them. People who valued privacy created a new key pair for each transaction, and their wallet databases could only reasonably be backed up on digital media [AH]. The owner's course notes of 2021, written after the second edition, treat the same design under the headings nondeterministic wallet, random wallet and its disadvantages [AL]."),
  (H, "A private key is a 256-bit number, which is 32 bytes. A wallet that holds a thousand independent keys therefore needs at least 32 times 1,000, that is 32,000 bytes, of fresh backup data, and every additional key adds 32 more. The cost grows linearly with the number of keys, and the real burden is not the size but the frequency, because the backup must be repeated whenever the database changes. The standard on hierarchical deterministic wallets records a workaround of the Bitcoin reference client of its time: by default 100 keys were cached in a pool of reserve keys, so that a backup stayed valid for a while [B32]."),
  (K, "Independent keys are not obsolete only in theory: a database that contains them can still be restored only from a backup of the database itself, and no recovery code can regenerate them. Anyone who inherits an old wallet file should check whether its keys were derived from a seed or are independent, because the answer decides whether a seed is enough. The book's closing sentence for the method is a recommendation: modern wallet applications do not generate keys independently but derive them from a single random seed [AH].")), None),
 ("Seed", "Seed", 3, "KeyGenerationMethods", ("a 256-bit random value", "A seed is the random value from which a deterministic wallet derives all its keys; the same seed, with the same algorithm, always gives the same keys.", ("len(bytes.fromhex('f1cc3bc03ef51cb43ee7844460fa5049e779e7425a6349c8e89dfbb0fd97bb73')) * 8", "256")), P(
  (W, "A seed is the starting value of a deterministic wallet. The book defines it in the course of its explanation of hash functions: using the same hash function with the same input, which it calls a seed, will produce the same seemingly random values [AH]. In practice a seed is a large random number, usually 128 to 256 bits according to the book, although the standard on hierarchical deterministic wallets allows between 128 and 512 bits and advises 256 [AH][B32]."),
  (Y, "The seed is the single secret on which all the other keys depend, and this concentrates both the benefit and the risk. The benefit is the backup: a user of deterministic key generation can back up every key in the wallet by recording the seed and a reference to the algorithm. The book illustrates this with Alice, who has received bitcoins to a million different addresses and needs to back up only 64 hexadecimal digits to recover access to all of them [AH]. The risk is symmetric: whoever obtains the seed can generate every private key."),
  (E, "A seed is met whenever a wallet application asks the user to write something down at creation. The words, or the other recovery code that the application shows, are an encoding of the seed or of the value from which it is computed. The root seed of a hierarchical deterministic wallet, which a later concept describes, is the seed in this sense. In this chapter the seed is usually produced from a recovery code, and the next branch explains how."),
  (H, "The book's example seed is the 64-digit hexadecimal number f1cc3bc0 followed by the rest of the value, and it was obtained by hashing some random data from the operating system, a command the book prints. A hexadecimal digit stands for four bits, so 64 digits make 256 bits, or 32 bytes. The seed does not need to look special: its only requirement is that nobody could have predicted it, which means that it must come from a good source of randomness, the entropy that Chapter 4 discussed."),
  (K, "A seed is only as strong as its randomness. The book sets this out when it contrasts recovery codes with brainwallets: humans are very poor sources of randomness, which is why a seed should be created randomly by the wallet application and not chosen by the user [AH]. A second caution is that the seed alone is not always enough to recover everything. The following branches show that a user may also need the derivation paths, a passphrase and the wallet's notes.")), None),
 ("DeterministicKeyGeneration", "Deterministic key generation", 3, "KeyGenerationMethods", ("sha256 of seed plus 0, 1, 2", "Deterministic key generation computes keys from a seed by a fixed rule, such as hashing the seed with a counter, so the same seed always yields the same keys.", ("__import__('hashlib').sha256(('f1cc3bc03ef51cb43ee7844460fa5049e779e7425a6349c8e89dfbb0fd97bb73 + 0' + chr(10)).encode()).hexdigest()", "'50b18e0bd9508310b8f699bad425efdf67d668cb2462b909fdb6b9bd2437beb3'")), P(
  (W, "Deterministic key generation is the creation of keys by a repeatable algorithm. Where independent generation draws a new random number each time, the deterministic method draws one random number, the seed, and computes everything else from it. The book builds the idea on a property of hash functions: a cryptographic hash function always produces the same output for the same input, changes its output unpredictably if the input changes even slightly, and does not let anyone predict the new output even when the new input is known [AH]."),
  (Y, "The property turns one random value into a practically unlimited number of seemingly random values, and, more usefully, makes them reproducible. If the derived values are used as private keys, the same keys can be generated again whenever the seed and the algorithm are available. The book concludes that a user can back up every key in the wallet by simply recording the seed and a reference to the algorithm that was used [AH]. This is the idea on which every wallet recovery scheme of the chapter rests."),
  (E, "The book shows the rule on the command line. A random value is collected and hashed with SHA-256, giving the seed f1cc3bc0 and so on; then a loop hashes the text made of the seed, a plus sign and a counter, for the counters 0, 1 and 2, and prints three values that begin 50b18e0b, a965dbcd and 19580c97 [AH]. The Python program in the worked example does the same calculation. A real wallet does not hash text in this way, but the structure is the same: a secret, a counter, a one-way function and a derived value."),
  (H, "The rule in the book's example is the SHA-256 hash of the text made of the seed, a space, a plus sign, a space, the counter and a line break; the book's command pipes the output of echo into sha256sum, and echo ends its line with a line break that is therefore part of what is hashed. For the counter 0 the result begins 50b18e0b, and the program in the worked example reproduces the whole value. Hashing the same text without the line break gives a different value, which the checks of this chapter confirm. Each derived value is 256 bits, which is the size of a private key. The values are independent in the sense that knowing one gives no practical way to find the seed or the others, because a hash function cannot be run backwards."),
  (K, "This simple scheme is a teaching device, not a wallet standard. It produces a single sequence of keys, and it does not allow public keys to be derived separately from the private ones, which is the flexibility that modern wallets need; the book remarks that modern wallet applications have a more cunning way of achieving this [AH]. A secret seed must be protected as carefully as before, and one more warning applies: the algorithm is part of the backup, so a seed without the name of the rule that was applied cannot be turned back into keys.")), None),
 ("KeyTweak", "Key tweak", 3, "KeyGenerationMethods", ("K plus 123 times G", "A key tweak is a value added to a public key, and in the same way to its private key, so that the child public key can be computed by someone who does not know the private key.", None), P(
  (W, "A key tweak is a number that is added to a key to produce a related key. The book introduces it through the equation that relates a public key to a private key: the public key is the private key multiplied by the generator point of the curve. The book notes that operations on an elliptic curve are not intuitive but are analogous to the addition, subtraction and multiplication of regular arithmetic, and that it is therefore possible to create a derived key pair by adding the same value to both sides of the equation: adding 123 times the generator to a public key gives the public key of the private key increased by 123 [AH]. The value that is added is known as a key tweak."),
  (Y, "The tweak makes it possible to derive child public keys by somebody who knows nothing about the parent private key. The book's story is that Alice generates a public key and gives it to Bob. Bob does not know the private key but knows the global constant, the generator, so he can add any value to Alice's public key. If he then tells Alice the value, she can add the same value to her private key and obtain the private key that matches the public key Bob created [AH]. If a deterministic algorithm generates the tweaks, someone without the private key can derive an essentially unlimited sequence of public keys, and the owner can derive the matching private keys."),
  (E, "The technique is the foundation of the separation between the frontend and the signer that the previous section described. Alice's frontend distributes public keys to those who want to pay her, and when she wants to spend she gives the tweaks to a hardware signing device. The same arithmetic, with a different tweak rule, is behind the extended public keys of the standard, the web store example and the taproot output key of the segwit version 1 addresses in Chapter 4."),
  (H, "Let k be a private key and K = k times G its public key. For any tweak t, K plus t times G equals the point (k plus t) times G, which is the public key of the private key k plus t. The worked checks of this chapter confirm it for the book's private key from Chapter 4, 1E99423A, and for the tweak 123: adding the public key of 123 to K gives the same point as the public key of the key increased by 123. The arithmetic of the private keys is performed modulo the order of the curve, a number that the section on child keys explains."),
  (K, "A tweak is only as private as the rule that produces it. If the tweaks are publicly known, anyone who holds the parent public key can compute all the child public keys, and anyone who learns a child private key can subtract the tweak and obtain the parent private key; the checks of this chapter show the subtraction at work. The standard states the general version of the warning: knowledge of a parent extended public key plus any non-hardened private key descending from it is equivalent to knowing the parent extended private key [B32]. This weakness is the reason for hardened derivation, which a later concept presents.")), None),
 ("HdKeyGeneration", "Hierarchical deterministic key generation", 3, "KeyGenerationMethods", ("a tree of keys under one seed", "Hierarchical deterministic (HD) key generation, the standard BIP32, derives a tree of keys from one seed; any key can be the parent of further keys, and public keys can be derived without private keys.", ("2**31 + 2**31", "4294967296")), P(
  (W, "Hierarchical deterministic key generation, usually shortened to HD, is the standard way to derive keys from a seed. It is defined in BIP32, a Bitcoin Improvement Proposal by Pieter Wuille that has the status Deployed [B32]. The book describes it as deterministic key generation combined with optional public child key derivation, using an algorithm that produces a tree of keys: any key can be the parent of a sequence of child keys, and any child can in turn be the parent of grandchildren, with no arbitrary limit on the depth [AH]."),
  (Y, "The standard exists because a single sequence of keys shares everything or nothing. The proposal explains that deterministic wallets typically consist of one chain of key pairs, so that sharing happens on an all-or-nothing basis, while an owner often wants to share only some public keys. Its example is a web shop whose server needs the addresses that receive customer payments, but not the change addresses that are generated when the merchant spends [B32]. A tree lets one branch be shared and another kept private."),
  (E, "The book states that every modern Bitcoin wallet of which its authors are aware uses hierarchical deterministic key generation by default [AH]. Bitcoin Core's documentation lists BIP32 as implemented since version 0.13.0 [BC], and the wallet that the release 31.1 created for this chapter reported key paths such as m/84h/0h/0h/0/0 for its first address, a position in such a tree [B31]. The tree can be given a meaning: the book mentions a branch for incoming payments and another for change, and in corporate settings branches for departments, subsidiaries, functions or accounting categories [AH]."),
  (H, "Every key in the tree has an index, and an extended key can have 2 to the power 31 normal children and 2 to the power 31 hardened children, which together are the 2 to the power 32, about four billion, children that the book mentions [B32][AH]. The details of how a child is computed, what an extended key is and how a path is written are developed in the second half of the chapter. At this point it is enough to know that the tree is built from a single starting value, so that a seed again suffices to rebuild all of it."),
  (K, "A tree has a freedom that a list does not: two wallets can place the same keys at different positions, and a recovery then needs to know which positions were used. This is the derivation path problem that the second branch of the chapter treats at length. A second caution concerns the word standard. The header of BIP32 gives its type as Informational, and many details of real wallets, such as which paths to use, come from further proposals that this chapter introduces one by one [B32].")), None),
]

CHECKS_A = [
 Qb("ch05_wallets.adoc", "what many people call a Bitcoin wallet—which we call a <em>wallet database</em> to distinguish it from wallet applications—contains only keys", "Those keys are associated with bitcoins recorded on the blockchain", "By proving to Bitcoin full nodes that you control the keys, you can spend the associated bitcoins"),
 Qb("ch05_wallets.adoc", "But losing access to a private key can make it impossible for anyone to ever spend the bitcoins received to the corresponding public key", "Wallets for physical cash hold that cash", "many people mistakenly believe that Bitcoin wallets contain bitcoins"),
 Qb("ch05_wallets.adoc", "Some solutions have almost no downsides and are universally adopted by modern wallets", "leading different wallet authors to make different trade-offs"),
 Qb("ch05_wallets.adoc", "Simple wallet databases contain both the public keys to which bitcoins are received and the private keys that allow creating the signatures", "Other wallets' databases may contain only public keys, or only some of the private keys necessary to authorize a spending transaction", "hardware signing devices or other wallets in a multisignature scheme"),
 Qb("ch05_wallets.adoc", "(sometimes confusingly called a _hardware wallet_)", "returning the signed transactions to the less-secure frontend for broadcast to the Bitcoin network", "most hardware signing devices will never export private keys"),
 Qb("ch07_authorization-authentication.adoc", "set a condition where _k_ public keys are recorded in the script and at least _t_ of those must provide signatures to spend the funds"),
 Qe("bip-0032.mediawiki", "wallets which can be shared partially or entirely with different systems, each with or without the ability to spend coins", "(the \"neutered\" version, as it removes the ability to sign transactions)", "Leaking a private key means access to coins - leaking a public key can mean loss of privacy", "Audits: N(m/*)", "Per-office balances"),
 Qe("bip-0032.mediawiki", "deterministic wallets typically consist of a single \"chain\" of keypairs", "all-or-nothing basis", "by default) 100 keys are cached in a pool of reserve keys", "Status: Deployed", "Type: Informational", "Authors: Pieter Wuille"),
 Qe("core_fresh_wallet_31_1_v1_0_0.json", '"format": "sqlite"', '"descriptors": true', '"hdkeypath": "m/84h/0h/0h/0/0"'),
 Qe("core_help_backupwallet_31_1_v1_0_0.txt", "Safely copies the current wallet file to the specified destination"),
 Qe("core_doc_bips.md", "Hierarchical Deterministic Wallets has been implemented since **v0.13.0**"),
 Qb("ch05_wallets.adoc", "For each independently generated key, the user would need to back up about 32 bytes, plus overhead", "All early Bitcoin wallet applications did this", "Failure to back up the wallet database on time would lead to the user losing access to any funds received to keys that had not been backed up", "created new key pairs for each transaction, producing wallet databases that could only reasonably be backed up using digital media", "severely reduces the privacy of that user and all of the people with whom they transact"),
 Qb("ch05_wallets.adoc", "Modern wallet applications don't independently generate keys but instead derive them from a single random seed"),
 ("32 * 1000", "32000"), ("2**256 // 2**248", "256"), ("256 // 8", "32"),
 Qb("ch05_wallets.adoc", "later using the same hash function with the same input (called a _seed_) will produce the same seemingly random values", "Although seeds are large random numbers, usually 128 to 256 bits", "all she needs to back up in order to later recover access to those bitcoins is"),
 Qe("bip-0032.mediawiki", "Generate a seed byte sequence S of a chosen length (between 128 and 512 bits; 256 bits is advised) from a (P)RNG"),
 ("len('f1cc3bc03ef51cb43ee7844460fa5049e779e7425a6349c8e89dfbb0fd97bb73')", "64"),
 ("len(bytes.fromhex('f1cc3bc03ef51cb43ee7844460fa5049e779e7425a6349c8e89dfbb0fd97bb73'))", "32"),
 Qb("ch05_wallets.adoc", "A hash function will always produce the same output when given the same input, but if the input is changed even slightly, the output will be different", "nobody should be able to predict the new output--not even if they know the new input", "A user of deterministic key generation can back up every key in their wallet by simply recording their seed and a reference to the deterministic algorithm they used", "This allows us to take one random value and transform it into a practically unlimited number of seemingly random values"),
 Qb("ch05_wallets.adoc", "50b18e0bd9508310b8f699bad425efdf67d668cb2462b909fdb6b9bd2437beb3", "a965dbcd901a9e3d66af11759e64a58d0ed5c6863e901dfda43adcd5f8c744f3", "19580c97eb9048599f069472744e51ab2213f687d4720b0efc5bb344d624c3aa", "f1cc3bc03ef51cb43ee7844460fa5049e779e7425a6349c8e89dfbb0fd97bb73", 'for i in {0..2} ; do echo "$seed + $i" | sha256sum ; done'),
 ("[__import__('hashlib').sha256(('f1cc3bc03ef51cb43ee7844460fa5049e779e7425a6349c8e89dfbb0fd97bb73 + %d' % i + chr(10)).encode()).hexdigest()[:8] for i in range(3)]", "['50b18e0b', 'a965dbcd', '19580c97']"),
 ("__import__('hashlib').sha256(b'f1cc3bc03ef51cb43ee7844460fa5049e779e7425a6349c8e89dfbb0fd97bb73 + 0').hexdigest() == '50b18e0bd9508310b8f699bad425efdf67d668cb2462b909fdb6b9bd2437beb3'", "False"),
 ("len(__import__('hashlib').sha256(b'x').digest()) * 8", "256"),
 X("W.ec_add(W.ec_mul(%s), W.ec_mul(123)) == W.ec_mul(%s + 123)" % ("0x1E99423A4ED27608A15A2616A2B0E9E52CED330AC530EDCC32C8FFC6A526AEDD", "0x1E99423A4ED27608A15A2616A2B0E9E52CED330AC530EDCC32C8FFC6A526AEDD"), "True"),
 X("W.ec_add(W.ec_mul(5), W.ec_mul(123)) == W.ec_mul(128)", "True"),
 X("(lambda k, t: W.ec_add(W.ec_mul(k), W.ec_mul(t)) == W.ec_mul(k + t))(0x1E99423A4ED27608A15A2616A2B0E9E52CED330AC530EDCC32C8FFC6A526AEDD, 98765)", "True"),
 X("W.leak_parent_private_key(W.ec_mul(777), bytes(32), 3, W.ckd_priv(777, bytes(32), 3)[0]) == 777", "True"),
 Qb("ch05_wallets.adoc", "it's possible to add or subtract from a public key, or to multiply it", "If he then tells Alice the value he added to the public key, she can add the same value to the private key", "The value added to a public key is known as a _key tweak._", "an essentially unlimited sequence of public child keys from a single public parent key", "provide the key tweaks she used to a _hardware signing device_", "Alice's frontend distributes her public keys to people wanting to pay her"),
 Qe("bip-0032.mediawiki", "knowledge of a parent extended public key plus any non-hardened private key descending from it is equivalent to knowing the parent extended private key"),
 Qb("ch05_wallets.adoc", "uses hierarchical deterministic (HD) key generation by default", "This standard, defined in BIP32", "There's no arbitrary limit on the depth of the tree", "a specific branch of subkeys is used to receive incoming payments and a different branch is used to receive change", "allocating different branches to departments, subsidiaries, specific functions, or accounting categories"),
 Qe("bip-0032.mediawiki", "Each extended key has 2<sup>31</sup> normal child keys, and 2<sup>31</sup> hardened child keys"),
 Qb("ch05_wallets.adoc", "there are approximately four billion first-level keys"),
 ("2**31 + 2**31 == 2**32", "True"), ("2**32", "4294967296"),
 Qb("ch05_wallets.adoc", "humans are very poor sources of randomness", "brainwallet consists of words chosen by the user, whereas recovery codes are created randomly by the wallet"),
 Qb("ch05_wallets.adoc", "Nondeterministic key generation: a collection of independently generated keys stored in a wallet database", "Deterministic key generation: a deterministic sequence of keys derived from a seed for a wallet database"),
 Pp("Chapter_5_Wallets_v1_0_0.pptx", "Nondeterministic", "JBOK wallet", "Disadvantages"),
 Qe("bip-0032.mediawiki", "someone illegally obtaining access to the webserver can at most see all incoming payments but will not be able to steal the money"),
]
