"""SEN0401 chapter 5, corpus text part H (version 1.0.0): the branch 'Foundations the chapter relies on' - the cryptographic primitives the
explanations use (hash function, the SHA family, digital signature, secret sharing) and recovery as a practice (data loss, testing a backup).
These concepts were added because an audit of the terms used in the chapter's explanations found them used without a concept of their own.
Markers such as [AH] become author-year strings (sen0401_ch05_common)."""
from sen0401_ch05_common_v1_0_0 import *

SHAMIR = ("prime = 2 ** 127 - 1\n"
          "secret, coeffs = 123456789, [11, 22]\n"
          "shares = [(x, (secret + coeffs[0] * x + coeffs[1] * x * x) % prime) for x in (1, 2, 3, 4, 5)]\n"
          "def combine(points):\n"
          "    total = 0\n"
          "    for j, (xj, yj) in enumerate(points):\n"
          "        num = den = 1\n"
          "        for m, (xm, _) in enumerate(points):\n"
          "            if m != j: num = num * (-xm) % prime; den = den * (xj - xm) % prime\n"
          "        total = (total + yj * num * pow(den, -1, prime)) % prime\n"
          "    return total\n"
          "result = (combine(shares[:3]), combine(shares[2:5]), combine(shares[:2]) == secret)")

NODES_H = [
 ("Foundations", "Foundations the chapter relies on", 1, None, None, P(
  (W, "This last branch collects the ideas that the rest of the chapter uses as though they were already known. Some of them the earlier chapters of the book have introduced: the private key, the public key, the elliptic curve, the address and its encodings belong to chapter 4, and the transaction, the output and the blockchain to chapters 1 and 2. The ones gathered here are the remainder, the terms that this chapter's own explanations lean on most heavily and that no earlier chapter of this course defines in its own right."),
  (Y, "The branch exists for a reason of method rather than of subject. A teaching text should not use a word it has not explained, and an audit of the explanations written for this chapter found several terms used as though they were self-evident: the hash function on which every derivation in the chapter rests, the particular algorithms SHA-256 and SHA-512 that the standards name, the digital signature that the keys exist to produce, and the secret sharing that two of the recovery schemes are built on. Each is now a concept of this chapter with its own section."),
  (E, "The reader has met all four already. The hash function appeared in the chapter's first demonstration of deterministic key generation and in every derivation since; SHA-256 computes the BIP39 checksum and SHA-512 the keyed hash of BIP32 and of PBKDF2; the signature is what a hardware device returns and what the private keys of the whole chapter exist for; and secret sharing is the mathematics behind SLIP39 and codex32 [AH] [B39] [B32] [S39] [B93]."),
  (H, "The branch has two groups. The cryptographic primitives group gives the four ideas just named, each with a worked example small enough to check by hand or in the page. The recovery practice group closes the chapter with the two statements the chapter itself ends on: that data loss, not theft, is perhaps the leading cause of lost bitcoins, and that a backup is worth only as much as the test that shows it works [AH]."),
  (K, "A warning about the level of treatment. These sections are summaries sufficient for this chapter and no more: the design of hash functions, the security proofs of signature schemes and the algebra of secret sharing are each a subject of their own, and the course's later chapters and the book's chapters 7 and 8 go further. What a reader should take from this branch is enough precision to read the standards of this chapter without hand-waving.")), None),

 ("CryptographicPrimitives", "Cryptographic primitives", 2, "Foundations", None, P(
  (W, "A cryptographic primitive is a basic operation out of which protocols are built: this group covers the four that chapter 5 uses. The hash function is the one-way, repeatable function behind every derivation in the chapter. The SHA family provides the two particular hash functions the standards name. The digital signature is the operation that a private key exists to perform. And secret sharing is the construction that lets one secret be split so that a subset of the parts recovers it."),
  (Y, "The group matters because the properties of these primitives are the reasons the chapter's claims are true. That a child key cannot be used to find its parent is a property of the hash function; that a recovery code's checksum detects an error but cannot correct it is a property of SHA-256 used as a compressor; that a server can hold an extended public key safely is a property of the signature scheme's key pair; and that three of five codes can recover a seed while two cannot is a property of polynomial interpolation."),
  (H, "The four sections give, for each primitive, what it is, why the chapter needs it, where it appears in the chapter and a worked example. The examples are all computable with Python's standard library, and the one for secret sharing is a toy over a prime field rather than the field of 256 elements that SLIP39 uses, so that the arithmetic can be read [S39].")), None),

 ("HashFunction", "Hash function", 3, "CryptographicPrimitives", ("the hash of three letters",
   "A hash function maps data of any size to a fixed-size value, always the same for the same input and unpredictable for a changed one, and cannot be run backwards.",
   ("__import__('hashlib').sha256(b'abc').hexdigest()[:8]", "'ba7816bf'")), P(
  (W, "A hash function maps an input of any length to an output of fixed length. The chapter gives the two properties it needs in one sentence: a hash function will always produce the same output when given the same input, but if the input is changed even slightly the output will be different, and if the function is cryptographically secure nobody should be able to predict the new output, not even if they know the new input [AH]. The worked example computes the beginning of the SHA-256 hash of the three letters abc, which is the standard's own best-known test value."),
  (Y, "Every mechanism in this chapter rests on those properties. Repeatability is what makes a seed a backup, since the same seed gives the same keys; unpredictability is what makes the derived keys unguessable; and the one-way direction is what makes a child key useless for finding its parent, which the chapter states when it says that because the derivation function is a one-way function the child key cannot be used to find the parent key [AH]. The chapter's opening demonstration makes the same point positively: a hash function lets one take one random value and transform it into a practically unlimited number of seemingly random values [AH]."),
  (E, "A reader has met hash functions at every stage. The chapter's first example hashes a random value with a counter to produce a sequence of private keys [AH]. BIP39 takes the first bits of a SHA-256 hash as a checksum and runs 2,048 rounds of a keyed hash to produce a seed [B39]. BIP32 derives every key with a keyed hash and identifies extended keys by a hash of the public key [B32]. Chapter 4 of the book used hashes to commit to a public key in an address, and chapter 2 used them to identify transactions."),
  (H, "What a hash function does not do is as important as what it does, and two limits matter here. It is not encryption: nothing can be recovered from the output, which is why BIP39 notes that the conversion from a sentence to a seed is one-way only and an arbitrary BIP32 seed cannot be written as a BIP39 sentence [B39]. And it is not a random oracle in practice: its output is fully determined by its input, so a hash of a guessable value is guessable, which is the brainwallet lesson of the first branch."),
  (K, "Two cautions for a learner. A hash is not a signature and proves nothing about who produced the data; proving that requires the keyed hash or the signature of the next sections. And collisions exist in principle, since a long input is mapped to a short output; the security claim is only that finding one is infeasible, which is why chapter 4 of the book discusses collision and preimage attacks on the shorter hashes used in addresses.")), None),

 ("ShaAlgorithm", "SHA-256 and SHA-512", 3, "CryptographicPrimitives", ("32 bytes and 64 bytes",
   "SHA-256 and SHA-512 are the two secure hash algorithms this chapter's standards name, producing 32 and 64 bytes; the choice of one or the other fixes the sizes in every scheme.",
   ("(len(__import__('hashlib').sha256(b'').digest()), len(__import__('hashlib').sha512(b'').digest()))", "(32, 64)")), P(
  (W, "SHA-256 and SHA-512 are two members of the second family of secure hash algorithms, producing outputs of 256 and 512 bits. The worked example measures both: 32 bytes and 64 bytes. The chapter names them where its standards do: the BIP39 checksum is taken from a SHA-256 hash, and the key-stretching function uses HMAC-SHA512, which produces a 512-bit value [AH]. Python's standard library provides both, and the documentation of its hashing module describes the constructors and the derivation function this chapter uses [PY]."),
  (Y, "The choice of algorithm fixes the sizes everything else is built around, and a reader who notices this will stop finding the numbers arbitrary. A BIP39 seed is 512 bits because HMAC-SHA512 produces 64 bytes in one block; a BIP32 derivation yields a 256-bit key and a 256-bit chain code because the same 64 bytes are split in half; an extended key's 78 bytes include those 32 bytes of chain code and 33 of key data [B39] [B32]. Change the hash and every one of those numbers changes."),
  (E, "A reader meets SHA-256 in the BIP39 checksum, in the double hash of base58check that protects an extended key, and in the tagged hash of BIP86's taproot tweak; SHA-512 in BIP32's master key generation and child derivation and in PBKDF2's pseudorandom function [B39] [B32] [B86]. codex32's criticism of BIP39 names the choice explicitly, listing the use of SHA-512 to derive seeds among the design decisions it considers unhelpful [B93]."),
  (H, "For this chapter the mechanism can be taken as given: both functions process their input in blocks and produce a fixed digest, and both are available as single calls. What matters is which is used where, and the sizes that follow. The claims of this chapter check those sizes directly, and also check that the two functions are not interchangeable: the same input gives unrelated outputs, which is why a standard must name the function and not merely say a hash."),
  (K, "Two points of care. The names are easy to confuse with SHA-1 and with the third family, SHA-3, which are different algorithms; the course's browser pages provide SHA-2 and SHA-3 but not the RIPEMD-160, a different hash function, that Bitcoin addresses also use, which is why some values in this chapter are given as data [PY]. And a longer digest is not automatically more secure for a given purpose: BIP39 uses 512 bits for a seed whose entropy is at most 256, which the chapter's sidebar on security strength explains [AH].")), None),

 ("DigitalSignature", "Digital signature", 3, "CryptographicPrimitives", ("what a signing device returns",
   "A digital signature is a value computed from a message and a private key that anyone can check against the matching public key, which is how spending a Bitcoin output is authorised.",
   None), P(
  (W, "A digital signature is the proof that the holder of a private key authorised a particular message. In Bitcoin the message is a transaction and the key is the one that controls the output being spent; the chapter assumes this throughout, beginning with its first sentence about wallet databases, which says that simple databases contain both the public keys to which bitcoins are received and the private keys that allow creating the signatures necessary to authorize spending those bitcoins [AH]. Chapter 4 of the book introduced the key pair, and the book's chapters 7 and 8 treat the signature itself."),
  (Y, "The signature is why the whole chapter is about keys. Losing a key does not lose data, it loses the ability to produce a signature, and the chapter's opening states the consequence: losing access to a private key can make it impossible for anyone ever to spend the bitcoins received to the corresponding public key [AH]. Conversely, the ability to sign is the whole of ownership, which is why a copied key is a stolen coin and why the separation of signing from the rest of a wallet is the chapter's central practical idea."),
  (E, "A reader meets signatures in this chapter mostly by their absence. A wallet with public keys only cannot make them; external signing is the arrangement in which someone else does; a hardware signing device is named for the operation it performs, and the chapter describes it returning the signed transactions to the less secure frontend for broadcast [AH]. A multisignature arrangement needs several of them, and BIP32 calls the extended public key the neutered version of an extended private key because neutering removes the ability to sign transactions [B32] [AH7]."),
  (H, "For this chapter the mechanism needs only its shape: a signature is computed from the message and the private key, it can be verified with the public key, and it cannot be produced without the private key. The claims of this chapter include a small signing and verification with the curve of chapter 4, which show the shape: a signature over one message does not verify over another. The details of the scheme, including the nonce whose reuse is catastrophic, belong to the book's chapter on signatures."),
  (K, "Two confusions to avoid. A signature is not encryption and nothing in a Bitcoin transaction is hidden; the blockchain is public, as chapter 2 made clear. And a signature authorises one message only, which is why a signing device must show what it is signing: possession of the key is necessary and consent to the particular transaction is what the user is actually giving.")), None),

 ("SecretSharing", "Secret sharing", 3, "CryptographicPrimitives", ("three of five points recover the secret",
   "Secret sharing splits a secret into parts so that any sufficient number of them recovers it and any smaller number reveals nothing; it is the mathematics behind SLIP39 and codex32.",
   (PROG(SHAMIR), "(123456789, 123456789, False)")), P(
  (W, "Secret sharing is a way of splitting one secret into several parts with a threshold. SLIP39's description is the clearest: the scheme splits a secret into a number of unique parts, of which any threshold-many are required to reconstruct it, and knowledge of fewer than the required number does not leak information about the secret [S39]. The chapter meets the idea through the schemes that use it, saying of SLIP39 that a single seed can be distributed using multiple recovery codes stored in different places or by different people, with the number required specified when they are created [AH]."),
  (Y, "The construction answers a problem no single backup can solve, which the first branch described: one copy can be lost, and many copies can be stolen. SLIP39 states the trade-off and the resolution: the usual approach is redundant backups, but when the asset is valuable there is a substantial risk of a backup holder absconding with it, and secret sharing distributes custodianship in a manner that can prevent loss even if one or a few parties are compromised [S39]. codex32's motivation puts the same tension as security against resilience [B93]."),
  (E, "The worked example is the mathematics in miniature. A secret and two coefficients define a polynomial whose arithmetic is carried out modulo a large prime, so that every value stays in a fixed range; five points on it are the shares; any three of them recover the secret, as the example shows for the first three and for the last three; and two of them do not, which the example's third value reports as false. SLIP39's own description is the same construction with the shared secret stored at the value 255 and a digest at 254, over the field of 256 elements, applied to each byte separately [S39]."),
  (H, "Why a threshold reveals nothing below it is worth one sentence: a polynomial of degree less than the threshold is not determined by fewer points than its coefficients, so every candidate secret remains possible, which is the sense in which fewer shares leak no information [S39]. The two standards that use the construction differ in their packaging rather than in this core: SLIP39 encrypts the master secret with the passphrase first and supports two levels of groups, while codex32 works in the bech32 alphabet so that the arithmetic can be done by hand and supports up to 31 shares with a threshold between 2 and 9 [S39] [B93]."),
  (K, "Three cautions. The toy in the worked example is not a secure implementation: it uses fixed coefficients where a real scheme draws them from a secure random source, and it works on one integer rather than on a byte string. A threshold is a policy decision with two failure modes, as the first branch said: too low invites theft, too high invites loss. And the shares are secrets: distributing them is a plan for who is trusted with what, which is why SLIP39 provides two levels of grouping to express uneven trust [S39].")), None),

 ("RecoveryPractice", "Recovery as a practice", 2, "Foundations", None, P(
  (W, "This last group turns the chapter's technical content into two statements about practice. The chapter's closing paragraph makes both: many people focus on securing their bitcoins against theft and other attacks, but one of the leading causes of lost bitcoins, perhaps the leading cause, is data loss, and if the keys and other essential data required to spend are lost, those bitcoins will forever be unspendable, with nobody able to get them back; and it is up to the reader to actually use the systems available to make good backups and regularly test them [AH]."),
  (Y, "The group matters because the chapter's whole argument is practical. Every mechanism it describes, from the word list to the descriptor, exists to make a recovery possible, and none of them acts on its own. A course that taught the mechanisms without the two statements above would leave a student able to explain a recovery code and unable to keep one."),
  (H, "The two sections state the problem and the remedy. Data loss describes the risk the chapter names as leading, with the particular forms it takes in the chapter's own text. Testing a backup describes the one action the chapter asks of the reader, and what a complete test covers, which the branches of this chapter have between them specified: the code, the paths and the data that is not keys.")), None),

 ("DataLoss", "Data loss", 3, "RecoveryPractice", ("the loss the chapter calls the leading cause",
   "Data loss is the loss of the keys or of the information needed to use them, which the chapter names as perhaps the leading cause of lost bitcoins, and which no one can reverse.",
   None), P(
  (W, "Data loss, in this chapter, means losing the information needed to spend rather than having it stolen. The chapter's closing paragraph puts it first among causes: many people focus on securing their bitcoins against theft and other attacks, but one of the leading causes of lost bitcoins, perhaps the leading cause, is data loss, and if the keys and other essential data required to spend are lost, those bitcoins will forever be unspendable, and nobody can get them back [AH]. The chapter's first sentence said the same of a single key [AH]."),
  (Y, "The emphasis is a correction of intuition. Theft is vivid and loss is dull, and so users protect against the first and neglect the second, while the chapter's examples of loss are mundane: a corrupted database, a wallet application whose labels were never exported, a passphrase that only the deceased owner knew, a payment beyond the gap limit, a path a newer wallet no longer tries [AH]. Each of those is a loss of data rather than an attack, and each has appeared in this chapter with its own section."),
  (E, "A reader meets the forms of loss throughout the chapter. Independent key generation loses funds received to keys that had not yet been backed up [AH]. A forgotten passphrase makes a seed useless and the funds lost forever [AH]. A seed-only restoration loses every label [AH]. A wallet restored into software that does not know its path finds nothing [AH]. A Lightning channel whose state is lost may be unrecoverable even with a static channel backup [AH] [LR]."),
  (H, "The mechanism common to all of them is the one the chapter keeps returning to: Bitcoin has no authority that can reissue a key or reverse a payment, which chapter 1 of the book described as irreversibility and decentralisation. The remedy is therefore always the same in form, to hold enough information in enough places, and the chapter's branches are the list of what that information is: the recovery code, the passphrase if any, the derivation paths or descriptors, and the data that is not keys."),
  (K, "Two things should not be inferred. That data loss is the leading cause does not make theft unimportant, and the chapter's own treatment of coercion shows that the two interact: a backup held in many places is easier to find. And a loss is not always immediately visible, which is the chapter's warning about a mistyped passphrase that shows a zero balance the user may not question for years [AH]. The practical conclusion is the next section's.")), None),

 ("BackupTesting", "Testing a backup", 3, "RecoveryPractice", ("the one action the chapter asks for",
   "Testing a backup means carrying out a recovery before it is needed, which is the only way to learn that a code, a path and the non-key data are all sufficient.",
   None), P(
  (W, "Testing a backup means performing the recovery while it is still optional. It is the action the chapter's last sentence asks for: it is up to the reader to actually use the systems available to make good backups and regularly test them [AH]. The test is the only evidence that the backup is complete, because every other check verifies a part: a checksum says the code was typed correctly, not that the code is the right one; a descriptor's checksum says the descriptor is intact, not that it describes the wallet."),
  (Y, "The reason a test is needed is that this chapter has produced a list of things that can each be individually right and jointly insufficient. A valid code with the wrong passphrase gives an empty wallet; a valid code in software that does not know the path gives an empty wallet; a complete key recovery with no labels gives an unreadable history; a recovered single-signature wallet says nothing about a multisignature arrangement's other participants [AH]. Only an attempted recovery exercises all of them at once."),
  (E, "A reader meets the need for a test in several of the chapter's own warnings. The chapter notes that a user who enters a slightly wrong passphrase may use the wallet for years before discovering the mistake, and that novice users seeing a zero balance may think their money is permanently lost and do something foolish, such as giving up and throwing away the code [AH]. Both are failures that a test would have caught. Bitcoin Core's own warning about its key pool points the same way, saying that smaller sizes may increase the risk of losing funds when restoring from an old backup [BCW]."),
  (H, "What a complete test covers follows from the branches of this chapter, and it can be stated as a short list: restore the recovery code, with the passphrase if one is used, into software other than the one that created it; check that the balance and the transaction history are as expected, which tests the paths or the descriptors; check that labels and any protocol data are present, which tests the non-key backup; and for a multisignature or descriptor wallet, check that the other participants' public keys or the descriptor itself were recorded. Each item is one of the chapter's sections."),
  (K, "A test is itself a risk and should be done carefully: entering a recovery code into software or a device exposes it, so a test belongs on a machine the user would trust with the wallet itself, and a code should never be typed into a web page. Two further cautions: a test proves the backup worked on that day, which is why the chapter says regularly; and a test of the recovery code is not a test of the kit, the descriptor or the label export unless those are included [AH].")), None),
]

CHECKS_H = [
 Qb("ch05_wallets.adoc", "A hash function will always produce the same output when given the same\ninput, but if the input is changed even slightly, the output will be\ndifferent",
    "If the function is cryptographically secure, nobody should\nbe able to predict the new output--not even if they know the new input",
    "the private keys that allow creating the signatures\nnecessary to authorize spending those bitcoins",
    "losing access to a\nprivate key can make it impossible for anyone to ever spend the bitcoins\nreceived to the corresponding public key"),
 Qb("ch05_wallets.adoc", "Many people", "focus on securing their bitcoins against theft and other\nattacks, but one of the leading causes of lost bitcoins--perhaps _the_\nleading cause--is data loss",
    "If the keys and other essential data\nrequired to spend your bitcoins is lost, those bitcoins will forever be\nunspendable.  Nobody can get them back for you",
    "it's up to you to\nactually use the systems available to make good backups and",
    "However, novice users may think their money was permanently lost and do\n  something foolish, such as give up and throw away their recovery code"),
 # hash functions and the SHA family
 ("__import__('hashlib').sha256(b'abc').hexdigest()[:8]", "'ba7816bf'"),
 ("__import__('hashlib').sha256(b'abc').hexdigest()", "'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'"),
 ("(len(__import__('hashlib').sha256(b'').digest()), len(__import__('hashlib').sha512(b'').digest()))", "(32, 64)"),
 ("__import__('hashlib').sha256(b'abc').digest() == __import__('hashlib').sha512(b'abc').digest()[:32]", "False"),
 ("__import__('hashlib').sha256(b'abc').hexdigest() != __import__('hashlib').sha256(b'abd').hexdigest()", "True"),
 ("sum(1 for a, b in zip(__import__('hashlib').sha256(b'abc').digest(), __import__('hashlib').sha256(b'abd').digest()) if a == b) < 8", "True"),
 Qe("python_hashlib.rst", "hashlib", "sha256", "sha512"),
 Qe("bip-0093.mediawiki", "the use of SHA-512 to derive seeds, or the use of 11-bit words"),
 # signatures, on the curve of chapter 4
 X("(lambda d, z: W.ecdsa_verify(W.ec_mul(d), z, W.ecdsa_sign(d, z, 987654321)))(0x1E99423A4ED27608A15A2616A2B0E9E52CED330AC530EDCC32C8FFC6A526AEDD, 12345)", "True"),
 X("(lambda d, z: W.ecdsa_verify(W.ec_mul(d), z + 1, W.ecdsa_sign(d, z, 987654321)))(0x1E99423A4ED27608A15A2616A2B0E9E52CED330AC530EDCC32C8FFC6A526AEDD, 12345)", "False"),
 X("(lambda d, z: W.ecdsa_verify(W.ec_mul(d + 1), z, W.ecdsa_sign(d, z, 987654321)))(0x1E99423A4ED27608A15A2616A2B0E9E52CED330AC530EDCC32C8FFC6A526AEDD, 12345)", "False"),
 Qe("bip-0032.mediawiki", "the \"neutered\" version, as it removes the ability to sign transactions"),
 # secret sharing
 (PROG(SHAMIR), "(123456789, 123456789, False)"),
 X("W.shamir_combine(W.shamir_split(2 ** 100 + 7, 3, 5, [11, 22])[::2]) == 2 ** 100 + 7", "True"),
 X("W.shamir_combine(W.shamir_split(2 ** 100 + 7, 2, 3, [99])[:2]) == 2 ** 100 + 7", "True"),
 Qe("slip-0039.md", "SSS splits a master secret into unique parts which can be distributed among participants",
    "A specified minimum number of parts is required to be supplied in order to reconstruct the original secret",
    "Knowledge of fewer than the required number of parts does not leak information about the master secret",
    "When any *T* points are provided, they exactly define the polynomial"),
 Qe("bip-0093.mediawiki", "we use Shamir's secret sharing, which guarantees that any number of shares less than the threshold leaks no information about the secret",
    "A minimum threshold of shares, which can be between 2 and 9, is needed to recover the secret"),
 Qe("core_help_keypool_31_1_v1_0_0.txt", "Smaller sizes may increase the risk of losing funds when restoring from an old backup"),
 Pp("Chapter_5_Wallets_v1_0_0.pptx", "Wallet Best Practices", "Discussions"),
]
