"""SEN0401 chapter 5, corpus text part G (version 1.0.0): the branches 'Backing up data that is not keys' (labels, the export format, other
protocol data, encrypted backups) and 'Deploying keys in practice' (an extended public key on a web store, the gap limit, payment processors,
cold storage, signing devices, a written backup). Markers such as [AH] become author-year strings."""
from sen0401_ch05_common_v1_0_0 import *

LABEL_IO = ("import json\n"
            "r = {'type': 'addr', 'ref': 'bc1qcr8te4kr609gcawutmrza0j4xv80jy8z306fyu', 'label': 'Paid Bob for podcast'}\n"
            "result = json.dumps(r, sort_keys=True)")
XOR_IO = ("import hashlib\n"
          "key = hashlib.sha256(bytes.fromhex('5b56c417303faa3f') + b'backup').digest()\n"
          "note = b'Paid Bob for podcast'\n"
          "hidden = bytes(a ^ b for a, b in zip(note, key))\n"
          "result = (hidden.hex()[:16], bytes(a ^ b for a, b in zip(hidden, key)).decode())")
GAP_IO = ("used = {0, 3, 25}\n"
          "gap = 20\n"
          "found = []; run = 0; i = 0\n"
          "while run < gap:\n"
          "    if i in used: found.append(i); run = 0\n"
          "    else: run += 1\n"
          "    i += 1\n"
          "result = (found, i)")

NODES_G = [
 ("NonkeyBackup", "Backing up data that is not keys", 1, None, None, P(
  (W, "This branch is about everything in a wallet that a seed cannot reproduce. The chapter opens its section on backing up non-key data by granting the obvious: the most important data in a wallet database is its private keys, and deterministic derivation with recovery codes provides a reasonably robust solution for backing up and recovering the keys and the bitcoins they control; but it is important to consider that many wallet databases store more than just keys, since they also store user-provided information about every transaction they sent or received [AH]."),
  (Y, "The branch matters because a restored wallet with the right balance can still be useless. The chapter asks the reader to imagine reviewing a bank or credit card statement from a year ago that had the date and amount of every transaction listed but a blank entry for the description field, and says that because address and transaction labels are stored only in each user's wallet database and are not deterministic, they cannot be restored by using just a recovery code: all the user will see is a list of approximate transaction times and bitcoin amounts [AH]. For a user with tax obligations or an accountant, that is a real loss."),
  (E, "A reader meets the problem in two forms. The first is labels, which the chapter illustrates with Bob adding a label to an address when he sends Alice an invoice and Alice labelling the transaction as paying Bob, and with a small table of Alice's own transaction history [AH]. The second is data belonging to protocols built on Bitcoin: the chapter notes that an increasing number of applications support sending and receiving over the Lightning Network, whose recovery mechanism cannot guarantee results [AH]."),
  (H, "The branch has two groups. The wallet notes group covers the labels themselves, on addresses and on transactions, and the standard proposed for exporting them, BIP329. The other protocol data group covers the data that other protocols add, with the Lightning Network and its static channel backups as the chapter's example, and the one solution the chapter describes for backing up everything at once: a complete, automatic backup of the wallet database encrypted by a key derived from the seed, which also requires a section on what encryption is."),
  (K, "The branch's conclusion is the chapter's own, and it is a warning about habits rather than about software: again, this means that users and wallet applications need to do more than just back up a recovery code [AH]. The chapter also notes that wallets should provide a convenient way to back up label data, which it says seems obvious, and yet a number of widely used applications make it easy to create and use recovery codes while providing no way to back up or restore label data [AH]. A learner should test a restoration before relying on one.")), None),

 ("WalletNotes", "Labels and notes", 2, "NonkeyBackup", None, P(
  (W, "This group covers the information a user adds to a wallet by hand. The chapter's examples are the two kinds that nearly every wallet keeps: a label attached to an address, so that the payment received there can be told apart from others, and a label attached to a transaction, so that the user can remember what it was for; it adds that some wallets store other useful information with a transaction, such as the exchange rate at the time, which can be useful for calculating taxes in some jurisdictions [AH]."),
  (Y, "The group matters because this information is private in a way the keys are not. The chapter notes that labels are stored entirely within their own wallets and not shared with the network, which protects the users' privacy and keeps unnecessary personal data out of the blockchain [AH]. The same property that protects them, that they exist in one place only, is what makes them easy to lose, so privacy and fragility have the same cause."),
  (H, "The three sections take the address label, the transaction label and the standard for moving both between applications. Each is short, because the subject is simple; what matters is the conclusion, which is that this part of a backup needs a separate mechanism, and that one has been proposed and is in use.")), None),

 ("AddressLabel", "Address label", 3, "WalletNotes", ("a name on an address at the time it is created",
   "An address label is a note a user attaches to an address they hand out, so that payments arriving there can be recognised; it exists only in that user's wallet.",
   None), P(
  (W, "An address label is a name a user gives to one of their own addresses. The chapter's example is the natural one: when Bob creates a new address as part of sending an invoice to Alice, he adds a label to the address he generates so that he can distinguish her payment from other payments he receives [AH]. The label is a note about the wallet's own address, not about the payer, and nothing about it leaves the wallet."),
  (Y, "The label is what makes a fresh address per payment practical. The branch on deploying keys shows a web store giving every order its own address so that each order has a unique identifier; without a note recording which address belonged to which order, that identifier would be useless [AH]. Labelling is therefore not a nicety but the bookkeeping that privacy-preserving address use requires."),
  (E, "A reader meets address labels in every wallet interface that asks for a name when an address is created, and in BIP329's record types, where the type addr takes an address in base58 or bech32 format as its reference [B329]. Bitcoin Core keeps labels for addresses as well, which is why its own address information command reports a label field; the evidence of this chapter shows the fields a fresh wallet reports for its first address, among them the descriptor and the key path [B31]."),
  (H, "Mechanically a label is a row in the wallet database keyed by the address, and that is all. Because the address is derived from the seed and the label is not, a restoration reproduces the address and loses the label, which is the asymmetry this branch is about. BIP329 adds one refinement for the case of several wallets from one seed: a record may carry an origin property describing the originating wallet, to disambiguate labels from different wallets contained in the same export [B329]."),
  (K, "Labels look harmless and are not. Because they connect an address to a person or a purpose, a leaked label file can undo the privacy that fresh addresses provide, and BIP329 says so plainly: care should be taken when exporting due to the privacy-sensitive nature of the data, encryption in transit over untrusted networks is highly recommended, encryption at rest should be considered, and unencrypted exports should be deleted as soon as possible [B329].")), None),

 ("TransactionLabel", "Transaction label", 3, "WalletNotes", ("Alice's two labelled payments",
   "A transaction label is a note a user attaches to a payment they made or received, which a seed-based restoration cannot reproduce.",
   ("round(0.00100 - 0.00075, 5)", "0.00025")), P(
  (W, "A transaction label is a note on a payment. The chapter's example continues the one before it: when Alice pays Bob's address, she labels the transaction as paying Bob, for the same reason Bob labelled the address, and the chapter prints her transaction history with each transaction labelled, two rows, one for bitcoins bought from Joe and one for a payment to Bob for a podcast [AH]. The worked example adds the two amounts of that table, a receipt of 0.001 and a payment of 0.00075, and gets the 0.00025 bitcoin left."),
  (Y, "Transaction labels are the user's own record of what their money did, and nothing else records it. The blockchain holds the amounts and the times; it holds no field for a description, which the chapter notes in its web store section when it says that the only metadata chosen by the receiver of a typical transaction are the amount and the payment address, with no subject or message field to hold a unique invoice number [AH]. The label fills that gap privately."),
  (E, "A reader meets transaction labels in the history view of any wallet, in the chapter's table, and in BIP329, whose type tx takes a transaction identifier in hexadecimal format as its reference and whose motivation observes that labels have even become mandatory when spending in several Bitcoin wallets [B329]. The standard also allows labels on inputs and outputs, with a reference of a transaction identifier and an index, and notes that the model Bitcoin uses makes these labels particularly valuable because they may indicate the source of funds [B329]."),
  (H, "The mechanism is the same as for an address label, a row in the local database, and so is the consequence for recovery. The chapter spells out what a seed-only restoration shows: a list of approximate transaction times and bitcoin amounts, which can make it quite difficult to figure out how the money was used in the past [AH]. The amounts and times come from the blockchain, which is why they survive; the words do not."),
  (K, "Two cautions. The arithmetic of a wallet's balance is not the arithmetic of its labels: the worked example's subtraction uses rounded decimal figures as the chapter prints them, whereas a real wallet works in satoshis, the integer unit chapter 2 introduced, precisely to avoid the rounding that decimal fractions invite. And a label is an assertion by the user, not evidence: it is as reliable as the person who typed it, which is worth remembering when labels are used for tax records.")), None),

 ("LabelExportFormat", "Label export format (BIP329)", 3, "WalletNotes", ("one record as a line of JSON",
   "BIP329 proposes a line-based JSON format for exporting wallet labels, so that labels can be moved between applications instead of locking a user into one.",
   (PROG(LABEL_IO), "'{\"label\": \"Paid Bob for podcast\", \"ref\": \"bc1qcr8te4kr609gcawutmrza0j4xv80jy8z306fyu\", \"type\": \"addr\"}'")), P(
  (W, "BIP329 is the proposal for writing labels down in a portable way. The chapter mentions it in one sentence: it may be useful for wallet applications to provide a standardised format to export labels so that they can be used in other applications, such as accounting software, and a standard for that format is proposed in BIP329 [AH]. The standard itself says it specifies a format for the export of labels that may be attached to various common types of records in a wallet [B329]."),
  (Y, "The reason given is lock-in. The standard's motivation says that the export and import of funds across different wallets is well defined through standards such as BIP39, BIP32 and BIP44, which are well supported and allow users to move easily between wallets, but that there is no defined standard to transfer the labels a user may have applied; allowing users to import and export labels in a standardised way ensures that they do not experience lock-in to a particular wallet application [B329]. The argument is exactly the one BIP380 makes about scripts, applied to notes."),
  (E, "The worked example writes one record in the shape the standard defines: a JSON object with a type, a reference and a label, here an address record for the address of the BIP84 test vector with one of the chapter's own labels [B329] [B84] [AH]. The standard's full set of types is wider: a transaction, an address, a public key, an input, an output, an extended public key or a scan key of a newer payment scheme, each with a defined form of reference, plus optional origin and spendable properties [B329]."),
  (H, "The format is deliberately plain. The standard uses JSON lines, also called newline-delimited JSON, so that a document can be split, streamed or incrementally added to, and so that a formatting error cannot invalidate an entire import; an export must be a UTF-8 text file with one JSON object per line, separated by a newline, with no multiline values, and each object must carry the type and the reference while the label, origin and spendable properties are optional [B329]. It also includes the frozen state of an output, because that wallet-related metadata is similar to labels and is not captured elsewhere [B329]."),
  (K, "Three limits are worth stating. The standard is a Draft and informational, so support varies; it defines no private key types, for security reasons; and the data it carries is privacy-sensitive, which is why it recommends encryption in transit and at rest [B329]. The chapter's own complaint stands beside it: a format helps only if wallets implement it, and the chapter notes that a number of widely used wallets still provide no way to back up label data at all [AH].")), None),

 ("OtherProtocolData", "Other data a wallet keeps", 2, "NonkeyBackup", None, P(
  (W, "This group covers the data that protocols built on top of Bitcoin add to a wallet, and the one general solution the chapter offers for backing everything up. The chapter introduces the subject by saying that wallet applications implementing additional protocols beyond basic Bitcoin support may also need or want to store other data, and gives the Lightning Network as its example, noting that although the protocol provides a method to recover funds in the event of a data loss, called static channel backups, it cannot guarantee results [AH]."),
  (Y, "The group matters because the consequences here are worse than losing a label. The chapter states them: if the node a wallet connects to realises that data has been lost, it may be able to steal bitcoins; and if that node loses its own database at the same time and neither party has an adequate backup, both lose funds [AH]. Data loss in such a protocol is therefore not only a loss of records but a loss of money."),
  (H, "The four sections give the protocol, its backup mechanism, the idea of encryption, and the encrypted wallet backup the chapter describes as one solution a few wallets implement. The last of these is the only mechanism in the chapter that backs up everything, keys and notes and protocol data together, and it is worth understanding because it shows how a seed can protect data that is not derived from it.")), None),

 ("LightningNetwork", "Lightning Network", 3, "OtherProtocolData", ("a channel as a shared output",
   "The Lightning Network is a protocol of payment channels built on Bitcoin, in which funds live in outputs that two parties control jointly, so a wallet must keep state that no seed can reproduce.",
   None), P(
  (W, "The Lightning Network is a protocol layered on Bitcoin for making payments without putting each of them on the blockchain. The book's glossary describes it as an implementation of hashed timelock contracts, which the same glossary defines as payments that require the receiver either to acknowledge the payment before a deadline by producing cryptographic proof of it or to forfeit the right to claim it, with bidirectional payment channels, which allows payments to be securely routed across multiple peer-to-peer channels, so that any peer can pay any other even without a direct channel between them [AHG]. Chapter 14 of the book develops the idea from a one-directional channel for a metered service to bidirectional channels joined end to end into a routed network first proposed under that name [AH14]."),
  (Y, "For this chapter the protocol matters because of where the money sits. The lnd recovery document explains that a node's funds can be in one of two pools, on-chain funds, which are outputs under the node's control that can be spent immediately and without any auxiliary data, and off-chain funds, which exist within a two-of-two multisignature output usually called a payment channel [LR]. A seed recovers the first pool; the second needs the channel's state, which is not derivable from the seed."),
  (E, "A reader meets the protocol in this chapter three times: as the reason the chapter says wallets may need to store other data; as one of the newer technologies the Muun wallet's recovery arrangement supports; and in the lnd documentation, where recovery needs both the 24-word cipher seed and the encrypted static channel backup file [AH] [LR]. Chapter 1 of the book introduced it among the ways Bitcoin is used, and chapter 14 gives the mechanism."),
  (H, "The part of the mechanism this chapter needs is short. A channel is opened by a transaction that pays an output requiring both parties' signatures, which chapter 14 describes for a related construction as assigning funds to an output that requires signatures from both parties; the parties then sign successive versions of a settlement that divides the balance, and only the last of them is meant to be published [AH14]. Because only the latest version is valid in the parties' agreement, a wallet that restores an old version is in a dangerous position, which is the next section's subject."),
  (K, "The protocol is outside the scope of this chapter and a reader should take only the recovery consequence from it: a Lightning-capable wallet's backup problem is strictly harder than a Bitcoin wallet's, because part of its state changes with every payment and cannot be recomputed. The chapter's conclusion applies with full force here: users and wallets need to do more than back up a recovery code [AH].")), None),

 ("StaticChannelBackup", "Static channel backup", 3, "OtherProtocolData", ("one backup per channel, not per payment",
   "A static channel backup records what is needed to recover a channel's settled funds and is taken once, when the channel is created; it allows recovery of those funds but cannot guarantee the result.",
   None), P(
  (W, "A static channel backup is the recovery mechanism the Lightning Network provides for the off-chain pool. The chapter names it: although the protocol provides a method to recover funds in the event of a data loss, called static channel backups, it cannot guarantee results [AH]. The lnd documentation explains the word static: the backups need to be obtained only once, when the channel is created, and from then on a backup is good until the channel is closed [LR]."),
  (Y, "The mechanism exists because the obvious alternative is dangerous. The document explains why copying the channel database periodically is worse: those methods can be dangerous because one never knows whether one has the latest state of a channel, whereas the static backup aims to provide a simple, safe method to let users recover the settled funds in their channels in the case of partial or complete data loss [LR]. It also says what the backup contains and what it triggers: all the information needed to initiate the protocol's data loss protection feature, which ultimately leads to recovering the channel's funds on-chain [LR]."),
  (E, "A reader meets static channel backups as a file beside the chain data, which the lnd documentation describes as a special file containing backup state, and as the second of the two things its recovery procedure requires beside the cipher seed [LR]. The chapter's own warning about the relationship with the other node belongs here: if the node a wallet connects to realises that data has been lost, it may be able to steal bitcoins, and if both parties lose their databases at the same time with no adequate backup, both lose funds [AH]."),
  (H, "The mechanism connects to the rest of this chapter through its encryption. The lnd documentation says that the backup file is encrypted using a key derived from the user's seed, so that it cannot be used in isolation, and gives the reason: this protects the privacy of the user's channels in the backup state and ensures that a random node cannot attempt to import another user's channels [LR]. That is the same construction as the encrypted wallet backup two sections below, and it is why the seed remains the single root of a recovery even for data that is not derived from it."),
  (K, "The limits are stated by both sources and should be quoted rather than softened. The chapter says the method cannot guarantee results [AH]. The documentation is more precise about what is recoverable: given a valid backup a user will be able to recover funds that are fully settled within their channels, meaning funds in the base commitment outputs, the outputs of the transaction that records the channel's current division, and not those in the payments still in flight, because the backup is made right after the channel is created, when the future payments are not yet known [LR]. A learner should therefore read static as once per channel, not as complete.")), None),

 ("Encryption", "Encryption", 3, "OtherProtocolData", ("a note hidden and recovered with a derived key",
   "Encryption turns data into a form that only a holder of the key can read back; a wallet can therefore store a backup where anyone can see it, as long as the key stays secret.",
   (PROG(XOR_IO), "('ddfb63036eb21eb9', 'Paid Bob for podcast')")), P(
  (W, "Encryption is the operation that turns readable data into a form from which only a holder of the key can recover it. The chapter uses the idea without defining it, in the sentence that matters most for this branch: a few wallet applications frequently and automatically create complete backups of their wallet database encrypted by one of the keys derived from their seed [AH]. The worked example shows the shape of such an operation at its simplest: a key is derived from a seed by hashing, a note is combined with it by exclusive-or so that it becomes unreadable bytes, and combining the result with the same key again returns the original text."),
  (Y, "Encryption is what lets a backup be stored in a place the user does not control. The chapter draws exactly that conclusion: because Bitcoin keys must be unguessable and modern encryption algorithms are considered very secure, nobody should be able to open the encrypted backup except someone who can generate the seed, which makes it safe to store the backup on untrusted computers such as cloud hosting services or even random network peers [AH]. The hard problem of backups, finding a safe place, is thereby replaced by the problem already solved, keeping the seed."),
  (E, "A reader meets encryption in several places in this chapter. The Muun recovery code decrypts the private keys contained in the user's kit [AH]. The lnd static channel backup file is encrypted with a key derived from the seed [LR]. SLIP39 encrypts the master secret with the user's passphrase before splitting it, and Aezeed enciphers its whole plaintext seed, which is why its words are a ciphertext [S39] [AZ]. In each case the same pattern appears: a secret the user already keeps protects data the user cannot otherwise protect."),
  (H, "The example in the worked example is a one-time pad and is shown only for its shape; real schemes use a block cipher or an authenticated cipher, as Aezeed does with aez and SLIP39 does with a Feistel network whose round function is PBKDF2 [AZ] [S39]. What the example does show correctly is the structure a reader needs: the key comes from the seed by a one-way function, so it never has to be stored, and decryption is the same operation run again, so nothing else needs to be remembered."),
  (K, "Three cautions. A one-time pad reused on two messages is broken, which is why real schemes never derive one key for two purposes; the example's key is derived with a purpose string for exactly that reason. Encryption without authentication hides data but does not detect tampering, which is why Aezeed's designers chose a cipher with a built-in checksum [AZ]. And encryption does not reduce the number of secrets a user must keep: it moves the whole backup's safety onto the seed, so a lost seed now loses the labels as well as the keys.")), None),

 ("EncryptedWalletBackup", "Encrypted wallet backup", 3, "OtherProtocolData", ("a backup key derived from the seed",
   "An encrypted wallet backup is a complete copy of the wallet database, encrypted under a key derived from the seed, which a user can restore from a recovery code alone.",
   ("__import__('hashlib').sha256(bytes.fromhex('5b56c417303faa3f') + b'backup').hexdigest()[:8]", "'8d9a0a67'")), P(
  (W, "An encrypted wallet backup is the chapter's one solution for backing up everything at once. It describes the practice: one solution implemented by a few wallet applications is to frequently and automatically create complete backups of their wallet database, encrypted by one of the keys derived from their seed [AH]. The backup therefore contains the keys, the labels and whatever protocol data the wallet keeps, and its safety rests on the seed the user already has."),
  (Y, "The attraction is that it restores the whole wallet from one secret. The chapter describes the recovery: if the original database is lost, the user enters their recovery code into the wallet application to restore the seed, and the application can then retrieve the latest backup file, regenerate the encryption key, decrypt the backup and restore all of the user's labels and additional protocol data [AH]. Nothing else has to have been written down, which is what makes this the only mechanism in the chapter that closes the gap the branch opened with."),
  (E, "A reader meets the same construction in the lnd static channel backup, encrypted with a key derived from the user's seed so that it cannot be used in isolation [LR]. Bitcoin Core offers the plain version of the idea without the encryption: its backupwallet command, whose help text this chapter's claims read, safely copies the current wallet file to a destination, leaving the protection of that copy to the user [B31]. The worked example shows the first step of the scheme: a backup key derived from the seed by hashing it together with a purpose string."),
  (H, "The mechanism has three parts, each already covered. A key is derived from the seed, as the chapter says, by one of the keys derived from it; the database is encrypted under that key; and the encrypted file is stored somewhere the user does not need to trust [AH]. The derivation is what makes the scheme work without a second secret: the same seed that proves ownership of the coins also opens the backup, so the recovery code remains the single thing to keep."),
  (K, "Two limits deserve emphasis. The scheme concentrates risk on the seed: a leaked seed now exposes the user's complete transaction history and labels as well as their money, which is a privacy loss on top of a financial one. And the backup is only as current as its last copy, so a wallet that encrypts and uploads rarely leaves a gap; the chapter's phrase frequently and automatically is part of the design, not a detail [AH]. Few wallets implement it, which is why the chapter's closing advice is again that users must do more than back up a recovery code [AH].")), None),

 ("WalletDeployment", "Deploying keys in practice", 1, None, None, P(
  (W, "This branch is the chapter's extended worked example and its practical advice. The chapter's section on using an extended public key on a web store follows a merchant, Gabriel, from a single address on a hobby page to a shop that derives a fresh address for every order from an extended public key held on the server, and the surrounding sections give the other half of that arrangement, the keys kept offline on a device or on paper [AH]."),
  (Y, "The branch matters because it shows what the machinery of the previous branches is for. Everything the chapter has built, the tree, the extended public key, the hardened step above it, the standard path, exists so that a person can take payments without putting the power to spend on an exposed computer. The branch also introduces one new concept that only appears when the arrangement is used in earnest, the gap limit, which is the practical boundary of a deterministic wallet's ability to find its own payments."),
  (E, "The reader meets the arrangement in the chapter's narrative, in the public-key-only wallet of the first branch, and in real software: the chapter has Gabriel export an extended public key from a Trezor device using its web application, noting that the device must be plugged in for the public keys to be exported and that most hardware signing devices will never export private keys, and then copy that key into his payment processing software, such as the widely used open-source BTCPay Server [AH] [BP]."),
  (H, "The branch has two groups. The web store group covers the deployment of an extended public key, the gap limit that limits how far a wallet will look for payments, and the payment processor that puts the two together. The offline keys group covers cold storage, the hardware signing device and the written backup, which are the three ways the chapter describes of keeping the private side out of reach."),
  (K, "The branch is practice rather than protocol, and two of its lessons are organisational. The first is that the safety of the arrangement comes from the hardened step above the shared key, not from the secrecy of the extended public key, which must still be protected for privacy [B32]. The second is the chapter's closing sentence for the whole chapter: one of the leading causes of lost bitcoins, perhaps the leading cause, is data loss, and it is up to the user to actually use the systems available to make good backups and regularly test them [AH].")), None),

 ("WebStore", "An extended key on a web store", 2, "WalletDeployment", None, P(
  (W, "This group follows the chapter's web store example and the one new idea it needs. The story is told in stages: Gabriel starts with a hosted page and a single Bitcoin address, which works well enough with a few orders a week even though it weakens the privacy of Gabriel, his clients and the people he pays; then the shop becomes successful and he is overwhelmed, because with all the orders paying the same address it becomes difficult to match orders and transactions, especially when several orders for the same amount arrive close together [AH]."),
  (Y, "The group matters because it is the chapter's answer to a question students ask: why would anyone want a tree of keys? The answer is in the chapter's own words: Gabriel's wallet offers a much better solution through the ability to derive public child keys without knowing the private keys, so he can load an extended public key on his website and derive a unique address for every customer order, which immediately improves privacy and gives each order a unique identifier for tracking which invoices have been paid [AH]."),
  (H, "The three sections take the deployment, its limit and the software that implements it. The deployment section covers what is placed on the server and what that means for the risk; the gap limit section covers what happens when addresses are handed out faster than they are paid, which is the chapter's own sidebar; and the payment processor section covers the kind of program the extended public key is loaded into.")), None),

 ("XpubDeployment", "Extended public key deployment", 3, "WebStore", ("the first three addresses of a branch",
   "Deploying an extended public key means putting the watching half of a wallet on an exposed computer, which can then derive a fresh address for every order and spend nothing.",
   ("['M/84h/0h/0h/0/%d' % i for i in range(3)]", "['M/84h/0h/0h/0/0', 'M/84h/0h/0h/0/1', 'M/84h/0h/0h/0/2']")), P(
  (W, "Deploying an extended public key means installing the public half of a branch on a machine that needs to receive but not to spend. The chapter describes the case: one common application of this solution is to install an extended public key on a web server that serves an e-commerce application, so that the server can use the public key derivation function to create a new Bitcoin address for every transaction, for example for a customer shopping cart, without having any private keys that would be vulnerable to theft [AH]. The worked example writes the first three paths such a server would use."),
  (Y, "The gain is stated twice in the chapter, once in general and once in the story. In general: that kind of deployment can produce an infinite number of public keys and addresses but cannot spend any of the money sent to them, while on another, more secure machine the extended private key can derive the corresponding private keys and spend [AH]. In the story: using the HD wallet allows Gabriel to spend from his personal wallet while the extended public key on the website can only generate addresses and receive funds, which the chapter calls a great security feature, because Gabriel's website contains no private keys and any hack of it can only steal the funds he would have received in the future, not those he received in the past [AH]."),
  (E, "A reader meets the deployment in the chapter's narrative, where Gabriel exports the key from his hardware device and copies it into his payment software, and in the alternative the chapter mentions for comparison: without HD wallets the only way to do this is to generate thousands of addresses on a separate secure server and preload them on the shop's server, an approach the chapter calls cumbersome and in need of constant maintenance to ensure the shop does not run out of keys [AH]. BIP32's own use case for an unsecure money receiver describes the same arrangement and its limits [B32]."),
  (H, "The mechanism is the public derivation of the previous branch applied at the two normal levels of a standard path. The server holds the account's extended public key, derives the branch and then each index, and never needs a private key; the chapter notes that the branch structure itself can carry meaning, with one branch for incoming payments and another for change [AH]. Because the account level is hardened, nothing the server holds can be used to work back to the master key, which is the design rule the chapter gives as best practice [AH] [B32]."),
  (K, "Two risks remain and the sources name both. The first is privacy: BIP32 says that someone who illegally obtains access to the web server can at most see all incoming payments, and that is already a serious loss, since the extended public key reveals every address of the branch [B32]. The second is substitution: a compromised server can be made to show the attacker's own addresses rather than the merchant's, which no amount of key separation prevents; the chapter's claim is only that past funds are safe [AH].")), None),

 ("GapLimit", "Gap limit", 3, "WebStore", ("a payment at index 25 missed by a scan with a gap of 20",
   "The gap limit is the number of unused addresses in a row that a wallet will tolerate before it stops looking for payments; a payment beyond it is not found.",
   (PROG(GAP_IO), "([0, 3], 24)")), P(
  (W, "The gap limit is how far a wallet keeps looking after it stops finding payments. The chapter introduces it in a sidebar: an extended public key can generate approximately four billion direct child keys, far more than any store should need, but it would take an unreasonable amount of time to generate all of them and scan the blockchain for transactions involving them, so most wallets generate only a few keys at a time, scan for payments involving those keys, and generate more as the previous ones are used [AH]. The maximum number of unused keys in a row that can fail to receive a payment without causing problems is what it calls the gap limit [AH]."),
  (Y, "The limit matters because exceeding it loses money in the most confusing possible way: the funds are on the blockchain, the keys are derivable, and the wallet still shows nothing. The chapter explains how a gap arises in ordinary use: sometimes a wallet distributes a key to someone who later decides not to pay, creating a gap in the key chain, which is fine as long as the wallet has already generated keys after the gap so that it finds later payments and continues generating more [AH]."),
  (E, "The worked example is a scan with the standard limit. BIP44 sets the address gap limit at 20, saying that if the software hits twenty unused addresses in a row it expects there are no used addresses beyond that point and stops searching the chain [B44]. The example scans a branch in which indices 0, 3 and 25 received payments: it finds 0 and 3, stops after examining index 23, and never sees the payment at 25. Bitcoin Core avoids the situation by preparing many keys in advance, 1,000 by default, which its source calls the look-ahead process used to detect payments, and the wallet in this chapter's evidence shows that range from 0 to 999 [BCW] [B31]."),
  (H, "The chapter lists the three choices a wallet has when it has handed out keys up to its limit and none has been paid, and each has a cost: it can refuse further requests, which is unpalatable although simplest and prevents any further payments; it can generate keys beyond the limit, which gives every payer a unique key and preserves privacy but means that a restoration, or other software loaded with the same extended public key, will not see payments received after the extended gap; or it can hand out keys it has already distributed, which ensures a smooth recovery but reduces the privacy of the owner and of the people they transact with [AH]."),
  (K, "The chapter's note on how production systems cope is the practical lesson, and so is its note on what has not been solved. Open-source production systems for online merchants, such as BTCPay Server, attempt to dodge the problem by using very large gap limits and limiting the rate at which they generate invoices; other solutions have been proposed, such as asking the spender's wallet to construct but not broadcast a transaction paying a possibly reused address before a fresh address is given out, but these have not been used in production as of the chapter's writing [AH]. BIP44 adds the rule a wallet should follow in the meantime: warn the user when they are about to exceed the gap limit [B44].")), None),

 ("PaymentProcessor", "Payment processor", 3, "WebStore", ("the software the extended public key is loaded into",
   "A payment processor is the program that watches for payments and matches them to orders; a self-hosted one lets a merchant accept bitcoins with the extended public key as its only key material.",
   None), P(
  (W, "A payment processor, in the chapter's story, is the software that turns an extended public key into a working shop. The chapter says that Gabriel copies the extended public key to his web store's Bitcoin payment processing software, such as the widely used open-source BTCPay Server [AH]. That project describes itself in the same terms: a free and open-source, self-hosted Bitcoin payment processor that lets merchants accept Bitcoin directly, without fees or intermediaries [BP]."),
  (Y, "The processor matters because it is where the bookkeeping of the previous branch actually happens. Somebody has to derive the next address, show it to the customer, watch the blockchain for a payment of the right amount to that address, mark the invoice paid and keep the association for later; the chapter's point about the unique identifier only becomes real inside such a program [AH]. The self-hosted kind is also the one that fits the rest of the chapter, because an intermediary would hold the keys and the whole arrangement would be unnecessary."),
  (E, "A reader meets the processor at the end of the web store story and in the gap limit sidebar, where the chapter names BTCPay Server as one of the open-source production systems for online merchants that use very large gap limits and limit the rate at which they generate invoices [AH]. The project's own documentation is organised for the roles the chapter implies, with separate guides for users, operators and developers, and it is released under a permissive licence [BP]."),
  (H, "The mechanism from this chapter's point of view is a loop over the address index. The processor holds the account's extended public key, keeps a record of the next unused index, derives an address for each new invoice and watches for payments to the addresses it has derived; because it holds no private key, the worst a compromise can do is divert future payments, as the deployment section explained [AH] [B32]. Its interaction with the gap limit is the subject of the previous section."),
  (K, "Two cautions. The chapter names one product as an example and this course should not read that as a recommendation; what matters is the property, self-hosted and holding no private keys. And a processor is a piece of infrastructure with its own backup problem: the association between invoices and addresses is exactly the non-key data of the previous branch, so a merchant who restores only the seed recovers the money and loses the order book [AH] [B329].")), None),

 ("OfflineKeys", "Keys kept offline", 2, "WalletDeployment", None, P(
  (W, "This group covers the other half of every arrangement in the chapter: where the private keys are when they are not in use. The chapter names the cases together: another common application of public derivation is for cold storage or hardware signing devices, in which the extended private key can be stored on a paper wallet or hardware device while the extended public key is kept online, so that the user can create receive addresses at will while the private keys are safely stored offline, and spending is done with the extended private key on an offline wallet or the hardware device [AH]."),
  (Y, "The group matters because the whole chapter's reasoning about which key is where becomes a decision about physical objects. A seed written on paper, a device in a drawer, a code memorised: each is a different trade-off between the risk of loss and the risk of theft, which the first branch examined in the abstract. The group also closes the chapter's advice, which is to write the recovery code down and to test the backup."),
  (H, "The three sections take the state, the device and the paper. Cold storage is the condition of keys kept offline; the hardware signing device is the object that makes using them convenient; and the written backup is the chapter's own recommendation about the recovery code, with the reasons it gives for preferring paper to memory.")), None),

 ("ColdStorage", "Cold storage", 3, "OfflineKeys", ("keys that never touch a connected computer",
   "Cold storage means keeping keys offline, created and stored in a secure environment that is not connected to a network, so that an attack on a connected computer cannot reach them.",
   None), P(
  (W, "Cold storage is the practice of keeping keys where no connected computer can read them. The book's glossary defines it as keeping a reserve of bitcoin offline, achieved when the private keys are created and stored in a secure offline environment, and adds that it is important for anyone with bitcoin holdings because online computers are vulnerable to attackers and should not be used to store a significant amount [AHG]. The chapter names cold storage as one of the two common applications of public child derivation, beside hardware signing devices [AH]."),
  (Y, "The reason is the asymmetry between receiving and spending. Receiving needs only public information, which the deployment section showed can live on an exposed machine; spending needs the private key, and spending happens rarely. Keeping the private side offline therefore costs little convenience and removes the largest class of attack, which is why the chapter's arrangement, extended public key online and extended private key offline, is the standard shape of a careful setup [AH]."),
  (E, "A reader meets cold storage in this chapter as the destination of an extended private key, on a paper wallet or a hardware device, and in chapter 4 of the book, which treats the paper wallet as an older form of the same idea [AH]. The arrangement in the chapter's web store story is cold storage in practice: Gabriel's keys are on a Trezor device and the shop sees only the extended public key [AH]."),
  (H, "The mechanism is the separation of the two halves of the tree, which this chapter has now described from three directions: public derivation makes the receiving side possible without secrets; a hardened step above the shared key makes the leak of a child harmless to the master; and an offline device or a written seed holds the private side [AH] [B32]. Spending is then a transfer of an unsigned transaction to the offline side and of a signature back, which is the external signing of the chapter's first branch [AH]."),
  (K, "Cold storage moves risk rather than removing it, and the direction it moves is towards loss. An offline key cannot be stolen over a network and cannot be recovered if the paper burns, which is why the chapter's advice about recovery codes applies with full force to cold storage: the code, not the device, is the backup. A reader should also note that cold does not mean unused: a device that is never tested is a backup whose condition is unknown, which is the chapter's final point about testing [AH].")), None),

 ("HardwareSigningDevice", "Hardware signing device", 3, "OfflineKeys", ("a device that signs but does not export",
   "A hardware signing device stores private keys and produces signatures on request without revealing the keys, so a less secure computer can build transactions it cannot sign.",
   None), P(
  (W, "A hardware signing device is a small purpose-built computer that holds private keys and signs with them. The chapter introduces it in its first branch, where it says that a user can provide the key tweaks she used to a hardware signing device, sometimes confusingly called a hardware wallet, that securely stores her original private key, and that the device uses the tweaks to derive the necessary child private keys and sign the transactions, returning them to the less secure frontend for broadcast [AH]. The chapter's parenthesis about the name is worth keeping: the device signs, and the wallet is the database and the application."),
  (Y, "The device exists because a general-purpose computer cannot be trusted with a key that cannot be replaced. By keeping the key inside and exposing only a signing operation, the device reduces what an attacker on the connected computer can do to proposing transactions, which the user is asked to confirm on the device's own screen. This is the arrangement the chapter calls the separation of wallet frontends, which do not require private keys, from signing operations, which do [AH]."),
  (E, "A reader meets the device in the chapter's web store story, where Gabriel exports an extended public key from his Trezor device using the web-based wallet application, with the device plugged in, and where the chapter notes that most hardware signing devices will never export private keys, since those always remain on the device [AH]. The reader also meets its influence on the standards of this chapter: BIP39 was proposed by the company behind the Trezor device, and the chapter says BIP39's weak key-stretching parameters are likely a consequence of being designed for compatibility with such devices and their low-powered processors [AH]."),
  (H, "The mechanism that matters here is what crosses the boundary. Out of the device come public keys, extended public keys and signatures; into it go transactions to sign and the derivation information needed to find the right key, which is why descriptors carry a key origin with a master fingerprint and a path [B380]. The device's own backup is a recovery code, which it shows once when it is initialised, so the device is replaceable while the code is not."),
  (K, "Three cautions. The name hardware wallet invites the belief that the coins are in the device, which the chapter's first branch corrected: the device holds keys, and the coins are outputs on the blockchain [AH]. A device protects the key from a compromised computer, not the user from a mistaken confirmation. And a device is a thing that can be lost, which is why the chapter's advice about writing the code down is the real backup, as the next section explains.")), None),

 ("WrittenBackup", "Written backup", 3, "OfflineKeys", ("twelve words instead of thirty-two hexadecimal digits",
   "A written backup is the recovery code on paper, which the chapter recommends even for schemes designed to be memorised, because memory fails and cannot be inherited.",
   ("(len('0c1e24e5917779d297e14d45f14e1a1a'), len('army van defense carry jealous true garbage claim echo media make crunch'.split()))",
    "(32, 12)")), P(
  (W, "A written backup is the recovery code recorded on a physical medium. The chapter's recommendation is explicit: even if a type of recovery code designed for easy memorisation is used, the authors very strongly encourage the reader to consider writing it down [AH]. The worked example compares what is written in the two encodings the chapter prints for the same 128 bits: thirty-two hexadecimal digits against twelve English words [AH]."),
  (Y, "The reason is the list of failure modes the first branch gave. Memory fails, so a forgotten code with a lost database means the bitcoins are lost forever; memory cannot be inherited, so heirs without access to the database cannot inherit; and a memorised code can be the reason a person is coerced [AH]. Paper fails differently, and the two failure modes are largely independent, which is why holding both is better than holding either."),
  (E, "A reader meets the written backup as the card a hardware device ships with, as the chapter's own table of a code in hexadecimal and in words, and in the owner's course notes for this chapter, which include a slide showing an example paper backup of the code [AH] [AL]. The schemes of the first branch differ in how well they suit paper: codex32 was designed so that codes can be created and validated with printed instructions and simple tools, while Muun's arrangement requires a printed kit beside the code [B93] [MU]."),
  (H, "What is written is the code and, where used, a note that a passphrase exists, though the chapter warns against keeping the passphrase in the same place [AH]. For explicit-path wallets the descriptor should be written too, which is the previous branch's conclusion; for multisignature arrangements each participant must record the other participants' public keys [AH]. The chapter's three technologies, a BIP39 code, BIP32 derivation and a BIP44-style path, are exactly the three things a complete written backup records, two of them implicitly [AH]."),
  (K, "Paper has its own risks, and a course should name them: it burns, it fades, it can be photographed, and a code lying in a drawer is a bearer instrument that anyone in the house can carry away. The chapter's answer is not to choose between paper and memory but to plan: it recommends using a passphrase only together with a carefully planned process for backup and recovery that considers surviving the owner, and it closes the chapter by saying that it is up to the reader to actually use the systems available to make good backups and regularly test them [AH].")), None),
]

CHECKS_G = [
 # non-key data
 Qb("ch05_wallets.adoc", "The", "most important data in a wallet database is its private keys",
    "many wallet databases store more than\njust keys--they also store user-provided information about every\ntransaction they sent or received",
    "he", "adds a _label_ to the address he generates\nso that he can distinguish her payment\nfrom other payments he receives",
    "she\nlabels the transaction as paying Bob for the same reason",
    "such as the current\nexchange rate, which can be useful for calculating taxes in some\njurisdictions",
    "These labels are stored entirely within their own\nwallets--not shared with the network--protecting their privacy\nand keeping unnecessary personal data out of the blockchain",
    "they can't\nbe restored by using just a recovery code", "all the user will see is a list of approximate\ntransaction times and bitcoin amounts",
    "Imagine reviewing a\nbank or credit card statement from a year ago that had the date and\namount of every transaction listed but a blank entry for the\n\"description\" field",
    "there are a number of\nwidely used wallet applications that make it easy to create and use\nrecovery codes but that provide no way to back up or restore label\ndata",
    "A standard for that format is\nproposed in BIP329"),
 Qb("ch05_wallets.adoc", "<td><p>Bought bitcoins from Joe</p></td>", "<td><p>+0.00100</p></td>", "<td><p>Paid Bob for podcast</p></td>", "<td><p>−0.00075</p></td>"),
 ("round(0.00100 - 0.00075, 5)", "0.00025"), ("100000 - 75000", "25000"),
 Qe("bip-0329.mediawiki", "This document specifies a format for the export of labels that may be attached to various common types of records in a wallet",
    "The export and import of funds across different Bitcoin wallet applications is well defined through standards such as BIP39, BIP32, BIP44 etc",
    "There is, however, no defined standard to transfer any labels the user may have applied",
    "Allowing users to import and export their labels in a standardized way ensures that they do not experience lock-in to a particular wallet application",
    "have even become mandatory when spending in several Bitcoin wallets",
    "this BIP uses a JSON format", "the JSON Lines format is used (also called newline-delimited JSON)",
    "This allows a document to be split, streamed, or incrementally added to, and limits the potential for formatting errors to invalidate an entire import",
    "an export of labels from a wallet must be a UTF-8 encoded text file, containing one record per line consisting of a valid JSON object",
    "Multiline values are not permitted.", "| One of <tt>tx</tt>, <tt>addr</tt>, <tt>pubkey</tt>, <tt>input</tt>, <tt>output</tt>, <tt>xpub</tt> or <tt>spscan</tt>",
    "| Transaction id in hexadecimal format", "| Address in base58 or bech32 format", "| Extended public key as defined by BIP32",
    "Each JSON object must contain both <tt>type</tt> and <tt>ref</tt> properties",
    "many wallets allow unspent outputs to be frozen or made unspendable within the wallet",
    "This property should be used to disambiguate transaction labels from different wallets contained in the same export",
    "Care should be taken when exporting due to the privacy sensitive nature of the data",
    "Encryption in transit over untrusted networks is highly recommended, and encryption at rest should also be considered",
    "Unencrypted exports should be deleted as soon as possible", "For security reasons no private key types are defined", "Status: Draft"),
 (PROG(LABEL_IO),
  "'{\"label\": \"Paid Bob for podcast\", \"ref\": \"bc1qcr8te4kr609gcawutmrza0j4xv80jy8z306fyu\", \"type\": \"addr\"}'"),
 ("len(__import__('json').dumps({'type': 'addr', 'ref': 'x', 'label': 'y'}).splitlines())", "1"),
 # Lightning and static channel backups
 Qb("ch05_wallets.adoc", "as of 2023, an increasing number of applications have added support for\nsending and receiving transactions over the Lightning Network (LN)",
    "Although the LN protocol provides a method to recover\nfunds in the event of a data loss, called _static channel backups_, it\ncan't guarantee results",
    "If the node your wallet connects to realizes\nyou've lost data, it may be able to steal bitcoins from you",
    "If it\nloses its wallet database at the same time you lose your database, and\nneither of you has an adequate backup, you'll both lose funds",
    "Again, this means users and wallet applications need to do more than just back up a\nrecovery code"),
 Qb("glossary.asciidoc", "Lightning Network is a proposed implementation of Hashed Timelock Contracts (HTLCs) with bi-directional payment channels which allows payments to be securely routed across multiple peer-to-peer payment channels",
    "A Hashed TimeLock Contract or HTLC is a class of payments that use hashlocks and timelocks to require that the receiver of a payment either acknowledge receiving the payment prior to a deadline by generating cryptographic proof of payment or forfeit the ability to claim the payment"),
 Qb("ch14_applications.adoc", "introduce bidirectional payment channels", "first proposed under the name _Lightning\nNetwork_"),
 Qe("lnd_recovery.md", "On-chain funds are outputs under the control of `lnd` that can be spent immediately, and without any auxiliary data",
    "Off-chain funds on the other hand exist within a 2-of-2 multi-sig output typically referred to as a payment channel",
    "The SCB file is encrypted using a key _derived_ from the user's seed. As a result, it cannot be used in isolation",
    "We call these _static_ as they only need to be obtained _once_: when the channel is created. From there on, a backup is good until the channel is closed",
    "The backup contains all the information we need to initiate the Data Loss Protection (DLP) feature in the protocol, which ultimately leads to us recovering the funds from the channel _on-chain_",
    "Those methods can be dangerous as one never knows if they have the latest state of a channel or not",
    "we aim to provide a simple, safe method to allow users to recover the settled funds in their channels in the case of partial or complete data loss",
    "The backups themselves are encrypted using a key derived from the user's seed",
    "Given a valid SCB, the user will be able to recover funds that are fully settled within their channels",
    "By \"fully settled\" we mean funds that are in the base commitment outputs, and not HTLCs"),
 # encryption and the encrypted backup
 Qb("ch05_wallets.adoc", "One solution implemented by a few wallet applications is to frequently\nand automatically create complete backups of their wallet database\nencrypted by one of the keys derived from their seed",
    "Bitcoin keys must\nbe unguessable and modern encryption algorithms are considered very\nsecure, so nobody should be able to open the encrypted backup except\nsomeone who can generate the seed",
    "This makes it safe to store the backup on\nuntrusted computers such as cloud hosting services or even random\nnetwork peers",
    "The\napplication can then retrieve the latest backup file, regenerate the\nencryption key, decrypt the backup, and restore all of the user's labels\nand additional"),
 (PROG(XOR_IO), "('ddfb63036eb21eb9', 'Paid Bob for podcast')"),
 ("__import__('hashlib').sha256(bytes.fromhex('5b56c417303faa3f') + b'backup').hexdigest()[:8]", "'8d9a0a67'"),
 ("__import__('hashlib').sha256(bytes.fromhex('5b56c417303faa3f') + b'backup') .hexdigest() != __import__('hashlib').sha256(bytes.fromhex('5b56c417303faa3f') + b'labels').hexdigest()", "True"),
 Qe("core_help_backupwallet_31_1_v1_0_0.txt", "Safely copies the current wallet file to the specified destination"),
 # the web store, the gap limit, the processor
 Qb("ch05_wallets.adoc", "Gabriel used the first Bitcoin address generated by his regular wallet as\nthe main Bitcoin address for his store",
    "even though it weakened the privacy of\nGabriel, his clients, and the people he paid",
    "With all\nthe orders paying the same address, it became difficult to correctly\nmatch orders and transactions, especially when multiple orders for the\nsame amount came in close together",
    "The only metadata that is chosen by the receiver of a typical Bitcoin\ntransaction are the amount and payment address",
    "Gabriel can\nload an extended public key (xpub) on his website, which can be used to\nderive a unique address for every customer order",
    "the xpub loaded on the website can only\ngenerate addresses and receive funds",
    "any hack of it can only steal the funds Gabriel would\nhave received in the future, not any funds he received in the past",
    "The Trezor device must be plugged in\nfor the public keys to be exported", "most hardware signing devices will\nnever export private keys--those always remain on the device",
    "Gabriel copies the xpub to his web store's Bitcoin payment processing\nsoftware, such as the widely used open source BTCPay Server"),
 Qb("ch05_wallets.adoc", "One common application of this solution is to install an extended public\nkey on a web server that serves an ecommerce application",
    "The web server will not have any private keys that would be vulnerable to\ntheft",
    "the only way to do this is to generate\nthousands of Bitcoin addresses on a separate secure server and then\npreload them on the ecommerce server",
    "That approach is cumbersome and\nrequires constant maintenance to ensure that the ecommerce server\ndoesn't \"run out\" of keys",
    "the extended\nprivate key can be stored on a paper wallet or hardware device, while\nthe extended public key can be kept online"),
 Qb("ch05_wallets.adoc", "extended public key can generate approximately 4 billion direct\nchild keys",
    "most wallets only\ngenerate a few keys at a time, scan for payments involving those keys,\nand generate additional keys in the sequence as the previous keys are used",
    "For example, Alice's wallet generates 100 keys.  When it sees a payment\nto the first key, it generates the 101st key",
    "Sometimes a wallet application will distribute a key to someone who\nlater decides not to pay, creating a gap in the key chain",
    "The maximum\nnumber of unused keys in a row that can fail to receive a payment\nwithout causing problems is called the _gap limit_",
    "It can refuse the requests, preventing it from receiving any further\npayments",
    "It can generate new keys beyond its gap limit", "those other wallets\nwon't see any payments received after the extended gap",
    "It can distribute keys it previously distributed, ensuring a smooth\nrecovery but potentially reducing the privacy of the wallet owner",
    "such as BTCPay\nServer, attempt to dodge this problem by using very large gap limits and\nlimiting the rate at which they generate invoices",
    "asking the spender's wallet to construct (but not broadcast) a\ntransaction paying a possibly reused address before they receive a fresh\naddress for the actual transaction",
    "these other solutions have\nnot been used in production as of this"),
 (PROG(GAP_IO), "([0, 3], 24)"),
 X("W.scan_with_gap({0, 3, 25}, 20)", "[0, 3]"),
 X("W.scan_with_gap({0, 3, 25}, 25)", "[0, 3, 25]"),
 X("W.scan_with_gap(set(range(0, 200, 19)), 20)", "[0, 19, 38, 57, 76, 95, 114, 133, 152, 171, 190]"),
 Qe("bip-0044.mediawiki", "Address gap limit is currently set to 20", "If the software hits 20 unused addresses in a row, it expects there are no used addresses beyond this point and stops searching the address chain"),
 Qc("src/wallet/scriptpubkeyman.h", "inline constexpr unsigned int DEFAULT_KEYPOOL_SIZE = 1000;"),
 Qc("src/wallet/wallet.h", "Number of pre-generated keys/scripts by each spkm (part of the look-ahead process, used to detect payments)"),
 Qe("core_help_keypool_31_1_v1_0_0.txt", "Set key pool size to <n> (default: 1000)", "Smaller sizes may increase the risk of losing funds when restoring from an old backup"),
 Qe("core_fresh_wallet_31_1_v1_0_0.json", '"keypoolsize": 3999', '"keypoolsize_hd_internal": 4000'),
 ("['M/84h/0h/0h/0/%d' % i for i in range(3)]", "['M/84h/0h/0h/0/0', 'M/84h/0h/0h/0/1', 'M/84h/0h/0h/0/2']"),
 Qe("btcpayserver_README.md", "BTCPay Server is a free and open-source, self-hosted Bitcoin payment processor. It lets merchants accept Bitcoin directly, without fees or intermediaries"),
 Qe("bip-0032.mediawiki", "someone illegally obtaining access to the webserver can at most see all incoming payments but will not be able to steal the money"),
 # offline keys
 Qb("glossary.asciidoc", "Refers to keeping a reserve of bitcoin offline. Cold storage is achieved when Bitcoin private keys are created and stored in a secure offline environment",
    "Online computers are vulnerable to hackers and should not be used to store a significant amount of bitcoin"),
 Qb("ch05_wallets.adoc", "Another common application of this solution is for\ncold-storage or hardware signing devices",
    "The\nuser can create \"receive\" addresses at will, while the private keys are\nsafely stored offline",
    "she can provide the key tweaks\nshe used", "to a _hardware signing device_ (sometimes confusingly called a\n_hardware wallet_) that securely stores her original private key",
    "The\nhardware signer uses the tweaks to derive the necessary child private\nkeys and uses them to sign the transactions, returning the signed\ntransactions to the less-secure frontend for broadcast to the Bitcoin\nnetwork",
    "This technique is commonly used to separate wallet application\nfrontends (which don't require private keys) from signing operations\n(which do require private keys)"),
 Qb("ch05_wallets.adoc", "BIP39 was proposed by the company behind the Trezor hardware wallet"),
 Qb("ch05_wallets.adoc", "one of the leading causes of lost bitcoins--perhaps _the_\nleading cause--is data loss",
    "it's up to you to\nactually use the systems available to make good backups and", "regularly\ntest them"),
 ("(len('0c1e24e5917779d297e14d45f14e1a1a'), len('army van defense carry jealous true garbage claim echo media make crunch'.split()))", "(32, 12)"),
 Pp("Chapter_5_Wallets_v1_0_0.pptx", "Gabriel’s Case", "Hardware Wallet", "Trezor Usage", "Backup", "Table 5-1. Example paper backup of the mnemonic"),
]
