"""SEN0401 chapter 5, corpus text part F (version 1.0.0): the branch 'Backing up derivation paths' - implicit and explicit paths, the four
standard paths the chapter tabulates, multisignature as the case that needs explicit paths, and output script descriptors with their checksum,
key origin, multipath form and miniscript. Markers such as [AH] become author-year strings."""
from sen0401_ch05_common_v1_0_0 import *

DESC84 = "wpkh([6d8c4b8f/84h/0h/0h]xpub6CwyJSJaLE3Kbot3LrjZkkMAfT2fNuzHrn2S4iHAwTctsp23par19x6D2FHkG6ypKdmJPsfcsbbrYqQSVuXrWME6QBFjvyuDod2UvsTRPhB/0/*)"
H160_84 = "c0cebcd6c3d3ca8c75dc5ec62ebe55330ef910e2"      # hash160 of the BIP84 test vector's first receiving public key
IKEY86 = "cc8a4bc64d897bddc5fbc2f670f7a8ba0b386779106cf1223c6fc5d7cd6fc115"   # BIP86 test vector internal key
BECH32 = ("CHARSET = 'qpzry9x8gf2tvdw0s3jn54khce6mua7l'\n"
          "def polymod(values):\n"
          "    gen = (0x3b6a57b2, 0x26508e6d, 0x1ea119fa, 0x3d4233dd, 0x2a1462b3); chk = 1\n"
          "    for v in values:\n"
          "        top = chk >> 25; chk = (chk & 0x1ffffff) << 5 ^ v\n"
          "        for i in range(5): chk ^= gen[i] if (top >> i) & 1 else 0\n"
          "    return chk\n"
          "def convertbits(data):\n"
          "    acc = bits = 0; out = []\n"
          "    for v in data:\n"
          "        acc = (acc << 8) | v; bits += 8\n"
          "        while bits >= 5: bits -= 5; out.append((acc >> bits) & 31)\n"
          "    return out\n"
          "data = [0] + convertbits(bytes.fromhex(%r))\n"
          "values = [ord(c) >> 5 for c in 'bc'] + [0] + [ord(c) & 31 for c in 'bc'] + data\n"
          "pm = polymod(values + [0] * 6) ^ 1\n"
          "result = 'bc1' + ''.join(CHARSET[d] for d in data + [(pm >> 5 * (5 - i)) & 31 for i in range(6)])" % H160_84)
ORIGIN = ("import re\n"
          "d = %r\n"
          "m = re.search(r\"\\[([0-9a-f]{8})((?:/\\d+[h'])*)\\]\", d)\n"
          "result = (m.group(1), [int(p.rstrip(\"h'\")) for p in m.group(2).split('/')[1:]])" % DESC84)
MULTIPATH = ("d = 'wpkh([6d8c4b8f/84h/0h/0h]xpub.../<0;1>/*)'\n"
             "head, rest = d.split('<')\n"
             "choices, tail = rest.split('>')\n"
             "result = [head + c + tail for c in choices.split(';')]")

NODES_F = [
 ("PathBackup", "Backing up derivation paths", 1, None, None, P(
  (W, "This branch is about the part of a backup that a recovery code does not contain. The chapter states the problem at the head of its section on backing up key derivation paths: in a BIP32 tree there are approximately four billion first-level keys, each of which can have its own four billion children, and so on, so it is not possible for a wallet to generate even a small fraction of every possible key, which means that recovering from data loss requires knowing more than the recovery code, the algorithm for obtaining the seed and the derivation algorithm, it also requires knowing what paths in the tree the wallet used for the keys it distributed [AH]."),
  (Y, "The branch matters because this is the gap through which money is actually lost. A user who holds a perfectly good recovery code and enters it into the wrong software may see an empty wallet, not because the keys are gone but because the software looked in a different part of the tree. The chapter says that two solutions to this problem have been adopted, and the whole branch is the comparison of those two: standard paths that every wallet knows, which it calls implicit paths, and paths recorded beside the code, which it calls explicit paths [AH]."),
  (E, "A reader meets the two solutions in the two kinds of wallet the chapter describes at the end of the section: it has long been the trend for wallets designed only for single-signature scripts to use implicit paths, while wallets designed for multiple signatures or other advanced scripts increasingly support explicit paths using descriptors, and applications that do both usually conform to the implicit standards and also provide descriptors [AH]. The evidence of this chapter shows the second kind in use: Bitcoin Core 31.1 described every key of a fresh wallet by a descriptor that states the script type, the key origin and the path [B31]."),
  (H, "The branch has two groups. The path conventions group explains the implicit and the explicit approach, then the four standard paths the chapter tabulates, one for each script type, and finally multisignature, which is the case the chapter uses to show why implicit paths are not enough. The descriptors group covers the standard that explicit paths are written in: what an output script is, what a descriptor says about one, the checksum that protects it, the key origin that records where its keys came from, the multipath form that writes a receive and a change descriptor as one, and miniscript, which describes the spending conditions themselves."),
  (K, "One caution frames the whole branch: neither solution removes the need for the recovery code, and neither is complete on its own. Implicit paths leave a wallet guessing which features were used; explicit paths require more to be written down. The chapter's own judgement is that the advantage of explicit paths is that they can describe exactly what keys should be used with what scripts, with no need to support outdated scripts and no compatibility problems, while their disadvantage is that they require users to back up additional information, which usually cannot compromise security but can reduce privacy and does require some protection [AH].")), None),

 ("PathConventions", "Implicit and explicit paths", 2, "PathBackup", None, P(
  (W, "This group covers the two ways of knowing which paths a wallet used. The first, which the chapter calls implicit paths, is to use standardised paths that every implementation of the standard knows, so that nothing has to be recorded; the second, explicit paths, is to back up the path information with the recovery code, making it clear which path is used with which scripts [AH]. The group also covers the standardised paths themselves and the case, multisignature, in which no standard path can be enough."),
  (Y, "The choice between the two is the chapter's main argument in this part, and it is a trade-off rather than a verdict. Implicit paths are convenient and inflexible; explicit paths are flexible and demand more of the user. Since the recovery code is the only thing many users keep, the question of what else must be kept beside it is a practical one, and a course that leaves it unanswered leaves the reader with an incomplete backup."),
  (H, "The sections begin with the two approaches and the chapter's arguments for and against each. Then come the four standard paths of the chapter's table, in the order the table gives them: BIP44 for legacy addresses, BIP49 for segwit nested in a script hash, BIP84 for native segwit and BIP86 for single-key taproot; each section says what the path is for and recomputes something from the standard's own test vectors. The group closes with multisignature, which the chapter uses to show that some information is neither universal nor derivable from the seed.")), None),

 ("ImplicitPath", "Implicit path", 3, "PathConventions", ("the path a wallet assumes",
   "An implicit path is a standardised derivation path that a wallet uses without being told, so that nothing has to be backed up beside the recovery code - at the price of inflexibility.",
   None), P(
  (W, "An implicit path is a path that does not have to be recorded because it is fixed by a standard. The chapter introduces the term through its mechanism: every time there is a change related to the addresses that wallets might want to generate, someone creates a BIP defining what derivation path to use, as BIP44 defines m/44'/0'/0' as the path for keys in pay-to-public-key-hash scripts, and a wallet implementing that standard uses the keys in that path both when it is first started and after a restoration from a recovery code [AH]."),
  (Y, "The gain is that a user needs to keep only the words. The chapter states it in one sentence: the advantage of implicit paths is that users do not need to keep a record of what paths they use, because if the code is entered into the same wallet application as before, of the same version or higher, it will automatically regenerate keys for the same paths it previously used [AH]. For the large majority of users, who hold one single-signature wallet, this is the whole of path management."),
  (E, "A reader meets implicit paths as the four rows of the chapter's table of implicit script paths, and as the behaviour of any wallet that asks only for words when restoring [AH]. BIP44's own account discovery algorithm is the implicit approach written out: derive the first account, derive its external chain, scan its addresses respecting the gap limit, and stop when an account has no transactions [B44]. Bitcoin Core's descriptor wallets use the standard paths by default too, which its documentation records for BIPs 43, 44, 49, 84 and 86 [BC]."),
  (H, "The mechanism is a convention plus a search. On restoration a wallet derives the keys for every path it supports and scans the blockchain for transactions involving those keys; the chapter names that as the disadvantage, saying that this is wasteful in wallets that support many features, each with its own path, if the user tried only a few of them [AH]. The search is bounded in two directions, by the set of paths the software knows and by the gap limit at each path's address index, and anything outside those bounds is not found."),
  (K, "The chapter lists three consequences a reader should be able to state. For codes without a version number, such as BIP39 and SLIP39, a new version of a wallet that drops support for an older path cannot warn users during the restore that some funds may not be found, and the same happens in reverse when a code is entered into older software that does not know the newer paths; codes that carry version information, such as Electrum version 2 and Aezeed, can detect this and direct the user to appropriate resources [AH]. And implicit paths can only carry information that is either universal or derived from the seed, so important non-deterministic information specific to a user cannot be restored from a code at all [AH].")), None),

 ("ExplicitPath", "Explicit path", 3, "PathConventions", ("the path written down with the code",
   "An explicit path is derivation information backed up alongside the recovery code, which says exactly which keys go with which scripts and can carry extra data such as other people's public keys.",
   None), P(
  (W, "An explicit path is path information that is written down. The chapter defines it by contrast with the first solution: the second solution is to back up the path information with the recovery code, making it clear which path is used with which scripts, and the chapter calls this explicit paths [AH]. In practice the information is written in a standard notation: the chapter says that almost all wallets that use explicit paths use the output script descriptors standard, specified in BIPs 380 to 386 and 389 [AH]."),
  (Y, "The gain is exactness, and the chapter sets out what that buys: explicit paths can describe exactly what keys should be used with what scripts, there is no need to support outdated scripts, there are no problems with backward or forward compatibility, and any extra information, such as the public keys of other users, can be included directly [AH]. BIP380's motivation makes the same argument from the wallet author's side, saying that a backup of private keys alone is insufficient, especially since segregated witness added new output types, because a restored wallet cannot know which kinds of output script and address to produce [B380]."),
  (E, "A reader meets explicit paths wherever a wallet shows or asks for a descriptor. Bitcoin Core is the clearest example: the wallet in this chapter's evidence lists eight descriptors, four script types with a receive and a change branch each, every one carrying its key origin and path, and the command that lists them is documented as listing all descriptors present in a wallet [B31]. The chapter's own sample table of descriptors is taken from Bitcoin Core's documentation, whose text this chapter's claims read [AH] [BCD]."),
  (H, "The mechanism is that the derivation information travels with the key rather than being assumed. A descriptor contains the script function, the key or extended key, the key origin, which records the fingerprint and the path above that key, and the path below it, so a restoring wallet needs to guess nothing [B380]. Because the information is not secret in the way a key is, it can be kept with less protection than the recovery code, which the chapter notes when it says the additional information usually cannot compromise a user's security [AH]."),
  (K, "The cost is the obvious one and the chapter states it: explicit paths require users to back up additional information along with their recovery code, and although that information usually cannot compromise security it can reduce privacy and does require some protection [AH]. The privacy point is worth taking seriously, since an extended public key in a descriptor reveals every address of its branch [B32]. A second caution is that a descriptor is not a substitute for the code: it contains public information, and without the seed it can only watch.")), None),

 ("StandardPath44", "BIP44 path for legacy scripts", 3, "PathConventions", ("m/44h/0h/0h",
   "BIP44's account path for pay-to-public-key-hash scripts is the first of the standard implicit paths and the one the chapter's table gives for legacy addresses.",
   ("'m/%dh/0h/0h' % 44", "'m/44h/0h/0h'")), P(
  (W, "The BIP44 path is the oldest of the standard implicit paths. The chapter's table of implicit script paths gives it in one row: the standard BIP44, the script P2PKH, the BIP32 path m/44'/0'/0' [AH]. The text explains the row before the table, saying that BIP44 defines m/44'/0'/0' as the path to use for keys in pay-to-public-key-hash scripts, which it glosses as a legacy address [AH]. The worked example writes the path from its purpose number."),
  (Y, "The path matters because it is what a wallet tries first when a code is restored, and because it defines what legacy means in this context. Pay-to-public-key-hash is the address type chapter 4 of the book described as the legacy form, beginning with the digit 1, and a wallet that supports only BIP44 will find only those addresses. Since many wallets created before segregated witness used this path, it remains the path on which old funds are found."),
  (E, "A reader meets the path in the chapter's table, in BIP44's own examples, where the first receiving address of the first Bitcoin account is m/44'/0'/0'/0/0, and in real software: the fresh Bitcoin Core wallet of this chapter's evidence has a descriptor pair under the origin 6d8c4b8f followed by 44h/0h/0h, written with the function pkh, which is the descriptor name for this script type [B44] [B31] [B380]. Bitcoin Core's documentation records BIP44 as used by default in descriptor wallets since version 0.21.0 [BC]."),
  (H, "The path is BIP44's five-level structure with the purpose set to 44 and the coin type to 0 for Bitcoin, which the previous branch explained; the levels below the account are the change branch and the address index [B44]. The script type is not part of the path arithmetic: the same keys could be used to make any kind of address, and it is the standard alone that says this path's keys belong in pay-to-public-key-hash scripts, which is exactly the layer violation BIP380 complains about and descriptors remove [B380]."),
  (K, "Two points of care. The first is that the chapter's table prints m/44'/0'/0' for BIP44 but m/49'/1'/0' for BIP49, whose second level is 1, the coin type for testnet, because BIP49's own test vectors are on testnet; the table is faithful to the standards but a reader should not read the 1 as part of the scheme [AH] [B49] [S44]. The second is that a wallet supporting only this path will not find segwit or taproot funds, which is the whole reason the other three rows of the table exist.")), None),

 ("StandardPath49", "BIP49 path for nested segwit", 3, "PathConventions", ("49 hardened is 0x80000031",
   "BIP49 gives segregated witness keys wrapped in a script hash their own account path, so that an incompatible wallet finds nothing rather than finding part of the funds.",
   ("hex(2 ** 31 + 49)", "'0x80000031'")), P(
  (W, "The BIP49 path is the standard path for pay-to-witness-public-key-hash nested in pay-to-script-hash, which the chapter's table calls nested P2WPKH and gives as m/49'/1'/0' [AH]. The standard's own title is a derivation scheme for P2WPKH-nested-in-P2SH based accounts, and it says it uses the same account structure as BIP44 but a different purpose value to indicate the different transaction serialisation method [B49]. The worked example gives the hardened purpose index, 2 to the 31 plus 49, as 0x80000031."),
  (Y, "The reasoning behind a separate path is the clearest statement in these standards of why implicit paths need discipline. BIP49 lists the alternatives it rejected, in which the same account would carry both legacy and segwit addresses, and gives its reason: those approaches share a common disadvantage, that if a user imports or recovers a BIP49-compatible master seed in a wallet that is not BIP49-compatible, the account might show up but might also miss some unspent outputs; the chosen approach fails in a more visible way, since either the account shows up or it does not at all, so the user does not have to check the balance after using the same seed in different wallets [B49]."),
  (E, "A reader meets this path as the wrapped segwit addresses that begin with the digit 3, and in the descriptors of the Bitcoin Core wallet in this chapter's evidence, where the pair under the origin 6d8c4b8f followed by 49h/0h/0h is written with the nested functions sh and wpkh [B31] [B380]. The claims of this chapter reproduce BIP49's own test vector from its recovery code: the first receiving key of the testnet account at m/49'/1'/0'/0/0 has the public key the standard prints, and the address derived from it is the 2Mww8d address of the standard [B49]."),
  (H, "The mechanism of the address is the encapsulation the standard sets out: the witness holds the signature and the public key, the input script holds a push of the version-zero witness program, and the output script is a hash-160 of that program followed by an equality check [B49]. The path is the BIP44 structure with purpose 49, and the standard also defines alternative version bytes for extended keys, giving the prefixes ypub and yprv, with testnet upub and uprv [B49]. The claims of this chapter compute the address from the public key by hashing the input script, which is why the example reproduces the standard exactly."),
  (K, "The chapter's table row for this standard uses coin type 1, which is testnet, and the standard's vectors are on testnet as well, so a reader working on mainnet should use m/49'/0'/0' [AH] [B49] [S44]. The deeper caution is the one the standard itself gives: this scheme is not backward compatible by design, so a wallet that does not know it will simply not see the account; that is intended, and it is better than silently showing part of a balance [B49].")), None),

 ("StandardPath84", "BIP84 path for native segwit", 3, "PathConventions", ("the first address of the standard's test vector",
   "BIP84 gives native segregated witness keys their own account path, and its test vector's first address is the bech32 address the course can recompute from the key hash.",
   (PROG(BECH32), "'bc1qcr8te4kr609gcawutmrza0j4xv80jy8z306fyu'")), P(
  (W, "The BIP84 path is the standard path for native pay-to-witness-public-key-hash keys. The chapter's table gives it as m/84'/0'/0' for the script P2WPKH [AH]. The standard says the same as BIP49 with a different number: it uses the account structure of BIP44 and BIP49 with the purpose level set to 84, and the address is derived by the native encapsulation of segregated witness, where the input script is empty and the output script is a zero followed by the twenty-byte key hash [B84]."),
  (Y, "This is the path most wallets use today, so a reader restoring a modern wallet is most likely to need it. The addresses it produces are the bech32 addresses beginning bc1q that chapter 4 of the book explained, and they are cheaper to spend than the nested form, which is why the nested scheme was transitional. For this course it is also the path the evidence of a real node shows in use: the wallet created by Bitcoin Core 31.1 reported its first address at m/84h/0h/0h/0/0 [B31]."),
  (E, "The worked example reproduces the standard's own first test vector in full. From the recovery code of twelve repetitions of the word abandon ending in about, the standard derives the account m/84'/0'/0' and gives its first receiving public key and the address bc1qcr8te4kr609gcawutmrza0j4xv80jy8z306fyu [B84]. The example takes the hash of that public key as data, because the course's browser pages have no RIPEMD-160, and performs the whole bech32 encoding, checksum included, to arrive at the same address. The claims of this chapter derive the key itself from the code with this chapter's library, and Bitcoin Core 31.1 produced the same address from a descriptor built on the same account key [B31]."),
  (H, "The derivation is the familiar one: the recovery code gives a seed through PBKDF2, the seed gives the master key through HMAC-SHA512, three hardened steps give the account, and two normal steps give the address key. The encoding of the address is bech32, which takes the witness version and the twenty-byte key hash, converts them to groups of five bits, appends a six-character checksum computed over the human-readable part and the data, and writes the result in the thirty-two-character alphabet [B84]. The example's output is checked against the string the standard prints and against the address the real node derived."),
  (K, "Two cautions. The standard defines its own extended key prefixes, zpub and zprv, and the chapter's example descriptor from the Core evidence uses an ordinary xpub with an explicit path instead, which is BIP43's and BIP380's preference; a reader who meets a zpub should recognise it as the same key with different version bytes [B84] [B43] [B380]. And the test vector's recovery code is the well-known abandon sequence, which is valid and public: it must never be used for funds, which is exactly why a standard can print it.")), None),

 ("StandardPath86", "BIP86 path for single-key taproot", 3, "PathConventions", ("the tweak of the test vector's internal key",
   "BIP86 gives single-key taproot outputs their own account path and says how the output key is computed from the derived key by a tagged hash.",
   ("(lambda h: h.sha256(h.sha256(b'TapTweak').digest() + h.sha256(b'TapTweak').digest() + bytes.fromhex('%s')).hexdigest()[:16])(__import__('hashlib'))" % IKEY86,
    "'2ca01ed85cf6b652'")), P(
  (W, "The BIP86 path is the standard path for taproot outputs with a single key. The chapter's table gives it as m/86'/0'/0' for the script P2TR single-key [AH]. The standard describes itself as suggesting a derivation scheme for wallets whose keys are involved in single-key pay-to-taproot outputs as the taproot internal key, and says it largely uses the same approach as BIPs 49 and 84 for ease of implementation [B86]."),
  (Y, "The standard exists because seed backups are still poorer than descriptors. Its motivation says that with single-key taproot transactions it is useful to have a common derivation scheme so that wallets which have only a backup of the seed can be likely to recover such outputs, and adds, candidly, that although there are now solutions which obviate the need for fixed derivation paths for specific script types, many software wallets and hardware signers still use seed backups that lack derivation path and script information [B86]. That sentence is the whole argument of this branch in miniature."),
  (E, "A reader meets this path as the taproot addresses beginning bc1p and in the fourth descriptor pair of the Bitcoin Core wallet in this chapter's evidence, written with the function tr under the origin 6d8c4b8f followed by 86h/0h/0h [B31] [B380]. The worked example computes the first step of the standard's own address derivation: the tagged hash of the test vector's internal key cc8a4bc6..., which begins 2ca01ed85cf6b652. The claims of this chapter carry the derivation through to the output key a60869f0... and the address bc1p5cyxnuxmeuwuvkwfem96lqzszd02n6xdcjrs20cac6yqjjwudpxqkedrcr that the standard prints [B86]."),
  (H, "The mechanism adds one step to the pattern of the other standards. The derived key becomes the internal key, and the standard quotes the taproot specification's rule that if the spending conditions do not require a script path, the output key should commit to an unspendable script path instead of having none, which is achieved by computing the output key as the internal key plus the tagged hash of the internal key times the generator point [B86]. The tag is the string TapTweak, and a tagged hash is the hash of the tag's hash twice followed by the message, which is what the worked example computes; the output script is then a one followed by the thirty-two-byte output key [B86]."),
  (K, "The address cannot be recomputed in the course's browser pages beyond this step, because the addition of a point to the curve needs the elliptic curve arithmetic of chapter 4 and the address uses the bech32m checksum rather than bech32; both are checked in the claims of this chapter instead [B86]. The standard also warns, as the others do, that it is not backward compatible by design, so an incompatible wallet will not discover these accounts at all [B86].")), None),

 ("Multisignature", "Multisignature", 3, "PathConventions", ("two of three signatures",
   "A multisignature arrangement requires several of a set of keys to sign; its participants cannot restore the arrangement from their own seeds alone, because they also need the others' public keys.",
   ("__import__('math').comb(3, 2)", "3")), P(
  (W, "Multisignature means that spending needs signatures from more than one key. The book's glossary defines it as requiring more than one key to authorise a Bitcoin transaction, and chapter 7 states the general form: multisignature scripts set a condition in which a number of public keys are recorded in the script and at least a threshold of those must provide signatures to spend the funds, so that a two-of-three arrangement lists three potential signers of whom at least two must sign [AHG] [AH7]. The worked example counts the ways that condition can be met: three pairs out of three keys."),
  (Y, "In this chapter multisignature is the argument that implicit paths cannot be enough. The chapter gives the case in full: Alice, Bob and Carol receive funds that can only be spent with signatures from two out of three of them, and although Alice needs only Bob's or Carol's signature to spend, she needs both of their public keys in order to find their joint funds on the blockchain, which means each of them must back up the public keys for all three; and it adds that as multisignature and other advanced scripts become more common, the inflexibility of implicit paths becomes more significant [AH]."),
  (E, "A reader meets multisignature in three places in this chapter. It is the reason the Muun wallet's recovery code is accompanied by a document, since that wallet defaults to requiring that spending transactions be signed by multiple keys [AH]. It is the case in which a wallet database holds only some of the private keys that a spending transaction needs, which the first branch described as external signing [AH]. And it is one of the script types a descriptor can express, which the chapter's sample table shows as a script-hash multisignature requiring two signatures corresponding to two given keys [AH] [BCD]."),
  (H, "The mechanism that matters here is not the script but the information each participant must keep. The seed of one participant derives that participant's keys and nothing else, so the arrangement itself, which keys, how many signatures, in what order, is non-deterministic information that no recovery code can reproduce. Descriptors record exactly that: BIP383 defines the multi and sortedmulti expressions, and Bitcoin Core's documentation shows them with several extended public keys and their paths, so that one descriptor describes the whole arrangement [B380] [BCD]."),
  (K, "Two distinctions keep the subject clear. The threshold and the number of keys are different numbers, and chapter 7 notes that earlier editions of the book used m-of-n for what it now writes as t-of-k, so a reader comparing texts should check which letter means which [AH7]. And a multisignature wallet is not more recoverable for having several keys: it is less recoverable, because every participant needs the public keys of all the others, which is why this is the case that pushed wallets towards descriptors.")), None),

 ("Descriptors", "Output script descriptors", 2, "PathBackup", None, P(
  (W, "This group covers the notation in which explicit paths are written. The chapter introduces it in one sentence: almost all wallet applications that use explicit paths use the output script descriptors standard, called descriptors for short, as specified in BIPs 380, 381, 382, 383, 384, 385, 386 and 389, and descriptors describe a script and the keys, or key paths, to be used with it [AH]. BIP380 is the general specification, and the others define the individual script expressions [B380]."),
  (Y, "The group matters because descriptors are now how wallets talk about keys. Bitcoin Core's wallets are descriptor wallets, so every example in this course that comes from a real node is a descriptor; the chapter's own sample table is taken from Bitcoin Core's documentation; and the standard's motivation is exactly the problem this branch is about, that a backup of keys alone cannot say which output scripts and addresses to produce [AH] [B380] [B31]."),
  (H, "The sections build the notation from the inside out. The output script is what a descriptor describes. The descriptor itself is the function-and-argument syntax that names a script type and its keys. The checksum is the eight characters that protect a descriptor from typing errors. The key origin is the bracketed fingerprint and path that records where an extended key came from. The multipath form writes the receive and change descriptors as one. And miniscript is the language for the spending conditions themselves, which descriptors can contain.")), None),

 ("OutputScript", "Output script", 3, "Descriptors", ("twenty-two bytes for a native segwit output",
   "An output script is the program in a transaction output that says what must be presented to spend it; a descriptor is a description of a family of such scripts.",
   ("len(bytes.fromhex('0014' + '%s'))" % H160_84, "22")), P(
  (W, "An output script is the piece of a transaction output that states the condition for spending it. Chapter 4 of the book introduced output and input scripts for the address types this course has met, and this chapter meets them again as the thing a descriptor describes: BIP380's title is output script descriptors, and it says that descriptors are a simple language that can be used to describe collections of output scripts [B380]. The worked example measures one: a native segwit output script is a zero byte, a push of twenty bytes and the twenty-byte key hash, twenty-two bytes in all [B84]."),
  (Y, "The script is the thing that actually decides whether a payment can be spent, which is why a backup that does not record the script type is incomplete. BIP380 makes the argument: wallets have traditionally stored keys which are later serialised and mutated to produce the output scripts the wallet watches and the addresses it provides, but given just the private keys it is not possible for a restored wallet to know which kinds of output script and address to produce, which has led to incompatibilities between wallets when restoring a backup or exporting data for a watch-only wallet [B380]."),
  (E, "A reader meets output scripts in the standards of this branch, each of which prints the script its path's keys belong in: BIP49 gives an input script that pushes a witness program and an output script that hashes it; BIP84 gives an empty input script and an output script of a zero and a key hash; BIP86 gives an output script of a one and a thirty-two-byte output key [B49] [B84] [B86]. The same three forms appear in the descriptor functions sh, wpkh and tr that Bitcoin Core used in the wallet of this chapter's evidence [B31] [B380]."),
  (H, "For this chapter the mechanism worth noting is the relation between a key and a script. One key can appear in several kinds of script, and each kind gives a different address, which is why the standards of this branch assign a different path to each: the key itself does not say which script it belongs in. Bitcoin Core's descriptor documentation lists the functions for each script type, among them pk, pkh, wpkh, sh and tr, with the rules about where each may appear [BCD]."),
  (K, "The word script is used for several things in Bitcoin and a reader should keep them apart: the output script in the output being spent, the input script in the spending input, and the witness, which segregated witness moved out of the input script. This chapter needs only the first, and only as the object a descriptor describes; the details belong to the later chapters of the book on transactions and on authorisation.")), None),

 ("OutputScriptDescriptor", "Output script descriptor", 3, "Descriptors", ("a descriptor split into function and argument",
   "A descriptor is a short expression naming a script type as a function and its keys as arguments, so that it says exactly which scripts and addresses a wallet should produce.",
   (PROG("d = %r\n"
         "result = (d[:d.index('(')], d[d.index('['):d.index(']') + 1], d[-5:])" % DESC84),
    "('wpkh', '[6d8c4b8f/84h/0h/0h]', '/0/*)')")), P(
  (W, "A descriptor is an expression that describes a set of output scripts. The chapter says descriptors describe a script and the keys, or key paths, to be used with it, and prints three examples from Bitcoin Core's documentation: a script-hash multisignature requiring two signatures for two given keys, a pay-to-public-key-hash script for a given public key, and a ranged descriptor whose extended public key is reached by a path from a master with a given fingerprint [AH]. BIP380 gives the grammar: script types are specified explicitly through script expressions, and key derivation paths explicitly in key expressions [B380]."),
  (Y, "The notation solves the problem this branch opened with, and it does so in one line of text. A descriptor records the script type, the keys, the origin of each key and the paths below it, so a wallet given a descriptor needs to guess nothing and a wallet given only a seed must guess everything. That is why Bitcoin Core's modern wallets are built on descriptors and why the chapter says applications that support advanced scripts increasingly adopt them [AH] [B31]."),
  (E, "The worked example takes one real descriptor apart: the one Bitcoin Core 31.1 produced for the native segwit receive branch of the wallet created for this chapter. Its function is wpkh; its key origin is the fingerprint 6d8c4b8f with the path 84h/0h/0h; and it ends with the branch and wildcard /0/*, which stands for every index of the receive branch [B31] [B380]. The chapter's own table and Bitcoin Core's documentation give many more forms, from a single public key to a taproot output with script paths [AH] [BCD]."),
  (H, "The syntax is a function applied to arguments, which may themselves be functions. BIP380 says a key expression consists of optional key origin information in brackets, then the key itself, which may be a hexadecimal public key, a key in wallet import format, or an extended public or private key, followed by zero or more path elements and optionally a final wildcard [B380]. Script expressions wrap key expressions: Bitcoin Core's documentation lists which may appear at the top level and which only inside others, so that for example wpkh is allowed at the top level or inside sh [BCD]."),
  (K, "Two things a descriptor is not. It is not a secret by default: a descriptor with an extended public key lets its holder compute every address of the branch, which is useful for a watching wallet and a privacy loss if it leaks [B32]. And it is not a wallet state: the range of indices a wallet has prepared is separate, which is why the descriptors in this chapter's evidence carry a range from 0 to 999 and a next index alongside the descriptor itself [B31].")), None),

 ("DescriptorChecksum", "Descriptor checksum", 3, "Descriptors", ("eight characters after a hash sign",
   "A descriptor carries an eight-character error-detecting checksum after a hash sign, which catches any one or two symbol errors in a descriptor of ordinary length.",
   ("len('raw(deadbeef)#89f8spxm'.split('#')[1])", "8")), P(
  (W, "The descriptor checksum is the eight characters that follow a hash sign at the end of a descriptor. BIP380 describes it exactly: following the top-level script expression is a single octothorpe followed by the eight-character checksum, which is an error-correcting checksum similar to bech32 and uses the same character set, the thirty-two characters of the bech32 alphabet [B380]. The worked example counts them in the standard's own smallest example, raw(deadbeef) with the checksum 89f8spxm."),
  (Y, "A descriptor is a long string that a user may have to type, and a single wrong character would point a wallet at the wrong keys. The checksum turns that silent failure into a refusal. BIP380 states its guarantees in terms of symbol errors: any one symbol error is always detected; any two or three symbol errors in a descriptor of up to 49,154 characters are always detected; any four in up to 507 characters and any five in up to 77 characters; and random errors have a chance of one in 2 to the 40 of going undetected [B380]."),
  (E, "A reader meets the checksum on every descriptor a wallet prints: all eight descriptors of the Bitcoin Core wallet in this chapter's evidence end in one, and the node's own command for inspecting a descriptor returns the checksum as a separate field, which the evidence of this chapter records for four descriptors including the three the chapter prints in its sample table [B31] [AH]. The claims of this chapter recompute all four checksums from the standard's algorithm and obtain the values the real node returned."),
  (H, "The mechanism is a linear code over the alphabet, computed in two stages. The characters of the descriptor are mapped into an input alphabet and grouped so that each group of three characters contributes an extra symbol, then a polynomial remainder is computed with five generator constants and the result is written as eight characters of the bech32 alphabet; checking recomputes the same remainder and compares it with a constant [B380]. BIP380 notes which substitutions count as one symbol error, including any character of the set used by hexadecimal keys and any case error, and observes that extended keys have their own checksum as well [B380]."),
  (K, "The checksum protects the descriptor, not the keys: a descriptor with a valid checksum may still name the wrong account, and a descriptor whose extended key is wrong will usually fail the key's own base58check instead. A reader should also note that the checksum is part of the string a wallet expects: Bitcoin Core accepts a descriptor without one in some commands and will compute it, but the canonical form includes it, which is why the evidence files of this chapter show the node returning descriptors with the checksum appended [B31].")), None),

 ("KeyOrigin", "Key origin", 3, "Descriptors", ("a fingerprint and three hardened steps",
   "The key origin of a descriptor records, in brackets, the fingerprint of the master key and the path from it to the key that follows, so that a signing device can find the right key.",
   (PROG(ORIGIN), "('6d8c4b8f', [84, 0, 0])")), P(
  (W, "The key origin is the bracketed part at the start of a key expression. BIP380 specifies it: optionally, key origin information, consisting of an open bracket, exactly eight hexadecimal characters for the fingerprint of the key where the derivation starts, then zero or more path elements written as a number with or without an h to indicate hardened steps, then a closing bracket [B380]. The chapter's third sample descriptor shows one: it specifies that the extended public key is a child of a master with fingerprint d34db33f derived using the path 44'/0'/0' [AH]."),
  (Y, "The origin is what lets a public descriptor be matched with a private key held elsewhere. A hardware signing device given a descriptor can compare the fingerprint with its own master key and then derive exactly the key the descriptor names; without the origin it would have to guess the path. BIP380's motivation lists this among the problems it solves, noting that the lack of derivation path information in backups and exports leads to incompatibilities between wallets [B380]."),
  (E, "The worked example reads the origin out of a real descriptor: the native segwit receive descriptor of the wallet Bitcoin Core 31.1 created for this chapter begins with the fingerprint 6d8c4b8f and the path 84h/0h/0h, and the program recovers both [B31]. The same structure appears in the chapter's sample table, in the BIP84 account descriptor built for this chapter's evidence, and in BIP329's label format, where the optional origin property must contain an abbreviated descriptor with all key origin information but no keys, paths or checksum [AH] [B31] [B329]."),
  (H, "Mechanically the origin is metadata: it takes no part in deriving anything below the key, and the path it records is the path above the key, which has already been applied. That is why the path in the brackets is usually the hardened part, down to the account, and the path after the key is the normal part, the branch and the index. Because the fingerprint is only four bytes, BIP32 warns that software must be willing to deal with collisions, so the origin is a hint for selecting a device, not a proof of identity [B32]."),
  (K, "Two details to keep straight. The origin is written with h or with an apostrophe for hardened steps, and the chapter recommends h in contexts such as descriptors where an apostrophe has a special meaning in a shell, which is what Bitcoin Core writes in the evidence of this chapter [AH] [B31]. And the fingerprint belongs to the master key, not to the key that follows: it is the fingerprint of the key where the derivation starts, so two descriptors from the same seed share it [B380].")), None),

 ("MultipathDescriptor", "Multipath descriptor", 3, "Descriptors", ("one descriptor expanded into two",
   "A multipath descriptor writes a tuple of derivation steps in angle brackets, so that one descriptor stands for the receive and the change descriptor of a wallet.",
   (PROG(MULTIPATH), "['wpkh([6d8c4b8f/84h/0h/0h]xpub.../0/*)', 'wpkh([6d8c4b8f/84h/0h/0h]xpub.../1/*)']")), P(
  (W, "A multipath descriptor is a descriptor in which one derivation step is a tuple of values. BIP389 specifies the modification: a key expression may contain one path element of the form of several numbers separated by semicolons inside angle brackets, indicating a tuple of derivation steps to be taken after the extended key [B389]. The worked example expands such a descriptor by hand: the element containing 0 and 1 becomes two descriptors, one for each value, in the order written."),
  (Y, "The form exists because wallets almost always need two descriptors that differ in one digit. BIP389's motivation says that wallets typically have one descriptor for producing receiving addresses and another for change addresses, that these are extremely similar, producing the same types of script and deriving from the same master key with almost identical paths, and that it is therefore useful to have a notation representing both as a single descriptor where one of the derivation steps is a pair of values [B389]."),
  (E, "A reader meets the need for this form directly in the evidence of this chapter: the Bitcoin Core wallet created for it has eight descriptors that are four pairs, each pair sharing an account key and differing only in the branch, 0 or 1, with one of each pair marked internal [B31]. Bitcoin Core's own descriptor documentation shows the multipath notation in use, in a two-of-three multisignature whose keys each carry the element for the receive and change paths [BCD]. The standard's status in the BIPs repository is Draft [B389]."),
  (H, "The expansion is purely textual and the standard fixes its order: the descriptor is equivalent to the list of descriptors obtained by replacing the tuple with each of its values in turn, so the first descriptor of the list is the receive branch and the second the change branch when the tuple is written 0 and 1. Because the expansion happens before any derivation, nothing else about the descriptor changes, and the checksum is computed over the multipath form itself."),
  (K, "The notation is a convenience and not a new capability: a wallet that does not support it can be given the two descriptors separately, which is what Bitcoin Core's own listing shows. A reader should also notice that the tuple is a path element, not a wildcard: the wildcard star at the end still stands for the whole range of address indices, so a multipath descriptor with a wildcard describes two infinite families of scripts rather than two scripts [B380] [B389].")), None),

 ("Miniscript", "Miniscript", 3, "Descriptors", ("a policy that decays from four of four to one of four",
   "Miniscript is a structured language for a subset of Bitcoin scripts, so that spending conditions can be analysed, composed and signed for; descriptors can contain it.",
   ("[4 - i for i in range(4)]", "[4, 3, 2, 1]")), P(
  (W, "Miniscript is a language for writing a subset of Bitcoin scripts in a structured way. Its specification describes it as enabling analysis, composition, generic signing and more [B379]. The chapter mentions it once, among the newer technologies that the Muun wallet's unusual recovery arrangement supports, beside the Lightning Network and output script descriptors [AH]; it belongs in this group because a descriptor can contain a miniscript expression, which is how an arbitrary spending condition is written down in a backup."),
  (Y, "The reason such a language exists is that raw Bitcoin script is hard to reason about. The specification lists what is highly non-trivial even though the language is limited: finding the most economical script for a combination of spending conditions, composing two scripts into one, finding out what conditions a script permits, and constructing a satisfying witness given enough private keys [B379]. For backups the consequence is direct: a condition that cannot be analysed cannot be safely recorded or restored."),
  (E, "A reader meets miniscript in Bitcoin Core's descriptor documentation, which shows a policy of four keys and three time locks that the documentation describes as starting as four-of-four and decaying to three-of-four, two-of-four and finally one-of-four at each future halving height, written as a threshold expression inside a witness-script descriptor with multipath keys [BCD]. The worked example is that sequence of thresholds. The specification's status in the BIPs repository is Draft [B379]."),
  (H, "The mechanism that matters here is that miniscript is a notation for the same scripts, with enough structure that a tool can compute properties of them. Because a descriptor can carry such an expression, one line of text can record a condition involving several parties and several times, together with the key origins needed to find each participant's keys; that is the extreme case of the explicit path, and it is the case the chapter says is driving wallets towards descriptors [AH] [B379]."),
  (K, "Miniscript is beyond what this chapter needs, and a learner should take only two points from it. The first is that the explicit approach scales to conditions that no implicit path could express. The second is that it is a draft, like several standards in this chapter, so a course should present it as a direction of travel and not as a settled part of the stack; the chapter's own treatment, one mention in a list, is the right weight for a first course [AH] [B379].")), None),
]

CHECKS_F = [
 Qb("ch05_wallets.adoc", "there are approximately four billion first-level\nkeys", "it also requires knowing what paths in the tree of keys\nyour wallet application used for generating the specific keys it distributed",
    "Two solutions to this problem have been adopted.  The first is using\nstandard paths", "We call", "this solution _implicit\npaths_",
    "The second solution is to back up the path information with the recovery\ncode, making it clear which path is used with which scripts",
    "The advantage of implicit paths is that users don't need to keep a record\nof what paths they use",
    "The disadvantage of implicit scripts is their inflexibility",
    "This is wasteful in wallets that support many\nfeatures each with their own path if the user only tried a few of those\nfeatures",
    "a new version of a wallet application that drops support\nfor an older path can't warn users during the restore process that some\nof their funds may not be found",
    "Recovery codes\nthat include version information, such as Electrum v2 and Aezeed, can\ndetect that a user is entering an older or newer recovery code",
    "they can only include\ninformation that is either universal (such as a standardized path) or\nderived from the seed (such as keys)",
    "The advantage of explicit paths is that they can describe exactly what\nkeys should be used with what scripts",
    "they require users to back\nup additional information along with their recovery code",
    "it can\nreduce their privacy and does require some protection"),
 Qb("ch05_wallets.adoc", "Almost all wallet applications that use explicit paths as of this\nwriting use the _output script descriptors_ standard (called\n_descriptors_ for short) as specified in BIPs 380, 381, 382, 383, 384,\n385, 386, and 389",
    "Descriptors\ndescribe a script and the keys (or key paths) to be used with it",
    "It has long been the trend for wallet applications designed only for\nsingle signature scripts to use implicit paths",
    "Wallet applications\ndesigned for multiple signatures or other advanced scripts are\nincreasingly adopting support for explicit paths using descriptors"),
 # the chapter's table of implicit paths
 Qb("ch05_wallets.adoc", "<td><p>BIP44</p></td>", "<td><p>P2PKH</p></td>", "<td><p><code>m/44'/0'/0'</code></p></td>",
    "<td><p>BIP49</p></td>", "<td><p>Nested P2WPKH</p></td>", "<td><p><code>m/49'/1'/0'</code></p></td>",
    "<td><p>BIP84</p></td>", "<td><p>P2WPKH</p></td>", "<td><p><code>m/84'/0'/0'</code></p></td>",
    "<td><p>BIP86</p></td>", "<td><p>P2TR Single-key</p></td>", "<td><p><code>m/86'/0'/0'</code></p></td>"),
 ("'m/%dh/0h/0h' % 44", "'m/44h/0h/0h'"), ("[hex(2 ** 31 + n) for n in (44, 49, 84, 86)]", "['0x8000002c', '0x80000031', '0x80000054', '0x80000056']"),
 # BIP49, BIP84, BIP86 test vectors
 Qe("bip-0049.mediawiki", "This BIP defines the derivation scheme for HD wallets using the P2WPKH-nested-in-P2SH ([[bip-0141.mediawiki|BIP 141]]) serialization format",
    "if a user imports/recovers a BIP49-compatible wallet masterseed into/in a non-BIP49-compatible wallet, the account might show up but also it might miss some UTXOs",
    "Therefore this BIP uses solution 2, which fails in a more visible way. Either the account shows up or not at all",
    "For the `purpose`-path level it uses `49'`", "scriptSig: <0 <20-byte-key-hash>>", "scriptPubKey: HASH160 <20-byte-script-hash> EQUAL",
    "account0recvPublicKeyHex = 0x03a1af804ac108a8a51782198c2d034b28bf90c8803f5a53f76276fa69a4eae77f",
    "address = base58check(prefix | addressBytes) = 2Mww8dCYPUpKHofjgcXcBCEGmniw9CoaiD2 (testnet)",
    "This BIP is not backwards compatible by design"),
 X("(lambda k, c: W.ser_p(W.ec_mul(W.derive_priv(k, c, 'm/0/0')[0])).hex())(*W.derive_priv(*W.master(W.mnemonic_to_seed('abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about')), \"m/49'/1'/0'\"))",
   "'03a1af804ac108a8a51782198c2d034b28bf90c8803f5a53f76276fa69a4eae77f'"),
 X("W.b58check(b'\\xc4' + W.hash160(b'\\x00\\x14' + W.hash160(bytes.fromhex('03a1af804ac108a8a51782198c2d034b28bf90c8803f5a53f76276fa69a4eae77f'))))", "'2Mww8dCYPUpKHofjgcXcBCEGmniw9CoaiD2'"),
 Qe("bip-0084.mediawiki", "For the <code>purpose</code>-path level it uses <code>84'</code>", "scriptPubKey: 0 <20-byte-key-hash>",
    "mnemonic = abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",
    "pubkey  = 0330d54fd0dd420a6e5f8d3624f5f3482cae350f79d5f0753bf5beef9c2d91af3c",
    "address = bc1qcr8te4kr609gcawutmrza0j4xv80jy8z306fyu",
    "address = bc1qnjg0jd8228aq7egyzacy8cys3knf9xvrerkf9g"),
 X("(lambda K, c: W.ser_p(W.pub_at(K, c, '0/0')[0]).hex())(*(lambda k, c: (W.ec_mul(k), c))(*W.derive_priv(*W.master(W.mnemonic_to_seed('abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about')), \"m/84'/0'/0'\")))",
   "'0330d54fd0dd420a6e5f8d3624f5f3482cae350f79d5f0753bf5beef9c2d91af3c'"),
 X("W.hash160(bytes.fromhex('0330d54fd0dd420a6e5f8d3624f5f3482cae350f79d5f0753bf5beef9c2d91af3c')).hex()", "'%s'" % H160_84),
 X("W.p2wpkh_address(bytes.fromhex('0330d54fd0dd420a6e5f8d3624f5f3482cae350f79d5f0753bf5beef9c2d91af3c'))", "'bc1qcr8te4kr609gcawutmrza0j4xv80jy8z306fyu'"),
 (PROG(BECH32), "'bc1qcr8te4kr609gcawutmrza0j4xv80jy8z306fyu'"),
 Qe("core_deriveaddresses_bip84_31_1_v1_0_0.json", '"bc1qcr8te4kr609gcawutmrza0j4xv80jy8z306fyu"', '"bc1qnjg0jd8228aq7egyzacy8cys3knf9xvrerkf9g"', '"bc1qp59yckz4ae5c4efgw2s5wfyvrz0ala7rgvuz8z"'),
 Qe("bip-0086.mediawiki", "This document suggests a derivation scheme for HD wallets whose keys are involved in single key P2TR ([[bip-0341.mediawiki|BIP 341]]) outputs as the Taproot internal key",
    "it is useful to have a common derivation scheme so that HD wallets that only have a backup of the HD seed can be likely to recover single key Taproot outputs",
    "many software wallets and hardware signers still use seed backups which lack derivation path and script information",
    "For the <tt>purpose</tt>-path level it uses <tt>86'</tt>",
    "If the spending conditions do not require a script path, the output key should commit to an unspendable script path instead of having no script path",
    "internal_key: lift_x(derived_key)", "32_byte_output_key: internal_key + int(HashTapTweak(bytes(internal_key)))G",
    "internal_key = cc8a4bc64d897bddc5fbc2f670f7a8ba0b386779106cf1223c6fc5d7cd6fc115",
    "output_key   = a60869f0dbcf1dc659c9cecbaf8050135ea9e8cdc487053f1dc6880949dc684c",
    "address      = bc1p5cyxnuxmeuwuvkwfem96lqzszd02n6xdcjrs20cac6yqjjwudpxqkedrcr"),
 ("(lambda h: h.sha256(h.sha256(b'TapTweak').digest() + h.sha256(b'TapTweak').digest() + bytes.fromhex('%s')).hexdigest()[:16])(__import__('hashlib'))" % IKEY86, "'2ca01ed85cf6b652'"),
 X("W.tagged_hash('TapTweak', bytes.fromhex('%s')).hex()" % IKEY86, "'2ca01ed85cf6b6526f73d39a1111cd80333bfdc00ce98992859848a90a6f0258'"),
 X("W.taproot_output_key(bytes.fromhex('02%s')).hex()" % IKEY86, "'a60869f0dbcf1dc659c9cecbaf8050135ea9e8cdc487053f1dc6880949dc684c'"),
 X("W.p2tr_address(W.taproot_output_key(bytes.fromhex('02%s')))" % IKEY86, "'bc1p5cyxnuxmeuwuvkwfem96lqzszd02n6xdcjrs20cac6yqjjwudpxqkedrcr'"),
 X("W.ser_p(W.ec_mul(W.keys_at('abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about', \"m/86'/0'/0'/0/0\")[0]))[1:].hex()", "'%s'" % IKEY86),
 # multisignature
 Qb("ch05_wallets.adoc", "Alice, Bob, and Carol receive funds that\ncan only be spent with signatures from two out of three of them",
    "she needs\nboth of their public keys in order to find their joint funds on the\nblockchain", "each of them must back up the public keys for\nall three of them",
    "As multisignature and other advanced scripts become\nmore common on Bitcoin, the inflexibility of implicit paths becomes more\nsignificant"),
 Qb("glossary.asciidoc", "Multisignature (multisig) refers to requiring more than one key to authorize a bitcoin transaction"),
 Qb("ch07_authorization-authentication.adoc", "set a condition where _k_ public keys\nare recorded in the script and at least _t_ of those must provide\nsignatures to spend the funds, called _t_-of-_k_",
    "For example, a 2-of-3 multisignature is one\nwhere three public keys are listed as potential signers and at least two\nof those must be used to create signatures for a valid transaction to\nspend the funds",
    "uses the term \"m-of-n\" for a traditional multisignature"),
 ("__import__('math').comb(3, 2)", "3"), ("__import__('math').comb(2, 2)", "1"),
 # descriptors
 Qb("ch05_wallets.adoc", "<td><p><code>pkh(02c6", "<td><p>P2PKH script for the provided public key</p></td>",
    "<td><p>P2SH multisignature requiring two signatures corresponding to these two keys</p></td>",
    "with the extended public key (xpub) at the path <code>M/44'/0'/0'</code>"),
 Qe("bip-0380.mediawiki", "Output Script Descriptors are a simple language which can be used to describe collections of output scripts",
    "Bitcoin wallets traditionally have stored a set of keys which are later serialized and mutated to produce the output scripts that the wallet watches and the addresses it provides to users",
    "Given just the private keys, it is not possible for restored wallets to know which kinds of output scripts and addresses to produce",
    "The lack of derivation path information in these backups and exports leads to further incompatibilities between wallets",
    "Script types are specified explicitly through the use of Script Expressions", "Key derivation paths are specified explicitly in Key Expressions",
    "These represent a public or private key and, optionally, information about the origin of that key",
    "Followed by zero or more <tt>/NUM</tt> or <tt>/NUMh</tt>  path elements to indicate the unhardened or hardened derivation steps between the fingerprint and the key that follows",
    "66 hex character string beginning with <tt>02</tt> or <tt>03</tt> representing a compressed public key",
    "<tt>xpub</tt> encoded extended public key or <tt>xprv</tt> encoded extended private key (as defined in BIP 32)",
    "Following the top level script expression is a single octothorpe (<tt>#</tt>) followed by the 8 character checksum",
    "The checksum is an error correcting checksum similar to bech32", "Any 1 symbol error is always detected",
    "Any 2 or 3 symbol error in a descriptor of up to 49154 characters is always detected",
    "Any 4 symbol error in a descriptor of up to 507 characters is always detected",
    "Random errors have a chance of 1 in 2<super>40</super> of being undetected",
    "The checksum itself uses the same character set as bech32: <tt>qpzry9x8gf2tvdw0s3jn54khce6mua7l</tt>"),
 Qe("core_doc_descriptors.md", "`pkh(02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5)` describes a P2PKH output with the specified public key",
    "`sh(multi(2,022f01e5e15cca351daff3843fb70f3c2f0a1bdd05e5af888a67784ef3e10a2a01,03acd484e2f0c7f65309ad178a9f559abde09796974c57e714c35f110dfc27ccbe))` describes a P2SH *2-of-2* multisig output with keys in the specified order",
    "additionally specifies that the specified xpub is a child of a master with fingerprint `d34db33f`, and derived using path `44'/0'/0'`",
    "`wpkh(KEY)` (top level or inside `sh` only): P2WPKH output for the given compressed pubkey",
    "`multi(k,KEY_1,KEY_2,...,KEY_n)` (not inside `tr`): k-of-n multisig script using OP_CHECKMULTISIG",
    "that starts as 4-of-4 and \"decays\" to 3-of-4, 2-of-4, and finally 1-of-4 at each future halvening block height",
    "This uses a multipath descriptor specifying both receiving (/0) and change (/1) address derivation paths"),
 ("len(bytes.fromhex('0014' + '%s'))" % H160_84, "22"), ("len('raw(deadbeef)#89f8spxm'.split('#')[1])", "8"), ("len('qpzry9x8gf2tvdw0s3jn54khce6mua7l')", "32"),
 ("[4 - i for i in range(4)]", "[4, 3, 2, 1]"),
 X("W.descsum_create('raw(deadbeef)')", "'raw(deadbeef)#89f8spxm'"),
 X("W.descsum_check('raw(deadbeef)#89f8spxm') and not W.descsum_check('raw(deedbeef)#89f8spxm')", "True"),
 X("W.descsum_create('pkh(02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5)')", "'pkh(02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5)#8fhd9pwu'"),
 X("W.descsum_create('sh(multi(2,022f01e5e15cca351daff3843fb70f3c2f0a1bdd05e5af888a67784ef3e10a2a01,03acd484e2f0c7f65309ad178a9f559abde09796974c57e714c35f110dfc27ccbe))')",
   "'sh(multi(2,022f01e5e15cca351daff3843fb70f3c2f0a1bdd05e5af888a67784ef3e10a2a01,03acd484e2f0c7f65309ad178a9f559abde09796974c57e714c35f110dfc27ccbe))#y9zthqta'"),
 X("W.descsum_create(\"pkh([d34db33f/44'/0'/0']xpub6ERApfZwUNrhLCkDtcHTcxd75RbzS1ed54G1LkBUHQVHQKqhMkhgbmJbZRkrgZw4koxb5JaHWkY4ALHY2grBGRjaDMzQLcgJvLJuZZvRcEL/1/*)\")",
   "\"pkh([d34db33f/44'/0'/0']xpub6ERApfZwUNrhLCkDtcHTcxd75RbzS1ed54G1LkBUHQVHQKqhMkhgbmJbZRkrgZw4koxb5JaHWkY4ALHY2grBGRjaDMzQLcgJvLJuZZvRcEL/1/*)#ml40v0wf\""),
 Qe("core_getdescriptorinfo_31_1_v1_0_0.json", '"checksum": "8fhd9pwu"', '"checksum": "y9zthqta"', '"checksum": "ml40v0wf"', '"checksum": "89f8spxm"'),
 Qe("core_fresh_wallet_31_1_v1_0_0.json", "wpkh([6d8c4b8f/84h/0h/0h]", "pkh([6d8c4b8f/44h/0h/0h]", "sh(wpkh([6d8c4b8f/49h/0h/0h]", "tr([6d8c4b8f/86h/0h/0h]", "#4yyve3wc", "#m6d2x6j5"),
 (PROG(ORIGIN), "('6d8c4b8f', [84, 0, 0])"),
 X("W.parse_origin(%r)" % DESC84, "('6d8c4b8f', [2147483732, 2147483648, 2147483648])"),
 (PROG(MULTIPATH), "['wpkh([6d8c4b8f/84h/0h/0h]xpub.../0/*)', 'wpkh([6d8c4b8f/84h/0h/0h]xpub.../1/*)']"),
 Qe("bip-0389.mediawiki", "This document specifies a modification to Key Expressions of Descriptors that are described in BIP 380",
    "Wallets typically have one descriptor for producing receiving addresses, and the other for change addresses",
    "These descriptors are often extremely similar - they produce the same types of scripts, derive keys from the same master key, and use derivation paths that are almost identical",
    "Thus it is useful to have a notation to represent both descriptors as a single descriptor where one of the derivation steps is a pair of values",
    "Status: Draft"),
 Qe("bip-0379.md", "This document specifies Miniscript, a language for writing (a subset of) Bitcoin Scripts in a structured way, enabling analysis, composition, generic signing and more",
    "Given a combination of spending conditions, finding the most economical script to implement it",
    "Given a script, find out what spending conditions it permits", "Status: Draft"),
 Qe("bip-0329.mediawiki", "the optional <tt>origin</tt> property must contain an abbreviated output descriptor"),
 Qc("doc/bips.md", "BIP 380`](https://github.com/bitcoin/bips/blob/master/bip-0380.mediawiki)"),
 Qe("core_help_listdescriptors_31_1_v1_0_0.txt", "List all descriptors present in a wallet"),
 Pp("Chapter_5_Wallets_v1_0_0.pptx", "Wallet Implementation Standards", "Standards for Implementation"),
]
