"""SEN0401 chapter 7, corpus text part I (version 1.0.0): the branch 'Taproot and tapscript' - the version 1 witness program, the two ways of
spending it (key path and script path), the control block, the changes that tapscript makes to the script language, the counting opcode that
replaces OP_CHECKMULTISIG and the OP_SUCCESS opcodes. Markers such as [AH] become author-year strings (sen0401_ch07_common). Every number is
computed by the chapter's library; the spends are real taproot spends signed with BIP340 and accepted by the library's interpreter."""
from sen0401_ch07_common_v1_0_0 import *

BK = "ch07_authorization-authentication.adoc"
SPENDS = "C.tr_spend"

NODES_I = [
 ("TaprootBranch", "Taproot and tapscript", 1, None, None, P(
  (W, "This branch presents the last upgrade of the chapter. Taproot is a new kind of output, a witness program of version 1, that can be spent in two ways: with one signature made for its key, or by revealing one script out of a tree of scripts that the key commits to. Tapscript is the slightly different version of the script language that the revealed scripts use [AH]."),
  (Y, "The upgrade combines the ideas of the previous branch. A tree of alternative scripts gives many conditions for the price of one hash; a tweaked key makes the same output a commitment to the tree; and a scriptless multisignature lets the parties who agree spend with a single signature that no one can tell from the signature of a single person. The book's reason is that a contract whose outcome is predictable should be settled by mutual satisfaction, and then nothing about its other conditions needs to be on the chain [AH]."),
  (E, "The data shows the result. Of the 6 taproot inputs in the first 599 transactions of block 775,072, 5 are spent by the key path with one signature, and the 1 script path spend reveals a script of 720 bytes with a control block of 33 bytes [MP]. Taproot became active at block 709,632 on 14 November 2021, and Bitcoin Core's source records the activation height in a comment on the warning height that is one miner confirmation window later [MA] [BCL]."),
  (H, "The branch has two groups. The first, taproot outputs, explains the output, the spending by the key path, the spending by the script path and the control block that proves the script belongs to the output. The second, tapscript, explains what changes in the script language, the counting opcode that replaces the old multisignature opcode, and the opcodes that make a script succeed. Every example is a real transaction signed and verified by the chapter's library."),
 ), None),

 ("TaprootOutputs", "Taproot outputs", 2, "TaprootBranch", None, P(
  (W, "This group is about the output itself and the two ways to spend it. The output holds a public key and nothing else, and it can be spent either by the key or by a script that the key commits to. The group explains the output, the key path, the script path and the control block [B341]."),
  (Y, "A single kind of output replaces the separate pay to public key and pay to script hash outputs. BIP341 states the aim: all outputs become spendable by either a key or, optionally, a script, and they are indistinguishable from each other, so that as long as the key path is used it is not revealed whether a script path was also permitted [B341]."),
  (H, "The first section computes the output key from an internal key and a script tree. The second spends it with a signature, and the third spends it with a script and a proof. The fourth section explains the control block, the string of bytes that connects the revealed script to the output. The examples sign real transactions and verify them with the library, and the browser examples recompute the keys and the signature check with SHA-256 and curve arithmetic alone."),
  (K, "The group describes the rules of the consensus and the practice of wallets. BIP341 is the consensus text; BIP86 only says how a single-key wallet should derive its keys; and the choice of an internal key for a contract is advice and not a rule. Where the page gives advice, it names the document it comes from."),
 ), None),

 ("Taproot", "Taproot output", 3, "TaprootOutputs", ("the output key is the internal key plus a tweak that commits to the tree", "A taproot output is a witness program of version 1 whose program is the 32-byte x coordinate of a point Q, computed as the internal key P plus the tagged hash of P and the root of a script tree, times the generator point; paying to Q is also a commitment to the scripts.",
   (PROG(SECP + SCHNORR + "internal = G[0].to_bytes(32, 'big')                                  # the internal key P: here the generator point, for the example\nroot = tagged('TapLeaf', bytes([0xc0, 1]) + bytes([0x51]))      # the root of a tree with one leaf: the script OP_TRUE\nparity, q = output_key(internal, root)\nresult = (parity, q.hex(), output_key(internal)[1] != q)"), "(0, '9b6ce0db0707e29f92bf8893ed1911d397e3d2d76bbc68110c49da2ceec8be23', True)")), P(
  (W, "Taproot is the name of the output type and of the soft fork that added it. The book builds it from the earlier ideas: pay to contract tweaks a key to commit to an agreement, and taproot commits instead to the program code of a contract by tweaking with the root of a MAST. The key that is tweaked is a regular public key, so it can require one signature, the signatures of several people, or even be made so that no signature for it can exist. The tweaked key is the taproot output key, and the key before the tweak is the taproot internal key [AH]."),
  (Y, "The construction gives two ways to satisfy the same contract. If everyone interested agrees, they can sign with the key and nothing else appears on the chain. If they do not, one of the scripts is revealed. The book notes that a spend by a million participants of a very complex contract and a spend by one user of his own coins then look the same on the chain. The only downside the book knows is that a contract that wants a tree but no cooperative clause must still put an internal key, about 33 bytes, on the chain [AH]."),
  (E, "BIP341 gives the formula and says what the program is: a witness version 1 whose programs consist of 32-byte encodings of points Q, with Q computed as P plus the hash of P and m times G, for a public key P and the root m of a Merkle tree whose leaves consist of a version number and a script. Bitcoin Core's constants name the same sizes: the program has 32 bytes, the leaf version for tapscript is 0xc0 and the mask that leaves the version is 0xfe [B341] [BCH]. The example takes the generator point as the internal key and a tree of one leaf that holds the script OP_TRUE, whose leaf hash is a85b2107...; the output key is 9b6ce0db... with an even y coordinate, and a different tree gives a different key."),
  (H, "The example follows the formula. The leaf hash is the tagged hash of the leaf version and the script; with a single leaf it is the root. The tweak is the tagged hash of the internal key and the root, taken as a number; the output key is the internal point plus the tweak times the generator, and only its x coordinate is the program. The library computes the same value and the same address form, and BIP341's wallet test vectors, seven in all, give the same keys, addresses and control blocks, as the verification script reports [BCW]."),
  (K, "A tree is not required. If the spending conditions do not need a script path, BIP341 and BIP86 both advise tweaking with an empty tree, Q = P plus the tagged hash of P alone, times G, so that the key commits to an unspendable script path instead of having no script path at all; the reason, which BIP341 gives, is that a key made from several keys can otherwise be given a hidden script path by a dishonest participant. When no key should be able to spend, the advice is a point with unknown discrete logarithm; the example in BIP341 is the hash of the generator point's encoding [B341] [B86]."),
 ), None),

 ("KeyPathSpending", "Key path spending", 3, "TaprootOutputs", ("the witness is one 64-byte signature for the output key", "Spending a taproot output by the key path needs one witness element, a BIP340 signature for the output key; it is checked like any other signature and shows nothing about any script the output might have committed to.",
   (PROG(SECP + SCHNORR + "q = bytes.fromhex('19cba5b63bdcbf46629edf17cda13bce567b90442bb421eae8a32e35843967c3')       # an output key\nsig = bytes.fromhex('f1473c2449c0ffa8c93f1c5585cede0eb918113ca49cfbd4d493591766d9f4c5bbc5fe8c237f2d1ef17925b0d58f7672aec55c06df41c6bac9be3ee6ef47bb13')\nmsg = hashlib.sha256(b'pay Bob 20000 satoshis').digest()\nresult = (len(sig), schnorr_verify(q, msg, sig), schnorr_verify(q, hashlib.sha256(b'pay Eve').digest(), sig))"), "(64, True, False)")), P(
  (W, "Key path spending is the spending of a taproot output with a signature for its key. The book describes it as the case in which spending is possible using just the key, such as a single signature or a scriptless multisignature, and says that the data put on the chain is the public key in the witness program and the signature on the witness stack. In BIP341's rules, if exactly one element remains in the witness stack after the optional annex is removed, the key path is used, and that element is interpreted as a signature that must be valid for the output key [AH] [B341]."),
  (Y, "The key path is the cheap and private way, and BIP341 says that ideally outputs are spent with it, because it prevents observers from learning the spending conditions of a coin. A key path spend can be a normal payment from a wallet with one key or several, or the cooperative settlement of a hidden contract. The signature is made with the secret key that matches the output key, which for a tweaked key is the internal secret key plus the tweak, adjusted for the parity of the point [B341]."),
  (E, "Alice's payment to Bob's cafe in chapter 6, in block 775,072, spends a taproot output this way: its witness has one element of 65 bytes, a Schnorr signature of 64 bytes followed by the hash type byte 01, and the library accepts it against the output it spends [MP]. In a signature made with the default hash type, the type byte is left out and the element is 64 bytes. Spending an output of the same kind with a script tree costs the same, since the signature does not depend on the tree except through the tweak: a transaction with one such input weighs 308 weight units in the library's example, whether the output committed to a tree of three scripts or to none [B340]."),
  (H, "The example checks a BIP340 signature in the browser. The output key was computed from the internal secret key 7 with an empty tree, the message is a stand-in for the signature hash of a transaction, and the signature was made with the tweaked secret key; the check holds, and it fails for another message. If the signature were made with the untweaked internal key, the real library rejects it with the error SCHNORR_SIG; the tweak is part of the secret [B341]."),
  (K, "The signature commits to more than the outputs, and the format of the signature has a trap. BIP341 builds the signed message from the hash type, the version, the lock time, and, unless the flag ANYONECANPAY is set, from the amounts and the scriptPubKeys of all the outputs being spent; it also commits to the spend type, which holds the annex flag. A signature of 64 bytes means the default hash type, and a signature of 65 bytes must not end in the byte 00, because that would let anyone, even a miner, turn a 64-byte signature into a 65-byte one and change the wtxid and the fee rate of the transaction; the library rejects such a signature with SCHNORR_SIG_HASHTYPE [B341]."),
 ), None),

 ("ScriptPathSpending", "Script path spending", 3, "TaprootOutputs", ("the witness shows a script, a proof and the data that satisfies it", "Spending a taproot output by the script path reveals one script of the committed tree, the control block that connects the script to the output key, and the items that satisfy the script; no other script of the tree is shown.",
   (PROG(SECP + SCHNORR + "def leaf(script): return tagged('TapLeaf', bytes([0xc0, len(script)]) + script)\ndef branch(a, b): return tagged('TapBranch', min(a, b) + max(a, b))\nscripts = [bytes([0x51]), bytes([0x52]), bytes([0x53])]\nla, lb, lc = [leaf(s) for s in scripts]\nroot = branch(branch(la, lb), lc)\ninternal = G[0].to_bytes(32, 'big')\nparity, q = output_key(internal, root)\ncontrol = bytes([0xc0 + parity]) + internal + lc + la          # reveal the second script's neighbours in order... for the first script: lb then lc\nproof_for_a = [lb, lc]\nh = la\nfor sibling in proof_for_a: h = branch(h, sibling)\nresult = (h == root, output_key(internal, h)[1] == q, len(control))"), "(True, True, 97)")), P(
  (W, "Script path spending is the spending of a taproot output by one of its scripts. The book lists what the witness holds: a version number; the underlying key, the taproot internal key; the script to execute, called the leaf script; one 32-byte hash for each junction in the Merkle tree along the path that connects the leaf to the root; and any data needed to satisfy the script, such as signatures or preimages [AH]."),
  (Y, "The reason for the design is to reveal as little as possible and to pay only for what is used. The script path is for the case in which the key path is not applicable, for instance because the parties failed to reach agreement; BIP341 says that such a spend leaks that there is a script path and that the key path was not applicable, so the other leaves stay hidden but the existence of the tree does not. The cost grows with the depth of the leaf, 32 bytes for each level [B341]."),
  (E, "In block 775,072 the 1 script path spend is an inscription: its tapscript begins with a 32-byte key and OP_CHECKSIG, then OP_FALSE OP_IF and an envelope of data, which the OP_IF never runs, with the content type image/png near the start; the witness has three elements, a signature of 64 bytes, a script of 720 bytes and a control block of 33 bytes, so the tree has one leaf [MP]. The example of the page builds a tree of three scripts and shows that the proof of the first script has two hashes and that of the third has one, and that either folds up to the root the output key committed to. In the library, a spend of a leaf of a three-leaf tree with two signatures is accepted, and the same spend with the wrong parity bit in the control block is rejected as WITNESS_PROGRAM_MISMATCH [B341]."),
  (H, "The verifier works in a fixed order, which BIP341 specifies. It removes the annex if there is one; with at least two elements left, it takes the last element as the control block and the one before it as the script; it computes the leaf hash from the leaf version and the script, folds in each hash of the control block, takes the result as the root, and checks that the tweaked internal key equals the output key, including the parity bit. Only then does it run the script, with the rules of its leaf version, on the items that remain [B341]."),
  (K, "A script path spend gives up something the key path keeps. It shows that the output had a tree and which leaf was used, and the depth of the leaf leaks the minimum depth of the tree. An inscription is not a different kind of spend; it uses the script path, with a script that contains data that is never run, and nothing in the rules limits the data except the size of the witness and the rules of the standard relay policy [B341] [MP]."),
 ), None),

 ("ControlBlock", "Control block", 3, "TaprootOutputs", ("the control block is 33 bytes plus 32 for each level of the tree", "The control block is the last element of a script path witness: one byte that holds the leaf version and the parity of the output key, the 32-byte internal key, and the sibling hashes from the leaf up to the root, so its length is 33 plus 32 times the depth of the leaf.",
   (PROG("control = bytes.fromhex('c100fd948e98e6289f833ddb7f10b8f72fbcdd4804b89421a1d3be9c1a9ea039a5')          # the control block of the block's only script path spend\nversion, parity = control[0] & 0xfe, control[0] & 1\ninternal_key = control[1:33]\nresult = (version, parity, len(internal_key), (len(control) - 33) // 32)"), "(192, 1, 32, 0)")), P(
  (W, "The control block is the proof that the revealed script belongs to the output. The book mentions it only in a note that it should be introduced; BIP341 defines it as the last stack element of a script path spend, of length 33 plus 32 times m, for a value of m that is an integer between 0 and 128, inclusive. Its first byte is the leaf version with the parity of the output key's y coordinate in its lowest bit, the next 32 bytes are the internal key, and the rest are the sibling hashes [AH] [B341]."),
  (Y, "Each field has a use. The parity bit lets the verifier lift the x coordinate of the output key to a single point, which, BIP341 says, is not strictly needed to check the commitment but is needed to allow batch verification. The leaf version lets later soft forks define new script rules for other versions while tapscript uses 0xc0. The sibling hashes are sorted before they are hashed, so the control block does not need to say whether each sibling is on the left or the right [B341]."),
  (E, "Bitcoin Core names the sizes: the base size of the control block is 33, each node is 32 bytes and the largest number of nodes is 128, so the largest control block is 33 plus 32 times 128, or 4,129 bytes. The one script path in the block has a control block of 33 bytes, whose first byte is 0xc1, leaf version 0xc0 with the parity bit set, and whose 32-byte internal key is 00fd948e...; it has no sibling hash because the tree has one leaf. In the example of the page's library, the control block of the first leaf of a tree of three scripts is 97 bytes, the 33 plus two hashes [BCH] [MP]."),
  (H, "The example takes the control block apart: the first byte masked with 0xfe gives the leaf version 192, which is 0xc0, and masked with 1 gives the parity 1; the internal key is the 32 bytes after it; and the number of sibling hashes is the length less 33, divided by 32, which is 0 here. A control block whose length is not 33 plus a multiple of 32, or is outside 33 to 4,129 bytes, is rejected with the error TAPROOT_WRONG_CONTROL_SIZE [BCH] [B341]."),
  (K, "The limit of 128 levels is not a practical one. BIP341 explains that the most space-efficient tree can be built by the Huffman algorithm, with branch lengths about the base-2 logarithm of the inverse of the probability, and that a branch longer than 128 would hold a script with a chance of use below 1 in 2 to the power 128, which is the security bound, so such a script could probably be removed. A tree with that many leaves could not be written down anyway [B341]."),
 ), None),

 ("Tapscript", "Tapscript", 2, "TaprootBranch", None, P(
  (W, "This group is about the version of the script language that the leaves of a taproot tree use. The leaf version 0xc0 selects it, and BIP342 defines it. It keeps most of the language of the earlier sections and changes how signatures are checked, how many signatures are counted and what happens with opcodes that the old language did not use [B342]."),
  (Y, "The changes have two aims. The first is to allow the batch verification of Schnorr signatures, which the old multisignature opcode makes impossible; the second is to make the language easier to extend with soft forks. BIP342 summarises both: the inefficient CHECKMULTISIG opcodes are disabled, a new opcode creates the same policies in a batch-verifiable way, MINIMALIF removes a malleability vector, and the OP_SUCCESS opcodes allow new opcodes more cleanly than the OP_NOP opcodes [B342]."),
  (H, "The first section lists the changes and runs each one through the library, in a real script path spend. The second explains the opcode that counts signatures and shows the m-of-n multisignature rewritten with it, including the sizes in bytes. The third explains the opcodes that make a script succeed at once and the rule that allows them to be redefined later."),
  (K, "BIP342 changes more than the book mentions: it also adds a budget for the signature operations of each script, a rule that unknown key types succeed, and a rule that the annex is committed to by the signature. The page names these where they matter and gives the document for the rest."),
 ), None),

 ("TapscriptChanges", "Changes in tapscript", 3, "Tapscript", ("the old multisignature opcodes fail; every signature is a Schnorr signature or empty", "Tapscript disables the old multisignature opcodes, makes every signature check use BIP340 Schnorr signatures, requires a signature that is not expected to succeed to be the empty value, and makes the MINIMALIF rule part of the consensus.",
   (PROG("legacy = 1 + 3 * 34 + 1 + 1          # OP_2, three 33-byte keys with their push byte, OP_3, OP_CHECKMULTISIG\ntapscript = 3 * 33 + 1 + 2 + 1 + 1     # three 32-byte keys with their push byte, CHECKSIG, two CHECKSIGADD, OP_2, NUMEQUAL\nresult = (legacy, tapscript, legacy - tapscript)"), "(105, 104, 1)")), P(
  (W, "The book lists the major differences. The old OP_CHECKMULTISIG and OP_CHECKMULTISIGVERIFY are removed and the new OP_CHECKSIGADD takes their place. All signature operations use the Schnorr algorithm of BIP340. A signature check that is not expected to succeed must be fed OP_FALSE, also called OP_0, instead of a signature, and anything else fed to a failed check makes the entire script fail. Opcodes that were unusable become OP_SUCCESS opcodes, which make a script succeed [AH]."),
  (Y, "The empty-signature rule is what makes batch verification possible. A verifier that checks many Schnorr signatures together needs to know that every non-empty signature must be valid, so that it can add them to the batch and not run each one to learn the result of the check. In the old language, a failed check could leave an invalid signature on the stack without harm; in tapscript an invalid, non-empty signature fails the whole script, and an empty one only makes the check return false [B342]."),
  (E, "BIP342 states the other changes. The disabled opcodes fail when they are executed and are ignored in a branch that is not executed, as OP_RETURN does, and the reason given is to make sure that people who keep using OP_CHECKMULTISIG notice a problem at once and not later. The MINIMALIF rule, which is only a policy rule in P2WSH, becomes a consensus rule: the argument of OP_IF and OP_NOTIF must be exactly empty or exactly the one byte 01, to make scripts that take branch information from the stack easier to make non-malleable. In the library, a leaf with OP_CHECKMULTISIG is rejected with TAPSCRIPT_CHECKMULTISIG, an OP_IF fed the byte 02 with TAPSCRIPT_MINIMALIF, and a lone check fed the byte 01 as its signature with SCHNORR_SIG_SIZE, while an empty signature gives the plain EVAL_FALSE [B342]."),
  (H, "The example compares the sizes of the same policy: the legacy script for 2 of 3 is 105 bytes and the tapscript form is 104 bytes, because each key costs 34 bytes in both forms, a push of 33 bytes in the legacy script and a push of 32 bytes followed by one signature opcode in the tapscript, and the legacy form needs one more byte, the count of keys, which the tapscript form does not write because the opcodes count the keys themselves. The signature rules are checked with real signatures in a leaf with one key: the right signature is accepted, a signature of another key is rejected as SCHNORR_SIG, an empty signature makes the script fail without an error in the signature, and a signature of the wrong length is rejected for its size [B342]."),
  (K, "There is an extra rule for upgrades, which the book leaves out. A public key in tapscript that is not 32 bytes long is of an unknown type, and any non-empty signature for it is accepted without being checked, which makes it possible to define new key types or signature algorithms by a soft fork; Bitcoin Core's relay policy therefore refuses such scripts, so that they are not relayed before a meaning has been given to them. The same is true of an unknown leaf version, whose scripts are accepted by consensus and discouraged by policy [B342] [BCI]."),
 ), None),

 ("ChecksigAdd", "OP_CHECKSIGADD", 3, "Tapscript", ("each valid signature adds one; an empty signature adds nothing", "OP_CHECKSIGADD pops a public key, a number and a signature, adds one to the number if the signature is valid, leaves it unchanged if the signature is empty and fails the script if the signature is not empty and not valid; a multisignature is a chain of these followed by a comparison.",
   (PROG("def checksigadd(count, sig, valid):              # a model of the opcode: the signature is valid, empty or wrong\n    if sig == b'': return count                         # an empty signature counts nothing\n    if sig in valid: return count + 1                   # a valid one counts one\n    raise ValueError('a non-empty invalid signature fails the script')\ndef two_of_three(sigs, valid):\n    count = 0\n    for s in sigs: count = checksigadd(count, s, valid)\n    return count == 2\nvalid = {b'sig-a', b'sig-b', b'sig-c'}\nresult = (two_of_three([b'', b'sig-b', b'sig-a'], valid), two_of_three([b'', b'', b'sig-a'], valid), two_of_three([b'sig-a', b'sig-b', b'sig-c'], valid))"), "(True, False, False)")), P(
  (W, "OP_CHECKSIGADD is the opcode that replaces OP_CHECKMULTISIG. The book says that it increments a counter by one when it successfully verifies a signature, which makes it possible to count how many signatures passed and compare the count with the number wanted. BIP342 gives the equivalence: it is functionally the same as OP_ROT OP_SWAP OP_CHECKSIG OP_ADD, but takes one byte [AH] [B342]."),
  (Y, "The multisignature opcode could not be kept because it does not combine with batch verification: it tries signatures against keys in order until enough match, so a verifier cannot tell which pairs are meant to be valid. Here every signature is tied to its key by position, and the empty value says explicitly that a key does not sign. BIP342 gives the translation: a script of m, n keys, n and CHECKMULTISIG, with witness 0 and m signatures, becomes the first key and CHECKSIG, each of the other keys with CHECKSIGADD, and m NUMEQUAL, with a witness of one element for each key that is either its signature or empty [B342]."),
  (E, "The library runs the translation. A 2-of-3 leaf of 104 bytes, with the keys of Mohammed, Saeed and Zahra, is spent in a real taproot transaction with the witness empty, signature, signature, and the interpreter accepts it; with one signature only it fails with EVAL_FALSE, since the count is 1, and with a non-empty garbage value in the place of an absent signature it fails with the error SCHNORR_SIG_SIZE. Mohammed's three-path contract of the previous branch, rebuilt as three tapscript leaves, weighs 577, 617 and 414 weight units for its three paths, against 585, 584 and 509 for the 192-byte P2WSH script, and a key path spend of the same output would weigh 308, so the script paths save weight only for the rarest path and the key path is the real saving [B342]."),
  (H, "The example is a model of the opcode, not the interpreter: the signature is valid when it is in a set, empty when it is the empty value, and anything else stops the script. It accepts two signatures and an empty value in any of the three places; it refuses a count of one and a count of three, since the final comparison is for equality, NUMEQUAL, and not for at least two. The witness is listed in the reverse order of the keys, because the last element is used first [B342]."),
  (K, "There are costs. A signature check that fails for a reason other than being empty fails the script, so a script that wants to test a signature and continue must use the empty value. Each non-empty signature counts against the budget of the script: BIP342 sets the budget at 50 plus the serialized size of the input's witness, and each non-empty signature takes 50 from it. A 2-of-3 spend with a witness of 335 bytes has a budget of 385, which allows 7 signatures, so an honest script is far from the limit [B342]."),
 ), None),

 ("OpSuccess", "OP_SUCCESS opcodes", 3, "Tapscript", ("87 opcode values make a tapscript succeed at once", "In tapscript, 87 opcode values that were unused or disabled are renamed OP_SUCCESSx, and a script in which one is found succeeds unconditionally even when the bytes after it could not be decoded; a later soft fork can give any of them a meaning, as that can only turn a valid script into an invalid one.",
   (PROG("success = {80, 98, *range(126, 130), *range(131, 135), 137, 138, 141, 142, *range(149, 154), *range(187, 255)}   # the numbers BIP342 lists\ndef tapscript_result(opcodes):                           # a model: scan the opcodes in order\n    return 'success' if any(o in success for o in opcodes) else 'run the script'\nresult = (len(success), tapscript_result([0x51, 0xac]), tapscript_result([0x51, 187, 0xff]))"), "(87, 'run the script', 'success')")), P(
  (W, "The OP_SUCCESS opcodes are opcode values that make a tapscript valid as soon as it is read. The book explains the idea: opcodes of previous versions that were unusable are redefined so that using them makes the entire script succeed, which lets a future soft fork redefine them as not succeeding under certain circumstances; that is a restriction and so possible by soft fork, whereas defining a non-succeeding operation as a success could only be done by a hard fork [AH]."),
  (Y, "The old route for new opcodes was OP_NOP, which can only look at the stack and leave it alone. An OP_SUCCESS opcode can be given more power. BIP342 gives the reasons: it may write to the stack, it may lift the limit on the size of stack elements because it comes before the check of the initial stack, it may change the behaviour of existing opcodes so that they work with it, and since it makes even a script that cannot be decoded succeed, it can be used to introduce multi-byte opcodes or a whole new language [B342]."),
  (E, "BIP342 lists the numbers: 80, 98, 126 to 129, 131 to 134, 137 and 138, 141 and 142, 149 to 153, and 187 to 254, which are 87 values, and the same list is in Bitcoin Core's IsOpSuccess function. The library runs a real script path spend of a leaf made of the single opcode 0xbb, which is OP_SUCCESS187, with an empty witness besides the script and control block, and the interpreter accepts it; a leaf that begins with 0x50 followed by bytes that do not decode is accepted too, and Bitcoin Core's policy flag that discourages the opcodes makes the same spend fail with DISCOURAGE_OP_SUCCESS [B342] [BCS]."),
  (H, "The model in the example scans the opcodes in order and succeeds at the first one in the list; it does not run the rest, which is the point. The real scan decodes the script first and fails if a script is cut short before any such opcode was found, so a truncated push before an OP_SUCCESS fails, while one after it does not. A wallet must never put such an opcode in a script by accident: anyone could spend the output, since the script succeeds without any signature [B342]."),
  (K, "The same property is a danger for the one who writes a script. A leaf with an OP_SUCCESS opcode is valid without a signature, so an output whose only leaf is such a script is an output that anyone can spend. Relay policy refuses these scripts for that reason, and also so that wallets and nodes can notice the mistake before any funds are lost. The names are renamed in the code as OP_SUCCESS80 to OP_SUCCESS254 [B342] [BCP]."),
 ), None),
]

CHECKS_I = [
 Qb(BK, "contracts whose participants want to use MAST but who don't want a", "mutual satisfaction clause have to include a taproot internal key on the", "blockchain, adding about 33 bytes of overhead.", "called _keypath spending_.", "called _scriptpath spending_.", "For keypath spending, the data that gets put onchain is the public key", "(in a witness program) and the signature (on the witness stack).", "called the _taproot output key_", "This underlying key", "is called the _taproot internal key_.", "The script to execute, called the _leaf script_.", "One 32-byte hash for each junction in merkle tree along the path that connects the leaf to the merkle root.", "activated", "in November 2021."),
 Qb(BK, "We can instead commit to the program code of a contract", "by committing to the root of a MAST.", "The public key we tweak", "is a regular Bitcoin public key, meaning it could require a signature", "from a single person or it could require a signature from multiple", "people (or it could be created in a special way to make it impossible to", "generate a signature for it).", "any transaction created by a single user who wants it", "to be satisfied by a single signature (or a multisignature generated by", "multiple different wallets they control) looks identical onchain to a", "mutual-satisfaction spend.", "There's no onchain difference in this case", "between a spend by a million users involved in an extraordinarily complex", "contract or a single user just spending their saved bitcoins."),
 Qb(BK, "//FIXME:mention \"control block\" (maybe in MAST section)", "called _tapscript_.", "The old +OP_CHECKMULTISIG+ and +OP_CHECKMULTISIGVERIFY+ opcodes are", "removed.", "A new +OP_CHECKSIGADD+ opcode is provided", "instead.", "increments a counter by one", "All signature operations in tapscript use the schnorr signature", "algorithm as defined in BIP340.", "must be fed the value +OP_FALSE+ (also called +OP_0+)", "instead of an actual signature.  Providing anything else to a failed", "signature-checking operation will cause the entire script to fail.", "This also helps support batch validation of schnorr signatures.", "Opcodes in previous versions of Script that were unusable are now", "redefined to cause an entire script to succeed if they are used.", "which", "is a restriction and so is possible to do in a soft fork.", "be done in a hard fork, which is a much more challenging upgrade", "path."),
 Qe("bip-0341.mediawiki", "a new witness version is added (version 1), whose programs consist of 32-byte encodings of points ''Q''.", "making all outputs spendable by either a key or (optionally) a script, and indistinguishable from each other.", "it is not revealed whether a script path was permitted as well", "If there are at least two witness elements left, script path spending is used:", "If there is exactly one element left in the witness stack, key path spending is used:", "The single witness stack element is interpreted as the signature and must be valid", "must have length ''33 + 32m'', for a value of ''m'' that is an integer between 0 and 128", "Let ''v = c[0] & 0xfe'' and call it the ''leaf version''", "The parity of the Y coordinate is necessary to lift the X coordinate ''q'' to a unique point.", "it is necessary to allow batch verification.", "Ideally, outputs are spent using the key path which prevents observers from learning the spending conditions of a coin.", "A script path spend leaks that there is a script path and that the key path was not applicable", "the output key should commit to an unspendable script path instead of having no script path", "Q = P + int(hash<sub>TapTweak</sub>(bytes(P)))G", "If that is inacceptable, pick as internal key a \"Nothing Up My Sleeve\" (NUMS) point", "H = lift_x(0x50929b74c1a04954b78b4b6035e97a5e078a5a0f28ec96d547bfee9ace803ac0)", "The <code>0x50</code> is chosen as it could not be confused with a valid P2WPKH or P2WSH spending.", "The total length of ''SigMsg()'' is at most ''206'' bytes", "A Taproot signature is a 64-byte Schnorr signature, as defined in [[bip-0340.mediawiki|BIP340]], with the sighash byte appended in the usual Bitcoin fashion.", "If omitted, the resulting signatures are 64 bytes, and a SIGHASH_DEFAULT mode is implied.", "If the <code>SIGHASH_ANYONECANPAY</code> flag is not set, the message commits to the amounts of ''all'' transaction inputs.", "Permitting that would enable malleating (by third parties, including miners) 64-byte signatures into 65-byte ones, resulting in a different `wtxid` and a different fee rat", "to have branches longer than 128 you would need to have scripts with an execution chance below 1 in ''2<sup>128</sup>''"),
 Qe("bip-0342.mediawiki", "The inefficient <code>OP_CHECKMULTISIG</code> and <code>OP_CHECKMULTISIGVERIFY</code> opcodes are disabled.", "a new opcode <code>OP_CHECKSIGADD</code> is introduced to allow creating the same multisignature policies in a batch-verifiable way.", "a potential malleability vector is eliminated by requiring MINIMALIF", "the new tapscript <code>OP_SUCCESS</code> opcodes allow introducing new opcodes more cleanly than through <code>OP_NOP</code>", "If any opcode numbered ''80, 98, 126-129, 131-134, 137-138, 141-142, 149-153, 187-254'' is encountered, validation succeeds", "The disabled opcodes behave in the same way as <code>OP_RETURN</code>, by failing and terminating the script immediately when executed, and being ignored when found in unexecuted branch of the script.", "The MINIMALIF rules, which are only a standardness rule in P2WSH, are consensus enforced in tapscript.", "must be either exactly 0 (the empty vector) or exactly 1 (the one-byte vector with value 1)", "This makes it considerably easier to write non-malleable scripts that take branch information from the stack.", "functionally equivalent to <code>OP_ROT OP_SWAP OP_CHECKSIG OP_ADD</code>, but only takes 1 byte", "The budget equals 50 + the total serialized size in bytes of the transaction input's witness (including the <code>CompactSize</code> prefix).", "with a non-empty signature decrements the budget by 50", "This is a precaution to make sure people who accidentally keep using <code>OP_CHECKMULTISIG</code> in Tapscript notice a problem immediately.", "<pubkey_1> CHECKSIG <pubkey_2> CHECKSIGADD ... <pubkey_n> CHECKSIGADD m NUMEQUAL", "Every witness element <code>w_i</code> is either a signature corresponding to <code>pubkey_i</code> or an empty vector."),
 Qe("bip-0086.mediawiki", "Q = P + int(hash<sub>TapTweak</sub>(bytes(P)))G"),
 Qe("bip-0340.mediawiki", "BIP0340/challenge"),
 Qc("src/script/interpreter.h", "inline constexpr size_t WITNESS_V1_TAPROOT_SIZE = 32;", "inline constexpr uint8_t TAPROOT_LEAF_MASK = 0xfe;", "inline constexpr uint8_t TAPROOT_LEAF_TAPSCRIPT = 0xc0;", "inline constexpr size_t TAPROOT_CONTROL_BASE_SIZE = 33;", "inline constexpr size_t TAPROOT_CONTROL_NODE_SIZE = 32;", "inline constexpr size_t TAPROOT_CONTROL_MAX_NODE_COUNT = 128;"),
 Qc("src/script/interpreter.cpp", "if (flags & SCRIPT_VERIFY_DISCOURAGE_OP_SUCCESS) {", "return set_error(serror, SCRIPT_ERR_DISCOURAGE_OP_SUCCESS);", "if (flags & SCRIPT_VERIFY_DISCOURAGE_UPGRADABLE_TAPROOT_VERSION) {", "if ((flags & SCRIPT_VERIFY_DISCOURAGE_UPGRADABLE_PUBKEYTYPE) != 0) {"),
 Qc("src/script/script.cpp", "bool IsOpSuccess(const opcodetype& opcode)", "return opcode == 80 || opcode == 98 || (opcode >= 126 && opcode <= 129) ||", "(opcode >= 131 && opcode <= 134) || (opcode >= 137 && opcode <= 138) ||"),
 Qc("src/kernel/chainparams.cpp", "consensus.MinBIP9WarningHeight = 711648; // taproot activation height + miner confirmation window", "// Taproot exception"),
 Qe("mainnet_activation_blocks_v1_0_0.json", "\"height\": 709632"),
 Qe("core_doc_bips.md", "Key aggregation via `musig()` descriptors is supported as of **v30.0**"),
 # executed: the output key and the tweak
 X("(lambda gx, root: (L.taproot_tweak_pubkey(gx, root)[0], L.taproot_tweak_pubkey(gx, root)[1].hex(), L.taproot_tweak_pubkey(gx)[1] != L.taproot_tweak_pubkey(gx, root)[1]))(L.G[0].to_bytes(32, 'big'), L.tap_leaf_hash(0xc0, b'\\x51'))", (0, "9b6ce0db0707e29f92bf8893ed1911d397e3d2d76bbc68110c49da2ceec8be23", True)),
 X("(lambda g: (exec(" + repr(SECP + SCHNORR) + ", g), (lambda gx, root: g['output_key'](gx, root) == L.taproot_tweak_pubkey(gx, root))(L.G[0].to_bytes(32, 'big'), L.tap_leaf_hash(0xc0, b'\\x51')))[1])({})", True),
 X("(L.sha256(b'\\x04' + L.G[0].to_bytes(32, 'big') + L.G[1].to_bytes(32, 'big')).hex(), L.lift_x(int('50929b74c1a04954b78b4b6035e97a5e078a5a0f28ec96d547bfee9ace803ac0', 16)) is not None)", ("50929b74c1a04954b78b4b6035e97a5e078a5a0f28ec96d547bfee9ace803ac0", True)),
 X("C.census(L)['p2tr-keypath'] + C.census(L)['p2tr-scriptpath']", 6),
 X("[__import__('datetime').datetime.fromtimestamp(b['timestamp'], __import__('datetime').UTC).strftime('%Y-%m-%d') for b in C.ev_json('mainnet_activation_blocks_v1_0_0.json')['blocks'] if b['height'] == 709632]", ["2021-11-14"]),
 X("709632 + 2016", 711648),
 X("33 + 32 * 128", 4129),
 # executed: key path
 X("(lambda r: (r[0], len(r[1][0]), r[2]))(C.tr_keypath(1))", ("OK", 64, 308)),
 X("(lambda r: (r[0], len(r[1][0]), r[1][0][-1]))(C.tr_keypath(1, hashtype=1))", ("OK", 65, 1)),
 X("(C.tr_keypath(1, [b'\\x51'])[0], C.tr_keypath(1, [b'\\x51'], tamper='untweaked')[0])", ("OK", "SCHNORR_SIG")),
 X("C.tr_keypath(1, [C.csa_script([0, 1, 2], 2), b'\\x51', b'\\x52'])[2]", 308),
 X("(lambda r: (lambda tx, spent: (len(tx.witness[0]), len(tx.witness[0][0]), tx.witness[0][0][-1], L.verify_input(tx, 0, spent, L.MAINNET_FLAGS), L.classify(spent[0][1])[0], spent[0][1].hex()[:12]))(L.parse_tx(r[0]), [(a, bytes.fromhex(s)) for a, s in r[1]]))(C.tx_record('466200308696'))", (1, 65, 1, "OK", "witness_v1_taproot", "5120225d4d0b")),
 X("(lambda d, m: (lambda q, tw: (L.schnorr_verify(q, L.sha256(b'pay Bob 20000 satoshis'), L.schnorr_sign(tw, L.sha256(b'pay Bob 20000 satoshis'))), L.schnorr_verify(q, L.sha256(b'pay Eve'), L.schnorr_sign(tw, L.sha256(b'pay Bob 20000 satoshis')))))(L.taproot_tweak_pubkey(L.schnorr_pubkey(d), m)[1], L.taproot_tweak_seckey(d, m)))(7, b'')", (True, False)),
 X("(lambda g: (exec(" + repr(SECP + SCHNORR) + ", g), (lambda msg, sig: (len(sig), g['schnorr_verify'](bytes.fromhex('19cba5b63bdcbf46629edf17cda13bce567b90442bb421eae8a32e35843967c3'), msg, sig), g['schnorr_verify'](bytes.fromhex('19cba5b63bdcbf46629edf17cda13bce567b90442bb421eae8a32e35843967c3'), L.sha256(b'pay Eve'), sig)))(L.sha256(b'pay Bob 20000 satoshis'), bytes.fromhex('f1473c2449c0ffa8c93f1c5585cede0eb918113ca49cfbd4d493591766d9f4c5bbc5fe8c237f2d1ef17925b0d58f7672aec55c06df41c6bac9be3ee6ef47bb13')))[1])({})", (64, True, False)),
 X("(lambda q: (lambda tx, spent: [(setattr(tx, 'witness', [[sig + bytes([t])]]), L.verify_input(tx, 0, spent, L.MAINNET_FLAGS))[1] for sig in [L.sign_taproot_input(tx, 0, spent, 1)] for t in (0, 5)])(*L.credit_and_spend(b'', L.p2tr_script(q), amount=100000)))(L.taproot_tweak_pubkey(L.schnorr_pubkey(1), b'')[1])", ["SCHNORR_SIG_HASHTYPE", "SCHNORR_SIG_HASHTYPE"]),
 # executed: script path and control block
 X("(lambda w: (len(w), len(w[0]), len(w[1]), len(w[2]), w[2][0], len(w[2][1:33])))(L.parse_tx(C.tx_record('4e0e703251bb')[0]).witness[0])", (3, 64, 720, 33, 193, 32)),
 X("'OP_CHECKSIG 0 OP_IF' in L.disassemble(L.parse_tx(C.tx_record('4e0e703251bb')[0]).witness[0][1])", True),
 X("b'image/png' in L.parse_tx(C.tx_record('4e0e703251bb')[0]).witness[0][1]", True),
 X("(lambda w: (w[0] & 0xfe, w[0] & 1, (len(w) - 33) // 32))(L.parse_tx(C.tx_record('4e0e703251bb')[0]).witness[0][2])", (192, 1, 0)),
 X("(lambda g: (exec(" + repr("control = bytes.fromhex('c100fd948e98e6289f833ddb7f10b8f72fbcdd4804b89421a1d3be9c1a9ea039a5')\nversion, parity = control[0] & 0xfe, control[0] & 1\ninternal_key = control[1:33]\nresult = (version, parity, len(internal_key), (len(control) - 33) // 32)") + ", g), g['result'])[1])({})", (192, 1, 32, 0)),
 X("L.parse_tx(C.tx_record('4e0e703251bb')[0]).witness[0][2].hex()", "c100fd948e98e6289f833ddb7f10b8f72fbcdd4804b89421a1d3be9c1a9ea039a5"),
 X("(lambda s: [C.tr_spend(s, i, it)[0] for i, it in ((0, [b'', ('sig', 1), ('sig', 0)]), (1, []), (2, []))])([C.csa_script([0, 1, 2], 2), b'\\x51', b'\\x51\\x51\\x75'])[:2]", ["OK", "OK"]),
 X("[len(C.tr_spend([C.csa_script([0, 1, 2], 2), b'\\x51', b'\\x52'], i, [b'', ('sig', 1), ('sig', 0)] if i == 0 else [])[1][-1]) for i in (0, 1, 2)]", [97, 97, 65]),
 X("(lambda s: (len(C.tr_spend(s, 0, [b'', ('sig', 1), ('sig', 0)])[1][-1]), len(C.tr_spend(s, 2, [])[1][-1])))([C.csa_script([0, 1, 2], 2), b'\\x51', b'\\x52', b'\\x53'][:3])", (97, 65)),
 X("(lambda s: (C.tr_spend(s, 0, [b'', ('sig', 1), ('sig', 0)])[0], C.tr_spend(s, 0, [b'', ('sig', 1), ('sig', 0)], tamper='ctrl')[0]))([C.csa_script([0, 1, 2], 2), b'\\x51'])", ("OK", "WITNESS_PROGRAM_MISMATCH")),
 X("(lambda g: (exec(" + repr(SECP + SCHNORR + "def leaf(script): return tagged('TapLeaf', bytes([0xc0, len(script)]) + script)\ndef branch(a, b): return tagged('TapBranch', min(a, b) + max(a, b))\nscripts = [bytes([0x51]), bytes([0x52]), bytes([0x53])]\nla, lb, lc = [leaf(s) for s in scripts]\nroot = branch(branch(la, lb), lc)\ninternal = G[0].to_bytes(32, 'big')\nparity, q = output_key(internal, root)\nh = la\nfor sibling in [lb, lc]: h = branch(h, sibling)\nh2 = lc\nfor sibling in [branch(la, lb)]: h2 = branch(h2, sibling)\nresult = (h == root, h2 == root, output_key(internal, h)[1] == q)") + ", g), g['result'])[1])({})", (True, True, True)),
 X("(lambda scs: [C.tr_spend(scs, i, it, sequence=sq)[2] for i, it, sq in ((0, [b'', ('sig', 1), ('sig', 0)], 0xffffffff), (1, [('sig0',), ('sig', 1), ('sig0',), ('sig', 3)], 4320), (2, [('sig', 3)], 12960))])([C.csa_script([0, 1, 2], 2), L.push_int(4320) + b'\\xb2\\x75' + L.push_data(C.xpub(3)) + b'\\xad' + L.push_data(C.xpub(0)) + b'\\xac' + L.push_data(C.xpub(1)) + b'\\xba' + L.push_data(C.xpub(2)) + b'\\xba' + L.push_int(1) + b'\\x9c', L.push_int(12960) + b'\\xb2\\x75' + L.push_data(C.xpub(3)) + b'\\xac'])", [577, 617, 414]),
 X("[(lambda t: (C.moh_spend(p, sequence=s, tx_out=t), t[0].weight()))([])[1] for p, s in ((1, 0xffffffff), (2, 4320), (3, 12960))]", [585, 584, 509]),
 # executed: tapscript
 X("(len(C.csa_script([0, 1, 2], 2)), 1 + 3 * 34 + 1 + 1, len(L.multisig_script(2, [C.pub(i) for i in range(3)])))", (104, 105, 105)),
 X("(C.tr_spend([C.csa_script([0, 1, 2], 2)], 0, [b'', ('sig', 1), ('sig', 0)])[0], C.tr_spend([C.csa_script([0, 1, 2], 2)], 0, [b'', b'', ('sig', 0)])[0], C.tr_spend([C.csa_script([0, 1, 2], 2)], 0, [b'\\x01', ('sig', 1), ('sig', 0)])[0], C.tr_spend([C.csa_script([0, 1, 2], 2)], 0, [('sig', 2), ('sig', 1), ('sig', 0)])[0])", ("OK", "EVAL_FALSE", "SCHNORR_SIG_SIZE", "EVAL_FALSE")),
 X("(C.tr_spend([C.csa_script([0, 1, 2], 2)], 0, [b'', ('sig', 0), ('sig', 1)])[0], C.tr_spend([C.csa_script([0, 1, 2], 2)], 0, [('sig', 2), b'', ('sig', 0)])[0], C.tr_spend([C.csa_script([0, 1, 2], 2)], 0, [b'', ('sig', 1), ('sig', 2)])[0])", ("SCHNORR_SIG", "OK", "SCHNORR_SIG")),
 X("(lambda sc: (C.tr_spend([sc], 0, [('sig', 0)])[0], C.tr_spend([sc], 0, [('sig', 1)])[0], C.tr_spend([sc], 0, [b''])[0], C.tr_spend([sc], 0, [b'\\x01'])[0]))(L.push_data(C.xpub(0)) + b'\\xac')", ("OK", "SCHNORR_SIG", "EVAL_FALSE", "SCHNORR_SIG_SIZE")),
 X("C.tr_spend([b'\\x51' + L.push_data(C.xpub(0)) + b'\\x51\\xae'], 0, [])[0]", "TAPSCRIPT_CHECKMULTISIG"),
 X("(C.tr_spend([b'\\x63\\x51\\x68'], 0, [b'\\x02'])[0], C.tr_spend([b'\\x63\\x51\\x68'], 0, [b'\\x01'])[0], C.tr_spend([b'\\x63\\x51\\x68'], 0, [b''])[0])", ("TAPSCRIPT_MINIMALIF", "OK", "CLEANSTACK")),
 X("(lambda s: (C.tr_spend(s, 0, [b'', ('sig', 1), ('sig', 0)], annex=b'\\x01')[0], C.tr_spend([b'\\x51'], 0, [], annex=b'\\x01')[0]))([C.csa_script([0, 1, 2], 2)])", ("SCHNORR_SIG", "OK")),
 X("(lambda sc: (C.tr_spend([sc], 0, [b'\\x01'])[0], C.tr_spend([sc], 0, [b'\\x01'], flags=L.MAINNET_FLAGS | {'DISCOURAGE_UPGRADABLE_PUBKEYTYPE'})[0], C.tr_spend([sc], 0, [b''])[0]))(L.push_data(b'\\x02' * 33) + b'\\xac')", ("OK", "DISCOURAGE_UPGRADABLE_PUBKEYTYPE", "EVAL_FALSE")),
 X("(C.tr_spend([b'\\x51'], 0, [], ver=0xc2)[0], C.tr_spend([b'\\x51'], 0, [], ver=0xc2, flags=L.MAINNET_FLAGS | {'DISCOURAGE_UPGRADABLE_TAPROOT_VERSION'})[0], C.tr_spend([b'\\x00'], 0, [], ver=0xc2)[0], C.tr_spend([b'\\x00'], 0, [], ver=0xc0)[0])", ("OK", "DISCOURAGE_UPGRADABLE_TAPROOT_VERSION", "OK", "EVAL_FALSE")),
 X("(lambda sc: [C.tr_spend([sc], 0, [('sig', 0)], flags=L.MAINNET_FLAGS)[0]])(L.push_data(C.xpub(0)) + b'\\xac')", ["OK"]),
 # executed: OP_SUCCESS
 X("[sum(1 for i in range(256) if L.is_op_success(i)), [i for i in range(256) if L.is_op_success(i)][:6], [i for i in range(256) if L.is_op_success(i)][-1]]", [87, [80, 98, 126, 127, 128, 129], 254]),
 X("(lambda success: success == {i for i in range(256) if L.is_op_success(i)})({80, 98, *range(126, 130), *range(131, 135), 137, 138, 141, 142, *range(149, 154), *range(187, 255)})", True),
 X("(C.tr_spend([b'\\xbb'], 0, [])[0], C.tr_spend([b'\\x50\\xff\\xff'], 0, [])[0], C.tr_spend([b'\\xbb'], 0, [], flags=L.MAINNET_FLAGS | {'DISCOURAGE_OP_SUCCESS'})[0])", ("OK", "OK", "DISCOURAGE_OP_SUCCESS")),
 X("C.tr_spend([b'\\x4c'], 0, [])[0]", "BAD_OPCODE"),
 X("C.tr_spend([b'\\x4c\\xbb'], 0, [])[0]", "BAD_OPCODE"),
 X("C.tr_spend([b'\\xbb\\x4c'], 0, [])[0]", "OK"),
]
