"""SEN0401 chapter 5, corpus text part C (version 1.0.0): the branch 'The BIP39 stack' - how a recovery code is generated (entropy, checksum,
word list, eleven-bit segments, code length, normalisation) and how it becomes a seed (key stretching, PBKDF2, salt, root seed, passphrase,
security strength). Markers such as [AH] become author-year strings (sen0401_ch05_common)."""
from sen0401_ch05_common_v1_0_0 import *

MN12 = "army van defense carry jealous true garbage claim echo media make crunch"
ENT12 = "0c1e24e5917779d297e14d45f14e1a1a"
_B128 = "bin(int.from_bytes(bytes.fromhex('%s'), 'big'))[2:].zfill(128)" % ENT12

NODES_C = [
 ("Bip39Stack", "The BIP39 stack", 1, None, None, P(
  (W, "This branch opens the second half of the chapter, in which the book stops surveying the options and works through one stack of technologies in detail. It names the three parts of that stack: BIP39 recovery codes, BIP32 hierarchical deterministic key derivation and BIP44-style implicit paths, and says that all of these standards have been around since 2014 or earlier, so a reader will have no problem finding additional resources for using them [AH]. The present branch covers the first part, the path from a random number to a recovery code and from the code to the seed."),
  (Y, "The branch matters because this is where the abstract words of the first two branches become arithmetic a student can carry out. The chapter describes BIP39 in nine numbered steps, split into two halves: steps one to six generate the code, steps seven to nine turn the code into a seed [AH]. Everything a wallet shows the user, the twelve or twenty-four words, and everything it keeps, the 512-bit seed, is produced by those nine steps, and each of them is short enough to be checked by hand."),
  (E, "The reader has already met the results of these steps. The chapter's three tables print a 128-bit entropy value with its twelve words and the resulting seed, the same words with the passphrase SuperDuperSecret and a different seed, and a 256-bit entropy value with twenty-four words and its seed [AH]. The worked examples of this branch recompute those tables from their inputs, which is possible because every function involved, SHA-256 and PBKDF2 with HMAC-SHA512, is in Python's standard library [PY]. The same functions are what a wallet application uses."),
  (H, "The branch has two groups, matching the two halves of the standard. Generating a recovery code covers the random input, the checksum that is appended to it, the word list the bits are read against, the eleven-bit segments that index into it, the fixed relation between entropy size and word count, and the text normalisation that makes the words comparable across systems. From the code to the seed covers the key-stretching function, the particular function PBKDF2 and its salt, the 512-bit root seed that comes out, the optional passphrase that changes it, and the question of how much entropy is actually needed."),
  (K, "One point of order will save a reader confusion later. The standard's text calls the words a mnemonic and the chapter calls them a recovery code; they are the same thing, and this course uses the chapter's term except when quoting [AH] [B39]. A second point is that the two halves are independent: the standard says that the conversion of the sentence to a seed is completely independent of generating the sentence, which is why a wallet can derive a seed from words it did not generate and why software must compute the checksum itself and warn if it is invalid [B39].")), None),

 ("CodeGeneration", "Generating a recovery code", 2, "Bip39Stack", None, P(
  (W, "This group follows the first six steps of BIP39. The chapter states them as a list: create a random sequence, that is entropy, of 128 to 256 bits; create a checksum of it by taking the first entropy-length over 32 bits of its SHA-256 hash; add the checksum to the end of the random sequence; split the result into segments 11 bits long; map each 11-bit value to a word from the predefined dictionary of 2,048 words; and the recovery code is the sequence of words [AH]. Each section of the group is one of the ideas those steps rely on."),
  (Y, "The order of the steps is not arbitrary, and understanding it answers questions that otherwise look like magic. Why 2,048 words and not 1,000? Because 2,048 is 2 to the 11th, so a word is exactly 11 bits. Why is a code always a multiple of three words? Because the entropy is a multiple of 32 bits and the checksum is a thirty-second of it, so the total is a multiple of 33 bits, that is of three words. Why can a wallet detect a mistyped word at all? Because the last few bits are not entropy but a hash of the rest."),
  (H, "The sections move in the direction the data flows. Entropy is the input and the only secret; the checksum is computed from it; the word list and the eleven-bit segment are the encoding; the code length is the arithmetic that ties the three together; and text normalisation is the rule that makes two spellings of the same words produce the same seed. A learner who has read the group can take 128 bits of hexadecimal and produce the twelve words a wallet would show, and can say which single word of a code carries bits of the checksum.")), None),

 ("Entropy", "Entropy", 3, "CodeGeneration", ("128 random bits in sixteen bytes",
   "Entropy is the unpredictability of a value, measured in bits; a BIP39 code encodes 128 to 256 bits of it, drawn by the wallet from a source of randomness and not chosen by a person.",
   ("len(bytes.fromhex('%s')) * 8" % ENT12, "128")), P(
  (W, "Entropy, in this chapter, is the amount of unpredictability in a value, counted in bits: a value with 128 bits of entropy is one that an attacker could only find by searching among 2 to the 128 equally likely possibilities. The chapter uses the word for the random input of the process, saying that the wallet starts from a source of entropy, adds a checksum and then maps the entropy to a word list, and that step one is to create a random sequence, which it glosses as entropy, of 128 to 256 bits [AH]. The standard requires that this entropy be a multiple of 32 bits and says that with more entropy security is improved but the sentence length increases [B39]."),
  (Y, "Entropy is the one quantity that decides whether a wallet can be guessed, and it cannot be added later. The chapter's opening example makes the point about repeatability rather than secrecy: a hash function always produces the same output for the same input, but if the input changes even slightly the output is different, and if the function is cryptographically secure nobody should be able to predict the new output, not even if they know the new input [AH]. All of that holds only if the first value was unpredictable; a seed derived from a guessable value is guessable however many times it is hashed."),
  (E, "A reader meets entropy at the first moment a wallet is created, usually invisibly. The chapter's own demonstration reads bytes from the operating system's random device and hashes them to produce a seed, printing the 64 hexadecimal digits of the result [AH]. The worked example takes the chapter's own 128-bit entropy value and counts it: sixteen bytes, each of eight bits, make the 128 bits that the first table of the chapter labels entropy input [AH]. Chapter 4 of the book discussed the same requirement for a single private key, where the entropy comes from a cryptographically secure random source."),
  (H, "The mechanism of interest is how little entropy is needed to produce a great deal of key material. The chapter explains that a hash function lets one take one random value and transform it into a practically unlimited number of seemingly random values, and that using the same function with the same input, called a seed, produces the same seemingly random values again [AH]. The entropy of the seed is therefore the entropy of the whole wallet: no derivation step adds any, because every later value is a function of the seed. The sidebar on how much entropy is needed works through the consequences of that fact in numbers."),
  (K, "Two misconceptions are worth naming. The first is that longer is always better: the chapter's sidebar concludes that there is no apparent benefit to using more than 128 bits of entropy, because the security strength of a Bitcoin public key is 128 bits, while noting one secondary benefit of more entropy if part of a code is seen by an attacker [AH]. The second is that entropy is a property of the value: it is a property of how the value was produced, so a 128-bit number a person invented has far less than 128 bits of entropy, which is the point of the brainwallet section of the previous branch [AH] [B39].")), None),

 ("Bip39Checksum", "BIP39 checksum", 3, "CodeGeneration", ("the first four bits of a SHA-256 hash",
   "The BIP39 checksum is the first entropy-length over 32 bits of the SHA-256 hash of the entropy, appended to it, so that a mistyped code can be detected but not corrected.",
   ("bin(__import__('hashlib').sha256(bytes.fromhex('%s')).digest()[0])[2:].zfill(8)[:4]" % ENT12, "'0111'")), P(
  (W, "A checksum is a short value computed from data and stored with it, so that a later reader can recompute it and notice if the data has changed. The BIP39 checksum is defined exactly: create a checksum of the random sequence by taking the first entropy-length divided by 32 bits of its SHA-256 hash, and add the checksum to the end of the random sequence [AH] [B39]. For the 128-bit entropy of the chapter's table that is 128 over 32, four bits, and the worked example computes them: the first byte of the hash written in binary, cut to four digits, is 0111."),
  (Y, "The checksum is what turns a long string of words from a secret into a secret that can be typed back. Without it, any twelve words from the list would be a valid code and a single wrong word would silently produce a different wallet. With it, software can tell the user that the code is wrong before deriving anything, and the standard requires exactly that: although using a sentence not generated by the standard's own procedure is possible, this is not advised, and software must compute a checksum for the sentence using a word list and issue a warning if it is invalid [B39]."),
  (E, "A reader meets the checksum in two places. The first is the arithmetic of the chapter's table, where the checksum column grows with the entropy: 4 bits for 128, 5 for 160, 6 for 192, 7 for 224 and 8 for 256 [AH]. The second is a wallet's refusal to accept a code that was typed wrongly. Because the checksum is computed from the entropy and not from the words, and because its own bits become part of the last word, the detection is of the whole code and not of one word in isolation."),
  (H, "The mechanism is a hash function used as a compressor. SHA-256 maps the entropy to 32 bytes; the leading bits of that output are taken, however many are needed; and they are appended so that the total length is a multiple of 11. For the 12-word case the entropy contributes 128 bits, which is 11 segments of 11 bits plus 7 bits left over, and the four checksum bits complete the twelfth segment, so the last word of a 12-word code carries 7 bits of entropy and 4 bits of checksum. A wrong word therefore changes both the data and the value being checked, which is why the error is noticed."),
  (K, "The standard is candid that this checksum is weak, and the reason is its length. It lists as a shortcoming that the checksum is short, so it gives only modest odds of catching random errors, with about one error in 256 missed, and that it is not able to provide any assistance in correcting errors [B39]. Four bits for a 12-word code are weaker still. A student should therefore not treat a valid checksum as proof that a code is the right one, only as evidence that it was probably typed correctly; and should notice that this is precisely the gap that codex32's error-correcting checksum was designed to close [B93].")), None),

 ("WordList", "Word list", 3, "CodeGeneration", ("2,048 words, eleven bits each",
   "The BIP39 word list holds exactly 2,048 words, so that each word stands for 11 bits; the list is sorted, has unique four-letter prefixes and avoids similar pairs.",
   ("2 ** 11", "2048")), P(
  (W, "The word list is the dictionary against which the bits of a code are read. The chapter's step five says to map each 11-bit value to a word from the predefined dictionary of 2,048 words [AH]. The number is not a round decimal but a round binary one: the worked example shows that 2 to the 11th is 2,048, so one word carries exactly 11 bits and no bits are wasted. The list used by every English BIP39 wallet is the one in the standard's repository, a copy of which is saved for this chapter and read by its claims [B39]."),
  (Y, "The list is what makes the code transcribable, and its design decides how often transcription fails. The standard sets out the criteria of an ideal list: a smart selection of words such that the first four letters identify a word unambiguously; similar words avoided, because pairs such as build and built, woman and women, or quick and quickly are harder to remember and more error-prone and easier to guess; and a sorted list, which lets implementations use binary search and allows a prefix tree to be used [B39]. Each criterion is a defence against a human error rather than an attacker."),
  (E, "A reader meets the list every time a wallet shows or accepts words. The chapter's example code, army van defense carry jealous true garbage claim echo media make crunch, is twelve of its entries, and the worked examples of this branch look them up by index: 96 is army and 423 is crunch, the first and last words of that code [AH] [B39]. The list is shared beyond BIP39: SLIP39 uses its own list of 1,024 words with its own criteria, while Aezeed encodes its ciphertext with the default BIP39 English list [S39] [AZ]."),
  (H, "The mechanism is a plain lookup in both directions. To write a code, the bits are cut into 11-bit groups and each group's value, a number from 0 to 2,047, selects the word at that position; to read a code, each word's position is found and written back as 11 bits [B39]. Because the list is a fixed, ordered sequence, the mapping is exact and reversible, and because the first four letters are unique, a wallet can accept abbreviations and still recover the full word. The list must be encoded in UTF-8 using normalisation form compatibility decomposition, which the normalisation section explains [B39]."),
  (K, "Dependence on the list is the scheme's best-known weakness. The standard says that because the words rather than the entropy are hashed to make the seed, translating a code to a different list necessarily creates a completely different seed, and therefore strongly discourages non-English lists, adding that if one is needed an existing list should be used rather than a new one invented [B39]. Electrum's document calls the requirement plainly inconsistent, since BIP39 still needs the list in order to compute its checksum even though keys and addresses were deliberately made independent of it [EL]. A learner should treat the English list as part of the backup.")), None),

 ("BitSegment", "Eleven-bit segment", 3, "CodeGeneration", ("the first three segments of the book's code",
   "The entropy and checksum are read as consecutive groups of 11 bits, each group a number from 0 to 2,047 that selects one word of the list.",
   ("[int(%s[i:i + 11], 2) for i in range(0, 33, 11)]" % _B128, "[96, 1929, 459]")), P(
  (W, "An eleven-bit segment is one group of the bit string that becomes one word. The chapter's step four is to split the result, meaning the entropy with its checksum appended, into 11-bit length segments, and step five maps each segment's value to a word [AH]. The standard says the same with the arithmetic attached: the concatenated bits are split into groups of 11 bits, each encoding a number from 0 to 2,047, serving as an index into a word list [B39]."),
  (Y, "The segment is where a reader can see that a recovery code is not a sentence but a number written in a strange base. Each word is a digit in base 2,048, and the whole code is one large integer, the entropy, with a few check digits at the end. Seeing this removes the temptation to think of the words as independently meaningful, which matters because it explains why the order of the words is as important as the words themselves and why one wrong word invalidates the code."),
  (E, "A reader meets the segments when checking a code by hand, which the worked example does for the book's own code: the 128 bits of the entropy 0c1e24e5917779d297e14d45f14e1a1a begin 00001100000, 11110001000, 00100111001, and those three values, 96, 1929 and 459, select army, van and defense, the first three words the chapter prints [AH] [B39]. The same bit-slicing appears in the other schemes with different widths: SLIP39 uses 10-bit segments against a list of 1,024 words, and codex32 uses 5-bit characters of the bech32 alphabet [S39] [B93]."),
  (H, "The mechanism is positional, and the boundaries do not respect byte boundaries. Eleven does not divide eight, so a segment generally straddles two bytes of the entropy, which is why an implementation works on a bit string rather than on bytes. For a 12-word code the first 11 segments use 121 of the 128 entropy bits and the twelfth segment takes the remaining 7 entropy bits together with the 4 checksum bits, which is the arithmetic the checksum section describes from the other side."),
  (K, "Two traps are common here. The first is to assume that each word corresponds to a fixed part of the entropy in a way that lets a single word be corrected independently: it does not, because the segments overlap byte boundaries and the last segment mixes entropy with checksum. The second is to read the segments from the hexadecimal digits directly: hexadecimal digits are four bits and a segment is eleven, so the conversion has to go through the full bit string, which is what the worked example does.")), None),

 ("CodeLength", "Code length", 3, "CodeGeneration", ("the chapter's entropy and word-length table",
   "Entropy length, checksum length and word count are tied together: the checksum is a thirty-second of the entropy and the total divided by 11 is the number of words, so codes have 12, 15, 18, 21 or 24 words.",
   ("[(e, e // 32, (e + e // 32) // 11) for e in (128, 160, 192, 224, 256)]",
    "[(128, 4, 12), (160, 5, 15), (192, 6, 18), (224, 7, 21), (256, 8, 24)]")), P(
  (W, "The length of a recovery code is not a free choice: it is determined by the amount of entropy. The chapter prints the relation as a table with four columns, entropy in bits, checksum in bits, entropy plus checksum, and recovery code words, whose five rows run from 128 bits and 12 words to 256 bits and 24 words [AH]. The standard gives the same table with two formulas above it: the checksum length is the entropy over 32, and the number of words is the entropy plus the checksum over 11 [B39]."),
  (Y, "The table answers the question a user actually asks, which is what the number of words tells them. A 12-word code means 128 bits of entropy; a 24-word code means 256. Because the formulas are fixed, the word count is a reliable statement about the strength of the backup, and a code of a length not in the table is not a BIP39 code at all. For software the same arithmetic is a cheap validity test before any hashing is done."),
  (E, "A reader meets the lengths as wallet options. The chapter says that a wallet shows a sequence of 12 to 24 words when first creating a wallet, and its own tables use 12 words for the 128-bit example and 24 for the 256-bit one [AH]. The figures also appear in the comparison with the other schemes: Electrum version 2 accepts 132 bits, which is 12 words of 11 bits with no checksum of its own; Aezeed encodes 33 bytes as 24 words; SLIP39's 128-bit secret becomes 20 words of 10 bits [AH] [EL] [AZ] [S39]."),
  (H, "The worked example computes the chapter's whole table from the two formulas, and the agreement is exact for all five rows. The reason the word counts come out whole is that the entropy is a multiple of 32: if the entropy is 32 times some number k, the checksum is k bits and the total is 33k, which 11 divides. That is also why codes grow in steps of three words, from 12 to 15 to 18 to 21 to 24, and why no 13-word BIP39 code exists."),
  (K, "A longer code is not automatically a better one. The chapter's sidebar explains that BIP32 extended private keys consist of a 256-bit key and a 256-bit chain code, so at most 512 bits of entropy can be held, that only slightly fewer than 2 to the 256 regular private keys exist, and that the security strength of a Bitcoin public key is 128 bits, from which it concludes that there is no apparent benefit beyond 128 bits [AH]. It also reports that as of 2023 most modern wallets generate 128 bits, or a value near it such as Electrum's 132 [AH]. The practical consequence is that a 12-word code is not a weak backup.")), None),

 ("TextNormalization", "Text normalisation", 3, "CodeGeneration", ("one character, two code points",
   "Normalisation rewrites text in a single canonical form before it is hashed, so that two spellings a person cannot distinguish produce the same bytes and therefore the same seed.",
   ("(len('\\u00e9'), len(__import__('unicodedata').normalize('NFKD', '\\u00e9')))", "(1, 2)")), P(
  (W, "Text normalisation is the operation that rewrites a piece of text in one agreed form before it is used as data. It is needed because the same visible characters can be stored in more than one way: the worked example takes the single character e with an acute accent, which is one code point, and shows that after normalisation form compatibility decomposition it is two, a plain e followed by a combining accent. BIP39 requires exactly this form, saying that the word list may contain native characters but they must be encoded in UTF-8 using normalisation form compatibility decomposition, abbreviated NFKD [B39]."),
  (Y, "Without the rule, two wallets could disagree about a code that looks identical on both screens. The seed is derived by hashing the text of the words and the text of the passphrase, and a hash function gives a different output for different bytes, however similar they look. The requirement therefore protects the one property the whole scheme rests on, that the same words always give the same seed, and it matters most for the localised word lists and for passphrases, which may contain any characters at all."),
  (E, "A reader meets normalisation in the derivation step: the standard says that the sentence, in UTF-8 NFKD, is used as the password and the string mnemonic plus passphrase, again in UTF-8 NFKD, as the salt [B39]. Electrum has a rule of its own with the same purpose and a different shape: its preparation function removes all but one space between words, removes diacritics, and removes spaces between Asian characters before the phrase is hashed [EL]. SLIP39 avoids the problem for passphrases by requiring them to contain only printable ASCII characters [S39]."),
  (H, "The mechanism is a standard mapping applied character by character. Compatibility decomposition replaces each precomposed character by its parts and rewrites compatibility characters into their ordinary equivalents, and the result is a sequence of code points that is the same whatever form the input took. In Python the operation is one call in the standard library's unicodedata module, which the worked example uses; a wallet applies it to the words and to the passphrase just before they are given to the key-stretching function."),
  (K, "The rule is easy to forget and its failures are silent, because a wrong normalisation gives a valid-looking seed for an empty wallet, exactly like a mistyped passphrase. The checksum does not help, since it is computed over the entropy rather than the text. For a course the safe habit is the one BIP39's own test vectors enforce: the Japanese vectors exist specifically to test heavily normalised symbols in the passphrase, and any implementation that passes them has got the rule right [B39].")), None),

 ("SeedDerivation", "From the code to the seed", 2, "Bip39Stack", None, P(
  (W, "This group covers the last three of BIP39's nine steps, the ones that turn words back into the number a wallet actually uses. The chapter states them in order: the first parameter to the PBKDF2 key-stretching function is the entropy produced from step six; the second is a salt composed of the string constant mnemonic concatenated with an optional user-supplied passphrase; and PBKDF2 stretches these using 2,048 rounds of hashing with the HMAC-SHA512 algorithm, producing a 512-bit value as its final output, which is the seed [AH]."),
  (Y, "The group matters because this is the step at which a passphrase can be added, and because it is the step most often misunderstood. The output is not the entropy that went in: it is 512 bits derived from it, and the derivation is one-way, which is why an arbitrary BIP32 seed cannot be written as a BIP39 code [B39]. The number of rounds is also the only defence against an attacker who knows part of a code, and the chapter is careful about how much that defence is worth."),
  (H, "The sections of the group go from the general to the particular and then to the consequences. Key stretching is the idea of making a derivation deliberately slow; PBKDF2 is the function BIP39 chooses; the salt is the second input, which is where the passphrase enters; the root seed is the 512-bit result; the passphrase has its own section because the chapter gives it one; and the security strength section works through the sidebar's argument about how much entropy is actually useful. Every number in the group is recomputed by a worked example from the chapter's own tables.")), None),

 ("KeyStretchingFunction", "Key-stretching function", 3, "SeedDerivation", ("2,048 rounds against 32,768",
   "A key-stretching function derives a key from a secret deliberately slowly, by repeating a hash many times, so that each guess an attacker makes costs more.",
   ("32768 // 2048", "16")), P(
  (W, "A key-stretching function is a function that turns a secret, typically one with limited entropy, into a key, and that is made deliberately expensive to compute. The chapter introduces it when it says that the entropy is used to derive a longer, 512-bit seed through the use of the key-stretching function PBKDF2, and that the function takes two parameters, the entropy and a salt [AH]. The word stretching refers to the cost rather than to the length: the output could be produced far more cheaply, and is not."),
  (Y, "The purpose is to raise the price of guessing. The chapter explains what this does and does not buy: the function, with its 2,048 rounds of hashing, makes it slightly harder to brute-force the recovery code using software, while special-purpose hardware is not significantly affected; for an attacker who must guess an entire code, the 128-bit minimum length already provides more than sufficient security; but where an attacker learns a small part of a user's code, key stretching adds some security by slowing down how fast combinations can be checked [AH]. Stretching is therefore a defence for the partially-compromised case."),
  (E, "A reader meets stretching in every scheme of the first branch, with different parameters, and the differences are the chapter's own comparison. BIP39 uses 2,048 rounds and the chapter says its parameters were considered weak by modern standards even when it was published almost a decade earlier, likely a consequence of being designed for compatibility with hardware signing devices with low-powered processors; some alternatives use stronger parameters, such as Aezeed's 32,768 rounds of the more complex scrypt algorithm, although these may be less convenient on such devices [AH]. The worked example is that ratio: 32,768 over 2,048 is 16 times the work."),
  (H, "The mechanism is iteration. A single hash is cheap, so the function applies the underlying operation again and again, each round depending on the previous one, so that the total cost is the number of rounds times the cost of one round, for the defender once and for the attacker once per guess. Newer functions add a second dimension: scrypt is specified as a password-based key derivation function based on memory-hard functions, which its specification says offer added protection against attacks using custom hardware, the very hardware the chapter says BIP39's round count does not slow down [R7914] [AH]."),
  (K, "Stretching cannot rescue a weak secret, and the chapter's own figures show why: multiplying an attacker's work by 2,048 is worth about 11 bits of entropy, which is useful beside 64 bits of a half-seen code and irrelevant beside 128 bits of a full one. It also costs the honest user time on every restoration, which is the reason the parameters were chosen low. A learner should read a round count as a statement about the designers' expectations of the attacker's hardware, and should notice that codex32 omits stretching entirely so that the scheme can be computed by hand [B93].")), None),

 ("Pbkdf2", "PBKDF2", 3, "SeedDerivation", ("the book's first seed, recomputed",
   "PBKDF2 is the standard password-based key derivation function that BIP39 uses: it applies HMAC-SHA512 2,048 times to the words and the salt and returns 64 bytes.",
   (PROG(PBKDF2 + "result = seed(b'%s', b'mnemonic').hex()[:16]" % MN12), "'5b56c417303faa3f'")), P(
  (W, "PBKDF2 is the second password-based key derivation function of the PKCS #5 standard, and it is the particular key-stretching function BIP39 names. Its specification defines it as applying a pseudorandom function to derive keys, with four inputs: a password, a salt, an iteration count and the intended length of the derived key in octets, and says it is recommended for new applications [R8018]. BIP39 fixes all four: the sentence is the password, the string mnemonic followed by the passphrase is the salt, the iteration count is 2,048, HMAC-SHA512 is the pseudorandom function, and the derived key is 512 bits, that is 64 bytes [B39]."),
  (Y, "Naming a standard function rather than inventing one is what makes a recovery code portable. Any implementation with a correct PBKDF2 produces the same seed from the same words, which is why a code written by one wallet can be read by another, and why this course can reproduce the book's tables with nothing but Python's standard library. Python's documentation describes its own function in the same terms, as providing the PKCS #5 password-based key derivation function 2, using HMAC as a pseudorandom function [PY]."),
  (E, "The worked example is the chapter's first table, recomputed: the twelve words army van defense carry jealous true garbage claim echo media make crunch, with the salt mnemonic and 2,048 iterations of HMAC-SHA512, give a seed that begins 5b56c417303faa3f, exactly the value the chapter prints [AH]. The claims of this chapter check all 64 bytes of that seed and of the chapter's other two tables, and they also reproduce the example in Python's own documentation, which uses SHA-256, a different salt and 500,000 iterations [PY]."),
  (H, "The mechanism is HMAC applied in a chain. HMAC is the keyed hash of RFC 2104, which computes its output as the hash of the key combined with an outer pad together with the hash of the key combined with an inner pad and the message [R2104]. PBKDF2 computes the first HMAC over the salt and a block counter, then applies HMAC repeatedly to the previous output, and combines all the intermediate values by exclusive-or; the result is as long as the hash, and further blocks are produced for longer keys. With SHA-512 one block is 64 bytes, which is exactly the length BIP39 wants, so a BIP39 seed is one such chain of 2,048 links. The worked example writes that chain out with the keyed hash rather than calling the standard library's own function for it, because the Python of the course's browser pages is built without that function; a claim of this chapter checks that the two give the same seed."),
  (K, "Two details matter in practice. The first is the order of the arguments: the words are the password and the salted constant is the salt, and swapping them produces a valid-looking but wrong seed, which no checksum will catch. The second is that PBKDF2's security rests on the password: its specification notes that the salt's purpose is to make precomputation infeasible, not to add secrecy, since the salt is assumed to be known [R8018]. The chapter's own judgement on the parameters, that they were weak even when published, applies to the iteration count and not to the function [AH].")), None),

 ("Salt", "Salt", 3, "SeedDerivation", ("the constant mnemonic, with or without a passphrase",
   "A salt is the second, non-secret input of a key derivation function; BIP39's salt is the string mnemonic followed by the optional passphrase, which is how the passphrase changes the seed.",
   (PROG(PBKDF2 + "result = seed(b'x', b'mnemonic') == seed(b'x', b'mnemonicSuperDuperSecret')"), "False")), P(
  (W, "A salt is a value that is combined with a secret before a key is derived from it, in order to make the derivation specific to that salt. The chapter explains the general purpose first: the purpose of a salt in a key-stretching function is to make it difficult to build a lookup table enabling a brute-force attack; and then the particular use BIP39 makes of it: in this standard the salt has another purpose, as it allows the introduction of a passphrase that serves as an additional security factor protecting the seed [AH]. The standard states the value exactly: the salt is the string mnemonic plus the passphrase, both in normalised UTF-8 [B39]."),
  (Y, "The first purpose is the classical one. The specification of PBKDF2 explains it with a number: a salt serves to produce a large set of keys for a given password, one of which is selected at random according to the salt, so that it is difficult for an opponent to precompute all the keys, or even the most likely keys, corresponding to a dictionary of passwords; with a 64-bit salt there are as many as 2 to the 64 keys for each password [R8018]. The second purpose, carrying the passphrase, is BIP39's own and is what makes a single code able to stand for many wallets."),
  (E, "A reader meets the salt as a string that is almost always the same. With no passphrase it is the eight characters mnemonic, which the chapter says produces a specific 512-bit seed from any given recovery code; with a passphrase it is mnemonic followed by that passphrase, and the chapter says the stretching function then produces a different seed from the same code [AH]. The worked example shows the effect with the chapter's own passphrase: the same password under the two salts gives two different outputs, so the comparison is false."),
  (H, "Mechanically the salt is simply the second argument, and PBKDF2 feeds it into the first HMAC of its chain together with a block counter [R8018]. Because it enters the first link, a change of one character changes every later link and therefore the whole output: there is no part of the seed that depends only on the words. That is why the chapter can say that every possible passphrase leads to a different seed, and why the set of wallets reachable from one code is as large as the set of possible passphrases [AH]."),
  (K, "BIP39's use of the salt breaks one of the salt's usual properties, and a reader should notice it. A classical salt is random and stored beside the derived key, so that two users with the same password get different keys; BIP39's salt is a fixed constant when no passphrase is used, so every wallet in the world uses the same salt, and the protection against precomputed tables comes from the 128 bits of entropy in the words rather than from the salt. The specification's recommendation that a salt should be at least eight random octets is therefore not met, and does not need to be met, in this one special case [R8018].")), None),

 ("RootSeed", "Root seed", 3, "SeedDerivation", ("512 bits, that is 64 bytes",
   "The root seed is the value from which every key of a hierarchical deterministic wallet is derived; BIP39 produces one of 512 bits, and BIP32 accepts 128 to 512.",
   ("512 // 8", "64")), P(
  (W, "The root seed is the single number that stands for a whole wallet. The chapter introduces it at the head of the section on creating a hierarchical deterministic wallet: such wallets are created from a single root seed, which is a 128-, 256- or 512-bit random number, and most commonly this seed is generated by or decrypted from a recovery code [AH]. The book's glossary gives the same definition in one line, calling the HD wallet seed or root seed a potentially short value used as a seed to generate the master private key and master chain code for an HD wallet [AHG]."),
  (Y, "The seed is the object that backups are really about. The chapter says that every key in the wallet is deterministically derived from this root seed, which makes it possible to re-create the entire wallet from that seed in any compatible wallet, and so makes it easy to back up, restore, export and import wallets containing thousands or even millions of keys by transferring only the recovery code that the seed is derived from [AH]. One short number therefore replaces an unbounded list of keys, which is the whole gain of determinism."),
  (E, "A reader meets the seed as the output of the previous sections and the input of the next branch. BIP39 always produces 512 bits of it, which the worked example counts as 64 bytes, and BIP32 is more permissive: it asks for a seed of a chosen length between 128 and 512 bits, advising 256, generated from a random number generator [B32]. The chapter's sidebar notes that BIP32 allows seeds from 128 to 512 bits while the schemes feed it between 128 and 256 bits of entropy [AH]."),
  (H, "What happens to the seed is the subject of the next branch, and one sentence of it belongs here: the root seed is given to HMAC-SHA512 and the resulting hash is used to create a master private key and a master chain code [AH] [B32]. Nothing else in the wallet is random. The seed's length matters only up to the size of that one operation's input, which is why BIP32 observes that the total number of possible extended key pairs is almost 2 to the 512 while the keys themselves are only 256 bits long and offer about half of that in terms of security, and concludes that master keys are generated from a potentially short seed value instead [B32]."),
  (K, "The seed and the recovery code are not the same object, and the difference matters when software is chosen. The code is an encoding of the entropy; the seed is the stretched result; the mapping from code to seed is one-way, so a wallet that imports a seed directly cannot show the user words for it [B39]. A wallet that asks for a seed in hexadecimal and a wallet that asks for words are therefore asking for different things, and giving the wrong one produces an empty wallet with no warning.")), None),

 ("Bip39Passphrase", "Optional passphrase in BIP39", 3, "SeedDerivation", ("the book's second seed, recomputed",
   "In BIP39 the optional passphrase is appended to the constant salt, so any passphrase yields a different valid seed from the same words and none of them is wrong.",
   (PROG(PBKDF2 + "result = seed(b'%s', b'mnemonicSuperDuperSecret').hex()[:16]" % MN12), "'3b5df16df2157104'")), P(
  (W, "The optional passphrase of BIP39 is a user-supplied string that is appended to the salt of the key derivation. The chapter devotes a section to it: the standard allows the use of an optional passphrase in the derivation of the seed, and if none is used the code is stretched with a salt consisting of the constant string mnemonic, producing a specific 512-bit seed from any given code; if a passphrase is used, the stretching function produces a different seed from that same code [AH]. The previous branch discussed the choice; this section is about the mechanism and its arithmetic."),
  (Y, "The consequence the chapter emphasises is that the passphrase cannot be validated. Given a single recovery code, every possible passphrase leads to a different seed; essentially there is no wrong passphrase; all passphrases are valid and they all lead to different seeds, forming a vast set of possible uninitialised wallets, and the set is so large, 2 to the 512, that there is no practical possibility of brute-forcing or accidentally guessing one that is in use [AH]. The chapter repeats the point as a tip: every passphrase leads to some wallet, which unless previously used will be empty [AH]."),
  (E, "The worked example is the chapter's second table, recomputed from its inputs: the same twelve words, with the passphrase SuperDuperSecret appended to the constant salt, give a seed beginning 3b5df16df2157104, where the same words with no passphrase gave 5b56c417303faa3f [AH]. A claim of this chapter checks all 64 bytes of both, and a further claim shows that four different passphrases give four different seeds, none of which is signalled as wrong."),
  (H, "The mechanism is a string concatenation inside the salt and nothing more: the salt is the eight characters mnemonic followed by the passphrase, both normalised, and the words remain the password [B39]. No separate field records whether a passphrase was used, and no checksum covers it, which is why the chapter groups BIP39 with Electrum version 2 and SLIP39 as schemes that do not include the passphrase in their checksum [AH]. Aezeed, by enciphering rather than salting, is able to authenticate it instead [AZ]."),
  (K, "The risks are the ones the previous branch set out, and they are worth repeating where the mechanism is visible. A forgotten passphrase is an unrecoverable loss, because nothing in the code hints at it; a passphrase stored with the code is no second factor at all; and a mistyped passphrase shows an empty wallet rather than an error [AH]. The chapter's closing advice on the subject is that passphrases are very useful but should be used only in combination with a carefully planned process for backup and recovery [AH].")), None),

 ("SecurityStrength", "Security strength", 3, "SeedDerivation", ("512, 256 and 128 bits",
   "Security strength is the work an attacker needs, measured in bits; extended keys hold 512 bits, private keys 256, and the elliptic curve offers about 128, so more than 128 bits of entropy buys little.",
   ("[(2 ** 512).bit_length() - 1, (2 ** 256).bit_length() - 1, (2 ** 128).bit_length() - 1]", "[512, 256, 128]")), P(
  (W, "Security strength is the amount of work an attacker needs in order to break something, expressed as a number of bits: a strength of 128 bits means about 2 to the 128 operations. The chapter's sidebar asks how much entropy a user needs and answers it with three such numbers. Extended private keys consist of a 256-bit key and a 256-bit chain code, for a total of 512 bits, so there are at most 2 to the 512 different extended private keys; there are only slightly fewer than 2 to the 256 regular private keys, and it is those that secure the bitcoins; and the security strength of a Bitcoin public key is 128 bits [AH]."),
  (Y, "The question is practical, because the schemes disagree. The chapter opens the sidebar by noting that the variation in these numbers makes it unclear how much entropy is needed for safety, and promises to demystify it [AH]. The answer has consequences a student can act on: a 12-word code is not a compromise, a 24-word code is not twice as strong, and the choice between them is not where attention should go."),
  (E, "The reasoning is met in three steps that the sidebar takes in turn. Starting with more than 512 bits of entropy still gives an extended private key containing 512 bits, so there is no point in more than 512; using more than 256 bits still gives private keys containing only 256 bits of entropy, and the chapter adds that there may be future protocols where extra entropy in the extended keys provides extra security but that this is not currently the case; and because an attacker with a classical computer would need about 2 to the 128 operations on Bitcoin's curve to find a private key for another user's public key, there is no apparent benefit to more than 128 bits of entropy, as long as the generated private keys are selected uniformly from the whole range [AH]. The worked example is those three numbers."),
  (H, "The mechanism behind the 128 is the mathematics of the curve, which chapter 4 of the book introduced: the best known attacks on the discrete logarithm problem for a 256-bit curve cost about the square root of the group size, that is about 2 to the 128 operations, and BIP32 repeats the figure when it states its own assumptions, saying that given a public key an attacker cannot find the private key more efficiently than by solving the elliptic curve discrete logarithm problem, assumed to require 2 to the 128 group operations [B32]. A seed with more than 128 bits of entropy therefore protects a key whose public form can be attacked with 2 to the 128 work."),
  (K, "The sidebar names one real benefit of more entropy and warns against relying on it: if a fixed percentage of a code, but not the whole code, is seen by an attacker, more entropy makes the unseen part harder, so half of a 128-bit code, 64 bits, is plausibly brute-forcible while half of a 256-bit code is not; but the chapter does not recommend relying on this defence and advises either keeping codes very safe or distributing them with a scheme such as SLIP39 [AH]. The other caution is that these are strengths against computation, not against coercion or data loss, which are the risks the rest of the chapter addresses.")), None),
]

CHECKS_C = [
 Qb("ch05_wallets.adoc", "BIP39 defines the creation of a recovery code and seed, which we\ndescribe here in nine steps",
    "1. Create a random sequence (entropy) of 128 to 256 bits.", "2. Create a checksum of the random sequence by taking the first\n(entropy-length/32) bits of its SHA256 hash.",
    "3. Add the checksum to the end of the random sequence.", "4. Split the result into 11-bit length segments.",
    "5. Map each 11-bit value to a word from the predefined dictionary of\n2,048 words.", "6. The recovery code is the sequence of words.",
    "The wallet starts from a source\nof entropy, adds a checksum, and then maps the entropy to a word list"),
 Qb("ch05_wallets.adoc", "All of these standards have been around since 2014 or earlier"),
 Qe("bip-0039.mediawiki", "The conversion of the mnemonic sentence to a binary seed is completely independent from generating the sentence",
    "software must compute a checksum for the mnemonic sentence using a wordlist and issue a warning if it is invalid",
    "With more entropy security is improved but the sentence length increases"),
 # entropy / checksum / word list / segments
 ("len(bytes.fromhex('%s')) * 8" % ENT12, "128"),
 ("bin(__import__('hashlib').sha256(bytes.fromhex('%s')).digest()[0])[2:].zfill(8)[:4]" % ENT12, "'0111'"),
 ("bin(__import__('hashlib').sha256(bytes.fromhex('2041546864449caff939d32d574753fe684d3c947c3346713dd8423e74abcf8c')).digest()[0])[2:].zfill(8)", "'11000001'"),
 ("2 ** 11", "2048"),
 ("[int(%s[i:i + 11], 2) for i in range(0, 33, 11)]" % _B128, "[96, 1929, 459]"),
 ("[int((%s + bin(__import__('hashlib').sha256(bytes.fromhex('%s')).digest()[0])[2:].zfill(8)[:4])[i:i + 11], 2) for i in range(0, 132, 11)]" % (_B128, ENT12),
  "[96, 1929, 459, 279, 956, 1866, 764, 333, 559, 1107, 1076, 423]"),
 ("11 * 11", "121"), ("128 - 121", "7"), ("7 + 4", "11"),
 ("[(e, e // 32, (e + e // 32) // 11) for e in (128, 160, 192, 224, 256)]", "[(128, 4, 12), (160, 5, 15), (192, 6, 18), (224, 7, 21), (256, 8, 24)]"),
 ("[(e + e // 32) % 11 for e in (128, 160, 192, 224, 256)]", "[0, 0, 0, 0, 0]"),
 X("len(W.wordlist())", "2048"),
 X("(W.wordlist()[96], W.wordlist()[423], W.wordlist()[0], W.wordlist()[2047])", "('army', 'crunch', 'abandon', 'zoo')"),
 X("len({w[:4] for w in W.wordlist()})", "2048"),
 X("W.wordlist() == sorted(W.wordlist())", "True"),
 X("W.entropy_to_mnemonic(bytes.fromhex('%s'))" % ENT12, "'%s'" % MN12),
 X("W.mnemonic_to_entropy('%s') == (bytes.fromhex('%s'), True)" % (MN12, ENT12), "True"),
 X("W.mnemonic_to_entropy('%s')[1]" % MN12.replace("crunch", "cruise"), "False"),     # one wrong word: the checksum fails
 Qb("ch05_wallets.adoc", "0C1E 24E5 9177 79D2 97E1 4D45 F14E 1A1A", "army van defense carry jealous true", "garbage claim echo media make crunch"),
 Qb("ch05_wallets.adoc", "<td><p>128</p></td>", "<td><p>4</p></td>", "<td><p>132</p></td>", "<td><p>12</p></td>", "<td><p>256</p></td>", "<td><p>8</p></td>", "<td><p>264</p></td>", "<td><p>24</p></td>"),
 Qb("ch05_wallets.adoc", "A hash function will always produce the same output when given the same\ninput", "This allows us to take one random value and transform it into a\npractically unlimited number of seemingly random values"),
 # normalisation
 Qe("bip-0039.mediawiki", "The wordlist can contain native characters, but they must be encoded in UTF-8 using Normalization Form Compatibility Decomposition (NFKD)",
    "Japanese wordlist test with heavily normalized symbols as passphrase"),
 ("(len('é'), len(__import__('unicodedata').normalize('NFKD', 'é')))", "(1, 2)"),
 ("__import__('unicodedata').normalize('NFKD', 'é') == 'é'", "True"),
 ("__import__('hashlib').sha256('é'.encode()).hexdigest() == __import__('hashlib').sha256(__import__('unicodedata').normalize('NFKD', 'é').encode()).hexdigest()", "False"),
 Qe("electrum_seeds.rst", "The normalization function (prepare_seed) removes all but one space between words. It also removes diacritics, and it removes spaces between Asian CJK characters"),
 Qe("slip-0039.md", "the passphrase MUST be a string containing only printable ASCII characters (code points 32-126)"),
 # key stretching / PBKDF2 / salt
 Qb("ch05_wallets.adoc", "The entropy is then\nused to derive a longer (512-bit) seed through the use of the",
    "key-stretching function PBKDF2", "The key-stretching function takes two\nparameters: the entropy and", "a _salt_. The purpose of a salt in a\nkey-stretching function is to make it difficult to build a lookup table\nenabling a brute-force attack",
    "it allows the introduction of a passphrase that\nserves as an additional security factor protecting the seed"),
 Qb("ch05_wallets.adoc", "The key-stretching function, with its 2,048 rounds of hashing, makes it\nslightly harder to brute-force attack the recovery code using software.\nSpecial-purpose hardware is not significantly affected",
    "BIP39's parameters were\nconsidered weak by modern standards even when it was first published\nalmost a decade ago",
    "designed for compatibility with hardware signing devices with low-powered\nCPUs"),
 Qb("ch05_wallets.adoc", "The salt is composed of the string constant\n  \"<code>mnemonic</code>\" concatenated with an optional user-supplied\n  passphrase string",
    "PBKDF2 stretches the recovery code and salt parameters using 2,048\n  rounds of hashing with the HMAC-SHA512 algorithm, producing a 512-bit\n  value as its final output. That 512-bit value is the seed"),
 Qe("bip-0039.mediawiki", "we use the PBKDF2 function with a mnemonic sentence (in UTF-8 NFKD) used as the password and the string \"mnemonic\" + passphrase (again in UTF-8 NFKD) used as the salt",
    "The iteration count is set to 2048 and HMAC-SHA512 is used as the pseudo-random function", "The length of the derived key is 512 bits (= 64 bytes)"),
 Qe("rfc8018.txt", "PBKDF2 applies a pseudorandom function (see Appendix B.1 for an example) to derive keys", "PBKDF2 is recommended for new applications",
    "PBKDF2 (P, S, c, dkLen)", "P password, an octet string", "S salt, an octet string", "c iteration count, a positive integer",
    "A salt in password-based cryptography has traditionally served the purpose of producing a large set of keys corresponding to a given password, one of which is selected at random according to the salt",
    "It is difficult for an opponent to precompute all the keys, or even the most likely keys, corresponding to a dictionary of passwords",
    "If the salt is 64 bits long, for instance, there will be as many as 2^64 keys for each password", "It should be at least eight octets (64 bits) long"),
 Qe("rfc2104.txt", "To compute HMAC over the data `text' we perform", "H(K XOR opad, H(K XOR ipad, text))"),
 Qe("rfc7914.txt", "This document specifies the password-based key derivation function scrypt",
    "It is based on memory-hard functions, which offer added protection against attacks using custom hardware"),
 Qe("python_hashlib.rst", "pbkdf2_hmac(hash_name, password, salt, iterations, dklen=None)", "The function provides PKCS#5 password-based key derivation function 2. It uses HMAC as pseudorandom function",
    "dk = pbkdf2_hmac('sha256', b'password', b'bad salt' * 2, our_app_iters)", "'15530bba69924174860db778f2c6f8104d3aaf9d26241840c8c4a641c8d000a9'"),
 ("__import__('hashlib').pbkdf2_hmac('sha256', b'password', b'bad salt' * 2, 500000).hex()", "'15530bba69924174860db778f2c6f8104d3aaf9d26241840c8c4a641c8d000a9'"),
 ("32768 // 2048", "16"), ("(2048).bit_length() - 1", "11"),
 (PROG(PBKDF2 + "import hashlib as _h\nresult = all(seed(w, t) == _h.pbkdf2_hmac('sha512', w, t, 2048) for w in (b'x', b'" + MN12.encode().decode() + "') for t in (b'mnemonic', b'mnemonicSuperDuperSecret'))"), "True"),
 ("len(__import__('hashlib').pbkdf2_hmac('sha512', b'x', b'mnemonic', 2048))", "64"), ("512 // 8", "64"),
 ("__import__('hashlib').pbkdf2_hmac('sha512', b'x', b'mnemonic', 2048) == __import__('hashlib').pbkdf2_hmac('sha512', b'x', b'mnemonicSuperDuperSecret', 2048)", "False"),
 # the three tables of the chapter, in full
 Qb("ch05_wallets.adoc", "<code>0c1e24e5917779d297e14d45f14e1a1a</code>", "<code>5b56c417303faa3fcba7e57400e120a0ca83ec5a4fc9ffba757fbe63fbd77a89a1a3be4</code>",
    "<code>c67196f57c39a88b76373733891bfaba16ed27a813ceed498804c0570</code>", "SuperDuperSecret",
    "<code>3b5df16df2157104cfdd22830162a5e170c0161653e3afe6c88defeefb0818c793dbb28</code>", "<code>ab3ab091897d0715861dc8a18358f80b79d49acf64142ae57037d1d54</code>",
    "<code>2041546864449caff939d32d574753fe684d3c947c3346713dd8423e74abcf8c</code>",
    "<code>3269bce2674acbd188d4f120072b13b088a0ecf87c6e4cae41657a0bb78f5315b33b3</code>", "<code>a04356e53d062e55f1e0deaa082df8d487381379df848a6ad7e98798404</code>"),
 ("__import__('hashlib').pbkdf2_hmac('sha512', b'%s', b'mnemonic', 2048).hex()" % MN12,
  "'5b56c417303faa3fcba7e57400e120a0ca83ec5a4fc9ffba757fbe63fbd77a89a1a3be4c67196f57c39a88b76373733891bfaba16ed27a813ceed498804c0570'"),
 ("__import__('hashlib').pbkdf2_hmac('sha512', b'%s', b'mnemonicSuperDuperSecret', 2048).hex()" % MN12,
  "'3b5df16df2157104cfdd22830162a5e170c0161653e3afe6c88defeefb0818c793dbb28ab3ab091897d0715861dc8a18358f80b79d49acf64142ae57037d1d54'"),
 X("W.entropy_to_mnemonic(bytes.fromhex('2041546864449caff939d32d574753fe684d3c947c3346713dd8423e74abcf8c'))",
   "'cake apple borrow silk endorse fitness top denial coil riot stay wolf luggage oxygen faint major edit measure invite love trap field dilemma oblige'"),
 X("W.mnemonic_to_seed('cake apple borrow silk endorse fitness top denial coil riot stay wolf luggage oxygen faint major edit measure invite love trap field dilemma oblige').hex()",
   "'3269bce2674acbd188d4f120072b13b088a0ecf87c6e4cae41657a0bb78f5315b33b3a04356e53d062e55f1e0deaa082df8d487381379df848a6ad7e98798404'"),
 ("len({__import__('hashlib').pbkdf2_hmac('sha512', b'%s', b'mnemonic' + p, 2048) for p in (b'', b'a', b'b', b'SuperDuperSecret')})" % MN12, "4"),
 # root seed and strength
 Qb("ch05_wallets.adoc", "HD wallets are created from a", "single _root seed_, which is a\n128-, 256-, or 512-bit random number",
    "Every key in the HD wallet is deterministically derived from this root\nseed", "by simply transferring only the recovery code that the root\nseed is derived from"),
 Qb("ch05_wallets.adoc", "BIP32 extended private keys consist of a 256-bit key and a 256-bit chain\ncode, for a total of 512 bits",
    "there are only (slightly less than) 2^256^ regular private keys", "The security strength of a Bitcoin public key is 128 bits",
    "would need to perform about 2^128^\noperations on Bitcoin's elliptic curve in order to find a private key\nfor another user's public key",
    "there's no apparent benefit to using more than 128\nbits of entropy", "if an attacker sees half of a\n128-bit code (64 bits), it's plausible that they'll be able to brute\nforce the remaining 64 bits",
    "As of 2023, most modern wallets generate 128 bits of entropy for their\nrecovery codes"),
 Qe("bip-0032.mediawiki", "Generate a seed byte sequence S of a chosen length (between 128 and 512 bits; 256 bits is advised) from a (P)RNG",
    "The total number of possible extended keypairs is almost 2<sup>512</sup>, but the produced keys are only 256 bits long, and offer about half of that in terms of security",
    "an attacker cannot find the corresponding private key more efficiently than by solving the EC discrete logarithm problem (assumed to require 2<sup>128</sup> group operations)"),
 Qb("glossary.asciidoc", "HD wallet seed or root seed is a potentially-short value used as a seed to generate the master private key and master chain code for an HD wallet"),
 ("[(2 ** 512).bit_length() - 1, (2 ** 256).bit_length() - 1, (2 ** 128).bit_length() - 1]", "[512, 256, 128]"),
 ("(2 ** 64) ** 2 == 2 ** 128", "True"),
 Pp("Chapter_5_Wallets_v1_0_0.pptx", "Generating mnemonic words", "From mnemonic to seed", "Root Seed, Master Key, Chain Code"),
]
