"""SEN0401 chapter 4, corpus text part B (version 1.1.0): the curve and the hash functions."""
from sen0401_ch04_text_a_v1_1_0 import W, Y, E, H, K, KHEX, NHEX, YHEX
import os as _os
# the point arithmetic of the chapter's toolkit, put into the worked example as a literal so that the same program
# runs in the reader's browser (which has no access to the file) and under the interpreter that checks it here
_ECSRC = open(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), "sen0401_ch04_keys_v1_1_0.py"),
              encoding="utf-8").read().split("# --- ec ---")[1].split("# --- end ec ---")[0].strip()
ECIO = ("(lambda src: (len(src.splitlines()), len(src.splitlines()) < 20))(%r)" % _ECSRC, "(13, True)")
BOOKP ="(lambda p, x, y: (x ** 3 + 7 - y ** 2) % p)(115792089237316195423570985008687907853269984665640564039457584007908834671663, 55066263022277343669578718895168534326250603453777594175500187360389116729240, 32670510020758816978083085130507043184471273380659243275938904335757337482424)"
SMALLADD = "(lambda a, b, p: (lambda m: (lambda x: (x, (m * (a[0] - x) - a[1]) % p))((m * m - a[0] - b[0]) % p))((b[1] - a[1]) * pow(b[0] - a[0], -1, p) % p))((1, 5), (2, 7), 17)"

NODES_B = [
 ("Curve", "The curve", 2, "Keys", None, [
  (W, "The curve is the mathematical object on which Bitcoin's public key cryptography is built. Elliptic curve cryptography, abbreviated ECC, is a type of asymmetric or public key cryptography based on the discrete logarithm problem as expressed by addition and multiplication on the points of an elliptic curve [BK]. This level of the chapter gathers everything that is needed to understand that sentence: the arithmetic of a finite field, the curve itself, the way points are added, the particular curve that Bitcoin uses and the standard that defines it, the generator point, multiplication of a point by a number, and the problem that makes the whole construction hard to reverse."),
  (Y, "A reader who only wants to use Bitcoin can treat the conversion from private key to public key as a black box, but a reader who wants to judge the security of Bitcoin cannot. Every claim of the form 'the public key does not reveal the private key' rests on the properties of this one curve. The book therefore spends a section on it, and it notes that the math is identical whether the curve is drawn over the real numbers, shown over a small finite field or taken over the enormous field that Bitcoin uses [BK]."),
  (H, "The sections of this level move from the general to the specific. The finite field and the elliptic curve are the general objects, and point addition is the one operation defined on them. The secp256k1 curve and its standard are the specific choices that Bitcoin made, and the generator point is the one point from which every public key is reached. Multiplication of a point by a whole number is built from addition, the discrete logarithm is its hard inverse, and the cryptographic library is the software in which all of it is implemented. Small curves over the field with 17 elements serve as worked examples, because a student can check every value by hand."),
 ], None),
 ("FiniteField", "Finite field", 3, "Curve", ("arithmetic modulo a prime", "A finite field of prime order p is the whole numbers from 0 to p - 1 with addition, subtraction, multiplication and division carried out modulo p; division by 5 modulo 17 is multiplication by 7.", ("pow(5, -1, 17)", "7")), [
  (W, "A finite field of prime order p, written F_p, is the set of whole numbers from 0 to p minus 1 together with the four arithmetic operations, in which every result is replaced by its remainder after division by p. The book writes the remainder operation as 'mod p' and says that it indicates that the curve is over a finite field of prime order p [BK]. Because the remainder always lies between 0 and p minus 1, the numbers never grow beyond the size of p, and every non-zero number has a partner by which it can be multiplied to give 1."),
  (Y, "The elliptic curve of Bitcoin is defined over a finite field instead of over the real numbers, and this choice is what makes it usable in software. Real numbers have to be rounded by a computer, whereas arithmetic modulo a prime is exact. The price is that the curve no longer looks like a smooth line. The book remarks that because the curve is defined over a finite field of prime order, it looks like a pattern of dots scattered in two dimensions, which makes it difficult to visualise, although the math is identical to that of an elliptic curve over real numbers [BK]."),
  (E, "Modular arithmetic is met outside cryptography as well, in clocks, in check digits and in the checksums of this chapter's later sections. In Bitcoin it appears whenever a coordinate of a point is calculated, and the prime in question is p = 2 to the 256 minus 2 to the 32 minus 2 to the 9 minus 2 to the 8 minus 2 to the 7 minus 2 to the 6 minus 2 to the 4 minus 1, a very large prime number [BK]. The standard gives the same prime in hexadecimal, as FFFFFFFF followed by repeated groups of F and ending in FFFFFC2F, and in the same long form [SEC2]. Written more briefly it is 2 to the 256 minus 2 to the 32 minus 977, an equality that the chapter's checks verify."),
  (H, "In Python the operator % gives the remainder, and pow(a, -1, p) gives the number by which a must be multiplied, modulo p, to obtain 1. In the field with 17 elements the partner of 5 is 7, because 5 times 7 is 35 and 35 leaves the remainder 1 when divided by 17; the chapter's checks confirm that every number from 1 to 16 has such a partner. Division by a is defined as multiplication by its partner. That operation, the modular inverse, is what the slope calculation in point addition needs, and the toolkit of this chapter uses exactly this call to add points on the real curve."),
  (K, "A finite field is not a number line, so ordinary intuitions about size and order fail: 16 is not 'greater' than 1 in any useful sense once results wrap around. The prime matters, too. A probabilistic primality test confirms that Bitcoin's p is prime, and with a modulus that is not prime some numbers would have no inverse. Finally, remember that p is only slightly smaller than 2 to the 256, the size of a private key, but it is a different number from n, the order of the curve; the two are easily confused."),
 ]),
 ("EllipticCurve", "Elliptic curve", 3, "Curve", ("y squared = x cubed + 7", "An elliptic curve is the set of points (x, y) that satisfy an equation such as y squared = x cubed + 7, together with a point at infinity; over the field with 17 elements the curve y squared = x cubed + 7 has 17 points besides the point at infinity.", ("sum(1 for x in range(17) for y in range(17) if (y * y - x ** 3 - 7) % 17 == 0)", "17")), [
  (W, "An elliptic curve is the set of all points (x, y) whose coordinates satisfy an equation of a particular form, together with one extra point called the point at infinity. The curve of Bitcoin has the equation y squared = x cubed + 7, which the book writes as y squared mod p = (x cubed + 7) mod p because the arithmetic is carried out in a finite field [BK]. In the notation of the standard the equation is y squared = x cubed + ax + b, and for this curve a is 0 and b is 7 [SEC2]."),
  (Y, "The reason for choosing such a curve is that its points can be added to one another by a simple rule, so that the points form a system on which multiplication by a whole number is easy to compute and its inverse is believed hard. Those two properties together give Bitcoin its one-way function. The curve is not valuable for its shape but for the algebra that its points obey."),
  (E, "Over the real numbers the curve is a smooth line, drawn in the book as a figure that is symmetric about the x-axis, which is to say that it is reflected like a mirror by the axis [BK]. Over a finite field it becomes a scatter of dots on a grid. The book shows the same equation over the field with 17 elements, and the chapter's checks find that it has exactly 17 points whose coordinates are whole numbers from 0 to 16, which together with the point at infinity makes 18. Bitcoin's own curve is, in the book's words, a much more complex pattern of dots on an unfathomably large grid [BK]."),
  (H, "To check that a point lies on the curve you substitute its coordinates into the equation. The book gives a point P with two 77-digit coordinates and shows in Python that x cubed plus 7 minus y squared leaves the remainder 0 when divided by p, so the point is on the curve [BK]; the chapter's checks reproduce that result. A point whose coordinates do not give 0 is not a valid public key. For every point (x, y) on the curve the point (x, minus y) is also on the curve, which is the symmetry about the x-axis in the finite world: in the field with 17 elements the point (1, 5) has the mirror image (1, 12), since 17 minus 5 is 12."),
  (K, "The word 'elliptic' is misleading, because the curve is not an ellipse. Do not take the smooth picture literally for Bitcoin, either: it explains the geometry of addition, but the real curve has only whole-number points modulo p and the lines of the drawing do not exist there. The book is careful on this point and says that the math is the same, which is why the drawing remains a faithful guide [BK]."),
 ]),
 ("PointAddition", "Point addition and the point at infinity", 3, "Curve", ("(1, 5) + (2, 7) = (1, 12)", "Two points of the curve are added by drawing a line through them, finding the third intersection and reflecting it in the x-axis; the point at infinity plays the role of zero.", (SMALLADD, "(1, 12)")), [
  (W, "Point addition is the operation by which two points of an elliptic curve are combined into a third point of the same curve. Given two points P1 and P2, there is a third point P3 = P1 + P2, also on the curve; the book describes it geometrically: draw a line between P1 and P2, which will intersect the curve in exactly one additional place, call that point P3' = (x, y), and then reflect it in the x-axis to get P3 = (x, minus y) [BK]. The curve also contains the point at infinity, which roughly corresponds to the role of zero in addition."),
  (Y, "Addition is the only operation that has to be defined, because everything else in elliptic curve cryptography is built from it. Multiplication of a point is repeated addition, the public key is such a multiple, and the verification of a signature adds points. That the rule yields a third point of the curve, and not a point somewhere else in the plane, is what makes the curve a closed system. The book adds that the addition is associative, so that A + B + C can be written without parentheses and without ambiguity [BK]."),
  (E, "In the field with 17 elements the points of the curve y squared = x cubed + 7 can be added by hand. Adding (1, 5) and (2, 7) gives (1, 12). Adding (1, 5) to itself gives (2, 10). Adding (1, 5) and (1, 12), two points with the same x value and different y values, gives the point at infinity. Adding the point at infinity to any point gives that point back. The chapter's checks confirm each of these sums and also the associativity rule on an example; they use the same rules that the toolkit applies to the big curve."),
  (H, "There are special cases, and the book explains why they require the point at infinity. If P1 and P2 are the same point, the line between them is replaced by the tangent to the curve at that point, which intersects the curve in exactly one new point; the techniques of calculus find its slope, and they work even though the points have whole-number coordinates. If P1 and P2 have the same x value but different y values, the line is vertical and the result is the point at infinity. If P1 is the point at infinity, then P1 + P2 = P2, and the same holds with the roles exchanged, which shows how the point at infinity plays the role of zero [BK]. In software the point at infinity is sometimes represented by x = y = 0, which does not satisfy the curve equation but is an easy separate case to check for [BK]."),
  (K, "The formulas that software uses are algebraic, not geometric, and they work in the finite field with modular division, so the picture of a line crossing a curve must not be taken literally. The chapter's toolkit shows the cost of care: each case, doubling, inverse points and the point at infinity, needs its own branch, and a mistake in one of them produces points that are not on the curve and public keys that nobody can use. This is one more reason to rely on a well-tested library in practice."),
 ]),
 ("Secp256k1", "The secp256k1 curve", 3, "Curve", ("y squared = x cubed + 7 over F(p)", "The secp256k1 curve, y squared = x cubed + 7 over the prime field with p = 2 to the 256 minus 2 to the 32 minus 977, is defined in SEC 2 by Certicom Research and is not a NIST-recommended curve.", (BOOKP, "0")), [
  (W, "The name secp256k1 identifies the specific elliptic curve and the set of constants that Bitcoin uses. The curve is y squared = x cubed + 7 over a finite field of prime order p, with p = 2 to the 256 minus 2 to the 32 minus 2 to the 9 minus 2 to the 8 minus 2 to the 7 minus 2 to the 6 minus 2 to the 4 minus 1 [BK]. The standard that defines it specifies the parameters as a sextuple of the prime p, the coefficients a and b, the base point G, the order n of G and the cofactor h, which the standard defines as the number of points of the curve divided by n; for secp256k1 the coefficient a is 0, the coefficient b is 7 and the cofactor is 1, which means that the points of the curve are exactly the multiples of G [SEC2]."),
  (Y, "Every Bitcoin public key is a point on this one curve, and every Bitcoin signature is checked against it. Fixing a single curve and a single generator point means that all participants perform the same calculation and obtain the same answer from the same private key. The choice also fixes the security level: the standard's table of properties gives secp256k1 a security strength of 128 bits for a field size of 256 bits [SEC2], and that figure, not the 256 bits of the key itself, is the amount of work an attacker is estimated to need."),
  (E, "The name is met in the documentation of every Bitcoin library, in the title of the Schnorr signature standard, which is called Schnorr Signatures for secp256k1 [B340], and in the book's remark that Bitcoin uses a specific curve and set of constants as defined in a standard called secp256k1 [BK]. The name is also a small code. In the words of the standard, each name begins with sec to denote Standards for Efficient Cryptography, followed by p to denote parameters over a prime field, a number for the length in bits of the field size, a k for parameters associated with a Koblitz curve or an r for verifiably random parameters, and a sequence number [SEC2]."),
  (H, "To use the curve in a program one needs only p, the generator G and the order n. The chapter's checks verify the book's example point P against the equation, compute p from its short form, and confirm that the generator point lies on the curve and that adding it to itself n times gives the point at infinity. They also parse the constants from the standard's text and compare them with the toolkit's constants, so that the numbers used in this chapter are the standard's and not copies from memory."),
  (K, "One statement in the book does not match its source. The book says that secp256k1 was established by the National Institute of Standards and Technology, but the curve is defined in SEC 2, Standards for Efficient Cryptography, published by Certicom Research in 2010, and the status table in that document marks secp256k1 with a dash in the NIST column, meaning not conformant with the NIST list, while secp256r1 is marked r, explicitly recommended [SEC2]. The error is easy to repeat and matters when a reader is asked whether Bitcoin's curve was chosen by a government agency: according to the standard it is not one of the curves on the NIST list."),
 ]),
 ("CurveStandard", "Curve standard (SEC 2 and NIST)", 3, "Curve", ('secp256k1 and secp256r1', 'SEC 2 lists recommended curve parameters with a table of which other standards each conforms to; secp256k1 is marked as not on the NIST list and secp256r1 is marked as recommended by it.', ("(lambda table: [(n, nist) for n, sec, nist in table if n.startswith('secp256')])([('secp192k1', '2.2.1', '-'), ('secp192r1', '2.2.2', 'r'), ('secp224k1', '2.3.1', '-'), ('secp224r1', '2.3.2', 'r'), ('secp256k1', '2.4.1', '-'), ('secp256r1', '2.4.2', 'r')])", "[('secp256k1', '-'), ('secp256r1', 'r')]")), [
  (W, "A curve standard is a published document that fixes the constants of an elliptic curve so that independent programmers obtain the same curve. The standard behind Bitcoin is SEC 2, Recommended Elliptic Curve Domain Parameters, version 2.0, published on 27 January 2010 by Certicom Research under the name Standards for Efficient Cryptography [SEC2]. It lists recommended parameters over prime fields in several sizes, from 192 to 521 bits, and gives each set of parameters a nickname such as secp256k1 or secp256r1."),
  (Y, "A curve is not safe merely because it has a name. Choosing the coefficients and the generator point is a decision that the user of the curve cannot check without help, which is why standards distinguish between parameters associated with a Koblitz curve, marked k, and parameters chosen verifiably at random, marked r [SEC2]. The standard also records how each set of parameters aligns with other standards, which tells a reader who else supports the curve and who recommends it."),
  (E, "The alignment table is Table 2 of the document. Its columns name other standards: ANSI X9.62, ANSI X9.63, echeck, IEEE P1363, IPSec, NIST and WAP. A dash denotes parameters not conformant with the standard of that column, the letter c denotes conformant parameters and the letter r denotes parameters explicitly recommended in the standard [SEC2]. In the NIST column secp256k1 has a dash and secp256r1 has an r, which is the evidence for the correction in the previous concept. The chapter's checks read the table rows from the text of the standard."),
  (H, "To trace a curve to its source, one starts from the name and looks for its section in the standard. Section 2.4.1 specifies secp256k1 and section 2.4.2 specifies secp256r1 [SEC2]. The parameters appear as hexadecimal numbers, and the prime p is also given as 2 to the 256 minus 2 to the 32 minus 2 to the 9 minus 2 to the 8 minus 2 to the 7 minus 2 to the 6 minus 2 to the 4 minus 1, the form the book uses. Anyone implementing the curve can check a copy of the constants against this text."),
  (K, "A standards document is a draft or a version at a given date, and the table reflects the status at that date. SEC 2 version 2.0 labels itself a draft in its page headers, so statements about 'the NIST list' should be read as statements about the list that the document refers to. When a textbook and a primary document disagree, the primary document is the better evidence for what it says itself, and the discrepancy is worth reporting rather than silently correcting."),
 ]),
 ("GeneratorPoint", "Generator point", 3, "Curve", ('G, the same for every key', 'The generator point G is the fixed point of the secp256k1 standard from which every public key is reached by multiplication; adding it to itself n times gives the point at infinity.', ("(lambda x, y: ('02' if y % 2 == 0 else '03') + format(x, '064x'))(0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798, 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8)", "'0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798'")), [
  (W, "The generator point, written G, is the predetermined point on the curve by which a private key is multiplied to give the public key. It is specified as part of the secp256k1 standard and is always the same for all keys in Bitcoin [BK]. The standard gives it in compressed form as 02 followed by the x coordinate 79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798, and in uncompressed form as 04 followed by that x coordinate and a y coordinate of 256 bits [SEC2]."),
  (Y, "Because the generator point is the same for every Bitcoin user, a private key k multiplied by G will always result in the same public key K [BK]. That uniqueness lets any two programs agree on the public key without exchanging any information about it. The same property is what lets this chapter's toolkit reproduce the public key that the book prints for its example private key."),
  (E, "The generator appears wherever a public key is derived from a private key and wherever a signature is verified. The book pictures the process as starting from G and doubling it: its figure shows G, 2G and 4G as a geometric operation on the curve [BK]. In the standard, G is paired with n, the order of G, and a cofactor h of 1, the ratio between the number of points of the curve and n, which says that the curve holds no points besides the multiples of G [SEC2]."),
  (H, "The order n is the number of times G must be added to itself to arrive at the point at infinity. The chapter's checks confirm for the standard's n that n times G is the point at infinity, that n minus 1 times G is the mirror image of G, and that n is prime. The first of these facts means that private keys beyond n minus 1 would only repeat earlier public keys, which is why the valid private keys are the numbers from 1 to n minus 1. The second says that the multiples of G form a loop of exactly n members, of which the public keys are the members other than the point at infinity."),
  (K, "The generator is public and standard, so it contributes nothing to secrecy; the secrecy is entirely in the multiplier. A reader should also not confuse the generator point G with the base point of a different curve, nor with a public key: G is a constant of the standard, while a public key is a multiple of G chosen by a private key."),
 ]),
 ("PointMultiplication", "Elliptic curve multiplication", 3, "Curve", ("double and add", "Multiplying a point by a whole number k means adding it to itself k times, which the double-and-add method does in about 256 doublings and additions; for the book's key it is 252 doublings and 123 additions.", ("(" + "0x" + KHEX + ".bit_length() - 1, bin(0x" + KHEX + ").count('1') - 1)", "(252, 123)")), [
  (W, "Elliptic curve multiplication takes a point P and a whole number k and produces kP, which is defined as P + P + P + ... + P with k terms. The book defines multiplication in the standard way that extends addition, and notes that k is sometimes confusingly called an exponent in this case [BK]. In Bitcoin the point is the generator point and the multiplier is the private key, so the public key is K = k times G."),
  (Y, "This single operation is the heart of Bitcoin's cryptography. It is easy in one direction and impossible, for any practical purpose, to reverse: the book calls it a trap door function, which is easy to do in one direction, multiplication, and impossible to do in the reverse direction, division [BK]. Someone with a private key can easily create the public key and share it knowing that no one can reverse the function and calculate the private key from the public key; the same trick makes unforgeable digital signatures possible."),
  (E, "The book illustrates multiplication on the curve over the real numbers: adding a point to itself corresponds to drawing the tangent at the point, finding where it intersects the curve again, and reflecting that point in the x-axis, and its figure shows G, 2G and 4G obtained this way [BK]. In real software the multiplication is performed by a library, such as libsecp256k1, which many Bitcoin implementations use for the elliptic curve math [BK]."),
  (H, "Adding G to itself k times, where k is a 256-bit number, would be impossible. The double-and-add method avoids it by reading the bits of k. Starting from the leading bit, the method doubles the running point for every further bit and adds P whenever the bit is 1. For the book's example key, which has 253 bits of which 124 are set, this means 252 doublings and 123 additions, a few hundred operations instead of an astronomically large number; the chapter's checks compute these counts and verify that the toolkit's result for this key matches the public key printed in the book. They also check that (a + b) times G equals aG plus bG for sample multipliers, which is the algebraic law the method relies on."),
  (K, "Multiplication is the fast direction only. The reverse calculation, finding k when K is known, is the discrete logarithm problem described in the next concept. Also do not confuse point multiplication with multiplying two points, which is not defined: the multiplier is always a plain whole number. Finally, the fact that a short loop of additions suffices for the forward direction does not make the chapter's toolkit safe for real use; its own description says so, and the concept on cryptographic libraries returns to the point."),
 ]),
 ("DiscreteLogarithm", "Discrete logarithm and brute-force search", 3, "Curve", ("finding k from K", "Finding the multiplier k from K = kG is the discrete logarithm problem; with no shortcut it is as hard as trying every value of k, a brute-force search; in a toy group modulo 101 it takes 9 tries to find that 2 to the power 9 leaves 7.", ("next(k for k in range(1, 101) if pow(2, k, 101) == 7)", "9")), [
  (W, "The discrete logarithm problem asks for the multiplier when the product is known. In elliptic curve terms: given the public key K and the generator point G, find the private key k with K = kG. The book calls this reverse operation 'finding the discrete logarithm' and says that it is as difficult as trying all possible values of k, that is, a brute-force search [BK]. A brute-force search is simply the method of trying every candidate in turn until one fits."),
  (Y, "The whole security of Bitcoin's ownership rule rests on the difficulty of this problem. If anyone could compute k from K, every public key that has ever appeared on the blockchain would reveal its private key, and anyone could spend anyone's coins. This is why the book calls elliptic curve multiplication a one-way function and bases the entire scheme on it [BK]."),
  (E, "The same pattern of an easy forward step and a hard reverse step occurs in the exponentiation of prime numbers that the book names as another suitable function [BK], and it can be seen in a small group. In the numbers modulo 101, raising 2 to the power 9 gives 7. Going backwards, from 7 to the exponent 9, requires trying exponents one after another until one fits, and the chapter's check does exactly that and stops at 9. Every step of the forward direction is a single call of pow, while the reverse direction needs a search."),
  (H, "For a private key of 256 bits the number of candidates is about 10 to the 77, far more than any computer could try. The standard's table of properties gives secp256k1 a security strength of 128 bits for a 256-bit field, which it describes as the approximate number of bits of security the parameters offer [SEC2]. That figure is half of the 256-bit field size, so the book's statement that the problem is as difficult as brute force over all values of k is best read as a simplification: a search over every key would correspond to 256 bits of security and not 128. The practical conclusion stands either way, because 2 to the 128 operations remain out of reach."),
  (K, "The difficulty of the discrete logarithm is an assumption about the present state of mathematics and computing, not a proved theorem. The book is careful to speak of what is infeasible 'using the computers and algorithms available today' [BK]. Reasoning from this assumption, a good habit is to make no stronger claim than the source does, and to keep in mind that the strength of 128 bits holds only if the private key is chosen at random from the full range."),
 ]),
 ("CryptoLibrary", "Cryptographic library (libsecp256k1)", 3, "Curve", ("libsecp256k1", "A cryptographic library is tested, reusable code for the elliptic curve math; the book notes that many Bitcoin implementations use libsecp256k1, and this chapter's toolkit is only a readable sketch of the same calculation.", ECIO), [
  (W, "A cryptographic library is a collection of ready-made routines for cryptographic calculations that programs call instead of writing the mathematics themselves. For the elliptic curve math of Bitcoin the book names the libsecp256k1 cryptographic library and observes that many Bitcoin implementations use it [BK]. The library carries out the point arithmetic, the multiplication and the signature operations of the curve that this level has just described."),
  (Y, "Cryptographic code must be exactly right, because an error that passes every ordinary test can still leak a key or accept a forged signature. The book's advice about random numbers shows the attitude: do not write your own code, study the documentation of the library you choose, and remember that correct implementation is critical to the security of the keys [BK]. The authors of the Schnorr signature standard make the same point about verification: to be safe for use in a consensus system, the verification algorithm must be completely specified at the byte level, so that nobody can construct a signature that is valid to some verifiers but not all [B340]."),
  (E, "The reference implementation of Chapter 3, Bitcoin Core, and the wrapper libraries that call it are the kind of shared software that Bitcoin users rely on; a cryptographic library is the same idea one level lower, below the wallet and the node. When a wallet developer in another language implements a wallet, the library is what ensures that every implementation derives the same public key from the same private key."),
  (H, "The toolkit that accompanies this chapter shows what such a library does. The point addition and multiplication of the curve take thirteen lines of Python, fewer than twenty, and with them the toolkit reproduces the public key of the book's example, the addresses of the later sections and the bech32 examples. Its results were compared with Bitcoin Core 31.1, which gave the same addresses for the same keys, and with the reference code that the book uses for bech32. A library does the same arithmetic with the care that production use demands."),
  (K, "The toolkit is written for reading. Its own description says that it is not for use with real funds, because it is not constant-time, which means that the time it takes depends on the key, and because it takes no care over where randomness comes from. Never copy educational code into a wallet. The comparison with independent software also shows how trust is built in this field: not by believing one implementation, but by checking that several independent ones agree."),
 ]),
 ("Hashing", "Hash functions", 2, "Keys", None, [
  (W, "A hash function is the second tool, next to the elliptic curve, from which Bitcoin addresses are built. This level introduces the general idea and the three functions the chapter uses: SHA256, RIPEMD-160 and the combination of the two that Bitcoin calls HASH160. Together they allow a long public key, or a script of thousands of bytes, to be replaced by a short and reliable fingerprint that can be copied, printed and checked."),
  (Y, "The book states the practical problem in these terms: Bitcoin already contains several data structures much larger than 65 bytes that need to be securely referenced in other parts of Bitcoin using the smallest amount of data that was secure [BK]. A hash function solves the problem of referring to a large object by a small one without losing the guarantee that the reference identifies exactly that object."),
  (H, "The sections below begin with the general notion of a hash function and the commitment it provides, then take SHA256 and RIPEMD-160 in turn, and end with HASH160, the way in which Bitcoin chains the two. The commitment itself, as it is used in addresses, is described later in the branch on legacy addresses, and the attacks that limit the strength of short hashes are described there as well."),
 ], None),
 ("HashFunction", "Hash function", 3, "Hashing", ("same input, same output", "A hash function takes a potentially large amount of data and outputs a fixed amount of data; a cryptographic hash function always gives the same output for the same input, and changing one bit of the input changes about half of the output bits.", ("bin(int(__import__('hashlib').sha256(b'a').hexdigest(), 16) ^ int(__import__('hashlib').sha256(b'`').hexdigest(), 16)).count('1')", "139")), [
  (W, "A hash function is a function that takes a potentially large amount of data, scrambles it (hashes it), and outputs a fixed amount of data. A cryptographic hash function will always produce the same output when given the same input, and a secure function also makes it impractical for somebody to choose a different input that produces a previously seen output [BK]. The standard that defines the SHA family describes its algorithms as ones that generate digests of messages, which are used to detect whether messages have been changed since the digests were generated [FIPS]."),
  (Y, "These two properties make the output a commitment to the input, which is a promise that, in practice, only input x will produce output X [BK]. The book illustrates this with a question whose answer is revealed later: it publishes the hash of its answer now, and after the guess has been made it shows that the answer, put into the hash function, gives exactly the published value. In Bitcoin the same trick lets a receiver publish a small commitment to a public key or a script and reveal the full object only when it is used."),
  (E, "Hash functions occur throughout this book. Chapter 1's proof of work is a search for an input whose hash has a required form, Chapter 3 verified that a downloaded release file has the published hash, and this chapter uses hashes for addresses and for checksums. The program command sha256sum, which the book uses in its example, computes one of them from the command line."),
  (H, "The chapter's checks show the behaviour on the book's own example. The sentence the book hashes, followed by the line break that the echo command adds, has the SHA256 value 94d7a772612c8f2f2ec609d41f5bd3d04a5aa1dfe3582f04af517d396a302e4e, as printed in the book, and the same input gives it every time. Two inputs that differ in a single bit, the letter a and the character just before it in the ASCII table, give outputs that differ in 139 of their 256 bits, a little more than the half that one would expect from an unrelated pair: a tiny change in the input scrambles the output completely, so a near-miss reveals nothing about the right input."),
  (K, "A hash is not an encryption: there is no key and no way to recover the input from the output except by guessing it. For the same reason it is not a good way to hide a small set of possible inputs. If the answer can only be one of a handful of years, anyone can hash all the candidates and compare, so a commitment hides a secret only when the set of possible secrets is huge. Finally, 'secure' is relative to output size: the shorter the output, the easier it is to find collisions, as the discussion of collision attacks later in the chapter shows."),
 ]),
 ("Sha256", "SHA256", 3, "Hashing", ("32 bytes of output", "SHA256 is the hash function most commonly used in Bitcoin; its output is 256 bits (32 bytes), and the SHA256 of the three bytes abc begins ba7816bf.", ("__import__('hashlib').sha256(b'abc').hexdigest()[:8]", "'ba7816bf'")), [
  (W, "SHA256 is the member of the SHA family that produces 256 bits (32 bytes) of output, and the book calls it the function most commonly used in Bitcoin and considers it to be very secure [BK]. Its output is less than half the size of the original Bitcoin public keys, which were 65 bytes [BK]; the chapter's checks confirm that 32 is smaller than half of 65."),
  (Y, "Bitcoin leans on SHA256 for many jobs. This chapter meets it as the first step of HASH160, as the double hash that gives base58check its checksum and as the function the book recommends for turning random bits into a private key candidate. Using one well-studied function in all these places keeps the system simple, and it means that a weakness in it would affect everything at once."),
  (E, "The command-line example in the book uses the tool sha256sum. Python offers the same function in its hashlib module, and the chapter's checks use it throughout. The hashlib module also provides functions of other families, but the Python that runs inside this course's browser pages has no RIPEMD-160, which is why some examples in this chapter are given as data."),
  (H, "The input can have any length and the output always has 32 bytes. The three-byte message abc has the SHA256 digest that begins ba7816bf, and the empty message and a message of a million bytes also give 32 bytes. The chapter's checks print the length for several inputs. Applying the function twice, as base58check does, is simply passing the 32-byte output as the input of a second call."),
  (K, "A 256-bit output does not mean 256 bits of security for every attack. For finding two inputs with the same hash the work is about the square root of the number of outputs, so the best case is 128 bits, and for the 160-bit RIPEMD-160 it is 80 bits; the book's discussion of collision attacks makes exactly this point [BK]. Choose the right function and the right question: preimage resistance, second preimage resistance and collision resistance are three different properties."),
 ]),
 ("Ripemd160", "RIPEMD-160", 3, "Hashing", ('20 bytes of output', 'RIPEMD-160 is a hash function with a 160-bit (20-byte) output; Bitcoin applies it to the SHA256 of a public key to obtain a 20-byte commitment.', ("(lambda d: (len(bytes.fromhex(d)), len(bytes.fromhex(d)) * 8))('bbc1e42a39d05a4cc61752d6963b7f69d09bb27b')", '(20, 160)')), [
  (W, "RIPEMD-160 is a hash function whose output is 160 bits (20 bytes). The book describes it as one of the other, slightly less secure hash functions that produce smaller output than SHA256 [BK]. Its place in Bitcoin is as the second step of the commitment to a public key, applied to the SHA256 digest of the key."),
  (Y, "A smaller output means a shorter address and a smaller transaction. The original version of Bitcoin made commitments to public keys by first hashing the key with SHA256 and then hashing that output with RIPEMD-160, which produced a 20-byte commitment, and the book adds that Satoshi Nakamoto never stated the reasons for this choice [BK]. The honest statement is therefore that the design is known and the motive is not."),
  (E, "RIPEMD-160 is met in Bitcoin in three kinds of place: the 20-byte commitments inside legacy addresses, the 20-byte witness programs of version 0 pay to witness public key hash outputs, and the commitments to scripts in pay to script hash outputs, all of which later sections describe. The checksums of the next branch use SHA256 alone, applied twice."),
  (H, "In Python the call hashlib.new('ripemd160', data) computes it where the underlying library supports the function, and the chapter's checks use it to reproduce the book's addresses. The course's browser pages do not provide it in their Python, so examples that depend on it are given as data there. Because it works on its input in the same way for every call, two parties that apply SHA256 and then RIPEMD-160 to the same public key obtain the same 20 bytes."),
  (K, "The size of the output limits security. The book states that for a secure 160-bit algorithm the chance of independently finding an input for an existing commitment is 1 in 2 to the 160, a preimage attack, but that when an attacker can influence the original input, the strength drops to the square root, 1 in 2 to the 80 [BK]. For this reason newer address types use SHA256 alone, which gives commitments of 32 bytes, as the later section on segwit outputs explains."),
 ]),
 ("Hash160", "HASH160", 3, "Hashing", ('RIPEMD160(SHA256(K))', "HASH160 is the RIPEMD-160 of the SHA256 of the data; for the book's compressed example key it is bbc1e42a39d05a4cc61752d6963b7f69d09bb27b, and the uncompressed form of the same key gives a different value.", ("(lambda c, u: (len(bytes.fromhex(c)), len(bytes.fromhex(u)), c == u))('bbc1e42a39d05a4cc61752d6963b7f69d09bb27b', '211b74ca4686f81efda5641767fc84ef16dafe0b')", '(20, 20, False)')), [
  (W, "HASH160 is the name of the combination RIPEMD160(SHA256(K)), in which a public key K, or any other data, is first passed into SHA256 and the resulting digest is then passed into RIPEMD-160. The book writes the formula A = RIPEMD160(SHA256(K)), where K is the public key and A is the resulting commitment, a 160-bit (20-byte) number [BK]. The name HASH160 is also that of the script operation OP_HASH160, which performs the same calculation inside a script."),
  (Y, "The combination gives Bitcoin a short, fixed-size reference to an object of any length. The same construction is used for both main legacy outputs: the commitment to a public key in a pay to public key hash output and the commitment to a script in a pay to script hash output, where the book says that it uses the same HASH160 mechanism, RIPEMD160(SHA256(script)) [BK]."),
  (E, "For the book's example private key the chapter's checks compute HASH160 of the compressed public key and obtain bbc1e42a39d05a4cc61752d6963b7f69d09bb27b, whose base58check form with version byte 0 is the address 1J7mdg5rbQyUHENYdx39WVWK7fsLpEoXZy. Hashing the uncompressed form of the same public key gives the different value 211b74ca4686f81efda5641767fc84ef16dafe0b and the different address 1424C2F4bC9JidNjjTUZCbUxv6Sa1Mt62x. The values match the output scripts that Bitcoin Core 31.1 reported when asked to validate the two addresses [CORE]."),
  (H, "The calculation is mechanical. Take the bytes of the public key, compute SHA256, compute RIPEMD-160 of that digest, and keep the 20 bytes that result. In an output script the operation OP_HASH160 replaces the top item of the stack by its HASH160, so that the comparison with a stored commitment can be made by the script itself, as the sections on legacy scripts show [BK]."),
  (K, "HASH160 commits to bytes, not to a mathematical point, so the same key written in two formats gives two different commitments. The book stresses that a single private key can produce a public key expressed in two formats, compressed and uncompressed, that produce two different addresses [BK]. The strength is that of a 160-bit function, no more, and the book recommends newer address types for this reason."),
 ]),
]
