"""SEN0401 chapter 7, corpus text part G (version 1.0.0): the branch 'Segregated witness scripts' - witness programs, pay to witness
public key hash and script hash, the bech32 addresses, the backward-compatible upgrade, the nested forms and the signature hash of
BIP143. Markers such as [AH] become author-year strings (sen0401_ch07_common). Every number is computed by the chapter's library."""
from sen0401_ch07_common_v1_0_0 import *

BK = "ch07_authorization-authentication.adoc"
HK = "751e76e8199196d454941c45d1b3a323f1433bd6"                     # HASH160 of the compressed generator point (BIP173's example key)
HB = "ab68025513c3dbd2f7b92a94e0581f5d50f654e7"                     # the key hash of the book's P2WPKH example
HNP = "3e0547268b3b19288b3adef9719ec8659f4b2b0b"                    # HASH160 of 0014<HB>, the book's nested P2WPKH script hash
WSH_N = "9592d601848d04b172905e0ddb0adde59f1590f1e553ffc81ddc4b0ed927dd73"      # the book's SHA-256 of a witness script (nested example)
HNW = "86762607e8fe87c0c37740cddee880988b9455b2"                    # HASH160 of 0020<WSH_N>
SCR173 = "210279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798ac"     # BIP173's P2WSH example script: <key> OP_CHECKSIG
SIGHASH_MODEL = '''import hashlib, struct
def h256(b): return hashlib.sha256(hashlib.sha256(b).digest()).digest()
def sighash(amount):                                   # BIP143 for a one-input, one-output transaction, hash type ALL
    outpoint = bytes(32) + struct.pack('<I', 0)
    script_code = bytes.fromhex('1976a914' + '11' * 20 + '88ac')
    outputs = struct.pack('<q', 50000) + bytes.fromhex('160014' + '22' * 20)
    return h256(struct.pack('<i', 2) + h256(outpoint) + h256(struct.pack('<I', 0xfffffffd)) + outpoint + script_code
                + struct.pack('<q', amount) + struct.pack('<I', 0xfffffffd) + h256(outputs) + struct.pack('<I', 0) + struct.pack('<I', 1))
'''

NODES_G = [
 ("SegwitScripts", "Segregated witness scripts", 1, None, None, P(
  (W, "This branch is about the outputs that came with segregated witness, the upgrade of 2017 that moved the proofs of authorization out of the part of a transaction that identifies it. A segregated witness output script is two pushes, a version number and a short program, and it is spent with a witness structure instead of an input script. The branch covers the two programs of version 0, pay to witness public key hash and pay to witness script hash, their addresses, the way old and new software live together, the nested forms, and the new signature hash [AH]."),
  (Y, "The upgrade matters because most of the bitcoin that moves today is spent this way. In the 1,022 inputs of block 775,072's first 599 transactions, 626 spend a native witness key hash output and 57 a native witness script hash output, and another 129 spend the same programs nested in a script hash, against 194 legacy key hash inputs: 812 of the 1,022 inputs, about 79 percent, are segwit forms [MP]. They are cheaper than their legacy equivalents, and they removed the signature from the data that a third party could change to alter a transaction identifier [B141]."),
  (E, "A reader meets the forms as addresses that begin with bc1q, or with 3 for the nested forms, and as the line in a decoded transaction where the witness appears after the outputs. The branch runs a real spend of every form with the library, so that each statement about what the engine does with a program is a result and not a description. All of it is backed by the specification BIP141 and the code of Bitcoin Core [BCI]."),
  (H, "The branch has two groups. The first, witness programs, defines the program and its two version-0 forms and the address format that carries them. The second, the upgrade, explains why old software accepts the new outputs, how the nested forms let a payer who knows nothing of segwit pay a segwit wallet, and what the new signature hash changes. The activation height of 481,824 and its date come from the saved block."),
 ), None),

 ("WitnessPrograms", "Witness programs and addresses", 2, "SegwitScripts", None, P(
  (W, "This group defines the new kind of output and shows its three faces: the output script, the witness that spends it, and the address that carries it. A witness program is a version and a hash; the hash is of a public key or of a script; and the address is a checksummed text that carries the same two things [AH] [B141] [B173]."),
  (Y, "The faces correspond to three kinds of reader. A node reads the output script, a wallet builds the witness, and a person reads and types the address. The design makes each face as simple as the job allows: the output script is shorter than its legacy equivalent, the witness holds exactly the data that the program needs, and the address is easier to read aloud and to scan than the legacy address."),
  (H, "The first section defines the program and the rule that decides what it means from its version and length; the second and third give the key hash and script hash forms with real spends and the failures that follow from breaking each rule; the fourth builds the address, with the algorithm in a few lines that the page runs."),
  (K, "A witness program is never created by converting a key or an address that was meant for something else. The book is explicit that the receiver must create it, since the sender cannot know whether the receiver's wallet can spend such an output. The same care applies to the choice of key: only a compressed public key is safe."),
 ), None),

 ("WitnessProgram", "Witness program", 3, "WitnessPrograms", ("OP_0 <20 bytes> or OP_0 <32 bytes>", "A witness program is an output script made of a version byte (OP_0, or OP_1 to OP_16) followed by one push of 2 to 40 bytes; the version and the length of the program decide how the output is spent.",
   (PROG("def kind(spk):                                 # BIP141: the version, then the length of the program\n    ver = 0 if spk[0] == 0 else spk[0] - 80\n    prog = spk[2:]\n    if ver == 0 and len(prog) == 20: return 'P2WPKH'\n    if ver == 0 and len(prog) == 32: return 'P2WSH'\n    if ver == 0: return 'fails'\n    return 'P2TR' if ver == 1 and len(prog) == 32 else 'future version'\nresult = [kind(bytes.fromhex(s)) for s in ('0014' + '11' * 20, '0020' + '22' * 32, '0013' + '33' * 19, '5120' + '44' * 32, '6003' + '55' * 3)]"), "['P2WPKH', 'P2WSH', 'fails', 'P2TR', 'future version']")), P(
  (W, "A witness program is what BIP141 calls an output script that consists of a one-byte push opcode, one of OP_0 and OP_1 to OP_16, followed by a direct data push between 2 and 40 bytes. The value of the first push is the version byte, and the following byte vector is the witness program. The book explains the same in its own words: to an old client the two pushes look like an output that anyone can spend, while to a segwit-aware client the first number is the witness version and the second part is the witness program [B141] [AH]."),
  (Y, "The definition is what lets one structure carry several kinds of authorization. With the version byte 0, the length of the program tells the two forms apart: 20 bytes is the hash of a key, 32 bytes the hash of a script, and any other length fails. Versions 1 to 16 are reserved for future extensions with no restriction: taproot is version 1. The book gives the length as the one difference that lets a full node tell the two version-0 programs apart [AH] [B141]."),
  (E, "Bitcoin Core's function IsWitnessProgram applies the rule: the script must be 4 to 42 bytes long, begin with OP_0 or OP_1 to OP_16, and have a second byte equal to the length of what follows. The page's example classifies five scripts by the rule: a 20-byte program is P2WPKH, a 32-byte one P2WSH, a 19-byte version-0 program fails, a 32-byte version-1 program is taproot, and a version-16 program is a future version. The library does the same on real spends [BCS]."),
  (H, "The engine runs the output script first, which pushes the version and the program, then recognises the pattern and does not run anything else for it; it hands the witness to VerifyWitnessProgram. There the version and the size select the case, in the code of Bitcoin Core: a 32-byte program is a script hash, a 20-byte program a key hash, and any other size of a version-0 program is the error WITNESS_PROGRAM_WRONG_LENGTH. The input script must be exactly empty, otherwise validation fails; for a witness program inside a script hash it must be exactly a push of the redeem script [BCI] [B141]."),
  (K, "A detail of the first execution makes some programs fail early. Because the engine runs the output script on its own first, the program is on top of the stack, and a program whose bytes are all zero counts as false, so the script fails before the witness is looked at; BIP141 notes that having a hash like this would be a preimage attack on the hash function and the risk is negligible. A program of 19 bytes with a nonzero byte fails with the length error, and a program of 41 bytes is not a witness program at all."),
 ), None),

 ("P2wpkh", "Pay to witness public key hash", 3, "WitnessPrograms", ("0 <20-byte public key hash>", "A P2WPKH output holds a version 0 and the 20-byte hash of a compressed public key; it is spent by a witness of exactly two items, a signature and the public key, and an empty input script.",
   (PROG("h = '" + HK + "'                          # HASH160 of the compressed public key\nspk = '0014' + h                              # witness version 0, a push of 20 bytes, the hash\nscript_code = '1976a914' + h + '88ac'         # the script BIP143 signs: the legacy key hash script with its length byte\nresult = (spk, len(spk) // 2, len(script_code) // 2 - 1)"), "('0014751e76e8199196d454941c45d1b3a323f1433bd6', 22, 25)")), P(
  (W, "A pay to witness public key hash output, P2WPKH, is the segregated witness equivalent of the pay to public key hash output. The book shows both for the same key hash ab68...: the legacy script has five items, and the witness one is 0 followed by the hash. It is much simpler: two values pushed onto the stack, the first the witness version and the second the witness program, which is simply the hash of the public key. Its spending transaction has an empty input script and a witness structure [AH]."),
  (Y, "The form does the same job for less: the output script is 22 bytes instead of 25, and the signature and the key sit in the witness, which gets a discount in the size on which the fee is calculated. BIP141 specifies it exactly: the witness must consist of exactly two items of at most 520 bytes each, a signature then a public key; the hash of the key must match the 20-byte program; and the signature is verified against the key with the signature check, which must leave a single true [B141]."),
  (E, "The form is the most common input of the saved block: 626 of the 1,022 inputs spend a P2WPKH output, three times more than the 194 legacy key hash inputs [MP]. The page's example builds the output script and the signed script code from the hash 751e76e8..., the key hash of BIP173's example key, and gets 22 bytes and 25 bytes. The library runs a real spend: it signs with the second demonstration key and verifies. Bitcoin Core builds the same script at run time, as DUP HASH160, the program, EQUALVERIFY and CHECKSIG [BCI]."),
  (H, "The engine takes the two witness items as the initial stack, signature then key, and executes the implied legacy script on them, so a P2WPKH spend is a P2PKH spend with the data moved to the witness. If the witness does not have exactly two items, the error is WITNESS_PROGRAM_MISMATCH. The signature does not sign the legacy way: the code that is signed is the legacy key hash script, with its length byte, and the amount of the output is part of the hash, as the last section of the branch explains [BCI] [B143]."),
  (K, "The book's warnings are about the key. A P2WPKH program must be created by the receiver and never converted by the sender from a key, a P2PKH script or an address, and it must be built from the hash of a compressed public key; an uncompressed key is nonstandard and may be disabled by a soft fork, and funds sent to the hash of an uncompressed key may be lost. The library shows the first stage of this: a spend with an uncompressed key is valid by consensus, but is rejected when the policy flag WITNESS_PUBKEYTYPE is on, as in the standard flags [AH] [BCQ]."),
 ), None),

 ("P2wsh", "Pay to witness script hash", 3, "WitnessPrograms", ("0 <32-byte SHA-256 of the witness script>", "A P2WSH output holds a version 0 and the 32-byte SHA-256 of a script; it is spent by a witness whose last item is that script and whose other items are its input.",
   (PROG("import hashlib\nscript = bytes.fromhex('" + SCR173 + "')        # BIP173's example script: a public key and OP_CHECKSIG\nprogram = hashlib.sha256(script).digest()       # one SHA-256, not HASH160\nresult = ('0020' + program.hex(), len(program))"), "('0020" + "1863143c14c5166804bd19203356da136c985678cd4d27a1b8c6329604903262" + "', 32)")), P(
  (W, "A pay to witness script hash output, P2WSH, is the segregated witness equivalent of pay to script hash. The book takes it from the multisignature of Mohammed's company: the output script is 0 followed by the 32-byte hash of the witness script, and the spend puts the signatures and the script in the witness, with an empty input script. The segregated witness script is a lot simpler than the legacy one and reduces the template overhead of the legacy form [AH]."),
  (Y, "The hash is different, on purpose. The book explains that P2SH uses the 20-byte RIPEMD160(SHA256(script)) while P2WSH uses a 32-byte SHA256(script), deliberately, to give stronger security in certain use cases: 128 bits of security instead of 80. The change raises the cost of finding two scripts with the same hash, which matters when several parties build a script together. BIP141 adds that a witness script may be up to 10,000 bytes, since the 520-byte push limit does not apply to it, though each other witness item is at most 520 bytes [AH] [B141]."),
  (E, "The page's example hashes BIP173's example script, a key followed by OP_CHECKSIG, once with SHA-256 and gets 1863143c...; with the version byte and the length it is the program of the address bc1qrp33g0q5... that BIP173 lists. In block 775,072, 57 of the inputs spend a P2WSH output directly and 34 more spend it nested; all 91 reveal a multisignature script [MP]. Bitcoin Core's standardness rules limit a witness script to 3,600 bytes, a stack of 100 items and 80 bytes per item [BCQ]."),
  (H, "The engine pops the last witness item, hashes it with a single SHA-256, compares it with the program, and if the hash differs it fails with WITNESS_PROGRAM_MISMATCH; an empty witness fails with WITNESS_PROGRAM_WITNESS_EMPTY. It then runs the script with the remaining items as the initial stack, in the witness version 0 rules, which differ from the legacy ones in two ways: the signature hash of BIP143 is used, and the signature is not removed from the script code. The result must be exactly one true on the stack [BCI] [B141]."),
  (K, "The standard limits are not the consensus limits, and the difference can lock coins. A witness script of 10,000 bytes is valid by consensus, but Bitcoin Core relays only scripts up to 3,600 bytes; the library spends a 20-of-20 multisignature, which has 685 bytes, and a 15-of-15 in a script hash, both accepted. The book also warns that a P2WSH multisignature should be made by the receiver's wallet, as for the key hash form, and that the program is not the script, so the script has to be backed up."),
 ), None),

 ("SegwitAddress", "Segwit address (bech32)", 3, "WitnessPrograms", ("bc1q... carries a version-0 program, bc1p... a version-1 program", "A native segregated witness address writes the witness version and the program as a bech32 string with a human-readable part, a separator, 5-bit characters and a six-character checksum; version 0 uses bech32 and version 1 and later use bech32m.",
   (PROG(BECH + "key_hash = bytes.fromhex('" + HK + "')\nresult = (segwit_address('bc', 0, key_hash), segwit_address('bc', 1, bytes.fromhex('79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798')))"), "('bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4', 'bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqzk5jj0')")), P(
  (W, "A native segregated witness address is a way to write a witness program that a person can read, type and scan. BIP173 defines the format, which it calls Bech32: a string of at most 90 characters made of a human-readable part, which for Bitcoin is bc on the main network, a separator that is always the character 1, and a data part of characters from a 32-character set that leaves out 1, b, i and o. The data part ends in a six-character checksum. The witness version is the first character of the data: q for 0 and p for 1 [B173]."),
  (Y, "The format fixes problems of the legacy addresses, which BIP173 lists: Base58 needs a lot of space in QR codes because it cannot use the alphanumeric mode, mixed case is inconvenient to write down and to read out, and the checksum from double SHA-256 is slow and has no error-detection guarantees. The new checksum is a BCH code, hence the name. BIP350 later found a weakness in the checksum for programs of later versions, and changed the constant for versions 1 and above, a variant called Bech32m, while version 0 keeps the original [B173] [B350]."),
  (E, "The two BIPs give examples. For the key 0279BE66..., whose HASH160 is 751e76e8..., the main-network P2WPKH address is bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4, and the page's example computes it in the browser from the hash. A version-1 program of 32 bytes, the x-coordinate 79be66... of the same key, gives bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqzk5jj0, a BIP350 vector, and the example computes that as well. The saved block's outputs are 754 P2WPKH, 69 P2WSH and 33 P2TR [B350] [MP]."),
  (H, "The algorithm has four steps. The witness version and the program bytes are regrouped from 8-bit bytes to 5-bit characters; the human-readable part is expanded into a list of values; a polynomial checksum over the expanded part and the data, followed by six zeros, is computed and combined with a constant, 1 for version 0 and 0x2bc830a3 for later versions; and the characters are looked up in the 32-character set. A decoder recomputes the checksum with the constant of the version and rejects the address on a mismatch [B173] [B350]."),
  (K, "A legacy address and a bech32 address of the same key are different outputs, and an address must be entered in the form the wallet gives. The two constants matter: the BIP350 vector with the version-1 program written with the version-0 constant is invalid, and the library rejects it, as it does a changed last character. The address is also case-insensitive, but only if it is all lowercase or all uppercase; mixed case is invalid, which the specification gives as a reason to prefer an all-uppercase address in a QR code."),
 ), None),

 ("SegwitUpgrade", "Upgrading to segregated witness", 2, "SegwitScripts", None, P(
  (W, "This group explains how a system with millions of users changed its rules without stopping. Segregated witness was implemented as a backward-compatible upgrade in which old and new clients coexist; wallets upgraded independently; and outputs from the nested forms let a payer who knows nothing about segwit pay one who does. The new signature hash fixed two weaknesses of the old one at the same time [AH] [B141] [B143]."),
  (Y, "The group matters because the way of introducing a change decides whether it is safe. A soft fork makes the rules stricter, so blocks valid under the new rules are valid under the old ones, and the old nodes follow the chain without understanding the new outputs. The price is that the old nodes see the new outputs as spendable by anyone, and the protection depends on the new nodes enforcing the rules."),
  (H, "The first section describes the soft fork and its two steps, with an old-node model; the second the nested forms, with their hashes and addresses recomputed from the book; the third the signature hash, with a model in the browser that is checked against the library."),
  (K, "The group describes the situation at a time. Native witness outputs are now the default of most wallets, and the nested forms are kept for payers whose software cannot yet send to a bech32 address; the saved block shows 129 nested inputs and 683 native witness inputs."),
 ), None),

 ("BackwardCompatibleUpgrade", "Backward-compatible upgrade", 3, "SegwitUpgrade", ("old nodes see anyone-can-spend, new nodes check the witness", "Segregated witness is a soft fork: an old node sees a witness output as two pushes that anyone can spend and ignores the witness, while an upgraded node enforces the witness rules, so the two kinds of node agree on the chain as long as the miners enforce the new rules.",
   (PROG(MINI + "program = '11' * 20\nold_view = run('0 0x' + program)                   # an old node runs only the output script: two pushes\nresult = (len(old_view), true(old_view[-1]))"), "(2, True)")), P(
  (W, "Segregated witness was implemented as a backward-compatible upgrade, where, in the book's phrase, old and new clients can coexist. Wallet developers independently upgraded wallet software to add segwit capabilities, while legacy P2PKH and P2SH continued to work for nonupgraded wallets. Two scenarios needed an answer: a spender's wallet that is not segwit-aware must be able to pay a recipient who can process segwit, and a segwit-aware wallet must be able to tell the recipients that are segwit-aware from the others, by their addresses [AH]."),
  (Y, "The mechanism is the version byte. BIP141 explains that, since a version byte is pushed before a witness program, and programs with unknown versions are considered anyone-can-spend scripts, a new script system can be introduced with a soft fork. Non-upgraded nodes do not see or validate the witness data and consider all witness programs anyone-can-spend, except the edge cases where the program is equal to 0; the BIP says wallets should always be wary of anyone-can-spend scripts and treat them with suspicion [B141]."),
  (E, "The activation is on the chain. The soft fork took effect at block 481,824 of the main network, which was mined on 24 August 2017, according to the heights in Bitcoin Core's chain parameters and the explorer's record of that block. The page's example is a model of the old node's view: it runs only the output script, 0 followed by 20 bytes, which leaves two items, the last of them a nonzero program, which counts as true. The library shows the same with the witness flag switched off: a witness spend with an empty witness is accepted [BCL] [MA]."),
  (H, "The two steps of the upgrade, in the book's words, are that wallets must first create segwit-type outputs, and then those outputs can be spent by wallets that know how to construct segregated witness transactions. The new node, which does enforce the rule, handles an output of the form version and program by requiring an empty input script and checking the witness; a miner who enforces the rules never includes a block in which the witness is wrong, and so the old node, whose rules are weaker, never sees a block that the new rules reject [AH] [B141]."),
  (K, "The words anyone-can-spend are exact for an old node and for a wallet that does not check. A coin held in a witness program is as safe as the number of miners that enforce the rules: if a majority did not, the witness could be ignored. This is why the soft fork was deployed with a period of signalling by miners, called version bits, which for segwit started on 15 November 2016 and had a timeout on 15 November 2017 [B147]."),
 ), None),

 ("NestedSegwit", "Nested segregated witness", 3, "SegwitUpgrade", ("a witness program inside a P2SH redeem script", "A nested segregated witness output is a script hash output whose redeem script is a witness program; a wallet that cannot send to a segwit address can pay the 3 address, and the receiver spends it with a witness.",
   (PROG(B58 + "h = bytes.fromhex('" + HNP + "')                # HASH160 of the redeem script 0014 <key hash>\nredeem = bytes.fromhex('0014" + HB + "')\nresult = (b58check(5, h), len(redeem) + 1)"), "('37Lx99uaGn5avKBxiW26HjedQE3LrDCZru', 23)")), P(
  (W, "A nested segregated witness output is a witness program embedded in a pay to script hash script. The book explains the case: Alice's wallet is not upgraded but Bob's is; Bob's wallet constructs a P2SH address that contains a segwit script inside it, Alice pays it without knowing anything about segwit, and Bob spends with a segwit transaction, taking advantage of the reduced cost of witness data. Both forms can be embedded: the first is noted as nested P2WPKH, the second as nested P2WSH [AH]."),
  (Y, "The nested form solves the second scenario of the upgrade at a small price. BIP141 compares it with the native form: the output script is one byte bigger and the input script 23 bytes bigger, and it says that although a nested witness program is less efficient, its payment address is fully transparent and backward compatible for all reference clients since version 0.6.0. In the saved block 129 inputs, 95 key hash and 34 script hash, use this form [B141] [MP]."),
  (E, "The book gives both constructions with numbers, and the library reproduces them. For the key hash ab680255..., the redeem script is 0014 followed by the hash; its HASH160 is 3e054726...; with the version byte 5 the address is 37Lx99uaGn5avKBxiW26HjedQE3LrDCZru. For the script hash 9592d601..., the redeem script is 0020 followed by the hash, its HASH160 is 86762607... and the address is 3Dwz1MXhM6EfFoJChHCxh1jWHb8GQqRenG. The page's example computes the first address and the 23 bytes of the push of the redeem script that is the input script."),
  (H, "The spend runs in the order of the two mechanisms. The output script is an ordinary script hash script and the input script is a single push of the redeem script; the hash matches, and then the engine sees that the redeem script is a witness program and runs the witness rules with it. The input script must be exactly the push of the redeem script, otherwise the error is WITNESS_MALLEATED_P2SH, because anything else would let a third party change the transaction. The library runs the nested spends of a key hash and of a 2-of-3 multisignature [BCI] [B141]."),
  (K, "Two hash steps are easy to confuse. The nested script hash is the legacy HASH160 of the witness program, with its version and length bytes, not of the key and not of the script; and in the nested script hash form the inner SHA-256 of the witness script is already one hash, so the data goes through the hashes of two layers. The book's two nested examples use different hashes, 9592d601... for the witness script, and a9b7b38d... for the native example, which are two different scripts and not a mistake."),
 ), None),

 ("WitnessSighash", "Witness signature hash", 3, "SegwitUpgrade", ("sighash v0 commits to the amount of the spent output", "BIP143 defines the signature hash for version-0 witness programs: it hashes the parts of the transaction in a fixed order with the value of the output being spent, and it reuses three hashes for all inputs, so that the work grows with the size of the transaction and not with its square.",
   (PROG(SIGHASH_MODEL + "result = (len(sighash(100000)), sighash(100000) != sighash(100001))"), "(32, True)")), P(
  (W, "The witness signature hash is the digest that a version-0 witness input signs, defined by BIP143. It is a double SHA-256 of ten items in a fixed order: the transaction version, a hash of all input outpoints, a hash of all input sequences, the outpoint of this input, the script code of the input, the value of the output spent by this input, the sequence of the input, a hash of all outputs, the lock time and the hash type. It replaced the old algorithm for witness inputs only [B143]."),
  (Y, "BIP143 names two weaknesses of the original algorithm. The first is that the data hashed for each signature is proportional to the size of the transaction, so the hashing grows with the square of the number of signature operations: a 1 MB block normally takes about 2 seconds to verify but a transaction of 1 MB with 5,569 signature operations could take 25 seconds. The second is that the original algorithm did not involve the amount being spent, so an offline signing device could not know the amount or the fee without the whole previous transaction [B143]."),
  (E, "The first fix is the three reusable hashes: the hash of the outpoints, of the sequences and of the outputs are computed once and reused for the other inputs, which reduces the whole process from the square to a linear amount of work. The second fix is the sixth item, the amount. The page's example is a model that follows the ten items for one input and one output and shows that changing the amount by one satoshi gives a different digest. The library's function for the same digest gives the same result for the same transaction, and the real spends of the saved block's 626 P2WPKH inputs validate with it [MP]."),
  (H, "The rules for the hash type are as before, with changes: all types commit to the amount; the removal of the signature from the script code is not applied; the single type does not commit to the input index; and for the key hash form the script code is the legacy key hash script, 0x1976a914, the 20-byte hash and 0x88ac. If the hash type does not have the anyone-can-pay flag, the hash of the outpoints is the hash of all of them, and otherwise zero; similar rules decide the hashes of the sequences and the outputs [B143]."),
  (K, "The amount is committed to by the signature, which means that a wallet signing with a wrong amount produces a signature that the network rejects: the library signs a spend with an amount one satoshi too small and the engine returns EVAL_FALSE. The model of the page is not a complete implementation, since it does not handle the other hash types or several inputs, which is what the library does and the specification defines in full."),
 ), None),
]

CHECKS_G = [
 Qb(BK, "As you can see, a P2WPKH output script is much", "simpler than the P2PKH equivalent.", "It consists of two values that are", "pushed onto the script evaluation stack.", "To an old (nonsegwit-aware)", "Bitcoin client, the two pushes would look like an output that anyone can", "spend.", "the first number (0)", "is interpreted as a version number (the _witness version_) and the", "second part (20 bytes) is a", "_witness program_.", "The 20-byte witness program is simply the hash of the", "public key, as in a P2PKH script.", "Bob’s transaction has an empty", "input script and includes a witness structure"),
 Qb(BK, "P2WPKH witness programs should only be created by", "the receiver and not converted by the spender from a known", "public key, P2PKH script, or address.", "The spender has no way of knowing", "if the receiver's wallet has the ability to construct segwit", "transactions and spend P2WPKH outputs."),
 Qb(BK, "P2WPKH outputs must be constructed from the hash of a", "_compressed_ public key. Uncompressed public keys are nonstandard in", "segwit and may be explicitly disabled by a future soft fork.", "it may be", "unspendable and you may lose funds."),
 Qb(BK, "The second type of", "segwit v0 witness program corresponds to a P2SH script.", "0 a9b7b38d972cabc7961dbfbcb841ad4508d133c47ba87457b4a0e8aae86dbb89", "a witness version", "(0) and the 32-byte SHA256 hash of the witness script (the witness", "program).", "While P2SH uses the 20-byte +RIPEMD160(SHA256(script))+ hash, the P2WSH", "witness program uses a 32-byte +SHA256(script)+ hash.", "This difference in", "the selection of the hashing algorithm is deliberate", "(128 bits of security in P2WSH versus 80 bits", "of security in P2SH).", "No data would be placed in the", "input script because this is a native witness program"),
 Qb(BK, "Both types of witness programs", "consist of the same version number followed by a data push.", "The", "critical difference between them is the length of the witness program:", "The witness program in P2WPKH is 20 bytes.", "The witness program in P2WSH is 32 bytes.", "By looking at the length of the hash,", "a node can determine what type of witness program it is"),
 Qb(BK, "upgrading to segregated", "witness is a two-step process.", "First, wallets must create segwit", "type outputs.", "Then, these outputs can be spent by wallets that know how", "to construct segregated witness transactions.", "Segregated witness was implemented as a", "backward-compatible upgrade, where _old and new clients can coexist_.", "Wallet developers independently upgraded wallet software to add", "segwit capabilities.", "Legacy P2PKH and", "P2SH continue to work for", "nonupgraded", "wallets.", "Ability of a spender's wallet that is not segwit-aware to make a", "payment to a recipient's wallet that can process segwit transactions.", "Ability of a spender's wallet that is segwit-aware to recognize and", "distinguish between recipients that are segwit-aware and ones that are", "not, by their _addresses_."),
 Qb(BK, "Bob would", "likely want to use segwit to reduce transaction fees, taking advantage", "of the reduced cost of witness structure.", "Bob's wallet can construct a P2SH address that contains a", "segwit script inside it.", "Alice's wallet can make payments to it without", "any knowledge of segwit.", "Both forms of witness scripts, P2WPKH and P2WSH, can be embedded in a", "P2SH address.", "The first is noted as nested P2WPKH, and the second is noted", "as nested P2WSH."),
 Qb(BK, "0 ab68025513c3dbd2f7b92a94e0581f5d50f654e7", "producing another 20-byte hash.", "+37Lx99uaGn5avKBxiW26HjedQE3LrDCZru+", "OP_HASH160 3e0547268b3b19288b3adef9719ec8659f4b2b0b OP_EQUAL", "9592d601848d04b172905e0ddb0adde59f1590f1e553ffc81ddc4b0ed927dd73", "86762607e8fe87c0c37740cddee880988b9455b2", "3Dwz1MXhM6EfFoJChHCxh1jWHb8GQqRenG", "OP_HASH160 86762607e8fe87c0c37740cddee880988b9455b2 OP_EQUAL", "hashes the witness script with SHA256 (just", "once)", "the witness program itself is hashed with SHA256 and RIPEMD-160"),
 Qe("bip-0141.mediawiki", "consists of a 1-byte push opcode (one of <code>OP_0,OP_1,OP_2,...,OP_16</code>) followed by a direct data push between 2 and 40 bytes gets a new special meaning.", "The value of the first push is called the \"version byte\". The following byte vector pushed is called the \"witness program\".", "The scriptSig must be exactly empty or validation fails.", "The <code>scriptSig</code> must be exactly a push of the BIP16 <code>redeemScript</code> or validation fails.", "It is interpreted as a pay-to-witness-public-key-hash (P2WPKH) program.", "The witness must consist of exactly 2 items (≤ 520 bytes each). The first one a signature, and the second one a public key.", "The HASH160 of the public key must match the 20-byte witness program.", "The <code>witnessScript</code> (≤ 10,000 bytes) is popped off the initial witness stack. SHA256 of the <code>witnessScript</code> must match the 32-byte witness program.", "If the version byte is 0, but the witness program is neither 20 nor 32 bytes, the script must fail.", "If the version byte is 1 to 16, no further interpretation of the witness program or witness stack happens, and there is no size restriction for the witness stack. These versions are reserved for future extensions.", "the script must fail if the witness program has a <code>CastToBool</code> value of zero.", "Only compressed public keys are accepted in P2WPKH and P2WSH", "P2WSH allows maximum script size of 10,000 bytes, as the 520-byte push limit is bypassed.", "Comparing with the previous example, the scriptPubKey is 1 byte bigger and the scriptSig is 23 bytes bigger.", "its payment address is fully transparent and backward compatible for all Bitcoin reference client since version 0.6.0.", "programs with unknown versions are always considered as anyone-can-spend script, it is possible to introduce any new script system with a soft fork.", "will consider all witness programs as anyone-can-spend scripts", "Wallets should always be wary of anyone-can-spend scripts and treat them with suspicion.", "scriptPubKey: 0 <20-byte-key-hash>"),
 Qe("bip-0143.mediawiki", "The algorithm does not involve the amount of Bitcoin being spent by the input.", "the amount of data hashing is proportional to the size of the transaction", "While a 1 MB block would normally take 2 seconds to verify with an average computer in 2015, a 1MB transaction with 5569 sigops may take 25 seconds to verify.", "All sighash types commit to the amount being spent by the signed input;", "<code>FindAndDelete</code> of the signature is not applied to the <code>scriptCode</code>;", "<code>SINGLE</code> does not commit to the input index.", "the <code>scriptCode</code> is <code>0x1976a914{20-byte-pubkey-hash}88ac</code>.", "from O(n<sup>2</sup>) to O(n)", "1. nVersion of the transaction (4-byte little endian)", "10. sighash type of the signature (4-byte little endian)"),
 Qe("bip-0147.mediawiki", "using the same parameters for BIP141 and BIP143", "For Bitcoin mainnet, the BIP9 starttime is midnight 15 November 2016 UTC", "BIP9 timeout is midnight 15 November 2017 UTC"),
 Qe("bip-0173.mediawiki", "This document proposes a checksummed base32 format, \"Bech32\"", "Base58 needs a lot of space in QR codes, as it cannot use the ''alphanumeric mode''.", "The mixed case in base58 makes it inconvenient to reliably write down, type on mobile keyboards, or read out loud.", "The double SHA256 checksum is slow and has no error-detection guarantees.", "A Bech32<ref>'''Why call it Bech32?'''", "is at most 90 characters long", "The '''separator''', which is always \"1\".", "excluding \"1\", \"b\", \"i\", and \"o\"", "Mainnet P2WPKH: <tt>bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4</tt>", "Mainnet P2WSH: <tt>bc1qrp33g0q5c5txsp9arysrx4k6zdkfs4nce4xj0gdcccefvpysxf3qccfmv3</tt>", "The P2WSH examples use <tt>key OP_CHECKSIG</tt> as script."),
 Qe("bip-0350.mediawiki", "replacing the constant ''1'' that is xored into the checksum at the end with ''0x2bc830a3''", "If its witness version is 0, encode it using Bech32.", "If its witness version is 1 or higher, encode it using Bech32m.", "<tt>bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqzk5jj0</tt>: <tt>512079be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798</tt>", "<tt>bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqh2y7hd</tt>: Invalid checksum (Bech32 instead of Bech32m)", "Bech32 remains in use for segregated witness outputs of version 0."),
 Qc("src/script/script.cpp", "bool CScript::IsWitnessProgram(int& version, std::vector<unsigned char>& program) const", "if (this->size() < 4 || this->size() > 42) {", "if ((size_t)((*this)[1] + 2) == this->size()) {"),
 Qc("src/script/interpreter.cpp", "// BIP141 P2WSH: 32-byte witness v0 program (which encodes SHA256(script))", "// BIP141 P2WPKH: 20-byte witness v0 program (which encodes Hash160(pubkey))", "exec_script << OP_DUP << OP_HASH160 << program << OP_EQUALVERIFY << OP_CHECKSIG;", "return set_error(serror, SCRIPT_ERR_WITNESS_PROGRAM_WRONG_LENGTH);", "return set_error(serror, SCRIPT_ERR_WITNESS_PROGRAM_MISMATCH);", "// The scriptSig must be _exactly_ a single push of the redeemScript. Otherwise we", "return set_error(serror, SCRIPT_ERR_WITNESS_MALLEATED_P2SH);"),
 Qc("src/policy/policy.h", "inline constexpr unsigned int MAX_STANDARD_P2WSH_STACK_ITEMS{100};", "inline constexpr unsigned int MAX_STANDARD_P2WSH_STACK_ITEM_SIZE{80};", "inline constexpr unsigned int MAX_STANDARD_P2WSH_SCRIPT_SIZE{3600};", "SCRIPT_VERIFY_WITNESS_PUBKEYTYPE |"),
 Qc("src/kernel/chainparams.cpp", "consensus.SegwitHeight = 481824; // 0000000000000000001c8018d9cb3b742ef25114f27563e3fc4a1902167f9893"),
 # executed: programs and spends
 X("[L.classify(bytes.fromhex(s))[0] for s in ('0014' + '11' * 20, '0020' + '22' * 32, '5120' + '44' * 32)]", ["witness_v0_keyhash", "witness_v0_scripthash", "witness_v1_taproot"]),
 X("[L.witness_program(bytes.fromhex(s)) is None for s in ('0014' + '11' * 20, '0013' + '33' * 19, '0029' + '55' * 41)]", [False, False, True]),
 X("(len(L.p2wpkh_script(bytes(20))), len(L.p2pkh_script(bytes(20))), len(L.p2wsh_script(bytes(32))), len(L.p2sh_script(bytes(20))))", (22, 25, 34, 23)),
 X("(C.wpkh_spend(), C.wpkh_spend(nested=True))", ("OK", "OK")),
 X("(C.wpkh_spend(witness=[]), C.wpkh_spend(witness=[b'x']), C.wpkh_spend(program=b'\\x01' + bytes(18)), C.wpkh_spend(script_sig=b'\\x51'))", ("WITNESS_PROGRAM_MISMATCH", "WITNESS_PROGRAM_MISMATCH", "WITNESS_PROGRAM_WRONG_LENGTH", "WITNESS_MALLEATED")),
 X("C.wpkh_spend(program=bytes(19))", "EVAL_FALSE"),
 X("(C.wpkh_spend(compressed=False), C.wpkh_spend(compressed=False, flags=L.MAINNET_FLAGS | {'WITNESS_PUBKEYTYPE'}), 'WITNESS_PUBKEYTYPE' in L.STANDARD_FLAGS)", ("OK", "WITNESS_PUBKEYTYPE", True)),
 X("C.wpkh_spend(signed_amount=99999)", "EVAL_FALSE"),
 X("C.wpkh_spend(nested=True, script_sig=b'\\x51')", "EVAL_FALSE"),
 X("(C.ms_spend(2, 3, [1, 2], wrap='p2wsh'), C.ms_spend(2, 3, [1, 2], wrap='p2sh-p2wsh'), C.ms_spend(20, 20, list(range(20)), wrap='p2wsh'))", ("OK", "OK", "OK")),
 X("(len(L.multisig_script(20, [C.pub(i % 8) for i in range(20)])), len(L.multisig_script(1, [C.pub(0)] * 2)))", (685, 71)),
 X("C.wsh_run(b'\\x51', [])", "OK"),
 X("(lambda tx, sp: L.verify_input(tx, 0, sp, L.MAINNET_FLAGS))(*L.credit_and_spend(b'', L.p2wsh_script(L.sha256(b'\\x51')), witness=[b'\\x52']))", "WITNESS_PROGRAM_MISMATCH"),
 X("(lambda tx, sp: L.verify_input(tx, 0, sp, L.MAINNET_FLAGS))(*L.credit_and_spend(b'', L.p2wsh_script(L.sha256(b'\\x51')), witness=[]))", "WITNESS_PROGRAM_WITNESS_EMPTY"),
 X("L.sha256(bytes.fromhex(" + repr(SCR173) + ")).hex()", "1863143c14c5166804bd19203356da136c985678cd4d27a1b8c6329604903262"),
 # executed: addresses
 X("L.hash160(L.pubkey_serialize(L.G)).hex()", HK),
 X("L.segwit_address('bc', 0, bytes.fromhex(" + repr(HK) + "))", "bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4"),
 X("L.segwit_address('tb', 0, bytes.fromhex(" + repr(HK) + "))", "tb1qw508d6qejxtdg4y5r3zarvary0c5xw7kxpjzsx"),
 X("L.segwit_address('bc', 0, L.sha256(bytes.fromhex(" + repr(SCR173) + ")))", "bc1qrp33g0q5c5txsp9arysrx4k6zdkfs4nce4xj0gdcccefvpysxf3qccfmv3"),
 X("L.segwit_address('bc', 1, bytes.fromhex('79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798'))", "bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqzk5jj0"),
 X("(lambda g: (exec(" + repr(BECH) + ", g), (g['segwit_address']('bc', 0, bytes.fromhex(" + repr(HK) + ")), g['segwit_address']('bc', 1, bytes.fromhex('79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798'))))[1])({})", ("bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4", "bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqzk5jj0")),
 X("[C.addr_ok(a) for a in ('bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4', 'BC1QW508D6QEJXTDG4Y5R3ZARVARY0C5XW7KV8F3T4', 'bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t5', 'bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqzk5jj0', 'bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqh2y7hd')]", [True, True, False, True, False]),
 X("(L.address_to_script('bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4').hex(), L.script_to_address(bytes.fromhex('0014" + HK + "')))", ("0014" + HK, "bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4")),
 X("(len('bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4'), len('bc1qrp33g0q5c5txsp9arysrx4k6zdkfs4nce4xj0gdcccefvpysxf3qccfmv3'))", (42, 62)),
 X("sorted(set('1bio')) and not (set('1bio') & set('qpzry9x8gf2tvdw0s3jn54khce6mua7l'))", True),
 X("(lambda c: (c['witness_v0_keyhash'], c['witness_v0_scripthash'], c['witness_v1_taproot'], c['scripthash'], c['pubkeyhash']))(__import__('collections').Counter(L.classify(s)[0] for r in C.block_records() for v, s in L.parse_tx(r['hex']).vout))", (754, 69, 33, 490, 314)),
 # executed: nested forms
 X("L.hash160(bytes.fromhex('0014" + HB + "')).hex()", HNP),
 X("L.b58check_encode(5, bytes.fromhex(" + repr(HNP) + "))", "37Lx99uaGn5avKBxiW26HjedQE3LrDCZru"),
 X("L.hash160(bytes.fromhex('0020" + WSH_N + "')).hex()", HNW),
 X("L.b58check_encode(5, bytes.fromhex(" + repr(HNW) + "))", "3Dwz1MXhM6EfFoJChHCxh1jWHb8GQqRenG"),
 X("(len(L.push_data(bytes.fromhex('0014" + HB + "'))), len(L.p2sh_script(bytes(20))) - len(L.p2wpkh_script(bytes(20))))", (23, 1)),
 X("(lambda c: (c['p2sh-p2wpkh'], c['p2sh-p2wsh'], c['p2sh-p2wpkh'] + c['p2sh-p2wsh']))(C.census(L))", (95, 34, 129)),
 X("(lambda c: (c['witness_v0_keyhash'], sum(v for k, v in c.items() if k.startswith('p2wsh')), c['pubkeyhash']))(C.census(L))", (626, 57, 194)),
 X("(626 + 57 + 129, round((626 + 57 + 129) / 1022 * 100))", (812, 79)),
 # executed: the upgrade
 X("(C.wpkh_spend(witness=[], flags=frozenset({'P2SH'})), C.wpkh_spend(witness=[], flags=L.MAINNET_FLAGS))", ("OK", "WITNESS_PROGRAM_MISMATCH")),
 X("(lambda a: [(b['height'], __import__('datetime').datetime.fromtimestamp(b['timestamp'], __import__('datetime').UTC).strftime('%Y-%m-%d')) for b in a['blocks'] if b['height'] == 481824])(C.ev_json('mainnet_activation_blocks_v1_0_0.json'))", [(481824, "2017-08-24")]),
 X("(__import__('datetime').datetime.fromtimestamp(1479168000, __import__('datetime').UTC).strftime('%Y-%m-%d'), __import__('datetime').datetime.fromtimestamp(1510704000, __import__('datetime').UTC).strftime('%Y-%m-%d'))", ("2016-11-15", "2017-11-15")),
 X("L.run('', '0 0x14 0x" + "11" * 20 + "', flags=frozenset({'P2SH'}))", "OK"),
 X("L.run('', '0 0x14 0x" + "11" * 20 + "', flags=L.MAINNET_FLAGS)", "WITNESS_PROGRAM_MISMATCH"),
 # executed: the signature hash
 X("(lambda g: (exec(" + repr(SIGHASH_MODEL) + ", g), g['sighash'](100000).hex())[1])({}) == (lambda tx: L.sighash_v0(bytes.fromhex('76a914" + "11" * 20 + "88ac'), tx, 0, 1, 100000).hex())(L.Tx(2, [(bytes(32), 0, b'', 0xfffffffd)], [(50000, bytes.fromhex('0014" + "22" * 20 + "'))], 0))", True),
 X("(lambda g: (exec(" + repr(SIGHASH_MODEL) + ", g), (g['sighash'](100000) == g['sighash'](100000), g['sighash'](100000) == g['sighash'](100001)))[1])({})", (True, False)),
 X("(lambda tx: (L.sighash_v0(bytes.fromhex('76a914" + "11" * 20 + "88ac'), tx, 0, 1, 100000) != L.sighash_v0(bytes.fromhex('76a914" + "11" * 20 + "88ac'), tx, 0, 1, 99999)))(L.Tx(2, [(bytes(32), 0, b'', 0xfffffffd)], [(50000, bytes.fromhex('0014" + "22" * 20 + "'))], 0))", True),
 X("(lambda d: (len(d), sum(1 for r in C.block_records() for w in L.parse_tx(r['hex']).witness if len(w) == 2 and len(w[1]) == 33)))(C.block_records())", (599, 626 + 95)),
]
