# Non-Apply items of the chapter 2 question bank, part B: the Network, Blockchain, Semantics and Practice branches.
# Each row is (concept, level, question, correct option, [three wrong options], one-sentence reason).
TEXT_B = [
 ("Network", "Remember", "What is the purpose of the Bitcoin network?",
  "To propagate transactions and blocks to all participants",
  ["To store the private keys of every wallet that joins it",
   "To decide which transactions pay an acceptable fee",
   "To keep the exchange rate consistent between countries"],
  "The network is a peer-to-peer network in which each peer connects to several others."),
 ("Participants", "Analyze", "Why is counting nodes not the same as measuring the network's security?",
  "Because what matters is how many participants independently verify the rules, not how many are connected",
  ["Because the figures that are published count only the nodes that accept incoming connections, and those are counted once a day by the block explorers",
   "Because every node counts for one vote on the next block",
   "Because lightweight clients are counted twice in the usual figures"],
  "The roles also overlap, since a full node may carry routing, mining and wallet functions as well."),
 ("FullNode", "Understand", "Why does a user with a full node have to trust less than one who asks a server?",
  "Their own program checks every rule, so only the software and the public rules need trust",
  ["Their node is operated for them by the miner of the most recent block, who guarantees the result and is paid for it out of the transaction fees",
   "Their node encrypts the payment so no outside party can read it",
   "Their node receives the blocks earlier than other nodes do"],
  "The chapter's opening claim is that software on your own computer can verify every aspect of the system."),
 ("LightweightClient", "Analyze", "What does a lightweight client give up in exchange for running on a telephone?",
  "The ability to know all unspent outputs, so it relies on peers for partial views of the chain",
  ["The ability to receive payments at all unless a full node is running nearby, since the client has to be told by that node which outputs are its own",
   "The ability to hold private keys, which must be kept on a server",
   "The ability to see the amounts in its own transactions"],
  "The book compares a full node with a tourist holding a street map and a lightweight client with one asking strangers."),
 ("Peer", "Understand", "Why is it safe for a node to connect to peers it knows nothing about?",
  "Because everything a peer sends is checked against the rules by the receiving node",
  ["Because peers must register with the network before they may connect",
   "Because each peer signs its messages with a certificate",
   "Because a node accepts data only from peers it has used before"],
  "A peer is not a trusted party, which is the most important thing to remember about the word."),
 ("PeerToPeerNetwork", "Analyze", "Which part of the Bitcoin world is centralized even though the protocol is not?",
  "The services built on top, such as exchanges, explorers and payment processors",
  ["The consensus rules, which are published by one committee of developers and then distributed to every node in the next release of the software",
   "The list of peers, which a central directory distributes",
   "The memory pool, which one node maintains for everybody"],
  "The book describes companies running nodes as edge routers on which such services are built."),
 ("Propagation", "Understand", "Why is propagation not merely the copying of data?",
  "Because every node that forwards the transaction has verified it first",
  ["Because the data is compressed differently at each hop",
   "Because each node adds its own signature before relaying",
   "Because only miners are allowed to forward a transaction"],
  "Propagation is therefore a wave of independent checks, and invalid data does not travel far."),
 ("Transmission", "Remember", "Why does it not matter how or where a transaction is transmitted?",
  "Because the transaction contains all the information necessary for it to be processed",
  ["Because every route passes through the same relay server",
   "Because the first node to receive it rewrites it in a standard form",
   "Because the fee pays for a guaranteed delivery path"],
  "Alice's wallet can use any connection, or hand the transaction to a program such as a block explorer."),
 ("Gossiping", "Analyze", "Which condition in the gossip rule stops bad data at the first node?",
  "A node forwards only a transaction it finds valid",
  ["A node forwards only to peers it has seen before",
   "A node forwards only transactions that pay a minimum fee",
   "A node forwards only after one confirmation"],
  "The rule also says not seen before, which stops the same transaction circulating forever."),
 ("TransactionPropagation", "Understand", "What does wide propagation of a transaction actually establish?",
  "That many nodes have seen it and found it valid, which is not the same as its being recorded",
  ["That the transaction has at least one confirmation, since a node relays a payment onward only after it has seen it inside a block that it accepted",
   "That no competing transaction can ever be mined instead",
   "That a miner has agreed to include it in the next block"],
  "A transaction does not become part of the blockchain until it is included in a block."),
 ("Mempool", "Analyze", "Why is there no such thing as the memory pool of the network?",
  "Because each node keeps its own, and the contents vary from node to node",
  ["Because the pool is deleted every ten minutes",
   "Because only mining nodes keep a pool at all",
   "Because the pool is stored on disk by the explorers instead"],
  "The book contrasts the pool, a local perspective, with the database of unspent outputs, which does not usually vary."),
 ("RecipientVerification", "Understand", "How does Bob's wallet recognise Alice's payment as his?",
  "It finds an output that is redeemable by Bob's keys",
  ["It reads the label that Alice's wallet attached to the payment",
   "It receives a message from the miner naming the recipient",
   "It compares the amount with the invoice it issued"],
  "His wallet can also verify that the transaction is well formed, and with a full node that the inputs are unspent."),
 ("BlockExplorer", "Analyze", "What may happen when you look up your own transactions in a block explorer?",
  "The operator may be able to guess how many bitcoins you have received, spent and currently own",
  ["Your wallet may be locked until the search has been confirmed by the explorer, because the operator has to check that you control the address",
   "The transaction may be relayed twice and counted as a double spend",
   "The explorer may charge a fee taken from the transaction"],
  "A search can be associated with your address on the internet, your browser details and your past searches."),
 ("Blockchain", "Remember", "How is the blockchain best described in one phrase?",
  "The authoritative journal of all transactions",
  ["The shared memory pool of every full node",
   "The index of addresses maintained by the explorers",
   "The list of miners entitled to create the next block"],
  "Its data structure is an ordered, back-linked list of blocks of transactions."),
 ("Mining", "Remember", "Which two purposes does mining serve?",
  "Rewarding only blocks that follow the consensus rules, and creating new bitcoins on a fixed schedule",
  ["Encrypting the blockchain so that only paying users can read it, and setting the exchange rate at which the next block's coins will be issued",
   "Storing the chain for lightweight clients, and signing transactions for wallets",
   "Choosing the next miner, and collecting taxes on large payments"],
  "Because miners earn honest income only from valid blocks, users may assume that a transaction in a block is valid."),
 ("Miner", "Analyze", "What stops a miner from writing itself a reward of a thousand bitcoins?",
  "Every other node would deem the block invalid, so the electricity spent on it would be wasted",
  ["The coinbase transaction carries a field in which the permitted reward is written by the previous block's miner, and a larger amount will not fit in it",
   "The pool operator checks the amount before the block is sent",
   "The reward is paid by the network after a vote of the nodes"],
  "A miner only gets to spend the reward if the block is accepted by everyone."),
 ("CandidateBlock", "Understand", "Why is a candidate block called a candidate?",
  "Because it is not yet valid: it has no proof of work",
  ["Because the miner has not yet chosen which transactions to include",
   "Because the other miners have not yet voted on it",
   "Because its transactions are still unconfirmed in the pool"],
  "It becomes valid only if the miner finds a solution to the proof-of-work algorithm."),
 ("ProofOfWork", "Analyze", "What does a valid proof of work prove, and what does it not?",
  "It proves that an enormous amount of computation was spent, not that the block obeys the other rules",
  ["It proves that the block was produced by a miner that had registered its address with the network, which is why the reward can be paid to it",
   "It proves that every transaction in the block paid a sufficient fee",
   "It proves that no other miner was working on the same height"],
  "A block with a perfect proof of work is still rejected if any of its transactions breaks a rule."),
 ("Block", "Understand", "Why is the ratio between a block header and a whole block so important?",
  "Because a program that keeps only headers keeps a chain thousands of times smaller than the full one",
  ["Because the header of a block has to be smaller than the total fee that the block collects, which is the rule that keeps blocks from growing",
   "Because a block is valid only if its body is fifty thousand times its header",
   "Because the ratio decides how many transactions the block may hold"],
  "That ratio is why lightweight clients are possible at all."),
 ("BlockHeader", "Analyze", "Why does changing an old block force the recalculation of every block after it?",
  "Because each header commits to the hash of its parent, so a change ripples forward",
  ["Because every node stores the blocks of the chain in one single file, so a change in the middle of that file moves everything that follows it",
   "Because the merkle root of a block includes the next block's transactions",
   "Because block heights would otherwise no longer be consecutive"],
  "The enormous cost of that recalculation is what makes deep history impractical to change."),
 ("MerkleTree", "Understand", "What does the merkle root in a block header achieve?",
  "It commits to every transaction in the block in thirty-two bytes",
  ["It stores the fee rate of the highest-paying transaction",
   "It holds the identifier of the first transaction only",
   "It records how many transactions the block contains"],
  "It also allows a short path of hashes to prove that one transaction is in the block."),
 ("Difficulty", "Analyze", "Why does a rising network hash rate not make payments faster?",
  "Because the difficulty is retargeted to keep the pace at about ten minutes",
  ["Because the fee rate rises in proportion to the hash rate",
   "Because blocks are limited to one every ten minutes by a timer",
   "Because faster miners are excluded until the next halving"],
  "The target is set so that the current mining power results in a ten-minute block interval."),
 ("HashRate", "Analyze", "Why is a published network hash rate an estimate rather than a measurement?",
  "Because nobody counts the hashes of the world's miners; the figure is inferred from difficulty and block times",
  ["Because the large mining companies report their rates to the block explorers once a month, and the explorers publish whatever total they are given",
   "Because the figure is fixed by the protocol at each retarget",
   "Because hash rates are measured only inside mining pools"],
  "That is why published values differ between sources and fluctuate."),
 ("ConsensusRules", "Understand", "What is most easily confused with the consensus rules?",
  "Consensus itself, which is the agreement that results when nodes have the same best chain",
  ["The relay policy that each node applies to its own memory pool, which decides the lowest fee rate it will accept and differs from one node to another",
   "The improvement proposals in which features are documented",
   "The difficulty, which is recalculated every 2,016 blocks"],
  "The rules are what nodes check; consensus is the state that applying them produces."),
 ("CoinbaseTransaction", "Analyze", "Why can the output of a coinbase transaction not be spent at once?",
  "Because the rules require it to be at least a hundred blocks deep first",
  ["Because the miner must first sign it with the pool's key",
   "Because the reward is paid only after the next halving",
   "Because its output script has no spending condition until the block matures"],
  "The book's blockchain chapter says that after a hundred blocks there is enough stability to spend it."),
 ("BlockReward", "Analyze", "Why should a learner remember the subsidy rule rather than the current figure?",
  "Because the subsidy halves every 210,000 blocks, so any particular figure goes stale",
  ["Because the figure is different on each node",
   "Because the subsidy is chosen by the miner within a range",
   "Because the figure is quoted in dollars and so moves with the rate"],
  "The book's own glossary still gives a reward that was true two halvings earlier."),
 ("MiningPool", "Understand", "How does a pool measure what each of its miners contributed?",
  "By setting an easier target and counting the shares each miner finds",
  ["By asking each miner to declare the speed of its hardware",
   "By dividing the reward equally among everyone who was connected",
   "By timing how long each miner stayed online during the round"],
  "Each time a miner finds a hash below the pool target it proves it did the hashing work."),
 ("SudokuAnalogy", "Analyze", "Where does the sudoku analogy stop describing Bitcoin's mining?",
  "A sudoku is solved by reasoning and has one answer, while a proof of work can only be found by trial",
  ["A sudoku cannot be checked quickly by anybody who did not solve it, while a finished block is verified by every node with a single hash computation",
   "A sudoku cannot be made harder, while the difficulty can be raised",
   "A sudoku is reset after every solution, while a block is not"],
  "The analogy also has no reward, no competition and no chain of earlier puzzles."),
 ("RuleChange", "Understand", "Why can a soft fork only narrow what is valid?",
  "Because blocks made under the new rules must still be valid under the old ones, or old nodes would reject them",
  ["Because the serialization format of a transaction is fixed for ever, so no change may ever add a field and only the meaning of existing fields can be narrowed",
   "Because miners refuse to signal for a change that adds a feature",
   "Because narrowing is the only change that needs no coordination"],
  "A change that widens what is valid triggers a hard fork when an old node rejects a new block."),
 ("Security", "Understand", "How is the security of a confirmed payment best described?",
  "As confidence that grows with each block, not as an absolute guarantee",
  ["As a certainty once the transaction has one confirmation",
   "As a promise enforced by the miners who signed the block",
   "As a guarantee that holds for payments below a fixed amount"],
  "As the blocks pile up it becomes harder to reverse the transaction, giving the receiver more confidence."),
 ("Confirmation", "Analyze", "Why is six confirmations a convention rather than a law?",
  "Because an attacker with enough hash rate can invalidate six or more blocks in a row",
  ["Because the protocol itself counts only the first three confirmations and leaves any further ones to the judgement of the merchant who is paid",
   "Because confirmations stop being counted an hour after the payment, so a merchant who waits longer learns nothing more about the risk",
   "Because six blocks take exactly sixty minutes to arrive"],
  "The book advises waiting longer for high-value items, mentioning about 144 confirmations for a day."),
 ("Probability", "Analyze", "On what assumption do the paper's reversal probabilities rest?",
  "That the attacker controls a minority of the hash rate",
  ["That no transaction pays more than the average fee",
   "That every block arrives exactly ten minutes after the last",
   "That the receiver waits for at least six confirmations"],
  "With a majority of the hash rate the arithmetic changes qualitatively, as the section on hashrate attacks shows."),
 ("BestBlockchain", "Understand", "Why is most work a more accurate description of the rule than longest chain?",
  "Because a chain of fewer blocks mined at a higher difficulty can carry more cumulative work",
  ["Because competing chains are compared by the number of bytes they occupy rather than by the number of blocks, so the heavier file always wins",
   "Because the longest chain is chosen only when a fork lasts two blocks",
   "Because the rule counts transactions rather than blocks"],
  "The book speaks of the valid chain with the most cumulative proof of work."),
 ("BlockHeight", "Analyze", "Why is a block height not a unique identifier?",
  "Because two or more blocks can compete for the same position in the chain",
  ["Because heights restart at zero after every halving",
   "Because the height is stored only in the coinbase transaction",
   "Because test networks reuse the heights of the main chain"],
  "Only the block hash always names exactly one block."),
 ("AlternativeBlock", "Understand", "Why do accidental forks happen without anybody attacking?",
  "Because the network takes time to carry a new block to everybody, so two miners can win at once",
  ["Because nodes that run different versions of the software disagree about the consensus rules, so each version builds a chain of its own for a while",
   "Because miners deliberately withhold blocks to raise fees",
   "Because the difficulty is recalculated on different schedules"],
  "The book says such forks are almost always resolved within one block."),
 ("DoubleSpend", "Understand", "What makes the rejection of a double spend unambiguous?",
  "The order of transactions in one chain of blocks, which lets a node see which spend came first",
  ["The signature, which the protocol allows to be made only once for any given output, so a second spend of the same output cannot be signed at all",
   "The fee, which is higher for the first of two competing spends",
   "The mempool, which is identical on every node"],
  "Within a single chain the enforcement of order ensures no two valid transactions spend the same output."),
 ("GenesisBlock", "Analyze", "Why is the genesis block fixed in the software rather than verified like other blocks?",
  "Because it has nothing below it, so it cannot be trusted on the strength of work piled on top",
  ["Because the proof of work of the first block was lost when the network restarted in 2011, so no node is able to check its header any more",
   "Because its only transaction has no output",
   "Because its hash was chosen by the miners of the first week"],
  "Every node therefore knows its hash, structure, time and single transaction as a secure root."),
 ("UnconfirmedTransaction", "Analyze", "Why is ten minutes an average rather than a waiting time?",
  "Because nothing makes a particular block arrive on time; the interval is random with a known mean",
  ["Because every node rounds the arrival time of a block to the nearest ten minutes before storing it, so the recorded interval is never the real one",
   "Because the difficulty fixes the interval exactly at ten minutes",
   "Because the first confirmation always takes five minutes"],
  "The book's own example has a miner finding a solution almost eleven minutes after starting."),
 ("SmallPaymentAcceptance", "Understand", "Which everyday comparison explains accepting a small payment unconfirmed?",
  "Coffee shops that accept card payments without a signature for small amounts",
  ["Banks that clear cheques overnight without asking the payer",
   "Shops that accept a banknote without checking it under a lamp",
   "Airlines that allow a seat to be held for a day without payment"],
  "The risk of a reversal is low while the cost of delaying the sale is comparatively larger."),
 ("Spending", "Understand", "What does the spending group show about Bitcoin's mechanism?",
  "That there is only one mechanism and each participant uses it in turn",
  ["That a received payment must be re-signed before it can be spent",
   "That only a full node may spend an output it received",
   "That outputs received from a miner follow different rules"],
  "Alice spent an output Joe created, and Bob spends the output Alice created."),
 ("SpendingOnward", "Analyze", "Why does spending onward need more than the public record?",
  "Because only the holder of the key that satisfies the output's script can spend it",
  ["Because the output has to be registered again with a full node before it can be used, which is the step that makes it spendable by its new owner",
   "Because the amount must be converted into satoshis by the explorer",
   "Because the earlier transaction must be signed again by its payer"],
  "The record is public, which is why losing a key loses the funds and nobody else gains them."),
 ("PaymentVerification", "Analyze", "What does simplified payment verification not establish?",
  "That the transaction's inputs existed and were unspent",
  ["That the transaction appears in a particular block, which is why a lightweight client has to ask a full node whether the payment arrived at all",
   "That blocks were mined after the one containing it",
   "That the block header belongs to the chain the client holds"],
  "The chapter's own word is partially: the client verifies part of what a full node verifies."),
 ("Semantics", "Understand", "Why does this branch describe the transaction chain as provenance?",
  "Because each output exists through a transaction that consumed earlier outputs, which is what provenance records",
  ["Because every full node stores its copy of the chain as a standard ontology, so the provenance vocabulary is already the format of the ledger",
   "Because the W3C publishes the consensus rules of Bitcoin",
   "Because provenance is the name the chapter gives to the fee"],
  "The W3C's PROV Ontology is a standard vocabulary for exactly such descriptions."),
 ("ProvenanceModel", "Analyze", "Why must the model and the thing modelled be kept apart?",
  "Because the triples are written by this course, not by Bitcoin, and a different modeller could choose differently",
  ["Because the triples are written into the blockchain itself by the miner of each block, so a chain reorganization can silently rewrite part of the model",
   "Because the standard forbids describing financial data",
   "Because the model must be regenerated after every block"],
  "A model is judged by whether it answers the questions it was built for."),
 ("Ontology", "Understand", "Why is the material of a course recorded as an ontology?",
  "So that terms are defined once, questions can be stated in advance, and the result can be queried and reused",
  ["So that the page can be translated automatically into other languages, since a machine-readable vocabulary carries the wording of every definition with it",
   "So that the text can be stored in fewer bytes than prose",
   "So that students can edit the definitions during a lecture"],
  "That is also why the chapter insists that every technical word it uses is itself a concept."),
 ("Triple", "Understand", "Why are triples a convenient form for a growing description?",
  "Because two descriptions can simply be put together and anything they share joins up",
  ["Because a triple can hold three values in a single field, which makes a description of a transaction chain three times smaller than a table of rows",
   "Because triples are smaller than rows in a table",
   "Because a triple is signed by the person who wrote it"],
  "Adding Bob's onward transaction extends the same graph without altering what is already there."),
 ("ProvenanceGraph", "Analyze", "What does a provenance graph of a transaction chain not tell you?",
  "Who the parties are, because attribution is to a key holder and not to a named person",
  ["Which of the two outputs of Alice's transaction is the change and which is the payment, and which satoshi of the input ended up in each of them",
   "Which transaction generated a given output",
   "How many outputs a transaction created"],
  "Derivation is also between whole outputs, not between individual amounts."),
 ("Practice", "Understand", "Why is an interactive demonstration page worth including in the material?",
  "Because the central claims about hashing and chaining can be seen rather than believed",
  ["Because the pages run the real Bitcoin consensus rules",
   "Because the pages are the only place the book's figures appear",
   "Because a student cannot otherwise compute a hash"],
  "A student who can say what a page leaves out has understood the chapter."),
 ("InteractiveDemo", "Remember", "In what order do the five pages of the demonstration build on one another?",
  "Hash, Block, Blockchain, Distributed, Coinbase",
  ["Block, Hash, Coinbase, Distributed, Blockchain",
   "Hash, Blockchain, Block, Coinbase, Distributed",
   "Coinbase, Distributed, Blockchain, Block, Hash"],
  "Each page adds one field or one dimension to the page before it."),
 ("HashDemo", "Analyze", "Why can a reader not reproduce a real transaction identifier on the hash page?",
  "Because the page hashes text once, while an identifier is a double hash of exact binary data",
  ["Because the page truncates every digest to sixteen hexadecimal digits, so the value it shows is only the first quarter of the real identifier",
   "Because the page uses a different hash function from Bitcoin's",
   "Because identifiers are not hashes but random numbers"],
  "Pasting a hexadecimal form into the data box hashes the characters, not the bytes."),
 ("BlockDemo", "Understand", "What does pressing Mine on the block page let a reader feel?",
  "The asymmetry between a search of thousands of attempts and an instant check",
  ["The effect that a rising exchange rate has on the fee a payment must pay, and the way the difficulty is retargeted to answer it",
   "The delay caused by sending the block to other peers",
   "The cost of storing the block on disk"],
  "The box recolours the moment a satisfying nonce is found, after a perceptible pause."),
 ("BlockchainDemo", "Analyze", "What can the blockchain page not show about Bitcoin's security?",
  "That an attacker would have to outpace the whole network while it keeps extending the honest chain",
  ["That an attacker needs a majority of the hash rate before any change to an early block can be made to stick in the chain that other peers hold",
   "That each block commits to the hash of the block before it",
   "That a changed block can be made valid again by mining it"],
  "The page has one chain and one editor, so a patient reader can simply remine every block."),
 ("DistributedDemo", "Analyze", "What must a reader supply from the other branches when using the distributed page?",
  "How peers learn from one another and how a node chooses between chains",
  ["How a hash is computed from the fields of a block",
   "How a nonce is found for a given difficulty",
   "How a coinbase amount is divided among transactions"],
  "The page has no messages, no propagation and no rule for comparing cumulative work."),
 ("CoinbaseDemo", "Analyze", "Which experiment on the coinbase page shows what Bitcoin adds that the page lacks?",
  "Spending the same amount twice, which the page allows and Bitcoin rejects",
  ["Changing the coinbase amount, which the page recomputes",
   "Mining two blocks in a row, which the page allows",
   "Adding a fourth peer, which the page does not support"],
  "The page has no keys, no signatures and no check that a sender holds what it sends."),
]
