"""SEN0401 chapter 7, corpus text part A (version 1.0.0): the branch 'Transaction scripts and the Script language' - what the language
is and what it deliberately cannot do (a stack machine without loops and without memory), the locking and unlocking scripts, what makes
a script succeed, and the 2010 repair that made the two scripts run one after the other (the +1 OP_RETURN+ bug, CVE-2010-5141).
Markers such as [AH] become author-year strings (sen0401_ch07_common). The facet names are only the author's writing guide."""
from sen0401_ch07_common_v1_0_0 import *
from sen0401_ch07_common_v1_0_0 import SS_PIZZA

BK = "ch07_authorization-authentication.adoc"
NODES_A = [
 ("ScriptLanguage", "Transaction scripts and the Script language", 1, None, None, P(
  (W, "This branch opens the chapter's central idea. When you receive bitcoins you must decide who has permission to spend them, which the book calls authorization, and every full node must be able to tell the authorized spender from everyone else, which it calls authentication; the instructions and the proof are checked by thousands of independent full nodes that all have to reach the same verdict [AH]. The original description of Bitcoin used a public key for authorization and a signature for authentication, and the version that was released instead gave both jobs to a small programming language called Script [AH]."),
  (Y, "The branch matters because every other branch of the chapter is a pattern written in this language. A payment to a key hash, a multisignature, a script hash, a timelock, a witness program and a taproot output are all Script, or a rule about where Script is stored; a reader who knows what the language can express, and what it refuses to express, can read each of them as a few lines of a stack machine instead of as a list of unrelated tricks. The book states the consequence in one sentence: transaction validation is not based on a static pattern but on the execution of a scripting language [AH]."),
  (H, "The branch has two groups. The first, the language and its limits, says what Script is - a Forth-like stack language - and what it is not: it is deliberately not Turing complete, it keeps no state between runs, and the consensus rules cap its size and its work. The second, locking, unlocking and running a script, shows how an output carries a condition, how an input carries the data that meets it, what counts as success, and how the two are run one after the other since a repair in 2010 [AH]. The worked examples run a small stack machine of about thirty lines, written in the standard library, in the reader's own browser."),
  (K, "Two cautions apply to the whole branch. First, the word script is used for several different byte strings in a transaction, and it is only the context - the output being spent, the input spending it, the witness - that says which one is meant. Second, the chapter describes the language as it is used, and some of what it describes is policy rather than consensus: policy is the stricter set of rules a node applies to unconfirmed transactions before it relays them, and consensus is the set every node must apply to the transactions in blocks. Each time a limit appears, the text says which of the two it is [BCQ].")), None),

 ("ScriptModel", "The language and its limits", 2, "ScriptLanguage", None, P(
  (W, "This group describes the language itself before any payment pattern is built from it. Script is a stack-based language in which numbers and other data are pushed onto a stack and operators take their inputs from the top of that stack and put their results back on it. The group covers the stack, the two properties that the book names as the reason the language is safe to run on every node in the world - it cannot loop, and it remembers nothing between runs - and the numeric limits that the consensus rules add [AH]."),
  (Y, "The group matters because the language is run by an adversary-facing machine. Every transaction is validated by every full node, so anyone can send every node a script and make it run; the book therefore treats the missing features as the design. If scripts could loop without bound the validation of one transaction could stall the network, and if scripts could read state from earlier runs two nodes with different histories could disagree about the same transaction [AH]."),
  (H, "The five sections go from the inside out: the language and its stack machine, the way a stack makes arithmetic look backward, the absence of loops that makes the language Turing incomplete, the absence of state that makes verification stateless, and the numeric limits - script size, operation count, item size, stack depth and key count - that Bitcoin Core enforces [BCS]. Each section ends in an example that the reader can run."),
  (K, "The group describes consensus behaviour, so a rule that is stricter in the relay policy of one release is not a rule of the language. Where this group quotes a limit it is read from the Bitcoin Core source at the commit pinned for the course, and where the book gives a different figure the difference is stated [BCS].")), None),

 ("Script", "Script", 3, "ScriptModel", ("2 3 OP_ADD 5 OP_EQUAL", "Script is the Forth-like, stack-based language in which the conditions for spending an output, and the proof that the conditions are met, are written.",
   (PROG(MINI + "result = run('2 3 ADD 5 EQUAL')"), "[b'\\x01']")), P(
  (W, "Script is the programming language that the original Bitcoin software introduced for transaction validation. The book describes it as a Forth-like stack-based language, says that both the script placed in an output and the legacy input script used in a spending transaction are written in it, and says that it is a very simple language that requires minimal processing and cannot easily do many of the fancy things modern programming languages can [AH]. The worked example is the book's own first script, 2 3 OP_ADD 5 OP_EQUAL, which adds two numbers and asks whether the sum is five."),
  (Y, "Script is what makes Bitcoin payments programmable rather than fixed. Most legacy transactions had the form payment to Bob's Bitcoin address and used one script, called pay to public key hash, but scripts can be written to express a vast variety of conditions, and an output that simply asks for the answer to an arithmetic puzzle is as valid to the network as one that asks for a signature [AH]. Understanding the language is therefore the way to understand every output type in the rest of the chapter."),
  (E, "The reader meets Script wherever a transaction is decoded: an explorer prints the locking script of an output as a line of words such as OP_DUP OP_HASH160 and the unlocking data as hexadecimal, and Bitcoin Core's source defines every word of the language as a numbered opcode in its script header [BCS]. The words are written with the prefix OP_, and the book notes that the prefix is sometimes omitted in examples, so that OP_ADD and ADD name the same operator [AH]."),
  (H, "A script is a sequence of items processed from left to right. A data item is pushed onto the stack; an operator pops its inputs, computes, and may push a result. The program in the example does this for 2 3 ADD 5 EQUAL: after the two pushes the stack holds 2 and 3, ADD replaces them with 5, the next push adds another 5, and EQUAL replaces the pair with 1 because the two are equal. The program that runs it is a loop over the words of the script that handles about twenty operators, and it is the same machine that the following concepts use."),
  (K, "Bitcoin's real interpreter is much larger than the thirty-line machine used for the examples, and the examples say so each time they simplify. The real language has 113 named opcodes in Bitcoin Core's header, stores every item as a string of bytes, and disables some opcodes outright; the machine in the examples is a teaching model of the same behaviour, while the library written for this course runs the real rules and was checked against 1,237 script tests that ship with Bitcoin Core [BCJ].")), None),

 ("StackExecution", "The script execution stack", 3, "ScriptModel", ("2 7 OP_ADD 3 OP_SUB 1 OP_ADD 7 OP_EQUAL", "A stack is a pile of items with two basic operations, push and pop, and the script engine reads a script from left to right, pushing data and letting each operator pop its inputs and push its result.",
   (PROG(MINI + "words = '2 7 ADD 3 SUB 1 ADD 7 EQUAL'.split()\nresult = [len(run(' '.join(words[:i]))) for i in range(1, len(words) + 1)]"), "[1, 2, 1, 2, 1, 2, 1, 2, 1]")), P(
  (W, "A stack is a very simple data structure that the book compares to a stack of cards. It has two base operations: push adds an item on top of the stack and pop removes the top item. The scripting language executes a script by processing each item from left to right; numbers, which the book calls data constants, are pushed, and operators push or pop one or more parameters from the stack, act on them, and might push a result [AH]."),
  (Y, "The stack explains why Script looks backward to a reader used to ordinary programming. The sum one plus one is written 1 1 OP_ADD because the operator comes after its operands, and the same reversal applies to every condition: the book's flow control puts the test before IF, and a signature check puts the signature and the public key before the operator that checks them. Once the reader sees every operator as a function of the top of the stack, long scripts become short sequences of small steps [AH]."),
  (H, "The book works one script by hand: 2 7 OP_ADD 3 OP_SUB 1 OP_ADD 7 OP_EQUAL calculates 2 plus 7 minus 3 plus 1 and asks whether the result is 7. The stack grows to two items after each number is pushed and shrinks back to one after each operator, which is the pattern 1, 2, 1, 2, 1, 2, 1, 2, 1 that the worked example prints for the nine words of the script, and it ends with a single true value. The book invites the reader to try it with pencil and paper [AH]."),
  (K, "The operators that compare, such as OP_EQUAL, push true as the number 1 and false as 0, but success is decided differently: a script succeeds when the top item of the stack is true, which is any nonzero value, as the next concepts explain. An operator that finds too few items on the stack does not wait for more; the script fails at that point, which is why the dummy element of the multisignature operator, met in a later branch, has to be present [AH].")), None),

 ("TuringIncompleteness", "Turing incompleteness", 3, "ScriptModel", ("no loop construct: ten repetitions cost twenty words", "Script is deliberately not Turing complete: it has no loops and no flow control but conditionals, so every script ends and its running time is predictable.",
   (PROG(MINI + "script = '1 ' + 'DUP ADD ' * 10\nresult = (dec(run(script)[-1]), len(script.split()))"), "(1024, 21)")), P(
  (W, "Turing completeness is the property of a language that can compute anything a general computer can, which requires loops or recursion. The book says Script has many operators but is deliberately limited in one important way: there are no loops and no complex flow control capabilities other than conditional flow control. That ensures the language is not Turing complete, so scripts have limited complexity and predictable execution times, and Script is not a general-purpose language [AH]."),
  (Y, "The limitation is a defence. The book explains that the language cannot be used to create an infinite loop or another logic bomb embedded in a transaction to mount a denial-of-service attack on the network, and it reminds the reader that every transaction is validated by every full node, so a limited language prevents transaction validation from being used as a vulnerability [AH]. The work a script can demand is bounded by its length and by the number of operations it is allowed to contain, both of which a node can read before it runs anything."),
  (H, "Without a repeat operator, a repetition has to be written out. The example doubles the number 1 ten times by writing DUP ADD ten times: the script has 21 words and leaves 1,024 on the stack, and doubling twenty times would need 41 words, so the script's size grows with the work it asks for. Bitcoin Core adds a second bound: it counts the operations that are not simple number pushes and fails a script that has more than 201 of them, and it fails any script longer than 10,000 bytes [BCS]. Conditionals exist - IF, ELSE and ENDIF - but they only choose between written-out branches."),
  (K, "Incomplete is not the same as weak. Because scripts cannot loop, the useful patterns of the chapter - signatures, hash locks, timelocks, thresholds, trees of alternatives - are all expressed as a few comparisons, and richer computation is done by the parties off chain, with only a commitment and its proof placed on chain. The book returns to this when it describes taproot, where the whole contract may never appear on chain at all [AH].")), None),

 ("StatelessVerification", "Stateless verification", 3, "ScriptModel", ("the same script gives the same result on every machine", "Script verification is stateless: there is no state before a script runs and none saved afterward, so a script runs the same way on any system.",
   (PROG(MINI + "outcomes = {repr(run('2 3 ADD 5 EQUAL')) for _ in range(5)}\nresult = len(outcomes) == 1"), "True")), P(
  (W, "A language is stateless when nothing outside the program and its inputs can change what the program does. The book says the Bitcoin transaction script language is stateless: there is no state prior to the execution of the script and no state saved after it, and all the information needed to execute a script is contained within the script and the transaction executing the script [AH]."),
  (Y, "Statelessness is what lets thousands of independent computers agree. The book states the conclusion: a script will predictably execute the same way on any system, so if your system verified a script you can be sure that every other system in the network will also verify it, which means a valid transaction is valid for everyone and everyone knows this. That predictability of outcomes is described as an essential benefit of the Bitcoin system [AH]."),
  (H, "In practice the inputs of a script run are few and explicit: the two scripts, the data stack passed between them, the transaction that contains the input and the amount and locking script of the output it spends. Nothing else - no clock, no random number, no database - is read, which is why the timelock opcodes of a later branch do not ask the clock but compare their argument with fields of the spending transaction. The example runs the book's first script five times and obtains one distinct result."),
  (K, "Statelessness describes the script engine, not the whole of validation. Whether an output is still unspent depends on the state of the network, namely the set of unspent outputs, and a node checks that separately before it runs any script; that check is the job of the ownership record described in the chapter on transactions [AH6].")), None),

 ("ScriptLimits", "Consensus limits of a script", 3, "ScriptModel", ("10,000 bytes, 201 operations, 520-byte items, 1,000 stack items", "Bitcoin Core bounds a script by its size, its number of non-push operations, the size of any item it pushes, the depth of its stack and the number of keys one multisignature operator accepts.",
   (PROG("max_items, max_item_size = 1000, 520\nresult = max_items * max_item_size"), "520000")), P(
  (W, "A limit of a script is a number that the consensus rules fix in advance so that no script can demand unbounded work or memory. The source of Bitcoin Core declares them as named constants: a script may be at most 10,000 bytes long, may contain at most 201 operations that are not number pushes, may push items of at most 520 bytes, may hold at most 1,000 values on its stack, and may check at most 20 public keys in one multisignature operator [BCS]."),
  (Y, "These constants turn the idea of predictable execution into numbers. With 1,000 items of at most 520 bytes the stack cannot hold more than 520,000 bytes, which is what the worked example multiplies out, and with 201 operations the running time is bounded as well. The book states the first limit when it discusses alternatives to conditionals: legacy script is limited to 10,000 bytes, which practically limits a script to a few hundred conditional branches at most [AH]."),
  (H, "The engine checks each limit while it runs. It refuses a script longer than the size limit before running a byte, counts operations as it reads them, rejects a push larger than the item limit, and fails with a named error - script size, operation count, push size or stack size - when a bound is crossed; the multisignature operator adds the number of keys it checks to the operation count [BCI]. Tapscript, met in the last branch, lifts two of them: its scripts are not limited to 10,000 bytes and not limited to 201 operations, and a per-script budget of signature checks takes the place of the operation count [B342]."),
  (K, "The limits are consensus rules for ordinary scripts but several related numbers are policy only: a standard bare multisignature output may list at most three keys, a standard witness script is at most 3,600 bytes, and a standard input script at most 1,650 bytes, so a transaction can be valid in a block yet refused by relay nodes [BCQ]. A reader who builds a script near a limit should test it against the relay policy as well as the consensus limit.")), None),

 ("ScriptExecution", "Locking and running a script", 2, "ScriptLanguage", None, P(
  (W, "This group follows a single spend from the two halves of its condition to its verdict. An output script states the condition under which the output can be spent, an input script supplies data that meets it, and the node runs them to decide whether the input is a valid authorization. The group also covers what the verdict means and the vulnerability that led the original design to be changed in 2010 [AH]."),
  (Y, "The split is the core of authorization and authentication in Bitcoin: the sender of a payment writes the condition into the output, and the receiver proves much later, when spending, that the condition is met. Because the proof is checked only when it is used, the same machinery supports a one-key payment, a multisignature, a timelock and a contract, and the sender needs to know nothing about how the receiver will satisfy the condition [AH]."),
  (H, "The five sections take the pieces in order: the output script, the input script, the rule that a script succeeds when it leaves a true value on top of the stack, the separate execution of the two scripts with the stack passed between them, and the +1 OP_RETURN+ bug that the separate execution repaired. The worked examples use real bytes from mainnet transactions for the scripts and the small stack machine for the control flow."),
  (K, "The words locking script and unlocking script are used in older material for the output script and the input script, and the owner's earlier course notes use them; the third edition prefers output script and input script, and so does this chapter. Segregated witness adds a third place where unlocking data can live, the witness, which the segwit branch treats [AL] [AH].")), None),

 ("OutputScript", "Output script", 3, "ScriptExecution", ("OP_DUP OP_HASH160 <hash> OP_EQUALVERIFY OP_CHECKSIG", "An output script, called scriptPubKey in the code, states the conditions that must be met to spend the output in the future, such as who is authorized to spend it and how they will be authenticated.",
   (PROG("script = bytes.fromhex('76a914ab68025513c3dbd2f7b92a94e0581f5d50f654e788ac')\nresult = (len(script), script[0], script[-1])"), "(25, 118, 172)")), P(
  (W, "An output script is the part of a transaction output that holds the locking condition. The book defines it as the script that specifies the conditions that must be met to spend the output in the future, such as who is authorized to spend the output and how they will be authenticated [AH]. The example is the most common legacy script, a payment to a public key hash: 25 bytes that begin with the operator DUP, byte 118, and end with the signature operator CHECKSIG, byte 172, around a 20-byte hash."),
  (Y, "The output script is where the sender decides what the receiver must prove. The sender writes it once, when creating the output; it then sits in every full node's set of unspent outputs until somebody spends the output, so its size is paid for by every node for as long as the output exists. That cost is the reason the chapter's later patterns - hash of a script, witness program, taproot key - all try to make the output script short [AH]."),
  (E, "The reader sees an output script in the vout list of any decoded transaction, where an explorer prints it both as bytes and as words, and in Bitcoin Core's solver, which recognises the standard templates by comparing a script with their shapes: pay to public key, pay to public key hash, pay to script hash, bare multisignature, data carrier and the witness programs [BCV]. Alice's output in the chapter on transactions, and the landmark transactions of this chapter, are all read this way."),
  (H, "A node validating a spend copies the output script of the referenced output and runs it after the input script. The book stresses that all of this is done on copies: the original data in the previous output and in the input is never changed, so the previous output is unaffected by failed attempts to spend it, and only a valid transaction makes the output count as spent [AH]. Every input of a transaction is checked independently against the output it names."),
 ), None),

 ("InputScript", "Input script", 3, "ScriptExecution", ("<signature> <public key>", "An input script, called scriptSig in the code, is a script that satisfies the conditions placed in an output script and so allows the output to be spent; in legacy transactions it usually holds a signature and a public key.",
   (PROG("ss = bytes.fromhex('" + SS_PIZZA + "')\npushes, i = [], 0\nwhile i < len(ss):\n    pushes.append(ss[i]); i += 1 + ss[i]       # each item is a length byte followed by that many bytes\nresult = pushes"), "[73, 65]")), P(
  (W, "An input script is the part of a transaction input that supplies the data meeting an output script's condition. The book describes it as a script that satisfies the conditions placed in an output script and allows the output to be spent, present in every transaction input; most of the time in legacy transactions it contains a digital signature produced by the user's wallet from the private key, but not all input scripts must contain signatures [AH]. The example is the input script of the first input of the pizza transaction of 2010, which holds two items: a 73-byte signature and a 65-byte public key."),
  (Y, "The input script is the proof half of authorization and authentication. The output script says who may spend; the input script is where the spender shows they are that person, by producing a signature that only the holder of the private key can make. Because the proof is created at spending time, the holder can keep the private key offline until then, and because it is only data, the same input script format serves every condition from one signature to a complicated tree of alternatives [AH]."),
  (E, "In a decoded legacy transaction the input script appears as scriptSig, in hexadecimal and in words, and in a segwit transaction it is empty and the proof sits in the witness instead. Bitcoin Core refuses to relay a standard input script longer than 1,650 bytes, and a consensus flag introduced with pay to script hash requires the input script of such a spend to contain only data pushes [BCQ] [BCH]."),
  (H, "A node reads the input script as a list of pushes: each item is a length byte followed by that many bytes of data, and the engine places the items on the stack in order, so that the last item pushed is on top. The output script is then run on the same stack; the signature and key lie where the output script's operators expect to find them. This is why the order in the example matters: the signature first, the public key on top, matching the order in which the P2PKH script consumes them [AH]."),
  (K, "The input script of a legacy transaction is part of what the signature hash covers in a different way from the rest of the transaction, and it is also the part that third parties could change without invalidating the signature, which made the transaction identifier malleable before segregated witness. That story belongs to the chapter on transactions and to the witness group of this one [AH6]."),
 ), None),

 ("ScriptTruth", "When a script succeeds", 3, "ScriptExecution", ("the top item is true: any non-zero value", "A script succeeds when it runs without error and leaves a non-zero value on top of the stack; zero, negative zero, an empty item and an empty stack are false.",
   (PROG(MINI + "result = [(b.hex() or 'empty', true(b)) for b in (b'', b'\\x00', b'\\x80', b'\\x01', b'\\x00\\x01')]"), "[('empty', False), ('00', False), ('80', False), ('01', True), ('0001', True)]")), P(
  (W, "A script succeeds when two things hold: it ran to the end without an error and the top value on the stack is true. The book puts it as a tip: transactions are valid if the top result on the stack is TRUE, which is any nonzero value, and invalid if the top value is FALSE, meaning the value zero or an empty stack, if execution was halted explicitly by an operator such as VERIFY or OP_RETURN, or if the script was not semantically valid, such as an OP_IF that was not terminated by an OP_ENDIF [AH]."),
  (Y, "This rule is the single place where all of the chapter's conditions turn into a yes or a no. A signature operator, an equality test, a timelock check and a hash comparison all end by leaving a value on the stack or by stopping the script, and the verdict is read only from the top of the stack afterwards. A designer who understands this reads any script by asking what it leaves on top, and what makes it stop."),
  (H, "Bitcoin Core's function that decides truth, CastToBool, returns false for an item made only of zero bytes and also for the byte string that is zero with its sign bit set, the so-called negative zero, 0x80; any other item is true. After both scripts have run, the engine fails with the error EVAL_FALSE if the stack is empty or its top item is false [BCI]. The example prints the verdict for five items: the empty item, 00 and 80 are false, while 01 and the two-byte item 0001 are true."),
  (K, "Truth in Script is about the item, not about the number: a value of 0x00 0x00 is false, and so is 0x80, even though the two have different bytes, whereas 0x00 0x01 is true. The standard relay policy adds a stricter requirement, called the clean stack rule, that exactly one item remains and that it is true; the consensus rule asks only that the top item be true [BCQ] [BCI]."),
 ), None),

 ("SeparateExecution", "Separate execution of the two scripts", 3, "ScriptExecution", ("the input script runs first; its stack is passed to the output script", "Since 2010 the input script and the output script are executed one after the other, with the stack that the first leaves transferred to the second, instead of being joined into a single script.",
   (PROG(MINI + "joined = run('2 3 ADD 5 EQUAL')\nafter_input = run('2')\nseparate = run('3 ADD 5 EQUAL', after_input)\nresult = (separate == joined, [dec(x) for x in after_input])"), "(True, [2])")), P(
  (W, "In the original Bitcoin client the output and input scripts were joined and executed in sequence as one script. For security reasons this was changed in 2010, because of a vulnerability known as the +1 OP_RETURN+ bug, and in the current implementation the scripts are executed separately with the stack transferred between the two executions [AH]. The book spells out the order: first the input script is executed using the stack execution engine; if it runs without errors and has no operations left over, the stack is copied and the output script is executed on that copy [AH]."),
  (Y, "The separation limits what an unlocking script can do. An input script can only put data on the stack; it cannot run to a premature end of the whole check, because its execution is complete before the locking script starts. The Bitcoin Core function that verifies a spend carries a comment that records the reason, saying that the two scripts must be evaluated sequentially on the same stack rather than being simply concatenated, with a reference to CVE-2010-5141 [BCI]."),
  (H, "The example performs the book's arithmetic both ways. Written as one script, 2 3 ADD 5 EQUAL leaves the value 1. Run as an input script 2, which leaves the stack holding the number 2, and then as an output script 3 ADD 5 EQUAL on that stack, it leaves the same value: the stack is the interface between the two, and for ordinary scripts the result is identical. The difference appears only for operators that stop a script, which is the subject of the next concept [AH]."),
  (K, "The words if it runs without errors and has no operations left over deserve care. The check for a valid ending is applied to the final stack after both scripts have run; the input script itself may leave any number of items. Pay to script hash and segregated witness later add a third and a fourth stage to this sequence, copying the stack again and running a script that was revealed by the input; those are separate concepts of later branches [BCI]."),
 ), None),

 ("OpReturnBug", "The +1 OP_RETURN+ bug", 3, "ScriptExecution", ("CVE-2010-5141: an input script of 1 OP_RETURN spent any output", "In the first release the two scripts were joined and OP_RETURN jumped to the end of the joined script, so an input script that began with a true value and then executed OP_RETURN made any output spendable by anyone.",
   (PROG(MINI + "lock = 'SHA256 0x' + hashlib.sha256(b'secret').hexdigest() + ' EQUAL'\nthief, owner = '1 RETURN', '0x' + b'secret'.hex()\ndef old(sig):                               # joined scripts: OP_RETURN jumps to the end of everything\n    words = (sig + ' ' + lock).split()\n    if 'RETURN' in words: words = words[:words.index('RETURN')]\n    return true(run(' '.join(words))[-1])\ndef new(sig):                               # one after the other: the input script, then the output script on its stack\n    st = run(sig)\n    out = [] if isinstance(st, str) else run(lock, st)\n    return not isinstance(out, str) and bool(out) and true(out[-1])\nresult = (old(thief), new(thief), new(owner))"), "(True, False, True)")), P(
  (W, "The +1 OP_RETURN+ bug is a vulnerability of the first Bitcoin software that let anyone spend any output. In version 0.3.0 the node joined the input script, a code separator and the output script into one script, and its OP_RETURN operator simply set the program counter to the end of the script, which ended the run with whatever was on the stack. An input script consisting of the number 1 followed by OP_RETURN therefore ended the whole check with a true value on top, and the output script, whatever it demanded, never ran [AH] [O0] [O0M]."),
  (Y, "The bug is the reason the chapter says scripts are executed separately. The Bitcoin Wiki's list of vulnerabilities records it as CVE-2010-5141, dated 28 July 2010, affecting wxBitcoin and bitcoind, with the effect that OP_RETURN could be used to spend any output, rated as theft and easy to exploit [CVE]. In version 0.3.7 the source verifies the input script and the output script with two separate runs, and OP_RETURN returns false, which is the behaviour that all later software keeps [O7] [BCI]. BIP342 describes the same flaw in its own words: in versions up to and including 0.3.5 the original OP_RETURN terminated script execution immediately and returned pass or fail from the top stack element, which permitted unconditional theft by a third party who placed an OP_RETURN in the input script [B342]."),
  (H, "The worked example is a model of the two designs on a lock that asks for the preimage of a hash. In the old design an attacker's input script 1 RETURN stops the combined script with a true value on the stack, so the check passes; in the new design the same input script fails at once, and only an input script that pushes the secret satisfies the lock. The example shows the outcomes (True, False, True): old design accepts the thief, new design refuses the thief, new design accepts the owner."),
  (K, "The word return is misleading, because in current software OP_RETURN does not return a value; it makes the script fail. The same opcode is used on purpose in the next branches to make an output provably unspendable, which is possible only because the script engine now treats it as an error. The book's data-recording section builds on that [AH]."),
 ), None),
]

CHECKS_A = [
 Qb(BK, "Bitcoin transaction validation", "is not based on", "a static pattern but instead is achieved through the execution of a", "scripting language"),
 Qb(BK, "called _authorization_", "called _authentication_", "thousands of", "independent full nodes"),
 Qb(BK, "The original description of Bitcoin used a public key for authorization"),
 Qb(BK, "introduced a new", "programming language called _Script_, a Forth-like stack-based", "language"),
 Qb(BK, "Script is a very simple language. It requires minimal processing and", "cannot easily do many of the fancy things modern programming languages", "can do."),
 Qb(BK, "there are no loops or complex flow control capabilities other than", "conditional flow control. This ensures that the language is not _Turing", "Complete_", "predictable execution times", "Script is not a general-purpose language"),
 Qb(BK, "cannot be used to create an", "infinite loop or other form of \"logic bomb\"", "denial-of-service attack"),
 Qb(BK, "stateless, in that there is no state prior to execution of the script", "or state saved after execution of the script", "A script will predictably execute the same way on any system"),
 Qb(BK, "a valid", "transaction is valid for everyone and everyone knows this"),
 Qb(BK, "A stack has two", "base operations: push and pop. Push adds an item on top of the stack. Pop", "removes the top item from the stack."),
 Qb(BK, "2 7 OP_ADD 3 OP_SUB 1 OP_ADD 7 OP_EQUAL", "Try validating the preceding script yourself using pencil and paper."),
 Qb(BK, "Transactions are valid if the", "top result on the stack is +TRUE+, which is any", "nonzero value.", "Transactions are invalid if the top value on the stack is +FALSE+ (the", "value zero or an empty stack)"),
 Qb(BK, "An output script", "specifies the conditions that must be met to spend the output in the", "future", "An input script is a script that satisfies the", "conditions placed in an output script and allows the output", "to be spent."),
 Qb(BK, "The original data in the previous output and current input is never changed", "the previous output is invariable and unaffected by", "failed attempts to spend it"),
 Qb(BK, "In the original Bitcoin", "client, output and input scripts were concatenated and executed", "in sequence. For security reasons, this was changed in 2010 because of", "a vulnerability known as the +1 OP_RETURN+ bug.", "the scripts are executed separately with the stack", "transferred between the two executions."),
 Qb(BK, "the input script is executed using the stack execution", "engine. If the input script is executed without errors and has", "no operations left over, the stack is copied and the", "output script is executed."),
 Qb(BK, "the script validation engine", "will halt the execution of the validation script and mark the", "transaction as invalid."),
 Qc("src/script/interpreter.cpp", "scriptSig and scriptPubKey must be evaluated sequentially on the same stack", "rather than being simply concatenated (see CVE-2010-5141)"),
 Qc("src/script/interpreter.cpp", "bool CastToBool(const valtype& vch)", "// Can be negative zero", "if (i == vch.size()-1 && vch[i] == 0x80)", "return false;"),
 Qc("src/script/interpreter.cpp", "return set_error(serror, SCRIPT_ERR_EVAL_FALSE);", "if (CastToBool(stack.back()) == false)"),
 Qc("src/script/script.h", "inline constexpr unsigned int MAX_SCRIPT_ELEMENT_SIZE = 520;", "inline constexpr int MAX_OPS_PER_SCRIPT = 201;", "inline constexpr int MAX_PUBKEYS_PER_MULTISIG = 20;", "inline constexpr int MAX_SCRIPT_SIZE{10'000};", "inline constexpr int MAX_STACK_SIZE = 1000;"),
 Qc("src/script/script.h", "// Maximum number of non-push operations per script"),
 Qc("src/script/interpreter.cpp", "if (opcode > OP_16 && ++nOpCount > MAX_OPS_PER_SCRIPT) {", "return set_error(serror, SCRIPT_ERR_OP_COUNT);", "return set_error(serror, SCRIPT_ERR_SCRIPT_SIZE);"),
 Qc("src/policy/policy.h", "MAX_STANDARD_P2WSH_SCRIPT_SIZE{3600}", "MAX_STANDARD_SCRIPTSIG_SIZE{1650}"),
 Qc("src/script/solver.cpp", "TxoutType::PUBKEY", "TxoutType::PUBKEYHASH", "TxoutType::SCRIPTHASH", "TxoutType::MULTISIG", "TxoutType::NULL_DATA"),
 Qe("old_bitcoin_v0.3.0_script.cpp", "case OP_RETURN:", "pc = pend;"),
 Qe("old_bitcoin_v0.3.0_script.cpp", "EvalScript(txin.scriptSig + CScript(OP_CODESEPARATOR) + txout.scriptPubKey, txTo, nIn, nHashType)"),
 Qe("old_bitcoin_v0.3.7_script.cpp", "case OP_RETURN:", "return false;", "if (!EvalScript(stack, scriptSig, txTo, nIn, nHashType))", "if (!EvalScript(stack, scriptPubKey, txTo, nIn, nHashType))"),
 Qe("bitcoinwiki_common_vulnerabilities_v1_0_0.txt", "CVE-2010-5141 2010-07-28 wxBitcoin and bitcoind Theft", "OP_RETURN could be used to spend any output."),
 Pp("Chapter_7_AdvancedTransactionsAndScripting_v1_0_0.pptx", "Locking &amp; Unlocking Scripts", "Traditional vs Stack Based Flow Control"),
 # numbers and behaviours, executed with the chapter library (real rules, not the teaching machine)
 X("L.run('', '2 3 OP_ADD 5 OP_EQUAL')", "OK"),
 X("L.run('2', '3 OP_ADD 5 OP_EQUAL')", "OK"),
 X("L.run('', '2 7 OP_ADD 3 OP_SUB 1 OP_ADD 7 OP_EQUAL')", "OK"),
 X("L.run('', '2 3 OP_ADD 6 OP_EQUAL')", "EVAL_FALSE"),
 X("L.run('', '1 IF')", "UNBALANCED_CONDITIONAL"),
 X("[L.cast_to_bool(b) for b in (b'', b'\\x00', b'\\x80', b'\\x01', b'\\x00\\x01')]", [False, False, False, True, True]),
 X("L.run('', '1 OP_RETURN')", "OP_RETURN"),
 X("L.run('1 OP_RETURN', '0')", "OP_RETURN"),
 X("L.run('', '')", "EVAL_FALSE"),
 X("len(L.assemble('1 ' + 'DUP ADD ' * 10).hex()) // 2", 21),
 X("L.run('', '1 ' + 'DUP ADD ' * 10 + ' 1024 EQUAL')", "OK"),
 X("L.run('', ' '.join(['1'] + ['NOP'] * 202))", "OP_COUNT"),
 X("L.run('', ' '.join(['1'] + ['NOP'] * 200))", "OK"),
 X("L.run('', '0x4d0902' + '00' * 521)", "PUSH_SIZE"),
 X("L.run('', ' '.join(['1'] * 1001))", "STACK_SIZE"),
 X("L.run('', '1 ' + 'NOP ' * 10000)", "SCRIPT_SIZE"),
 Qe("bip-0342.mediawiki", "The maximum script size of 10000 bytes does not apply", "The maximum non-push opcodes limit of 201 per script does not apply"),
 Qe("bip-0342.mediawiki", "(v0.1 up to and including v0.3.5)", "The original <code>OP_RETURN</code> terminates script execution immediately, and return pass or fail based on the top stack element at the moment of termination", "unconditional third party theft by placing an <code>OP_RETURN</code> in <code>scriptSig</code>"),
 X("len(__import__('re').findall(r'OP_[A-Z0-9_]+ *= 0x', C.core_raw('src/script/script.h')))", 113),
 X("C.census(L)['pubkeyhash']", 194),
 X("C.census(L)['witness_v0_keyhash']", 626),
 X("sorted(C.census(L).items(), key=lambda kv: -kv[1])[0][0]", "witness_v0_keyhash"),
 X("sum(C.census(L).values())", 1022),
 X("L.classify(bytes.fromhex('76a914ab68025513c3dbd2f7b92a94e0581f5d50f654e788ac'))[0]", "pubkeyhash"),
 X("[len(o[2]) for o in L.get_ops(L.parse_tx(C.tx_record('a1075db55d41')[0]).vin[0][2]) if o[2] is not None]", [73, 65]),
 X("L.classify(bytes.fromhex(C.tx_record('a1075db55d41')[1][0][1]))[0]", "pubkeyhash"),
]
