"""Every computation the SEN0401 chapter 2 lecture deck shows, and the answer the chapter records for it.

1.2.0 adds AttackerSuccess: the whitepaper section 11 catch-up probability, the exact procedure the
chapter research record reproduced against the paper's own table (q=0.1 column equal to 7 decimals).

Generated by sen0401_deck_examples_gen_v1_0_0.py from sen0401_ch02_corpus_v1_2_0.py: each entry is one worked example of that
corpus, recast into the console rows a slide can show (or, where the program needs an indented block, into
the program itself). The outputs are never typed here - examples_run_v1_1_0.py executes every row and
writes them, and refuses to write anything if a recast example stops producing the answer in EXPECT, which
is the corpus's own recorded output.
"""
__version__ = "1.2.0"

PRELUDE = "import datetime\nimport hashlib\nimport math\nimport struct\nimport urllib.parse\nDIGITALSIGNATURE_D1 = 'cf5efe2d8ef13ed0af21d4f4cb82422d6252d70324f6f4576b727b7d918e521c00b51be739df2f899c49dc267c0ad280aca6dab0d2fa2b42a45182fc83e8171301'\n"

# concept id -> the console rows the deck shows; the value of the last row is the output
EX = {
 'AttackerSuccess': [
  "asp = lambda q,z: (lambda p: 1.0 - sum(math.exp(-z*q/p)*(z*q/p)**k/math.factorial(k)*(1-(q/p)**(z-k)) for k in range(z+1)))(1-q)",
  '[round(asp(0.1,z),7) for z in range(7)]',
  '[round(asp(0.3,z),7) for z in range(7)]',
 ],
 'DoubleEntryLedger': [
  'sum([75000, 20000, 5000]) == 100000',
 ],
 'Input': [
  "bytes.fromhex('eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a')[::-1].hex()",
 ],
 'Output': [
  'sum([75000, 20000])',
 ],
 'TransactionFee': [
  '100000 - sum([75000, 20000])',
 ],
 'TransactionSize': [
  '(569 + 3) // 4',
 ],
 'FeeRate': [
  'round(5000 / 143, 2)',
 ],
 'UnspentOutput': [
  "[o for o, spent in {'Tx1:0': True, 'Tx2:0': False, 'Tx2:1': False}.items() if not spent]",
 ],
 'TransactionIdentifier': [
  "bytes.fromhex('eb3ae38f27191aa5f3850dc9cad00492b88b72404f9da135698679268041c54a')[::-1].hex()",
 ],
 'HashFunction': [
  "hashlib.sha256(b'Hello, world!\\n').hexdigest()",
 ],
 'KeyPair': [
  "len(bytes.fromhex('1E99423A4ED27608A15A2616A2B0E9E52CED330AC530EDCC32C8FFC6A526AEDD')) * 8",
 ],
 'PublicKeyCryptography': [
  '[k for k in range(1, 17) if pow(3, k, 17) == 11]',
 ],
 'EllipticCurve': [
  '(0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8 ** 2 - 0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798 ** 3 - 7) % (2 ** 256 - 2 ** 32 - 977)',
 ],
 'DigitalSignature': [
  'len(bytes.fromhex(DIGITALSIGNATURE_D1))',
 ],
 'Checksum': [
  "hashlib.sha256(hashlib.sha256(b'bitcoin').digest()).digest()[:4].hex()",
 ],
 'Script': [
  's = []',
  "[s.append(s.pop() + s.pop()) if t == 'OP_ADD' else s.append(s.pop() == s.pop()) if t == 'OP_EQUAL' else s.append(int(t)) for t in '2 3 OP_ADD 5 OP_EQUAL'.split()] and s",
 ],
 'TransactionChain': [
  '[100000 - 75000 - 20000, 75000 - 67000]',
 ],
 'MakingChange': [
  '20 - 5',
 ],
 'CoinSelection': [
  'vals, need = [60000, 30000, 25000], 80000',
  'next((vals[:i + 1], sum(vals[:i + 1]) - need) for i in range(len(vals)) if sum(vals[:i + 1]) >= need)',
 ],
 'SimplePayment': [
  'ins, outs = [100000], [20000, 75000]',
  '(len(ins), len(outs), sum(ins) - sum(outs))',
 ],
 'Consolidation': [
  'sum([30000, 25000, 20000]) - 1500',
 ],
 'PaymentBatching': [
  'pay = [60000, 55000, 50000, 32000]',
  '(sum(pay), 200000 - sum(pay) - 3000)',
 ],
 'Satoshi': [
  '10**8 // 1000',
 ],
 'Uri': [
  "u = urllib.parse.urlsplit('bitcoin:bc1qk2g6u8p4qm2s2lh3gts5cpt2mrv5skcuu7u3e4?amount=0.01577764')",
  '(u.scheme, u.path, u.query)',
 ],
 'QrCode': [
  "a = 'BC1QK2G6U8P4QM2S2LH3GTS5CPT2MRV5SKCUU7U3E4'",
  '(a == a.upper(), a.isalnum(), len(a))',
 ],
 'Bip': [
  "hdr = '  BIP: 21\\n  Title: URI Scheme\\n  Status: Closed'",
  "dict(l.strip().split(': ', 1) for l in hdr.splitlines() if ': ' in l)['Status']",
 ],
 'Bip21Uri': [
  "urllib.parse.parse_qs(urllib.parse.urlsplit('bitcoin:bc1qk2g6u8p4qm2s2lh3gts5cpt2mrv5skcuu7u3e4?amount=0.01577764&label=Bob%27s%20Store').query)['label'][0]",
 ],
 'TransactionConstruction': [
  'utxo, pay, fee = 100000, 75000, 5000',
  '[utxo - pay - fee, pay]',
 ],
 'BitsAndBytes': [
  "len(bytes.fromhex('4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b')) * 8",
 ],
 'HexadecimalNotation': [
  "(int('ff', 16), int('1d00ffff', 16), len(hex(255)[2:]))",
 ],
 'Entropy': [
  '(2 ** 256).bit_length() - 1',
 ],
 'Nonce': [
  "next(n for n in range(1000) if hashlib.sha256(('Hello, world! %d\\n' % n).encode()).hexdigest().startswith('0'))",
 ],
 'Encryption': [
  "k, m = 0x5a, b'pay Bob'",
  '(bytes(c ^ k for c in m).hex(), bytes(c ^ k for c in bytes(c ^ k for c in m)).decode())',
 ],
 'Serialization': [
  "int.from_bytes(bytes.fromhex('204e000000000000'), 'little')",
 ],
 'ByteOrder': [
  "bytes.fromhex('4ac541802679866935a19d4f40728bb89204d0cac90d85f3a51a19278fe33aeb')[::-1].hex()[:16]",
 ],
 'Outpoint': [
  "txid, vout = '4ac541802679866935a19d4f40728bb89204d0cac90d85f3a51a19278fe33aeb', 1",
  "'%s:%d' % (txid[:8] + '...', vout)",
 ],
 'Address': [
  "a = 'bc1qk2g6u8p4qm2s2lh3gts5cpt2mrv5skcuu7u3e4'",
  '(a[:3], len(a), a.islower())',
 ],
 'ExchangeRate': [
  'round(25.0 / 1584.0, 8)',
 ],
 'Wallet': [
  'utxos, pay, fee = [100000], 75000, 5000',
  'sum(utxos) - pay - fee',
 ],
 'Witness': [
  'total, stripped = 194, 125',
  '(total - stripped, stripped * 3 + total)',
 ],
 'FullNode': [
  "checks = {'syntax': True, 'inputs_nonempty': True, 'amounts_in_range': True, 'outputs_unspent': True, 'scripts_valid': True}",
  'all(checks.values()) and len(checks)',
 ],
 'LightweightClient': [
  'headers, full = 80, 800000',
  'round(full / headers)',
 ],
 'Peer': [
  "peers = {'peer-a', 'peer-b', 'peer-c'}",
  '(len(peers), sorted(peers)[0])',
 ],
 'PeerToPeerNetwork': [
  'n = 5',
  'n * (n - 1) // 2',
 ],
 'Transmission': [
  "routes = {'wired', 'wifi', 'mobile', 'block explorer'}",
  'sorted(routes)',
 ],
 'Gossiping': [
  'peers, rounds = 8, 3',
  'peers ** rounds',
 ],
 'TransactionPropagation': [
  'sec, nodes = 5, 10000',
  'round(nodes / sec)',
 ],
 'Mempool': [
  "pool, mined = ['txA', 'txB', 'txC'], {'txB'}",
  '[t for t in pool if t not in mined]',
 ],
 'RecipientVerification': [
  "outs, mine = [(20000, 'alice'), (75000, 'bob')], 'bob'",
  '[i for i, (amt, owner) in enumerate(outs) if owner == mine]',
 ],
 'BlockExplorer': [
  "q = '466200308696215bbc949d5141a49a4138ecdfdfaa2a8029c1f9bcecd1f96177'",
  "'txid' if len(q) == 64 else 'address' if q.startswith('bc1') else 'height'",
 ],
 'Miner': [
  'subsidy, fees = 625000000, 183000',
  'subsidy + fees',
 ],
 'CandidateBlock': [
  'pool, limit = [120, 150, 200, 90, 400], 3',
  '(len(pool[:limit]), sum(pool[:limit]))',
 ],
 'ProofOfWork': [
  'h = hashlib.sha256',
  "next(n for n in range(200000) if h(('1' + str(n) + 'Alice pays Bob 75000').encode()).hexdigest().startswith('0000'))",
 ],
 'Block': [
  'header, body = 80, 4000000',
  '(header, body // header)',
 ],
 'BlockHeader': [
  'd, s = lambda b: hashlib.sha256(hashlib.sha256(b).digest()).digest(), struct',
  "d(s.pack('<I', 1) + bytes(32) + bytes.fromhex('4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b')[::-1] + s.pack('<III', 1231006505, 0x1d00ffff, 2083236893))[::-1].hex()",
 ],
 'MerkleTree': [
  'd = lambda b: hashlib.sha256(hashlib.sha256(b).digest()).digest()',
  "L = [d(x) for x in (b'A', b'B', b'C', b'D')]",
  'd(d(L[0] + L[1]) + d(L[2] + L[3])).hex()[:16]',
 ],
 'Difficulty': [
  'bits = 0x1d00ffff',
  '(bits >> 24, bits & 0xffffff, (bits & 0xffffff) * 2 ** (8 * ((bits >> 24) - 3)) == 0xffff * 2 ** 208)',
 ],
 'HashRate': [
  'attempts, seconds = 168 * 10 ** 9 * 10 ** 12, 600',
  'attempts // seconds',
 ],
 'ConsensusRules': [
  "rules = {'pow_below_target': True, 'first_tx_is_coinbase': True, 'weight_within_limits': True, 'timestamp_in_range': True, 'all_txs_valid': True}",
  '(sum(rules.values()), all(rules.values()))',
 ],
 'CoinbaseTransaction': [
  'inputs_spent, subsidy, fees = 0, 625000000, 183000',
  '(inputs_spent, subsidy + fees)',
 ],
 'BlockReward': [
  '(50 * 10 ** 8) >> 3',
 ],
 'MiningPool': [
  "shares, reward = {'a': 50, 'b': 30, 'c': 20}, 625000000",
  '{m: reward * s // sum(shares.values()) for m, s in shares.items()}',
 ],
 'SudokuAnalogy': [
  'cells, bitcoin_attempts = 81, 168 * 10 ** 9 * 10 ** 12',
  '(cells, bitcoin_attempts > cells)',
 ],
 'RuleChange': [
  "old_valid, new_valid = {'a', 'b', 'c'}, {'a', 'b'}",
  "'soft fork' if new_valid <= old_valid else 'hard fork'",
 ],
 'Confirmation': [
  'depth = 2',
  'depth + 1',
 ],
 'Probability': [
  'round((0.1 / 0.9) ** 6, 9)',
 ],
 'BestBlockchain': [
  "chains = {'A': [100, 100, 100], 'B': [100, 100, 120]}",
  'max(chains, key=lambda c: sum(chains[c]))',
 ],
 'BlockHeight': [
  'genesis, added = 0, 800000',
  'genesis + added',
 ],
 'AlternativeBlock': [
  'a, b = 5, 5',
  "('fork' if a == b else 'extends', max(a, b) + 1)",
 ],
 'DoubleSpend': [
  "spent, tx = {'4ac54180:1'}, {'input': '4ac54180:1'}",
  "'reject' if tx['input'] in spent else 'accept'",
 ],
 'GenesisBlock': [
  'datetime.datetime.fromtimestamp(1231006505, datetime.timezone.utc).date().isoformat()',
 ],
 'UnconfirmedTransaction': [
  'avg, blocks = 10, 6',
  'avg * blocks',
 ],
 'SmallPaymentAcceptance': [
  'value, threshold = 5, 25',
  "'accept now' if value < threshold else 'wait for confirmations'",
 ],
 'SpendingOnward': [
  'received, paid = 75000, 67000',
  '(received - paid, received - paid == 8000)',
 ],
 'PaymentVerification': [
  'n = 16000',
  'math.ceil(math.log2(n)) * 32',
 ],
 'Ontology': [
  "classes, parents = ['Transaction', 'Input', 'Output', 'Network'], {'Transaction': None, 'Input': 'Transaction', 'Output': 'Transaction', 'Network': None}",
  '(len(classes), sum(1 for c in classes if parents.get(c) is None))',
 ],
 'Triple': [
  "triples = [('Tx2', 'used', 'Tx1:0'), ('Tx2:1', 'wasGeneratedBy', 'Tx2'), ('Tx2', 'wasAttributedTo', 'Alice')]",
  '(len(triples), len({s for s, p, o in triples} | {o for s, p, o in triples}))',
 ],
 'ProvenanceGraph': [
  "chain = ['Tx1:0', 'Tx2:1', 'Tx3:0']",
  "[(b, 'wasDerivedFrom', a) for a, b in zip(chain, chain[1:])]",
 ],
 'HashDemo': [
  "hashlib.sha256(b'Alice pays Bob 75000').hexdigest()[:16]",
 ],
 'BlockDemo': [
  'h = hashlib.sha256',
  "next(n for n in range(500000) if h(('1' + str(n) + 'Alice pays Bob 75000').encode()).hexdigest().startswith('0000'))",
 ],
 'BlockchainDemo': [
  "chain, edited = ['b1', 'b2', 'b3', 'b4', 'b5'], 1",
  '[i for i in range(len(chain)) if i >= edited]',
 ],
 'DistributedDemo': [
  "peers = {'A': 'h5', 'B': 'h5', 'C': 'h5x'}",
  '(len(peers), len(set(peers.values())) == 1)',
 ],
 'CoinbaseDemo': [
  "coinbase, txs = 100, [('A', 'B', 30), ('A', 'C', 20)]",
  'coinbase - sum(amount for _, _, amount in txs)',
 ],
}

# concept id -> a program the deck shows verbatim; the value of `result` is the output
BLOCKS = {
}

# concept id -> the output the chapter corpus records for this example
EXPECT = {
 'AttackerSuccess': '[1.0, 0.6277491, 0.4457171, 0.3245841, 0.2391269, 0.1773523, 0.1321112]',
 'DoubleEntryLedger': 'True',
 'Input': "'4ac541802679866935a19d4f40728bb89204d0cac90d85f3a51a19278fe33aeb'",
 'Output': '95000',
 'TransactionFee': '5000',
 'TransactionSize': '143',
 'FeeRate': '34.97',
 'UnspentOutput': "['Tx2:0', 'Tx2:1']",
 'TransactionIdentifier': "'4ac541802679866935a19d4f40728bb89204d0cac90d85f3a51a19278fe33aeb'",
 'HashFunction': "'d9014c4624844aa5bac314773d6b689ad467fa4e1d1a50a1b8a99d5a95f72ff5'",
 'KeyPair': '256',
 'PublicKeyCryptography': '[7]',
 'EllipticCurve': '0',
 'DigitalSignature': '65',
 'Checksum': "'f1ef1bf1'",
 'Script': '[True]',
 'TransactionChain': '[5000, 8000]',
 'MakingChange': '15',
 'CoinSelection': '([60000, 30000], 10000)',
 'SimplePayment': '(1, 2, 5000)',
 'Consolidation': '73500',
 'PaymentBatching': '(197000, 0)',
 'Satoshi': '100000',
 'Uri': "('bitcoin', 'bc1qk2g6u8p4qm2s2lh3gts5cpt2mrv5skcuu7u3e4', 'amount=0.01577764')",
 'QrCode': '(True, True, 42)',
 'Bip': "'Closed'",
 'Bip21Uri': '"Bob\'s Store"',
 'TransactionConstruction': '[20000, 75000]',
 'BitsAndBytes': '256',
 'HexadecimalNotation': '(255, 486604799, 2)',
 'Entropy': '256',
 'Nonce': '32',
 'Encryption': "('2a3b237a183538', 'pay Bob')",
 'Serialization': '20000',
 'ByteOrder': "'eb3ae38f27191aa5'",
 'Outpoint': "'4ac54180...:1'",
 'Address': "('bc1', 42, True)",
 'ExchangeRate': '0.01578283',
 'Wallet': '20000',
 'Witness': '(69, 569)',
 'FullNode': '5',
 'LightweightClient': '10000',
 'Peer': "(3, 'peer-a')",
 'PeerToPeerNetwork': '10',
 'Transmission': "['block explorer', 'mobile', 'wifi', 'wired']",
 'Gossiping': '512',
 'TransactionPropagation': '2000',
 'Mempool': "['txA', 'txC']",
 'RecipientVerification': '[1]',
 'BlockExplorer': "'txid'",
 'Miner': '625183000',
 'CandidateBlock': '(3, 470)',
 'ProofOfWork': '6630',
 'Block': '(80, 50000)',
 'BlockHeader': "'000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f'",
 'MerkleTree': "'59e82c45a3662f55'",
 'Difficulty': '(29, 65535, True)',
 'HashRate': '280000000000000000000',
 'ConsensusRules': '(5, True)',
 'CoinbaseTransaction': '(0, 625183000)',
 'BlockReward': '625000000',
 'MiningPool': "{'a': 312500000, 'b': 187500000, 'c': 125000000}",
 'SudokuAnalogy': '(81, True)',
 'RuleChange': "'soft fork'",
 'Confirmation': '3',
 'Probability': '1.882e-06',
 'BestBlockchain': "'B'",
 'BlockHeight': '800000',
 'AlternativeBlock': "('fork', 6)",
 'DoubleSpend': "'reject'",
 'GenesisBlock': "'2009-01-03'",
 'UnconfirmedTransaction': '60',
 'SmallPaymentAcceptance': "'accept now'",
 'SpendingOnward': '(8000, True)',
 'PaymentVerification': '448',
 'Ontology': '(4, 2)',
 'Triple': '(3, 4)',
 'ProvenanceGraph': "[('Tx2:1', 'wasDerivedFrom', 'Tx1:0'), ('Tx3:0', 'wasDerivedFrom', 'Tx2:1')]",
 'HashDemo': "'320a22eeeb9c0391'",
 'BlockDemo': '6630',
 'BlockchainDemo': '[1, 2, 3, 4]',
 'DistributedDemo': '(3, False)',
 'CoinbaseDemo': '50',
}
