"""Every computation the SEN0401 chapter 1 lecture deck shows, and the answer the chapter records for it.

Generated by sen0401_deck_examples_gen_v1_0_0.py from sen0401_ch01_corpus_v1_2_0.py: each entry is one worked example of that
corpus, recast into the console rows a slide can show (or, where the program needs an indented block, into
the program itself). The outputs are never typed here - examples_run_v1_1_0.py executes every row and
writes them, and refuses to write anything if a recast example stops producing the answer in EXPECT, which
is the corpus's own recorded output.
"""
__version__ = "1.1.0"

PRELUDE = 'import datetime\nimport decimal\nimport hashlib\nimport hmac\nimport json\nimport math\nimport urllib.parse\nBLOCK_D1 = \'{"id":"0000000000000000000320283a032748cef8227873ff4872689bf23f1cda83a5","height":840000,"version":710926336,"timestamp":1713571767,"tx_count":3050,"size":2325617,"weight":3993281,"merkle_root":"031b417c3a1828ddf3d6527fc210daafcc9218e81f98257f88d4d43bd7a5894f","previousblockhash":"0000000000000000000172014ba58d66455762add0512355ad651207918494ab","mediantime":1713570208,"nonce":3932395645,"bits":386089497,"difficulty":86388558925171.02}\'\nBLOCK_D2 = \'{"id":"000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f","height":0,"version":1,"timestamp":1231006505,"tx_count":1,"size":285,"weight":1140,"merkle_root":"4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b","previousblockhash":null,"mediantime":1231006505,"nonce":2083236893,"bits":486604799,"difficulty":1.0}\'\n'

# concept id -> the console rows the deck shows; the value of the last row is the output
EX = {
 'SatoshiUnit': [
  "int(decimal.Decimal('0.001') * 10**8)",
 ],
 'SupplyCap': [
  'sum((50 * 10**8 >> era) * 210000 for era in range(33)) / 10**8',
 ],
 'Halving': [
  '(50 * 10**8 >> 840000 // 210000) / 10**8',
 ],
 'BlockSubsidy': [
  '[(50 * 10**8 >> h // 210000) / 10**8 for h in (0, 210000, 420000, 630000, 840000)]',
 ],
 'FloatingExchangeRate': [
  'round(0.001 * 60000, 2)',
 ],
 'VolumeWeightedAverage': [
  'sum(p * v for p, v in [(100, 3), (104, 1)]) / sum(v for p, v in [(100, 3), (104, 1)])',
 ],
 'Deflation': [
  'str((datetime.datetime(2009, 1, 3, 18, 15, 5) + datetime.timedelta(seconds=6_930_000 * 600)).date())',
 ],
 'ProofOfWork': [
  "next(n for n in range(10**6) if hashlib.sha256(f'SEN0401-{n}'.encode()).hexdigest().startswith('0000'))",
 ],
 'DoubleSpend': [
  "[(c not in s) and not s.add(c) for s in [set()] for c in ('coin7', 'coin7')]",
 ],
 'Mining': [
  '24 * 60 // 10',
 ],
 'DifficultyAdjustment': [
  '14 * 24 * 60 * 60 // (10 * 60)',
 ],
 'Hashcash': [
  "format(int(hashlib.sha256(b'SEN0401-15083').hexdigest(), 16), '0256b').index('1')",
 ],
 'BitcoinImprovementProposal': [
  '[(ent, ent // 32, (ent + ent // 32) // 11) for ent in (128, 256)]',
 ],
 'RecoveryCode': [
  "len('nephew dog crane clever quantum crazy purse traffic repeat fruit old clutch'.split())",
 ],
 'Invoice': [
  "int(decimal.Decimal(urllib.parse.parse_qs('amount=0.01577764&label=Bob%27s%20Store')['amount'][0]) * 10**8)",
 ],
 'SendingAndReceiving': [
  '(0.001 * 10**3, round(0.001 * 10**8))',
 ],
 'Transaction': [
  "{'to': 'Alice', 'amount_sat': 100000}['amount_sat'] / 10**8",
 ],
 'InputsAndOutputs': [
  '(sum([110000]), sum([100000, 5000]))',
 ],
 'TransactionFee': [
  '110_000 - 100_000',
 ],
 'Confirmation': [
  'm, q, z = math, 0.1, 6',
  'p = 1 - q',
  'l = z * q / p',
  'round(1 - sum(m.exp(-l) * l**k / m.factorial(k) * (1 - (q / p)**(z - k)) for k in range(z + 1)), 7)',
 ],
 'HashFunction': [
  "hashlib.sha256(b'abc').hexdigest()",
 ],
 'DigitalSignature': [
  'n, e, d, m = 3233, 17, 2753, 65',
  '(pow(m, d, n), pow(pow(m, d, n), e, n) == m, pow(pow(m, d, n), e, n) == 66)',
 ],
 'PublicKeyCryptography': [
  'pow(pow(65, 17, 3233), 2753, 3233)',
 ],
 'PrivateKey': [
  'len(str(2**256))',
 ],
 'Entropy': [
  '(2048 .bit_length() - 1, 12 * 11, 128 + 128 // 32)',
 ],
 'Checksum': [
  'hashlib.sha256(bytes(16)).digest()[0] >> 4',
 ],
 'KeyedHash': [
  "len(hmac.new(b'key', b'message', 'sha512').digest())",
 ],
 'Block': [
  "(json.loads(BLOCK_D1)['tx_count'], json.loads(BLOCK_D2)['tx_count'])",
 ],
 'Timestamp': [
  'str(datetime.datetime.fromtimestamp(1231006505, datetime.timezone.utc))',
 ],
 'Http': [
  "'GET /index.html HTTP/1.1'.split(' ')",
 ],
 'Api': [
  "'sha256' in hashlib.algorithms_guaranteed",
 ],
 'Uri': [
  "u = urllib.parse.urlsplit('bitcoin:175tWpb8K1S7NmH4Zx6rewF9WQrcZv245W?amount=20.3&label=Luke-Jr')",
  '(u.scheme, u.path, u.query)',
 ],
 'QrCode': [
  '[21 + 4 * (v - 1) for v in (1, 40)]',
 ],
 'Database': [
  "rows = [{'address': 'addr1', 'label': 'Alice'}, {'address': 'addr2', 'label': 'Joe'}]",
  "index = {r['address']: r for r in rows}",
  "(index['addr1']['label'], [r['label'] for r in rows if r['address'] == 'addr2'], 'addr3' in index)",
 ],
 'BitsAndBytes': [
  "(len(hashlib.sha256(b'').digest()), len(hashlib.sha256(b'').hexdigest()))",
 ],
 'Virtual': [
  "txs = [('Joe', 'Alice', 100_000), ('Alice', 'Eve', 30_000), ('Joe', 'Eve', 5_000)]",
  'def balance(who): return sum(a for f, t, a in txs if t == who) - sum(a for f, t, a in txs if f == who)',
  "(balance('Alice'), balance('Eve'))",
 ],
}

# concept id -> a program the deck shows verbatim; the value of `result` is the output
BLOCKS = {
 'KeyStretching': "import hmac\npassword, salt, iters = b'abandon', b'mnemonic', 2048\nu = hmac.new(password, salt + bytes([0, 0, 0, 1]), 'sha512').digest()\nseed = u\nfor _ in range(iters - 1):\n    u = hmac.new(password, u, 'sha512').digest()\n    seed = bytes(a ^ b for a, b in zip(seed, u))\nresult = (len(seed), seed.hex()[:8])",
 'Blockchain': "import hashlib\ndef link(prev, data): return hashlib.sha256((prev + data).encode()).hexdigest()\ndata = ['Joe pays Alice 1', 'Alice pays Eve 2', 'Eve pays Joe 3']\ndef build(items):\n    hs, prev = [], 'genesis'\n    for d in items:\n        prev = link(prev, d); hs.append(prev)\n    return hs\nstored = build(data)\ntampered = ['Joe pays Alice 100'] + data[1:]\nresult = (build(data) == stored, build(tampered) == stored)",
 'PeerToPeerProtocol': "links = {'A': ['B', 'C'], 'B': ['A', 'D'], 'C': ['A', 'E'], 'D': ['B', 'F'], 'E': ['C', 'F'], 'F': ['D', 'E', 'G'], 'G': ['F']}\nseen, frontier, rounds = {'A'}, {'A'}, 0\nwhile len(seen) < len(links):\n    frontier = {n for f in frontier for n in links[f]} - seen\n    seen |= frontier; rounds += 1\nresult = rounds",
 'ConsensusRuleSet': 'def accept(claim, height, fees):\n    subsidy = (50 * 10**8) >> (height // 210000)\n    return claim <= subsidy + fees\nresult = [accept(312_500_000, 840000, 0), accept(312_500_001, 840000, 0), accept(325_000_000, 840000, 12_500_000)]',
 'PaymentChannel': 'onchain, a, b = 2, 60_000, 40_000\nfor _ in range(100):\n    a, b = a - 10, b + 10\nresult = (a, b, a + b, onchain)',
 'LightningNetwork': "channels = {('Alice', 'Bob'), ('Bob', 'Carol'), ('Carol', 'Dave')}\nnbr = {}\nfor x, y in channels: nbr.setdefault(x, []).append(y); nbr.setdefault(y, []).append(x)\npath, frontier = {'Alice': ['Alice']}, ['Alice']\nwhile 'Dave' not in path:\n    nxt = []\n    for x in frontier:\n        for y in nbr[x]:\n            if y not in path: path[y] = path[x] + [y]; nxt.append(y)\n    frontier = nxt\nresult = (path['Dave'], len(path['Dave']) - 1, ('Alice', 'Dave') in channels)",
}

# concept id -> the output the chapter corpus records for this example
EXPECT = {
 'SatoshiUnit': '100000',
 'SupplyCap': '20999999.9769',
 'Halving': '3.125',
 'BlockSubsidy': '[50.0, 25.0, 12.5, 6.25, 3.125]',
 'FloatingExchangeRate': '60.0',
 'VolumeWeightedAverage': '101.0',
 'Deflation': "'2140-10-08'",
 'ProofOfWork': '15083',
 'DoubleSpend': '[True, False]',
 'Mining': '144',
 'DifficultyAdjustment': '2016',
 'Hashcash': '16',
 'BitcoinImprovementProposal': '[(128, 4, 12), (256, 8, 24)]',
 'RecoveryCode': '12',
 'Invoice': '1577764',
 'SendingAndReceiving': '(1.0, 100000)',
 'Transaction': '0.001',
 'InputsAndOutputs': '(110000, 105000)',
 'TransactionFee': '10000',
 'Confirmation': '0.0002428',
 'HashFunction': "'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'",
 'DigitalSignature': '(588, True, False)',
 'PublicKeyCryptography': '65',
 'PrivateKey': '78',
 'Entropy': '(11, 132, 132)',
 'Checksum': '3',
 'KeyedHash': '64',
 'KeyStretching': "(64, 'd96147bf')",
 'Block': '(3050, 1)',
 'Blockchain': '(True, False)',
 'Timestamp': "'2009-01-03 18:15:05+00:00'",
 'Http': "['GET', '/index.html', 'HTTP/1.1']",
 'Api': 'True',
 'Uri': "('bitcoin', '175tWpb8K1S7NmH4Zx6rewF9WQrcZv245W', 'amount=20.3&label=Luke-Jr')",
 'QrCode': '[21, 177]',
 'Database': "('Alice', ['Joe'], False)",
 'BitsAndBytes': '(32, 64)',
 'Virtual': '(70000, 35000)',
 'PeerToPeerProtocol': '4',
 'ConsensusRuleSet': '[True, False, True]',
 'PaymentChannel': '(59000, 41000, 100000, 2)',
 'LightningNetwork': "(['Alice', 'Bob', 'Carol', 'Dave'], 3, False)",
}
